### ISSUE TITLE
Edit Form Properties

### ISSUE THREAD

**Issue by seamusjunior** [OrchardCMS/Orchard#5153]
Version Orchard 1.9 

When editing a custom Form.  And Editing the "Form" object the details don't save.
See attached Image Steps.  You see I try to change the name of the form but I reverts back to untitled after saving.
## Edit Form 
![step1](https://cloud.githubusercontent.com/assets/1537210/7140428/13a50f4c-e2c3-11e4-8c6f-797832134226.PNG)
## Change Form Name
![step2](https://cloud.githubusercontent.com/assets/1537210/7140427/13a396e4-e2c3-11e4-844d-05563fcbe8f5.PNG)
## Click Save
![step3](https://cloud.githubusercontent.com/assets/1537210/7140426/13a1b180-e2c3-11e4-97c0-7efa60dbfe53.PNG)
## Name reverts to Untitled
![step4](https://cloud.githubusercontent.com/assets/1537210/7140429/13a53c42-e2c3-11e4-9822-39c494f94031.PNG)

**Comment by douwinga** [comment]
I had this same problem with a custom container element we wrote. It appears that the JSON returned in args.elementEditorModel in the form directive is no longer being parsed.

A workaround we use for now is doing JSON.parse on args.elementEditorModel
```javascript
var editorModel = JSON.parse(args.elementEditorModel);
$scope.element.name = editorModel.name;
$scope.element.formBindingContentType = editorModel.formBindingContentType;
```

**Comment by sfmskywalker** [comment]
That's a bug recently introduced - the ```elementEditorModel``` should be parsed as JSON before triggering the "command" event. Will push a fix shortly.
