### ISSUE TITLE
Cleanup old branches

### ISSUE THREAD

**Issue by mylemans** [OrchardCMS/Orchard#5158]
Maybe now is the time to clean up old branches (read: delete them) to get a better overview?

**Comment by dcinzona** [comment]
Should "Master" be latest public release?

**Comment by MpDzik** [comment]
+1

**Comment by ASADeveloper** [comment]
Please do. +1

**Comment by sebastienros** [comment]
> Should "Master" be latest public release?

Master has always been that

**Comment by Ermesx** [comment]
:+1:

**Comment by Skrypt** [comment]
Closing this. #6583 explains the latest merge plan.
