### ISSUE TITLE
Adding field to content type and showing within blog widget (recent posts) - how to?

### ISSUE THREAD

**Issue by dyardyGIT** [OrchardCMS/Orchard#5169]
I want to add an image which will be displayed on the recent blog post widget shown on my home page. 
I am using orchard 1.8.1 

I am finding a lot of information that seems to be out/outdated and not applicable to 1.8.1 (i.e. the designer tools module 1.6 does not work in 1.8.1) 

Where can i find information on how to add change the content of the recent blog posts part to show the newly added feature image (added to the blog post content type) 

Little frustrating because the shapes feature is enabled but nothing is visible either. Not sure if broken/changed or what. 

thx -dave

**Comment by sebastienros** [comment]
Please ask this question on the forum https://orchard.codeplex.com/discussions
