### ISSUE TITLE
Email field element causes compilation error in 1.9-int

### ISSUE THREAD

**Issue by douwinga** [OrchardCMS/Orchard#5183]
After commit https://github.com/OrchardCMS/Orchard/commit/c61e08abd956fa997b9962808e4db01aa7ee6edd there is still a remaining view compilation error with email field elements

Here is the error message:
'Orchard.DisplayManagement.Shapes.OrchardTagBuilder' has no applicable method named 'AddClientValidationAttributes' but appears to have an extension method by that name. Extension methods cannot be dynamically dispatched. Consider casting the dynamic arguments or calling the extension method without the extension method syntax.

**Comment by sfmskywalker** [comment]
Fixed
