### ISSUE TITLE
Deprecate, then remove Orchard.Core.Common.Utilities.LazyField

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/Orchard#5191]
...since there is another LazyField, in Orchard.ContentManagement.Utilities. The latter seem to be used everywhere any way.
There is a slight difference between the two, the loader delegate in the one in Orchard.ContentManagement.Utilities also gets fed the existing value of the field. This is quite strange however since the LazyField can only already have a value when the loader delegate is executed, when it got its value set previously (and actually it's also necessary that the loader should be set after the value was set).

**Comment by thekaveman** [comment]
:+1: I always wondered why there were two...

**Comment by MpDzik** [comment]
:+1: I find that confusing as well.

**Comment by sebastienros** [comment]
I remember sitting in my office with @rpaquay working on this class, and trust me when I say the difference made sense at that time. However if we can refactor it to use the other one and make it obsolete then I am not opposed to it. Not deleting it as it could potentially break external packages, just in a later version.

**Comment by Piedone** [comment]
Only if there was a thing (like comments) to record such volatile memories! :-D
I also meant to deprecate with `[Obsolete]`, then remove some time later.
