### ISSUE TITLE
Improve Tokens UI

### ISSUE THREAD

**Issue by thekaveman** [OrchardCMS/Orchard#5193]
#2202 is an old issue, but the point is still valid: the tokens popup 1) doesn't always contain enough information, and 2) can be difficult to navigate when many modules are contributing tokens.

Can/should this be improved? Some ideas include:
  - Modal popup a la ContentPicker/MediaPicker
  - Increasing the popup width (currently hard-coded at 700px) or making it more dynamic (e.g. 75%)
  - Removing the label, just showing the actual token and its description

Personally, I think something more along the lines of a modal would give the most flexibility; that popup is rather limiting.

**Comment by Piedone** [comment]
Related: #3224

**Comment by thekaveman** [comment]
Oh I didn't see that one...pretty much a duplicate, I think this can be closed then?

**Comment by thekaveman** [comment]
Closing as a dupe
