### ISSUE TITLE
Orchard.Core.Contents.Controllers.AdminController - >List

### ISSUE THREAD

**Issue by vesko-k** [OrchardCMS/Orchard#5203]
1.Create new Role e.g. (test) 
2.Stop access to everything of that role, but give it access to the admin pannel and access to the front end. 
3.Create new user (e.g test). 
4.Assign test user to the test role.

Login with the specified user and go to the admin dashboard. 

 Click on the "Content" link. 

 The result is that all creatable, non creatable content is listed, layers, menus, widgets, everything.

The problem is when the user does not have access to any creatable type, then GetCreatableTypes returns an empty list and thus 

``` C#
_contentManager.Query(versionOptions, GetCreatableTypes(false).Select(ctd => ctd.Name).ToArray()) 
```

executes without Type filter, which causes all content to be returned.

One possible solutions is to add the following snippet before executing the content manager query:

``` C#
var creatableTypes = GetCreatableTypes(false).ToArray();
if (creatableTypes.Count() == 0)
{
         model.Options.FilterOptions = Enumerable.Empty<KeyValuePair<string, string>>();
         return View(Shape.ViewModel().Options(model.Options));
}
```

In the latest source code of Orchard, GetCreatableTypes is renamed to GetListableTypes and the only difference is that the query asks for listable instead of creatable types, but nevertheless bug remains.

**Comment by TFleury** [comment]
@sebastienros  Should be closed.

I reproduced the same scenario on 1.10.1 the only issue was #6890 which has been fixed in dev branch.

**Comment by sebastienros** [comment]
Thanks for letting us know
