### ISSUE TITLE
Last 1.8.2-int commit (about filter execution order) not merged in 1.x, 1.8.x, 1.9-int

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#5204]
Is it normal that the last commit of 1.8.2-int
#21218: Fixing IFilterProvider execution order
isn't merged in 1.x, 1.8.x, 1.9-int ?

Best

**Comment by Piedone** [comment]
Yes. Before the release 1.8.2-int will be merged into 1.9-int, as well as the int branches will be merged back to the x branches.
