### ISSUE TITLE
OutputCache backword compatibility

### ISSUE THREAD

**Issue by mdameer** [OrchardCMS/Orchard#5210]
Dear,
Please remove the read only restriction from "ValidFor" Property in the CacheItem class, to make sure it's compatible with older modules.

**Comment by Piedone** [comment]
Which module does it break?

**Comment by mdameer** [comment]
Module: Mdameer.ContentOutputCache
I was built this module based on Orchard.OutputCache, but I can upgrade it to support the new version.

**Comment by sebastienros** [comment]
I will blame @DanielStolt at our next meeting, but it's too late now. It's on 1.9 so some other breaking changes are expected, please update your module.
