### ISSUE TITLE
Importing Blog?

### ISSUE THREAD

**Issue by thejrose1984** [OrchardCMS/Orchard#5212]
Hello, I was tasked with sorting out my company's website, which was recently redesigned in Orchard CMS. I noticed that the blog, which the designer originally told us would resemble WordPress, is nowhere near in quality. In addition, the blog doesn't list entries by their titles.

Can anyone point me in the right direction for troubleshooting and resolving the issues with the blog module? In addition, if there's a module that can be used to import content from a WordPress blog I would find it immensely useful if someone could provide a URL/Wiki so I couldn't find anything from searching on GitHub as well as http://orchard.codeplex.com and http://doc.orchardproject.net

**Comment by Skrypt** [comment]
You can use the import/export module of Orchard. Here are some ideas : 

https://orchard.codeplex.com/discussions/397451

**Comment by thejrose1984** [comment]
Thanks @Skrypt I figured the import feature would do the trick. Now for another  "silly" question. Why does the blog not format its pages to match the installed theme? Also, why does the blog's main page not allow any non-text content (e.g. photos or videos)? Again, am I missing something here?

**Comment by Skrypt** [comment]
You can go to "Content Definition" and customize your content types with Orchard. That's how you do it. Then you can also customize your views.

**Comment by thejrose1984** [comment]
Thanks again @Skrypt. I looked under Content Definition and found Blogs and tried fiddling with some settings, but there doesn't seem to be any obvious changes that can be seen. Also, under Patterns (see provided screenshot), I'm noticing a 'Content.Slug' as a pattern definition. Again, am I missing something here? I did not write the site, but merely implemented it using the code and SQL dump provided to me. Any feedback would be appreciated.

![2015-04-28 17_54_16-sandata - edit content type - blog](https://cloud.githubusercontent.com/assets/7573083/7381256/9f530c08-edcf-11e4-96de-67dcc86bcc28.png)

**Comment by Skrypt** [comment]
On that page you can add a Field. Name that field "Photo" then select the Media Library Picker Field as the type. Go back to edit/create your blog, you will see now a new "Photo" field added to that form/page so that you can add your image or else. After that, you can modify your .cshtml file in your theme so that it will display that media item. Look at the documentation on the Orchard website or Codeplex forum to find some examples.

**Comment by thejrose1984** [comment]
Still having issues, but fairly certain it's an issue with the way the developer customized the site. Will close this issue and research further using the information provided above. Thanks again @Skrypt I appreciate your patience, understanding, and assistance.
