### ISSUE TITLE
Exception in features view of module Orchard.Modules

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [OrchardCMS/Orchard#5214]
Hi,

i was playing around with some modules today and i came to a point where Orchard was not running anymore. I tracked it down to the file

```
src\Orchard.Web\Modules\Orchard.Modules\Views\Admin\Features.cshtml
```

and the following line that looks like this

```
var dependencies = (from d in feature.Descriptor.Dependencies
                    select (from f in Model.Features where f.Descriptor.Id.Equals(d, StringComparison.OrdinalIgnoreCase) select f).SingleOrDefault()).Where(f => f != null).OrderBy(f => f.Descriptor.Name);
```

The call to **SingleOrDefault() throws an exception** when a user copies a module in the Modules folder and therefore two Module.txt files with the same content exist. I think it would be better to call **FirstOrDefault()** as it

a) does not crash
b) shows features correctly (in my case one feature multiple times) in the admin features view

So lonG

**Comment by sebastienros** [comment]
Agreed, let's use `FirstOrDefault`, but we also need a check for this case, and display an error notification.

**Comment by ViRuSTriNiTy** [comment]
Can't reproduce this anymore, therefore no need to fix something.
