### ISSUE TITLE
Submit Button missing from DynamicForm

### ISSUE THREAD

**Issue by davegardner** [OrchardCMS/Orchard#5217]
Using  1.9-int, create a new site
Enable Dynamic Forms
Create a new Form
Add a Form Element to the Layout. Enable Store Submission, Create Content and Publish
Add a Text Field. Set the Field and add a Label.
Publish Now.
==> 
1. No option to create a menu item, so manually navigate to the form on the front end .
2. The form is displayed but without a Submit Button.

Am I jumping the gun expecting Dynamic Forms to work at this point? Or more likely I have missed something in setting it up?

**Comment by sfmskywalker** [comment]
1. To enable the option to add the form to the menu, attach the MenuPart to the Form content type.
2. You need to manually ads the Button element to the form. However, I think it would make sense to preconfigure the Form content type with a default Form and Button element. We have this feature but seems to be broken a.t.m. I'll create a separate issue for that.
