### ISSUE TITLE
Razor intellisence not working in new module  because of Orchard.Framework.csproj not copied locally

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/Orchard#5219]
To repro 
Create a new module using codegen create module 
Create a razor view file . Intellisense is not working 

To fix
From references change the Orchard.Framework reference property "Copy Local" from false to true.

    <ProjectReference Include="..\..\..\Orchard\Orchard.Framework.csproj">
      <Project>{2D1D92BB-4555-4CBE-8D0E-63563D6CE4C6}</Project>
      <Name>Orchard.Framework</Name>
      <Private>True</Private>
    </ProjectReference>

Now intellisence is restored.

**Comment by Piedone** [comment]
Isn't only that you have to build the solution first? I think this is the case with Copy Local = true still.

**Comment by giannik** [comment]
Nope , Tried it. 
Maybe if we change the web.config to point to correct base razor file it might work. Will have to try.
I like the fact the it has reduced the size of files with this setting, but not having  intellisence is bad.
Thanks.

**Comment by giannik** [comment]
Just to be clear, whats not working is the base orchard stuff for razor view. 
For example writing:
Style.Include("mystyle") is not working.

**Comment by Piedone** [comment]
I see. This is some serious problem then.

**Comment by giannik** [comment]
A solution to make it work is to  add in web.config of project which has  CopyLocal=false the 
Orchard.Framework assembly reference as shown below.
  
![image](https://cloud.githubusercontent.com/assets/1516981/7437182/1137094c-f05e-11e4-905d-8cb409115e7d.png)



Found the answer here.

http://stackoverflow.com/questions/4953330/razor-based-view-doesnt-see-referenced-assemblies


Maybe it would need to be done for Orchard.Core as well since it also has CopyLocal=False

**Comment by sfmskywalker** [comment]
That works.

**Comment by Xeevis** [comment]
I consider **Copy Local** to be extremely annoying feature for web projects and I always turn it off for all internal references in my Orchard modules. I welcomed change in 1.x that turned it off for `Orchard.Core` and `Orchard.Framework`, but I'd take it further and modify all core modules as well. 

It's a small change to all `web.config`s (necessary only for intellisense), but huge reduction in size. There are hundreds of duplicates, just `Orchard.Tokens.dll` after publish has cca 28 duplicates scattered in different module bin folders. Why? Module dependency already ensures those assemblies are present in App_Data/Dependencies no?

**Comment by sfmskywalker** [comment]
I agree that we should apply the same changes for the most commonly used core modules such as Tokens and Forms as well to reduce the build output size even further.

**Comment by sfmskywalker** [comment]
I updated lmost all project references by setting CopyLocal=False, but I didn't see a huge gain in terms of smaller build output - only about 30 megabytes. Are you seeing something else?

**Comment by Xeevis** [comment]
Yes I do, hundreds of megs, have you deleted bin folders before rebuilding? Visual Studio doesn't clean it up automatically, I have created new issue for this #5272
