### ISSUE TITLE
Awaiting activities not cleared on workflow updating (fix included)

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#5235]
__Repro:__
 - Create a worflow with a starting activity (e.g Content Published)
 - Add a timer activity (e.g 5 minutes)... And save your workflow
 - Publish a content item to start your workflow and wait a little
 - Then, edit, optionally update, and save again your workflow
 - At this point, your workflow has been updated and stopped

__Issue:__
 - 1) The workflow is still listed as running in the "Workflows Definitions" page
 - 2) And in the "Running workflows" page related to the item, you get an exception

__Analysis:__
 - 1) The timer awaiting Activity isn't cleared when the workflow is saved
 - 2) This awaiting activity is linked to an activity that doesn't exist

__Fix:__
In AdminController.cs, EditPost() action, after this line

    workflowDefinitionRecord.ActivityRecords.Clear();

Add this line

    workflowDefinitionRecord.WorkflowRecords.Clear();

This way, the related workflows and their awaiting activities will be cleared

Best

**Comment by sebastienros** [comment]
I can't find where, but I am pretty sure we commented on the same issue explaining the recommended fix. The idea is to display a confirmation message on Save if there are any running instances,. And if accepted then go on with deleting the instances.

**Comment by jtkech** [comment]
Oh yes, but, when editing a worflow definition, there is no info about the associated workflows in the current view model. Anyway, I think we need to see if they are running instances at the time the user clicks on the "Save" button

So, to get this needed sync info on "Save", I've added an ajax get request that targets a new controller action. But not sure I've done it the right Orchard way, with right names... Let me know

**Comment by jtkech** [comment]
Fixed, the related PR has been committed
