### ISSUE TITLE
In Media library, Site, Import you can not click on breadcrumb Media Folders  

### ISSUE THREAD

**Issue by veldenamw** [OrchardCMS/Orchard#5237]
On Site , Create folder you can click on breadcrumb Media Library and breadcrumb Site to go back.
But when you are in Media library, Site and you click on Import, then you can not click on breadcrumb Media Folders because this is not a link. 

![media site import no breadcrumb](https://cloud.githubusercontent.com/assets/12233438/7453156/9a4e7918-f266-11e4-9340-c6123b57ef94.jpg)

**Comment by veldenamw** [comment]
By mistake i had closed the issue, so i have reopen it.

**Comment by sfmskywalker** [comment]
Fixed.
