### ISSUE TITLE
Feature Req: Create aliases using the Alias UI to external resources (URLs)

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5240]
The Alias UI is great, but things get a bit fragmented when we need to create short urls that redirect users to other websites or pages (which happens quite a bit when we are working on campaigns).

It would also be nice to be able to search aliases (so giving the alias a title / description that can be indexed).  

Aliases that are created automatically by content items could get the title from the title part of the content item.

**Comment by Piedone** [comment]
I don't think that the ability to create redirect links is a feature that Alias should be concerned about: it's about creating URIs for local contents.

**Comment by dcinzona** [comment]
Why can't it do both?

**Comment by Piedone** [comment]
I think it's something completely different. Sure it's both about URLs but other than that I don't think it's a related feature-set.

**Comment by dcinzona** [comment]
Hmmm.. ok.  I'm not so sure I agree, but I see your point.
Thanks!

**Comment by Skrypt** [comment]
Alias is about creating url rewriting. Using external url's would not make sense. But the search feature in the Alias UI is a good idea.

**Comment by ropstah** [comment]
@dcinzona you could create a custom record and store the external url information in there and use an alias to point to a RedirectController which loads the record and redirects based on that.

**Comment by bleroy** [comment]
Please use the Rewrite Rules module. It's designed to set-up redirects. http://gallery.orchardproject.net/List/Modules/Orchard.Module.Contrib.RewriteRules
