### ISSUE TITLE
Custom Forms is deprecated in 1.9 right?

### ISSUE THREAD

**Issue by abhishekluv** [OrchardCMS/Orchard#5247]
Custom Forms is deprecated in 1.9 right? I just downloaded the release preview of Orchard.web.1.9 and I can still see the Custom Forms option in the Module area.

**Comment by Piedone** [comment]
It kind of is, but good point, we actually haven't talked about what to communicate about it. But any way it won't be removed just now as you can't force people to migrate immediately.

**Comment by Xeevis** [comment]
How about removing deprecated modules from distro and instead provide them on-demand from gallery &/or repository, wouldn't that suffice?

**Comment by Piedone** [comment]
I don't think that would be a good idea still. Better would be to 1) document and 2) indicate on the Features screen somehow if a module has been deprecated/succeeded (see: #3829).

**Comment by abhishekluv** [comment]
Good idea.we can even include a text saying check out or use dynamic forms.

**Comment by rtpHarry** [comment]
This is now fixed, see #5271
