### ISSUE TITLE
Dropdown for content localization does not default to currently selected culture

### ISSUE THREAD

**Issue by Xeevis** [OrchardCMS/Orchard#5261]
## Tested on 1.9
1. Go to site Settings and add another language
2. Go to modules and enable `Culture Picker`
3. In the culture picker select this new culture
4. Go to Page creation
5. Under `Content Localization` there is always **en-US** selected by default instead of what is selected in the culture picker (at least I think it should work that way)

At the **Localization.ContentTranslations.Edit.cshtml** there is function for selecting it `BuildSelectedCultureList`, but `Model.SelectedCulture` that is passed to it appears to be always **null**, so it doesn't work.

**Comment by Skrypt** [comment]
I can reproduce this. I found a scenario where the model.SelectedCulture = null and makes a log entry. Will try to fix this.
