### ISSUE TITLE
http://www.orchardproject.ch/ link from homepage

### ISSUE THREAD

**Issue by MatthiasJost** [OrchardCMS/Orchard#5264]
http://www.orchardproject.ch/ link from your homepage has been hacked or something like this. It does not contain any content which seems to be related to Orchad CMS.

![screenshot](https://cloud.githubusercontent.com/assets/8178852/7571717/c8c57752-f819-11e4-8a55-7d59dcba35b2.png)

**Comment by Piedone** [comment]
How is not winning money online related to Orchard?
JK, removed it. And while we're at it, orchardproject.be, orchardproject.co, orchardhispano.com and orchardproject.pt are dead as well, so removed them.

**Comment by MatthiasJost** [comment]
Yes winning money is always related to Orchard :+1: 

Maybe adapt the list here as well: http://www.orchardproject.net/discussions (under commmunities).

Btw: The facebook page looks a bit ugly and has not been updated since May 2014. Maybe you could add a link to the twitter account instead.

**Comment by abhishekluv** [comment]
Fixed. Thanks!

**Comment by Piedone** [comment]
Good idea, added the Twitter handle.
