### ISSUE TITLE
InternalsVisibleTo doesn't seem to work

### ISSUE THREAD

**Issue by thekaveman** [OrchardCMS/Orchard#5266]
One would use this attribute to e.g. give test projects access to the internal members of another project under test. 

In AssemblyInfo.cs under `Orchard.Azure.MediaServices` we have (line 16):

```c#    
[assembly: InternalsVisibleTo("Orchard.Azure.MediaServices.Tests")] // Not working. :( Someone please fix.
```

And I can verify that it's not working with my own module/test project. 

Any ideas?

**Comment by MpDzik** [comment]
I had the same problem some time ago. Make sure that the `AssemblyInfo.cs` file is included in the compilation. In the csproj file it should be:

    <Compile Include="Properties\AssemblyInfo.cs" />

The codegen utility used to add this file to the project as `None` or `Content`. In that case the code is not compiled at all and your attribute is not added to the assembly.

**Comment by thekaveman** [comment]
Thanks @MpDzik! Setting Build Action to `Compile` on the AssemblyInfo.cs file works.
