### ISSUE TITLE
Module manifest metadata to indicate if a module is beta/preview or deprecated

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/Orchard#5271]
Especially when we go onto a shorter release cycle we might release new modules that although are meant for production (and in our best effort are ready for it) are still young and doesn't yet have a mature feature set or UI (and, depending on user feedback, can still change a lot). For these modules (instead of postponing the release and trying to get pre-release feedback) we could have a way in the module manifest to indicate that the module is in beta/preview state.
Similarly we could have some indicator for deprecated modules (see #3829).
Detected metadata would cause a notification to be displayed when enabling the feature and maybe also other visual clues to be shown on the Features dashboard.

Ideas from the meeting:
- New metadata (line) in Module.txt
- An indication in the version number (e.g. "1.0b" would be detected as beta)

**Comment by DanielStolt** [comment]
I think it makes little sense to use __both__ a new metadata line __and__ a version number suffix (metadata line work both to enable banner and to show a human-readable marker) but if we do include the version number suffix, I think it should be more explicit and human-readable, like for example:

- 1.10.0-preview
- 1.9.2-deprecated

**Comment by Piedone** [comment]
Yes, it's either-or.

**Comment by DanielStolt** [comment]
Then I would definitely prefer a dedicated metadata line.

**Comment by sebastienros** [comment]
Ok, let's go with a list of possible values and their meaning.

Brainstorming:
- [ ] alpha
- [ ] beta
- [ ] preview
- [x] deprecated

**Comment by DanielStolt** [comment]
I don't think it adds anything to differentiate between the different stages of pre-production, and it's very subjective and arbitrary how you define them anyway. IMO a better approach would be simply:

* [ ] Preview
* [ ] Production
* [ ] Deprecated

We might call the metadata line "LifecycleStatus", to avoid potential confusion with the runtime status (enabled/disabled). So for example:

		Name: Audit Trail
		AntiForgery: enabled
		Author: The Orchard Team
		Website: http://orchardproject.net
		Version: 1.9.0
		OrchardVersion: 1.9
		LifecycleStatus: Production
		Description: Provides a log for recording and viewing back-end changes.

**Comment by Piedone** [comment]
I like the suggestion, and would also add that IMO Production should be assumed if the item is omitted.

**Comment by DanielStolt** [comment]
Agree on the implicit default.

**Comment by sebastienros** [comment]
Implicit default approved.
