### ISSUE TITLE
Orchard 1.9 error if version number in ResourceManifest is single digit

### ISSUE THREAD

**Issue by psenechal** [OrchardCMS/Orchard#5283]
ResourceManifest.cs file with script and style definitions works in Orchard 1.8 when the .SetVersion() attribute contains a single digit such as "1".

After upgrading to Orchard 1.9, an error is thrown:
"Version string portion was too short or too long."

Modifying the attribute value to "1.0" resolves the issue.

Since the value for .SetVersion() is a string, I would think any value would be acceptable.

**Comment by Xeevis** [comment]
:-1: 

Although value you set is a string, this string gets later parsed into `System.Version` type which has this as a requirement.

> Version numbers consist of two to four components: major, minor, build, and revision. The major and minor components are required; the build and revision components are optional, but the build component is required if the revision component is defined. All defined components must be integers greater than or equal to 0. The format of the version number is as follows (optional components are shown in square brackets ([ and ]):

> major.minor[.build[.revision]] 

Of course it would be possible to make it work with single digit by appending extra zero in the code, but I'd advise against such hacks. No versioning system I've ever encountere used less than 2 component versioning and that also applies to .NET. It's an industry standard.

**Comment by Ermesx** [comment]
:-1:  x :100: 
I think it should be closed, it is not important and does not influence on Orchard.

**Comment by armanforghani** [comment]
I have similar problem with the following error:

Input string was not in a correct format.
src\Orchard\UI\Resources\ResourceManager.cs    Line: 199 

I think this is because i had some non integer versions in my modules for Orchard 1.8.1 such as "1.4.0-rc.0".

**Comment by Xeevis** [comment]
@armanforghani Yes of course, that is not supported version format. You should use only digits in format `major.minor[.build[.revision]]` (bracketed being optional). To better understand why this is necessary. Unified System.Version provides reliable comparison of versions, so it knows that 1.11 is newer than 1.0 or 1.9.15.110102 ...

Why this is a good thing. For example Orchard.jQuery module has resource called "jQuery" set to version **1.11.1**, so lots of modules that depend on jQuery and include it with `Script.Require("jQuery)`, will include `jquery-1.11.1.min.js`on the page ... But what If you want to use the 2.x version of jQuery across your site? Thanks to version comparison you don't need to rewrite Orchard.jQuery module, but instead you can just define new resource in your theme or module and call it "jQuery" and if you give it higher version like **2.1.4**, then entire site will be using this higher version. That way you can swap scripts and stylesheets without doing any modifications to original files. If you were allowed to input any string into version, comparisons would fail and it would be impossible to tell which resource should take priority.

**Comment by armanforghani** [comment]
@Xeevis, Yes, I read official document for System.Version. You are right. Thank you so much for your useful comment.

**Comment by donaldboulton** [comment]
I always keep the latest version of jQuary, jQuaru-ui, bootstrap whatever. Why would anyone want to use version  in there modules. I had a recent issue where cookiecutter used version 1.4.0 of jquery.cookie.js
but it  used version 1.4.1 in Orchard.Jquary and caused me issues, same with several other modules calling a version of jQuary that I had updated to 2.1.3 not 1.1.1
