### ISSUE TITLE
Dynamic Forms form elements should auto-generate either one of Name or Label

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/Orchard#5287]
It's tedious to set up both Name and Label for most of the cases since both will be the same. Since the Label is what matters to users I'd probably put that first and be the Name auto-generated (maybe in a way like content field names: trimmed and stripped from spaces).

**Comment by Piedone** [comment]
@sfmskywalker @DanielStolt what do you think?

**Comment by sfmskywalker** [comment]
I would be all for that.

**Comment by Piedone** [comment]
Thanks!

**Comment by DanielStolt** [comment]
Seems good to me too!

**Comment by Piedone** [comment]
Related: #7609, #7608.
