### ISSUE TITLE
Project getting error when Orchard_Users_UserPartRecord table have more than 2100 data

### ISSUE THREAD

**Issue by cybervation** [OrchardCMS/Orchard#5290]
We are making a ProPortal Virtual Mentoring System. Once the Orchard_Users_UserPartRecord table gets populated with more than 2100 data then I am getting the below error. Please help! Really urgent. We have a data of more than 19000 student and more to come.

Error
"The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Too many parameters were provided in this RPC request. The maximum is 2100."

**Comment by sfmskywalker** [comment]
Can you profile the query and see what it looks like?

**Comment by Piedone** [comment]
This suspiciously looks like you have an IN() query generated somehow that tries to fetch more than 2100 users by ID and you hit the SQL Server limit of IN parameter count. You have a content query somewhere that fetches users by ID, using a collection of IDs.
Since there is no code in Orchard to my knowledge this doesn't look like a bug in Orchard but rather a bug in your code.

**Comment by sebastienros** [comment]
I think @Piedone is right.

**Comment by pszmyd** [comment]
Yup, it definitely seems like hitting an IN parameter limit. 

We can't do much here - you have to either split the query into smaller batches, keeping the limit in mind, or apply a different query that wouldn't require that many IN parameters.

**Comment by Piedone** [comment]
No reply from @cybervation so let's assume it was an issue with a custom module. Closing the issue, please re-open if you can confirm this is an Orchard problem.

FYI you could use this to split a large IN() expression into multiple ones, which will let the query succeed but it still won't scale performance-wise: http://helpfullibraries.codeplex.com/SourceControl/latest#Libraries/Utilities/HqlQueryExtensions.cs
