### ISSUE TITLE
using azure sql databases as repository

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/Orchard#5296]
I migrated my local sql server database to azure  sql data bases and then changed the connection string in Settings.txt to what was given from the azure portal . Looks like this 

State: Running
Themes: 
Modules: 
Name: Default
DataProvider: SqlServer
DataConnectionString: Server=tcp:gmv0s7oxpy.database.windows.net,1433;Database=IntelliOrchard;User ID=remote.......

After I tried using the site from azure web sites its not connecting to the database. I am getting an error 
HTTP 404.  The resource cannot be found.

Is there something else needed to make this work.?
Thanks.

**Comment by CSurieux** [comment]
May be you have not setup the sql Azure firewall to accept your IP ?

**Comment by dcinzona** [comment]
What do the error logs say?  App_Data/logs

**Comment by giannik** [comment]
ok , my mistake. 
The error  logs states   ''Client with IP address '23.100.53.152' is not allowed to access the server. ''.
Obviously, the  client ip of the web site is different from your local ip . DUH.
Adding it to the allowed ips from azure fixed it.
Thanks guys.
