### ISSUE TITLE
Orchard 1.9 Web config question.

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#5300]
Timeout setting for 1.9 int before merge with 1x and dev and then official 2.9 release.
defaultSettings timeout="00:30:00"

Timeout setting with Orchard.Web.1.9 zip 1.9 release.
Getting major problem with caching and timeouts to sql server. Could this be the issue.
defaultSettings = no timeout
And why the change???

**Comment by sebastienros** [comment]
It's a connectionstring related value. You can define it when you setup the connection string or in the Settings.txt file if you need to change it. But this is also the default value for SQL Server, which means your issue should not be related to that. Please test it though and reopen the issue if it goes away.
