### ISSUE TITLE
Authentication cookie can be stolen even if SSL is forced on all pages

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/Orchard#5315]
Even if you enable "Force SSL on all pages" in the SSL module the authentication cookie (and anything from the first request) can be stolen in the following circumstances:
- The site uses the default FormsAuthentication.
- You've authenticated with the site previously and have a living authentication cookie.
- Then try to open the site via http.
- The first request happens via http but your cookie is sent in the request.
- The redirection to the https URL happens after that, but you've already sent all authentication data (and possibly more sensitive information) in the previous request.
Now if someone sniffs network traffic they can catch the first unsecured request and hijack the user session.
With FormsAuthentication this can be solved by setting `requireSSL="true"` and force the authentication cookie to be only sent via SSL as in:
```
        <authentication mode="Forms">
            <forms loginUrl="~/Users/Account/AccessDenied" timeout="2880" requireSSL="true"/>
        </authentication>
```
However this sets this for the whole application (not allowing different configuration for individual tenants).
Ideally this would be automatically handled by the SSL module. I'm thinking about having an `IAuthenticationEventHandler` for `SignIn()` and `SignOut()` (`IUserEventHandler` is not enough as it's tied to Orchard.Users and wont fire if SignIn/Out happens other than in AccountController) that the module could hook into and set the cookie to be secure. There can be cookie-less `IAuthenticationService` implementations though, so maybe a cookie argument for the event handler is not the right thing to do (or just document that it can be null if the implementation doesn't use cookies).

**Comment by sebastienros** [comment]
Solution is to define a new Framework interface to provide the HttpsOnly value for auth cookies. The default implementation is in the Framework, returning `FormsAuthentication.RequireSSL` as it is the current implementation, and can be changed globally in the web.config. Then the SSL module needs to implement this interface (SuppressDependency) and return whatever `Enable SSL` is.
