### ISSUE TITLE
Implement sort on SearchController

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#5320]
The ```SearchController``` in _Orchard.Search_ could be updated to accept some optional ```sort``` parameter that contains the field to sort by. The tricky part it seems is how to determine the field type so that the appropriate SortBy* method on the search builder can be invoked (e.g. ```SortByDateTime``` if the specified field is of that type).

**Comment by sfmskywalker** [comment]
We should probably also take into account the fact that we can specify the field type to sort by, e.g. LONG, DOUBLE, INT and STRING.

**Comment by Piedone** [comment]
How about having a Projector filter for search instead? Like. https://helpfulextensions.codeplex.com/SourceControl/latest#Extensions/Projections/SearchFilter.cs Also see #5030

**Comment by sfmskywalker** [comment]
That looks pretty clever. Thanks!
