### ISSUE TITLE
Missing css files when editing a workflow

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#5323]
When editing a workflow, with the browser tools I can see some errors about missing css files. I can fix it by adding empty files in the Styles folder of the related modules

    workflows-activity-logging.css (in Orchard.Workflows/Styles)
    workflows-activity-add-model-error.css (in Orchard.DynamicForms/Styles)
    workflows-activity-dynamic-form-submitted.css (in Orchard.DynamicForms/Styles)
    workflows-activity-dynamic-form-validating.css (in Orchard.DynamicForms/Styles)

Best

**Comment by Piedone** [comment]
Duplicate of #4358.
