### ISSUE TITLE
Orchard CMS not available in Azure Web App Gallery

### ISSUE THREAD

**Issue by anavgale** [OrchardCMS/Orchard#5325]
From the Azure portal at - https://manage.windowsazure.com, when you try, 

New + -> Web App -> From gallery 

You can see all other CMS and other Web Apps, but Orchard is missing since last few days. I am desperately trying to find it as I want to setup one of our clients website. We did all development on local, all modules are ready and it is missing from Gallery. 

Will it be reinstated again in the Azure gallery? 

I had put this in discussion, but there is no resolution, so opened the issue here.

**Comment by ask2963** [comment]
You can find it in the marketplace on the preview portal. https://ms.portal.azure.com

**Comment by sebastienros** [comment]
It's available in the new Portal and in WebPI, exactly where it is supposed to be. The old portal is not updated with web apps anymore AFAIK.
