### ISSUE TITLE
Orchard Statistic Module

### ISSUE THREAD

**Issue by apolun** [OrchardCMS/Orchard#5328]
Hello
I search threads but couldn't find any good built in statistic module unless a module for injecting Google Analytics code,  is there any exists at all? I want something simple for showing daily and monthly page views and other popular features .
Thanks

**Comment by Piedone** [comment]
Please don't ask questions in the issue tracker but rather in the forum: https://orchard.codeplex.com/discussions

AFAIK there is no such module.

**Comment by apolun** [comment]
Thanks for response 
 I thought that Orchard completely left CodePlex because of vulnerability issues .

**Comment by sfmskywalker** [comment]
No worries. Yeah, well at some point we'll also move to another forums platform, but for the time being that part remains on CodePlex. Thanks for your cooperation.
