### ISSUE TITLE
Navigation - Localization

### ISSUE THREAD

**Issue by pda-code** [OrchardCMS/Orchard#5329]
Can someone please - from the orchard team - inform me official

- If the menu/menuitems can be localized. 
- If yes i must add the localization part to both Menu and MenuItems or only menuitems?
- If yes what is the purpose of attaching localization part to menus? (it creates a new menu!!!) as the navigation widget displays only hierarchical menuitems?
- If the Culture picker module/Culture switcher widget (from orchard team) work

It is terrible to search the entire internet for solution and/or answers for these major issues and in the new versions of orchard to only see meaningless  enhancements like "Layout in pages" !!!

**Comment by Skrypt** [comment]
I suggest that we create a recipe that would configure things like that automatically for multi-culture websites. Maybe include that in the setup of the website so that we don't have to tweak those things afterward. That and a better documentation or "wiki", how-to do multi-culture websites with Orchard.

**Comment by sebastienros** [comment]
From my own experience the solution is to create two distinct menus, as they can have difference contents. But some scenarios might require the same structure and could use a simplified experience then. Not that is impossible with two menus still. You can filter which menu to display using a custom layer with the `culture` verb in its rule.

However, a menu item is always associated to a culture. And it will be filtered automatically. So if you add several menu items of different cultures to the same menu, they will be removed automatically at rendering if they don't match the current culture. This only works for simple websites obviously, so I'd still recommend to use separate menus for each culture.

**Comment by pda-code** [comment]
**Problem**
The problem with localized Taxonomies (even when you use the Localization synchronization module) is that in every place you want to use a taxonomy you must select the Culture Specific Taxonomy.

For example suppose we have two localized taxonomies 
"Product Categories en-US"
"Product Categories el-GR"

With this structure 
* the "Product" Content Type must have TWO DISTINCT taxonomy fields "Product Category en-US" and  "Product Category el-GR"
* The razor views must handle those two fields based on the current  user's culture.
* If i want to make a sidebar widget that shows the product categories (based on the current user's culture) i have to write 2 Culture specific sidebar widgets because in projection-->query--->you must select terms from only ONE TAXONOMY.
* In General if you have 2 DIFFERENT TAXONOMIES (although they are each other translations), YOU MUST MAKE EVERYTHING TWICE

**Solution**

* You create only one "Product Categories" taxonomy. YOU DO NOT ADD localization part
* You edit content definition of term "Product Categories Term"  and ADD localization part
* You add terms terms to "Product Categories". In the editor of each term you can switch to other culture and add a translation
* When you click "List terms" in orchard admin the orchard displays only the terms in default site language but when you open the editor for each term the translations are available. 


If you go to the "Product" and add a taxonomy field "Product Category" of taxononomy  "Product Categories", the editor of the product shows only the terms of one language...NOT GOOD when you make a translation for a product. 

In English product you can select an english term...**GOOD**
In Greek product, you cannot select a Greek term. The list keeps displaying only english terms (although there are greek terms!!!!). **BAD** 

**WITH JUST 5 LINES OF CODE (the correct LINQ query) the orchard team could solve this issue (filtering the terms according to content items culture)** and never have the problem of keeping 2 distinct taxonomies just for translation.

**WITH JUST 2 LINES OF CODE (no LINQ query) the orchard team could solve this issue (no filtering) and display ALL THE TERMS in every language (English + Greek)** and never have the problem of keeping 2 distinct taxonomies just for translation.

**My solution**
Do not use taxonomy field "Product Category"

Replace it with Content Picker Field and add as a filter to display on "Product Category Term" type. That way the user can select one or more corrent localized versions.

-----------------------------------------------------------------------------------------------------------------------
In my little experience in orchard that solution works perfect.

- You keep using Taxonomies 
- You have localized versions of terms
- You have ONLY ONE taxonomy (for all the cultures) to pick for in Queries, Fields, Query Menu Items.
- You have ONE UNIFORM BASE CODE

What do you think? Do you suspect some kind of drawbacks using this approach?
