### ISSUE TITLE
Recipe Journal provides sparse detail, and no indication as to where an error occurred in a recipe step.

### ISSUE THREAD

**Issue by gcsuk** [OrchardCMS/Orchard#5335]
Currently, the Recipe Journal reports that a step has begun, and if an error occurs it logs the error message. It does not provide a breakdown of the location in the Step where the problem occurred, which would be useful information when investigating issues.

As an example, the CommandRecipeHandler loops through all commands in the Recipe file and executes them. If a command fails it would be valuable to know which commands succeeded, in order to more easily identify the problem item.

In order to facilitate improved logging, I propose that a string property representing the Execution ID be added to the RecipeContext model object, so that it is available to all RecipeHandlers. Also, IRecipeJournal would be passed into the constructor of each recipe handler, thereby making the WriteJournalEntry method available to the respective classes.

The proposed change would require no breaking changes. There would be a single property added to a POCO class, and some logging code in each handler. I believe that the benefit of having a trace of Features/Commands/Widgets/etc that have been successfully processed makes this a worthwhile undertaking, and our team have already found this to be of value.

I have completed the proposed changes on our implementation and would be happy to submit them to the orchard repository for review.

**Comment by PaulDevenney** [comment]
+1

**Comment by gcsuk** [comment]
https://github.com/OrchardCMS/Orchard/pull/5371

**Comment by gcsuk** [comment]
Pull request merged so issue closed.
