### ISSUE TITLE
Recipe parser currently throws full page error when encountering invalid recipe file

### ISSUE THREAD

**Issue by gcsuk** [OrchardCMS/Orchard#5342]
Currently, the recipe parser throws any recipe errors to the user, causing full page error on the tenant setup screen or ‘Recipes’ tab in the admin area. It would be beneficial for these errors to be trapped and logged, so that users can still work with valid recipes.

If the RecipeParser validated the recipe text, it could return a null for any invalid files. Any null recipes returned by RecipeParser could then be logged, along with the file name. No error would occur for the user.

The manner in which the user is informed is flexible. I would propose a message on-screen informing them of the problem file or files, as a logging-only solution could mask problems.

There are no breaking changes involved in the implementation of the proposed amendments..

I have implemented a solution on our project, which I am happy to submit for review.

**Comment by MpDzik** [comment]
Good idea, I like it.

**Comment by gcsuk** [comment]
https://github.com/OrchardCMS/Orchard/pull/5344

**Comment by PaulDevenney** [comment]
+1

**Comment by gcsuk** [comment]
PR 5344 is now merged. Issue is resolved.
