### ISSUE TITLE
Exception in StorageFilterBase.cs

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [OrchardCMS/Orchard#5345]
Hi there,

i get an exception log in my Orchard 1.9 logs when e.g. editing & saving a user and tracked it down to StorageFilterBase.cs:

```
src\Orchard\ContentManagement\Handlers\StorageFilterBase.cs

namespace Orchard.ContentManagement.Handlers {
    public abstract class StorageFilterBase<TPart> : IContentStorageFilter where TPart : class, IContent {

      ...

        void IContentStorageFilter.Versioning(VersionContentContext context) {
            if (context.ExistingContentItem.Is<TPart>() || context.BuildingContentItem.Is<TPart>())
                Versioning(context, context.ExistingContentItem.As<TPart>(), context.BuildingContentItem.As<TPart>());
        }

        void IContentStorageFilter.Versioned(VersionContentContext context) {
            if (context.ExistingContentItem.Is<TPart>() || context.BuildingContentItem.Is<TPart>())
                Versioned(context, context.ExistingContentItem.As<TPart>(), context.BuildingContentItem.As<TPart>());
        }
```

Here you can see that the **.Is<>() comparisions** are linked via a **logical or**. The expression is imho wrong as it calls **Versioning()** and **Versioned()** when TPart is not welded to _existing content item_ or the _building content item_ resulting in an **null reference exception** in

```
src\Orchard\ContentManagement\Handlers\StorageFilter.cs

namespace Orchard.ContentManagement.Handlers {

  ...

    public class StorageFilter<TRecord> ... {

      ...

        protected override void Versioning(VersionContentContext context, ContentPart<TRecord> existing, ContentPart<TRecord> building) {
            building.Record = existing.Record;
        }
```

due to acessing _building_ or _existing_ without sanity check.

Other handlers overriding the **Versioning()** and **Versioned()** method might be affected too.

I temporarily changed the code in my Orchard sources to 

```
.Is<TPart>() && ... .Is<TPart>
```

It would be nice to have this issue fixed in future releases.

So lonG

**Comment by ViRuSTriNiTy** [comment]
FYI: This is still a bug in Orchard 1.10.1.

**Comment by sebastienros** [comment]
Looks like to me that this was excepted, that the values can be null. So the implementer needs to check that the versions are not null before using it.

**Comment by sebastienros** [comment]
Can you explain how you get to a point that the Part is not welded on either of these objects?

**Comment by BenedekFarkas** [comment]
@ViRuSTriNiTy please reopen and provide a repro is we should still look at this issue.

**Comment by BenedekFarkas** [comment]
My guess would be that the exception happens when versioning a content item after adding and/or removing a content part, so one of the conditions will see a null.
