### ISSUE TITLE
Decouple Dynamic Forms from Orchard.Scripting.CSharp and Orchard.Users

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/Orchard#5349]
The base Dynamic Forms feature depends on a lot of modules, but also depending on Orchard.Scripting.CSharp and Orchard.Users seems excessive:

- Orchard.Scripting.CSharp is added solely for `DynamicFormValidatingActivity`
- Orchard.Users is there only for `UserPartBindings`

While having a feature for both of these also seems heavy-handed, `UserPartBindings` could be in Orchard.Users without the module depending on Dynamic Forms (since `IBindingProvider` is an event handler).

And while you mostly have Orchard.Users already enabled Orchard.Scripting.CSharp is certainly not something everybody would need or would want to use so moving `DynamicFormValidatingActivity` to its own feature would be better.

**Comment by Piedone** [comment]
What do you think @sfmskywalker ?

**Comment by sfmskywalker** [comment]
I agree. I was waiting for you to bring this up and take care of it. :)

**Comment by Piedone** [comment]
I'm not sure I'm worthy to touch the sacred source files of Dynamic Forms :-D.
