### ISSUE TITLE
Loading modules / themes from additional folder

### ISSUE THREAD

**Issue by qt1** [OrchardCMS/Orchard#5354]
The current module harvester looks into the modules folder, but not at sub folders or specific other folders.

I would like to set harvesting to look at additional folders (but without making changes to the orchard code)

Justification:
I would like to organize my modules (and contributions etc) in separate folders so they can be managed more conveniently by their own git or other managers and not interfere with the full project git.

**Comment by Ermesx** [comment]
So,
in the OrchardStarter class where are autofac container registrations exists code:
```c#
builder.RegisterType<ModuleFolders>()
       .As<IExtensionFolders>().SingleInstance()
       .WithParameter(new NamedParameter("paths", new[] { "~/Modules" }));
```
I think you can override ModuleFolders class by your custom simple module but I'm not sure if SuppressDependency attibute will work.
But it seems to me that you can also take advantage of autofac modules and re-register ModuleFolders with your new implementation.

**Comment by qt1** [comment]
Thanks Ermesx,  

It seems like the natural thing would be to add some settings to ~/config/host.config , unfortunately I am not that familiar enough with autofac so I would appreciate an advice about how to do this.

The other option would be to add this setting to web.config (or to ModuleFolders class) and make a small change to the harvester - but before burdening people with another PR I would like to make sure first that I am not missing a trivial solution.

**Comment by Piedone** [comment]
Duplicate of  #5019.

**Comment by armanforghani** [comment]
@qt1 It seems you have good experience on this topic. 
I'm looking for a way to load themes from sub directories of Media folder because i want to hold themes per tenant. 
I would like to allow users to change the theme of their site. I think this is very useful feature.
Can you help me please?

**Comment by sfmskywalker** [comment]
@armanforghani You can configure which themes are available per tenant using the **Themes** field in the `Settings.txt` file of your tenant. E.g.

```
State: Uninitialized
Themes: ThemeA, ThemeC
Name: MyTenant
...
```

Hope that helps.

**Comment by armanforghani** [comment]
@sfmskywalker Thank you but it is not what i want. I want the users be able to write their themes. In other words i want Orchard Harvester also searches Media folder for overridden templates.
I used IShapeTemplateHarvester and IShapeTemplateViewEngine but they work for view templates and not for shape templates. Ex. Index.cshtml has been found in Media folder but Menu.cshtml has not been found.

**Comment by qt1** [comment]
Having write access to executable code seems to me like a security risk.

The code in cshtml can access everything and is not limited to specific tenant access. Anyone that can write cshtml is effectively a superuser and can mess things up for all other tenants (e.g. have unlimited access to the database).

**Comment by armanforghani** [comment]
I understand your concern but i will only allow liquid markup instead of razor. It has limited access.

**Comment by qt1** [comment]
In principal it can be done - try adding the path to web.config .

I would, however, consider writing a specific module that will handle the functionality and the security. The current harvester/loader would just load everything in its path so setting up the security (and prevent bypassing it) will be tricky at best..

**Comment by armanforghani** [comment]
I don't want to share media themes for all tenant. Each tenant should have access to its theme in media folder of that tenant.

**Comment by qt1** [comment]
You can still limit theme access by the landlord so each tenant will be able to select only to the theme(s) it can access for writing.

**Comment by armanforghani** [comment]
I know i can limit access to the theme but this does not cover my needs.
I want the user be able to overwrite some templates of install theme or develops a theme from scratch.
I'm looking for a way like [MediaTheme in DotNest sites](https://dotnest.com/knowledge-base/topics/theming/writing-a-dotnest-theme-from-scratch).
