### ISSUE TITLE
Maybe invalid html with the pager shape

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#5359]
When in a shape the localizer `T()` is used without `.Text` or `.ToString()`, there is no further html encoding because of the `LocalizedString` that inherits from an `IHtmlString`. This means, for example, that you can inject some html tags through a .po file...

That's ok unless you use an html reserved character but not for its normal usage. This is the case in `CoreShapes.cs` for the `Pager_Links` shape where the `"<"` character is used but not for opening an html tag. I've seen this when doing some html parsing on the rendered pager shape and where I've got some parsing errors. I could fix it by overriding before the pager model properties or by replacing in `CoreShapes.cs` this

        var firstText = FirstText ?? T("<<");
        var previousText = PreviousText ?? T("<");

With this

        var firstText = FirstText ?? T("&lt;&lt;");
        var previousText = PreviousText ?? T("&lt;");

Or this

        var firstText = FirstText ?? T("<<").Text;
        var previousText = PreviousText ?? T("<").Text;

Note: I didn't have any problem with the `"&"` and `">"` characters, but not sure this results in a valid html. So, maybe, we need to do the same just after when the `">"` character is used in two places

Best

**Comment by sebastienros** [comment]
I think the current behavior of T is correct. We need to find and fix the usages where we were making some wrong assumptions. You are finding them one by one as I can see .... sorry for that.

**Comment by sebastienros** [comment]
Because T accepts HTML, and this html will be displayed as is in most cases, I think the correct solution is to use `T("&lt;&lt;")`. We were lucky so far that browsers would fix our issue, and so it won't be a breaking change. But this is what users should do it their themes.

**Comment by TFleury** [comment]
It means that we have to edit all translations (french and probably others) and html encode all accented or special characters.
It also means that we have to edit all usages of *Html.ActionLink(T("").Text)* and *Html.ActionLink(T("").ToString())* (a little more than 200 usages) to provide ActionLink method an **unencoded** string.
There are probably other places where we need unencoded translations.

Are you sure it's not a beaking change ? I don't think so...
