### ISSUE TITLE
JobsQueue will process all jobs after each other, even if there are a huge number of them

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/Orchard#5365]
`JobsQueueProcessor.ProcessQueue()` will fetch jobs as long as there are any. If there are many (even hundreds of) jobs that do something non-trivial (especially if they do DB calls) this will eventually cause timeout, and it's very dangerous since we have a potentially long-running background task. Imagine e.g. processing all content items in such a long execution like at #4729.

I'd suggest modifying the implementation so 10 (or a configurable amount of) jobs are processed at once, then subsequent jobs are executed in later background task sweeps.

On a related note I don't understand why `IJobsQueueProcessor` is a singleton.

**Comment by Piedone** [comment]
@sebastienros any comments?

**Comment by sebastienros** [comment]
- bg task doesn't stop with the app
-> Cancellation requested after each job, stop the loop ?

- single transaction
-> one transaction per job

- implement the background tasks pools

**Comment by Piedone** [comment]
Related issues:
- #4417 and #4620 so we can have long-running background tasks without them being terminated in an indefinite state when the app is torn down.
- #4842 so long-running tasks are not blocking other tasks, as there should be a separate pool/group for tasks that run continuously.

**Comment by sebastienros** [comment]
I think a new transaction should be created on every job.

**Comment by jersiovic** [comment]
Do you think it would be a good idea backbround tasks or at least long-running background tasks change  the priority of its thread to have less priority than regular threads?

**Comment by Piedone** [comment]
I guess the point would be to prioritize serving requests over bg tasks. I'm not sure whether the thread System.Timers.Timer creates will be on the same ASP.NET thread pool.
