### ISSUE TITLE
Orchard 1.9 setup doesn't work with MySql because of creating Index on Text column without prefix length.

### ISSUE THREAD

**Issue by DavidDeVries** [OrchardCMS/Orchard#5366]
Tested on MySql 5.
Setup never completes and gets stuck in an infinite error loop.

The following 2 commands caused this:
- `create index 'IDX_AutoroutePartRecord_DisplayAlias' on 'Orchard_Autoroute_AutoroutePartRecord' (DisplayAlias)`
- `create index 'IDX_MediaPartRecord_FolderPath' on 'Orchard_MediaLibrary_MediaPartRecord' (FolderPath)`

I could solve it by adding a prefix length while debugging, like this:
- `create index 'IDX_AutoroutePartRecord_DisplayAlias' on 'Orchard_Autoroute_AutoroutePartRecord' (DisplayAlias(10))`
- `create index 'IDX_MediaPartRecord_FolderPath' on 'Orchard_MediaLibrary_MediaPartRecord' (FolderPath(10))`

As described here: 
http://dev.mysql.com/doc/refman/5.0/en/create-index.html

> BLOB and TEXT columns also can be indexed, but a prefix length must be given.

**Comment by Piedone** [comment]
Related to #4780 and #4779?

**Comment by DavidDeVries** [comment]
Possibly, though it seems like for mysql you will always need to specify a key length for a Text column. 
This is the error that is included in the exception, should have added it: 
`Additional information: BLOB/TEXT column 'FolderPath' used in key specification without a key length`
So it seems not to be about the length of the prefix, but about the absence of the key length.

**Comment by Thierry-S** [comment]
I've got same error with a 1.10 install:

``2016-04-26 16:26:15,425 [184] Orchard.Data.Migration.DataMigrationManager - Default - ERROR Error while running migration version 0 for Orchard.Autoroute.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> MySql.Data.MySqlClient.MySqlException: BLOB/TEXT column 'DisplayAlias' used in key specification without a key length
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Orchard.Data.Migration.Interpreters.DefaultDataMigrationInterpreter.RunPendingStatements()
   at Orchard.Dat...``
