### ISSUE TITLE
Have prefix for all Orchard custom styles

### ISSUE THREAD

**Issue by yaplex** [OrchardCMS/Orchard#5370]
in Orchard 1.9 in file Row.cshtml you have tagBuilder.AddCssClass("row");
When using twitter Bootstrap theme for website Orchard "row" class conflicts with Bootstrap "row" class.

As a solution to have custom prefix for all orchard classes, something like 
tagBuilder.AddCssClass("orc-row");

**Comment by konstrui** [comment]
The Row.cshtml file comes from the Layout Module. I think this module inserts a css class called default-grid.css.

I use bootstrap also, but it is loaded after the default-grid.css, and not causing any problems. Not sure if you can 'disable' the default styles that come from the Layout Module, but you can of course prevent it from loading by changing the code?

In the Parts.Layout file:

    @{
       Style.Include("default-grid.css");
    }
    <div class="orchard-layouts-root">
       @Display(Model.LayoutRoot)
    </div>

**Comment by sfmskywalker** [comment]
In case you're using Bootstrap, override the Parts.Layout.cshtml view in your theme and get rid of the `Style.Include line`. I've written a section about this here: http://www.ideliverable.com/blog/orchard-layouts (see section *Bootstrap*)

**Comment by yaplex** [comment]
Yes, that was what i did, it works for me 
sfmskywalker Thanks for the post, but please check images, they are not available (in fact images are not available in all your other blog posts)

**Comment by sfmskywalker** [comment]
Are you sure? As far as I know there's only image issues with the post on layouts and dynamic forms. Please let me know what other posts you're seeing missing images. Thanks!

**Comment by konstrui** [comment]
@sfmskywalker Still, those two posts are the most interesting for me ;) Hope you can fix them.

**Comment by sfmskywalker** [comment]
Right ;) Yes I will.

**Comment by yaplex** [comment]
@sfmskywalker you right, when I read your post about caching in 1.9 about month ago, it was also problems with images, but now it's fixed
