### ISSUE TITLE
Export should write items in a predictable order

### ISSUE THREAD

**Issue by DanielStolt** [OrchardCMS/Orchard#5375]
Currently the order of elements in the `<Data>` section of an exported recipe is arbitrary. This makes it impossible to compare two exports to figure out what changed between them.

It would be incredibly helpful if item elements in the n the `<Data>` section  were written in a predictable order. My suggestion would be to order on:

1. Content type
2. Identifier

**Comment by thekaveman** [comment]
:+1: :100:

**Comment by sfmskywalker** [comment]
Fixed in 537adf9cbac3973a34227b3fe9dab8b0349476ea
