### ISSUE TITLE
Media Library Picker Field does not render media in Layout

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#5378]
Repro steps:

1. Create a new content type and attach both a LayoutPart as well as a Media Library Picker Field.
2. Create a content item of this type and select a media item using the picker and add the field element to the layout.
3. Hit Save.
4. Observe that the field element is not rendering the selected media.

**Comment by sebastienros** [comment]
And I am not sure you want to do it, or with limited support at least, with specific cases, because you never know what one would render on the front end that is not supported in the admin. You could at least support Image content type and render it by yourself.

**Comment by sfmskywalker** [comment]
I agree, but it should at least render something. Even if just a list of titles of selected media.

**Comment by sfmskywalker** [comment]
Fixed in c3dffb79f54d5b76917dbe6e440a915e9dc6739c.
