### ISSUE TITLE
jquery-datetime-editor.js removal from Orchard.JQuery causes nwazet.commerce reports to crash

### ISSUE THREAD

**Issue by dpomt** [OrchardCMS/Orchard#5385]
Hi,

jquery-datetime-editor.js was removed from Orchard.Jquery 11 month ago:

Author:		Sipke Schoorstra <sipke@orchardpros.net>#mailto:sipke@orchardpros.net
Date:		11 months ago (25.07.2014 06:18:08)
Commit hash:	4ba6bcdbc0d9ef7fa65e30d6d0cc52b9d5712bb9
Parent(s):	be37ee54dc

This leads nwazet.commerce reports to crash.
Could this js file please get re-added?

Thanks!

**Comment by sfmskywalker** [comment]
It was removed in favor of the ```jquery.timeentry.js``` and ```jquery.calendars.all.js``` scripts, used by the ```DateTimeEditor.cshtml``` view. Perhaps best to update the module to take advantage of these scripts and shapes instead? If not, can you include the script you need yourself?

**Comment by dpomt** [comment]
Thanks for your quick response. 

Betrand has already updated the nwazet.commerce module - I just was not on his latest sources. After pulling his changes everything works fine again.

**Comment by sfmskywalker** [comment]
Good to hear!
