### ISSUE TITLE
WidgetPart should contain a 'CssClass' property

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/Orchard#5387]
On a site containing various widgets it would be awesome - especially for sitebuilders - to be able to set one or more CSS classes to the widget containers from the dashboard instead of doing it from an overridden shape. Now it is possible to do it using the Name property but it is unique and only one class name is allowed. It makes sense because this property is not only for styling.
All in all, that would be great to see a fully displayed WidgetPart property value (ie. without removing spaces or dashes) in the class attribute of a widget container.

**Comment by sfmskywalker** [comment]
You can do this today by attaching the TextField for example to the WidgetPart. That way all widgets will have that field.

**Comment by Piedone** [comment]
Yes, but for that you'd need a shape override or a wrapper that will actually use that value as CSS classes. It's not that it's hard to do, but this is a missing feature when you have a lot of widgets.

**Comment by sfmskywalker** [comment]
Do you have any idea how often this feature is missed? Sometimes, or most of the times?

**Comment by Piedone** [comment]
If you have a site with more than 3 widgets and a non-trivial design then all the time.

**Comment by DanielStolt** [comment]
I sort of like the idea - we have it for elements after all, so why not for widgets too - but it seems arbitrary to do it only for widgets. Why not, in that case, take it all the way and allow entering CSS classes on content items as well?

**Comment by DanielStolt** [comment]
But I must say I have never missed it either, and I have built sites with more than 3 widgets and non-trivial design. :) I find that in the majority of cases (put conservatively) a widget does not share any traits with other widgets that would make me want to apply styling to them as a group. Widgets are normally only defined (and styled) by virtue of A) being a widget and B) being a specific widget, both of which we already have classes for.

**Comment by Piedone** [comment]
Projector Layouts also can have CSS classes and an ID specified.

**Comment by sebastienros** [comment]
We are accepting this suggestion for next release. However as @sfmskywalker mentioned you can configure widgets to support that, and the Vandelay Indutries module has this feature too.
