### ISSUE TITLE
Admin Culture Picker wrong cookie domain

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/Orchard#5389]
In CookieCultureSelector.cs in the Orchard.Localization module. at line 40

``` C#
            if (!String.IsNullOrEmpty(_shellSettings.RequestUrlHost)) {
                cookie.Domain = _shellSettings.RequestUrlHost;
            }

            if (!String.IsNullOrEmpty(_shellSettings.RequestUrlPrefix)) {
                cookie.Path = GetCookiePath(httpContext);
            }
```

this should be

```
            cookie.Domain = httpContext.Request.Url.Host;

            if (!String.IsNullOrEmpty(_shellSettings.RequestUrlPrefix)) {
                cookie.Path = GetCookiePath(httpContext);
            }
```

Else the admin culture picker will fail in a tenant that has more than one domain configured on that host setting. For instance I could set multiple domain names in that host setting like Bertrand said on a blog post. So we can't set the cookie domain to a string like : "www.domain.com,domain.com,www.domain2.com,domain2.com". We should then set that cookie to the domain we are actually browsing.

**Comment by Piedone** [comment]
Agree. Not sure why the original code didn't use that. @Jetski5822 ?

**Comment by Jetski5822** [comment]
@Piedone erm - cuz, erm... I forgot!? - Actually I have no good reason.

**Comment by Piedone** [comment]
OK, as this seems by design. But even better.

**Comment by Skrypt** [comment]
Damn should have pushed this on 1.9.x, I do errors too @Jetski5822

**Comment by Skrypt** [comment]
Tell me if you want me to do a git revert and push back. But this should not affect anything on the dev branch. This is a small change.

**Comment by Jetski5822** [comment]
No revert, take a patch... Then apply it :)

git format-patch -1 <sha>

I forget how to apply, use erm tortoise?
