### ISSUE TITLE
Gallery links in the footer of the orchard gallery page are not working. 

### ISSUE THREAD

**Issue by mahsaro** [OrchardCMS/Orchard#5393]
Address of the following links seem to be wrong: 
![links](https://cloud.githubusercontent.com/assets/12941562/8216512/5bc5eb60-1537-11e5-8318-2bc906d03b91.png)

http://orchardproject.net/gallery/List/Themes is used instead of http://gallery.orchardproject.net/List/Themes and leads to this: 

![error](https://cloud.githubusercontent.com/assets/12941562/8216536/80b04286-1537-11e5-906f-9daaf4591fcc.png)

**Comment by bleroy** [comment]
This is going to be fixed as part of the Gallery do over. Thanks for reporting.
