### ISSUE TITLE
Maybe a missing component in HostComponents.config

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#5398]
In the `ShellDescriptorCache` implementation, related to `"cache.dat"`, a `Disabled` property is used. But there is no corresponding component in `HostComponents.config`. Is it intentional?

Best

**Comment by dcinzona** [comment]
Not sure if this is related, but the Message Bus and Distributed Signals modules may make this obsolete. Issue #5410

**Comment by jtkech** [comment]
@dcinzona thanks for testing all of that
I just remember that these Disabled properties was done to prevent from concurrent access issues (in a shared file system). For more infos, see the comments in these 2 commits
https://github.com/OrchardCMS/Orchard/commit/0cce4b435743f277d89c29b5ffb997785659ec97
https://github.com/OrchardCMS/Orchard/commit/a2d91796d14b9aa0b7fb1ae97037c9d843680acd

Best
