### ISSUE TITLE
Localizer does not handle strings containing "

### ISSUE THREAD

**Issue by MpDzik** [OrchardCMS/Orchard#5402]
The localization module does not handle strings which contain the " character. For example:

    #: ~/Themes/MyTheme/Views/MyView.cshtml
    msgctxt "~/Themes/MyTheme/Views/MyView.cshtml"
    msgid "Foo \"{0}\""
    msgstr "Foo \"{0}\""

From what I checked, there are two problems. First, the localization file contains the string with escaped chars (`Foo \"{0}\"`) and Orchard is looking for `"Foo "{0}"`. Additionally, the localization file parser does not read escaped chars correctly.

I can try to create a pull request with a fix to this issue.

**Comment by pszmyd** [comment]
Good catch! Please do it.

**Comment by MpDzik** [comment]
Created pull request #5404.

The fix turned out to be a lot more simple than I thought. The problem was caused by the fact that `DefaultLocalizedStringManager` was using `string.Trim` to remove quotes from localized texts and `string.Trim` removes all specified chars from the beginning and end of the string, and not just one. This caused problems if the localized string was ending or beginning with a quote (as in the example above).

**Comment by MpDzik** [comment]
Duplicates #4154

**Comment by MpDzik** [comment]
Updated pull request #5404

**Comment by MpDzik** [comment]
Fixed in changeset 104cf7d
