### ISSUE TITLE
Updates to content definitions in a farm environment do not get applied to all instances

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5410]
I have verified this on Azure (Cloud Services AND Web Apps - formerly known as Web sites).

When I make a change to the content definition of, say, a page content type, the change is applied locally to the instance I am currently accessing, but when I switch instances, the change is no longer applied.

I created a module that allows me to switch instances when running on Azure Web Apps (cloud services can be changed by going to the internal IP address on the VNET for the cloud service instance).  This module basically just sets the ARRAffinity cookie to the instance ID for the instance that I want to access.

Steps to reproduce:
1. Edit the 'Page' content type and set the search index from 'Published' to 'Not Indexed'
2. Swap instances (however you decide to do it)
3. Refresh the content type definition for the 'Page' content type. The search index will still be 'Published'
4. Swap instances again
5. Refresh content type page - search index will be 'Not Indexed'

I have disabled both the Shell Descriptor Cache and Session Configuration Cache as well as deleted the mappings.bin and cache.dat files in the App Data.

Orchard should fully support a farm environment, especially with Azure Marketplace support.  Restarting the web service is not a valid solution, however, it does function as a work around to sync changes between instances.

**Comment by sfmskywalker** [comment]
This is a know limitation and is addressed by the Orchard.MessageBus module and more specifically the "Distributed Signals" feature, which will distribute the cache invalidation signal across nodes. Out of the box, Orchard provides 2 message broker implementations:

1. SqlServer (using SQL Server Notifications that you need to enable on your SQL server)
2. Redis (which obviously requires a Redis server)

Should work. If not, please do let us know.

**Comment by dcinzona** [comment]
Do we just need to enable those modules if not currently enabled?  We are using Redis for caching right now.  The SQL server option requires that the server support that, and because we are using Azure SQL V12, I'm not sure that is an option.

**Comment by sfmskywalker** [comment]
I haven;t used it myself, so I am not sure about the details, but if you have Redis already setup for caching, I believe all you have to do now is enable "Redis Message Bus".

**Comment by dcinzona** [comment]
Yup, going through this now... There's also a web.config connection string that needs to be included.
<add name="Orchard.Redis.MessageBus" connectionString="xxxxx" />

**Comment by dcinzona** [comment]
Ironically, enabling the distributed signals module did not propagate across instances and when I tried to enable it on the other instance directly manually, it would not enable - so it is enabled in one instance but not the other.
I restarted the web service to get the distributed signals module enabled on both instances, then ran through the steps outlined in the initial issue description and it looks like this is working.  

Does this negate the need to disable the ShellDescriptorCache and SessionConfigurationCache in hostcomponents.config (does it sync these updates between instances)?

**Comment by sfmskywalker** [comment]
Makes sense, since enabling/disabling features requires a shell restart, which you can also synchronize across nodes by enabling the "Distributed Shell Restart" feature.

I don't know the answer to your latter question offhand, sorry.

**Comment by dcinzona** [comment]
No problem, thanks for the help! I'll link this issue to the other one regarding the hostcomponents.config
