### ISSUE TITLE
External Media (oEmbed) Export/Import Issue

### ISSUE THREAD

**Issue by hannan-azam** [OrchardCMS/Orchard#5417]
The export and import of OEmbedPart is buggy. Exporting method of this part exports "Source" only. 

```
protected override void Exporting(OEmbedPart part, ContentManagement.Handlers.ExportContentContext context) {
        context.Element(part.PartDefinition.Name).SetAttributeValue("Source", part.Source);
}
```

However the part also contains an indexer which contains very useful information such as the thumbnail, width, height etc which gets lost as it is not exported in the recipe. On a target machine if this recipe is imported the media item is shown with blank thumbnail.

```
public string this[string index] {
    get { return this.As<InfosetPart>().Get("OEmbedPart", index, null); }
    set { this.As<InfosetPart>().Set("OEmbedPart", index, null, value); }
}
```

Any suggestions on how to pull the available Keys and add those to recipe for Export. Googled it and people suggest using reflection to get the Keys from the string indexer.

**Comment by bleroy** [comment]
I wouldn't try to extract the information: the structure of an oEmbed item's data is arbitrary. Instead, maybe we should just dump everything that's under OEmbedPart in the infoset under the export tag. Both sides are dealing with XML documents, so this should be easy enough.

**Comment by sebastienros** [comment]
Let's import the whole document as a difference property. And BTW I think it's already done,

**Comment by hannan-azam** [comment]
@sebastienros Since we need to export and import the whole XML structure under OEmbedPart from Infoset, is it a good idea to add these two new methods in class "InfosetPart" OR we should implement the exporting logic in the drivers Exporting/Importing by dealing with the Infoset property and then finding out the relevant XElement within it.

```
        public string Get(string partName) {
             //Return the XML under OEmbedPart tag
        }
```
```
        public void Set(string partName, string infoset) {
             //Set the new XML under OEmbedPart tag
        }
```

**Comment by sebastienros** [comment]
You need to implement it in the OEmbedPArt
