### ISSUE TITLE
client side error for workflow in newest dev

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#5420]
![wf-404](https://cloud.githubusercontent.com/assets/297675/8331149/b64f6aa8-1a54-11e5-998a-8b3564932f66.png)

**Comment by infofromca** [comment]
is it because of gulp?

**Comment by pszmyd** [comment]
Seems like you're simulating a mobile Android browser in F12 tools. IIRC we've never talked about supporting admin UI under mobile browsers.

**Comment by infofromca** [comment]
it is not concerned with  the deviced .
i used firefox , the same:
![wf-firefox](https://cloud.githubusercontent.com/assets/297675/8344635/3d48c326-1ab2-11e5-8b71-9f6a291f25cd.png)

**Comment by infofromca** [comment]
how does workflows-activity-dynamic-form-validating come out?

**Comment by sfmskywalker** [comment]
I think it has to do with the workflows module which automatically generates a style sheet URL and includes it by convention, even if no such file exists. So we need to provide the requested CSS files from the Dynamic Forms module.

**Comment by sfmskywalker** [comment]
Seems like I was right, this is the case with other activities as well (see screenshot).
![css-not-found-workflows](https://cloud.githubusercontent.com/assets/938393/8392709/96449be4-1cfb-11e5-81a3-1b0ce726af1e.png)

**Comment by sfmskywalker** [comment]
Fixed in 5c688267fa11abc306a5d829f0b0654017eba9dc.
