### ISSUE TITLE
Media Library Images with '#' in the file name return 404

### ISSUE THREAD

**Issue by GeoffArmstrong** [OrchardCMS/Orchard#5421]
When a browser attempts to retrieve a images uploaded to the Media Library that have a '#' character in the filename, it gets a 404.  I discovered this issue when upgrading a 1.7 website to 1.9 which had Media Library images with '#' in the file names.

I reproduced the issue again by creating a "fresh" Orchard 1.9 installation, using the Blog recipe, and uploaded images where some images had a '#' in the file name and some didn't.  All the images with a '#' get a 404 when the browser attempts to retrieve them.

**Comment by Piedone** [comment]
We should URLEncode file names probably.
