### ISSUE TITLE
HostingEnvironment.VirtualPathProvider.GetCacheDependency exception

### ISSUE THREAD

**Issue by qt1** [OrchardCMS/Orchard#5422]
with vs2015, win 8.1

The following code from Orchard\FileSystems\VirtualPath\DefaultVirtualPathProvider.cs causes an exception:

            var cacheDependency = HostingEnvironment.VirtualPathProvider.GetCacheDependency(
                virtualPath,
                new[] { virtualPath },
                _clock.UtcNow);

Details:
Exception thrown: 'System.Web.HttpException' in System.Web.dll
```
Additional information: Invalid file name for file monitoring: 'F:\git_managed\github\OrchardCMS\Orchard.git\src\Orchard.Web\Themes'. Common reasons for failure include:
...
- The file specified is a directory.
...
```
As far as I understand this code is used to watch directories (~/Modules, ~/Themes etc) so it will never work as intended..

**Comment by DanielStolt** [comment]
What branch/version?

**Comment by qt1** [comment]
Just tested with 1.9.1
Please note you have to enable break on exception System.Web.HttpException to see that something is wrong.
I noticed this after enabling all exceptions looking for another problem..
I suspect this is like that for a long time, so it does not do any immediate harm but according to the description in the exception it just does not work because you can not monitor directories..

**Comment by sebastienros** [comment]
It is by design. On a dev box we watch everything to trigger automatic compilation when a file has changed. The watcher doesn't support folders. But it's actually faster to catch the exception than checking if there will be an exception, MUCH faster. Unless you prove it has changed.
