### ISSUE TITLE
Dynamic Forms - Clearing Values on Validation Error

### ISSUE THREAD

**Issue by RG29** [OrchardCMS/Orchard#5437]
When submitting a dynamic form if a validation error occurs all select list, multi-select list, and check box elements are cleared (lose their selections). Textboxes retain the data entered, but everything else is cleared.  This is a huge problem if you have a form with a bunch of select lists.  This is a huge usability impact to dynamic forms.

Repro Steps:  1) Create Dynamic form with a Text Box, Check Box, and Select List (you can use an enumeration).
2) Add validation so that you can get the text box to fail on submission.
3) Fill out the form (check the check box and make a selection from the select list).  Ensure that the textbox will fail validation.
4) Try to submit the form.

The form should fail and the checkbox and select list values should clear and go back to default state.

Orchard Version:  1.9.0.0

**Comment by sfmskywalker** [comment]
Fixed in 2c496a36db7aa8dd378c4f66bdb48eb344018b6e.
