### ISSUE TITLE
SSH.net as a reference error

### ISSUE THREAD

**Issue by mcabrera190** [OrchardCMS/Orchard#5439]
Hi, 

I'm trying to SSH into Linux servers and I found the package SSH.net. It works in standalone projects I've made ,but when i try to add it as a reference and run it on orchard it gives me an error saying it cant load it. (See error below) 

An exception of type 'Orchard.OrchardCoreException' occurred in Orchard.Framework.dll but was not handled in user code 

Additional information: Error compiling module "Modules.SSH.Module" from file "/OrchardLocal/Modules/Modules.SSH.Module/Modules.SSH.Module.csproj": 

Assembly reference 'Renci.SshNet, Version=2013.4.7.0, Culture=neutral, processorArchitecture=MSIL' for project '/OrchardLocal/Modules/Modules.SSH.Module/Modules.SSH.Module.csproj' cannot be loaded 

I've added it using nuget and I'm not understanding why it refuses to run and load the referenced package. Is there something I'm not doing right or does orchard not allow it?

**Comment by sebastienros** [comment]
You need to ask the owner of the package, or fix it by yourself. Try to look at other modules using external libraries to see how to reference and ship them.

**Comment by choikwa** [comment]
Check your namespaces
