### ISSUE TITLE
Dynamic Forms Field Bindings

### ISSUE THREAD

**Issue by jonvee** [OrchardCMS/Orchard#5445]
I've never really used field bindings, but trying to create a content item from a dynamic form and I'm not seeing the bindings tab when editing a field. My workflow decision isn't working so I'm guessing it's because there are no bindings.
Is my install broken or did bindings get deprecated, or is this a bug?

**Comment by sfmskywalker** [comment]
That's a bug. I just tried and was able to reproduce the issue. To work around the issue, you need to edit the Form element and hit Save again. We'l look into it. Thanks for reporting!

**Comment by jonvee** [comment]
Thanks Sipke!

**Comment by jonvee** [comment]
After a bit more testing... (For others experiencing this issue) It seems the work around is only effective if all form fields/elements are directly in the Form itself. When you start adding grids and columns for a customized layout, the workaround has no effect... Or at least none yet for me ;)

**Comment by sfmskywalker** [comment]
Fixed in b18f153e6a3e421947e896a3260eaa9449f7bb62.
