### ISSUE TITLE
Adding a Content Item Element that renders own form in the Layout Part.

### ISSUE THREAD

**Issue by neTp9c** [OrchardCMS/Orchard#5452]
If Content Item displays own form (ex. Product from the Nwazet Commerce Module displays form with "add to basket" button) and if that content is added by Content Item Element to Layout Part Editor that it gives a error after saving.

Error:
The anti-forgery token could not be decrypted. If this application is hosted by a Web Farm or cluster, ensure that all machines are running the same version of ASP.NET Web Pages and that the <machineKey> configuration specifies explicit encryption and validation keys. AutoGenerate cannot be used in a cluster.

**Comment by sebastienros** [comment]
Told you @sfmskywalker. Trying to __render__ front-end UI in the admin can just cause trouble.

**Comment by sfmskywalker** [comment]
Yeah yeah you must hate it being right ;)
I propose we render some abstracted version of the content items. Similar to what we do when rendering a `ValidationSummary` element, which is rendered as a simple greyish block element. We could display the DisplayText property of the selected content items.

**Comment by sfmskywalker** [comment]
Fixed in 1093e16a81e4a3218f1b7e2d3488901ceda94d18.
