### ISSUE TITLE
Admin culture picker does'nt work on localhost

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/Orchard#5457]
Same place as the other time. I tried to make the admin culture picker work on a website using localhost and found that the cookie domain should never be set to localhost else it will never work. Here is what I did in CookieCultureSelector.cs.

``` C#
cookie.Domain = httpContext.Request.Url.Host != "localhost" ? httpContext.Request.Url.Host : null;
```

Setting the Cookie.Domain = null makes this work.

**Comment by Jetski5822** [comment]
Does IsLocal() on the request work instead?

**Comment by Skrypt** [comment]
yes and this would be a better solution

```C#
cookie.Domain = !httpContext.Request.IsLocal ? httpContext.Request.Url.Host : null;
```
