### ISSUE TITLE
SchemaBuilder does not support Column<Guid>

### ISSUE THREAD

**Issue by qt1** [OrchardCMS/Orchard#5464]
The native syntax for creating Guid columns is not supported 
SchemaBuilder.CreateTable("MyTable", table => table.Column<Guid>(

**Comment by Piedone** [comment]
Well, why not have this.

**Comment by Ermesx** [comment]
I have guid id columns in my application and I have to do something like thatt:
``` c#
SchemaBuilder.CreateTable(
                "TableName",
                table =>
                table.Column("Id", DbType.Guid, c => c.PrimaryKey()));
```
