### ISSUE TITLE
Orchard.List "Choose Items" action is not supported under /OrchardLocal sub url.

### ISSUE THREAD

**Issue by owen26** [OrchardCMS/Orchard#5466]
In development environment, orchard automatically deploy to two urls including:

- /
- /OrchardLocal

When access admin panel under **/OrchardLocal** (which is the default one), the **choose items** button from within a custom list is trying to access url under **/** (without /OrchardLocal), which redirected to login page and does nothing even successfully logged in.

**Comment by sfmskywalker** [comment]
Which version are you using? What I see is that BaseUrl is used as specified in Settings - not "/".

**Comment by owen26** [comment]
@sfmskywalker thank you for your reply.

I use version 1.9.0.

BaseUrl is left NULL in my settings which I think is the default value when set up a new Orchard site. I guess that's the problem lead to this error. When I change BaseUrl to **http://localhost:30321/OrchardLocal**, problem solved.

Although not related to Orchard.List, it's still a little misleading. Since the default setting for BaseUrl is "NULL", and default development url is "/OrchardLocal"

I found only a minor group of features in Orchard (such as Orchard.List module) use BaseUrl setting for root detection. And there are inconsistencies across many different modules. Not to say when involving multi tenancy module.

I'm still learning Orchard at the moment so I can't give proper advice, but maybe some improvements can be done to get Orchard urls usage better organised and documented.

Since it's not related to my original issue, I'll close this ticket.

**Comment by sfmskywalker** [comment]
No worries. Actually, the default value for the base URL setting is set during setup by means of some command executed as part of the Default recipe (and probably Core recipe as well, but didn't check). Regarding better organization, perhaps you could describe and list the inconsistencies you discovered?
