### ISSUE TITLE
The controller for path '/' was not found

### ISSUE THREAD

**Issue by GadgetGeekUK** [OrchardCMS/Orchard#5472]
Using the latest 1.9 source code, the site starts up, I select SQL CE, default recipie, 'Cooking Recipie' appears followed by the exception: The controller for path '/' was not found
![orchard](https://cloud.githubusercontent.com/assets/13166551/8499930/7c6cdd24-218f-11e5-9e25-ba79df9fa006.png)

**Comment by pszmyd** [comment]
Can you please give more insight on your local config (IIS vs IIS Express, localhost:XXX vs custom domain etc.)? I've see those a few times, but never made a consistent repro.

**Comment by GadgetGeekUK** [comment]
I have rebuilt it via both the command line and via VS. The IIS settings for the web project are just set to: http://localhost:30321/
![capture1](https://cloud.githubusercontent.com/assets/13166551/8516449/3e8f49d2-23ac-11e5-9431-babca85a92c0.PNG)

**Comment by GadgetGeekUK** [comment]
This issue has gone when I use the new 1.9.1 source code. I'm still not clear why it happened, but as long as it doesn't come back... ;)
