### ISSUE TITLE
codegen theme leads to NotImplementedException if module CulturePicker is enabled

### ISSUE THREAD

**Issue by dpomt** [OrchardCMS/Orchard#5475]
[NotImplementedException: Die Methode oder der Vorgang ist nicht implementiert.]
   bei System.Web.HttpRequestBase.get_HttpMethod()
   bei Orchard.Localization.Selectors.ContentCultureSelector.GetCulture(HttpContextBase context)
   bei Orchard.Localization.Services.CurrentCultureWorkContext.<>c__DisplayClassa.<GetCurrentCulture>b__3(ICultureSelector c)
d\orchard-rems-service\src\Orchard\Localization\Services\CurrentCultureWorkContext.cs:Zeile 29.
   bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)

**Comment by belgeunefois** [comment]
I think it appear when a an "ICultureSelector" implementation is activated within a module...
Before 1.9.1 the httpContext in "Orchard.Localization.Services.CurrentCultureWorkContext.GetCurrentCulture()" was null during "package create" command and now it's an "HttpContextPlaceholder" with a Request property of type "HttpRequestPlaceholder". It return the HttpMethod directly from HttpContextBase which is null. :-(

I must disable all my localization modules before create package.

**Comment by sebastienros** [comment]
I also commented on the PR

> This is a typical issue when using the placeholder that one of its properties is null or not implemented. In this case please add the missing implementation to the HttpContextPlaceholder class.
