### ISSUE TITLE
WebDeploy 1.9.1 errors

### ISSUE THREAD

**Issue by Hazzamanic** [OrchardCMS/Orchard#5484]
Hey,

In the web.config for a few modules assemblies have been added to other Orchard modules, which is causing the following error during webdeploy:

Error ASPCONFIG: Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified.

So Orchard.DynamicForms web.config looks like this in 1.9.1:

```
<system.web>
        <compilation targetFramework="4.5.1">
            <assemblies>
...
                <add assembly="Orchard.Layouts" />
            </assemblies>
        </compilation>
    </system.web>
```

Is there something special I need to do for webdeploy to work or is adding these assemblies having an unintended side-effect of breaking webdeploy?

**Comment by dcinzona** [comment]
Don't pre-compile during the deployment. I ran into the same issue.

**Comment by Hazzamanic** [comment]
@dcinzona cheers buddy

**Comment by dcinzona** [comment]
:+1:
