### ISSUE TITLE
Gulp not running in VS2015 RC

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#5488]
I modified some less code but discovered that no task was runned when I saved it.
I also noticed that when I expend the layout project and show all files I have not NPM node as stated in various comments around using gulp, so no way to reinstall or refresh missing packages.
What are the exact files to install with VS 2015 RC ?  Node, web essential for 2015, gulp ?, other ?
Seems that the new gulp usage in place of web.essentials is not working in actual orchard solution under vs2015 RC ?

CS

**Comment by Skrypt** [comment]
Compiler
https://visualstudiogallery.msdn.microsoft.com/3b329021-cd7a-4a01-86fc-714c2d05bb6c
Minifier
https://visualstudiogallery.msdn.microsoft.com/9ec27da7-e24b-4d56-8064-fd7e88ac1c40

as stated on the Web Essentials 2015 extension if you read the text.
https://visualstudiogallery.msdn.microsoft.com/ee6e6d8c-c837-41fb-886a-6b50ae2d06a2
They removed the compiler and the minifier of the solution to make them separated modules.

**Comment by CSurieux** [comment]
Yes this could provide a solution if it works, but it is not in the 'spirit' of VS 2015 and of what has been done in layout and 2 other modules where it seems that they intend to use gulp.
I read what they did in W.E, the intention seems to be to use Node.js + Gulp + Bower as stated here
http://docs.asp.net/en/latest/client-side/index.html

Yes I know: it seems a little complicated....but if the wind blows this direction.

Even the authors of layout module use gulp.

Anyway thanks.

**Comment by DanielStolt** [comment]
Unless you want to modify the Less or TypeScript files of these modules, you don't need to worry about Gulp. See https://github.com/OrchardCMS/Orchard/issues/5450 for more info.

**Comment by CSurieux** [comment]
Yes it was my point, when I change a less file nothing happen, no news css.

**Comment by DanielStolt** [comment]
I see. Well the information I linked to should explain what you need to get it started. Basically install Node.js on your machine, run `npm install` from the module directory, and then run `gulp`.

**Comment by CSurieux** [comment]
Thanks, I was not knowing of this #5450 discussion.

**Comment by CSurieux** [comment]
Just a pointer for those who want to compile bootstrap with vs2015 RC
https://www.orderfactory.com/articles/Bootstrap-LESS-Grunt-VS.html

**Comment by CSurieux** [comment]
Ok, it works, just an installation problem. Closing it.
