### ISSUE TITLE
Web request workflow activity using the JSON format does not escape characters like ", /, or \ in tokens

### ISSUE THREAD

**Issue by douwinga** [OrchardCMS/Orchard#5492]
When using the web request workflow activity in JSON format with the FormSubmission.Field token (does not really matter what token, but this is the most likely to cause this issue) to send form data to other systems, any field that contains characters like ", /, or \  causes errors because they invalidate the JSON.

Repro steps:

1) Create a new dynamic form with a submit button and a text field. Name the form ContactUs and name the field Comments.
2) Create a workflow that triggers with a "Dynamic Form Submitted" action and set the dynamic form to ContactUs. Turn the trigger on
3) Add a "Web Request" activity to the form and link the trigger to this activity.
4) Set the the url to something that accepts only valid JSON (sorry I don't have anything public that can be used).
5) Set the Verb to POST
6) Set the Form Format to Json
7) Set the Form Values to:
```
((
"Comments": "{FormSubmission.Field:Comments}",
))
```
8) Add a logging activity to the workflow
9) Drag the error path of the web request activity to the new logging activity
10) Set the logging activity entry level to Error
11) Set the logging activity message to:
```
Form Submission Workflow Failed

WebRequestResponse: {Workflow.State:WebRequestResponse}
```
12) Save the workflow
13) On the frontend navigate to your form. In the comments field put in the following value:
```
This is a test and "I am quoting something" which causes this to break
```
14) Submit the form
15) Check the log and you will see an error

**Comment by douwinga** [comment]
Would it make sense to just have another token that handles the JSON string escaping? Something like {JsonEscape:{FormSubmission.Field:Comments}}

**Comment by bleroy** [comment]
I would do it the other way around: add an escaping token to string tokens. {FormSubmission.Field:Comments.EscapeJs}

**Comment by douwinga** [comment]
Looks like pull request #5568 will add the ability to do token chaining on the FormSubmission token which should make a fix for this easier once it is merged.
