### ISSUE TITLE
Compile Error during the execution of the Orchard CMS from GitHub

### ISSUE THREAD

**Issue by HaifengMei** [OrchardCMS/Orchard#5496]
Orchard was successfully cloned on to my local repository. There were no building errors however there were runtime errors. 

(Compiler Error Message: CS0841: Cannot use local variable 'tagBuilder' before it is declared) 

This error appears after initial creation of website which then prevent any further execution, hence we are unable to load the website.

**Comment by sfmskywalker** [comment]
Which branch is that?

**Comment by HaifengMei** [comment]
The dev branch

**Comment by sebastienros** [comment]
Works for me.
