### ISSUE TITLE
Make content import dependency-order-agnostic

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#5497]
Design notes:

- Add an optional method that drivers can implement to express their content item dependencies by returning a list of XElements (selected from the specified <Data> element containing ALL content item elements)
- Dependencies are pushed to the top.
- Once this phase is complete, the actual import process will begin.

**Comment by sfmskywalker** [comment]
Closing, this doesn't seem to be an issue.

**Comment by IntranetFactory** [comment]
We frequently have problems with the order of imports - which frequently requires that an import is executed 2+ times until all references between content items are resolved.

**Comment by sfmskywalker** [comment]
You do? Would you mind sharing with me a recipe that reproduces the issue? I haven't been able to. Thanks!

**Comment by sfmskywalker** [comment]
Also, can you let me know on what Orchard version you're seeing this?

**Comment by IntranetFactory** [comment]
Our fork is between 1.8.x and 1.9 and we don't use a recipe for the import. But the problem happens e.g. with a content picker. Let's say we have item A with Id 1, which has a content picker referencing item B with Id 2. We export both. When A is imported item 2 isn't yet imported, so the reference can be resolved. If the import is executed again B exists and A is updated. But this requires that the import is executed twice. If we have dependencies between more content types then the import even needs to run multiple times until all references are resolved.

Should this work OOTB with just running the import once?

**Comment by sfmskywalker** [comment]
That should work OOTB but I'll give that a try. Thanks for providing these repro steps.

**Comment by sfmskywalker** [comment]
Can't reproduce. This is what I tried:

1. Create a Product content type with two Content Picker Fields: User Guide and Developer Guide.
2. Created 2 Page items: Product 1 User Guide and Product 1 Developer Guide.
3. Created a Product item called Product 1 and selected both a Page item for both content picker fields.
4. Exported Page and Product types and data.
5. Nuked my Orchard installation and recooked the Default recipe.
6. Enabled Import Export
7. Imported the exported recipe file from step 4.
8. The Product content item was correctly pointing to the referenced Page items.

Please reopen this issue if you have repro steps for Orchard 1.9 or higher on a clean installation. Thanks.

**Comment by IntranetFactory** [comment]
It depends of the order of the export items - sometimes it works. If Product item is exported after the Page item it will work. Is it correct to assume that your export file contains the page items **before** the product items?

**Comment by sfmskywalker** [comment]
Sorry, I forgot to mention that I manually edited the exported recipe by putting the Product item before the Page (dependencies) items.

**Comment by IntranetFactory** [comment]
I reproduced your use case without changing the export file - and to my surprise it worked with a basic use case. So it's obviously not a general problem. I'll try to reproduce the issue we see and open an extra case if the problem becomes reproducible.

**Comment by sfmskywalker** [comment]
Perfect, thanks.
