### ISSUE TITLE
Improvement for module/feature compatibility

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#5500]
As there is a dependency list in module.txt, there should exist a restriction list.
If this list is maintained in the module.txt file, it would contain all the features which should not be enabled to allow actual feature to run correctly. If one of these feature is enabled, it should not be possible to enable any module/feature referencing it in its restriction list.
As an example: 2 different sub-systems dealing with same process but incompatible for an eCommerce package which can't be activated on the same time in the same orchard instance (ordering/payment or shipping ).

**Comment by Piedone** [comment]
I think this is more a question on how you develop your module, as it shouldn't interfere with other modules in a wrong way. In your particular case rather the two modules should have subfeatures for e.g. payment so they won't clash since you can select which one to enable.

**Comment by CSurieux** [comment]
In my modules that's the case but who can prevent someone to validate 2 Paypal Payments features or 2 order management ?

**Comment by Piedone** [comment]
Again this is something that IMO should be solved with better module design so two developers don't implement clashing features, unaware of each other. BTW even with your suggestion of adding features in the module manifest to disable the authors of the two modules would need to know about each other and each other's module. So even if the technique would solve some scenarios it depends on developers to communicate with each other.

**Comment by CSurieux** [comment]
And how to avoir 2 paypal payments??? And There are hundred other colliding areas.
The idea behind all this Is to have better classification of features. Si no necessity of impossible communication between implementors. You just add a keyword for your module fonctionnal area. May be the category could a used and extended, a kind of singleton for features.

**Comment by sfmskywalker** [comment]
Ah I think I see what you mean. There could for example be a field in Settings.txt called "Domain". When two features are of the same domain, only one of them can be enabled. I think this could be useful, but maybe even better would be to make Settings.txt extensible. That way you could implement this regardless of whether others find this useful or not. I believe there's an issue on module manifest extensible already.

**Comment by CSurieux** [comment]
"There could for example be a field in Settings.txt called "Domain". When two features are of the same domain, only one of them can be enabled."
Yes you got it.
The optional keyword could be 'Domain' with an optional modifier as 'Exclusive'.

But if this is only a proprietary extension for one's modules, it is a nonsense.

**Comment by sfmskywalker** [comment]
True, it would have to be a framework feature, otherwise all modules that want to handle this would need to share the same code.

**Comment by harmony7** [comment]
I have another simple use case of where this would be useful.

Orchard comes with TinyMce but we created a module for CkEditor as we have clients who prefer it. The two are in direct conflict and it would be nice if the framework can support the notion of allowing just one of these to be enabled.

**Comment by CSurieux** [comment]
Yes and this could drive to some reorg concerning features are defined.
may be we could start to create a global list of business features or validate some existing taxonomy for it
