### ISSUE TITLE
Import creates duplicate homepages

### ISSUE THREAD

**Issue by DanielStolt** [OrchardCMS/Orchard#5504]
When importing a recipe on an existing site that contains an item with alias "/", and the recipe contains an item with that same alias, duplicates are created. For other aliases, it seems this is not the case.

**Comment by sfmskywalker** [comment]
Created a PR here: https://github.com/OrchardCMS/Orchard/pull/5556

**Comment by sfmskywalker** [comment]
Fixed with this PR: https://github.com/OrchardCMS/Orchard/pull/5567
