### ISSUE TITLE
Orchard.Search: ContentPicker Search does not work when Search Settings should filter on ContentType

### ISSUE THREAD

**Issue by hsbicego** [OrchardCMS/Orchard#5506]
at Line 78 of \Modules\Orchard.Search\Controllers\ContentPickerController.cs it tests The Name of the part.
It Sould test also the Name o the content.
Line is
.Where(x => x.Parts.Any(p => rawTypes.Contains(p.PartDefinition.Name)))
**but should be**
.Where(x => x.Parts.Any(p => rawTypes.Contains(p.PartDefinition.Name) || rawTypes.Contains(x.Name)))

**Comment by MatteoPiovanelli** [comment]
5 year later, this issue should be closed as the Setting for search on ContentPickers works as it is today
