### ISSUE TITLE
Incorrect message of DynamicForms StringLength rule if only Maximum is specified

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#5512]
Can be fixed in StringLength.cs by replacing this

    if (Minimum != null && Maximum != null)
        return T("{0} must be between {1} and {2} characters long.", context.FieldName, Minimum, Maximum);

    return T("{0} must be at least {1} characters long.", context.FieldName, Minimum);

With

    if (Minimum != null && Maximum != null)
        return T("{0} must be between {1} and {2} characters long.", context.FieldName, Minimum, Maximum);
    else if (Minimum != null)
        return T("{0} must be at least {1} characters long.", context.FieldName, Minimum);

    return T("{0} must be at most {1} characters long.", context.FieldName, Maximum);

Best

**Comment by sebastienros** [comment]
This is very close to a PR, you know you can edit the code and create a PR directly from the web?
