### ISSUE TITLE
OrchardLayouts:  404 (not found) for the fontawesome-webfont.woff2 file

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#5513]
Can be fixed by adding this in the staticContent section of the Orchard.Layouts/Styles/Web.config

      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />

Best

**Comment by Piedone** [comment]
This is only an issue if your app doesn't serve woff2 files already. See related PR by @dcinzona : https://github.com/OrchardCMS/Orchard/pull/5476

**Comment by jtkech** [comment]
Ok, I understand
