### ISSUE TITLE
DynamicForms client validation issue

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/Orchard#5519]
It seems there is an issue since e8de82b611063dd59969ed5f4fcd62b79f6e30.

The script throws a null exception, and then client validation fails.

*jquery.validate.unobtrusive.additional.js* should be added after *jquery.validate.unobtrusive.js* in *gulpfile.js*

**Comment by Jetski5822** [comment]
Fixed in https://github.com/OrchardCMS/Orchard/pull/5551

**Comment by TFleury** [comment]
Reintroduced by 6da6c5c214a40d71c2c714a0d0ba8e6aa018120a
