### ISSUE TITLE
On setup screen, prefix recipes with module name

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#5525]
Now that modules and themes can provide recipes, it becomes necessary to prefix the recipe names by the module/theme name they were harvested from to disambiguate between them.
And sort by name.

**Comment by sebastienros** [comment]
The recipe name is controlled and can be changed to a custom convention. At least please check that recipes are displayed in order.

**Comment by sebastienros** [comment]
Other solution is to have a Category property on the recipe to group them, not using the module name.
