### ISSUE TITLE
Extending ProjectionPartDriver and ProjectionManager With part.ContentItem tokens

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#5533]
I'll try to describe what I want to achieve:
1. I have a Projection with a text field
2. I would like the Query referenced in ProjectionPart to filter Contents by the value stored my projection text field
**but**
1. ProjectionPartDriver (line 113) when it calls projectionManager.GetContentItems doesn't pass part.ContentItem informations
**So the idea is:**
modify line 113 like this
var contentItems = _projectionManager.GetContentItems(query.Id, pager.GetStartIndex() + part.Record.Skip, pager.PageSize, new Dictionary<string, object> { { "Content", part.ContentItem } }).ToList();
full chenages will be there in my next push.

I have a backward compatible solution ready, I will push it soon...
Any

**Comment by sebastienros** [comment]
Thank you, however I don't really like the changes it implies on the code. What you could do is use another existing token which lets you get the currently displayed content item. Then your query could use this token to point the projection, and use a continuation to access its field. Would that work ?

**Comment by HermesSbicego-Laser** [comment]
@sebastienros can you suggest where to find the existing token ({Request.Content} perhaps)? I never used a "continuation"... How should I do that? Can you give me a starting point?
TY

**Comment by sebastienros** [comment]
{Request.Content.Fields.YOURPART.YOURFIELD}

**Comment by HermesSbicego-Laser** [comment]
@sebastienros,  we used proposed solution till now, so, request.content is perfect if i have a request.content. but i cannot use it in other contests, like within widgets for example. Any idea on how to solve it? In general I think that having the ability to pass a dictionary to projectionmanager methods which uses queries should be considered...

**Comment by sebastienros** [comment]
I changed my mind and it actually makes sense based on @HermesSbicego-Laser's feedback.

I suggest to pass the ProjectionPart to the Query api calls.
