### ISSUE TITLE
FormsAuthenticationService should use IMembershipService instead of IContentManager to retrieve the IUser object

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/Orchard#5536]
`IMembershipService` is responsible for creating and retrieving users.

`FormsAuthenticationService.GetAuthenticatedUser()` retrieves the currently logged in `IUser` object from the Content Manager (line 141). This means that this implementation of `IAuthenticationService` makes the assumption that users are always stored as Content Items. This assumption would be incorrect if the implementation of `IMembershipService` had been swapped out.

I propose that the `IUser` object is instead retrieved from `IMembershipService.GetUser(string username)`.

**Comment by Piedone** [comment]
Sebastien attempted this and it failed for some reason. @sebastienros ?

**Comment by sebastienros** [comment]
Exactly. Doing so was failing the setup as there would be no default implementation available before the Users module is enabled. And we try to impersonate as "admin" during the setup. The solution might be to refactor the `IMembership` or to have a default dummy implementation in Framework. Please take a look at the history of `FormsAuthentication` to see what I had tried to do.

**Comment by Piedone** [comment]
Maybe we should just add a NullMembershipService from Orchard.Setup that doesn't do anything, purely to enable setup to run?

**Comment by DanielStolt** [comment]
I don't understand why this was an issue for you @sebastienros - `SetupService.CreateTenantData()` does call `FormsAuthenticationService.SetAuthenticatedUserForRequest()` and also `FormsAuthenticationService.SignIn()`, but **before** that it actually resolves an `IMembershipService` in the same method, so the implementation must be available, no?

**Comment by DanielStolt** [comment]
I got curious, just had to find out. I see the problem now, the problem is the *temporary* work context scope used to obtain the new shell descriptor, in which only `Orchard.Framework` and `Settings` are enabled. Indeed, some kind of `NullMembershipService` would be needed here. I think that's a good solution.

**Comment by sebastienros** [comment]
Thanks, and I see that you took the username change too. FYI the SuppressDependency is not needed for framework services as the module will always take priority. But that's fine.

I will follow the integration tests as it is there that I could see it failing.

**Comment by DanielStolt** [comment]
Ah, I didn't know that. I realized in the middle of my sleep that perhaps the `NullMembershipService` is unnecessary too, if `FormsAuthenticationService` resolves the `IMembershipService` when it needs it, instead of injecting it into the constructor?

**Comment by DanielStolt** [comment]
@sebastienros It's my understanding that while the module implementation will take precedence, if anybody ever injected or resolved an enumerable of `IMembershipService` they would get both, so I think suppressing the default is a matter of hygiene no?

**Comment by sebastienros** [comment]
About resolving the dependency only when necessary, I used a Lazy at first, and it still didn't work in some scenarios.
