### ISSUE TITLE
SecureSocketLayer in 1.9.X is older than in 1.8.x and Dev branches, why #5202 not applied ?

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#5538]
After many problems with my localhost:44300 secured url in dev, invoking a bug in w10 because I was getting this
![image](https://cloud.githubusercontent.com/assets/2103534/8762583/ca5fd492-2d7d-11e5-802c-4007c45c0bd0.png)

I finally read history for the file SecureSocketsLayerService.cs and see that the correction in #5202, originally applied in 1.8.x is in Dev but not in 1.9.x.

Could we get it to fix this SSL settings pb.

Thanks

**Comment by CSurieux** [comment]
I proposed a PR for 1.9.x here
#5538 Urlbuilder Pb in 1.9.X SecureSocketLayer Module

**Comment by Piedone** [comment]
That commit is in the dev branch only, not in 1.8.x.

**Comment by CSurieux** [comment]
I just say this reading the comments on the PR provided by @jtkech 

@sebastienrossebastienros modified the milestone: Orchard 1.8.x, Orchard 1.8.2 on May 5

But this certainly does not means it has been applied to 1.8.x or 1.8.2

**Comment by CSurieux** [comment]
Well Orchard is not very funny? Isn't it ?
