### ISSUE TITLE
Orchard Displayed YSOD After Deploying to Azure

### ISSUE THREAD

**Issue by jchenga** [OrchardCMS/Orchard#5539]
Instead of getting the set up page, I got the YSOD after deploying to Azure. This is caused by the incorrect binding redirection for System.Web.Mvc in Web.config in Orchard.Web.Azure: 

<bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.0.0"/> should be

<bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0"/>

I am using branch 1.9.x. I'll create a pull request shortly.

**Comment by sebastienros** [comment]
I think the PR has been accepted, please reopen if I am wrong.

**Comment by Jetski5822** [comment]
I accepted it :)
