### ISSUE TITLE
bug/regression: Orchard.Search for ContentPicker doesnt't show correct search form/View

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#5552]
Step to reproduce:
prerequisites:
Modules 
1. Orchard.Search all features enabled (Admin Content Search, Content Picker Search, Media Library Search, Search)
2. Lucene
Then:
1. I created a Content Type "Contatto"
2. In Page i added a ContentPicker Field Named Contatti
Settings are:
![image](https://cloud.githubusercontent.com/assets/13333709/8798814/74fed4c4-2fa5-11e5-8207-7e326dee3311.png)
3. In my Page when i try to Add one of my Contatto to Contatti field, and I presss Search Tab, this i s the result:
![image](https://cloud.githubusercontent.com/assets/13333709/8798836/ad08148e-2fa5-11e5-9d7d-ecc7cbe8a8c6.png)
but should be a form to full-text search my contents...

I found this bug because I would like to apply a patch for Content-Type filter described at #5506

The LocalNav routes in a wrong Controller/Action
Adding this new route, 
                new RouteDescriptor {
                    Priority = 5,
                    Route = new Route("ContentPickerSearch/{searchIndex}",
                        new RouteValueDictionary {
                            {"area", "Orchard.Search"},
                            {"controller", "ContentPicker"},
                            {"action", "Index"},
                            {"searchIndex", UrlParameter.Optional}
                        },
                        null,
                        new RouteValueDictionary {
                            {"area", "Orchard.Search"}
                        },
                        new MvcRouteHandler())
                }

Form is displayed.
But ContentPicker Search does not work.
many problems:
1. it search within Search Index... but it should search within index specified into ContentPickerFieldSettings.SearchIndex (in most cases Admin)
2. It should search in fields described into that Index (in most cases Admin)
and so on...

**Comment by sebastienros** [comment]
Do you know by chance which commit broke that. Just asking as you helped me this way on the localization bug ;)

**Comment by HermesSbicego-Laser** [comment]
hi Sebastien, I was working on dev branch.
This seems to be a change made into the dev branch beacuse in 1.9.x it partially works (it routes correctly, but cpf does not filter by ContentPart/ContentType names ). Hope this helps.

**Comment by jtkech** [comment]
Just found from which commit the route issue is and how to fix it. I've also a fix to use the correct searchIndex from the picker field settings, and just found why the content type filtering doesn't work (I think there is the same problem in the MediaController with mediaType)...

I need more tests to validate this, no time right now, I will do a PR tomorrow

Best
