### ISSUE TITLE
Build precompiled : Custom themes compiled as modules

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/Orchard#5557]
Issue present in 1.9.x since 7282df432688b0b833559cbc9d88b36568215b3c

Default themes are correctly compiled, but custom ones remains uncompiled in Themes folder.
A compiled version of custom themes was outputed in Modules folder.

**Comment by sebastienros** [comment]
I broke it. Was not sure, checked, and couldn't see the issue. I will fix it.
