### ISSUE TITLE
How to create a module that allow users in the front end to add items to a list on the front end.

### ISSUE THREAD

**Issue by HaifengMei** [OrchardCMS/Orchard#5558]
I am trying to create a module which generate a list of recent activities for a user. The module should allow users to add a new activity(with 3 fields: Title, Detail and Date) in the editor templates, however the editor view should provide an a "add" function to enter another activity. 

I read and tried out the SampleAddress module:
http://docs.orchardproject.net/Documentation/Creating-1-n-and-n-n-relations#UsingtheAddressPart

What i learnt is that you are able to use IEnumerable to store items in a list. However sample module pre-populates the table in the datamigration.cs. Instead of that, i want to allow user to populate it the list on the front end.

This is what i wish the list look like(no need to worry abt css):
<img width="396" alt="myactivity" src="https://cloud.githubusercontent.com/assets/13001527/8810144/fe35825a-2fba-11e5-86d4-9abdf2c7a71d.png">

I thank you in advance for any form of assistance, i am a beginner in orchard and C#  so i request simple guidles in how to use IEnumerable or IList in orchard to accept and store data accordingly.

**Comment by sfmskywalker** [comment]
I don't think this is suitable as a GitHub issue. Can you please ask your question on [CodePlex](http://orchard.codeplex.com/) or [OrchardPros](http://orchardpros.net)? Thanks
