### ISSUE TITLE
Current 1.9.x branch fails test ConvertFromLocalizedDateStringTest01()

### ISSUE THREAD

**Issue by netwavebe** [OrchardCMS/Orchard#5559]
The current 1.9.x branch does not build:

"D:\Microsoft Visual Studio\Orchard\Branches\1.9\Orchard.proj" (Build target) (1) -> (Test target) ->
NUNIT : 1) Test error : Orchard.Tests.Localization.DefaultDateLocalizationServicesTests.ConvertFromLocalizedDateStringTest01 [D:\Microsoft Visual Studio\Orchard\Branches\1.9\Orchard.proj]

**Comment by DanielStolt** [comment]
Fixed in 7411013b456e131f87d598b3f323cebd5ca514ee.

**Comment by netwavebe** [comment]
Thanks, Daniel!
