### ISSUE TITLE
How to empty an IRepository in orchard migrations?

### ISSUE THREAD

**Issue by HaifengMei** [OrchardCMS/Orchard#5569]
I have the following code in my migrations.cs

private readonly IRepository<AlertProgramRecord> _alertProgramRepository;

        private readonly IEnumerable<AlertProgramRecord> _alertPrograms =
            new List<AlertProgramRecord> {
                /*new AlertProgramRecord {Message = "Payment of 20,000 sucessfully made for My Home - Home Loan (A/C No. 1245645) on 5th April 2015.", TransID = "Transaction ID 57845412", ALertType="success"},
                new AlertProgramRecord {Message = "Your premium for Medallion (Policy No: 11921564) is due on 30th March 2014.", TransID = "Would you like to pay now?", ALertType=""},*/
            };

        public AlertModuleDataMigration(
            IRepository<AlertProgramRecord> alertProgramRepositoryRepository)
        {
            _alertProgramRepository = alertProgramRepositoryRepository;
        }

public int UpdateFrom1()
        {
            if (_alertProgramRepository == null) throw new InvalidOperationException("Couldn't find alert program repository.");
            foreach (var alertProgram in _alertPrograms)
            {
                _alertProgramRepository.Create(alertProgram);
            }
            return 2;
        }

I wish to know how i can empty alertProgramRespository so i can reset migration data and repopulate the repository using data from alertPrograms.

**Comment by Piedone** [comment]
This is not an issue, please ask questions e.g. here: https://orchard.codeplex.com/discussions
