### ISSUE TITLE
Dynamic Forms loads jquery.validate files in the wrong order

### ISSUE THREAD

**Issue by douwinga** [OrchardCMS/Orchard#5586]
The Lib.js file of the Dynamic Forms module is getting generated in the wrong order which causes the following error:

`Uncaught TypeError: Cannot read property 'adapters' of undefined`

This appears to be caused by the Assets.json file as it is doing the following
```javascript
{
        "inputs": [ "Assets/JavaScript/Lib/**/*.js" ],
        "output": "Scripts/Lib.js"
}
```

This causes the validation scripts to load in the following order since it loads them alphabetically:
`jquery.validate.js`
`jquery.validate.unobtrusive.additional.js`
`jquery.validate.unobtrusive.js`

jquery.validate.unobtrusive.js needs to be loaded before jquery.validate.unobtrusive.additional.js

Repro steps:

1. Create a new Form
2. Set the form to use client validation
3. Publish and navigate to the form
4. Check the console log for the error

**Comment by thekaveman** [comment]
There's already a PR for this #5575

**Comment by douwinga** [comment]
Awesome, I just did a quick search in issues and didn't see it. I will check PR next time too before submitting an issue.
