### ISSUE TITLE
Adding new translation fails for Widgets

### ISSUE THREAD

**Issue by NLAppel** [OrchardCMS/Orchard#5590]
Orchard throws an error when you want to translate a widget. 

Steps to reproduce:

-Enable localization
-Add locatization part to a Widget(html widget, menu widget or any other widget)
-Add a supported site culture in Settings.
-Add a Widget to a Zone.
-Open the Widget and click on "+ New translation".

The following error is shown:
![image](https://cloud.githubusercontent.com/assets/13557895/8986608/37f55d2a-36dd-11e5-9271-31dc706fb093.png)

**Comment by Skrypt** [comment]
duplicate #5031
