### ISSUE TITLE
List of Layouts Blueprint Elements isn't cached properly

### ISSUE THREAD

**Issue by neTp9c** [OrchardCMS/Orchard#5596]
It's the same problem that is described in https://github.com/OrchardCMS/Orchard/issues/5134
Summary: Sometimes, Layouts Blueprint Elements isn't displayed.

When i was debugging source code i notice that ElementManager.GetCategories method that uses for configurate Layout doesn't contains Blueprint Element Category. To get this situation you need reproduce steps https://github.com/OrchardCMS/Orchard/issues/5134#issuecomment-105659804

It happens because BlueprintElementHarvester class works incorrect (https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Layouts/Providers/BlueprintElementHarvester.cs).

If change BlueprintElementHarvester.HarvestElements method that it didn't use _isHarvesting variable that all be work fine and this problem will go away.

I think it is possible that ElementManager.GetCategories method (and BlueprintElementHarvester.HarvestElements correspondingly) is simultaneously performed from multiple threads or places (before all data will be cached). Something like this:
1. First call sets _isHarvesting = true
2. Second call return empty enumerable.
3. First call results is cached.
4. Second call results is cached (It's final result with no bluprint elements).

Since i changed source code and removed using _isHarvesting variable that this problem does not appear. I added one parameter to method BlueprintElementHarvester.HarvestElements (insted of _isHarvesting  variable) that it is a flag that determine when this function was be called.

```
namespace Orchard.Layouts.Framework.Harvesters {
    public class HarvestElementsContext {
        public IContent Content { get; set; }
        public System.Type FromHarverster { get; set; } // added by me
    }
}
```

```
namespace Orchard.Layouts.Services {
    public class DescribeElementsContext {
        public IContent Content { get; set; }
        public string CacheVaryParam { get; set; }

        public static readonly DescribeElementsContext Empty = new DescribeElementsContext();

        public System.Type FromHarverster { get; set; } // added by me
    }
}
```

Method from Orchard.Layouts.Services.ElementManager class:

```
public IEnumerable<ElementDescriptor> DescribeElements(DescribeElementsContext context) {
            var contentType = context.Content != null ? context.Content.ContentItem.ContentType : default(string);
            var cacheKey = String.Format("LayoutElementTypes-{0}-{1}", contentType ?? "AnyType", context.CacheVaryParam);
            return _cacheManager.Get(cacheKey, acquireContext => {
                var harvesterContext = new HarvestElementsContext {
                    Content = context.Content,
                    FromHarverster = context.FromHarverster // added by me
                };
                var query =
                    from harvester in _elementHarvesters.Value
                    from elementDescriptor in harvester.HarvestElements(harvesterContext)
                    orderby elementDescriptor.DisplayText.Text
                    select elementDescriptor;

                acquireContext.Monitor(_signals.When(Signals.ElementDescriptors));
                return query.ToArray();
            });
        }
```

Method from Orchard.Layouts.Providers.BlueprintElementHarvester class

```
public IEnumerable<ElementDescriptor> HarvestElements(HarvestElementsContext context) {
            //if (_isHarvesting) // commented by me
            //    return Enumerable.Empty<ElementDescriptor>(); // commented by me

            if (context.FromHarverster == this.GetType()) // added by me
                return Enumerable.Empty<ElementDescriptor>(); // added by me

            _isHarvesting = true;
            var blueprints = _elementBlueprintService.Value.GetBlueprints().ToArray();

            var query =
                from blueprint in blueprints
                let describeContext = new DescribeElementsContext { Content = context.Content, CacheVaryParam = "Blueprints", FromHarverster = this.GetType() } // changed by me
                let baseElementDescriptor = _elementManager.Value.GetElementDescriptorByTypeName(describeContext, blueprint.BaseElementTypeName)
                let baseElement = _elementManager.Value.ActivateElement(baseElementDescriptor)
                select new ElementDescriptor(
                    baseElement.Descriptor.ElementType,
                    blueprint.ElementTypeName,
                    T(blueprint.ElementDisplayName),
                    T(!String.IsNullOrWhiteSpace(blueprint.ElementDescription) ? blueprint.ElementDescription : blueprint.ElementDisplayName),
                    GetCategory(blueprint)) {
                        EnableEditorDialog = false,
                        IsSystemElement = false,
                        CreatingDisplay = creatingDisplayContext => CreatingDisplay(creatingDisplayContext, blueprint),
                        Display = displayContext => Displaying(displayContext, baseElement),
                        StateBag = new Dictionary<string, object> {
                            {"Blueprint", true},
                            {"ElementTypeName", baseElement.Descriptor.TypeName}
                        }
                    };

            var descriptors = query.ToArray();
            _isHarvesting = false;
            return descriptors;
        }
```

**Comment by sebastienros** [comment]
@sfmskywalker

**Comment by davidmoons** [comment]
We do have the same problem on our instance.

Problem occurs 'sometimes', no error is logged.
result is that custom Element Category and elements are not displayed in the editor, and layout is rendered empty on the page.

**Comment by armanforghani** [comment]
@sfmskywalker I have the same problem.
Sometimes, Layouts Blueprint Elements isn't displayed and i have to edit Blueprint Element and save again.

**Comment by carlwoodhouse** [comment]
I'm assuming this is still the case? we launched our first production elements today and experienced something similar on one of our instances, blueprint elements were missing (no errors) others (non blueprint) were fine. Recycling the effected instance fixed it. Is the patch described safe to apply, any thoughts @sfmskywalker ?

**Comment by carlwoodhouse** [comment]
Though i think it might just make more sense to expose isharvesting and not do the cache call if its in process

**Comment by carlwoodhouse** [comment]
i also ponder if the approach of returning an empty list while harvesting is even right ... or if we should just be applying a lock or similar
