### ISSUE TITLE
Orchard DefaultDateFormatterTests failing

### ISSUE THREAD

**Issue by wharri220** [OrchardCMS/Orchard#5598]
I'm attempting to use TeamCity to setup a CI/Deployment pipeline for an Orchard project. I'm attempting to build/deploy using MSBuild and the Orchard.proj file. However, there seem to be some failing unit tests that are preventing a successful build. Some of the tests being run in the DefaultDateFormatterTests are failing. Does anyone have knowledge of this? And are there any plans to fix these unit tests?

**Comment by DanielStolt** [comment]
I wrote these tests and the code under test. Tests are passing on my machine. Can you tell me which version of Orchard, and give me error messages and stack traces of the failing tests please? Also tell me which locale/culture the session is running under.

**Comment by wharri220** [comment]
I'm using Orchard 1.9

The tests are failing on both my local machine, and on the build server I'm running TeamCity on. 

On my local machine: OS: Windows 7 Professional SP1, Culture: English (United States) (en-US)

![culture](https://cloud.githubusercontent.com/assets/9452756/9037069/6cce10f2-39b5-11e5-9f9b-609e52b8ba03.PNG)

Error Message:

![failedtests](https://cloud.githubusercontent.com/assets/9452756/9037056/42cf8056-39b5-11e5-8d30-5495d45ef1cb.PNG)

Strack trace for ParseDateTest01

![stacktrace](https://cloud.githubusercontent.com/assets/9452756/9037114/d9321432-39b5-11e5-9486-8dad8ede740d.PNG)

Stack Trace for ParseDateTimeTest01

![parsedatetimetest01](https://cloud.githubusercontent.com/assets/9452756/9037276/a97e9718-39b7-11e5-8b20-90c72e358100.PNG)

The build server is Windows Server 2008 R2, with similar results, TeamCity error log for ParseDateTest01:

![teamcity](https://cloud.githubusercontent.com/assets/9452756/9037329/275d4f44-39b8-11e5-8485-794ed8a5598b.PNG)

**Comment by DanielStolt** [comment]
If you're still on 1.9 then that would explain it. Tests have been fixed in dev as of https://github.com/OrchardCMS/Orchard/commit/9491a5750bdec559a9fffe59fe63431c40b90b03. Can you try on dev or 1.9.x?

**Comment by wharri220** [comment]
I'm actually using 1.9.1. But if they've been fixed, I'll move to 1.9.x. Thanks!
