### ISSUE TITLE
Problem creating fields attached to taxonomy terms in code

### ISSUE THREAD

**Issue by juanfq** [OrchardCMS/Orchard#5601]
I'm running Orchard v.1.8.1.0 and developing a module. 
In Migrations, I am creating a taxonomy and adding fields to the taxonomy term.
The problem I'm having is that when I go to the content definition view for the term, my fields are not appearing. I have determined the missing piece.

The first section of code below creates the taxonomy and it's term successfully.
Here (among others), a record created in Settings_ContentTypeDefinitionRecord.
The second section of code creates the fields for the term.
Here (among others), a record created in Settings_ContentPartDefinitionRecord.

The missing piece however is that a record is not being created in Settings_ContentTypePartDefinitionRecord tying together the ids from the Settings_ContentTypeDefinitionRecord and the Settings_ContentPartDefinitionRecord records.
When adding a field to a taxonomy from within the content definition view directly, this record is created automatically. Without it, the fields do not appear.

Can you tell me what call I can make to have this record created?

Sample Code: 
            var taxonomyName = "Merchants";
            var taxonomy = _taxonomyService.GetTaxonomyByName(taxonomyName );
            if (taxonomy == null)
            {
                taxonomy = _orchardServices.ContentManager.New("Taxonomy").As<TaxonomyPart>();
                taxonomy.Name = taxonomyName;
                taxonomy.ContentItem.As<TitlePart>().Title = taxonomyName;
                _orchardServices.ContentManager.Create(taxonomy);
                _orchardServices.ContentManager.Publish(taxonomy.ContentItem);
            }

            ContentDefinitionManager.AlterPartDefinition("MerchantsTerm", builder => builder
                .Attachable()
                .WithField("Website", cfg => cfg
                    .OfType("TextField")
                    .WithDisplayName("Website")
                    .WithSetting("TextFieldSettings.Flavor", "Large")
                    .WithSetting("TextFieldSettings.Required", "False"))
            );

**Comment by Devqon** [comment]
I think you are missing a step. You didnt create the term content type for the taxonomy. This is how I've done it:

    private const string KnowledgeTaxonomyName = "Knowledge";

    private void EnsureKnowledgeTaxonomy() {

        var knowledgeTaxonomy = _taxonomyService.GetTaxonomyByName(KnowledgeTaxonomyName);
        if (knowledgeTaxonomy == null)
        {
            knowledgeTaxonomy = _contentManager.New("Taxonomy").As<TaxonomyPart>();
            knowledgeTaxonomy.Name = KnowledgeTaxonomyName;
            knowledgeTaxonomy.ContentItem.As<TitlePart>().Title = KnowledgeTaxonomyName;

            // See this following step:
            _taxonomyService.CreateTermContentType(knowledgeTaxonomy);
            // Now the term content type exists (and therefore also its part)

            _contentManager.Create(knowledgeTaxonomy);
            _contentManager.Publish(knowledgeTaxonomy.ContentItem);
        }
    }

**Comment by juanfq** [comment]
Hi,




Thanks for your reply. 




I had that line of code in at one point but I was getting duplicate content type records, so I removed it. 

The term part itself is not my problem at the moment though I’ll explain my findings on the duplicate term part records in a moment. 




My problem is the record that ties the term part to the content type for the part is not being created.




Using your code as an example, 2 of the tables and the resulting records affected by creating the taxonomy and the term are:

Settings_ContentTypeDefinitionRecord

Id     Name                        DisplayName              Hidden    Settings
50    KnowledgeTerm      Knowledge Term        0               <settings Taxonomy="Knowledge" />




Settings_ContentPartDefinitionRecord


Id     Name                        Hidden       Settings
69    KnowledgeTerm      0                 <settings ContentPartSettings.Attachable="True" />




The missing record that is causing the fields to not display on the content definition view is:

Settings_ContentTypePartDefinitionRecord

Id     Settings               ContentPartDefinitionRecord_id     ContentTypeDefinitionRecord_Id
95    <settings />         69                                                          50




----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




As for the duplicate content Type records, this is what I’ve found:

If you run the code example that you provided and then to create a field for the term programmatically use the following code:



ContentDefinitionManager.AlterPartDefinition(“KnowledgeTerm”, builder => builder


.Attachable()

.WithField(“MyField”, cfg => cfg


.OfType(“TextField”)

.WithDisplayName(“MyField”))

);



The resulting records are as follows:

Settings_ContentTypeDefinitionRecord

Id     Name                        DisplayName              Hidden    Settings
50    KnowledgeTerm      Knowledge Term        0               <settings Taxonomy="Knowledge" />

51    Knowledge2             Knowledge Term        0               <settings Taxonomy="Knowledge" />


Interestingly enough, I happened to find this morning that if the code is run in 2 steps as follows, the duplicate does not occur.


ContentDefinitionManager.AlterPartDefinition(“KnowledgeTerm”, builder => builder


.Attachable()

);


ContentDefinitionManager.AlterPartDefinition(“KnowledgeTerm”, builder => builder


.WithField(“MyField”, cfg => cfg


.OfType(“TextField”)

.WithDisplayName(“MyField”))

);



Sorry for being so long winded, but I’ve tried virtually all combinations in an attempt to find a solution. I hope that my findings will help you find a solution to my problem but also help with some the minor bugs I’ve discovered as well.




Thanks,



Juan 





From: Devqon
Sent: ‎Monday‎, ‎August‎ ‎3‎, ‎2015 ‎8‎:‎05‎ ‎AM
To: OrchardCMS/Orchard
Cc: Juan Quintana





I think you are missing a step. You didnt create the term content type for the taxonomy. This is how I've done it:
private const string c= "Knowledge";

private void EnsureKnowledgeTaxonomy() {

    var knowledgeTaxonomy = _taxonomyService.GetTaxonomyByName(KnowledgeTaxonomyName);
    if (knowledgeTaxonomy == null)
    {
        knowledgeTaxonomy = _contentManager.New("Taxonomy").As<TaxonomyPart>();
        knowledgeTaxonomy.Name = KnowledgeTaxonomyName;
        knowledgeTaxonomy.ContentItem.As<TitlePart>().Title = KnowledgeTaxonomyName;

        // See this following step:
        _taxonomyService.CreateTermContentType(knowledgeTaxonomy);
        // Now the term content type exists (and therefore also its part)

        _contentManager.Create(knowledgeTaxonomy);
        _contentManager.Publish(knowledgeTaxonomy.ContentItem);
    }
}

**Comment by Piedone** [comment]
Don't create taxonomies by hand, create then through TaxonomyService. That will do all the necessary setup. If the issue persists that way too please re-open.

**Comment by hec-adam** [comment]
The TaxonomyService does not expose a method for creating taxonomies, only terms.

Did the op get this working?

Also, Devqon's reply is obsolete because the TaxonomyPartHandler calls _taxonomyService.CreateTermContentType() in its OnPublished handler. That's why you are getting a duplicate content type.

@Piedone: Any clarification on the proper way to set up a taxonomy, add terms, and create a taxonomy field in a migration would be greatly appreciated.

**Comment by Piedone** [comment]
@hec-adam you're right, I'm sorry. Creating Taxonomies like this works on the almost latest source:

```
                if (taxonomyService.GetTaxonomyByName(name) == null)
                    contentManager.Create<TaxonomyPart>("Taxonomy", taxonomy => taxonomy.Name = name);
```

**Comment by juanfq** [comment]
Sorry to be a pain but my original problem has never been addressed. I never had a problem with creating a taxonomy (aside from the duplicate term record). The problem I need help with is in creating fields for the taxonomy term. 

The problem is not that the fields aren't being created in the database but that they do not display when you edit the content definition for the taxonomy term via the admin view or when adding terms to the taxonomy.

In my testing I discovered that a crucial record is not being added to the Settings_ContentTypePartDefinitionRecord table that links the term record in the Settings_ContentTypeDefinitionRecord table with the term record in the Settings_ContentPartDefinitionRecord table.
Once that record is added (I added the missing record manually), the fields display everywhere as they should.

Below is a test block of code to demonstrate what I am doing (I've incorporated the suggestion by @Piedone in creating the taxonomy). 

If my code for creating the fields is incorrect, I'd appreciate feedback on the proper method. Thanks.

```
            //Create the Knowledge taxonomy
            var name = "Knowledge";
            if (_taxonomyService.GetTaxonomyByName(name) == null)
                _orchardServices.ContentManager.Create<TaxonomyPart>("Taxonomy", taxonomy => taxonomy.Name = name);

            // Create the fields for KnowledgeTerm
            ContentDefinitionManager.AlterPartDefinition("KnowledgeTerm", builder => builder
                .Attachable()
                .WithField("KnowledgeField", cfg => cfg
                    .OfType("TextField")
                    .WithDisplayName("Knowledge Field"))
            );
 ```

**Comment by hec-adam** [comment]
Well I am not sure exactly what you are trying to do, but "KnowledgeTerm" is not a part, it is a type. You add fields to parts not types, and I don't think you want the field to be part of the KnowledgeTerm type anyway.

You probably want to create a part (e.g. KnowledgePart) add your field to that part, and then attach that part to whatever content type needs the field.

Here is an example:
```
            // Get or Create Taxonomy
            var name = "KnowledgeTypes";
            var taxonomy = _taxonomyService.GetTaxonomyByName(name);
            if (taxonomy == null) {
                taxonomy = _contentManager.Create<TaxonomyPart>("Taxonomy", t => t.Name = name);
                // This will have triggered the TermContentType "KnowledgeTypesTerm" to be created
            }

            // Define Part
            ContentDefinitionManager.AlterPartDefinition(typeof(YourPart).Name, part => part
                .WithField("KnowledgeType", field => field
                    .OfType("TaxonomyField") // This should be TaxonomyField not TextField
                    .WithDisplayName("Knowledge Type")
                    .WithSetting("TaxonomyFieldSettings.Taxonomy", taxonomy.Name)
            ));

            // Define Type
            ContentDefinitionManager.AlterTypeDefinition("YourType", type => type
                .DisplayedAs("Your Type")
                .WithPart(typeof(YourPart).Name)
                .Creatable()
            );
```

I hope that helps.

**Comment by juanfq** [comment]
I finally got it. I was hung up with the way Orchard creates the records when doing all this via the admin screen. When a user adds fields, a part is created behind the scenes with the same name as the type and then the part is associated to the type. I could have called the part anything I wanted rather than using the same name as the type...hence the confusion.

What I was missing was the following (which follows the 2 other chunks of code):
```
            // Associate the part to the type
            ContentDefinitionManager.AlterTypeDefinition("KnowledgeTerm", type => type
                .WithPart("KnowledgeTerm")
            );
``` 

Thanks for your help.
