### ISSUE TITLE
Can not publish 1.9.x to a local directory because of compiler error.  

### ISSUE THREAD

**Issue by rasseru08** [OrchardCMS/Orchard#5605]
I am trying to compile and publish the 1.9.x to a local directory from within VS2015.   However, when I attempt to publish the Orchard.Web to a local directory it fails.    

Steps
1.  Start VS2015 as Administrator. 
2.  Git Fetch from Official orchard source for 1.9.x  (no personally changes have been added yet)
3.  Right Click Orchard.Web to select Publish.  Specify a local directory.  
4.  Publish fails with following error.  

1>------ Publish started: Project: Orchard.Web, Configuration: Release Any CPU ------
1>Connecting to C:\Orchard...
1>Transformed Config\log4net.config using Config\log4net.Release.config into obj\Release\TransformWebConfig\transformed\Config\log4net.config.
1>Transformed Config\HostComponents.config using Config\HostComponents.Release.config into obj\Release\TransformWebConfig\transformed\Config\HostComponents.config.
1>Transformed Web.config using C:\Users\rrice\Documents\GitHubVisualStudio\Orchard\src\Orchard.Web\Web.Release.config into obj\Release\TransformWebConfig\transformed\Web.config.
1>Copying all files to temporary location below for package/publish:
1>obj\Release\AspnetCompileMerge\Source.
1>C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_compiler.exe -v /OrchardLocal -p C:\Users\rrice\Documents\GitHubVisualStudio\Orchard\src\Orchard.Web\obj\Release\AspnetCompileMerge\Source -u C:\Users\rrice\Documents\GitHubVisualStudio\Orchard\src\Orchard.Web\obj\Release\AspnetCompileMerge\TempBuildDir 
1>C:\Users\rrice\Documents\GitHubVisualStudio\Orchard\src\Orchard.Web\obj\Release\AspnetCompileMerge\Source\modules\orchard.dashboards\web.config(39,0): Error ASPCONFIG: Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified.
1>
========== Build: 0 succeeded, 0 failed, 80 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by thekaveman** [comment]
Have you tried doing a full rebuild of the solution, before trying the publish?

**Comment by rasseru08** [comment]
Yes, I have.   Everything complies correctly, but deployment fails as described above.

**Comment by sebastienros** [comment]
```
...
73>Publishing folder Themes/TheAdmin/Styles...
73>Publishing folder Themes/TheAdmin/Styles/images...
73>Publishing folder Themes/TheAdmin/Views...
73>Publishing folder Themes/TheThemeMachine...
73>Publishing folder Themes/TheThemeMachine/Styles...
73>Publishing folder Themes/TheThemeMachine/Views...
73>Web App was published successfully file:///c:/temp/testpublish
73>
========== Build: 72 succeeded, 0 failed, 8 up-to-date, 0 skipped ==========
========== Publish: 1 succeeded, 0 failed, 0 skipped ==========
```

Worked fine for me using 1.9.x, can you try with this branch?

**Comment by dcinzona** [comment]
Disable the option to Pre-Compile on publish - see here: https://github.com/OrchardCMS/Orchard/issues/5484

**Comment by rasseru08** [comment]
@dcinzona,  Thank you.   Once I unchecked the "Precompile during Publication" I was able to publish the website.    I do not understand why it does not work with it turn on but that is for another day.

**Comment by dcinzona** [comment]
Excellent, yeah - I'm not sure about why that breaks it but glad it's fixed for you!
