### ISSUE TITLE
Unable to translate content

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/Orchard#5616]
branch: 1.9.x
When trying to translate a content, I can't select translation localization.
Localization is forced to original's one.

Issue introduced by fa09e2e83a95d99eafb5afaf557eab3f74e86e9f.

**Comment by TFleury** [comment]
PR #5629 proposed.

**Comment by TFleury** [comment]
@sebastienros can you add this issue to 1.9.2 milestone.

**Comment by sebastienros** [comment]
See https://github.com/OrchardCMS/Orchard/issues/5535 for initial issue to fix
