### ISSUE TITLE
After upgrade to 1.9.1 - taxonomy in autoroute needs to be saved twice

### ISSUE THREAD

**Issue by Habbni** [OrchardCMS/Orchard#5618]
Hi,

when I try to get a route to include a taxonomy path, I have to save the content item twice.
It seems like the new data does not get populated early enough, so the token can not resolve it..

I have installed a fresh 1.9 installation and everything works as expected.
In a fresh 1.9.1 installation however, the issue is easily reproducable:

- create new taxonomy "TaxTest"
- add a new term "Term1" and another term "Term2" as a child
- create a new part "TestPart" and add taxonomy field "TaxSelection"
- create a new content type "TestType". Add AutoRoute, Title and TestPart
- set "TaxTest" as taxonomy for the TestPart. Check "required" and restrict selection to only one term
- set the route pattern to "{Content.Fields.TestPart.TaxSelection.Terms:0.Path}/{Content.Slug}"
- activate auto-regeneration

Now create a new TestType content. Select "Term2" and set the title to "Test".
Hit Save or publish. The alias now is "/test", while It should be "/term1/term2/test".
Hit Save or publish again, the alias now is correct.

Thanks for your time!

**Comment by Habbni** [comment]
Figured out that reverting https://github.com/OrchardCMS/Orchard/commit/0c7b52e1be2011de4d81f55b40dd33310e88e669 fixes the issue for me

**Comment by mjy78** [comment]
Noticed the same problem. Also noted that reverting the https://github.com/OrchardCMS/Orchard/commit/0c7b52e1be2011de4d81f55b40dd33310e88e669 fixes the issue.

**Comment by jchenga** [comment]
Backing out 0c7b52e1be2011de4d81f55b40dd33310e88e669 works because field.Terms is not called too early in the process. 

The Terms property in TaxonomyField returns a collection by calling TermsField.Value which holds and always returns a reference to the loaded collection.

Calling field.Terms during view model initialization creates a collection of zero elements because no terms have been added to the field yet. When autoroute accesses field.Terms to generate an alias, that stale collection is returned instead of a collection with the added terms. Since there are no taxonomy terms, autoroute does not generate an alias with taxonomy terms.

**Comment by thekaveman** [comment]
So I think we can agree that the fix from [`0c7b52e`](0c7b52e) addresses an important issue. 

In looking at the two related issues that were the genesis of this fix (#4194 and #4671) there is a distinct difference: ContentPicker and MediaLibraryPicker use an underlying `Lazy*` to materialize the complete objects being "picked"; however they are also storing the raw ids of the "picked" objects directly in the Infoset. It is this raw data that is being accessed and used in the respective `Editor` functions to (re)initialize view models.

Could a similar approach work for TaxonomyField? In addition to the `LazyField<IEnumerable<TermPart>>` for materializing the complete objects, could we make use of a `public int[] Ids` property (or similar) for the purposes of view model (re)initialization?

**Comment by jchenga** [comment]
I've created a PR for this issue. The fix borrowed the codes from the other Editor method to load the selected terms from the db. the autoroute issue is fixed, but I didn't test with editor groups as I don't know how to set it up.

**Comment by jchenga** [comment]
I believe the fix should also work with editor group scenario because it is getting all selected terms for all taxonomy fields.
