### ISSUE TITLE
Retry logic and transient fault handling for Azure SQL

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5653]
We are using Orchard 1.9.1 running on Azure Web Apps with an Azure SQL DB backend in an elastic pool.  At least 4 or 5 times a week, we drop connectivity to the Azure SQL database, causing catastrophic failure of the web application.  My guess is that the Orchard NHibernate data provider for Azure SQL is using an old model and is has not been updated.

Here is the line that stands out to me: https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Data/Providers/SqlServerDataServicesProvider.cs#L30

I also looked through the lib directory and was unable to find NHibernate.SqlAzure: https://github.com/MRCollective/NHibernate.SqlAzure

Do we need to include the NHibernate.SqlAzure library in the lib folder (considering that there is an automated deployment option for Azure now) and does the data services provider need to be modified to support the new library?

**Comment by CSurieux** [comment]
This has been removed when orchard upgraded the ado.net sql driver which now manage directly retry, their are new keywords for this to add in the connection string, see the ado.Net fm :)
https://msdn.microsoft.com/en-us/library/ex6y04yf(v=vs.110).aspx

**Comment by dcinzona** [comment]
Are you referring to the Connection Timeout property?  Because we have had that in our connection string for about a year - it doesn't not maintain the connection.  If there's a different property that we should include (I looked at the link you sent briefly but didn't see anything that stood out), can you post it here?

**Comment by CSurieux** [comment]
"The ConnectRetryCount and ConnectRetryInterval connection string keywords (ConnectionString) let you control the idle connection resiliency feature."

**Comment by dcinzona** [comment]
Hmm... I see that now... the retry interval is not exponential?  i.e. retry count = 5, retry interval  = 10 (it will try 5 times at 10 second intervals)?  I guess I could set it to retry count 30, interval 3.... any best practices here for azure?

**Comment by dcinzona** [comment]
Heh, already had those in the connection string, but it was max 15 second (3 retry at 5 seconds).  The reconfigs can last up to 50 seconds... so I will adjust and report back!

**Comment by CSurieux** [comment]
from my experience no special case with sql Azure, from azure or not. Curiously it works perfectly without NH, simply ADO.NET but within Orchard still pbs from time to time when running background tasks.

**Comment by dcinzona** [comment]
Ok, I've updated the connection strings in QA and restarted the application... I'll wait until tomorrow AM to restart production.

**Comment by dcinzona** [comment]
Haven't received any ysod's yet.  Closing this for now.

**Comment by Piedone** [comment]
@dcinzona what exactly is the config that you're using? All connection-related errors went away?

**Comment by dcinzona** [comment]
We still get timeout errors but we haven't gotten any YSODs in the last few days.
Our connection string includes the usual DB stuff, with the following specific to our Azure SQL DB:
`Trusted_Connection=False;Encrypt=True;Connection Timeout=30;MultipleActiveResultSets=True;ConnectRetryCount=15;ConnectRetryInterval=5;Max Pool Size=1000;`

My guess is that the timeout errors are reported during the retries, but eventually, connectivity is restored and the application doesn't crash.  In the last 2 days, we've only logged 98 errors (compared to the last 7 days of 20,877).  The majority of those are logged when total loss of connectivity to SQL Azure occurs.

**Comment by dcinzona** [comment]
I may even try to raise the connection timeout to 60, even though MS originally recommended 30.

**Comment by dcinzona** [comment]
We also have not logged (in the last 2 days) any 
`Database 'dbname' on server 'servername' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of ...` errors

**Comment by Piedone** [comment]
Thanks. Is MARS also something you definitely know is beneficial on SQL Azure? FYI the timeout is 30s by default so you don't have to set it.

**Comment by dcinzona** [comment]
Yes, MARS was actually recommended by MS support when we were early in development with 1.8.x - haven't had a need to remove it so not sure if it is still helping or just a fragment from an earlier time.

**Comment by Piedone** [comment]
Cool, thanks.

**Comment by dcinzona** [comment]
:+1:

**Comment by sebastienros** [comment]
You are mentioning background tasks, are you using the 1.9.x branch where
the sessions management was fixed? If not, then we'll probably release
1.9.2 this next week so it might be interesting to see the difference.

**Comment by dcinzona** [comment]
@sebastienros are you referring to this issue: https://github.com/OrchardCMS/Orchard/issues/5480 
We are using 1.9.1. So if this is, indeed, due to the sessions management bug it should resolve it.
