### ISSUE TITLE
Best Way To Simulate Tree Structure

### ISSUE THREAD

**Issue by Skelet0r67** [OrchardCMS/Orchard#5654]
Hello,

I have multiple pages on a site that have their own subnav embedded into the content on the page, and when clicking on that subnav, you are then presented with another navigation. When clicked, each nav item changes the content on the page, and could possibly be a page by itself. I've been thinking about what would be the best way to represent this in the CMS. 

Here are the options I've come up with:
1. The first thing I thought about doing is using the depreciated list module. This would make it extremely easy to create a standard template for each page with this structure. I could simply nest the pages and when the shape is rendering get all the children of each page to build the navigation as well as the content.
2. Create menus for each page's sub nav, this way we could still set an association between the nav items and the content. 
3. Use a series of widgets. Not really too fond of this way, considering the navigation and the content won't be linked and I would have to create widgets for each individual page. 

The point is, aside from using the depreciated lists module, I'm not quite sure how to do this. Has anyone encountered this type of scenario before? If so any guidance on how you tackled it would be extremely helpful.

**Comment by sfmskywalker** [comment]
The Lists module had been "un-deprecated" and refurbished so if that module solves your issue then definitely use that one.

I think this is more of a question than an issue, so I'm closing it here. Please feel free however to open a discussion on CodePlex if you want to discuss this further.
