### ISSUE TITLE
SysCache really should not be a feature

### ISSUE THREAD

**Issue by DanielStolt** [OrchardCMS/Orchard#5657]
If any NHibernate 2nd level cache provider is activated, it gets activated for the whole AppDomain, never per tenant. Having `SysCache` as a feature is therefore a source of confusion. As a site admin, you will likely think you turn it on for a tenant, but really as soon as you turn it off for **any** tenant it's on for all of them.

Having it as a feature also makes it harder to manage, because to turn it off you have to:

1. Disable it for **all** tenants on your site
2. Restart the application pool

I therefore propose that we remove the `SysCache` feature completely in `dev` and instead configure/activate any NHibernate 2nd level cache providers using `Host.config`.

The default implementation of `IDatabaseCacheConfiguration` does not enable any caching, which should still be the default configuration. If you want to enable the `SysCache` implementation you would do something like this:

    <autofac defaultAssembly="Orchard.Framework">
        <components>
            <component instance-scope="single-instance" type="SysCache.Services.SysCacheDatabaseCacheConfiguration, SysCache" service="Orchard.Data.IDatabaseCacheConfiguration"></component>
    </autofac>

And to enable the `Orchard.Azure` implementation you would do:

    <autofac defaultAssembly="Orchard.Framework">
        <components>
            <component instance-scope="single-instance" type="Orchard.Azure.Services.Caching.Databae.AzureCacheConfiguration, Orchard.Azure" service="Orchard.Data.IDatabaseCacheConfiguration"></component>
    </autofac>

We could have both these configurations as commented-out examples in `Host.config`.

**Comment by paynecrl97** [comment]
I agree. This has caused issues for us where we have a multi tenant environment and have needed to switch db cache providers.

It's also misleading to see in the UI that the state of these feature may not necessarily reflect the cache provider being used.

**Comment by PaulDevenney** [comment]
+1, that or fix NHibernate to support a scheme that would allow true per tenant implementations

**Comment by CSurieux** [comment]
May be some feature should be tagged in their module.txt as non tenant aware or site-wide.

**Comment by PaulDevenney** [comment]
@CSurieux A site is a tenant, and features are enabled per tenant, by commands that specify their tenant. If you had an administrator of Site A, would you be happy for him to be able to turn on the feature on Site B?

**Comment by CSurieux** [comment]
You missed my point Paul, I just say that some features are nice to have for those not using the multitenant armada. But if those features are not friendly with MT it should be clearly mentioned to warn the admins.

**Comment by DanielStolt** [comment]
After some testing I'm no longer convinced this is an issue - it seems SysCache is indeed only enabled per tenant. I will investigate more and reopen if I can reproduce.
