### ISSUE TITLE
Shape Tracing Module doesn't work

### ISSUE THREAD

**Issue by AlexanderStasyuk** [OrchardCMS/Orchard#5661]
When turning shape tracing module on errors come up.  This happens on a fresh install.

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.
OrchardCMS\Orchard-dev\Orchard-dev\src\Orchard\DisplayManagement\Implementation\DefaultShapeFactory.cs    Line: 90

**Comment by Piedone** [comment]
Duplicate of #5647.
