### ISSUE TITLE
Can't setup a new instance of OrchardCMS without PathTooLongException

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5669]
I've cloned the repo using GitExt as suggested in the setting up a source enlistment documentation.

When I open the solution in Visual Studio Community 2015, run it with F5 and attempt to go though the initial setup screen an exception is thrown from `ViewsBackgroundCompilation.cs` in `GetViewDirectories()`.

It tries to dig deep into the `node_modules` folders and eventually gets stuck on this folder:

    "~/Modules/Orchard.DynamicForms/node_modules/gulp-minify-css/node_modules/gulp-util/node_modules/dateformat/node_modules/meow/node_modules/indent-string/node_modules/repeating/node_modules/is-finite/node_modules/number-is-nan/"

I don't think that the code should be going through the `node_modules` folders at all looking for views so I think the code needs to be changed somewhere to skip these folders.

It looks like the offending code that triggers this cascade is in `ViewsBackgroundCompilation.cs` `CompileViews()`. On lines 89/90 it does this:

    // Leave these at end (as a best effort)
    "~/Core", "~/Modules", "~/Themes"

Which sends it off into a spiral of doom.

**Comment by rtpHarry** [comment]
I updated the method to abort that directory if the path contains node_modules and it worked for me.

        private static void GetViewDirectories(IVirtualPathProvider vpp, string directory, IEnumerable<string> extensions, ICollection<string> files) {
			if (directory.Contains("node_modules"))
			{
				return;
			}

            if (vpp.ListFiles(directory).Where(f => extensions.Any(e => f.EndsWith(e, StringComparison.OrdinalIgnoreCase))).Any()) {
                files.Add(directory);
            }

            foreach (var childDirectory in vpp.ListDirectories(directory).OrderBy(d => d, StringComparer.OrdinalIgnoreCase)) {
                GetViewDirectories(vpp, childDirectory, extensions, files);
            }
        }

Can anyone see any knock on effects that this might cause?

**Comment by dcinzona** [comment]
You need to delete the node_modules folder completely, remove packages.json and gulpfile.js.
1.9.x has been updated to reintroduce gulp in a non-breaking manner in VS 2015.

**Comment by dcinzona** [comment]
See commit: https://github.com/OrchardCMS/Orchard/commit/6da6c5c214a40d71c2c714a0d0ba8e6aa018120a

**Comment by Piedone** [comment]
So you say this is not an issue any more?

**Comment by dcinzona** [comment]
This was fixed by @DanielStolt in that commit.  It's still a very real issue in the current 1.9.1 release

**Comment by rtpHarry** [comment]
Thanks, I did do a search in issues for `PathTooLongException` which returned 0 results but I now see this was reported in #5446.

I think it's safe to close this issue.

**Comment by rtpHarry** [comment]
I just got around to publishing the site in question today and hit a bunch of errors with the Publish / Deploy feature of Visual Studio.

I'm just posting this here in case anyone else hits the same errors. You need to use 7-zip to delete the files. 

Open up 7-zip on its own then navigate to the offending `node_module` folders and press `shift-del` to force it to do a straight delete. A normal delete will fail even though it says it will force delete files because they are too long for the recycle bin. `Shift-del` will do the trick.

After deleting the files mentioned by dcinzona the package created without an issue:

    ./Orchard.Web/Modules/Orchard.DynamicForms
    ./Orchard.Web/Modules/Orchard.Layouts
    ./Orchard.Web/Modules/Orchard.Azure.MediaServices

Delete any of these that you find in this location:

    gulpfile.js
    package.json
    node_modules
