### ISSUE TITLE
Add SSL for http://www.orchardproject.net/advisory

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5673]
If running Orchard CMS over HTTPS (which, IMO, is the recommended way to run it), the default advisory should pull from HTTPS.  Browsers will otherwise block unsecured content and users with access to the dashboard will fail to see any advisory messages.

**Comment by rtpHarry** [comment]
This is a dupe of #2792

**Comment by dcinzona** [comment]
Yup, thanks - closing
