### ISSUE TITLE
Error in TinyMCE

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/Orchard#5679]
When I save the following code
```
<ul>
    <li>
        <a href="">
            <img title="" alt="" src="sp2.jpg">
            <div>
                <h4></h4>
                <img src="">
                <span></span>
            </div>
        </a>
    </li>
</ul>
```
After being saved, the following code gets converted
```
<ul>
    <li>
        <a href="">
            <img title="" alt="" src="sp2.jpg">
        </a>
        <div>
            <h4></h4>
            <img src="">
            <span></span>
        </div>
    </li>
</ul>
```

**Comment by sfmskywalker** [comment]
Looks like TinyMce wants to help preventing you from doing something wrong (http://stackoverflow.com/questions/1827965/is-putting-a-div-inside-an-anchor-ever-correct#) - although some say that in HTML 5 you should be allowed to put block level elements in anchors. To be googled some more.

**Comment by asemandeveloper** [comment]
Please upgrade to 4.2.4 Tinymce version
