### ISSUE TITLE
ContentManager.Destroy doesn't remove registered Alias

### ISSUE THREAD

**Issue by hannan-azam** [OrchardCMS/Orchard#5689]
The new Destroy method in ContentManager of Orchard 1.9 doesn't remove the associated Aliases.
Once the content item is destroyed, the Aliases become a ghost entry and cannot be deleted even through the Alias UI utility.

This will probably have to be hooked for Destroying/Destroyed of AutoroutePart just like the way it is currently done for Removing/Removed.

**Comment by JingyuShao** [comment]
I met the same issue. Once deleted an alias from one browser, the alias showed up again in another browser. And cannot be deleted anymore, eventhough the UI is telling you it has been deleted. I checked the Alias_AliasRecord database table, it is for sure deleted.

**Comment by hannan-azam** [comment]
Resolved in PR https://github.com/OrchardCMS/Orchard/pull/6296
