### ISSUE TITLE
Orchard.DynamicForms - Check Box Field Uses "Mandatory" Instead Of "Required"

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5708]
v1.9.1

In all other elements I've used so far the Validation tab has a "Required" checkbox.

The Check Box element uses the word "Mandatory" instead.

**Comment by sfmskywalker** [comment]
The checkbox uses a different client side validator ("mandatory") than the textfields ("required"), but I agree it would be better to keep the same name on the UI layer, since there's no functional difference as far as the user is concerned.
