### ISSUE TITLE
Orchard 1.9x Exceptions because it tries to compile modules not in solution under VS2015

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#5709]
When there are module source code not in solution but in the Module folder and I press F5 under VS2015, the DefaultExtensionCompiler class generates Exceptions because it tries to compile the not in solution modules and fails.
Previously I was able to do this without those errors.
All the Orchard code come from a fresh clone from 1.9x

**Comment by sebastienros** [comment]
This is by design since Orchard 0.5. You can disable dynamic compilation in the config folder.

**Comment by CSurieux** [comment]
OK this is some kind of logic. It is convenient when running on site, but it could appear very strange and disappointing when we run it through the Visual Studio Debugger to have Orchard trying to use modules not in the solution.
