### ISSUE TITLE
Convention for Modules using Angularjs

### ISSUE THREAD

**Issue by davegardner** [OrchardCMS/Orchard#5722]
Angularjs uses an 'auto-bootstrapping' directive `ng-app` to automatically kick off. The Orchard.Layouts module uses this mechanism. The problem for any other module that wants to use Angularjs is that there can only be ONE `ng-app` directive on an html page. So the issue is, How can other modules (besides Orchard.Layouts) use Angularjs?

Obviously, this only becomes a problem when two part editors using Angularjs are combined on a single content type.

Angular does permit more than one 'module' per page, but you need to use manual bootstrapping. Also, there are problems with including additional modules and getting them initialized thru Angular's Dependancy Injector.

**Comment by Devqon** [comment]
+1, I too struggle with the correct implementation of angular components. Currently I use the ng-app directive on the html tag in Layout, but there must be a better solution.

**Comment by DanielStolt** [comment]
@davegardner @Devqon 

This has now been fixed for the 1.10 release by manually bootstrapping using the `angular.bootstrap()` function.

Thanks for raising this issue, and sorry it took so long to get around to making this simple change.
