### ISSUE TITLE
Dynamic forms not staying on same page after submission

### ISSUE THREAD

**Issue by markstevens10** [OrchardCMS/Orchard#5724]
I've left the redirect URL blank for each of my dynamic forms, and made sure that the workflows do not contain a redirect on form submission. However on form submission the user is redirected to the homepage with the Show Notification message appearing there. I expected that the same page (containing the form) would reload with the Show Notification message appearing.

**Comment by Piedone** [comment]
You can work around this by using the Request token in the redirect URL field.

**Comment by remesq** [comment]
Is this similar to the behavior I raised an issue about here https://github.com/OrchardCMS/Orchard/issues/5765?

**Comment by sebastienros** [comment]
Should be fixed with #5765 in 1.9.2
