### ISSUE TITLE
Customizing TinyMce for inline editing

### ISSUE THREAD

**Issue by armanforghani** [OrchardCMS/Orchard#5725]
I want to customize TinyMce for inline editing but it seems the configuration is hard code in Angular module. How can i override the configuration?

Also TinyMce in Inline editing mode has incorrect style or bad configuration. It has fixed size so it is not responsive (At lease in RTL languages).

Also dialog mode uses iframe so does not load theme style sheets, fonts, etc. This causes several problems. Dialog has not full screen mode and if you click full screen button of TinyMce it will be maximized in its iframe instead of full screen.

**Comment by sebastienros** [comment]
Duplicate, there is an ongoing PR on improving TinyMCE configuration.
Also, we removed Edit inline form the Layouts module.
