### ISSUE TITLE
Command-Line Scaffolding for Unit Test Projects

### ISSUE THREAD

**Issue by SantoDE** [OrchardCMS/Orchard#5727]
Hey there,

what do you guys think about a command line scaffolding option to create Unit Test Projects for our own modules?

I'm currently trying to create such a module on my own and therefore I ended up "missing" such a feature.

Cheers,
SantoDE

**Comment by rtpHarry** [comment]
I didn't realise this when you brought it up but I've just noticed that there is actually a command in Orchard.exe for creating a module test project.

It was added in https://github.com/OrchardCMS/Orchard/commit/4ce3ee32267224a126c149dbcb61d06b08784e0f

You can use it by going to your `Orchard.Web\Bin` folder, running `orchard.exe` and then using this command:

    codegen moduletests <module-name> [/IncludeInSolution:true|false]

**Comment by Piedone** [comment]
You don't need anything more by default in a test project as the next step is writing the tests: there is no one size fits all module-level code generation solution here. And actually adding the right references is the trickiest part, trust me.

Closing as already implemented. But if you'd like to add a note about this to the Docs everybody would be very grateful :-).
