### ISSUE TITLE
Random 404 with Azure Web App tenant and SQL CE

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#5732]
I'm testing a configuration and am seeing some anomalies.  We have our root orchard website running off of **Azure SQL Server** on **Azure Web Apps** with no issues.  When I create a new tenant and set the database to use SQL CE, the tenant is created successfully and setup completes with the recipe selected.  Then it gets weird.  

After setup is complete, I can go to the tenant and access the site, but sometimes (I would say 50/50), the page loaded will respond with a 404 from the root application, like it can't find the tenant.  No errors are logged.  I can sit there and just hit the refresh button, sometimes I'll get a 404 and sometimes the tenant page will load.

This is using Orchard 1.9.1.  
Is this configuration even supported?  Azure Web Apps used shared file storage, so multiple farm instances have access to the same files... My guess is that there's some kind of access lock on the SQL CE database file...

**Comment by sfmskywalker** [comment]
Anything in the error logs that would indicate database access issues? Or maybe Azure is experiencing some issues? Are you seeing the same with a regular MVC application that does nothing special?

**Comment by dcinzona** [comment]
Nothing in the logs regarding any errors.  I don't have another MVC application to test.  It's so bizarre.  Like the root application doesn't see that the tenant exists sometimes.

**Comment by sebastienros** [comment]
It might be because different nodes are hit and the tenant is unknown from the other one. After a restart, if it disappears then this is the reason. Also SqlCe is not supported in a multi-server instance, as it doesn't support multiple writers on the same db.

**Comment by dcinzona** [comment]
Looks like that is the issue. 
```
System.Data.SqlServerCe.SqlCeException (0x80004005): There is a file sharing violation. A different process might be using the file. [ D:\home\site\wwwroot\App_Data\Sites\TestTenant\Orchard.sdf ]
   at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   at System.Data.SqlServerCe.SqlCeConnection.Open()
   at NHibernate.Connection.DriverConnectionProvider.GetConnection()
   at NHibernate.AdoNet.ConnectionManager.GetConnection()
   at NHibernate.Impl.SessionImpl.get_Connection()
   at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel)
```
