### ISSUE TITLE
Orchard.DynamicForms - Potential DefaultFormLayoutData Migration Bug About To Sneak Through

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5733]
The configuration of Orchard.DynamicForms\Migrations.cs has changed but the migration is still on v1.

In the v1.9.1 tag the default layout is defined like this:

                    "{" +
                        "\"elements\": [{" +
                            "\"typeName\": \"Orchard.DynamicForms.Elements.Form\"," +
                            "\"elements\": [{" +
                                "\"typeName\": \"Orchard.DynamicForms.Elements.Button\"," +
                                "\"state\": \"ButtonText=Submit\"" +
                            "}]" +
                        "}]" +
                    "}"

In the 1.9.x branch which as I understand it, is about to become v1.9.2 the migration is now:

		@"{
			""elements"": [
				{
					""typeName"": ""Orchard.Layouts.Elements.Canvas"",
					""elements"": [
						{
							""typeName"": ""Orchard.DynamicForms.Elements.Form"",
							""data"": ""FormName=Untitled&amp;FormAction=&amp;FormMethod=POST&amp;FormBindingContentType=&amp;Publication=Draft&amp;Notification=&amp;RedirectUrl="",
							""elements"": [
								{
									""typeName"": ""Orchard.DynamicForms.Elements.Button"",
									""data"": ""InputName=&amp;FormBindingContentType=&amp;Text=Submit""
								}
							]
						}
					]
				}
			]
		}";

However both of them still consider themselves to be the Create() with no UpdateFromX() method to transition.

I have pulled the 1.9.x branch over a copy of 1.9.1 to work around some other bugs and for me, I do not get any default content when I try to make a new dynamic form.

If I pull a fresh copy of 1.9.x and try then it does work with the default content of a form + button.

**Comment by sebastienros** [comment]
This code is just meant to initialize the new deployments. Updating existing deployments with it could break the websites. Thanks.

**Comment by sebastienros** [comment]
We need an UpdateFrom1() which will overwrite it if the string is the previous one. We can check the value with a hash if we don't want to keep the old code for ever.
