### ISSUE TITLE
Orchard.DynamicForms - Form element doesn't support Enter keyboard shortcut

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5749]
1.9.x / Chrome / Win 8.1

When I have the Form element selected, I cant use the `enter` keyboard shortcut to open up its `Edit form` dialog.

![image](https://cloud.githubusercontent.com/assets/1038062/9682597/00c83504-5300-11e5-9c66-3e4f1fafe33a.png)

**Comment by sebastienros** [comment]
Assigned it to @DanielStolt because is asking for stuff to do.
