### ISSUE TITLE
Orchard.Layouts - Edit HTML content inline doesn't work?

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5751]
1.9.x / Chrome / win 8.1

No matter what install I've tried this on the `Edit HTML content inline` doesn't work.

Before:

![image](https://cloud.githubusercontent.com/assets/1038062/9682771/afc21c22-5301-11e5-8492-7d3049c207c5.png)

After:

![image](https://cloud.githubusercontent.com/assets/1038062/9682773/b7bd7246-5301-11e5-817a-26d3487f6049.png)

It bumps the layout area down, hides the element groups down the right but doesn't give me any edit functionality.

I've tried it on fresh forms, existing sites, fresh pages, all sorts. I kept putting off reporting it because I was working with upgraded installs and wasn't sure if it was a "pure" bug but this is a fresh copy of 1.9.x and its still doing it.

**Comment by sebastienros** [comment]
A simple fix is to remove the feature ... /cc @sfmskywalker

**Comment by rtpHarry** [comment]
One of the reasons I was holding off reporting this was because I was sure I had seen this feature work at some point.

I've just figured out where. If you go to the Layouts menu item in the admin sidebar then tick this box the editor does appear and it seems to work pretty well.

The feature fails when it is attached to a ContentType.

There are a couple of other glitches that I will report as separate items.

**Comment by rtpHarry** [comment]
Ok I have finally figured out what I'm experiencing!

If a Layout doesn't have a `HTML content` element in it then the rich text editor fails to display. It just bumps it down like the first screenshots in this issue.

If a Layout does have a `HTML content` element then the feature works everywhere, attached as a Content Type and standing on its own in the Layouts editor.

So it seems that the feature is only intended for the HTML elements and literally means `Edit HTML elements inline`.

As I said in #5793 I find this confusing. I originally thought it was a way to look under the hood and edit the raw html of that layout. It raises two questions for me:

  1. Is there a reason why you can't edit other content elements in this mode?
  1. Is there a reason why you need this mode, can't the edit content be built in to the builder side of things?

**Comment by DanielStolt** [comment]
I built this feature as sort of an experiment, basically because I could. :) It seemed like it would be a cool more "wysiwyg" way of editing a page.

It's very of hackish in that it works only for HTML elements, assumes there actually is at least one of those in the layout, and has built-in hard-coded knowledge of a specific type of element.

I would not be extremely sad if this feature was removed. With the current architecture of the client-side editor it's basically not possible to build such a feature in a cleanly separated way. That's one of the drivers behind our Ayos project, which aims to rebuild this whole client-side editor from scratch with a much more robust and cleanly designed architecture, and as a library that can be reused anywhere, not just in Orchard.

**Comment by rtpHarry** [comment]
Ok cool, I haven't heard of the Ayos project until now. I think that could be really popular of you open it up to other CMS as a generalised library!

I guess the resolution of this ticket then is as @sebastienros suggested to hide/remove the checkbox.

If that's what is decided it would close the other two issues as well #5794, #5793

**Comment by Jetski5822** [comment]
Ayos?

**Comment by rtpHarry** [comment]
https://github.com/IDeliverable/Ayos

**Comment by DanielStolt** [comment]
And boom, I guess the genie is out of the bottle.. :) Let me just clarify that Ayos is still only in the design stage, and the code in that repo is only a skeleton, nothing that can actually be run or used. I'll try to put some documentation up in the repo soon to explain things.

**Comment by DanielStolt** [comment]
I've added some information to the project page now.
https://github.com/IDeliverable/Ayos

**Comment by rtpHarry** [comment]
Interesting read. I really like the concept and I'm excited to build elements because they are so client friendly. It will be good when you've got it to a usable state.
