### ISSUE TITLE
Don't work OnIndexing in Orchard CMS 1.9.x

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/Orchard#5755]
after upgrading to 1.9, in this code. OnIndexing don't work!
```
        public MovieHandler(IRepository<MoviePartRecord> moviePartRepository,
            IContentManager contentManager,
            IIndexManager indexManager) {
            _contentManager = contentManager;
            _indexManager = indexManager;
            Filters.Add(StorageFilter.For(moviePartRepository));

            OnIndexing<MoviePart>((context, part) => {
                foreach (var keyword in part.Keywords.Split(',').Select(k => k.Trim())) {
                    context.DocumentIndex.Add("movie-keywords", keyword).Analyze();
                }
            });
        }
```

**Comment by sfmskywalker** [comment]
Can you please clarify what you mean by that exactly? for example, are you seeing an error, or is the code not executed? If so, how can you tell? Anything in the error logs?

**Comment by asemandeveloper** [comment]
Pluralsight.Movies  module in orchard cms version 1.7 runs well. But in version 1.9 will not run and can not find Similar Movies, but OnIndexing don't work!

**Comment by sebastienros** [comment]
> don't work

This is not describing what your issue is. We could assume that the event is not called, or that the event is called but the code not working, or that the code is working but some other element is broken ... Please be explicit about "don't work". What do you expect and what actually happens.
