### ISSUE TITLE
Suggestion for new event Orchard.Roles.Events.IRoleEventHandler.PermissionsChanged()

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [OrchardCMS/Orchard#5757]
Hi there,

i trying to create a handler that implements `Orchard.Roles.Events.IRoleEventHandler` to do some stuff when a change in the role permissions occure. The issue here is that the permissions list is cleared before `PermissionAdded()` and `PermissionRemoved()` is called but i need a complete list of permissions to execute my code. Therefore i suggest adding an additional event named `PermissionsChanged()`:

Current source:

    roleRecord.RolesPermissions.Clear();

    foreach (var rolePermission in rolePermissions) {
      ...
      
    foreach (var rolePermission in rolePermissions) {
      ...
      
        if(!currentPermissions.ContainsKey(permission))
            _roleEventHandlers.PermissionAdded(new PermissionAddedContext { Role = roleRecord, Permission = permissionRecord });
        else
          ...
    }

    foreach(var permission in currentPermissions.Values)
        _roleEventHandlers.PermissionRemoved(new PermissionRemovedContext { Role = roleRecord, Permission = permission.Permission });      
    
    ...

Source after adding the new event `PermissionsChanged()`:

    roleRecord.RolesPermissions.Clear();

    bool permissionsChanged = false;

    foreach (var rolePermission in rolePermissions) {
        ...

        if(!currentPermissions.ContainsKey(permission)) {
            _roleEventHandlers.PermissionAdded(new PermissionAddedContext { Role = roleRecord, Permission = permissionRecord });

            permissionsChanged = true;
        }
        else
            ...
    }

    if (currentPermissions.Values.Count > 0) {
        foreach(var permission in currentPermissions.Values)
            _roleEventHandlers.PermissionRemoved(new PermissionRemovedContext { Role = roleRecord, Permission = permission.Permission });

        permissionsChanged = true;
    }

    if (permissionsChanged)
        _roleEventHandlers.PermissionsChanged(new RoleContext {Role = roleRecord});
        
    ...

I would be nice to see that change in the next Orchard release.

So lonG

**Comment by sebastienros** [comment]
I think the current implementation should be fixed instead of adding a new event.

c.f. https://github.com/OrchardCMS/Orchard/issues/5776
