### ISSUE TITLE
Configurable recipe execution timeout

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#5758]
Currently, the `SetupController` and the `ExecuteRecipeAction` set `HttpContext.Server.ScriptTimeout` to a hardcoded value of `600` seconds. In some scenarios it is desirable to change this value without changing the source code.

`HostComponents.config` could be used for this to configure a public property on said types. The default would set from both controllers to `600` seconds.

**Comment by Piedone** [comment]
Just to add: before anybody suggests this idea being able to set this by the user (like from the recipe itself), that shouldn't be allowed since changing execution timeout is a security sensitive operation.

**Comment by sfmskywalker** [comment]
In your opinions, should we add an entry to HostComponents.config for both the `SetupController` and the `ExecuteRecipeAction` separately, or should we add some sort of shared class that provides the ExecutionTimeout Setting?

**Comment by sfmskywalker** [comment]
For some reason the property value won't be injected into the controller. That, and the fact that we need the same value for two classes makes me consider adding a `ScriptTimeout` property to `IMachineNameProvider` and rename that to `IApplicationEnvironment` (or `IEnvironmentAccessor`). Unless someone stops me with a better idea?

**Comment by sfmskywalker** [comment]
I created a PR here so we can discuss the details: https://github.com/OrchardCMS/Orchard/pull/5813

**Comment by PaulDevenney** [comment]
I'd suggest putting this in web.config - it's not something you often want to change - but (for example) we really need to currently. I'm about to raise another issue for the performance of recipes, but summary is 1500 items takes about 22mins on Azure VMs....

**Comment by DanielStolt** [comment]
Correct me if I'm wrong, but hasn't this one already been merged into dev?

**Comment by sebastienros** [comment]
HostComponent.config
