### ISSUE TITLE
How to create a database connection and crud-solution using business objects(dll) in asp.net orchard cms

### ISSUE THREAD

**Issue by afsalg2t** [OrchardCMS/Orchard#5760]
I am new to <b>asp.net orchard CMS</b> .I need to create <b>database</b> connection using <b>business object(dll)</b> and a <b>crud solution using orchard CMS</b> </br>                                          View part and model part I already have.

**Comment by bleroy** [comment]
Hi, and welcome. Questions should be asked on the forums, rather than in the bug database: http://orchard.codeplex.com/discussions
