### ISSUE TITLE
Cannot Clone Content Item with Multiple Identity Providers - Fix Included

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/Orchard#5762]
If you have a content item which has multiple identity providers (say the autoroute part and the identity part) then you will have issues with "Clone". Please don't say "just don't use those two parts together" as I have just provided a simple example you can test out with native Orchard. My true issue was with the Nwazet.Commerce SKU identity and the AutoRoute identity providers (and yes, both of them are needed in the content type definition).

The issue is in Orchard.ContentManagement.DefaultContentManager --> Clone method

The default code is just to append a "-copy" onto the end of the current elementId.Value. This works great if there is only one provider but completely fails if there are two providers since Orchard will now import a content item against just one matching provider (which is the correct thing to do). To get this to work properly, we need to append "-copy" onto each identity. Here is how I accomplished it (and, if acceptable, can be brought into Orchard):

1. Utilize this code to expand the ContentIdentity, edit the values, and push them back into a string:

        var copyId = elementId.Value + "-copy";
        var contentIdentity = new ContentIdentity(elementId.Value);            
        var names = new List<string>(contentIdentity.Dictionary().Keys);
        if (names.Any()) {
            foreach (var name in names) {
                var oldValue = contentIdentity.Get(name);
                if (oldValue != null) {
                    var newValue = oldValue + "-copy";
                    contentIdentity.Add(name, newValue);
                }
            }
            copyId = contentIdentity.ToString();
        }

2. In order for this to work, also need to expose the Dictionary on Orchard.ContentManagement.ContentIdentity like this:

        public Dictionary<string, string> Dictionary() {
            return _dictionary;
        }

And that is it. I look forward to feedback.

**Comment by bleroy** [comment]
Yup, that's a completely legit scenario. Also, appending "-copy" could fail even with one id provider: there can be semantics to identity, that may not allow for any string. This would look like the right fix if it weren't for that. Maybe we need identity providers to provide a new value, and fall back on this if that doesn't work?

**Comment by jeffolmstead** [comment]
Yes, there is this really older issue #5762 which I did not incorporate as I did not want to cause confusion but it does show your point.

**Comment by joshberry** [comment]
Just upgraded a site to 1.10 and I'm still seeing this issue. I'm not sure even creating new identities will fix it since it could still resolve against the alias, right? 

For example:

> /alias=test-product/Identifier=95dc1ea501ab422b9f3c5c4795b161b9/Sku=123-copy
