### ISSUE TITLE
Enhancing ISearchbuilder to accept array as value field

### ISSUE THREAD

**Issue by kumards** [OrchardCMS/Orchard#5764]
Hi,

The current ISearchBuilder.WithField allows only one value to be supplied as search criterion. Any plans to allow array of values. This will allow conditions like
City IN (New York, Boston) AND ProductCategory IN (Electoronics, Mobile, Accessories)

I would assume these are very common scenarios encountered in most of the applications.

**Comment by sebastienros** [comment]
I assume you can call `WithField` multiple times and it will have the same effect. Two other solutions:
- create an extension method to do it for you
- use lucene query language directly if you want more control over the search query

If you go the extension method way, then we could add it in the same namespace as ISearchBuilder.

**Comment by kumards** [comment]
@sebastienros  extension technique wouldn't work. If you look at the example I gave here, it requires must clause nested with should clause. I tried multiple times ```WithField``` method. It ends up with non nested must and should clauses. That does not give me a desired result.

I think query parameter in ```Parse``` method could be another potential candidate only if it allows defaultField to be empty or null.

**Comment by sebastienros** [comment]
I see, it's a MUST between SHOULD values ... so this needs to be added to the interface.

**Comment by TwistedWhisper** [comment]
I have asked a question similar to this a few weeks back at [http://stackoverflow.com/questions/35596168/orchard-lucene-custom-search-service-with-query-grouping-and-numeric-range-query](url)

Currently the ISearchBuilder is limited to handling linear queries only, it doesn't handle grouping well. By grouping, I mean clauses that involve nested parentheses with combination of `MUST` and/or `SHOULD`. The `ISearchBuilder.Parse()` could be used to write a freestyle query to somehow work around this limitation but it's not without its own limitations. `ISearchBuilder.Parse()` is unable to handle range query.

    // this handles Grouping with no problems, note that you can put "null" as the "defaultField" as long as you specify the fields in the query.
    _searchBuilder.Parse(null, "+(City:New\ York City:Boston) +(ProductCategory:Electronics ProductCategory:Mobile ProductCategory:Accessories)", false).Mandatory();

    // the following code can't handle range query and will return no hits (more info at the link I provided above)
    _searchBuilder.Parse("price", "+([100 TO 150] cost:[100 TO 150]) +(ProductCategory:Electronics)", false).Mandatory();

you're better off using the API

    _searchBuilder.WithinRange("price", 100, 150).Mandatory();

but the API is unable to handle more complex queries involving Grouping. Boy, do we appreciate the dilemma here.

<hr />
<h2>Solution</h2>

I would propose the following solution to handle groupings.

<h3>Implementation</h3>
_/src/Orchard/Indexing/ISearchBuilder.cs_

    namespace Orchard.Indexing {
        public interface ISearchBuilder {
            // add a new member
            ISearchBuilder WithGroup(Action<ISearchBuilder> grouping);
        }
    }

_/src/Orchard.Web/Modules/Lucene/Services/LuceneSearchBuilder.cs_

    namespace Lucene.Services {
        public class LuceneSearchBuilder : ISearchBuilder {
            private readonly ILuceneAnalyzerProvider _analyzerProvider;

            public LuceneSearchBuilder(
                Directory directory, 
                ILuceneAnalyzerProvider analyzerProvider,
                string indexName) {
                _analyzerProvider = analyzerProvider;
            }

            public Query CreateQuery() { // change from "private" to "public" access modifier
                ...
            }

            // implement ISearchBuilder.WithGroup()
            public ISearchBuilder WithGroup(Action<ISearchBuilder> grouping) {
                CreatePendingClause();

                // a group is essentially a SearchBuilder                
                var groupSearchBuilder = new LuceneSearchBuilder(null, _analyzerProvider, _indexName);
                grouping(groupSearchBuilder);

                _query = groupSearchBuilder.CreateQuery();
                return this;
            }
        }
    }

<h3>Usages</h3>

    // City IN (New York, Boston) AND ProductCategory IN (Electronics, Mobile, Accessories) which can be translated to 
    // +(City:New\ York City:Boston) +(ProductCategory:Electronics ProductCategory:Mobile ProductCategory:Accessories)
    searchBuilder
        .WithGroup(groupSearchBuilder => groupSearchBuilder
                                            .WithField("City", "New York").ExactMatch()
                                            .WithField("City", "Boston").ExactMatch()
        ).Mandatory()
        .WithGroup(groupSearchBuilder => groupSearchBuilder
                                            .WithField("ProductCategory", "Electronics").ExactMatch()
                                            .WithField("ProductCategory", "Mobile").ExactMatch()
                                            .WithField("ProductCategory", "Accessories").ExactMatch()
        ).Mandatory();

<h2>Additional More General Method</h2>

While we're at it, why not give developers more flexibility than `ISearchBuilder.WithGroup()` has to offer? Allow them to construct their own query.

<h3>Implementation</h3>
_/src/Orchard/Indexing/ISearchBuilder.cs_

    namespace Orchard.Indexing {
        public interface ISearchBuilder {
            // add a new member
            ISearchBuilder WithQuery(Query query);
        }
    }

_/src/Orchard.Web/Modules/Lucene/Services/LuceneSearchBuilder.cs_

    namespace Lucene.Services {
        public class LuceneSearchBuilder : ISearchBuilder {
            public ISearchBuilder WithQuery(Query query) {
                CreatePendingClause();
                _query = query;
                return this;
            }
        }
    }

<h3>Usages</h3>

    // construct our own custom queries
    // let's try building this query
    // +name:camera +(price:[100 TO 150] cost:[100 TO 150]) +(bundle-price:[100 TO 150] total-price:[100 TO 150])
    var booleanQuery1 = new BooleanQuery();
    booleanQuery1.Add(NumericRangeQuery.NewDoubleRange("price", 100, 150, true, true), Occur.SHOULD);
    booleanQuery1.Add(NumericRangeQuery.NewDoubleRange("cost", 100, 150, true, true), Occur.SHOULD);

    var booleanQuery2 = new BooleanQuery();
    booleanQuery2.Add(NumericRangeQuery.NewDoubleRange("bundle-price", 100, 150, true, true), Occur.SHOULD);
    booleanQuery2.Add(NumericRangeQuery.NewDoubleRange("total-price", 100, 150, true, true), Occur.SHOULD);

    searchBuilder.WithField("name", "camera").ExactMatch().Mandatory();
    // insert our custom queries into the SearchBuilder using the newly added interface method (ISearchBuilder.WithQuery()) above
    searchBuilder.WithQuery(booleanQuery1).Mandatory();
    searchBuilder.WithQuery(booleanQuery2).Mandatory();
