### ISSUE TITLE
Dynamic Forms: Button - Validation error goes to home page

### ISSUE THREAD

**Issue by remesq** [OrchardCMS/Orchard#5765]
Original [Orchard Discussion on Codeplex](https://orchard.codeplex.com/discussions/644775).

I noticed that when submitting a Dynamic Form (i.e., clicking the Submit button), instead of the validation error showing up on the page which contains the form it redirects to the home page. Hovering over the button itself shows "/Orchard.DynamicForms/Form/Submit" as the URL. 

Repro: 
* Create a Dynamic Form using the Orchard.Layouts feature with a simple text field and a button for submission. 
    * Enable client side validation. 
    * The text field itself is set to required.
    * NOTE: For simplicity (and in case it was the cause of the error) I removed a Validation Summary element and an actual Validation Message element tied to the text field from the form. However, the error still persists.
    * NOTE: I set the form to Store Submission and also to show a Notification when submitted. I did not include a redirect link.
* Navigate to page containing the form.
* Submit without filling in the text field.
* Redirects to home page.
* Returning to the page containing the form using a link on the home page the validation error shows up.

**Comment by remesq** [comment]
Similar issue which was marked as a bug: https://github.com/OrchardCMS/Orchard/issues/5778

**Comment by sebastienros** [comment]
It seems @sfmskywalker fixed it with this commit c8f2c27
on 1.9.x
