### ISSUE TITLE
HTML error in page crashes content system

### ISSUE THREAD

**Issue by johnwason** [OrchardCMS/Orchard#5767]
I had an error in an MS Word document that I tried to import into a page by inserting the HTML that resulted in the content management system crashing.  I got an "unterminated XML" error when trying to view the content list in the admin menu.  I could not delete the content except through the database.  It should be possible to delete the content even if there is an error in it.

**Comment by sebastienros** [comment]
Could you provide some repro steps? At least tell us where you inserted this faulty XML?

**Comment by johnwason** [comment]
I created a page, added an HTML element, went to Tools->Code, and pasted it in.  I haven't been able to reproduce the error except with the full document. I can send you the document but don't want to post it publicly.

**Comment by sebastienros** [comment]
Tried to add an invalid XML document in the Tools->Code option, works fine for me.

Please provide this file of yours by any mean, or remove any sensitive content from it. I have opened another bug however while trying to repro your bug: https://github.com/OrchardCMS/Orchard/issues/5772

**Comment by CSurieux** [comment]
I had the similar problem on a dev homepage, then Orchard crashed as soon as I try display homepage, only option was to restore db backup. The error was cause by un incomplete src url in an image which was generating an access forbbiden error...

**Comment by sebastienros** [comment]
Do you have any idea how I can reproduce it?

**Comment by CSurieux** [comment]
The theme was missing in my urls, and path badly initiated something as
<img ... src='/Themes/content/header.jpg' />

**Comment by johnwason** [comment]
I put the document that was causing the problem in a gist to download.  I will delete it as soon as you pull the data. It is a public page on my site but I don't necessarily want it being used as a unit test or committed somewhere as it is going to be changed soon.

https://gist.github.com/johnwason/ae9003aad2fffd1de32a

**Comment by sebastienros** [comment]
I have it

**Comment by sebastienros** [comment]
And it's just to repro the issue locally, one time.

**Comment by sebastienros** [comment]
No repro:
- create new page
- open Tools->Code
- paste the content of your gist
- save
- publish the page
- open the page

All fine

**Comment by johnwason** [comment]
I am using 1.9.1. Maybe it has been fixed in the dev branch?
