### ISSUE TITLE
HTML editor toolbar scrolls with long documents

### ISSUE THREAD

**Issue by johnwason** [OrchardCMS/Orchard#5769]
When editing a long document in an HTML page element the toolbar scrolls off screen when scrolling down.  This makes it hard to change font settings etc. when working on a long document.

**Comment by sfmskywalker** [comment]
A workaround is changing the TinyMCE editor to full screen mode.

**Comment by johnwason** [comment]
Thanks, that works.

**Comment by sebastienros** [comment]
Should we still do something?

**Comment by bleroy** [comment]
Yes, this has always been a drag. How about we add a little script that switches the toolbar to a fixed placement as soon as it scrolls off-screen? We did it for the layout toolbar.

**Comment by johnwason** [comment]
I also found the toolbox on the right of the page editor would scroll off screen with the long document.  It made it nearly impossible to select the correct item.  Could you add a separate scrollbar for the toolbox and keep it on the screen? (This is a different problem but related to the TinyMCE issue).
