### ISSUE TITLE
It is such a pain to set up a page using layouts + bootstrap + less

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#5774]
Tying to debug the generated code in browser is crazy so many useless divs genreated with class names unrelated to what they do, some of them (group class) doing duplicate bootstrap features in places where bootstrap does not expect them.
The process is clumsy:
0) Open the html in your layout clic first to edit the html, click next to edit the source code, replace your html (because as far as you have more then 30 lines, the editor is not adapted, so you create your html code in an html file in VS), click accept. reopen to check that editor has changed nothing, click cancel, then accept. Then your images does not display, no pb: publish your page and open it in front to see if it works. If no crash, start debugger to understand why it is not what you expected. but here you are in a kind of PowerPoint made to fight sadam and it is crazy. Found something, restart to 0.

I would add that I installed alternates and hacked my code directly in layout_xxx.cshtml.
Should I go back to using layout ?: yes because I have some orchard content items to display....

**Comment by bleroy** [comment]
It's not clear what the bug is here. FWIW, I have built a couple of themes using BS and LESS, without any trouble. I overrode the templates for the basic layout elements to get the markup I needed, and that was it. I'm a little lost about why you had to do all that.

**Comment by CSurieux** [comment]
I agree it is more several inconveniences than a bug
- to many useless level lines generated: headers, groups, content, item, zone, before, after, message, many layout-xxx , some never used because I am in a layout and don't need all the stuff from the .info file.
- my images don't display in edit layout because they are in my theme content ? May be my fault ? But they display when page is called in front
- css classes with different meanings then in Orchard TMachine and then in pure bootstrap.

**Comment by bleroy** [comment]
Just override the templates. I'll publish a blog post tomorrow with the code for my own overrides. It's BS3.
For images, if you are going to use them in layouts, they should be in media, not the theme.
For those CSS classes, don't use the theme machine, it's not designed for Bootstrap. Use a real BS theme.
Can we close this?

**Comment by CSurieux** [comment]
For bs I followed the reco from different meetings and created a dedicated The BootstrapMachine with a less as the following.
In the past I add been using direct duplicated and adapted .cshtml in my theme views. It was easier.
I will look at your blog.

Concerning the layout, I am always puzzled by the fact that it is not totally integrated with the traditional placement.info and orchard native zones. It is more a collision than an integration.

If you need to close do it.



@import "lib/bootstrap/variables.less";
@import "lib/bootstrap/mixins.less";
@import "lib/bootstrap/grid.less";

#layout-wrapper
{
    .container-fluid;
}

#layout-main-container
{
    .container-fluid;
}

#layout-triple-container
{
    .container-fluid;    

}

#layout-footer
{
    .container-fluid;
}

#layout-triple, #layout-main
{
    .make-row;
}

#triple-first, #triple-second, #triple-third
{
    .make-md-column(4);
}

#layout-content
{
    .make-md-column(12);
}

#aside-12
{
    #layout-content
    {
        .make-md-column(6);
    }
}

#aside-1, #aside-2
{
    #layout-content
    {
        .make-md-column(3);
    }
}


#footer-quad
{ 
    .make-row;
}

#footer-quad-first, #footer-quad-second, #footer-quad-third, #footer-quad-fourth
{
    .make-md-column(3);
}

#footer-sig
{ 
    .make-row;
}

**Comment by sebastienros** [comment]
TODO: Document how to customize elements for bootstrap.

**Comment by bleroy** [comment]
OK, here's the post: https://weblogs.asp.net/bleroy/my-element-template-overrides-for-bootstrap-happy-orchard-dynamic-layouts

**Comment by CSurieux** [comment]
Personnally I end with this customized layout-url-home.cshtml.
Less levels, beacuse I don't need them, allshould be in layout...
But I have to go back to layout....

@{
    /* Global includes for the theme
    ***************************************************************/

    SetMeta(httpEquiv: "X-UA-Compatible", content: "IE=edge,chrome=1");
    Style.Include("lib.css");
    Style.Include("site.css");
    Style.Include("theme.css");
    Script.Require("jQuery").AtFoot();
    Script.Include("../Scripts/bootstrap.js").AtFoot();

    /* Some useful shortcuts or settings
    ***************************************************************/

    Func<dynamic, dynamic> Zone = x => Display(x); // Zone as an alias for Display to help make it obvious when we're displaying zones

    /* Inserting some ad hoc shapes
    ***************************************************************/

    //WorkContext.Layout.Header.Add(New.Branding(), "5"); // Site name and link to the home page
    WorkContext.Layout.Footer.Add(New.BadgeOfHonor(), "5"); // Powered by Orchard
    WorkContext.Layout.Footer.Add(New.User(), "10"); // Login and dashboard links

    /* Last bit of code to prep the layout wrapper
    ***************************************************************/

    Model.Id = "layout-wrapper";
    var tag = Tag(Model, "div"); // using Tag so the layout div gets the classes, id and other attributes added to the Model
}
@tag.StartElement
<div id="layout-main">
    <div id="layout-content">
        @if (Model.Messages != null) {
            <div id="messages">
                @Zone(Model.Messages)
            </div>
        }
        @* the model content for the page is in the Content zone @ the default position (nothing, zero, zilch)
            @if (Model.Content != null) {
            <div id="content">
                @Zone(Model.Content)
            </div>
        *@
        
        <div id="headerhome">
            <img class="main full" alt="h" src="Themes/TheBootstrapMachine/content/header.jpg" />
            <img class="jmenu" alt="" src="Themes//TheBootstrapMachine/Content/menu.png" />
        </div>
        
        <div id="edito">
            <img class="top full" alt="1b" src="Themes/TheBootstrapMachine/Content/barre-danger-page-1.jpg" />
            <div class="contenu">
                <div class="row">
                    <div class="col-xs-4"><div class="whiteborder"><h1>Jingwei<br /> scrute en permanence<br />l'actualité de nos inconscients<br />grâce à ses agents</h1></div></div>
                    <div class="col-xs-8">
                        <h1>Edito</h1>
                        <p>
                            Texte Page 1 ici.
                            Texte Page 1 ici.
                            Texte Page 1 ici.
                            Texte Page 1 ici.
                            Texte Page 1 ici.
                            Texte Page 1 ici.
                            Texte Page 1 ici.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        
        <div id="agenda">
            <img class="top full" alt="2b" src="Themes/TheBootstrapMachine/Content/barre-danger-page-2.jpg" />
            <img class="main full" alt="1" src="Themes/TheBootstrapMachine/content/Page-2.jpg" />
        </div>
        
        <div id="actus">
            <img class="top full" alt="1b" src="Themes/TheBootstrapMachine/Content/separateur-pages.jpg" />
            <div class="contenu">
                <h1>News</h1>
                <div class="list-group">
                    <a href="#" class="list-group-item active">
                        <h4 class="list-group-item-heading">Première nouvelle</h4>
                        <p class="list-group-item-text">patati patata</p>
                    </a>
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Autre nouvelle</h4>
                        <p class="list-group-item-text">patati patata</p>
                    </a>
                </div>
            </div>
        </div>
        
        <div id="catalogue">
            <img class="top full" alt="1b" src="Themes/TheBootstrapMachine/Content/separateur-pages.jpg" />
            <img class="main full" alt="1" src="Themes/TheBootstrapMachine/content/Page-4.jpg" />
        </div>
        
        <div id="partenaires">
            <img class="top full" alt="1b" src="Themes/TheBootstrapMachine/Content/separateur-pages.jpg" />
            <div class="contenu">
                Texte Page 5 ici</div>
            </div>
            
            <div id="appela">
                <img class="top full" alt="1b" src="Themes/TheBootstrapMachine/Content/separateur-pages.jpg" />
                <img class="main full" alt="1" src="Themes/TheBootstrapMachine/content/Page-6.jpg" />
            </div>

            }
        </div>
    </div>
    <div id="layout-footer">
        <footer id="footer">
            @if (Model.Footer != null) {
                <div id="footer-sig">
                    @Zone(Model.Footer)
                </div>
            }
        </footer>
    </div>
    @tag.EndElement
