### ISSUE TITLE
HomeAlias causes content to have two paths

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#5791]
Now that a content item becomes the homepage no longer because it has an empty alias, but by virtue of an alias record pointing to the content item, that content item now has two URLS:

- /
- my-page

Even if you consider that to be a non-issue, then the actual issue is exposed by the following spec flow test:

```
Scenario: I set my blog to be the content for the home page and the posts for the blog be rooted to the app
    Given I have installed Orchard
    When I go to "admin/blogs/create"
        And I fill in
            | name | value |
            | Title.Title | My Blog |
            | AutoroutePart.PromoteToHomePage | true |
        And I hit "Save"
        And I go to "admin/blogs"
        And I follow "My Blog"
        And I follow "New Post" where class name has "primaryAction"
        And I fill in
            | name | value |
            | Title.Title | My Post |
            | Body.Text | Hi there. |
        And I hit "Publish Now"
        And I am redirected
        And I go to "/"
    Then I should see "<h1>My Blog</h1>"
    When I go to "/"
    Then the status should be 200 "OK"
    When I go to "/my-post"
    Then I should see "<h1>My Post</h1>"
```

To summarize, this is what the test is trying to assert:

1. Create a Blog (my-blog) and make it the homepage.
2. Create a Blog Post (my-post).
3. Check that the Blog is served when navigating to "/".
4. Check that the Blog Post is served when navigating to "/my-post".

Check 4 will fail, because when generating the alias for the blog post, it uses the {Content.Container.Path} token, which evaluates to "my-blog" instead of "".

One solution to restore this expected behavior of homepages is to update the Path token implementation to see if the content item is actually the homepage, and return an empty string if it is.

**Comment by sebastienros** [comment]
Right, assuming the token is the only issue. Let's also see where the same property is used anywhere else. And just to be sure, that `@Url.ItemDisplayUrl` and `@Html.ItemDisplayLink` work too.

**Comment by sfmskywalker** [comment]
Good point. Probably need to update the content handler for the autoroutepart to set the proper route values.

**Comment by sfmskywalker** [comment]
Created a PR that fixes the issue here: https://github.com/OrchardCMS/Orchard/pull/5796

This maintains proper URL generation so that `Url.ItemDisplayUrl` and `Html.ItemDisplayLink` return the homepage alias. That's achieved by making sure that of the two available aliases based on the route values, the alias with the empty string is taken to generate the virtual path.
