### ISSUE TITLE
Orchard.Layouts - Expose LayoutData in the admin ui

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5795]
When you add a LayoutPart to a content item you can configure the default data by giving it a block of JSON.

The only way I can find to get at this data is to export the Layouts data as an XML file, open it up and fish out the LayoutData field for the relevant LayoutPart.

As its used within the admin UI it would be useful if the layout editor had some way of exposing the layout data JSON without having to go through this process.

**Comment by DanielStolt** [comment]
In Chrome you can select an element, hit Ctrl+C and then that JSON data is actually placed on the system clipboard, along with the plain-text of the element. It's how copy-paste works. Then you can get it out using LinqPad like this for example:

![image](https://cloud.githubusercontent.com/assets/3889090/9831684/dfb5b438-5960-11e5-9dc5-522898812c89.png)

Realize this is not super easy either, but at least a little less cumbersome than going through the whole export process and getting it XML encoded...

**Comment by rtpHarry** [comment]
Thanks for the tip!

Quick guide for anyone following along:

  1. Download [LINQPad 4](http://www.linqpad.net/download.aspx)
  1. Paste this query into the query window:

      ```var s = (System.IO.MemoryStream)System.Windows.Forms.Clipboard.GetData("Chromium Web Custom MIME Data Format");
System.Text.Encoding.Unicode.GetString(s.ToArray()).Dump();```

  1. Set the Language to `C# Statement(s)` for multiline support
  1. Query > Query Properties > Additional References > Add > Search `Forms` > Add `System.Windows.Forms.dll` reference > OK
  1. Run the query

## Troubleshooting
### NullReferenceException: Object reference not set to an instance of an object.

You copied something else into the clipboard while setting this up, copy the original back from Orchard.
