### ISSUE TITLE
ProjectionElement stores query layout by record ID which does not roundtrip through export/import

### ISSUE THREAD

**Issue by DanielStolt** [OrchardCMS/Orchard#5800]
When adding a projection element to a layout the user can choose a query layout like so:

![image](https://cloud.githubusercontent.com/assets/3889090/9839602/a7e8c30e-5a7f-11e5-8948-6455d0cfde22.png)

This choice gets persisted in the JSON data of the element as the database record ID of the query layout, like so:

    QueryLayoutId=85

Exporting this element to a recipe, the record ID 85 gets embedded in the JSON in the recipe. When importing to a new site (such as when using the recipe as a setup recipe) the query layout will most likely not have the same record ID, which causes the projection element to fall back to the default query layout.

The projection element needs to store the query layout reference by its index which, unlike the DB record ID, will persist across the export/import cycle.

**Comment by DanielStolt** [comment]
Somewhat related issue:
https://github.com/OrchardCMS/Orchard/issues/4440

That one suggests adding a `Name` property to layouts. If we do that, obviously that would be a better identifier than the index.

**Comment by Piedone** [comment]
Although QueryLayoutId is indeed exported, as is the identifier of the query and the index of the layout. So while the former one is useless it does not do harm and there is still the necessary information to restore the state. I don't think this is an existing issue (at least in latest 1.9.x).

**Comment by DanielStolt** [comment]
OK, good. Then it should just be a matter of fixing this in the import code?

**Comment by Piedone** [comment]
It is already. #4440 is a valid issue but if you just export/import Layouts and Queries it will work as expected, at least in my experience (I also fixed some related glitches in 1.9.x because currently I have to do a lot of such export/import).

**Comment by sfmskywalker** [comment]
I just tested it on 1.9.x and it works as expected. Looking at the code, I see that the LayoutIndex is exported as well as imported.

@DanielStolt do you have any repro steps?

**Comment by FB-River** [comment]
I've just come across this bug (or something very similar to it) in 1.9.1 - I've exported a projection and it's query (that only has one custom layout on it) to create a recipe, but when running the recipe, the default query layout is set, not the custom one. Are there any additional steps I need to take to make it work?

**Comment by Piedone** [comment]
It should be fixed in 1.9.2.

**Comment by FB-River** [comment]
OK, thanks!
