### ISSUE TITLE
Orchard.Layouts - Fields Display Issues

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5801]
I have taken a fresh install of 1.9.x branch.

Added some fields to the `Page` ContentType:

![image](https://cloud.githubusercontent.com/assets/1038062/9839601/3e0af7f2-5a77-11e5-9222-33e0c38d2b23.png)

This enables some extra elements under the Fields section of the layouts editor:

![image](https://cloud.githubusercontent.com/assets/1038062/9839605/5bc40220-5a77-11e5-93db-0976aeefeb26.png)

When I try to use them they automatically show all of the fields of that type in their shape instead of just the field that its labelled as:

![image](https://cloud.githubusercontent.com/assets/1038062/9839610/818e7922-5a77-11e5-975b-f16fc41bbc38.png)

I've tried to dig in deep with the Shape Tracer and `placements.info` but I cannot get anything to target them. It stops at the `ContentField.cshtml` template.

It only lists one alternate:

![image](https://cloud.githubusercontent.com/assets/1038062/9839624/c97f1296-5a77-11e5-932b-faf1253c3908.png)

It seems like:

  1. The field element should only show that specific element that its advertising in the toolbox
  1. That it should have more alternates to get a lot more specific with it like:

![Image](https://cloud.githubusercontent.com/assets/1038062/9839631/0b831070-5a78-11e5-8c72-07e991121469.png)

Putting an alternative in the view like `.\TheThemeMachine\Views\ContentField-AnotherText.cshtml` has no effect.

**Comment by cwojke** [comment]
It's fixed by sfmskywalker in 3a7091467b19e468fe59346c1dcfd725e3e3888e.
