### ISSUE TITLE
Enhancement: different cache for specified cookies

### ISSUE THREAD

**Issue by LorenzoFrediani-Laser** [OrchardCMS/Orchard#5811]
Add possibility to vary cached page when specified cookie's parameters change

**Comment by sebastienros** [comment]
@DanielStolt do you think it's reasonable? Looks like any other header value we already support, as long as it is opt-in.

**Comment by DanielStolt** [comment]
Agreed, seems reasonable to me.

**Comment by MatteoPiovanelli-Laser** [comment]
I am integrating @LorenzoFrediani-Laser solution to this issue in my 1.10.x fork. Is that fine?
