### ISSUE TITLE
'not authenticated' layers not being rendered

### ISSUE THREAD

**Issue by d3v3l0p3r** [OrchardCMS/Orchard#5817]
Since upgrading to Orchard 1.9.1 we now have no footer information on our login page when a user is unauthenticated.

It is no longer being rendered. If i set the 'layer rule' to 'authenticated' the footer is rendered.

This is because the Model.Footer is now null in our custom Layout.cshtml

Any suggestions from anyone please?

**Comment by sebastienros** [comment]
Can't repro, I created an HTML widget in the `Anonymous` layer, and it was only displayed when not authenticated.

**Comment by d3v3l0p3r** [comment]
Can you try adding the HTML widget into the footer zone?
