### ISSUE TITLE
Orchard.Layouts - Columns(0) when LayoutPart attached to new content item

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5819]
Fresh install of 1.9.x branch

When you attach a layout part to a content item (for example replacing an existing blog bodypart or creating a new test content item) the default template gives you a column (0):

![image](https://cloud.githubusercontent.com/assets/1038062/9911813/d68bcc6a-5c9b-11e5-975b-38f25c2abb8d.png)

This renders out to a span-0 as well:

![image](https://cloud.githubusercontent.com/assets/1038062/9911827/f1aa92ce-5c9b-11e5-8bb2-ee32b88eb0c7.png)

**Comment by rtpHarry** [comment]
`Orchard.Layouts\Elements\Column.cs` line 23:

        public int? Width {
            get { return this.Retrieve<int?>("Width") ?? this.Retrieve<int?>("ColumnSpan") ?? 0; } // Falling back on "ColumnSpan" for backward compatibility.
            set { this.Store(x => x.Width, value); }
        }

If you change the final `0` in the get to `12` then fixes the bug:

        public int? Width {
            get { return this.Retrieve<int?>("Width") ?? this.Retrieve<int?>("ColumnSpan") ?? 12; } // Falling back on "ColumnSpan" for backward compatibility.
            set { this.Store(x => x.Width, value); }
        }

but it's just glossing over the missing width in the default template.

**Comment by sebastienros** [comment]
Or maybe the attribute should not be rendered when it's `0`

**Comment by sebastienros** [comment]
or return `null` ?

**Comment by rtpHarry** [comment]
The default JSON should include this in the snippet:

   "width": 12,

But I can't find where that is at the moment?

**Comment by rtpHarry** [comment]
The column 0 shouldn't ever exist, it's sneaking in because the template isn't configured correctly.

I think it's going to need another hashed migration fix when it's found plus that sensible default.

**Comment by sebastienros** [comment]
@sfmskywalker
