### ISSUE TITLE
Orchard.Layouts - Stuck in a dialog box when login has timed out / exception occurs

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5821]
1.9.x branch

I had the admin panel open working on a content item with a layout (I've attached one to the blog post).

I'd ended up getting logged out of Orchard separately.

When I dragged the element (it was a H1-6 element) on to the canvas the Dialog box opened up.

Instead of showing the element it showed the login page of the site.

I tried to log in but after I submitted my login form it showed this:

![image](https://cloud.githubusercontent.com/assets/1038062/9912244/72371870-5c9e-11e5-97c6-f58c884233c5.png)

Additionally I then couldn't escape from the Dialog. I tried clicking outside on the ghosted area and pressing esc. There were no dialog buttons for me to click to dismiss nor an X in the corner.

When I attempted to refresh the page I was reminded that I had unsaved content.

As a developer I could f12 in, delete the overlay div and save my content. Normal users would have ended up trapped though.

**Comment by sfmskywalker** [comment]
Yeah, there's a session that times out. We should either use a database table to transfer state from one screen to the next, or keep the session alive using a periodic AJAX ping.

A dialog dismiss button (such as an X or Close button) should definitely be added. Weird that you didn't see one, because it should have been there.

**Comment by rtpHarry** [comment]
I just double checked:

![image](https://cloud.githubusercontent.com/assets/1038062/9912897/c6f7340a-5ca1-11e5-94c0-f583d5e5b9a2.png)

Placing the mouse cursor anywhere in the title bar shows the four way arrows for move.
Clicking in the corner doesn't do anything.

Also I just tested letting it load successfully and there is never a dismiss, just the cancel button in the bottom when it loads correctly:

![image](https://cloud.githubusercontent.com/assets/1038062/9912943/08ff94a0-5ca2-11e5-8455-0119d9485599.png)

**Comment by sebastienros** [comment]
Let's create a component in the admin that will ping the site regularly to keep the session open. This will also fix issues when users create long blog posts and could lose everything because of that.

**Comment by dcinzona** [comment]
Would this component effectively remove timeouts?  We expect a user to be logged out if they keep their browser window open on the computer for an extended period of time.  Perhaps storing the data in local storage in the browser instead?

**Comment by rtpHarry** [comment]
I agree with @sebastienros but also the dialog needs a way to exit using standard procedures like pressing esc or clicking outside the window. If an exception occurred while loading these panels in then you would still end up stuck in it even with the ping component.

**Comment by rtpHarry** [comment]
Esc has been implemented to get out of the dialog if the error occurs so the original issue has been resolved.

Closing this but feel free to reopen if you think it should be open to continue the background timeout ping feature discussion.
