### ISSUE TITLE
set  Autoroute to xxx.html , then Alternate 

### ISSUE THREAD

**Issue by lilonghe** [OrchardCMS/Orchard#5824]
because  i need " XXX.html "
so, set **Autoroute**, then get " news.html "

use **Alternate** to create a view page ( Content-url-news.html.cshtml )
but it's not work 

Can you help me?

> I'm sorry.My English is very poor

**Comment by sfmskywalker** [comment]
Hi! We use GitHub for issue tracking (bug reports and feature suggestions). Questions should be asked on CodePlex: http://orchard.codeplex.com/discussions. Thanks for understanding.

**Comment by dcinzona** [comment]
or gitter ;)
