### ISSUE TITLE
Orchard.exe fail on azure console

### ISSUE THREAD

**Issue by qt1** [OrchardCMS/Orchard#5832]
Scenario:
Newly published site (via git publishing repository),
Site is up and running with default db 
Orchard.exe runs OK on published folder

Trying to run from the azure console results in an exception:

```
> bin\Orchard.exe
D:\home\site\wwwroot
Initializing Orchard session. (This might take a few seconds...)

Type "?" for help, "exit" to exit, "cls" to clear screen



orchard> Error:

  Object reference not set to an instance of an object.


> 
```
Can anyone verify this is not specific to my setting?
Is there a way to remotely debug Orchard.exe ?

**Comment by dcinzona** [comment]
Orchard.exe runs fine for me on the Kudu console (running on azure web apps).  Did you check the logs?  It could be trying to load a dependency and hitting an error.

**Comment by sebastienros** [comment]
I can repro, but only from the Portal and it works fine from the scm console.
I talked to the devs and they explained to me that orchard.exe can't work on the portal console as it's interactive. On the portal they don't support interactive input, they just run the .exe and wait for it to finish, not providing the Sandard input at all.

I am closing it as Not Supported for now.
