### ISSUE TITLE
Placement.info is cached and changes are ignored

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard#5835]
With version 1.9.x (last commit of 12/9/2015) when you make a change to placement it is ignored.

Steps to repro:
1 - Create a new site and load home page
2 - Add `<Place Parts_Common_Metadata="-"/>` to Placement.info and refresh homepage. You will notice metadata still appear.
3 - Stop IIS and remove cache.dat file and Start the App
4 - When you open the homepage the Metatadata of the contents are not shown.

**Comment by jersiovic** [comment]
I have checked monitoring of placement file in HostComponents.config is enabled. 
In fact, I can tell you DefaultVirtualMonitor.Signal is been called when I change Placement file, and this method is executed:
```
public void Signal(string key, object value, CacheItemRemovedReason reason) {
            var virtualPath = Convert.ToString(value);
            Logger.Debug("Virtual path changed ({1}) '{0}'", virtualPath, reason.ToString());

            var token = DetachToken(virtualPath);
            if (token != null)
                token.IsCurrent = false;
        }
```
However by the moment I haven't found where this change in the state of the token is checked to trigger a reload of the Placement.info.

Tomorrow I will retry to look for where it should be checked, but in the mean time I would thank any help.

**Comment by sebastienros** [comment]
I can repro locally.

**Comment by sebastienros** [comment]
It appears it has never worked like this unless `placement.info` is in the theme. I think the cache was just preventing multiple threads from accessing the content of the same file during initialization.

**Comment by sebastienros** [comment]
Can't make it work on themes either ...

**Comment by GioviQ** [comment]
I have just uploaded a new Placement.info in a theme of my online installation of Orchard v.1.10.1.0 and I do not see the changes. Test locally with Visual Studio and it works.

Now reading https://github.com/OrchardCMS/Orchard/issues/7678 I discovered that HostComponents.Release.config disables all monitoring in my realease.
