### ISSUE TITLE
AntiForgery field in manifest file is not optional anymore.

### ISSUE THREAD

**Issue by armanforghani** [OrchardCMS/Orchard#5838]
Based on this [page](http://docs.orchardproject.net/Documentation/manifest-files) AntiForgery field must be optional for a manifest file but it is not because of calling 
```AntiForgery.Equals("enabled", StringComparison.OrdinalIgnoreCase)``` in AntiForgeryAuthorizationFilter.
In case of removing this field from manifest the following error will be occurred.
```Object reference not set to an instance of an object.```

My suggestion is: updating documentation to mark this field as Required. I think explicit ```AntiForgery: disabled``` is good.

**Comment by Piedone** [comment]
Agree. Could you submit a PR for the docs?

**Comment by armanforghani** [comment]
Yes, of course.
