### ISSUE TITLE
Gallery not working in 1.9.x?

### ISSUE THREAD

**Issue by TaiAivaras** [OrchardCMS/Orchard#5843]
^

**Comment by dcinzona** [comment]
Any screenshots or error messages you would like to share?

**Comment by TaiAivaras** [comment]
When i clone 1.9.x branch and try to import a module from gallery into my project, it instals fine and doesn't throw any error, but the module doesn't appear in the features page. It works fine in the master branch though.

**Comment by sebastienros** [comment]
Testing right now.

**Comment by sebastienros** [comment]
Can't repro, works fine for me.
I assume the module you download doesn't actually compile, hence the feature is not loaded. Would you mind sharing with us what module it is? There might be a breaking change introduced in 1.9.x which would be unfortunate.
