### ISSUE TITLE
Invoke Imported on all imported items AFTER Importing has been invoked on ALL content items being imported.

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#5848]
This allows content items to properly configure related information depending on other content items.

For example, the ProjectionElement depends on the selected Query and Layout index. However, if the Query occurs after the content item with the ProjectionElement, the ProjectionElement import code will fail to properly set the selected query layout index since the Query has not yet been fully imported (there's just an on-the-fly- created Query item with zero Layouts).

**Comment by sebastienros** [comment]
Isn't there already a way to order which items are imported first?

**Comment by sebastienros** [comment]
Other solution is to create an Event Handler with new methods after and before the full import. Containing all the items that have been imported, but it would have to work per batch.

**Comment by sfmskywalker** [comment]
@sebastienros There is none - we explored this a while ago, but then realized we didn't need to change anything because the import process will create dependency content items on the fly, which works in cases where depending content items only need the ID of the dependency content item. But if you need information from a content item after its driver's Import method has run, you're out of luck.

**Comment by sfmskywalker** [comment]
The other solution you propose would work o course, but if we repurpose the OnImported event for that we don't have to add anything.

**Comment by stuartraines** [comment]
I also encountered this issue today. Would it not be less invasive to introduce a custom attribute to specify the ordering in which items are exported, or something like a DependsOn attribute.

**Comment by sebastienros** [comment]
@sfmskywalker If you need the actual information to build your item, isn't it that you have a problem in the export, and maybe should include this information, or that your sub content is _composed_ and should be in full?

I will take a look at the Projection/Query export to see what the issue is, I see you are mentioning indexes, which looks ugly in an export (and yes I am probably the one who wrote this ;) )

**Comment by sfmskywalker** [comment]
Maybe, but I don't think so in this case - the Projection export would need to store the QueryLayoutRecords, which are records created by the query part. A projection stores a reference to the Query content item (content identity, which is fine) as well as the index into its Layouts collection (of type LayoutRecord).

I agree that storing the index as part of the export is a nasty business. Someone here suggested to store some 'Name' property instead, but my objection against that is that now the user would be require to provide a valid, unique name for each Query Layout. But a good compromise could be to just generate a GUID as an identifier for the Layout, since it's both unique and constant.

**Comment by sfmskywalker** [comment]
To add, if we store a GUID representing the selected LayoutRecord, we could use that to select the right record when it's needed instead of getting the ID during import (see last line):

```C#
protected override void OnImporting(Projection element, ImportElementContext context) {
    var queryIdentity = context.ExportableData.Get("QueryId");
    var query = queryIdentity != null ? context.Session.GetItemFromSession(queryIdentity) : default(ContentManagement.ContentItem);
...
    var queryPart = query.As<QueryPart>();
    var layoutIndex = XmlHelper.Parse<int>(context.ExportableData.Get("LayoutIndex"));

    element.QueryId = queryPart.Id;
    element.LayoutId = layoutIndex != -1 ? queryPart.Layouts[layoutIndex].Id : -1;
}
```

**Comment by sebastienros** [comment]
Generating a GUID as the identifier? Well, add the IdentityPart maybe ;)

**Comment by sfmskywalker** [comment]
Yes, if only the `LayoutRecord` were a content item. :)

**Comment by sfmskywalker** [comment]
Anyway, I just realized that the `ProjectionPartDriver` handles the import of the selected layout in the **Imported** event rather than *Importing*, while the `ProjectionElementDriver` is doing that during **Importing**. So I'm investigating if all we need is to expose the **Imported** event to element drivers.

**Comment by sebastienros** [comment]
Zoltan will tell us that he told us it should have been a content item ...

**Comment by sfmskywalker** [comment]
:see_no_evil:

**Comment by sfmskywalker** [comment]
Same issue exists with the ProjectionPartDriver (although it prevents an exception by checking if the LayoutRecord exists in the collection of the Query record).

So I still think the easiest and simplest fix is to invoke **Imported** on all content items and elements *after* **Importing** has run on everything.

**Comment by sebastienros** [comment]
This is changing the current assumption, not sure we should do it. Maybe a new event instead, that this module would use. Not in the content handler but as an EventHandler.

**Comment by sfmskywalker** [comment]
Yeah I had the exact same concern, but after discussing that with @DanielStolt , he convinced me that it would not cause any behavioral change. I can't imagine any driver would rely on **Imported** being invoked right after **Importing** before it is invoked on other content items.

Although I do agree a new event would be safest, it does seem like a very low risk and zero impact change, and wouldn't require the addition of an event, which means a clean way to fix something that is currently broken.

**Comment by sebastienros** [comment]
ok on dev, we'll see

**Comment by sfmskywalker** [comment]
Ok, I'll create a PR first.

**Comment by sfmskywalker** [comment]
@sebastienros Do you think it's important to invoke `Imported` on all content items within a batch, or would it be fine to invoke it at the very end across all batches? If per batch, we will need to ask each content item for its dependencies, otherwise we will still have an issue if a dependency is part of a later batch.

**Comment by dcinzona** [comment]
:+1: for this issue.  We encountered this when we were first launching our website via orchard.  Added a few hours to the initial deployments because we had to manually create all of the queries / projections after import.

**Comment by sfmskywalker** [comment]
The following PR fixes this issue: https://github.com/OrchardCMS/Orchard/pull/5872.

The question is: is it OK to invoke `Imported` at the very end across all batches.
