### ISSUE TITLE
Asset system for less does not check imported files

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#5849]
I have a json built like this (part of)
{
        "inputs": [
            "Assets/Less/Site.less"
        ],
        "output": "Styles/Site.css"
    }

and my less site.less starts with

@import "layout.less";
@import "bootswatch.less";

In this case the build command never check for modifications in layout.less nor bootswatch.less.

**Comment by sebastienros** [comment]
Interesting, should/could we actually parse the .less files to detect the dependencies?

@dcinzona @DanielStolt

**Comment by DanielStolt** [comment]
I initially intended to use https://www.npmjs.com/package/gulp-watch-less for this, which identifies imported files and adds them to the watch. But there were many complications with this approach, so I ultimately had to abandon it.

Instead, you should add your imported files to the watch property, like so:

```
{
  "inputs": [ "Assets/Less/Site.less" ],
  "output": "Styles/Site.css",
  "watch": [ "Assets/Less/layout.less", "Assets/Less/bootswatch.less" ]
}
```

**Comment by dcinzona** [comment]
Agree with @DanielStolt 100%.

**Comment by sebastienros** [comment]
Yeah, and this is what I am already using too.
