### ISSUE TITLE
Non draftable content items get an UnPublish menu in Content list

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#5856]
If this is normal, it is not clear.
What is doing the Unpublish command ?

**Comment by sebastienros** [comment]
Good question ;) have you tried clicking it?

**Comment by CSurieux** [comment]
No :)
I was  totally focused on a bug when tryinf to input an IEnumerable<string> and finding how to input datetime ( date with time ) in Orchard ( seems elementary but not obvious, à story of shapes calling shapes...).
But I though, just before leaving, too much tired, rhat it could be my last working session action, reporting it.
As soon as my edior processus is OK and thé Google calendar next calll is running, I could press unpublish, after à db backup.
So it could be à real bug? Not simply an unclear and tricky feature?

**Comment by CSurieux** [comment]
I gave it a try and it set a flag in version to unpublished...so in theory not displayed in front-end.

The problem is that there is no Publish button in edit mode ???? There is only a Save button.
But for draftable items, there is a Save and Publish button ????

Could be disappointing: buttons are in the content  list screen but not in the editor ????

**Comment by sebastienros** [comment]
Ok, we need to fix this inconsistency.
