### ISSUE TITLE
 Decision activity doesn't work

### ISSUE THREAD

**Issue by chandlercc** [OrchardCMS/Orchard#5866]
I create a content parts  name : test1 (address (Text Field))
then  user content type attach  test1
---------------------------------------------
Decision activity :
ContentItem.test1.address.Text="test1";
SetOutcome("Done");
it doesn't work.
---------------------------
Error log:
Orchard.Exceptions.DefaultExceptionPolicy - Default - ERROR An unexpected exception was caught
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 无法对 null 引用执行运行时绑定
Please help me , thx

**Comment by sebastienros** [comment]
I assume your code is wrong. Please check the casing of your part names (test1) and also cast `ContentItem` to dynamic if you want to do something like this code.
