### ISSUE TITLE
[suggestion]Orchard.Search module should support muti-indexdb

### ISSUE THREAD

**Issue by cabbage89** [OrchardCMS/Orchard#5868]
SearchController.cs

in the current, searchSetting is from the global setting, if i have many index-db should i how to assign which index-db i use?
i think search widget should has a setting that can assign index-db .

sorry  , i am poor in english ...

**Comment by sfmskywalker** [comment]
The Search Form widget has an option called *Override Search Index* that allows you to specify the index to search.
