### ISSUE TITLE
Cannot resolve parameter 'Orchard.IWorkContextAccessor workContextAccessor' when running Cloud Service project

### ISSUE THREAD

**Issue by mattcowen** [OrchardCMS/Orchard#5869]
I am getting the following when trying to run the Azure Cloud Service project off the "dev" branch.

The type 'Orchard.Azure.Services.TaskLease.ApplicationEnvironment, Orchard.Azure' could not be found. It may require assembly qualification, e.g. "MyType, MyAssembly".

I guess this should be AzureApplicationEnvironment but that doesnt work either. Anyone know or have any ideas why this type isn't being found?

**Comment by mattcowen** [comment]
I fixed this by making the type Orchard.Azure.Services.Environment.AzureApplicationEnvironment, Orchard.Azure.

However now I get....

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Orchard.Environment.DefaultOrchardShell' can be invoked with the available services and parameters:
Cannot resolve parameter 'Orchard.IWorkContextAccessor workContextAccessor' of constructor 'Void .ctor(Orchard.IWorkContextAccessor, System.Collections.Generic.IEnumerable`1[Orchard.Mvc.Routes.IRouteProvider], System.Collections.Generic.IEnumerable`1[Orchard.WebApi.Routes.IHttpRouteProvider], Orchard.Mvc.Routes.IRoutePublisher, System.Collections.Generic.IEnumerable`1[Orchard.Mvc.ModelBinders.IModelBinderProvider], Orchard.Mvc.ModelBinders.IModelBinderPublisher, Orchard.Tasks.ISweepGenerator, System.Collections.Generic.IEnumerable`1[Orchard.Owin.IOwinMiddlewareProvider], Orchard.Environment.Configuration.ShellSettings)'.

Source Error: 


Line 111:            var shellScope = _shellContainerFactory.CreateContainer(settings, blueprint);
Line 112:
Line 113:            return new ShellContext {
Line 114:                Settings = settings,
Line 115:                Descriptor = descriptor,

Source File: d:\Projects\Orchard-1.9.x\src\Orchard\Environment\ShellBuilders\ShellContextFactory.cs    Line: 113

**Comment by sfmskywalker** [comment]
I recently renamed that type and its namespace. I think I may have forgotten to update the Azure solution. I'll check.

**Comment by mattcowen** [comment]
I got passed the type name by updating the namespace but now getting Cannot resolve parameter error.

**Comment by sfmskywalker** [comment]
Can you please undo your changes and pull from the *dev* branch? You should not have to create your own type as you mentioned in your second post.

What namespace did you update?

**Comment by mattcowen** [comment]
Thanks for the update. I didn't create anything. I just made the change you have just committed so thats good.

Any ideas why the workcontextaccessor on the DefaultOrchardShell is not being resolved by Autofac? I see this in 1.9.x and 1.9.2 however I have had to update to Azure 2.7 sdk. Would be good to know if anyone else is seeing this or just me.

**Comment by sfmskywalker** [comment]
I don't know, but it could be related to this issue: https://github.com/OrchardCMS/Orchard/issues/5490.

**Comment by sebastienros** [comment]
Can I assume you are building the cloud service package and deploying it on Azure?
I will try it right now. And also fix the namespace.

Side discussion, why are you not using Azure Web Apps instead of cloud services?

**Comment by mattcowen** [comment]
I am running the cloud service project in the local Azure emulator. 

Namespace is fixed.

Very good question. Happy to look into making Orchard work for Azure Web Apps however I'm dealing with a year old project that I want to get on the latest code asap. It is a multi-tenant application for 2000+ websites. I would need to check that Azure Web Apps can handle scaling for that.

**Comment by sebastienros** [comment]
Azure Web Apps is as much capable as cloud services. If not more. I can help you on migrating if you wish.

**Comment by sebastienros** [comment]
Fixed in 1.9.2

**Comment by sebastienros** [comment]
NB: local debugging doesn't work, but Cloud Services work fine on Azure.
