### ISSUE TITLE
Could we upgrade the WebApi dlls in lib to Microsoft HTTP Client Libraries 2.2.29 (package)

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#5873]
It seems to be actually 2.28 and it generates many troubles with nugets packages using 2.2.29.

**Comment by sebastienros** [comment]
Can you try to provide a PR?

**Comment by CSurieux** [comment]
I tried to do it
https://github.com/OrchardCMS/Orchard/pull/5930
