### ISSUE TITLE
Dynamic Forms: Web Address Field

### ISSUE THREAD

**Issue by phillipsj** [OrchardCMS/Orchard#5878]
All,

I have created a Web Address Field that validates the entered URL to make sure it is HTTP(S).  I was binding a form to a content type that uses URL and wanted to make sure it validated before hand.  I have this code ready to commit if it is wanted.  If so, which branch?  1.9.x?

Thanks,

Jamie

**Comment by sebastienros** [comment]
Thanks for creating an issue before working on the PR. I think the recommendation we made so far was that if a Content Field exists, then so should the Element for the forms module. And we have one, so I think it's safe to submit it. I want to hear from @bleroy and @sfmskywalker

**Comment by phillipsj** [comment]
@sebastienros Thanks for the quick response.
