### ISSUE TITLE
In DistributedLockService, lock object not removed from the list

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#5882]
Just by enabling the job queue feature, I get this error every minute...

    "No record could be found in the database for lock '{0}'."

I could fix it by adding after this line

    DeleteDistributedLockRecord(internalName);

This line

    _locks.Remove(monitorObj);

Best

**Comment by jtkech** [comment]
In JobsQueueProcessor.cs, because IDistributedLockService is an IDependency referenced by IJobsQueueProcessor that is an ISingletonDependency.

I also use the Work class for this dependency

        private readonly Work<IDistributedLockService> _distributedLockService;


Best

**Comment by jtkech** [comment]
@sfmskywalker, seems to work in other places as in `AutomaticDataMigrations`. The problem is when it's always the same instance of `IDistributedLockService` (even there is one per shell) that is executed as in `JobsQueueProcessor` because it's an `ISingletonDependency`.

So, can be fix by only applying the last update with the `Work<>` in `JobsQueueProcessor`. I've created a PR for this simple fix.

Best

**Comment by lbcsy** [comment]
> Just by enabling the job queue feature, I get this error every minute...
> 
> ```
> "No record could be found in the database for lock '{0}'."
> ```
> 
> I could fix it by adding after this line
> 
> ```
> DeleteDistributedLockRecord(internalName);
> ```
> 
> This line
> 
> ```
> _locks.Remove(monitorObj);
> ```
> 
> Best

I have had the same "No record could be found ..." issue even after I added Work<> in my singleton service, so I was wondering  why "_locks.Remove(monitorObj);" did not go into the code as a fix?
