### ISSUE TITLE
Orchard Dependencies and NuGet - Assembly Errors

### ISSUE THREAD

**Issue by phillipsj** [OrchardCMS/Orchard#5890]
As I understand it, Orchard does not use NuGet due to some modifications of some of the libraries.  Is this accurate?  If so, is there a list of those modifications or the original modified source?  This is causing a lot of issues for us and I am wanting to understand the reasoning as to maybe help find a better solution.  Is it only nHibernate and Autofac that is modified?

Thanks,

**Comment by Jetski5822** [comment]
It used to be that NHibernate was modified. Not sure if that is still the case.

What issues are you running in to?

**Comment by phillipsj** [comment]
We are getting conflicts between dlls when we use nuget, the conflicts almost are always with the dlls in the libs folder.

**Comment by sebastienros** [comment]
Don't use Nuget. We have very specific versions in the /lib which will probably ALWAYS be out of date with what is in Nuget. Which means that if your module is using Nuget, you will have conflicts between the local assemblies in your module and the ones from Orchard. You can always fix it to force them to use the versions from the /lib folder as these are the ones that are supported and forced by Orchard.

Some people have tried to make Orchard use Nuget, without success so far.
