### ISSUE TITLE
media--null ex in recentmediaitems 

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#5891]
user:admin
go to media, create folder,
click recent , got ex
![recent-null](https://cloud.githubusercontent.com/assets/297675/10256688/d71a140c-6920-11e5-88c0-b74c2ca6f4e2.png)

**Comment by infofromca** [comment]
this should go to 1.9.2

**Comment by dcinzona** [comment]
This is fixed in my PR
https://github.com/OrchardCMS/Orchard/pull/5937
