### ISSUE TITLE
Bug in AzureFileSystem generates wrong Blob Urls

### ISSUE THREAD

**Issue by hannan-azam** [OrchardCMS/Orchard#5896]
We have developed a custom Deployment module using Orchard.ImportExport which is capable of exporting Media resources (on Stage) and importing on target site (Production).

Both sites are hosted in Azure. On Stage we have Media placed locally and on Production it is on Azure Blob Storage.

Using Blob (AzureFileSystem) the urls that gets generated on Production are wrong.

For example: For the given FileName: xyz.jpg   and  FolderPath folder1/folder2
The correct url that should be:
http://testazure.blob.core.windows.net/media/Default/folder1/folder2/xyz.jpg

But it generates following url on blob storage:
http://testazure.blob.core.windows.net/media/http://testazure.blob.core.windows.net/media/Default/folder1/folder2/xyz.jpg

We looked into it and figured out where exactly the issue is:

In Orchard.Azure/FileSystems/AzureFileSystem.cs line 358 is the issue:

```
_blob = _blob.Container.GetBlockBlobReference(_blob.Uri.ToString());
```

The above line references the Blob Container and then uses the complete blob URI to regenerate the blob path. Hence the above url gets generated wrongly. By making a small modification as below we fixed this issue for us.

```
_blob = _blob.Container.GetBlockBlobReference(_blob.Name);
```

Please include this bug fix in future versions.

**Comment by Piedone** [comment]
Hmm, I wonder why this works at all then? How is that it generates the correct URL in staging?

**Comment by ivyexcellence** [comment]
We have Media hosted locally on Staging and on Azure Blob Storage on Production.

**Comment by sebastienros** [comment]
What branch are you using to repro this bug?

**Comment by ivyexcellence** [comment]
We are using Orchard 1.9.1 for Staging and Production.

**Comment by dcinzona** [comment]
Can you provide some of the code that facilitates the import/export of the media to blob storage?  Specifically, the method that calls the CreateFile() method in the AzureFileSystem.  I'm having trouble reproducing this issue.

**Comment by ivyexcellence** [comment]
I have created a simple scenario to reproduce the issue. I created a new content type "TestMedia" and included a BodyPart in it. I inserted two Media images into it and later triggered the deployment process which generated a zip (Recipe) which includes the standard Orchard Recipe + the Media resources in the Media folder.

Recipe can be downloaded from following path:
https://www.dropbox.com/s/90rp9f74z54nw95/Recipe.zip?dl=0

At the end of the standard recipe import process which already has created the necessary content items including the Media content items, we trigger the Media import process using standard interface of IStorageProvider

I have taken out all unnecessary code of logging into RecipeJournal and kept the main code which is handling the Media import process.

https://www.dropbox.com/s/ggb4l9iw5g11kry/ImportMedia.txt?dl=0

Following is a brief overview of what we are doing in there:
1. Open up the recipe zip file
2. Read the Orchard standard recipe and extract the MediaPart tags
3. Combine up the FolderPath and FileName to generate the media path
4. Using IStorageProvider check if the media already exists. Create the media if it doesn't exist already
5. From the above process we got IStorageFile instance. We then call "CreateFile" on this to open the media stream in write mode.
6. Open up the media image stream in readonly mode from within the zip and write to the target file (Azure Blob)

At step no.5 where we use the IStorageFile to open up the file in write mode creates the whole mess and generates wrong blob url by combining the container url to the whole uri of the blob url.

As i mentioned previously we fixed it by simple changing it to _blob.Name

One more thing to discuss is that the blob url keeps generating fine if you upload resources from within the Media utility. It is only this specific case where we are importing through code that the blob url gets generated wrongly. I believe that this function of IStorageFile.CreateFile never gets triggered while using the Media utility.

Please let me know if you need more details.

**Comment by dcinzona** [comment]
Thanks, that's good information.  The media utility doesn't use that method for uploading files.  In fact, I can't see anything that does after a quick search (I'm probably wrong, otherwise why would it exist). 
The media library module uses it's own services to upload media.  You may want to try looking into that?  Considering that I can't find anything else that uses the broken method, it may not cause any harm fixing it with your recommendation, but I obviously defer to @Piedone and @sebastienros

**Comment by hannan-azam** [comment]
@dcinzona i just confirmed from the source that Media Library services are also using IStorageProvider to perform all necessary actions of creating/removing files/folders.

We have following two IStorageProvider available:

```
public class FileSystemStorageProvider : IStorageProvider {

[OrchardSuppressDependency("Orchard.FileSystems.Media.FileSystemStorageProvider")]
public class AzureBlobStorageProvider : AzureFileSystem, IStorageProvider {
```

When the feature Orchard.Azure.Media gets activated it suppresses the default FileSystemStorageProvider and starts handling things with AzureBlobStorageProvider.

**Comment by dcinzona** [comment]
So we have that module enabled as we are using Azure and storing our content on Azure Blob storage, but we have no issues and I don't hit the breakpoint mentioned.

**Comment by hannan-azam** [comment]
@dcinzona There are two CreateFile methods available.

```
IStorageProvider.CreateFile
IStorageFile.CreateFile
```

The one with IStorageProvider is fine and seems to be doing things correctly. Media services and all other code paths probably use this method to create files whenever required.
One more thing that i noticed is that the IStorageProvider.CreateFile also creates Folder Entries in Azure Blob with suffixes "$$$ORCHARD$$$.$$$" where as the other method IStorageFile.CreateFile doesn't do this step of ensuring folder entries in Azure Blob Storage.

Our issue could also be solved by making a small code fix and changing the mediaFile.CreateFile call to _storageProvider.CreateFile but i believe the behavior and functionality should be same no matter how you use it.

**Comment by dcinzona** [comment]
Agreed, so I guess I just want to verify that nothing else is affected by making this PR

**Comment by dcinzona** [comment]
PR submitted for review

**Comment by hannan-azam** [comment]
Thanks

**Comment by dcinzona** [comment]
No problem. My guess is that we will review it during tomorrow's call
