### ISSUE TITLE
The Orchard.Azure ServiceDefinition file references a startup task that doesn't exist?

### ISSUE THREAD

**Issue by carlwoodhouse** [OrchardCMS/Orchard#5903]
As far as i can see the ServiceDefinition file for azure is referencing a startup task for setting idle timeout which doesn't exist.

```
  <Startup>
      <Task commandLine="Startup\SetIdleTimeout.cmd" executionContext="elevated" taskType="simple">
        <Environment>
          <!-- Create the environment variable that informs the startup task whether it is running 
			   in the compute emulator or in the cloud. -->
          <Variable name="ComputeEmulatorRunning">
            <RoleInstanceValue xpath="/RoleEnvironment/Deployment/@emulated" />
          </Variable>
        </Environment>
      </Task>
    </Startup>
````

I think there used to be a startup directory in Orchard.Azure.Web with this in

**Comment by DanielStolt** [comment]
The file is there, it just doesn't live in Orchard.Azure.Web.

![image](https://cloud.githubusercontent.com/assets/3889090/10364121/128ac26a-6db9-11e5-8785-3e443f09a8e3.png)

**Comment by carlwoodhouse** [comment]
think i was having a moment lol - cheers
