### ISSUE TITLE
Orchard.Projections - Some admin panel sections escape from the /Admin/ url

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5905]
Branch: Currently on dev but seen it on master as well

When you try to add a new filter, sort criteria or layout the module escapes from the `/admin/` url and use `~/Projector/`:

```
http://localhost:30321/OrchardLocal/Projector/Layout/Add/12
http://localhost:30321/OrchardLocal/Projector/SortCriterion/Add/12
http://localhost:30321/OrchardLocal/Projector/Layout/Add/12
```

![image](https://cloud.githubusercontent.com/assets/1038062/10350560/98c1bc76-6d3c-11e5-8dcb-068ceda33c88.png)

While this might not be technically a requirement of admin, I'm pretty sure I've seen it as a best-practice and it means a user cannot create a page a slug with that name.

**Comment by rtpHarry** [comment]
Also

    http://localhost:30321/OrchardLocal/Packaging/Gallery/Modules

**Comment by rtpHarry** [comment]
Also, as Donald points out in #6787 

    /Orchard.OutputCache/Statistics

**Comment by Skrypt** [comment]
Someone started working on this ?

**Comment by rtpHarry** [comment]
I haven't no

**Comment by Skrypt** [comment]
Won't fix. Too old. Should be moved to Orchard Core as some Url's are also not having the /admin in the admin.
