### ISSUE TITLE
Orchard.MultiTenant - Exception when changing database prefix after tenant has been created

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5906]
Branch: Dev

## Repro
 1. Enable multi tenant
 1. Create a tenant (I used SQL CE database) but leave `Database Table Prefix` blank
 1. Set up tenant in Orchard setup
 1. Go back to tenant management and add a `Database Table Prefix`, i used `forgotprefix` but any value will break it:

![image](https://cloud.githubusercontent.com/assets/1038062/10350994/19e20eda-6d3f-11e5-85a6-f913e36bccd1.png)

![image](https://cloud.githubusercontent.com/assets/1038062/10351064/6c379830-6d3f-11e5-8b04-2e48874a3211.png)

**Comment by rtpHarry** [comment]
Haha I just noticed this message:

    Warning: If you don't know what you're doing you *will* (likely) send this tenant into a downward spiral of irrecoverable disrepair. Have a nice day.

That might be what this is referring to.

It has a CSS class .warning .message applied to it but no styles and I missed it until just now.

**Comment by rtpHarry** [comment]
Going back to my first screenshot it seems that the database prefix isn't actually for SQL CE and should be hidden?

If I select `Use an existing SQL Server` and then go back to `SQL Compact` half the UI disappears:

![image](https://cloud.githubusercontent.com/assets/1038062/10351923/12bff4e6-6d44-11e5-923e-738c421bc861.png)

**Comment by sebastienros** [comment]
Better fix is in #5912

**Comment by rtpHarry** [comment]
I opened #5912 because it was separate to this, but I agree this a bit of a muddled issue report, I'll split them out and be clearer.
