### ISSUE TITLE
Modules Admin - Display glitches when module has many dependencies

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#5907]
Branch tested: Dev
Browser tested: Chrome

On large screens a module's dependencies may wrap onto a new line and touch the bottom border:

![image](https://cloud.githubusercontent.com/assets/1038062/10351303/ba650244-6d40-11e5-9e7e-544a7050d418.png)

On smaller screens the dependencies can disappear from view:

![image](https://cloud.githubusercontent.com/assets/1038062/10351417/59ddf4c0-6d41-11e5-9477-95c68445ea1b.png)

(missing the widgets)

Consider implementing an auto-height script such as:

  - https://github.com/liabru/jquery-match-height/

**Comment by DanielStolt** [comment]
Auto-height scripts should not be necessary, it should only be a matter of not having a fixed height specified on those containers.

**Comment by rtpHarry** [comment]
If you don't set all the items to an equal height then each li will be uneven: 

![image](https://cloud.githubusercontent.com/assets/1038062/10364565/6c8a0924-6db4-11e5-97b0-217c497d00fc.png)

**Comment by DanielStolt** [comment]
Yes - is that a problem?

If that's not acceptable I think we should use flexbox rather than a script. (Yes, IE9 users will still see the original behavior, but I don't think they exist... :) )

**Comment by rtpHarry** [comment]
Well it just makes it look a bit messy and the original developer specifically put a height on it to get the effect so I was just trying to keep it consistent.

I only suggested the JS solution because it's in the admin panel so page weight isn't such an issue. If flexbox is ready for use now then I'm behind it, I read about it a long time ago but it's not part of my toolbox yet as I thought browser support wasn't there yet.

I'm solution agnostic :)

**Comment by DanielStolt** [comment]
Once you go flex, you ain't never going back. ;)

Browser support is definitely there:
http://caniuse.com/#feat=flexbox
