### ISSUE TITLE
Page editor

### ISSUE THREAD

**Issue by hkesharia** [OrchardCMS/Orchard#5909]
Hi, 

I want to provide page creation/edition at runtime something similar to Page Editor here in Orchard. Is it possible to use just PageEditor framework (without using whole) from Orchard? 

Or any suggestion on that? 

Regards,
Hitesh

**Comment by sfmskywalker** [comment]
Hi hkesharia,

Please ask questions on our forum: http://orchard.codeplex.com/discussions.

Thanks!
