### ISSUE TITLE
Others issues with Layout OnIndexing in BackgroundTasks

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#5932]
Repro:
 - Configure a valid search index
 - Create a Layout, add a menu element and publish
 - The indexing background task will fail

The Same with Breadcrumbs and projection elements... This because **display methods** are used in the layout part **OnIndexing()**, so each element OnDisplaying() which expects a valid httpContext will fail...

Moreover, with a projection element you can have more issues because of full content items rendering, with other content parts / fields, in a current theme, culture... So, potentially, there are too many places where we would need to check for a valid httpContext, request, requestContext...

I can easily fix each issue one by one, but I think we need here a more global solution. Maybe by providing through httpContextAccessor a new standin context as in the MvcModule but with more properties (QueryString, Session...). Or by wrapping a fake httpContext... I've tried this last solution whithout the baseUrl, with any hostname but with the right app virtual path...

Or maybe, for indexing the layout part, we need to implement some kind of layout element indexing handler / driver methods, and not to use the element OnDisplaying() ones.

Best

**Comment by sfmskywalker** [comment]
> Or maybe, for indexing the layout part, we need to implement some kind of layout element indexing handler / driver methods, and not to use the element OnDisplaying() ones.

That's what I did initially, very similar to what we do from content handlers.

However, we should still be able to render elements from a background task regardless, so I think it should be fixed by providing a stand-in HTTP context as provided by `MvcModule`.

This issue was originally fixed with the changes I made to `HttpContextAccessor`. Those changes have been reverted (for the better). If you could provide a PR fixing this issue that'd be awesome. :)

**Comment by jtkech** [comment]
@sfmskywalker very interesting, I will work on it asap. But there are so many interactions and so many ways to do things. So, I first need some advices (sorry for the length).

> **For a stand-in HTTP context in a background task, do we really need to use the baseUrl? I've tried a solution with only a fake hostname but with the right application virtual path...**

But maybe important, I've seen that the `baseUrl` is used to init some collections (e.g `Headers & ServerVariables`). If so, one of the difficulties in the `MvcModule` is that we need a first request context to get the baseUrl... Here, maybe I've found a solution by using an `Autofac QueryOver`...

> **Through the HttpContextAccessor, do we need to carry the httpContext? Or can we return always a new object as I've tried and as done in the MvcModule**

If we need to carry the httpContext, we could use the `CallContext Logical Data`. See the last posts of #4338, where I use it to carry the workcontext in async code (need to be validated)... Otherwise, I've tried a solution where I carry only the `baseUrl`, used when a new httpContext is created...

> **In place of an HttpContextPlaceholder, can we use an HttpContextWrapper based on a created httpContext? (marked  somewhere as a background context).**

There are so many things initialized for us with an `HttpContextWrapper` (here maybe good to init some collections as done in the MvcModule). If we need to use an `HttpContextPlaceholder`, I would need to override others properties (e.g request.RequestContext).

> **Finally, in one of your commits I've seen that you was initializing the HttpContext.Current...**

I didn't need it, but you was talking about some Html Helpers which use it... Is it worth to consider this?

Best

**Comment by jtkech** [comment]
@sfmskywalker I've a solution that seems to work fine in my local environment, with only a few updates, and that prevents all the issues described above...

I've opted to always use an `HttpContextPlaceholder`. In `WorkContextAccessor`, after the workcontext, I also resolve an `HttpContextBase` which is carried through the `CallContext.LogicalSetData()`. Then in `HttpContextAccessor` I can simply retrieve it through the `CallContext.LogicalGetData()`...

So easy to use the `CallContext` in a few lines without using thread static dictionaries... I also needed to extend some other properties in the `MvcModule`, and other minor updates...

I will do a PR soon but I don't know if I use my current solution because I also carry the `WorkContext` through the `CallContext`. Maybe yes because it's an experimental PR, and it would be easy to change it (only the `WorkContextAccessor` file) to carry only the `HttpContextBase` through the `CallContext` ...

Best

**Comment by sfmskywalker** [comment]
> I've opted to always use an HttpContextPlaceholder

You mean, always use an `HttpContextPlaceholder` in background tasks, correct?
That makes sense to me. What other option would there be? (I'm not currently looking at the code)

Regarding your question on setting `HttpContext.Current`, yes this is necessary if we want to be able to render shapes from background tasks, since HtmlHelpers access `HttpContext.Current` directly. Not only important for indexing layouts in the background, but also when generating email messages from a workflow in response to a timer activity for example.

Thanks for doing all of this work, much appreciated.

**Comment by jtkech** [comment]
>You mean, always use an HttpContextPlaceholder in background tasks, correct?

Yes

>What other option would there be?

A derivated class of `HttpContextWrapper` based on a `mockup HttpContext`, I've tried some solution that seems to work. But I still needed to override some properties, and there is no perfect solution with the lazy loading of the baseUrl...

Because to get the baseUrl we need an `HttpContext` that needs a baseUrl..., we use a lazy loading for the baseUrl. **But this circular dependency can still causes many issues when resolving components**. I've tried a solution that works with a 3rd Factory registered by name to break the loop, and used for the first creation... But I found a solution by only using a new property to check if the baseUrl is loaded...

>Regarding your question on setting HttpContext.Current, yes this is necessary...

I've worked on it. As said, I use the `CallContext DataStore` to carry the workcontext and the httpcontext, and this seems to work even with async code. Notice that `HttpContext.Current` uses the `CallContext.HostContext` that is not carried automatically (this is done by asp during a web request).

So, if tomorrow we use async code in background tasks, it would be difficult to update and maintain the `HttpContext.Current` value. I think we have better to set a value in some specific context / event...

So, I first tried a disposable scope class in some places, this worked but not the best solution. Finally, because when a view is rendered the `httpContext.Request` property is used, I've tried the solution to update the `HttpContext.Current` in this property accessor and clear it when the `HttpContextPlaceholder` is disposed (without retrieving a previous value because we set it when needed to render views in background tasks)..., and all seemed to work even when using some html helpers...

Need more thinking and tests...

Best

**Comment by jtkech** [comment]
@sfmskywalker just to say that I've done an experimental PR #5966 to share my code and for testing. In this PR, I carry through the Logical CallContext not only the HttpContext but also the WorkContext , but I can easily revert back some changes to carry the WorkContext as before with a thread static dictionary...
