### ISSUE TITLE
On the Widget Admin page zones should be attached to each layer not global to all layers

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#5933]
For the default Layer, widgets could be displayed if their zone is present on the actual layer ?
This has certainly be tried ?

replace in actual Admin controller
>            IEnumerable<string> allZones = _widgetsService.GetZones();
>            IEnumerable<string> currentThemesZones = _widgetsService.GetZones(currentTheme);
>            string zonePreviewImagePath = string.Format("{0}/{1}/ThemeZonePreview.png", currentTheme.Location, currentTheme.Id);

by

>            IEnumerable<string> allZones = _widgetsService.GetZones(currentLayer);
>            IEnumerable<string> currentThemesZones = _widgetsService.GetZones(currentTheme,currentLayer);
>             string zonePreviewImagePath = string.Format("{0}/{1}/{2}ThemeZonePreview.png", currentTheme.Location, currentTheme.Id, currentLayer);

etc....

**Comment by CSurieux** [comment]
I have implemented it and it works nice. I will propose a PR asap.
It just involves adding 2 lines on each theme.txt as in this sample
>Name: The Bootstrap Machine
>Author: Me
>Description: Orchard Bootstrap Theme Machine built with less
>Version: 1.9.1
>Tags: Awesome
>Website: http://jingwei.agency
>Zones: Header, Navigation, Featured, BeforeMain, AsideFirst, Messages, BeforeContent, Content, AfterContent, AsideSecond, AfterMain, TripelFirst, TripelSecond, TripelThird, FooterQuadFirst, FooterQuadSecond, FooterQuadThird, FooterQuadFourth, Footer
>Layers: TheHomepage, Blogs, Calendar
>LayerZones: {"TheHomepage":"Messages, Headerhome, Edito, Agenda, Actus, Catalogue, Partenaires, Appela","Blogs":"Header, Navigation, Featured, AsideFirst, Messages, Content, AsideSecond, Footer","Calendar":"Header, Navigation, AsideFirst, Messages, BeforeContent, Content, Footer"}

**Comment by CSurieux** [comment]
I created the PR https://github.com/OrchardCMS/Orchard/pull/5942

**Comment by sebastienros** [comment]
This is not how Layers have been designed to work. And you can't define something in the manifest that will depend on actual content. The zones don't know about the layers.

Can you try to explain what the current implementation is preventing you from doing?

**Comment by CSurieux** [comment]
I will take time to write about this asap.

Envoyé à partir de mon sanyo phc 25
________________________________
De : Sébastien Ros<mailto:notifications@github.com>
Envoyé : ‎15/‎10/‎2015 21:28
À : OrchardCMS/Orchard<mailto:Orchard@noreply.github.com>
Cc : CSurieux<mailto:christian.surieux@hotmail.fr>
Objet : Re: [Orchard] On the Widget Admin page zones should be attached to each layer not global to all layers (#5933)

This is not how Layers have been designed to work. And you can't define something in the manifest that will depend on actual content. The zones don't know about the layers.

Can you try to explain what the current implementation is preventing you from doing?

---

**Comment by CSurieux** [comment]
https://youtu.be/oXNVY_LFMJc
