### ISSUE TITLE
Ability to add default value for every Content Field.

### ISSUE THREAD

**Issue by sylord0803** [OrchardCMS/Orchard#5934]
Currently only the BooleanField has DefaultValue setting. Having this feature would be great.

**Comment by sebastienros** [comment]
> Having this feature would be great.

This is an opinion. Please don't share these.

**Comment by sebastienros** [comment]
Ok, and this value should be tokenized.

**Comment by BenedekFarkas** [comment]
![](https://i.imgflip.com/somkv.jpg)

**Comment by Piedone** [comment]
Changed to dev as this is quite involved and needs Framework and Core changes too.
