### ISSUE TITLE
Ability to add placeholder for every Content Field.

### ISSUE THREAD

**Issue by sylord0803** [OrchardCMS/Orchard#5943]
Currently there is no option to adding placeholder for Content Fields. Having this feature would be great.

**Comment by sebastienros** [comment]
Yes, because we already have support for hints.

**Comment by sfmskywalker** [comment]
And perhaps do the same for Dynamic Form fields where it makes sense.

**Comment by spero-cnet** [comment]
+1 adding placeholder to Dynamic Forms
