### ISSUE TITLE
How to get Orchard ContentManager service in new thread method

### ISSUE THREAD

**Issue by Klainer** [OrchardCMS/Orchard#5949]
Hello,
How to get Orchard ContentManager service in new thread method,

I tried this, but it no work due to "dispose error"
Thread thread = new Thread(() => CallService(this._services.ContentManager));
thread.Start();

Thanks  for help !

**Comment by Piedone** [comment]
This is not an issue but a question, please don't open issue about such.

In separate threads you should create a separate work context and resolve the CM from that. BTW creating Threads by hand is not something you should generally do (but rather write Tasks).

**Comment by Klainer** [comment]
I´m sorry and thanks. Please how create and resolve work context ? Thanks many!!!
