### ISSUE TITLE
Page Title is overridden by last Model's Title if a Content Item of type Form or Page

### ISSUE THREAD

**Issue by j42house** [OrchardCMS/Orchard#5954]
To reproduce:
1. Create a Page - Page Title displays TitlePart from Page
2. Add a Content Item element to the Page and select a Dynamic Form (or other Page) - Page Title displays the Content Item's TitlePart (selects last Model in tree if multiple)

**Comment by Piedone** [comment]
This is only if the content item is displayed in Detail display type. Not sure we should change this.

**Comment by j42house** [comment]
My solution was to create a Content-Form.Detail view that checks if Layout.Title is set already, else set it (for cases where the same form is both embedded and its own route).  It just seems somewhat unnecessary.

**Comment by sebastienros** [comment]
By design, not much we can do but what you already found, or what Zoltan is suggesting.

**Comment by Bunlong** [comment]
Hello @j42house @Piedone @sebastienros I am working on a project using Orchard CMS and I've faced the problem similar to the above issue. I add the Content Item to the page and I can't get the page title of the page. Do you have any ideas on this issue? Thanks

**Comment by Piedone** [comment]
What exactly do you mean by "can't get the page title of the page"?

**Comment by Bunlong** [comment]
@Piedone I mean that whenever I add a Content Item element the a page, the page title always empty/nil or blank.

**Comment by Piedone** [comment]
Is it the built-in Page content type, so does it have TitlePart attached (and if yes, did you specify a title? It should be obligatory, but nevertheless.)? What's the content type of the embedded item, and does it have TitlePart and does it have a title? Also, do you display it in Summary or Detail?
