### ISSUE TITLE
LinkEntry needs Sizes Attribute

### ISSUE THREAD

**Issue by RolfVeinoeSorensen** [OrchardCMS/Orchard#5960]
It would be nice if the Orchard.UI.Resources LinkEntry had the Sizes attribute.

This would enable the possibility to add favicons using the method described her
https://github.com/audreyr/favicon-cheat-sheet

        public string Sizes
        {
            get
            {
                string value;
                _builder.Attributes.TryGetValue("sizes", out value);
                return value;
            }
            set { SetAttribute("sizes", value); }
        }

**Comment by Piedone** [comment]
Indeed.

**Comment by sebastienros** [comment]
What about adding an `Attributes` indexer on this class? And also add Sizes if it's part of a standard.

**Comment by rtpHarry** [comment]
It is documented here so I think it should be included:

  - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-sizes

One note in the docs is that:

  > It must be present only if the rel contains the icon link types value.

Worth coding?
