### ISSUE TITLE
How to get one element record to another element in orchard

### ISSUE THREAD

**Issue by NST77** [OrchardCMS/Orchard#5964]
I have 2 element one is Element1 and 2nd one is Element2, and i have saving some data's in element1 and i need to fetch that data to Element2. How can i do that?

**Comment by sfmskywalker** [comment]
Hi! Please ask questions on [the forum](http://orchard.codeplex.com/discussions) - we use GitHub for issue tracking. Thanks!

**Comment by NST77** [comment]
Ho ok....
I have also created one question in form
https://orchard.codeplex.com/discussions/646355
