### ISSUE TITLE
Precompile Build and config files

### ISSUE THREAD

**Issue by phillipsj** [OrchardCMS/Orchard#5965]
I have noticed that if I run a precompiled build it puts the Host.Config, HostComponents.Config, and log4net.config files in the root.  However, when I download the Orchard.Web package from website it has those files in the Config folder.  Is this by design?  Does it need fixed for the precompiled build?  I am assuming the package on the website is a web deploy package.

**Comment by sebastienros** [comment]
They should be in the /Config folder, that's weird

**Comment by phillipsj** [comment]
Okay, I will take this.

**Comment by sebastienros** [comment]
They are correctly in /Config for me

**Comment by phillipsj** [comment]
Hmm, interesting that it isn't working correctly for me.  I just tried it with a fresh version of Orchard source it it worked fine.  Very strange.
