### ISSUE TITLE
Optionally setup a 301 redirect on autoroute change

### ISSUE THREAD

**Issue by carlwoodhouse** [OrchardCMS/Orchard#5968]
Currently when a route is updated the old alias is removed, it would be nice if it was preserved and did a 301 redirect to the new route for SEO purposes. This could be optional. Thoughts?

Currently have this implemented in my deployment by suppressing the DefaultAliasService and implementing a filter to handle the redirects, not made it optional yet.

**Comment by sebastienros** [comment]
Sipke says they have a module for that. If there wasn't one I would suggest to create a module for that.

**Comment by carlwoodhouse** [comment]
shall have a look for it and see if its better then what we do currently
