### ISSUE TITLE
1.9.2 Layouts - Manage Layout Content

### ISSUE THREAD

**Issue by phillipsj** [OrchardCMS/Orchard#5969]
Layouts are not showing up in the Manage Layout Content at all.  In addition, when I click Apply in the Manage Layout Content, it loads Manage Content.

**Comment by sfmskywalker** [comment]
The Layout type is not Listable, while we're using the content list controller from the Contents module. I think we should tweak this controller that it does list non-listable content items if the list is filtered by that type. @sebastienros has ideas on this.

**Comment by phillipsj** [comment]
@sfmskywalker @sebastienros  Hmm, with them not being listable, can layouts be disabled? I can understand not allowing deletion unless you check first to make sure it isn't used, but I would like the ability to disable a layout from showing up as a choose in the dropdown.  I will take a look and see if I can do something with it.

**Comment by sfmskywalker** [comment]
If you don't have any template layout content items, that dropdown will not be visible. A user could still create a Layout content item of course. If you want to disable that, simply remove the `ManageLayouts` permission form the user's role.

**Comment by sfmskywalker** [comment]
But if you want to prevent the user from being able to select a layout template using the dropdown, we'll have to add another permission. Is that something you would need?

**Comment by phillipsj** [comment]
So here is the exact use case that I had in mind.

    As a content creator, I created a layout incorrectly. I want 
    to be able to not allow that layout to be used when creating 
    content, so that the incorrect template is not mistakenly used.

 If layouts could be deleted then this is probably not an issue, but once in use, deletion becomes difficult so having the ability to toggle if its "selectable" will handle that issue the easiest.

**Comment by sebastienros** [comment]
The solution is to force the type to appear if it's not in the Listable but it's specified in the querystring.

**Comment by joshberry** [comment]
I'm running into this issue and am not sure what to do. Layouts are essentially unusable with this issue since you can't access them for updates. What's the recommended workaround? Should I simply make the Layout content type listable for now?

**Comment by sfmskywalker** [comment]
Yes, I'd make them listable for the time being so you can at least edit them.
