### ISSUE TITLE
SessionState blocking SignalR start request after DB change

### ISSUE THREAD

**Issue by FrancoisCamus** [OrchardCMS/Orchard#5975]
Hi,

I'm having a weird behavior when using SignalR 2.2.0 via @pszmyd Signalr module (https://bitbucket.org/Proligence/proligence.signalr-git/wiki/Home) with Orchard 1.9.1.

The first time I load the site on a page that starts a signalr connection then no worries. If I then do any action in the Dashboard that requires a DB change (add widget, edit content item...) then the next time I load my page, all ajax requests and the signalr start request hangs for 110s before being processed.
I can reproduce this issue on 1.9.1 and 1.9.2 with @pszmyd Signalr module (master branch) by using one of the samples: ~/Proligence.SignalR/Samples/Benchmark

I understand that the issue comes from the SessionState locking the request and therefore blocking all other requests from being processed.
https://github.com/SignalR/SignalR/issues/3295

It seems that the following line:
```
requestContext.HttpContext.SetSessionStateBehavior(_sessionStateBehavior);
```
in Orchard.Mvc.Routes.ShellRoute is the cause of the SessionState locking.

By default, the value is SessionStateBehavior.Default which is overridable via module resource manifest. All my modules and @pszmyd Signalr module have the "sessionstate" set to "disabled".

If I force the value to be ReadOnly then my issue disappears.
If I force the value to be Disabled then I get the issue described here:
http://orchard.codeplex.com/workitem/19141

I'm puzzled why the DB change is causing this. Am I missing something obvious here?

**Comment by halter73** [comment]
If SignalR is running in IIS's integrated pipeline, it should handle all of its requests entirely during the "PostAuthorizeRequest" stage which is before the "AcquireRequestState" where session state is usually set up.

The entire reason for running in PostAuthorizeRequest is [to avoid this session state issue](https://github.com/SignalR/SignalR/blob/2.1.2/src/Microsoft.AspNet.SignalR.Core/Owin/OwinExtensions.cs#L238). 

My guess is that the session state is acquired during/prior to the PostAuthorizeRequest stage.

**Comment by pszmyd** [comment]
@halter73 Thanks for the info. Sounds like fun - have to take a closer look. Haven't touched the module for months...

**Comment by FrancoisCamus** [comment]
Thanks @halter73 for the info. @pszmyd have you had a chance to look into this? I'm still unsure it comes from your module or the way the session state is handled within Orchard. I haven't seen anything weird by playing with the Application_PostAuthorizeRequest and Application_AcquireRequestState events in Global.asax.

I'm still struggling with this issue as now I cannot use any features using SessionState or TempData, otherwise this issue occurs. Recycling the app pool each time I make a change is not an option for me.

At first, I put in place a hack within Orchard.Mvc.Routes.RoutePublisher to force session state accesses to only be read-only but this breaks features using SessionState or TempData like Orchard.Layouts :(

For example, if I make a change to a content (like TitlePart on a Page) then the issue occurs because Orchard.UI.Notify.NotifyFilter add some data to TempData. If I modify it to not write into TempData then the issue does not occur.

I've tried using the Owin.IAppBuilder.UseStageMarker to force the right stage within Orchard and @pszmyd module with no luck.

Am I the only one using SignalR with Orchard 1.9?

I'm running out of ideas so I'll take any pointers or clues...

**Comment by FrancoisCamus** [comment]
Alright! It took me a while but I can definitely say that the issue comes from @pszmyd module.
I'll close this one and raise a bug on @pszmyd repository. I've got SignalR 2.2.0 working fine with Orchard 1.9.2 now and can start playing with Orchard.Layouts :)

**Comment by FrancoisCamus** [comment]
Here is a link to the bug raised on @pszmyd module repository:
https://bitbucket.org/Proligence/proligence.signalr-git/issues/18

**Comment by kumards** [comment]
@FrancoisCamus could you please help me locating the fix in the code?
I am also stuck in this issue.
