### ISSUE TITLE
1.9.2 Layouts - 'Image not found' (null) when adding Image Element

### ISSUE THREAD

**Issue by nqynik** [OrchardCMS/Orchard#5978]
After dragging an image element to the layout and selecting the image in the library picker, it always displays 'image not found'.

To replicate - after creating a new column, drag an image element to the canvas. Click the 'add' button, select an image and click the 'Select' button. 

On further testing, the image does insert correctly if you double click the image instead of clicking the select button.

I get the same issue on 1.9.x.

**Comment by rtpHarry** [comment]
Are you scrolling the media picker down and clicking its button? It kind of sounds like you are but I just thought I would check as it tripped me up to start with. There is a button to dismiss the dialog but the media picker is in a scrolling frame within that and the button for the media picker doesn't fit on screen.

**Comment by rtpHarry** [comment]
I've just tested this with 1.9.2 and it is working for me:

  1. 
![image](https://cloud.githubusercontent.com/assets/1038062/10705584/d9ec15e2-79d6-11e5-9c40-e5aed52ccea3.png)

  1. `Create Folder`

  1. Name it `Images`, click `Save`

  1. Select `Images` folder, click `Import`

      ![image](https://cloud.githubusercontent.com/assets/1038062/10705603/0d1a7ef4-79d7-11e5-8aae-730c660b6966.png)

  1. Add an image, click `Close`

  1. Back in the main media library, select the image:

      ![image](https://cloud.githubusercontent.com/assets/1038062/10705627/4815707c-79d7-11e5-9056-f26a82719a33.png)

  1. Now you will see that a scroll bar appears:

      ![image](https://cloud.githubusercontent.com/assets/1038062/10705651/664034a6-79d7-11e5-8082-e077d3af5cb9.png)

      You must scroll down here.

  1. Click select, then click `save`:

       ![image](https://cloud.githubusercontent.com/assets/1038062/10705675/8de98714-79d7-11e5-9d7e-ff5bd724da0e.png)

  1. The image is added:

      ![image](https://cloud.githubusercontent.com/assets/1038062/10705715/d858d994-79d7-11e5-80cf-305b2c431af4.png)

Now, I do agree that this is pretty bad UI and going to confuse 90% of people, especially end users, but it does work :)

I think I will open a separate issue to get this sorted

**Comment by sfmskywalker** [comment]
I'd say. One minor temporary improvement that was made is hiding the Save button while browsing Media. I'm not sure if that went into 1.9.x or dev though.

In any case, a re-work of the media picker story in combination with Layouts would make you turn you into a hero instantaneously. :)

**Comment by rtpHarry** [comment]
A quick solution would be to:

  1. Move `Selection` to the top and `Properties` to the bottom
  1. Move the buttons to the top of each section

This would immediately make the buttons more visible:

![image](https://cloud.githubusercontent.com/assets/1038062/10706995/a2ecb93a-79e4-11e5-986e-51d43d998f80.png)

**Comment by sebastienros** [comment]
Matthew, feel free to fix this, the properties should still be at the top, but the select button has to be visible without scrolling.

**Comment by mkinawy** [comment]
Shouldn't this be closed by now? #6057
