### ISSUE TITLE
Hide MediaLibraryPicker fields

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/Orchard#5993]
In Dashboard or admin panel, How we can hide MediaLibraryPicker fields in Content Items List?
![image](https://cloud.githubusercontent.com/assets/13555275/10826982/8fedca80-7e81-11e5-9751-e8b9d993e07b.png)

**Comment by sebastienros** [comment]
You can update the Placement.info for this field targeting the SummaryAdmin. The default value should be in the Orchard.MediaLibrary folder, and you can also define the new value ("-") in the Admin theme.

You can also define it per field if you prefer.
