### ISSUE TITLE
Gallery downloads broken version of Onestop.SlideShows

### ISSUE THREAD

**Issue by vlatkost** [OrchardCMS/Orchard#5994]
When getting the Onestop.SlideShows Module from the Gallery on Orcahrd 1.9.2, an error occurs.

Error: ValueFactory attempted to access the Value property of this instance

When running the source code, the following error occurs:

Delegate 'Func' does not take 0 arguments.

I checked the parts that throw the error and on one place I saw this comment:
//TODO 1.9: verify that this works

So it seems an incomplete version gets pulled.

To fix this either replace the wrong lines:

SlideShowPartHandler.cs
- part.LazySlides.Loader(() => _slideShowService.GetSlidesFor(part).ToList());
to
part.LazySlides.Loader(x => _slideShowService.GetSlidesFor(part).ToList());

SlideShowFieldHandler.cs

-field.LazySlides.Loader(() => _contentManager.GetMany<SlidePart>(localField.SlideIds, VersionOptions.Published, QueryHints.Empty));
to
-field.LazySlides.Loader(x => _contentManager.GetMany<SlidePart>(localField.SlideIds, VersionOptions.Published, QueryHints.Empty));

OR

wait for the proper version to come from the Gallery.

Hope this helps someone out there and will be fixed by the team.

**Comment by sebastienros** [comment]
Issues in specific gallery modules have to be reported to their own repositories. Thanks.

**Comment by vlatkost** [comment]
A pointer would be nice. I could not find where to comment on that particular module :(
