### ISSUE TITLE
Layout Editor ElementController behavior appears incorrect

### ISSUE THREAD

**Issue by harmony7** [OrchardCMS/Orchard#5995]
I've noticed that ElementController, in its `Update()` method, goes to `Request.Form.ToDictionary()` to initialize the Data dictionary.

Update():

            var elementData = ElementDataHelper.Deserialize(sessionState.ElementData);
            var data = Request.Form.ToDictionary();
            var element = _elementManager.ActivateElement(descriptor, e => e.Data = data);
            var context = CreateEditorContext(session, describeContext.Content, element, postedElementData: data, elementData: elementData, updater: this);
            var editorResult = _elementManager.UpdateEditor(context);

For comparison, Edit():

            var data = elementData.Combine(ElementDataHelper.Deserialize(sessionState.ElementEditorData));
            var element = _elementManager.ActivateElement(descriptor, e => e.Data = data);
            var context = CreateEditorContext(session, describeContext.Content, element, postedElementData: data, elementData: elementData);
            var editorResult = _elementManager.BuildEditor(context);

I feel that going to `Request.Form` is incorrect, especially for the purpose of simply saving it into the Data dictionary.

1. Updating the element with submitted data is supposed to happen in the Element driver's `UpdateEditor()` method when `context.Updater != null` (and you have many examples of this in your code too). This gives control over which fields to transfer from the submitted data into the element (or viewModel).
2. There is no guarantee that the `Request.Form` is going to have fields that are compatible with the Element. For example, I often write view models to pass to the EditorTemplate, rather than directly pass the Element to the EditorTemplate.

            var viewModel = new MyElementEditorViewModel();
            /* fill in viewModel based on Element data */
            // e.g.
            viewModel.Field1 = element.Value1;

            if (context.Updater != null) {
                context.Updater.TryUpdateModel(viewModel, context.Prefix, null, null);
                /* update Element based on viewModel */
                // e.g.
                element.Value1 = viewModel.Field1;
            }
     
            var editor = context.ShapeFactory.EditorTemplate(TemplateName: "Elements/TemplateName", Model: viewModel);
            return Editor(context, editor);

I want to suggest that the correct behavior in `Update()` is to initialize Data by using `ElementDataViewModel.ElementData` instead of `Request.Form`. In turn, the actual updating of the element will be performed in the `if (context.Updater != null)` branch of the ElementDriver.

What do you guys think?

**Comment by harmony7** [comment]
I found another problem, that's that ElementController modifies ValueProvider when it creates the EditorContext.

I've made some changes that appear to work for me, so I'll make a PR.

**Comment by sfmskywalker** [comment]
I can't recall the exact details, but there was a reason the `ValueProvider` was being modified with existing values from the element, and it had something to do with a certain scenarios where the element's editor UI would not be rendered, yet its Update method was called, or something along those lines. However, your proposal does make things more "natural", so what I propose we do is merge in your PR and see how it works. I'm currently doing some Layouts development anyway, so if there are any issues I'll most likely spot them soon enough (and ask you to fix them ;))

Thanks for spotting this.
