### ISSUE TITLE
Layout Element Blueprint definition doesn't get exported.

### ISSUE THREAD

**Issue by headchannelgit** [OrchardCMS/Orchard#5996]
While exporting layout parts all elements of a layout gets exported, including these which come form element blueprints. Element blueprints allow easy sharing of common pieces of layout, though their definitions are not exported, so it is difficult to synchronise multiple instances of Orchard and take advantage of that kind of layout. Could this be implemented?

**Comment by sfmskywalker** [comment]
That's already implemented. Make sure to check the **Custom Elements** checkbox on the Export screen. Admittedly, not the most intuitive name to export "element blueprints".
