### ISSUE TITLE
Wrap Orchard.Layouts Grid in extra div

### ISSUE THREAD

**Issue by davegardner** [OrchardCMS/Orchard#5999]
In order to be able to sustain a full-width banded background layout, while using Bootstrap containers in Layouts, you need to be able to wrap the existing 'grid' div in an outer div to which you can apply styling.

A very simple solution for doing this is to modify the Elements.Grid.cshtml file so it generates the extra div and applies attributes to it, while preserving the inner div for the grid container. For example:

```
@using Orchard.DisplayManagement.Shapes
@using Orchard.Layouts.Helpers
@{
    var tagBuilder = TagBuilderExtensions.AddCommonElementAttributes(new OrchardTagBuilder("div"), Model);
    var isEmpty = tagBuilder.Attributes.Count == 0;
}

@if(!isEmpty){
    <text>@tagBuilder.StartElement</text>
}
<div class="container">
    @DisplayChildren(Model)
</div>
@if(!isEmpty){
     <text>@tagBuilder.EndElement</text>
}
```

**Comment by bleroy** [comment]
You can have an override for the template in your theme: the base templates are not designed for Bootstrap in particular.

**Comment by davegardner** [comment]
This mod is now standard in the Cascade.Bootstrap theme.
