### ISSUE TITLE
Registering inline styles in views

### ISSUE THREAD

**Issue by leventesen** [OrchardCMS/Orchard#6003]
Isn't there a Style.Head() function for registering styles in views?
This code works but its a hack.

```
@using(Script.Head())
{
    <style>
        body {
            background: #379;
        }
    </style>
}
```

Also this code replicates when the view is called more than once.

**Comment by sebastienros** [comment]
Nope, that is the only way, and not a hack. You can also target the Layout.Head zone like this: 

```
Layout.Head.Add(New.YourShape());
```

**Comment by sfmskywalker** [comment]
Or even:

```C#
@using(Capture(Layout.Head)){
<style>
        body {
            background: #379;
        }
    </style>
}
```

Which is nicer as you don;t have to create a separate shape.
