### ISSUE TITLE
Bug in MediaLibrary on multiple images upload since version 1.9.1

### ISSUE THREAD

**Issue by fbardet** [OrchardCMS/Orchard#6004]
Hello,

I found a bug in the MediaLibrary on multiple images upload since version 1.9.1.
This bug do not exist in version 1.8.2.

To reproduce the bug, follow these steps :
1 - get the file sources Orchard-1.9.2.zip,
2 - compile the solution on visual studio (vs 2013 update 5 in this case) and run the installation on IIS Express and Chrome,
3 - create the folder "Images" in the Media Library,
4 - upload 5 images in this folder => it's OK,
5 - remove these images,
6 - clear all browser data from cache,
7 - upload 5 images in this folder => it's OK,
8 - remove these images,
9 - enable Lucene module,
10 - clear all browser data from cache,
11 - upload 5 images in this folder => the process fails (1 or 2 images are correctly uploaded but not every images)
in the chrome console : http://localhost:30321/OrchardLocal/Orchard.MediaLibrary/ClientStorage/Upload Failed to load resource: the server responded with a status of 500 (Internal Server Error)
or http://localhost:30321/Admin/Orchard.MediaLibrary/MediaItem/undefined?displayType=Thumbnail 500 (Internal Server Error) with in log "The parameters dictionary contains a null entry for parameter 'id' of non-nullable type 'System.Int32' for method 'System.Web.Mvc.ActionResult MediaItem(Int32, System.String)' in 'Orchard.MediaLibrary.Controllers.AdminController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter."

When i disable and enable Lucene or Media Library modules, the multiple images upload become ok again. But after the browser data clean, the process fails again.
If the upload is only for one image, it'ok.

Could you reproduce this error ?

Best regards

**Comment by urbanit** [comment]
Have you enabled "Media Library Search" module? Or, indexing any MediaLibrary field?

**Comment by fbardet** [comment]
Hello,

No, I just enable the Lucene module without any other action and after clean the cache of my browser.

**Comment by sebastienros** [comment]
I couldn't repro it with 1.9.x
