### ISSUE TITLE
database column named 'Group' causes problems

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/Orchard#6008]
I have not had time to really check this out yet, but I wanted to just post a quick issue in case this is not a known problem. I added a column to a table named group and this caused errors when using IRepository Fetch to get items from the table. This could be a rule that some keywords cannot be used as column names, I remember access having this same restriction. If it is a restriction then I would like to get a list of the restricted names for documentation.

**Comment by sfmskywalker** [comment]
this one bit me a s well. I didn't investigate further, but I assume SQL keywords (like `group`) are reserved keywords. Perhaps this can be solved by having the schema builder surround the reserved words with square brackets, or some solution along those lines. If, of course, this is the issue.

**Comment by Piedone** [comment]
I think you bumped into this: http://english.orchardproject.hu/blog/a-harsh-reminder-that-you-can-t-forget-what-s-below-the-abstraction

The issue with using SQL keywords as column names arises not when tables are created but rather when queried. So if we want to do something with this then querying should be changed. I guess something is already in NHibernate to solve this for us: http://stackoverflow.com/a/8733843/220230 and http://stackoverflow.com/a/15341167/220230

**Comment by sebastienros** [comment]
That's a bug in NHibernate, it is the only component to deal with IRepository. You can also try with the `Version` column which is even more scary, as it will incremement the value automatically at each update.

**Comment by Piedone** [comment]
@sebastienros why is this a bug in NHibernate? It seems to me that rather there is a feature in NHibernate to prevent this that we don't use.

**Comment by sebastienros** [comment]
By the way the question is explained, it seemed obvious to me that the query is done in a pure IRepository.Fetch, which is handled in its whole by NHibernate, it's not something we write, or if it's not NHibernate then the db, which I doubt. Feel free to create a sample test to validate it.
