### ISSUE TITLE
gulp rebuild changes files

### ISSUE THREAD

**Issue by qt1** [OrchardCMS/Orchard#6016]
1. git clone 1.9.2

2. running gulp from command line results in "Local gulp not found in S:\tmp\orchard\src"
running "npm install" seems to solve the issue however, IMHO There should  be instructions to properly set up the toolchain..

3. Running "gulp rebuild" results in multiple errors messages e.g. 
[01:31:17] Using gulpfile S:\tmp\orchard\src\Gulpfile.js
[01:31:17] Starting 'rebuild'...
Orchard.Web\Modules\Orchard.Azure.MediaServices\Assets\TypeScript\cloudmedia-admin-common.ts(8,26): error TS2345: Argument of type 'JQuery' is not assignable to parameter of type 'string'.
[01:31:27] Plumber found unhandled error:
 TypeScript error: Orchard.Web\Modules\Orchard.Azure.MediaServices\Assets\TypeScript\cloudmedia-admin-common.ts(8,26): error TS2345: Argument of type 'JQuery' is not assignable to parameter of type 'string'.
Orchard.Web\Modules\Orchard.Azure.MediaServices\Assets\TypeScript\cloudmedia-admin-settings.ts(92,13): error TS2345: Argument of type '{ activate: () => void; active: any; }' is not assignable to parameter of type 'TabsOptions'.
  Object literal may only specify known properties, and 'activate' does not exist in type 'TabsOptions'.

4. After running "gulp rebuild" there are changes in many files, mostly in line ending "\n" vs "\n\r" which irritate git

**Comment by DanielStolt** [comment]
This has been fixed in `dev` by adding end-of-line character normalization to the Gulp pipeline.

**Comment by ssinno28** [comment]
when will this fixed be merged into master?
