### ISSUE TITLE
Taxonomy Widget issue

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#6017]
thanks for your time .. I guess I'm having (again) a blackout!

PS:I use Taxonomies e.g. in 1.8.1 without any problems.

I'm using a newly downloaded Orchard 1.9.2 via Github.
I'm able, after some module enabling, to define some taxonomy Parent/child terms

Now I would like to create  a Taxonomy Widget:

a) surprise: I don't have a taxonomy widget shown in the list? Shouldn't that widget already be in the list?
b) therefore I went and added in the Taxonomy CI Stereotype: Widget. After that I had a Taxonomy Widget in the widget list.
(as said I always thought the widget should be in the list by default!?)
c) now when I call that widget I get an ... oops ... error like:

Oops. Something went wrong ... sorry
An unhandled exception has occurred and the request was terminated.
Please refresh the page. If the error persists, go back
Specified cast is not valid.
System.InvalidCastException: Specified cast is not valid. at Orchard.ContentManagement.ContentCreateExtensions.New[T](IContentManager manager, String contentType) in z:\Builds\work\9f6cd39ff0f68f41
etc......

This must be a misunderstanding on my side I CAN'T imagine that the Taxonomies module is failing ..
Thanks for any help
ed

**Comment by sfmskywalker** [comment]
Hi Ed, the Taxonomy Widget has been removed in favor of the Taxonomy Link (menu item). Check out these posts:

http://orchard.codeplex.com/discussions/643884
https://orchard.codeplex.com/discussions/568386
https://orchardtaxonomies.codeplex.com/discussions/441158

**Comment by edikaufmann** [comment]
that clarifies everything, thanks a lot, ed
