### ISSUE TITLE
Support for jQuery v2.1.4

### ISSUE THREAD

**Issue by leventesen** [OrchardCMS/Orchard#6018]
Will Orchard.jQuery module support jQuery v2.1.4?

**Comment by sebastienros** [comment]
Yes, but only for a major release like 1.x, hence I assigned it to the dev milestone.

We can however bump the current version to the latest of jQuery 1.

**Comment by leventesen** [comment]
Sorry, I couldn't understand correctly. Did you mean v2.1.x  or v1.x ?

**Comment by infofromca** [comment]
@leventesen @sebastienros fixed in 1.10

**Comment by jbuck79** [comment]
Is there any specific reason to use the 2.x version of jQuery? My Orchard site needs to support older versions of IE, which aren't supported by jQuery 2.x. I know that IE 8 and below are pretty old now, but a lot of organizations still need to support them.

I managed to hack something together by defining my own jQuery resource pointing to the 1.x version and setting the version to 3.0 in the declaration. Now, when I require jQuery or set it as a dependency of another script, it pulls the 1.x version. I haven't noticed anything breaking with the 1.x version.

My opinion is that as long as the site doesn't need 2.x, it should be using 1.x.

**Comment by sebastienros** [comment]
We include 2.x version, but every theme can use there own resource. We don't support such old browsers from the admin.
