### ISSUE TITLE
themes inheritance problem

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6024]
i have a theme guang.bootstrapbase which is based on a bootstrap theme.
i have another theme guang.selfInc which is base on guang.bootstrapbase.
set current for guang.selfInc , good.
set current for guang.bootstrapbase, good.
set current for guang.bootstrapbase,then disable guang.selfInc. error showed  Orchard.OrchardException: Shape type guang_thumbsup not found.
but actually guang_thumbsup.cshtml is inside guang.bootstrapbase project
![theme-1](https://cloud.githubusercontent.com/assets/297675/11066876/f5012114-8797-11e5-9642-610cbc8ac6e7.png)
![theme-2](https://cloud.githubusercontent.com/assets/297675/11066877/f502f944-8797-11e5-91a4-61ad938822fd.png)
![theme-3](https://cloud.githubusercontent.com/assets/297675/11066881/f505291c-8797-11e5-96a2-7c92cc8b4407.png)
![theme-4](https://cloud.githubusercontent.com/assets/297675/11066878/f5034a66-8797-11e5-8f4e-d22ae1a31276.png)
![theme-5](https://cloud.githubusercontent.com/assets/297675/11066880/f50438d6-8797-11e5-8ae5-5eb2081e831e.png)
![theme-6](https://cloud.githubusercontent.com/assets/297675/11066879/f5043624-8797-11e5-8cc9-338a15275926.png)
![theme-7](https://cloud.githubusercontent.com/assets/297675/11066882/f50ba35a-8797-11e5-9363-ccfaf56e9131.png)

**Comment by sebastienros** [comment]
I assume you are using 1.8.1?

**Comment by infofromca** [comment]
no, i  use latest dev

**Comment by infofromca** [comment]
the same thing happened when i enabled CONTENT PICKER feature
use version
4573f65c19ac6aaef1a609c0e2fa38cd954860c6

**Comment by infofromca** [comment]
fixed (by 0e1cca0fce31195b638c2ee2e0ffceaeb0168d9a, i think)
so close it
