### ISSUE TITLE
Tenant with virtual root should be handled consistently

### ISSUE THREAD

**Issue by mattcowen** [OrchardCMS/Orchard#6027]
If you create a tenant with a URL prefix of "mysite" then in Settings of this newly created site the base url field has http://example.com/mysite but the URL in a number of places has a duplicated root folder in the URL.

1. in the "click here" URL in the forgotten password email
2. in the New page view, the url has mysite/mysite/...

By updating the base URL to not have the virtual root you resolve this however, this probably has unintended consequences as that is not the correct base URL

**Comment by mattcowen** [comment]
BTW tested only on 1.9.x

**Comment by sebastienros** [comment]
You are right, the base url should not have the prefix in it when it's generated.

**Comment by sebastienros** [comment]
I could not repro it. I created two tenants with prefix, one without a host and one with a host. Both times the BaseUrl in Settings was correct.
