### ISSUE TITLE
Shape element of layout problem in latest dev

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6035]
it happens between    adc92fb1b4fe59d00889f3017763f4bdd2132408 and  4573f65c19ac6aaef1a609c0e2fa38cd954860c6

create new page,
drag the SHAPE from LAYOUT =>SNIPPETS,
in the popup text box , enter the name of shape
save, does not work.
(if you use the same steps to edit, you can not see the shape name which was already there.)

now i have to use version adc92fb1b4fe59d00889f3017763f4bdd2132408

**Comment by harmony7** [comment]
This might be one of things that "broke" due to fixing #5995. I'll take a look when I have some time.

**Comment by sfmskywalker** [comment]
Fixed in changeset 8693b68ac7ed899e1655e488af7e2d32ea7a76bc.
