### ISSUE TITLE
Why create intermediateScope 

### ISSUE THREAD

**Issue by dragonsky18** [OrchardCMS/Orchard#6038]
Hi all,
  
   When I read ShellContainerFactory. class ,  I cannot understand blew code,

    ShellContainerFactory.CreateContainer(ShellSettings settings, ShellBlueprint blueprint) 
   {
       var intermediateScope = _lifetimeScope.BeginLifetimeScope(
                builder => {
                    foreach (var item in blueprint.Dependencies.Where(t => typeof(IModule).IsAssignableFrom(t.Type))) {
                        var registration = RegisterType(builder, item)
                            .Keyed<IModule>(item.Type)
                            .InstancePerDependency();

       intermediateScope.BeginLifetimeScope(
                "shell",
                builder => {

   } 

  question : why create a intermediateScope  and register Imodule as InstancePerDependency? 
                  why orchard create 'shell" scope under the intermediate scope?

  Thanks in advance.
  Mark

**Comment by Piedone** [comment]
Please ask questions on the discussion board: http://orchard.codeplex.com/discussions

BTW my guess would be that IModules are instantiated once ever so it doesn't really matter whether they're InstancePerDependency or not.
