### ISSUE TITLE
 can not see sub theme icon

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6039]
because any path to sub theme are 500
![sub-theme](https://cloud.githubusercontent.com/assets/297675/11180778/689b3d34-8c2b-11e5-8c05-10b9a7ed5b15.png)

**Comment by infofromca** [comment]
#5675

**Comment by infofromca** [comment]
fixed in 1,10

**Comment by Thierry-S** [comment]
see my comment in #5675 about multiple web.config in subfolder Scripts, Styles and Content and `<add name="StaticFile"` which is causing the 500 error. Adding `<remove name="StaticFile"/>` above each fixes this issue, but themes like TheThemeMachine are not affected and I don't know why.
