### ISSUE TITLE
Redis Business Data Caching Limitations

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/Orchard#6045]
I actually don't know if the Redis Business Data Caching can be "fixed" but here are a couple:

Because the data needs to be converted to Json (as I understand it) if you try to cache any class with a LocalizedString you will receive an error like this:

```
Unable to find a constructor to use for type Orchard.Localization.LocalizedString. 
A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. 
Path '[0].Text.Scope', line 1, position 18.
```

When you dig into this it is because the LocalizedString does not meet those requirements. You can go in and add the JsonConstructor attribute (guessing on this one) and it will at least take care of that one:

```
[JsonConstructor]
public LocalizedString(string languageNeutral) {
    _localized = languageNeutral;
    _textHint = languageNeutral;
}
```

The other issue I have run into I don't think can be overcome. If you go to cache a class that uses IContent (or any other interface) you will not be able to, Interfaces are not allowed.

So, should these be permanently understood as limitations on the Redis Business Data Caching? If so, fine, but throwing it out here to see if there are ways around these limitations. Obviously the Redis Business Data Caching will work fine for "simple" models.

**Update Note**
Oh, for what it is worth, the native (in memory) Orchard.Caching does handle the above scenarios. However, perhaps it shouldn't and the argument should be made to simplify the caching :)

**Comment by sebastienros** [comment]
Maybe we should not use JsonSerializer for this, but something more RAW that would work with more types

**Comment by sebastienros** [comment]
You can also serialize it as a string by yourself, or byte[] and then Json would not complain

**Comment by jeffolmstead** [comment]
Yeah, I am torn on this one. I can easily serialize this one instance but it will cause doubt on my mind on where the "error" might creep in later (for example, applying the module onto older websites and not being able to assume it just works). Is there another serializer that could work as well? Would be glad to tweak my local instance of the module and see how it works out and get back to you.

**Comment by sebastienros** [comment]
The recommendation is to always use a DTO to do such things. Like for a database.

**Comment by jeffolmstead** [comment]
I just want to make sure I am understanding the direction here. As I read it, there is no plans to change the serializer away from JsonSerializer but instead each developer needs to use a DTO (e.g. simpler models that can be serialized easily). It is fine either way, I just want to make sure I am planning correctly.
