### ISSUE TITLE
Clicking submit button in layout part causes post-back that loses unsaved progress

### ISSUE THREAD

**Issue by mattcowen** [OrchardCMS/Orchard#6046]
Merged the latest 1.9.x and then went to create a Form. Added 6 text fields and hooked them up with content type bindings. When I had finished I went to move the submit button. I accidentally clicked the button and a postback was generated that caused a page refresh and wiped the form.

The button should not cause a postback when rendered in the layout part.

**Comment by unzipme** [comment]
+1

**Comment by rtpHarry** [comment]
I just noticed this issue, I've been working on a similar solution on #5707

**Comment by rtpHarry** [comment]
closing this as a duplicate of #5707 as they are both open and that one catches more html form elements than this attempt
