### ISSUE TITLE
Exception in MediaPart (and dependencies between Content Parts)

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#6047]
One of the pupils of our Orchard course bumped into this problem (which made the whole front-end unavailable) recently: an Image was displayed in the Header zone (so it displayed everywhere on the frontend), but he accidentally removed TitlePart from the Image Content Type causing an YSOD on any page load. The Media Library module depends on TitlePart of course, but this relation has a deeper meaning, since MediaPart.Title directly accesses TitlePart.Title, thus removing TitlePart in the type definition editor leads to that type being unusable.

The affected code in this case is:

``` csharp
/// Gets or sets the title of the media.
/// </summary>
public string Title {
    get { return ContentItem.As<TitlePart>().Title; }
    set { ContentItem.As<TitlePart>().Title = value; }
}
```

I see currently two ways to approach this (they are not mutually exclusive):
- Add some mechanism (safeguard) for Content Type definitions if changes would endanger application health. These could be discovered by checking dependencies between the features the affected Content Parts/Types declared in.
- Coding convention: don't assume that another Content Part is attached on the Content Type and avoid directly depending on another Content Part (or at least add checks), so the "get" should rather look like this:

``` csharp
get { return ContentItem.Has<ITitleAspect>() ? ContentItem.As<ITitleAspect>().Title : ""; }
```

What do you think?

**Comment by Piedone** [comment]
I'd go with suggestion number 2.

Related: #4792.

**Comment by sfmskywalker** [comment]
Suggestion number 2 makes sense.

**Comment by bleroy** [comment]
Number 2 has always been the recommendation in fact. Developers should never assume that a part is going to be there (even Common), and have a downgrade path available. I'm sure there are quite a few cases where the guideline is not followed however...

**Comment by sebastienros** [comment]
Suggestion 3: Use an activating filter to add the TitlePart to it.

**Comment by sebastienros** [comment]
Please take a look at whether we can remove the TitlePart dependency from the code, then keep it as a metadata.

**Comment by BenedekFarkas** [comment]
I'd prefer solution number 3 (ActivatingFilter), so you can configure whether you want to display the title or override, just like other types.
