### ISSUE TITLE
Creating a new Image Profile pre-caches a negative result

### ISSUE THREAD

**Issue by flew2bits** [OrchardCMS/Orchard#6051]
When a new image profile is created, the ImageProfilePartDriver calls the GetImageProfileByName method in the ImageProfileService to find out if a profile already exists by the given name. GetImageProfileByName uses the cache manager to find a result; if a result isn't cached, the acquire method performs a query to find a matching ImageProfilePartRecord in the database, and, if it doesn't, caches a result of -1 as the ID for the new profile. Since the result is -1, the ImageProfilePart returned is null, and the creation is allowed to continue. However, when trying to use that profile later in Display.MediaProfile, that negative result is still cached, so the profile is not returned from GetImageProfileByName. Eventually, I believe the cache expires, and things start working, but it takes some time.

This is the patch that seems to have caused this issue; it looks like it's been around awhile: https://github.com/OrchardCMS/Orchard/commit/42ab42e6e238d753d8dab5d3cd4667488817f0b8

**Comment by sebastienros** [comment]
We need to use `ISignal` to invalidate this cache entry when the item is actually created (not when it's modified).

**Comment by flew2bits** [comment]
I'm not sure if this is the best way to do it, but it works. In ImageProfileService.GetImageProfileByName I changed the first line to:
```c#
var profileId = _cacheManager.Get("ProfileId_" + name, ctx => {
    ctx.Monitor(_signals.When("MediaProcessing_Published_" + name));
    var profile = _contentManager.Query<ImageProfilePart, ImageProfilePartRecord>()
        .Where(x => x.Name == name)
        .Slice(0, 1)
        .FirstOrDefault();
```

Then I modified the handler as such:
```c#
public ImageProfilePartHandler(IRepository<ImageProfilePartRecord> repository, ISignals signals) {
    Filters.Add(StorageFilter.For(repository));
    OnPublished<ImageProfilePart>((context, part) => signals.Trigger("MediaProcessing_Published_" + part.Name));
}
```

**Comment by sebastienros** [comment]
This is exactly how to do it. Please try that it fixed the issue for you and submit a PR.

You could also override OnPublished() instead so that the constructor of the handler doesn't invoke unnecessary code.
