### ISSUE TITLE
@Href() Should Not Mess with http:// or https:// urls

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/Orchard#6052]
I have run into instances where we use azure blob storage for our media. In these scenarios, the file URL's start with https://. In some modules URL's are rendered using code like this:
```
<img src="@Href(imageUrl)" alt="@title"
```
This seems like a good technique but it causes issues in getting an error like this:
```
System.Web.HttpException (0x80004005): 'https:/{name}.blob.core.windows.net:443/media
```
Note the https:/ only has one slash so this ends up throwing an error. This being the case, I do not feel every module should be changed but that Orchard\Mvc\ViewEngines\Razor\WebViewPage.cs Href method should be changed to something like this:
```
public override string Href(string path, params object[] pathParts) {
    if (path.ToLowerInvariant().StartsWith("http://") || path.ToLowerInvariant().StartsWith("https://")) {
        return path;
    }
    // continue on with existing code...
```
This way the Href method just does not process absolute URLs.

**Comment by sebastienros** [comment]
I want to see some code calling image urls with href in Orchard's modules. We'd need to fix it.

But I agree that your fix is valid. Please use `StartsWith( ..., OrdinalIgnoreCase)`

**Comment by jeffolmstead** [comment]
I don't know of a native usage of @Href inside img src, the example above stems from Nwazet.Commerce module. Will see if I can get a pull request in and reference this issue.

**Comment by mkinawy** [comment]
I thought writing "fixes #+++" in the PR would close the issue automatically when that PR gets merged, as described here: http://docs.orchardproject.net/Documentation/Contributing-patches
am I wrong?

**Comment by jeffolmstead** [comment]
@mkinawy thanks much for pushing that PR through! I am closing the issue as you resolved it completely and am just wondering if it didn't auto-close because I was the author instead of your name, hopefully someone else can chime in and let us know. Thanks again.
