### ISSUE TITLE
Allow user to place menu item when creating or editing a page

### ISSUE THREAD

**Issue by mattcowen** [OrchardCMS/Orchard#6064]
I've been working on a change to the menu part to allow for the user to specify the parent menu item when editing or creating a page. This reduces the need of the navigation view to position the menu item in the right level.

I can imagine it is a module at the very least but I wondered if anyone thought it could be useful being rolled into the core.

Here is a demo http://screencast.com/t/lYXZaSJa8E.

N.B. The dropdown of menu entries will be updated as the menu selected changes.

**Comment by Piedone** [comment]
This looks fine by me to be included into the Core. However probably we had some discussion about removing this feature completely and just letting users use the menu editor under Navigation?

**Comment by mattcowen** [comment]
Thanks for the feedback. Unless @sebastienros disagrees, I shall submit a PR to the dev branch. I've done the work so might as well add it.

**Comment by sfmskywalker** [comment]
Thanks for providing a screencast, quite helpful! It looks good to me. If we want to keep the feature, I think we should include this as well so that we don't have to go to the navigation menu to position it. I'm not sure we should remove this feature entirely, because it is quite convenient to be able to add content items to the menu like this. Perhaps we could not add the `MenuPart` to the `Page` type by default (effectively removing the feature).

Unless someone has strong objections, I suggest we include Matt's work.

**Comment by mattcowen** [comment]
@sebastienros please could review and advise. Thanks

**Comment by mattcowen** [comment]
@Piedone @sfmskywalker @sebastienros  sorry to bother you guys but is anyone able to advise whether this can be accepted please? This feature is something my users would like so I need to know whether or not it can be included so I can proceed as necessary. Thanks

**Comment by sfmskywalker** [comment]
I think we want it, but let me confirm.

**Comment by sebastienros** [comment]
This looks cool but we actually wanted to get rid of this part as it is a huge perf issue. Creating menu items like this will make the content item a menu item, so rendering the menu will load the content item itself. We usually recommend to use Custom Links instead. Or maybe if you could also change the feature to create custom links that would be great. But you would also need to intercept when the autoroute is changed, to update the link in the menu. And it can only work for items with autoroute, or you couldn't detect that the link has changed, I assume this is fine.

**Comment by mattcowen** [comment]
Ok, that's an interesting point about the perf issue. Let me revisit this and look into those requirements around generating custom links and I will try and come back to you. Thanks all
