### ISSUE TITLE
port diff for permalink

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6066]
i actually used 30381
it gave me 30321 which made " View "  giving not found page
![port-diff](https://cloud.githubusercontent.com/assets/297675/11324904/0c314a98-910d-11e5-8ee0-22f694bc4b8e.png)

**Comment by mkinawy** [comment]
Have you changed the base url setting to use that new port?
You could find it here *the red arrow*

 ![image](http://content.screencast.com/users/mkinawy/folders/Jing/media/452527ab-b56d-4e30-b692-4a95baaf0187/2015-11-22_1928.png)

**Comment by infofromca** [comment]
yes, after change port on that setting, resolved it
