### ISSUE TITLE
In Widgets management, the concept of default layer should be replaced by a more fexible implementation

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6081]
It would be better if we could select the layers where a widget will be present, the default layer would be the 'all layers' case.
This is a more fexible concept, today either we have a wizard by layer, either it is on all layers. If we want it on 2 layers as for exemple in Blog List layers and in Blog Layer, we have to replicate it.

**Comment by sfmskywalker** [comment]
By "wizard", do you mean "widget"?

> If we want it on 2 layers as for exemple in Blog List layers and in Blog Layer, we have to replicate it.

You wouldn't have to replicate the widget, but you would have to introduce a new layer with a layer rule that matches both Blog and Blog Post pages for example.

So the flexibility is already there, but it does sound nice to be able to assign a widget to multiple layers without having to create potentially complex layer rules to have a widget appear on multiple layers.

**Comment by CSurieux** [comment]
Yes  Widget, I fixed it thanks.

yes I know we can edit the rules, but creating common rules for layers is not always easy and sometime there are no obvious solutions, may be no solutions at all.

**Comment by CSurieux** [comment]
If no opposition I could bring a PR next month.
