### ISSUE TITLE
It should exist a Summary editor for each part with formatted data content

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6083]
BodyPart for exemple, but also LayoutPart.
This Summary edited data should be automatically used, if present, by all the default xxx.Summary.cshtml templates.

The actual default action for summary views is to truncate in the less dangerous place, not always good results when you are not blind and if an image is present, you can't keep it.

Yes I know that it is easy to add a second editable part to each contentitem where I need a summary view and redefine all my summary view to look if this part exists in the contentitem and use it in place of the blind truncate.

We could have an internal process for body part to input full text and summary text in the same dit session (maybe some tab to access summary). Same for other parts with formated input.

I am sure I am not the only.

Ideally we could input as many values as display types used.

**Comment by bleroy** [comment]
Different people want different mechanisms for their summaries, of which you mention a few. I use the WordPress convention of including a `<!--more-->` cutting mark in the body where I want the summary to end: https://weblogs.asp.net/bleroy/my-body-summary-template-for-orchard

**Comment by CSurieux** [comment]
Astucieux, but different from writing a summary.

**Comment by bleroy** [comment]
You've mentioned the other valid solution for writing a summary. It's not clear what you're asking for.

**Comment by CSurieux** [comment]
Yes I discovered that Orchard itself is not clear, si I adapt to the env. Great but not clear.

Envoyé à partir de mon sanyo phc 25
________________________________
De : Bertrand Le Roy<mailto:notifications@github.com>
Envoyé : ‎27/‎11/‎2015 09:50
À : OrchardCMS/Orchard<mailto:Orchard@noreply.github.com>
Cc : CSurieux<mailto:christian.surieux@hotmail.fr>
Objet : Re: [Orchard] It should exist a Summary editor for each part with formatted data content (#6083)

You've mentioned the other valid solution for writing a summary. It's not clear what you're asking for.

---

**Comment by CSurieux** [comment]
Another option could be to have a TextSummary string property added in the bodyPart.

I could create a BodyExPart but it means replacing the BodyPart in all the contentitems where Orchard or my own devs are using it. And BodyPart is in Core so I expect a lot of difficulties and not friendly code as replacing some dependencies ?
It would be easier to add  the new property in the xisting BodyPart and adapt is drivers/templates.
