### ISSUE TITLE
Projection element not saving any settings

### ISSUE THREAD

**Issue by Xeevis** [OrchardCMS/Orchard#6100]
On `dev` projection element stopped working, when added anywhere into layout canvas it simply won't save any settings so it doesn't work at all. However projection content type still works well.

**Comment by Xeevis** [comment]
Dynamic form elements are also affected by this.

**Comment by jtkech** [comment]
@Xeevis there is a pending PR #6042 that would need to be applied, @harmony7 and @sfmskywalker are working on this. Also see my last comment in this PR for a temporary workaround I needed to apply to get it working...

Best
