### ISSUE TITLE
Enumeration field on Dynamic Form should allow empty elements for validation

### ISSUE THREAD

**Issue by mattcowen** [OrchardCMS/Orchard#6123]
If you add an Enumeration field to a form and then have an empty row as the first option, the empty row is trimmed out. It would be nice if an empty option was possible so it could be validated as an incomplete mandatory field.

**Comment by jonvee** [comment]
This still seems to be an issue... Are there any suggested workarounds or docs explaining how to create a validation workflow similar to "Verify User Unicity" if this needs to be handled server-side?

**Comment by I3undy** [comment]
If you leave the value empty, it will be handled as if you didn't choose any of the options, and it will be validated as an incomplete mandatory field.

> Please select a language:
> Cantonese
> Mandarin

Orchard version: 1.10.1.0

**Comment by mwentz** [comment]
To build on what @I3undy is saying, if you want to have an empty row at the top you can just use a colon in the first line. It will look like this in the admin screen:

```
:
First Option
Second Option
```
I think this is working as intended.

**Comment by sfmskywalker** [comment]
@mwentz and @I3undy are right.
