### ISSUE TITLE
OutputCacheFilter locking

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#6126]
@DanielStolt 

How isn't this code always executed even when the `CaptureStream` is not yet done?
```
            finally {
                // If the response filter stream capture handler was attached then we'll trust
                // it to release the cache key lock at some point in the future when the stream
                // is flushed; otherwise we'll make sure we'll release it here.
                if (!captureHandlerIsAttached)
                    ReleaseCacheKeyLock();
            }
```

As the even handler is assigned, the code will continue running to this statement, so the `Monitor` will be released before the content is processed and added to the cache.

I have changed it locally to be executed in a `Dispose` call instead, as a safe call if Capture was not correctly releasing the lock.

**Comment by DanielStolt** [comment]
I don't follow your logic here. The `ReleaseCacheKeyLock()` is only called if the caputer handler was *not* attached. If it was attached, it is assumed to be the handler's responsibility to release the lock at a later time. Just like the comment says. What am I missing?

**Comment by sebastienros** [comment]
Will continue this one on the PR
