### ISSUE TITLE
packaged Modules do not install in Azure versions

### ISSUE THREAD

**Issue by dpalfery** [OrchardCMS/Orchard#6128]
http://thesoftwarepractice.net/development/orchard-cms-module-listed-but-not-working. I am seeing this same issue.

**Comment by dcinzona** [comment]
Which module in particular is missing from Orchard.Azure.Web?  By the way, this is only an issue if you are using cloud services.  Web Apps can be deployed using the main Orchard.sln / Orchard.Web project.

**Comment by dpalfery** [comment]
a custom module. I can package it and deploy it to a local version of Orchard but when I upload it to my azure version of Orchard it never installs. No errors in the logs, nothing. At the very least if there is some other thing I have to do to get it to work in azure why would we swallow the error? Is the packaging procedure different for site running in Azure?

**Comment by dcinzona** [comment]
How are you deploying it to azure? Also, are you running orchard as an azure web app or cloud service?



On Dec 4, 2015, at 10:15 AM, David Palfery <notifications@github.com<mailto:notifications@github.com>> wrote:


a custom module. I can package it and deploy it to a local version of Orchard but when I upload it to my azure version of Orchard it never installs. No errors in the logs, nothing. At the very least if there is some other thing I have to do to get it to work in azure why would we swallow the error? Is the packaging procedure different for site running in Azure?

-

**Comment by dpalfery** [comment]
I am running as an azure web app with an azure database. I am running package create from the orchard command line and creating a nupkg file. then I upload that nupkg file to orchard through the admin module interface. I have also tried just ftp copy and paste of the source to the site. both have the same result, it says the feature is enabled but the migrations do not run and the feature does not deploy. not routes registered either

**Comment by sebastienros** [comment]
May you share the source for your module? At least the module.txt and Migration class?

**Comment by dpalfery** [comment]
I am trying to package and install this fork of the WebAdvanced.Sitemap https://github.com/douwinga/Orchard-SiteMap/commit/3708d3efdcd703e72b2bc9f792e531f3508e95c8
again this package deploys fine to an on premises dev farm

**Comment by dcinzona** [comment]
What does your deployed version of HostComponents.config look like?

**Comment by dpalfery** [comment]
<?xml version="1.0" encoding="utf-8"?>
<HostComponents>
    <Components>

        <Component Type="Orchard.Environment.Extensions.ExtensionMonitoringCoordinator">
            <Properties>
                
                <Property Name="Disabled" Value="false"/>
            </Properties>
        </Component>

        <Component Type="Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.PlacementFileParser">
            <Properties>
                
                <Property Name="DisableMonitoring" Value="true"/>
            </Properties>
        </Component>

        <Component Type="Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy">
            <Properties>
                
                <Property Name="DisableMonitoring" Value="true"/>
            </Properties>
        </Component>

        <Component Type="Orchard.Environment.Extensions.Folders.ExtensionHarvester">
            <Properties>
                
                <Property Name="DisableMonitoring" Value="false"/>
            </Properties>
        </Component>

        <Component Type="Orchard.Environment.Extensions.Compilers.DefaultProjectFileParser">
            <Properties>
                
                <Property Name="DisableMonitoring" Value="true"/>
            </Properties>
        </Component>

        <Component Type="Orchard.Environment.Extensions.Loaders.DynamicExtensionLoader">
            <Properties>
                
                <Property Name="DisableMonitoring" Value="true"/>
                
                <Property Name="Disabled" Value="false"/>
            </Properties>
        </Component>

        <Component Type="Orchard.Environment.Extensions.Loaders.PrecompiledExtensionLoader">
            <Properties>
                
                <Property Name="DisableMonitoring" Value="true"/>
            </Properties>
        </Component>

        <Component Type="Orchard.FileSystems.Dependencies.DefaultDependenciesFolder">
            <Properties>
                
                <Property Name="DisableMonitoring" Value="true"/>
            </Properties>
        </Component>

        <Component Type="Orchard.FileSystems.Dependencies.DefaultExtensionDependenciesManager">
            <Properties>
                
                <Property Name="DisableMonitoring" Value="true"/>
            </Properties>
        </Component>

        <Component Type="Orchard.Localization.Services.DefaultLocalizedStringManager">
            <Properties>
                
                <Property Name="DisableMonitoring" Value="true"/>
            </Properties>
        </Component>

        <Component Type="Orchard.Caching.DefaultParallelCacheContext">
            <Properties>
                
                <Property Name="Disabled" Value="false"/>
            </Properties>
        </Component>

        <Component Type="Orchard.Data.SessionConfigurationCache">
            <Properties>
                
                <Property Name="Disabled" Value="false"/>
            </Properties>
        </Component>
        
        <Component Type="Orchard.Environment.Descriptor.ShellDescriptorCache">
            <Properties>
                
                <Property Name="Disabled" Value="false"/>
            </Properties>
        </Component>

        <Component Type="Orchard.Services.ClientAddressAccessor">
            <Properties>
                
                <Property Name="EnableClientHostAddressHeader" Value="false"/>

                
                <Property Name="ClientHostAddressHeaderName" Value="X-Forwarded-For"/>
            </Properties>
        </Component>

        <Component Type="Orchard.Setup.Controllers.SetupController">
            <Properties>
                
                <Property Name="RecipeExecutionTimeout" Value="600"/>
            </Properties>
        </Component>

        <Component Type="Orchard.ImportExport.Providers.ImportActions.ExecuteRecipeAction">
            <Properties>
                
                <Property Name="RecipeExecutionTimeout" Value="600"/>
            </Properties>
        </Component>

    </Components>
</HostComponents>

**Comment by dcinzona** [comment]
Can you try changing the value here to false?  We monitor the bin/dll files in our modules so that updates are processed accordingly. 
```
<Component Type="Orchard.Environment.Extensions.Loaders.PrecompiledExtensionLoader">
        <Properties>
            <!-- Set Value="true" to disable pre-compiled files monitoring (~/Modules/**/bin/*.dll) -->
            <Property Name="DisableMonitoring" Value="true"/>
        </Properties>
    </Component>
```

**Comment by dpalfery** [comment]
Packaging/PackagingServices/InstallPackageDetails?redirectUrl=%2FAdmin%2FModules] Orchard.OrchardCoreException: Recipe execution with ID 36d50c9efb464808b6479628929418bc failed because the step 'Feature' failed to execute. The following exception was thrown: Could not enable feature 0 because it was not found. Refer to the error logs for more information. at Orchard.Recipes.Services.RecipeStepExecutor.ExecuteNextStep(String executionId) at Orchard.Recipes.Services.RecipeScheduler.ExecuteWork(String executionId) at Orchard.Events.DelegateHelper.<>c__DisplayClass14_0`2.<BuildAction>b__0(Object target, Object[] p) at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue)
this is what I am seeing in the logs now

**Comment by sebastienros** [comment]
If a restart doesn't fix it, changing the configuration wouldn't help.

**Comment by dcinzona** [comment]
True, I didn't see if he tried restarting the website on azure.

**Comment by dpalfery** [comment]
I have a little ritual each time I test it. Uninstall, restart azure, install, restart azure, enable restart azure

**Comment by sebastienros** [comment]
How do you know the migration is not running ? PS: Might want to continue the conversation on gitter. See home page for link.

**Comment by dpalfery** [comment]
The issue was with the open source module I was running. Once I turned logging to debug I could see that there was a dll missing. someone had a jetbrains reference in the project. removed that reference and it started working. Strange that it compiled on prem
