### ISSUE TITLE
Content item changes in OnUpdating ContentHandler not stored

### ISSUE THREAD

**Issue by dpomt** [OrchardCMS/Orchard#6135]
I want to geocoe a content items address each time the content item is saved e. g. via editing it via dashboard.
I added a class deriving from ContentHandler that implements OnUpdating.
Within that OnUpdating method I do the geocoding and store long+lat at the content item.

My problem is that long+lat seems not be stored at the content item. After pushing save button in editor I see the OnUpdating method is called and long+lat are set but the long+lat fields in editor are still emtpy.

Since I am within the OnUpdating method I assume I neither have to create a version draft of the content item prior setting the attributes nor calling publish on the content items after having the set attributes:

 OnUpdating<ContentPart>(
               (context, part) =>
               {
                   if (context.ContentItemRecord == null)
                   {
                       return;
                   }
                            dynamic ci = part.ContentItem
                            ci.SomeContentType.Longitude.Value = new decimal (...);
                            ci.SomeContentType.Latitude.Value = new decimal (...);                          
               });

What am I doing wrong? Any help/hint is greatly appreciated. Thanks!

**Comment by dpomt** [comment]
Using OnPublished instead of OnUpdating will store the attributes when published as expected.

OnPublishing<ContentPart>(
               (content, part) =>
               {
                      dynamic ci = part.ContentItem
                      ci.SomeContentType.Longitude.Value = new decimal (...);
                      ci.SomeContentType.Latitude.Value = new decimal (...);                 
               });


OnUpdating calls DefaultContentDisplay::UpdateEditor that invokes
   _handlers.Value.Invoke(handler => handler.UpdateEditor(context), Logger);
and this reloads the Content item and the previously set attributes are lost.

So OnUpdating seems to be the wrong place to inject Setting the attributes. What would be the correct place to store attributes when Save button is clicked in Content item Editor?

**Comment by ViRuSTriNiTy** [comment]
Use the `OnUpdated()` instead of `OnPublished()` because `OnPublished()` is problematic as it may not be called because the content item is already published.
