### ISSUE TITLE
Layout Editor js race condition

### ISSUE THREAD

**Issue by connorsmallman** [OrchardCMS/Orchard#6142]
Seems to be an error on the Contents Edit page `Uncaught Error: No element with type "Canvas" was found.`

This is casued when `window.layoutEditor = new LayoutEditor.Editor(editorConfig, editorCanvasData);` in the LayoutEditor view is called before `registerFactory("Canvas", function (value) { return LayoutEditor.Canvas.from(value); });` in the Models.js.

https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Layouts/Scripts/Models.js

https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Layouts/Views/EditorTemplates/LayoutEditor.cshtml

Fix:

Change anonymous function to JQuery document ready function `JQuery(function() {});`

https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Layouts/Views/EditorTemplates/LayoutEditor.cshtml#L38

**Comment by connorsmallman** [comment]
Still having this issue with the minified Layouts.Models script.

**Comment by sfmskywalker** [comment]
Could you try running gulp from task explorer and see if that fixes it?

**Comment by connorsmallman** [comment]
@sfmskywalker That fixed it, I'll open a pr shortly

**Comment by connorsmallman** [comment]
@sfmskywalker That fixed it thanks!
