### ISSUE TITLE
No way to relocate the Home\Search.cshtml from Orchard.Tags under my theme View folder

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6161]
The controller has the [Themed] Attrbute, it should work ? I even tried to add the [Themd] attribute to the search action...
I used this in the past, is it broken or I am missing something ?

**Comment by CSurieux** [comment]
It seems that it searchs in MyTheme\Views\Orchard.Tags\Home\ and MyTheme\Views\ but not as before in MyTheme\Views\Home\ ?

**Comment by CSurieux** [comment]
And when I added the search.cshtml (exact copy) in MyTheme\Views\Orchard.Tags\Home\ it crashes with this nice trace

Erreur source: 



Ligne 172 :
Ligne 173 :                    environment["orchard.Handler"] = new Func<Task>(async () => {
Ligne 174 :                        await Task.Factory.FromAsync(
Ligne 175 :                            _httpAsyncHandler.BeginProcessRequest,
Ligne 176 :                            _httpAsyncHandler.EndProcessRequest,
  

 Fichier source :  C:\NJingwei\Orchard\src\Orchard\Mvc\Routes\ShellRoute.cs    Ligne :  174 

Trace de la pile: 



[InvalidOperationException: The view 'Search' or its master was not found or no view engine supports the searched locations. The following locations were searched:
~/Themes/TheBootstrapMachine/Views/Orchard.Tags/Home/Search.cshtml
~/Themes/TheBootstrapMachine/Views/Search.cshtml
~/Core/Orchard.Tags/Views/Home/Search.cshtml
~/Modules/Orchard.Tags/Views/Home/Search.cshtml
~/Core/Reports/Views/Search.cshtml
~/Core/Dashboard/Views/Search.cshtml
~/Modules/TinyMce/Views/Search.cshtml
~/Modules/Orchard.Tags/Views/Search.cshtml
~/Modules/Orchard.Scripting/Views/Search.cshtml
~/Modules/Orchard.Pages/Views/Search.cshtml
~/Modules/Orchard.Packaging/Views/Search.cshtml
~/Modules/Orchard.Modules/Views/Search.cshtml
~/Modules/Orchard.MediaPicker/Views/Search.cshtml
~/Modules/Orchard.Media/Views/Search.cshtml
~/Modules/Orchard.Lists/Views/Search.cshtml
~/Core/Containers/Views/Search.cshtml
~/Modules/Orchard.Recipes/Views/Search.cshtml
~/Modules/Orchard.ImageEditor/Views/Search.cshtml
~/Modules/Orchard.Fields/Views/Search.cshtml
~/Modules/Orchard.DesignerTools/Views/Search.cshtml
~/Modules/Orchard.Layouts/Views/Search.cshtml
~/Modules/Orchard.Workflows/Views/Search.cshtml
~/Modules/Orchard.Comments/Views/Search.cshtml
~/Modules/Orchard.CodeGeneration/Views/Search.cshtml
~/Modules/Orchard.ContentPicker/Views/Search.cshtml
~/Modules/Orchard.Blogs/Views/Search.cshtml
~/Core/Shapes/Views/Search.cshtml
~/Core/Navigation/Views/Search.cshtml
~/Modules/Orchard.MediaLibrary/Views/Search.cshtml
~/Modules/Orchard.MediaProcessing/Views/Search.cshtml
~/Modules/Orchard.OutputCache/Views/Search.cshtml
~/Modules/Orchard.ContentTypes/Views/Search.cshtml
~/Modules/Orchard.Roles/Views/Search.cshtml
~/Modules/Orchard.Users/Views/Search.cshtml
~/Modules/Orchard.Alias/Views/Search.cshtml
~/Modules/Datwendo.Twitter/Views/Search.cshtml
~/Modules/Orchard.Caching/Views/Search.cshtml
~/Modules/Datwendo.OnePage/Views/Search.cshtml
~/Modules/Datwendo.Edito/Views/Search.cshtml
~/Modules/Orchard.Widgets/Views/Search.cshtml
~/Modules/Orchard.Themes/Views/Search.cshtml
~/Modules/Orchard.Conditions/Views/Search.cshtml
~/Modules/Orchard.Taxonomies/Views/Search.cshtml
~/Core/Contents/Views/Search.cshtml
~/Modules/Orchard.Resources/Views/Search.cshtml
~/Modules/Orchard.PublishLater/Views/Search.cshtml
~/Core/Scheduling/Views/Search.cshtml
~/Core/Common/Views/Search.cshtml
~/Core/Settings/Views/Search.cshtml
~/Modules/Datwendo.CookieConsent/Views/Search.cshtml
~/Modules/Datwendo.Calendar/Views/Search.cshtml
~/Modules/Orchard.Projections/Views/Search.cshtml
~/Core/Title/Views/Search.cshtml
~/Core/Feeds/Views/Search.cshtml
~/Modules/Orchard.Forms/Views/Search.cshtml
~/Modules/Orchard.jQuery/Views/Search.cshtml
~/Modules/Orchard.Autoroute/Views/Search.cshtml
~/Modules/Datwendo.BlogEx/Views/Search.cshtml
~/Modules/Orchard.Tokens/Views/Search.cshtml]
   System.Web.Mvc.ViewResult.FindView(ControllerContext context) +330
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +116
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +27
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +58
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +349
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +69
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +188
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +124
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +27
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +27
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +48
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +21
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +32
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +26
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +40
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +21
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +24
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +27
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +48
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +58
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +30
   System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +21
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +29
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +23
   System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) +72
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Orchard.Mvc.Routes.<<ProcessRequestAsync>b__0>d.MoveNext() in C:\NJingwei\Orchard\src\Orchard\Mvc\Routes\ShellRoute.cs:174
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Orchard.Owin.<<UseOrchard>b__0_0>d.MoveNext() in C:\NJingwei\Orchard\src\Orchard\Owin\OrchardMiddleware.cs:17
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Orchard.Mvc.Routes.<ProcessRequestAsync>d__5.MoveNext() in C:\NJingwei\Orchard\src\Orchard\Mvc\Routes\ShellRoute.cs:181
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +71
   System.Web.HttpTaskAsyncHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +11
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9644037
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by sebastienros** [comment]
This has always been this:
[Theme]\Views\[Module]\[Controller]\[View]

**Comment by CSurieux** [comment]
Sorry, as usual your are too 'speedy', I have 3 sites which runs with the rule, and I think that Nwazet Ecommerce also uses it (TBC)
[Theme]\Views\[Controller][View]

**Comment by sebastienros** [comment]
That can't be, or maybe just for a specific module name, otherwise there could be conflicts

**Comment by CSurieux** [comment]
Conflicts ? but the View engine already provides 2 choices
[Theme]\Views[Module][Controller][View]
AND
[Theme]\Views[View] look in debugger and for thid one there should be conflicts...

Sorry something has changed here.
