### ISSUE TITLE
DynamicForms : TextAreaElement throwing on null ProcessedValue

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/Orchard#6189]
1.9.x branch

Adding a TextArea in a DynamicForm throws `RuntimeBinderException` if no value is specified.
Issue appears after e29fb90298659a67b58711a64f0c23746817cb06

**Comment by TFleury** [comment]
Fix here : #6191 (sorry I missed my commit title)

**Comment by TFleury** [comment]
It could cause issue on themes where TextArea's element has been overridden. Maybe we should prevent `TextAreaElementDriver` to return a null value ?

**Comment by infofromca** [comment]
the same issue as  #6127 in dev branch
