### ISSUE TITLE
Migration of Search crashes when Search mediaLibrary is activated

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6199]
It crashes with nullReference on
_indexManager.GetSearchIndexProvider().CreateIndex("Media");

this occurs when nothing in 'the search system'  has been activated before.

Curiously orchard continues running and announces that all is Ok.
Trace
2015-12-17 22:05:02,863 [22] Orchard.Data.Migration.DataMigrationManager - Default - ERROR Error while running migration version 0 for Orchard.Search.MediaLibrary.
System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Orchard.Search.MediaMigration.Create()
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   à System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   à System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   à System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   à Orchard.Data.Migration.DataMigrationManager.Update(String feature) dans C:\NJingwei\Orchard\src\Orchard\Data\Migration\DataMigrationManager.cs:ligne 115
2015-12-17 22:05:03,225 [22] Orchard.Exceptions.DefaultExceptionPolicy - Default - ERROR An unexpected exception was caught
Orchard.OrchardException: Erreur lors de l'exécution de la migration de la version 0 pour Orchard.Search.MediaLibrary. ---> System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Orchard.Search.MediaMigration.Create()
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   à System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   à System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   à System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   à Orchard.Data.Migration.DataMigrationManager.Update(String feature) dans C:\NJingwei\Orchard\src\Orchard\Data\Migration\DataMigrationManager.cs:ligne 115
   --- Fin de la trace de la pile d'exception interne ---
   à Orchard.Data.Migration.DataMigrationManager.Update(String feature) dans C:\NJingwei\Orchard\src\Orchard\Data\Migration\DataMigrationManager.cs:ligne 152
   à Orchard.Data.Migration.DataMigrationCoordinator.Installing(Feature feature) dans C:\NJingwei\Orchard\src\Orchard\Data\Migration\DataMigrationCoordinator.cs:ligne 26
   à Orchard.Events.DelegateHelper.<>c__DisplayClass14_0`2.<BuildAction>b__0(Object target, Object[] p) dans C:\NJingwei\Orchard\src\Orchard\Events\DelegateHelper.cs:ligne 116
   à Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) dans C:\NJingwei\Orchard\src\Orchard\Events\DefaultOrchardEventBus.cs:ligne 84
   à Orchard.Events.DefaultOrchardEventBus.TryInvoke(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue) dans C:\NJingwei\Orchard\src\Orchard\Events\DefaultOrchardEventBus.cs:ligne 70
   à Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue) dans C:\NJingwei\Orchard\src\Orchard\Events\DefaultOrchardEventBus.cs:ligne 53
2015-12-17 22:05:11,177 [22] Orchard.Data.Migration.DataMigrationManager - Default - ERROR Error while running migration version 0 for Orchard.Search.MediaLibrary.
System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Orchard.Search.MediaMigration.Create()
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   à System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   à System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   à System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   à Orchard.Data.Migration.DataMigrationManager.Update(String feature) dans C:\NJingwei\Orchard\src\Orchard\Data\Migration\DataMigrationManager.cs:ligne 115

**Comment by Piedone** [comment]
Duplicate of #5280.

**Comment by CSurieux** [comment]
The problem with closing duplicate is that we miss the fact that many people suffer from the same bug.
I think they should be kept open util solved, just to see the size of the Problem?
Sorry Zoltan I am not trying to suppress your activity on duplicates but it's use is puzzling me.

**Comment by bleroy** [comment]
No, closing because of a duplicate means you should go to the duplicate bug, which is still open. This one can still be found through Google, and has a link to the other one. There's no problem here.
