### ISSUE TITLE
Orchard Gallery Version Sort Order Incorrect

### ISSUE THREAD

**Issue by davegardner** [OrchardCMS/Orchard#6209]
The new orchard Gallery website does not cope with version numbers where the last component is > 9. Consequently, it thinks version 3.3.5.9 is the latest version when it should be 3.3.5.11. See screenshot.

![orchardgallerywrongorder](https://cloud.githubusercontent.com/assets/1154410/11923860/b2d65b5c-a7fd-11e5-93ff-7cc63d7f367f.png)

**Comment by sebastienros** [comment]
Please open the exact same issue on the gallery's project.
