### ISSUE TITLE
Widget placement form is not displayed in Chrome

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [OrchardCMS/Orchard#6211]
Hi there,

the widget placement form is not displayed in Google Chrome:

![widgets_chrome](https://cloud.githubusercontent.com/assets/12170676/11927069/fc047644-a7c9-11e5-969b-d34f0b414b8e.jpg)

I have noticed that the form is displayed when refreshing the page but as soon as the page is loaded it is set to hidden.

In IE all is working correctly:

![widgets_ie](https://cloud.githubusercontent.com/assets/12170676/11927073/05ae0138-a7ca-11e5-9eec-7f71e2bb9007.jpg)

Responsible for this is a style in

    Orchard.Web\Modules\Orchard.Widgets\Styles\orchard-widgets-admin.css

    #widgets-placement .summary-view .widgets-none {
        display: none;
    }

Outcommenting `display: none` makes the form visible again.

I'm not sure why this style is needed here, can someone explain?

**Comment by agriffard** [comment]
I don't have this behavior.

This is as if you have clicked on the button on the right that hides the zones that don't have any widgets (There are 2 buttons : Summary and Details view).

**Comment by ViRuSTriNiTy** [comment]
Ok, figured it out. It is caused by a missing Zone: entry in the Theme.txt.
