### ISSUE TITLE
Widget enhancement proposal: Deactivated flag for widgets to prevent widgets from being rendered

### ISSUE THREAD

**Issue by dpomt** [OrchardCMS/Orchard#6226]
Need to temporarily prevent widgets from being rendered. 
Proposed enhancement: https://github.com/OrchardCMS/Orchard/pull/6213

**Comment by sfmskywalker** [comment]
I don't think this is necessary; we have the Disabled layer for that.

**Comment by dpomt** [comment]
I personnally prefer the new flag and the possibility to quickly activate/deactivate widgets without moving them to the Disabled layer and back. So I would love to see this as part of the widgets module.

**Comment by CSurieux** [comment]
You should also be able to hide them using placement. Not Ok for one more flag.

**Comment by Piedone** [comment]
@dpomt did you know that with the Disabled layer you can also do this quickly? When you edit the widget, just change the layer in the drop-down. The zone and everything else will remain the same so you can put it back by changing the layer again.

Furthermore I think widgets now can be draftable and you can unpublish them?

**Comment by dpomt** [comment]
@Pioedone: the way you have described to move a widget to the disabled layer is sufficient for me. 
So please close this issue. I will close my pull request. 

I did not know that widgets are draftable. I have just tested it - it works. Thanks for that additional info!
