### ISSUE TITLE
Timer activity throws null error exception 

### ISSUE THREAD

**Issue by neTp9c** [OrchardCMS/Orchard#6240]
That happens in dev branch.

Error log:
_Orchard.Tasks.BackgroundService - (null) - Error while processing background task "Orchard.Workflows.Activities.TimerBackgroundTask" on tenant "Default". [(null)]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.Workflows.Activities.TimerBackgroundTask.Sweep() in d:\sites\orchard sites\rpa-mu.ru-dev\src\Orchard.Web\Modules\Orchard.Workflows\Activities\TimerActivity.cs:line 132
   at Orchard.Tasks.BackgroundService.Sweep()_

It happens on line (where ContentItemRecord is null)
`var contentItem = _contentManager.Get(action.WorkflowRecord.ContentItemRecord.Id, VersionOptions.Latest);`

**Comment by Piedone** [comment]
Which Orchard version are you using? I suspect this is because of a Workflows bug that was solved but I couldn't find a reference to it now.

**Comment by Piedone** [comment]
Fixed in https://github.com/OrchardCMS/Orchard/pull/6604.
