### ISSUE TITLE
IOrchardHost.GetShellContext - Creating and setting up tenants

### ISSUE THREAD

**Issue by leventesen** [OrchardCMS/Orchard#6244]
I'm trying to create and setup tenants by code.
When I write this code:
```csharp
_tenantService.CreateTenant(tenantSettings);
var shellContext = _orchardHost.GetShellContext(newTenantShellSettings);
```
shellContext  is null. Then I changed the code to this:
```csharp
_tenantService.CreateTenant(tenantSettings);
_orchardHost.EndRequest();
_orchardHost.BeginRequest();
var shellContext = _orchardHost.GetShellContext(newTenantShellSettings);
```
shellContext is valid but it invalidates the login state (I mean log out me).

What's wrong all with this?

**Comment by Piedone** [comment]
Please don't open issues for questions.
