### ISSUE TITLE
"Use CDN" breaks Orchard.MediaLibrary with javascript error

### ISSUE THREAD

**Issue by Xeevis** [OrchardCMS/Orchard#6252]
(affects `dev` branch)

Enabling "Use CDN" in site settings will cause `/Admin/Orchard.MediaLibrary` to fail with javascript error. 

```
20:41:07.732 TypeError: this._addClass is not a function
._create() droppable.min.js:1
...
```

**Comment by Xeevis** [comment]
Issue is caused by differences in local vs CDN versions of **jQuery UI** scripts. While CDN is serving standard single file package of stable jQuery UI that includes everything, Orchard on the other hand features some sort of custom **jquery-ui.js** with to me unknown additional js files all over the place (draggable, droppable, mouse all these are already present in jQuery UI file no?).

If **Orchard.Resources** module is to be one-stop for module developers, it should probably switch to resources identical to standard distributions with CDN support rather than custom builds which are unpredictable and chaotic.

Orchard.MediaLibrary's `index.cshtml` has

    Script.Require("jQueryUI_Droppable").AtFoot();

That through dependencies includes droppable.min.js, draggable.min.js, mouse.min.js, jquery-ui.min.js which is 4 requests, 291 KB and doesn't work with CDNs (CDNs as are set now will cause the error).

If I use original stable jQueryUI from CDN and change `index.cshtml` to

    Script.Require("jQueryUI").AtFoot();

I get rid of the errors, gallery starts working again, drop to 1 request 235 KB and can fetch it easily from CDN.

Is there a reason why jQuery UI isn't just 1 file? I don't see any benefit to current implementation.

**Comment by sebastienros** [comment]
I also think we should aggregate jQuery UI in less resources. Assigning it to the next version as it's too late to change in 1.10 and the design needs to be discussed.

**Comment by sebastienros** [comment]
It should be fixed now. Can you try it from the 1.10.x branch? Thanks.
