### ISSUE TITLE
Azure Deploy

### ISSUE THREAD

**Issue by fynman** [OrchardCMS/Orchard#6255]
Hi,

  I tried to deploy Orchard from the Azure Marketplace and consistently get an error during deployment:

Resource: MSDeploy

Type: Microsoft.Web/Sites/Extensions

STATUSMESSAGE
{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'."}}

  Any idea what might be going on?

Thanks,
Bart

**Comment by sebastienros** [comment]
It has been tested a couple of days ago with success.

**Comment by ridecar2** [comment]
I'm getting the same error today.

**Comment by summer600** [comment]
Just tried to deploy orchard to azure and got this exact error

**Comment by sebastienros** [comment]
I am reopening it until the new package is uploaded on Azure. Please use the source code or the release packages to deploy.
