### ISSUE TITLE
Broken alias for first couple imported taxonomy terms from a single xml file

### ISSUE THREAD

**Issue by Xeevis** [OrchardCMS/Orchard#6263]
On latest **dev** there is a new problem concerning import, while in **1.9.2** it works fine.

Term's Autoroute pattern is `{Content.Container.Path}/{Content.Slug}` *(my-taxonomy/my-term/sub-term)*

It appears `{Content.Container.Path}` is not fully initialized before import starts and populates in the middle of the process creating alias discrepancy between terms.

**Test scenario:**, import single xml file where data is ordered as 1 taxonomy then 1 parent term + 50 children terms then 1 parent term + 1 child term.

1st parent won't have taxonomy's slug in it's alias and first 18 of it's children won't have their parent's slug in their alias while rest of the children do. Second parent term will properly have taxonomy's slug and it's child will have properly both Taxonomy's slug and parent's slug in it's alias. ***So only 2 out of 53 terms get imported with correct expected alias.***

To test this I've prepared self contained XML import file, 
1. Just compile latest `dev` branch
2. Enable **Import/Export Module** and import attached XML file
3. Go to Taxonomies > Terms
4. Observe discrepancies in aliases

[import-issue.zip](https://github.com/OrchardCMS/Orchard/files/80504/import-issue.zip)

**Comment by Skrypt** [comment]
Can you say if you have Content.Localization module enabled ?
Are you importing on a clean install of Orchard ?
Else the Alias module should work as in 1.9.2 with a single autoroute pattern. Not sure the problem comes from the changes made in the Alias module itself.

**Comment by Skrypt** [comment]
Have you tried also creating the same Taxonomies manually on a clean dev branch to see if there is not some differences in the impot/export because I think Bertrand Leroy has integrated a lot of changes in the import/export module. So the xml export of dev branch might be a little different than in branch 1.9.2

**Comment by Xeevis** [comment]
Yes clean install on Default recipe. Importing via text editor through taxonomy UI does work correctly so Import/Export module might indeed be the one to blame.

**Comment by sebastienros** [comment]
Found the issue, and believe it or not this is due to this other one: https://github.com/OrchardCMS/Orchard/issues/6273
