### ISSUE TITLE
Error publishing Orchard with "Precompiled" option

### ISSUE THREAD

**Issue by gcsuk** [OrchardCMS/Orchard#6265]
When publishing to the file system with "Precompiled" option selected, the following error is thrown:

Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified.

(dev branch)

**Comment by sebastienros** [comment]
Precompiled views are not supported in Orchard, I will still look into it to understand why Layout in particular.

**Comment by sebastienros** [comment]
Couldn't find the reason, still closing as it's not supported.
