### ISSUE TITLE
Many pbs after last switch in Dev on Package usage

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6266]
I got this on many Orchard modules
"Could not resolve this reference. Could not locate the assembly "System.Web.Mvc". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors."

**Comment by CSurieux** [comment]
Addendum 1
Could we migrate Log4net package to 2.05 ? Google client API packages in my modules use 2.05.

**Comment by CSurieux** [comment]
Addendum 2
What do we do for all the updates proposed by the package manager ? Is there an official process ?

**Comment by gcsuk** [comment]
Have you restored packages? I cannot replicate the issue.

Addendum 1: If you do this and submit a PR it will be discussed at a Thursday meeting

Addendum 2: If you have a reason to update any package (streamlining solution versions would be a valid one) then see addendum 1 above. If it is not a major version change, and there are no breaking changes mentioned in release notes between current version and 2.0.5, it might be accepted.

**Comment by CSurieux** [comment]
Making PRs is actually very time consuming, or I have not the fastest method ?

**Comment by gcsuk** [comment]
This is the way:

* Fork Orchard
* Create a new branch ***off dev***
* In Visual Studio, update the Log4net NuGet package in package manager to 2.0.5
* Rebuild the solution to ensure no broken build, then run it and test things out to make sure it is working.
* Run the unit tests
* Commit the changes and push to GitHub
* Open a PR and concisely describe what you have done and why.

It won't take long, trust me.

**Comment by CSurieux** [comment]
I have already 8 forks of Orchard only for PR that I had to rewrite because the wording was not ok, because braces were not ok,  because someone change all the end of line and we must resynch, and finally some because they were not admitted (but working).
Microsoft is great and Orchard is poor. :)

The problem in your process is that we have all to open Git repos to be able to make PR to Orchard. That’s very unfriendly. There should be something more easy were everybody could fork directly inside Orchard repos.

 

 

De : Rob King [mailto:notifications@github.com] 
Envoyé : jeudi 14 janvier 2016 17:16
À : OrchardCMS/Orchard <Orchard@noreply.github.com>
Cc : CSurieux <christian.surieux@hotmail.fr>
Objet : Re: [Orchard] Many pbs after last switch in Dev on Package usage (#6266)

 

This is the way:

*	Fork Orchard
*	Create a new branch off dev 
*	In Visual Studio, update the Log4net NuGet package in package manager to 2.0.5
*	Rebuild the solution to ensure no broken build, then run it and test things out to make sure it is working.
*	Run the unit tests
*	Commit the changes and push to GitHub
*	Open a PR and concisely describe what you have done and why.

It won't take long, trust me.

**Comment by bleroy** [comment]
You are complaining about git, or rather about how you use git. All open source projects that use git (and that's pretty much all open source projects nowadays) use that exact same process, which is why it's even integrated into the Github web site. You don't have to have multiple forks. Branches are enough. I do pull requests routinely, and the overhead is minimal. Anyway, this discussion should not be happening here, as it's entirely unrelated to the issue. Please move it to forums or Gitter.

**Comment by CSurieux** [comment]
Ok sorry for this. I will try to do this PR.
But change something please ;)

**Comment by sebastienros** [comment]
File a separate issue if you want to upgrade log4net
