### ISSUE TITLE
Incorrect wording on Edit Query page.

### ISSUE THREAD

**Issue by mwentz** [OrchardCMS/Orchard#6272]
For a custom field of type DateTimeField, when you choose "Is greater than or equal to" on the Edit Filter page, it shows up as "is greater or equal than" on the Edit Query page.

**Comment by Devqon** [comment]
2 occurences:
- DateTimeFilterForm.cs (line 262)
- NumericFilterForm.cs (line 139)

**Comment by agriffard** [comment]
Also change "Is less than or equal to" to "Is less or equal than"
