### ISSUE TITLE
Images have links like pages

### ISSUE THREAD

**Issue by GioviQ** [OrchardCMS/Orchard#6274]
Watching the statistics of my site I discovered /Contents/Item/Display/243 as page visited.
This url does not map to a page or other text content I created, but it shows an image uplodead in the gallery. This seems strange to me, even I do not understand how someone, human or bot, has discovered and visited this link.
I would like to avoid such links be public.

**Comment by CSurieux** [comment]
Change the corresponding template file to remove links, I also did it.

**Comment by GioviQ** [comment]
Please be more detailed.

**Comment by sebastienros** [comment]
Robots. Probably parsing some RSS feeds you have on your pages rendered from projections.

**Comment by GioviQ** [comment]
I have no projections, but I discovered rss links in taxonomy pages. So I disabled Feeds module, but that disables Blog module too. So I enabled again and I used what explained in #4172; that is: Disallow: /rss
Anyway even checking inside rss I do not find links like  /Contents/Item/Display/243.

**Comment by CSurieux** [comment]
It may be a mistake but it seems that the template image.summary.cshtml contains a link ?
It seems that I had to remove it in the past but I can't remember why, so may be it is a bad suggestion.

**Comment by sebastienros** [comment]
@CSurieux is probably right, if you display a Media item's shape directly you might have a url automatically.

**Comment by sebastienros** [comment]
Media items have a title. If you are displaying a Media using the summary view, this title will link to the content item using this generic url.
You can either add an AutoroutePart to the Image type if you want these urls to work but be less generic, or update the summary view not to display this url.
