### ISSUE TITLE
In Container Widget, Order by is not working as expected

### ISSUE THREAD

**Issue by urbanit** [OrchardCMS/Orchard#6276]
Version: 1.9.x (as of 10/01/2016)
Scenario: Enable Lists module, add ​Containable part to BlogPost, create a new List, add some BlogPosts, reorder, create Container Widget with "order by" weight option.

The List renders BlogPosts by recent descending...

Am I missing anything?

**Comment by sfmskywalker** [comment]
This might be a bug., but I believe the Order By is not supposed to work anymore, and the option should probably be removed, because the order is governed by the list itself. If you want to control ordering, you should use a Projection Widget and a Query that uses the List filter.
