### ISSUE TITLE
WorkContext null

### ISSUE THREAD

**Issue by juanfq** [OrchardCMS/Orchard#6278]
I'm using the multitenancy module and am trying to see if it is possible to have shape alternates defined by tenant so that a customization doesn't have to affect all tenants.
My thought was to implement my own IShapeTemplateHarvester in order to add an additional path such as "Views/TenantName". 
My problem is that WorkContext is null at the time the ShapeTemplateHarvester is run. 
Is there another way I could get the tenant name for the current request?  
```
        public IEnumerable<string> SubPaths()
        {
            var workContext = _workContextAccessor.GetContext();
            //var workContext = Services.WorkContext;
            List<string> paths = new List<string>() { "Views", "Views/Items", "Views/Parts", "Views/Fields", "Views/Elements" };
            if(workContext != null)
            {
                var settings = workContext.Resolve<Orchard.Environment.Configuration.ShellSettings>();
                var tenant = settings.Name;
                paths.Add("Views/" + tenant);   
            }
            return paths;
        }
```

**Comment by sebastienros** [comment]
This code is not run by a specific tenant. What you can do instead if defined alternates with the tenant name. Look at the Widget Url Atlernates feature which does something similar.
