### ISSUE TITLE
Created Layouts Not Listed

### ISSUE THREAD

**Issue by jchenga** [OrchardCMS/Orchard#6283]
1. Create a layout.
2. Click "Layouts". the created layout is not displayed in "Manage Layoutout Content". Layout is also not in the Show options.

The problem has to do with Layout content type no longer being Listable since commit 5903f756651c2b4de127e38e5bad644525a6564a. The call to Listable was taken out of Migrations.cs in Layouts module.

**Comment by sfmskywalker** [comment]
I believe @sebastienros fixed this a few days ago, not sure which branch, either 1.9.x or dev.

**Comment by jchenga** [comment]
Thanks. It is indeed fixed three days ago in 1.9.x.
