### ISSUE TITLE
The Migration record in Orchard_Framework_DataMigrationRecord should not be prefixed with the namespace where the migration class is created

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6284]
With this prefix the records depends of the namespace and any change in namespace means an error in startup. Because the tables are not prefixed with the namespace but use the Part/Record class names, and migration try to run for the new namespace but the tables already exist and it crashes.
All this should be sync, the best would be to not use the migration namespace but a fixed name.
Changing this would consist in creating a property with same name as its namespace.

**Comment by Piedone** [comment]
So if I understand correctly your argument against the current practice is that it prevents you from moving records across namespaces? You do know that records can only be in the Models namespace (and nothing else, not even a sub-namespace of this) in an extension, so this is only a case if you move a record from one extension to the other (including renaming the extension)?

But how would you add a custom prefix? Let's try an example: you create ModuleA and Record inside it. Now you need to choose a prefix for Record so it doesn't clash with anything else. What would you prefix it with if not the module name as an obvious choice? Because if you do that then it's the same issue again.

**Comment by CSurieux** [comment]
You don't understand correctly.

**Comment by bleroy** [comment]
Then clarify?

**Comment by sfmskywalker** [comment]
Although I see Chris' point, I don't think it's compelling enough to change any of this.The convention where the namespace is used to build the table name is highly convenient in the majority of the cases. The only case where it might be inconvenient is when you are refactoring and the namespace changes, or even the class name, but having to manually try and specify a unique table name doesn't outweigh the benefit of that happening automatically in my opinion.

That being said, I believe you can already control the exact table name mapped to your entity classes by implementing `ISessionConfigurationEvents`, which allows precise control over table and column mapping. I did this on a few occasions with column name mapping, but never tried with table names. Sounds like it be worth a shot.

**Comment by CSurieux** [comment]
Thanks Sipke for understanding better this point. But not totally.
What I did has been to have a bad namespace name for the migration class and discovered it month later.
I tried to fix the namespace name but then entered in errors on start as explained.
I do not propose to change any table Name, simply to change the name in the migration record. Get rid of the namespace prefix and replace it by a  string property.
This way changing the namespace where is the migration class will have no impact.
Is it more clear to toi?

Envoyé à partir de mon sanyo phc 25
________________________________
De : Sipke Schoorstra<mailto:notifications@github.com>
Envoyé : ‎19/‎01/‎2016 22:54
À : OrchardCMS/Orchard<mailto:Orchard@noreply.github.com>
Cc : CSurieux<mailto:christian.surieux@hotmail.fr>
Objet : Re: [Orchard] The Migration record in Orchard_Framework_DataMigrationRecord should not be prefixed with the namespace where the migration class is created (#6284)

Although I see Chris' point, I don't think it's compelling enough to change any of this.The convention where the namespace is used to build the table name is highly convenient in the majority of the cases. The only case where it might be inconvenient is when you are refactoring and the namespace changes, or even the class name, but having to manually try and specify a unique table name doesn't outweigh the benefit of that happening automatically in my opinion.

That being said, I believe you can already control the exact table name mapped to your entity classes by implementing `ISessionConfigurationEvents`, which allows precise control over table and column mapping. I did this on a few occasions with column name mapping, but never tried with table names. Sounds like it be worth a shot.

---

**Comment by sebastienros** [comment]
Just to clarify, @CSurieux is talking about the value of the field which stores the name of the class that was run. Not the Table name.

**Comment by bleroy** [comment]
Ideally, wouldn't it be a better solution to have the required API in migrations to fix existing data and move it to the new names, rather than a runtime override that fixes usage to point to the bad name?

**Comment by sfmskywalker** [comment]
Ah, yes I see now what you mean. I've run into that issue a few times myself. Easily fixed manually once you realize what's going on, but probably best to have the migration fix that data automatically once as per Bertrand's suggestion.

**Comment by CSurieux** [comment]
Seems more complicated than removing the link with the namespace where is the class.
________________________________
De : Sipke Schoorstra<mailto:notifications@github.com>
Envoyé : ‎19/‎01/‎2016 23:18
À : OrchardCMS/Orchard<mailto:Orchard@noreply.github.com>
Cc : CSurieux<mailto:christian.surieux@hotmail.fr>
Objet : Re: [Orchard] The Migration record in Orchard_Framework_DataMigrationRecord should not be prefixed with the namespace where the migration class is created (#6284)

Ah, yes I see now what you mean. I've run into that issue a few times myself. Easily fixed manually once you realize what's going on, but probably best to have the migration fix that data automatically once as per Bertrand's suggestion.

---

**Comment by bleroy** [comment]
More complex to implement for sure, but also more correct.

**Comment by CSurieux** [comment]
Correct for you.

Envoyé à partir de mon sanyo phc 25
________________________________
De : Bertrand Le Roy<mailto:notifications@github.com>
Envoyé : ‎19/‎01/‎2016 23:38
À : OrchardCMS/Orchard<mailto:Orchard@noreply.github.com>
Cc : CSurieux<mailto:christian.surieux@hotmail.fr>
Objet : Re: [Orchard] The Migration record in Orchard_Framework_DataMigrationRecord should not be prefixed with the namespace where the migration class is created (#6284)

More complex to implement for sure, but also more correct.

---

**Comment by bleroy** [comment]
Do you want to substantiate that maybe?

**Comment by CSurieux** [comment]
No need les jeux sont pipes.


Envoyé via Outlook Mobile






On Tue, Jan 19, 2016 at 2:40 PM -0800, "Bertrand Le Roy" <notifications@github.com> wrote:





Do you want to substantiate that maybe?

---

**Comment by sebastienros** [comment]
I think the current behavior is fine, changing it would just push the issue somewhere else, defining your custom string would not prevent you from deciding to change it later and make existing migrations fail.
