### ISSUE TITLE
Media ImageEditor button not showing 

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#6285]
what are the criteria's to make the Media 'ImageEditor' button appear?
I'm out of ideas on this issue; what in the world am I missing!?

My Environment: 1.9.2; WebMatrix, VS2015 or deployed  (ISP i.e not on Azure)

Following Modules (and its prereq's) are enabled:
 Media.Library
 Media.Library.Search
 Media.Library.Processing
 Image.Editor

I always use the standard Media Import to load my images
What stupid thin am I missing, doing wrong?
Thanks for your time and hints, ed

**Comment by edikaufmann** [comment]
PS:
I'm definitely a GitHub novice ...
I (only) understand that GitHub is firstly an App for distributed revision control using (local) repositories. After Orchard introduced GitHub: where is the correct place to report issues like this? 

So far I always used the Forum via 'Orchard -> discussions and help' i.e. this issue is also reported there.

 Now I see reported issues also on GitHub - are all of them based on local repositories contributing to fix Orchard development / design errors?
Which is the correct place for issues like above? Thanks for a clarification, ed

**Comment by sebastienros** [comment]
It works fine on 1.10, please try with the source code, or wait for the new 1.9.3/1.10 release.

![image](https://cloud.githubusercontent.com/assets/1165805/12494477/369f07aa-c03f-11e5-916e-c484b3d23939.png)
