### ISSUE TITLE
Sending emails from Orchard error cert.

### ISSUE THREAD

**Issue by manhuyetxa** [OrchardCMS/Orchard#6286]
Hj!
I have a problem in framework Orchard (version 1.9.2).
I done enable module email and config it.
I done test send mail but get a message "send mail fail.".
Please suport for me.
Thank you for view.

**Comment by abhishekluv** [comment]
Hi,

Kindly double check these things:

- Host name
- Port number
- email and password 
- Try sending a test email with and without SSL communication.

Regards

**Comment by manhuyetxa** [comment]
Thank you for suport.
I forgot enable security in account gmail of google.
