### ISSUE TITLE
When updating a content the ContentFieldDriver doesn't check if the field was displayed or not

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/Orchard#6287]
In ContentPartDriver.UpdateEditor() there is a check for the placement that decides if the part needs to be updated or not. But nothing like this in ContentFieldDriver or anywhere.

Repro: Make a field required and create an editor group where you make the field not be displayed from Placement.info. Now save the content on that editor group. You will get a validation error.

Solution:
Copy-paste the relevant code from ConentPartDriver.UpdateEditor() to ContentFieldDriver.UpdateEditorShape() and fix compilation errors (add usings and add field parameter to var editor = Editor(part, field, context.New) as ContentShapeResult;).

Now this method will look like this and it will work fine.

```
        DriverResult IContentFieldDriver.UpdateEditorShape(UpdateEditorContext context) {
            return Process(context.ContentItem, (part, field) => {
                // checking if the editor needs to be updated (e.g. if it was not hidden)
                var editor = Editor(part, field, context.New) as ContentShapeResult;

                if (editor != null)
                {
                    ShapeDescriptor descriptor;
                    if (context.ShapeTable.Descriptors.TryGetValue(editor.GetShapeType(), out descriptor))
                    {
                        var placementContext = new ShapePlacementContext
                        {
                            Content = part.ContentItem,
                            ContentType = part.ContentItem.ContentType,
                            Differentiator = editor.GetDifferentiator(),
                            DisplayType = null,
                            Path = context.Path
                        };

                        var location = descriptor.Placement(placementContext).Location;

                        if (String.IsNullOrEmpty(location) || location == "-")
                        {
                            return editor;
                        }

                        var editorGroup = editor.GetGroup() ?? "";
                        var contextGroup = context.GroupId ?? "";

                        if (!String.Equals(editorGroup, contextGroup, StringComparison.OrdinalIgnoreCase))
                        {
                            return editor;
                        }
                    }
                }

                DriverResult result = Editor(part, field, context.Updater, context.New);
                
                if (result != null) {
                    result.ContentPart = part;
                    result.ContentField = field;
                }
                
                return result;
            }, context.Logger);
        }
```

**Comment by Piedone** [comment]
@sebastienros what about this for 1.9.3/1.10? Obviously after factoring it out to some common place and using it in both Coordinators.

**Comment by sebastienros** [comment]
Do we agree this only applies to fields attached to the dynamic part (the one for the type) as parts also have their own Group value?
Ok for 1.10.1, so dev branch.

**Comment by barthamark** [comment]
It doesn't matter if the field is attached to dynamic part or a normal part, it always tries to be updated. This fix actually checks if it was displayed or not and doesn't care about where it was attached.
Did I understand your question well?
