### ISSUE TITLE
Orchard Gallery Url must be changed

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard#6289]
Because the Orchard gallery has been changed, the new packages feed url should be https://orchardgallery.azurewebsites.net/api/FeedService 

The url is still http://packages.orchardproject.net/FeedService.svc in DefaultPackagingUpdater.cs and has to be changed.

The attribute "xml:base=" must be changed in the gallery feed XML.

This change should also be mentioned in the next release notes to explain how to point to the correct feed url.

**Comment by agriffard** [comment]
The module Orchard.Packaging also has a service reference to http://packages.orchardproject.net/FeedService.svc but I don't know if it can be replaced by the new one.

**Comment by sebastienros** [comment]
I think the reference is just for the Visual Studio tooling to generate the client proxy based on metadata. So it's not used unless the schema changes.

**Comment by sebastienros** [comment]
We could still change it.
