### ISSUE TITLE
Worklow Content Activities after the Timer Activity lose HttpContext and generate Exception in AuditTrail GlobalContentHandler and stops logging

### ISSUE THREAD

**Issue by hannan-azam** [OrchardCMS/Orchard#6292]
The main issue is that the HttpContext is lost after the TimerActivity and since AuditTrail uses Client IP address in its logging, it fails and generates an exception in Orchard.Services.IClientHostAddressAccessor.GetClientAddress since there is no null check implemented for HttpContext Hence the log is not generated by Audit Trail.

In order to reproduce this exception please create a new workflow with activities as mentioned below.
Please make sure that Workflow Timer and Audit Trail is enabled.
In Debug mode place a Breakpoint at the start of:
Orchard.AuditTrail.Providers.Content.GlobalContentHandler.RecordAuditTrailEvent

1. Content Created Activity (Starts Workflow)
2. Timer Activity (Set it to trigger after 1 minute)
3. Publish Activity

Create new content item and Save it. The workflow will trigger and will get paused at Timer Activity. After one minute it will resume and will Publish the newly created item. 
The IContentManager.Publish will Invoke Published Handlers where the Audit Trail Handler will also be invoked and will crash in the method "RecordAuditTrailEvent" at IAuditTrailManager.CreateRecord since there it tries to fetch the Client IP address and fails with an exception of "Object reference not set to an instance of an object."

**Comment by sfmskywalker** [comment]
Which version or branch is this?

**Comment by hannan-azam** [comment]
@sfmskywalker Orchard 1.9.2 can be used to reproduce this.

**Comment by sfmskywalker** [comment]
Ok, then it's probably fixed in 1.9.x or dev, because changes have been made to ensure the HttpContext is mocked in background tasks. Would you mind giving that a go?

**Comment by hannan-azam** [comment]
Sure i will test it with 1.9.x and post the results here.

**Comment by hannan-azam** [comment]
@sfmskywalker im able to reproduce the issue on 1.9.x with the only difference that one has to turn on the Client IP Logging setting in Audit Trail settings.

I couldn't test the dev branch as im seeing compilation errors using Visual Studio 2013

**Comment by jtkech** [comment]
@sfmskywalker 

About the changes i've contributed around fake contexts when there is no ambient HttpContext, they have been committed only to the dev branch, not to the 1.9.x. Maybe they need more time to be validated. But not all properties are implemented, we have to add them step by step as needed...

No time right now but maybe i will open an issue about possible future compatibility issues when 1.9.x is merged in the dev branch. Before, see my comments here https://github.com/OrchardCMS/Orchard/commit/7057740787ff1f36d40425eb483bb5de1768d9b6#commitcomment-15492987

In 1.9.x, other changes could provide some contexts in some other cases, maybe that's why @hannan-azam have seen a different issue. One known drawback in 1.9.x (and now in 1.9.3) is that some workcontexts are created and never disposed (maybe not so important)...

Best

**Comment by sfmskywalker** [comment]
Ok, sounds like these issues will be at least solved in 1.10 then.

**Comment by hannan-azam** [comment]
@sebastienros Kindly can you also brief on how this issue should be fixed. From the comments of @jtkech it seems that some work has been done in dev branch to mock the HttpContext when it doesn't exist but it will take some time for this to be part of active branches.

Since this problem is primarily with AuditTrail and how it fails to log when there is no HttpContext, do you think it is a good idea that we enclose that chunk of code which tries to get client IP in try catch block to avoid the exception. This would be a fix which will ensure that logging is always done and as @jtkech and @sfmskywalker  recommended once we will have mock HttpContexts in place we will stop getting the exceptions for this scenario.

Please advise.

**Comment by sebastienros** [comment]
I will try to repro it first to understand what happens.

**Comment by jtkech** [comment]
@sebastienros 

It's in the 1.9.2 (from 1.9.x) and after a timer activity, so, without ambient httpContext. I think we would need here the updates around fake contexts only done in the dev branch.

I think it fails in `GetClientAddress()` at this line:

            var request = _wca.GetContext().HttpContext.Request;

Here, even if the workContext is not null, accessing the HttpContext property use `HttpContextAccessor` (if not yet done) and then return null (in 1.9.2).

I could update 1.9.x (and maybe 1.9.3) as done in the dev branch, except if you think it's too soon. For an overview on this, see #6294.

@hannan-azam indeed, adding the necessary null checks on HttpContext (and maybe also on GetContext()) is a temporary workaround...

Best

**Comment by sebastienros** [comment]
Ok, then please just check for nullability here, as it wouldn't make sense anyway to get an IP in a background task. As a PR on 1.9.3 please.
