### ISSUE TITLE
Method of Invoking Handlers in IContentManager.Export

### ISSUE THREAD

**Issue by hannan-azam** [OrchardCMS/Orchard#6293]
Handlers are invoked in almost all of the methods of IContentManager using the following scheme.
It is a very nice way since the Invoke method does the exception handling on its own and if by an chance there is any buggy code anywhere in the out of the box or third party modules it doesn't stop the complete execution.
```
Handlers.Invoke(handler => handler.Activating(context), Logger);
Handlers.Invoke(handler => handler.Publishing(context), Logger);
```

When i look at how these handlers are called in **IContentManager.Export** it is a little different. i.e.
```
            foreach (var contentHandler in Handlers) {
                contentHandler.Exporting(context);
            }

            foreach (var contentHandler in Handlers) {
                contentHandler.Exported(context);
            }
```
This way the exception is handled by **DefaultOrchardEventBus** and the execution is terminated immediately with all transactions roll backed.

We recently came across this issue where we were dealing with TimerActivity and Export method.
The HttpContext is lost after the TimeActivity as we reported the issue in this other ticket: https://github.com/OrchardCMS/Orchard/issues/6292
The whole process was terminating abnormally since the code was crashing somewhere in AuditTrail logging and the execution was terminating abnormally as it was handled by DefaultOrchardEventBus.

If the Handlers were invoked through Invoke method instead of how these are called currently, the code would have survived the AuditTrail exception gracefully. The result of the abnormal termination was that our workflow went into a very abnormal state. Where it wasn't paused and wasn't moving ahead. It was stuck.

Kindly change these Handler invoke method to:

```
Handlers.Invoke(handler => handler.Exporting(context), Logger);
Handlers.Invoke(handler => handler.Exported(context), Logger);
```

**Comment by Piedone** [comment]
Hmm, this indeed seems just left out.

**Comment by sebastienros** [comment]
Please provide a PR
