### ISSUE TITLE
What's the best rule around fake contexts to prevent future compatibility issues?

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#6294]
@sebastienros, @sfmskywalker, @Piedone... not sure about the following but what are your opinions?

In the dev branch some updates have been done to provide fake contexts (when no ambient HttpContext), and not all properties are implemented, we have to add them step by step as needed.

**So, first in the dev branch, what's the best rule:**

1. Always add the implementation of all properties as they appear. But there are so many properties, maybe the following is a good compromise.
2. Only add the implementation when it makes sense. And use in some places the `IsBackgroundContext()` extension that not only test if the context is null but also if it's a fake one.

In 1.9.x, to fix an issue sometimes this test `context != null` is added before accessing a property. But, when 1.9.x is merged in dev, because the context is not null, an exception could be thrown if the property is not yet implemented in the fake context.

**So, for future compatibility, in 1.9.x what's the best rule:**

1. If we agree with 1. above, we already need to add the implementation in the dev branch. But people need to use right now `context != null` and wait for a new release.
2. If we agree with 2. above, we need to replace some `context != null` with `!IsBackgroundContext()`.
3. In all cases, we can prevent additional `context != null` test by integrating in 1.9.x the updates done in the dev branch. But maybe they need more time to be validated.

**Last remark in 1.9.x (and now in 1.9.3)**

In 1.9.x, to fix some issues this commit https://github.com/OrchardCMS/Orchard/commit/5b53671a2a76493f0fa141653fa52f65980161a5 has been done (and only reverted in dev). One known drawback is that some workcontexts are created and never disposed. Maybe not so important, but if it is, i think it could be replaced by the end of this PR #5887 (previously committed but only in the dev branch).

Or, again, integrate in 1.9.x the updates done in the dev branch. But maybe too soon (not sure myself).

Best

**Comment by Piedone** [comment]
Keep in mind that (although rarely) the HttpContext can be null even if we're not in a background task: this is the case when the application startup logic runs, independently of a request. I'd need to check but I *think* you can easily get this case with an `IOrchardShellEvents.Activating()` implementation.

Any way, for most of the cases you observe right that the context != null checks should be changed to IsBackgroundContext().

Properties should be examined case by case whether they make sense in a background scenario IMO. It does make sense to have a fake HttpContext in a background task (think about shape display for example) and sometimes it does make sense to have a check instead.

**Comment by jtkech** [comment]
@Piedone 

Ok, but what do you think about all the updates only done in the dev branch? What we do for 1.9.x, 1.9.3?

> HttpContext can be null even if we're not in a background task

You're right, i know this. In fact `IsBackgroundContext()` doesn't mean in a background task but rather with no ambient HttpContext.

That said, with the updates done in the dev branch, to have a fake httpcontext you only need to create a WorkContext scope, as done at the beginning of background tasks. But you can do this (if necessary) in others places...

Best

**Comment by pszmyd** [comment]
@Piedone @jtkech Not really that rarely. `HttpContext` can be null when you just spin up a new TPL task or use async/await (which is not unusual). As far as I can tell there are lots of changes in dev branch to ensure `HttpContext` that's reached through `IHttpContextAccessor.Current` is correctly checked and replaced with a fake. This also applies to `IWorkContextAccessor` which uses the above to grab the current context - in other words everywhere you create new `WorkContext` scope, it will be guarded against possible null `HttpContext`, replacing with fake if needed.

**Comment by jtkech** [comment]
@pszmyd you're right but here i was wondering if all the changes i've made in the dev branch could be integrated in 1.9.x / 1.9.3, or need more time, or reserved for dev then 1.10. This to know what we have to do to solve an issue depending on the version.

Normally it works with TPL if each task create its own wc scope. With `async/await`, you're right, that's why i've used the `CallContext Logical Data`...

@Piedone i remember this issue #4338 where you helped me. It would be interesting to know if now the updates in dev can fit your needs with `async code` and as you was saying with `work contexts created independent from an http context`.

Best

**Comment by CSurieux** [comment]
May be I am not totally understanding the problem, but sometimes we could have an http context not null but the output stream under this context closed and no way to write something to output, so you get exceptions. But it could be a different Pb? Shouldn't we rip the httpcontext when asp.net closes the output stream ?.

**Comment by Piedone** [comment]
@pszmyd indeed HttpContext.Current can be null in TPL tasks too (if you write async code in the context of the request, it won't be null though), but I believe we're really talking about the context you can access via Orchard services - so the one that is supplied with a fake one in such cases.

@jtkech now I'm not really sure what you'd like to bring up. What is really the question?

**Comment by jtkech** [comment]
@Piedone sorry i was not clear, maybe because of my bad english...

I've done some PRs around fake contexts that have been agreed and committed by @sebastienros, but only in the dev branch to be validated. So, about these changes the first question would be: are they ready to be used in 1.9.x and 1.9.3?

Then, we could have the same approach to solve issues around this regardless to the Orchard version.

Anyway, thank you all @pszmyd @CSurieux  for the use cases you have pointed out

**Comment by Piedone** [comment]
I see. These were targeted at dev because they are risky and partially breaking changes, but these will be shipped with 1.10. 1.9.3 is just for bugfixes. It's only about this.

**Comment by jtkech** [comment]
@Piedone 

Oh i see, i thought it could create issues for a long time...
Said like this i understand, so i can close this "issue"...

Thanks
