### ISSUE TITLE
Inconsistent Permissions in Gallery and Themes

### ISSUE THREAD

**Issue by jchenga** [OrchardCMS/Orchard#6300]
As the site owner of a tenant, I see a list of Themes when I click Themes -> Gallery in Dashboard. Each theme has "Install" and Download  options. When I click one of the Install links, I get the following error: 

> Access Denied
> You do not have permission to complete your request.

The codes below are from the Index method in Theme Module's AdminController. The value of installThemes is used to determine whether to hide the "Install a  theme from your computer" link. In this case, only site owners of the default site can install a theme.

```
bool installThemes = 
                _featureManager.GetEnabledFeatures().FirstOrDefault(f => f.Id == "PackagingServices") != null 
                && Services.Authorizer.Authorize(StandardPermissions.SiteOwner) // only site owners
                && _shellSettings.Name == ShellSettings.DefaultName; // of the default tenant
```

Similar logics is in the InstallGalley action method in PackagingServicesController:

```
if (_shellSettings.Name != ShellSettings.DefaultName || !Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to add sources")))
                return new HttpUnauthorizedResult();
```

However, the AdminMenu class in Packaging module shows the Gallery tab as long as the user is a site owner, regardless of tenant.

```
 item = item.Action(actionName, controllerName, new { area = "Orchard.Packaging" }).Permission(StandardPermissions.SiteOwner);
```

The Themes action method in GalleryController also displays a list of themes, as long as the user is a site owner, regardless of tenant. 

```
if (!Services.Authorizer.Authorize(StandardPermissions.SiteOwner, T("Not authorized to list Themes")))
                return new HttpUnauthorizedResult();
```

Gallery tab should not display to a tenant site owner if only the default site's owner have the permission to install themes.

**Comment by jardg** [comment]
Sorry for bumping this. I think the best way to avoid the inconsistencies with permissions related by @jchenga  is to not build the menu for these users, isn't it?. I have created a pull with the  possible solution in #7511
