### ISSUE TITLE
Update Module.txt everywhere to remove codeplex references?

### ISSUE THREAD

**Issue by jean** [OrchardCMS/Orchard#6306]
At for example https://github.com/OrchardCMS/Orchard/blob/master/src/Orchard.Web/Modules/Orchard.ContentPicker/Module.txt#L4 
I see 
> Website: http://orchardcontentpicker.codeplex.com

As far as I know that's obsolete. Can all such occurences be updated to point at github? If so, I can do a pull request.

**Comment by sfmskywalker** [comment]
That would be good, thanks!
