### ISSUE TITLE
Layout automatically adds Grid in Grid when loading

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/Orchard#6309]
I've created a new Layout for my Pages.
Now when I create a new Page and select the custom Layout, Orchard automatically add a Grid inside the first Grid in my custom Layout.
So everytime I create a new Page i first have to delete the automatically added Grid which is kinda annoying.

**Comment by sfmskywalker** [comment]
You can configure the default layout of elements by editing the Layout Part settings of the Page content type (Content Definition -> Page -> Edit). You'll notice it's a chunck of JSON that you can replace with your own JSON string (without the grids).

I personally also prefer to start with an empty Page, so perhaps we should consider changing the default layout to not add a Grid by default.

**Comment by Flarescape** [comment]
Perfect, thanks! 

That would be great!
