### ISSUE TITLE
On Import, the modified url only gets updated in AutoroutePart and not as new Alias (Friendly Url)

### ISSUE THREAD

**Issue by hannan-azam** [OrchardCMS/Orchard#6316]
I reproduced this bug on Orchard 1.9.3 branch.

Following are the steps to reproduce this issue. On a fresh installation, enable ImportExport:
1. Import the attached file [Import1.txt](https://github.com/OrchardCMS/Orchard/files/109642/Import1.txt). It will create an item of type Page with friendly url "/test-page"
2. Import the attached file [Import2.txt](https://github.com/OrchardCMS/Orchard/files/109641/Import2.txt). Observe that on edit mode, Autoroute Part says "modified/test-page" whereas the friendly url still is "/test-page". i.e. the new Autoroute url won't be registered as the new Alias (friendly url).

The main issue is, when IContentManager.Import method tries to Publish the item at following lines of code:

```
            if (status == null || status.Value == Published) {
                Publish(item);
            }
```

The Publish method checks if the Record is already Published or not. If it is already published it simply ignores and returns without calling the handlers.

```
            if (contentItem.VersionRecord.Published) {
                return;
            }
```

This works very nicely on the first Import process where the record was created anew. It went ahead and called all those handlers. For example Autoroute OnPublished which registers the friendly url:

```
            OnPublished<AutoroutePart>((ctx, part) => PublishAlias(part));
```

If user manually Publishes the item then this error goes away since in that case a new draft is created which gets published and in turn calls all the handlers.

This should work with Import as well. If user changes the friendly url, at the end of Import process it should register the new friendly url automatically.

**Comment by hannan-azam** [comment]
One solution that come to my mind is to add two new handlers for AutoroutePart
```
            OnImporting<AutoroutePart>
            OnImported<AutoroutePart>
```

On Importing, we should remove any existing(old) Aliases by directly injecting the IAliasStorage. This will have to be done this way because, the value of Autoroute would have been changed already once this handler will be called and simple call to **RemoveAlias** won't be able to remove it.

OnImported, we should call the PublishAlias if the item is in Published state.

Moreover, we will have to move the Imported handler Invoke thing at the end of the Import Process.

```
            Handlers.Invoke(handler => handler.Importing(context), Logger);

            var savedItem = Get(item.Id, VersionOptions.Latest);

            // the item has been pre-created in the first pass of the import, create it in db
            if(savedItem == null) {
                if (status != null && status.Value == "Draft") {
                    Create(item, VersionOptions.Draft);
                }
                else {
                    Create(item);
                }
            }

            if (status == null || status.Value == Published) {
                Publish(item);
            }
       
            Handlers.Invoke(handler => handler.Imported(context), Logger);
```

**Comment by hannan-azam** [comment]
@sebastienros Kindly advise what should be the possible solution to fix the bug mentioned above.

**Comment by hannan-azam** [comment]
@sebastienros Please can you help a little in this task in suggesting some good solution.

I will briefly explain the issue and the root cause.

**Problem**
For an existing content item with alias already registered. If we try to import the recipe for the same item with a modified alias. The old alias doesn't get deleted and stays there where as the new alias is also registered.

**Root Cause**
During Import, RecipeExecutor.Execute schedules the recipe and calls UpdateShell
At this time IAliasHolder has been emptied
Now Recipe begins to execute. On Publish, DefaultAliasService.Replace method gets called to set the new Alias. Lookup fails to locate an existing route in IAliasHolder and hence the existing route is not deleted and later a new route is created.
Once all is done, DefaultOrchardShell.Activate gets called which Activates the Shell
AliasUpdaterEvent.Activated gets called to Refresh the IAliasHolder and now we have a fully populated Alias Holder.

So the issue is that, during recipe import, when we are trying to replace existing we don't find it in alias holder. Later the alias holder is populated on Shell activation.

The solution in my mind is that when we try to get the alias map, we can check if the alias holder has 0 entries, we first force a refresh using IAliasHolderUpdater.Refresh

But this doesn't seem right and i fell there should be a better way of doing this.

Please advise.

cc: @sfmskywalker

**Comment by sebastienros** [comment]
I don't think there is a better way.

**Comment by hannan-azam** [comment]
@sebastienros  do i need to push the changes to 1.10.2 separately?

**Comment by sebastienros** [comment]
No, I will merge to 1.10.2
