### ISSUE TITLE
Support multiple contexts for entries in .po files

### ISSUE THREAD

**Issue by pszmyd** [OrchardCMS/Orchard#6322]
Latest versions of POEdit (and most likely other tools) perform entry de-duplication on save, resulting in entries being changed to eg.

```
#. "Date"
#: ~/Core/Common/Views/EditorTemplates/DateTimeEditor.cshtml
#: ~/Core/Reports/Views/Admin/Display.cshtml
#: ~/Core/Reports/Views/Admin/Index.cshtml
msgid "Date"
msgstr "Date"
```

The above is a single entry with multiple contexts. This is still a valid entry and we should support it. As far as I can tell this de-duplication is a requirement for compilation to .mo files (which POEdit supports and performs).

**Comment by MpDzik** [comment]
+1

**Comment by jburgard** [comment]
With this change, it looks like support for generic key(|some-key) has been removed. Is this intended?  If not, I can submit a pull request.

**Comment by jburgard** [comment]
Issue has been reported on [6363](https://github.com/OrchardCMS/Orchard/issues/6363) with pull request.
