### ISSUE TITLE
ajaxonly for Contollers

### ISSUE THREAD

**Issue by KANekT** [OrchardCMS/Orchard#6325]
Do you plan add attribute [ajaxonly] for Contollers?

Example http://weblogs.asp.net/imranbaloch/adding-ajaxonly-filter-in-asp-net-web-api

**Comment by sebastienros** [comment]
What would be the advantage of such an attribute? I don't think it adds any value to your service to use this, and by having that we would encourage its usage which I think is wrong.

**Comment by KANekT** [comment]
In projects often only need to use Ajax requests, and ignoring not Ajax ...

**Comment by sebastienros** [comment]
This doesn't provide any more security, and I can only see the advantage to be providing a message to a user. Hence we won't do it, but you can create one for your own usage.
