### ISSUE TITLE
Pbs in Orchard.resources (Dev)

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6329]
Orchard.Ressources is missing somes files for bootstrap and I get

"The controller for path '/OrchardLocal/Modules/Orchard.Resources/fonts/glyphicons-halflings-regular.eot' was not found or does not implement IController."

Note that the message itself is strange.

many problems also with breaking change in Jquery where the old ressources no more exist and we only get error running

jQueryUI_Core no more exists
some other resources have changed their name as jQueryUI_Widget which became jQueryUI_Widgets

and always the same problem to input a date (tons of includes to add depending what we want).

**Comment by CSurieux** [comment]
Thanks Sebastian fixing this for 1.10, exptecting it in Dev asap ? I am not sure it has no consequences on the DateTime input stuf.

**Comment by sebastienros** [comment]
We checked DateTime was working when we applied the fix. Yes it will be merged to dev very shortly.
