### ISSUE TITLE
podcast module

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/Orchard#6332]
is there any podcast module for orchard cms?

**Comment by sebastienros** [comment]
1- What would a podcast module do?
2- We assume you can just a create a list with a Podcast content type and custom fields for the media. And you can even use the RSSPart to customize the RSS feed from a projection to render the media url in it.
3- You should not use the issue tracker to ask question, feel free to drop on our chat and forums, you'll even get faster answers.
