### ISSUE TITLE
Ability to add placeholder to Dynamic Form fields

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/Orchard#6336]
Add the ability to specify a placeholder (http://www.w3schools.com/tags/att_input_placeholder.asp) for applicable Dynamic Form fields. The same issue for content fields: #5943

**Comment by ramiassi** [comment]
This article explains something about this:
[http://mdameer.com/orchard-cms/how-to-add-placeholder-to-text-field-in-dynamic-forms](http://mdameer.com/orchard-cms/how-to-add-placeholder-to-text-field-in-dynamic-forms)
Unfortunately I could not get it working. 
do you have any idea how can I add this attribute to the dynamic forms elements?
