### ISSUE TITLE
Clean up CalendarsPickerLocalization.cshtml

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#6338]
References to the sc
![2016-02-04_21-50-04](https://cloud.githubusercontent.com/assets/938393/12829330/cb5a1902-cb89-11e5-91ae-732dc12b8d94.png)
ript `"calendars/jquery.calendars*"` should be removed.

**Comment by DanielStolt** [comment]
No, not removed. The files are needed. They need to be moved into Orchard.Resources and the paths should be corrected.
