### ISSUE TITLE
ImageProfileManager null reference with Profile

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/Orchard#6343]
1.10

I have code that call the MediaUrl method with just the profile.  After upgrading to 1.10, there is null reference.

In ImageProfileManager.cs, Line 115, GetImageProfileUrl method:
`    if (customFilters == null || !customFilters.Any()) {`
throws null reference when calling with something like
`    @Display.MediaUrl(Profile: "myProfile", Path:Url.Content("~/Media/Default/Logo.jpg"))`

The issue was caused by when arugment "customFilter" became "params customFilters".  The added check `!customFilters.Any()` didn't account for when null was passed into the params.  So the params array has a null as its item.

If someone can guide me how to make PR (because it is a cool thing to do) =P, I can create one.

Otherwise, the fix is as below.  Not sure if it fix all scenarios though:
`    if ( customFilters == null || !customFilters.Any( c => c != null )) { `

Thanks!

**Comment by infofromca** [comment]
relate to #6231
