### ISSUE TITLE
Parts_Widgets_WidegetBagPart

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#6344]
I was looking around the codebase and noticed this in the placements.info for Orchard.Widgets:

    <Place Parts_Widgets_WidegetBagPart="Content:5"/>

Looks like a typo but I can't figure out where else it's used so I don't know?

**Comment by sebastienros** [comment]
Probably a left over. If you can't find anything related to WidgetBag then we can remove it.

**Comment by rtpHarry** [comment]
No I did a solution wide search and it's not mentioned, I'll create a PR to zap it.
