### ISSUE TITLE
Module updates not working anymore

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard#6345]
In the admin, if you enable 'Package updates' and go the the tab 'Updates' of the gallery (Packaging/GalleryUpdates/ModulesUpdates), there is an error.

It seems to try to download a package but fails and displays the html source.

Note: I replaced the gallery url by the correct one (https://gallery.orchardproject.net/api/FeedService) but I don't know if it causes the error.

The url of the downloads (in the 'Gallery' tab) is also weird because it shows wrong urls (http://orchardgallery.azurewebsites.net/Download/...) and I don't know why it is using this base url that isn't configured anywhere in the settings.

**Comment by sunzip** [comment]
after my debug, found that "The specified package could not be found..."
