### ISSUE TITLE
Impossible to create its own WorkContextStateProvider from a module ?

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6352]
I am trying to use a WorkContextStateProvider for a useful value in my module but GetState<T>(string name) always return a default value because my implementation class inheriting from IWorkContextStateProvider is never loaded by the Lazy loader used by the implementation.
It is well referenced in the list but has a null value, so it is never called ?

Any idea ? An Autofac Pb ? I found no error log ? It is a very classic code  using the CurrentCulture model ?
I even tried to add a lazy loader on the sole servicesthat its Ctor uses but no improvement?

It looks like a bug.

**Comment by sebastienros** [comment]
Right, that should just work. Let's try to repro.

**Comment by CSurieux** [comment]
I was using a Currency object, which is a structure, in the GET<T>
`public Func<WorkContext,T> Get<T>(string name) {
            if (name == "CurrentCurrency") {
                return ctx => (T)(object)_currencyManager.GetCurrentCurrency(ctx.HttpContext);
            }
            return null;
        }`

when I changed to a string, it started working ???
