### ISSUE TITLE
allow need more mime type to uplaod

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6357]
such as the standard ogg, webm

**Comment by donaldboulton** [comment]
Add mime type to root web.config.
Answer: [http://madskristensen.net/post/prepare-webconfig-for-html5-and-css3](http://madskristensen.net/post/prepare-webconfig-for-html5-and-css3](url))

**Comment by sebastienros** [comment]
This is the recommended way to do it. We didn't want to add too many of them, there is an issue with the full discussion if you search for it it should be easy to find it.
