### ISSUE TITLE
Github 1.9.3: 'Vandelay Industries' compile error 

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#6359]
based on several recommendations (Dynamic Form, Image Editor) I downloaded Orchard 1.9.3 from Github. All seems ok except when downloading the 'Vandelay Industries' Module from the Gallery -  I get following compile error in 'DefaultExtensionCompiler.cs' (line 116):
error msg:
An exception of type 'Orchard.OrchardCoreException' occurred in Orchard.Framework.dll but was not handled in user code
Additional information: Error compiling module "Vandelay.Industries" from file "/OrchardLocal/Modules/Vandelay.Industries/Vandelay.Industries.csproj":
Assembly reference 'System.Data.DataSetExtensions' for project '/OrchardLocal/Modules/Vandelay.Industries/Vandelay.Industries.csproj' cannot be loaded
end error msg
PS: same issue when downloading/compiling 'Bing Maps'!

Knowing that 1.9.3 is not released officially ... somebody might have a hint
thanks for your time, ed

**Comment by donaldboulton** [comment]
Got the same thing and for many other older modules.

**Comment by Piedone** [comment]
Did you see concrete compile errors in the logs? What happens if you add the project to the solution and try to build it manually?

Also you might need to update such old modules on Orchard upgrades, this time maybe the .NET target version changed.

**Comment by edikaufmann** [comment]
I've seen that the TargetNetwork in 1.9.3. is 'v4.5.2' (config.web)!. In .csproj: Module 'Vandelay' is v4.5; Bing Maps v4.0; changing it didn't help. Also,  I did do a fresh download from the Gallery!
see also the attached file Log.txt
Any ideas .... thanks for your time, ed

[Log.txt](https://github.com/OrchardCMS/Orchard/files/122742/Log.txt)

**Comment by Piedone** [comment]
I have a hunch that you just have to remove the otherwise unused System.Data.DataSetExtensions reference from the module.

**Comment by edikaufmann** [comment]
Same issue when removing <Reference Include="System.Data.DataSetExtensions" />
from Vandelay .. .csproj
Do you think of other referencies?

**Comment by donaldboulton** [comment]
This same reference, "System.Data.DataSetExtensions", is in almost all of the 1.9.3 core modules along with targetFramework="4.5.1" in modules = and in all dll.config's and web.config's. SO these need to be changed, tried a bulk replace of targetFramework="4.5.1" to targetFramework="4.5.2"  then nothing worked??? Not even the logs.

**Comment by donaldboulton** [comment]
Removed System.Data.DataSetExtensions and now get error of:
The assembly reference 'System.Web.Entity' could not be loaded for module ' Any and all additional modules besides core modules'.
No .dll called System.Web.Entity.dll. Update references to <add assembly="System.Web.Entity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089"/>
Now everything works.

**Comment by donaldboulton** [comment]
Solved see git hub post: https://github.com/OrchardCMS/Orchard/issues/6359

On Tue, Feb 9, 2016 at 8:14 AM, Ed Kaufmann <notifications@github.com>
wrote:

> Same issue when removing
> from Vandelay .. .csproj
> Do you think of other referencies?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OrchardCMS/Orchard/issues/6359#issuecomment-181880630>
> .
>



-- 
Donald W. Boulton

**Comment by sebastienros** [comment]
The issue is that at some point the MarkdownSharp dll was replaced by the source code (a single file) as we were not using nuget and the package was not updated and not in sync with the source code. The solution is to reference the MArkdown module from Vandalay.Industries. At the same time we will fix 1.10.x to include this library from Nuget as we are now using it.
