### ISSUE TITLE
Orchard 1.10 / 1.9.3 Media 'ImageEditor': Image not shown 

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#6361]
couple weeks ago I opened #6285 on a 'similar' issue. Sebastien recommended to use 1.10 / 1.9.3. from github.
I tried  with both Github versions. On both I see the ImageEditor button
BUT: when clicking, the Image does NOT appear ; there is only the little 'cross' shown!

I loaded some images via Media->Import; they appear correct when clicking the appropriate folder! The 'Edit' function works correctly!
PS: I did NOT load any additional Modules etc. and I realize that 'Media' and 'MediaPicker' is labled 'depreciated': I explicitely disabled them!

WebMatrix 3, VS2015 or deployed (ISP i.e not on Azure)

Following Modules (and its prereq's) are enabled:
 Media Library
 Media Library Search
 Media Processing
 Image Editor

 What stupid thin am I missing, doing wrong?
 Thanks for your time and hints, ed

**Comment by sebastienros** [comment]
Can you look at the network trace on chrome to see what is the url it can't load?

**Comment by edikaufmann** [comment]
Below info is from Edge (I certainly could test with chrome).  Thanks for your time ... ed
After Media --> Pictures(my folder) the HTML source:
<input type="hidden" id="image-editor-url" value="/Media/Default/pictures/flugzeug.JPG"/>

After clicking the image: HTML source
<div id="image-editor-container" class="editor-shadow">
        <div id="image-editor-image-wrapper" >
               <img id="image-editor-image" class="canvas-shadow" 
                src="/Admin/Orchard.ImageEditor/Proxy?url=http%3A%2F%2Flocalhost%3A30321%2FOrchardLocal%2FMedia%2FDefault%2Fpictures%2Fflugzeug.JPG">    
        </div>
    </div>

The Edge F12 --> Network trace:
Name	Protocol	Method	Result	Content type	Received	Time	Initiator
http://localhost:63053/Admin/Orchard.ImageEditor/Index/19?returnUrl=http%3A%2F%2Flocalhost%3A63053%2FAdmin%2FOrchard.MediaLibrary%3FfolderPath%3Dpictures

**Comment by sebastienros** [comment]
Does the /Media/Default/pictures/flugzeug.JPG image exist ?

**Comment by sebastienros** [comment]
Or even better, are you able to provide some repro steps from a vanilla download of 1.9.3/1.10, meaning, clone to a new folder and stat from a clean setup ?

**Comment by edikaufmann** [comment]
After Media --> Pictures(my folder) I see my image. When clicking the image, on the right side (PROPERTIES) I see my Image, the ' Edit' AND the 'Image Editor' button etc. So the image is there.

In fact I started with a fresh copy 1.9.3 AND 1.10. Well, to confirm I do it again on a freshly downloaded 1.9.3 from GitHub. Then I only 'Import' one picture in one newly created media folder! ... I let you know.

**Comment by edikaufmann** [comment]
my test sequence on VS2015:
- freshly downloaded 1.9.3 from GitHub
- enabled the necessary modules
- created one Media folder (pictures) and imported 4 images
- the 'Image Editor' shows my image; I can eg resize -> all ok!
Now I want to create my Web version:
- using 'publish' in VS2015 --> runs without any errors!
- in WebMatrix it loads ok
- however, the 'Image Editor' doesn't work --> I still get the little cross
PS: on my tests before I always had some user modules loaded like Bing Maps, facebook, Vandelay Industries etc. Sorry, that might have messed up the tests.
When checking the Media folders I can see the images in: Media --> pictures, Media Storage and in the profile!
your time hints are appreciated, ed

**Comment by donaldboulton** [comment]
Works fine for me in 1.9.3 and 1.10. I am using Orchard.Web.zip not source.

**Comment by donaldboulton** [comment]
Did you upgrade infoset's and migrate images with Orchard Upgrade?

**Comment by edikaufmann** [comment]
for some other reason I downloaded a new 1.10 from GitHub, interesting:
On VS2015
importing couple pictures --> 'Image Editor': OK
after publishing as Orchard.Web (WebMartrix) -- > loading some pictures --> 'Image Editor' : won't work

donaldboulton: I dont't think I need to care about 'infoset', do I?  I'm doing this with a fresh 1.10 !

**Comment by dcinzona** [comment]
@edikaufmann what error(s), if any, do you get?  Anything in the developer console?

**Comment by edikaufmann** [comment]
In VS2015:
remember here 'Image Editor' works; kind of!
e.g. when clicking filters and set 'brightness from 0 (default) to eg 1 --> the picture is totally greyed out!
e.g. 'preset' doesn't show anything!
but
resize, rotate works

In WebMatrix:
I do Not get any errors (not in console nor App_data Log)  --> i.e. only the little cross!.

PS: to me the HTML code looks alike! !the 1.10 download I did on Feb 24 !

**Comment by sfmskywalker** [comment]
Is the Base URL of the site settings the same as the actual URL in the browser?

**Comment by edikaufmann** [comment]
Sipke, thanks a million! My fault; due to a 'hack' on the browser (not related to orchard !) under very special circumstances I changed the browser URL !
I apologize to everybody who spent time on this, ed
