### ISSUE TITLE
Workflow : Missing view for EditProperties

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard#6366]
In 1.9.x and 1.10, you can't create a workflow or edit the properties anymore .

The create button redirects to 'Workflows/EditProperties' but there is no EditProperties.cshtml view.
The 'Properties' link in the worflows list also redirects to Workflows/EditProperties?id=...

This seems to come from a wrong merge from dev : https://github.com/OrchardCMS/Orchard/commit/56032dd8

@sfmskywalker : can you check please?

**Comment by sfmskywalker** [comment]
I checked on both branches, but was unable to reproduce the issue. In both cases I am redirected to **/Workflows/EditActivity**. Can anyone else reproduce this?

**Comment by agriffard** [comment]
OK found the issue:
views\Admin\EditProperties.cshtml is just not included in the .csproj so it hasn't been generated in deploy.
