### ISSUE TITLE
Create ContentItem continue to create even when an exception is raised in one of its parts driver

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6371]
So we get strange data in the DB.
Repro: create a fake part throwing in its driver editor update and attach it to something existing and Ok and try to create.

**Comment by sebastienros** [comment]
This is by design, handlers and drivers which are failing are not interrupting the events to be processed. The design is to catch any expected exception and call `Model.AddModelError` which will prevent the content item from being updated.

**Comment by CSurieux** [comment]
I know but I think it is an error, some external element added could easily add and error and the database is corrupted. It should be secured by system conception.
