### ISSUE TITLE
Owin middleware not detected in Azure environment

### ISSUE THREAD

**Issue by kumards** [OrchardCMS/Orchard#6373]
Hi,

For some reason Orchard.Owin.Startup file is not getting picked up by the Owin framework when I try to test Orchard under Azure Cloud Service environment.

I noticed that <add key="owin:AppStartup" value="Orchard.Owin.Startup, Orchard.Framework"/> entry is missing in the web.config file of Orchard.Azure.Web. Adding this entry didn't help either. I also tried adding assembly reference to Microsoft.Owin.Hosting.dll.

Any help is appreciated on this.

**Background:** I am trying to use SignalR within Orchard based on https://bitbucket.org/Proligence/proligence.signalr-git/wiki/Home. But SignalR does not get registered in Azure Cloud Service environment.

**Comment by sebastienros** [comment]
Tagging the issue just to ensure the web.config is correct.

**Comment by donaldboulton** [comment]
I get the same errors without having trust level set to full and a 256 bit machine key

**Comment by kumards** [comment]
@donaldboulton Did you set these entries in web.config?

Something like 
```
 <machineKey validationKey="" decryptionKey="" validation="SHA1" decryption="AES"/>
    <trust level="Full"/>
```

**Comment by donaldboulton** [comment]
yes just below system.web
go to[http://www.a2zmenu.com/utility/Machine-Key-Generator.aspx](url)
and generate a 256 bit key. I use 512 bit HMACSHA512 so Chrome will remember my passwords = Chrome Issues. Or go to you App_Data/ SItes/ Default/ settings.txt file and copy that key for your validationKey and decryptionKey.

**Comment by donaldboulton** [comment]
Noticed on 1.9.3 property pages Microsoft.Owin.Host.SystemWeb is referenced in GAC and in bin, might be the issue, cannot get 1.9.3 to start 1.10 works.
Found this post on SignalR and MVC5, might be your issue.
[http://www.codeproject.com/Articles/727052/When-MVC-SignalR-and-NuGet-Just-Won-t-Get-Along](url)

**Comment by kumards** [comment]
Thanks @donaldboulton . Assembly redirection is something I already tried. I would like to retry with 256 bit encryption key.

**Comment by kumards** [comment]
@donaldboulton Did you mean you had to add the above mentioned web.config entries to make them work on IIS on shared server? Not on Azure setup?

I am facing this owin issue only in Azure setup.

**Comment by dcinzona** [comment]
We use OWIN in Azure.  We had issues with the machine key providers as well.  This is due to how Azure architecture is set up.  Not sure if this is exactly what is happening with you, but for use to be able to protect the OWIN cookie, we had to create a machine key data protector class.
https://github.com/IdentityServer/IdentityServer3/issues/1710

**Comment by kumards** [comment]
@sebastienros you were spot on. It was an issue with the inconsistent web.config. 
I just had to match Orchard.Web project's web.config with Orchard.Azure.Web project's web.config and add a new library reference to Microsoft.Owin.Security.dll.
