### ISSUE TITLE
Net Compilation is .vb not C#

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6387]
IIS manager Net Compilation says Orchard is .vb not C#. Change it to C# and see the speed increase.

What up with this, its always has been .vb since 1.0.

**Comment by sebastienros** [comment]
Can you provide some repro steps? I am not aware of this feature in IIS.

**Comment by donaldboulton** [comment]
Just to tell the compiler to use C# it figures it out anyway.
changing it is `<compilation batch="true" defaultLanguage="c# numRecompilesBeforeAppRestart="250" optimizeCompilations="true" targetFramework="4.5.2">`
No C# statement makes IIS think about it for a nano-second reads the code and determines C#, I just like to tell it what its compiling. Most likely makes no difference.
