### ISSUE TITLE
Draftable should only control Save button

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6388]
if i does not misunderstand, Draftable should only control Save button. and we  should always have publish  button.
i will do a PR for 1.9.3

**Comment by sebastienros** [comment]
Semantics ... one could argue you Publish a draft. If everything is published, there is no Publish verb per se. We'll see what others have to say.

**Comment by bleroy** [comment]
You also publish a new version. It would more consistent and less confusing to have "publish" that always results in the contents of the editor going online, and a "save as draft" button.

**Comment by sfmskywalker** [comment]
Having a "Save as draft" and "Publish" button seems the most straight forward option. If a content type is not draftable, then perhaps only the "Publish" button should be displayed, since the content item would be published immediately.

**Comment by infofromca** [comment]
I agree with @sfmskywalker 
if need , i can do more commit

**Comment by sebastienros** [comment]
Action:
- Change "Save" to "Save as draft"
- Show Publish all the time.

Example:
For a draftable content type, we'll have "Save as draft" and "Publish"
For a non-draftable CT we'll have "Publish"

**Comment by infofromca** [comment]
added new commit for
Action:

Change "Save" to "Save Draft"
Show Publish all the time.
