### ISSUE TITLE
the widgets works well only on homepage but doesn't work on blog posts for the corresponding blog.

### ISSUE THREAD

**Issue by pallavigm22** [OrchardCMS/Orchard#6402]
the widgets works well only on homepage but doesn't work on blog posts for the corresponding blog.

**Comment by infofromca** [comment]
similar to #6392

**Comment by pallavigm22** [comment]
I have certain blog posts under one blog so i have created a widget for it. i dont want my blog posts to use the layout of the blog. how do i do that?

**Comment by CSurieux** [comment]
Use alternates maybe

**Comment by sebastienros** [comment]
Please file an issue with the explicit problem and some repro steps. There is nothing we can help with based on the description.
