### ISSUE TITLE
NHibernate doesn't support ulong types

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6404]
I tried to Add a column of type ulong in a recordPart and get this nice NH baby on the migration
{"Dialect does not support DbType.UInt64\r\nParameter name: typecode"}

**Comment by CSurieux** [comment]
Well... thanks... Title not in the line of the High Castle ...

**Comment by sebastienros** [comment]
Nope, it's not

**Comment by bleroy** [comment]
Seriously though, beyond the Godwin point, bug titles need to be descriptive of the problem, in order to be efficiently searchable.

**Comment by sebastienros** [comment]
Is there anything we can do as the dialect is in NH? We could only automatically remap it to some other type, but I assume getting the exception would still force you to change the type, so why bother?

**Comment by jmroyb** [comment]
Hi,

Still not supported in 5.2.1.

Do you plan support it soon? 

Thanks
