### ISSUE TITLE
[1.10] Packages.config should reference target framework 452 not 451

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#6406]
Just looking at the Themes project, but it appears to be the case for most of the other projects (if not all)
https://github.com/OrchardCMS/Orchard/blob/1.10/src/Orchard.Web/Themes/packages.config
Not sure if this causes any problems with build, but may be good to have them update the framework where appropriate.  This is quite an overhaul because it may not be readily apparent which packages have target framework support for 452

**Comment by dcinzona** [comment]
I'm going through trying to add our custom modules to a vanilla install of 1.10 and found this command to be somewhat helpful after retargeting the framework version: `Update-Package –reinstall`

**Comment by dcinzona** [comment]
Although, I do think that once this is done, keeping the packages in sync will be a breeze.

**Comment by donaldboulton** [comment]
Used 
Update-Package –reinstall
works perfect. Thanks for that info. 
Still some things in 1.10 core modules targeting `<TargetFrameworkVersion>v4.5.1</TargetFrameworkVersion>` in project files
and
`<compilation targetFramework="4.5.1">` in some config files. 
Have to add Orchard.jQuary to get most non core modules to work

**Comment by dcinzona** [comment]
Regarding the Target Framework in the csproj files, I didn't have that issue with a clean download of 1.10.  Everything was pointing to 4.5.2 for me.

**Comment by dcinzona** [comment]
@donaldboulton Which modules require Orchard.jQuery?  I think that module is deprecated in 1.10 and should not be required by any other core modules.  I would check but I'm currently running the nuget package reinstall

**Comment by dcinzona** [comment]
Oh, I think Orchard.Resources is the new Orchard.jQuery... I read what you wrote wrong, you should update the non-core modules to use Resources I guess?

**Comment by donaldboulton** [comment]
Just added Orchard.jQuary from 1.9.3 as I use some non core modules that require it and re targeting to Orchard.Resources did not work, not sure but has something to do with changed manifest files
from the Orchard.jQuary ResourceManifest.cs to packages.config  and adding for jQuary in Orchard.Resounces a jQuery.cs file for manifests.
see issue 
#6393 [https://github.com/OrchardCMS/Orchard/issues/6393](url)

**Comment by dcinzona** [comment]
That module should exist in 1.10, just deprecated.  It's been updated to use target framework 4.5.2.  in 1.9.3, it uses 4.5.1, which is what would cause compilation errors.

**Comment by donaldboulton** [comment]
Was not in my Orchard.Web.zip file. It is in the source download. Changed it and all my non-core modules to 4.5.2 mvc 5.2.3.

**Comment by dcinzona** [comment]
Ah, ok, that's an issue in it of itself.  It should be in the zip cc/ @sebastienros

**Comment by donaldboulton** [comment]
None of the packages were any different on using...
Update-Package –reinstall
It did check then uninstall then reinstall the same packages; the only thing it changed was the packages.config reference for targetFramework="net451" to targetFramework="net452"

**Comment by dcinzona** [comment]
@donaldboulton I forgot...
Orchard.jQuery has been removed and replaced by Orchard.Resources.  Try updating your custom modules to use Orchard.Resources instead of Orchard.jQuery

**Comment by donaldboulton** [comment]
Orchard.jQuary and many other custom modules have a error in 1.10, a dependency of `<Reference Include="System.Data.DataSetExtensions" />` which is removed in root web.config, so I removed the reference in Orchard.jQuary then worked.
Some Custom Modules have the same reference and also have a reference to `<Reference Include="System.Web.Entity" />` which is not referenced in web.config, so add a reference to`<add assembly="System.Web.Entity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />. And I got most non-core modules to work except one of my favorites iDeliverable widgets, cannot figure it out, @sfmskywalker is aware of it and working on it.

**Comment by dcinzona** [comment]
Ah cool. Ok.  Yeah, I had to go through and make some changes to our custom modules as well, to get them to work with 1.10.
The irony is that some files in Orchard.Resources reference Orchard.jQuery.  I submitted a bug for that here: https://github.com/OrchardCMS/Orchard/issues/6416

**Comment by agriffard** [comment]
I have a similar issue installing 1.10.1 on my server : 

```
Orchard.Environment.DefaultAssemblyLoader - (null) - Error loading assembly 'System.Data.DataSetExtensions' [(null)]
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.DataSetExtensions' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Data.DataSetExtensions'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Orchard.Environment.DefaultAssemblyLoader.LoadWorker(String shortName, String fullName)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Orchard.Environment.DefaultAssemblyLoader.Load(String assemblyName)
```

**Comment by agriffard** [comment]
An instance with 1.10 was working. I updated using Orchard.Web.1.10.1.zip in https://github.com/orchardcms/orchard/releases

**Comment by donaldboulton** [comment]
In Root web.config just change `<remove assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />`
To:
`<add assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />`
`<add assembly="System.Web.Entity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />`
A Lot of non-core modules require both System.Data.DataSetExtensions and System.Web.Entity.
Yesterdays dev build Orchard.Layouts is asking for System.Transactions as:
`<add` assembly="System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />`
All three should be added for backwards compatibility, so all the users of Orchard do not have to figure this out.

**Comment by agriffard** [comment]
I had to add these namespaces to web.config :
```
<add assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />
                <add assembly="System.Data.Services.Client, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
                <add assembly="System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
				<add assembly="System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
				<add assembly="System.Web.Entity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />
```
and remove 

`                <remove assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />`

And remove Orchard.Dashboards and Orchard.DynamicForms because the dependency to Orchard.Layouts prevented to compile.

@sfmskywalker : can you help us to determine what has to be done to make Orchard.web.1.10.1 work  ?

**Comment by drosenba** [comment]
My site does come up, but, I still see an error in my \App_Data\Logs\orchard-debug-2017.01.18.log

2017-01-18 13:17:05,171 [7] Orchard.Environment.DefaultBuildManager - Default - WARN Error when compiling assembly under ~/Modules/Orchard.Dashboards/Orchard.Dashboards.csproj.
System.Configuration.ConfigurationErrorsException: Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified. (C:\Users\dennis\Documents\My Web Sites\Orchard\modules\orchard.dashboards\web.config line 35) ---> System.IO.FileNotFoundException: Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified.
...
