### ISSUE TITLE
reordering of content inside blog post

### ISSUE THREAD

**Issue by pallavigm22** [OrchardCMS/Orchard#6408]
![sc9](https://cloud.githubusercontent.com/assets/16664571/13104525/99c9d5e6-d555-11e5-867f-8e0ba2a75128.png)
![sc10](https://cloud.githubusercontent.com/assets/16664571/13104535/a6eebe8a-d555-11e5-83a4-b7e324675798.png)

**Comment by pallavigm22** [comment]
guys in the above screenshot i want my content to look like the first screenshot. Could you help me please?

**Comment by sebastienros** [comment]
Not and issue.
