### ISSUE TITLE
Where to implment data verification or any business validation

### ISSUE THREAD

**Issue by kumards** [OrchardCMS/Orchard#6412]
Hi,

I am implementing a solution on Orchard framework. I extensively use REST APIs to do CRUD on the content items and parts.

I have been pondering where to invoke business validation on a data that user has submitted through REST API.

I have written some business validation scenarios in a class something like below

```
public interface IRatingValidationService : IDependency
    {
        bool IsValidRating(ContentItem content);
    }
```

Should I be invoking this service 
1. In the API controller to make sure the submitted data is valid 
2. In the ContentHandler events to make sure the submitted data is valid
3. None of them listed above

The problem with approach 1 is, every controller action which accepts the rating data, has to invoke the same validation service. I see a code redundancy here.

If I go through the approach 2, the exception thrown in the validation service is suppressed in the `InvokeExtensions.Invoke` method. This does not use `IExceptionPolicy `to handle the exception so that I can override the behavior.

**Comment by sebastienros** [comment]
Can you please ask the question on the forum or stackoverflow. We try to keep the github issues for actual bug reports or feature requests.

**Comment by kumards** [comment]
You got it, man. Here it is.
http://stackoverflow.com/questions/35491683/where-to-implment-data-verification-or-any-business-validation
