### ISSUE TITLE
[1.10] Orchard.jQuery module is not in Zip but required by Orchard.Resources

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#6416]
Here:
https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Resources/Views/CalendarsPickerLocalization.cshtml#L74
And here:
https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Resources/Views/TimeEntryLocalization.cshtml#L45

**Comment by sebastienros** [comment]
If these files are really needed we need them in Resources.
