### ISSUE TITLE
can not add tenant name first time

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6434]
i should click EDIT button again to add and save
![addtenant](https://cloud.githubusercontent.com/assets/297675/13194298/6114bc8c-d75a-11e5-9583-18ac864a424a.png)

**Comment by Piedone** [comment]
You mean the tenant host/prefix is not saved when the tenant is created?

**Comment by infofromca** [comment]
the first field--i remember host ---not save ,see collaboration2

**Comment by sebastienros** [comment]
Please provide some repro steps with what you are expecting to see. Thanks.

**Comment by infofromca** [comment]
1-enable tenancy
2--create tenant
3--fill in RealEstateWorld in Host field
4--save
5--get this:
![tenant-1](https://cloud.githubusercontent.com/assets/297675/13342642/c49f1f16-dc11-11e5-98d7-216b84c5d8f4.png)

**Comment by infofromca** [comment]
6--clike Edit
can see this
![tenant-2](https://cloud.githubusercontent.com/assets/297675/13342662/e88466b6-dc11-11e5-9c1e-feb4c04e28fa.png)

**Comment by infofromca** [comment]
7--fill in RealEstateWorld in Host field
8--save
now ok

**Comment by dcinzona** [comment]
This works fine for me on `dev`.  What branch are you using?

**Comment by infofromca** [comment]
1.9.x and 1.10
localhost

**Comment by dcinzona** [comment]
Thats interesting, I am running on dev on localhost and also 1.10 - no issues with adding a tenant.  You don't have any custom modules do you?  Could they be overriding the tenant service?

**Comment by infofromca** [comment]
for 1.9.x, it is clean version

**Comment by infofromca** [comment]
my mistake, 
i did not fill in host field, so close it
