### ISSUE TITLE
[1.10] (Sorry) httpContextAccessor.Current().GetOwinContext throws an error

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#6438]
Hopefully this is not a 1.10 issue but an issue with my code... 
```c#
 var currentContext = _httpContextAccessor.Current();
 //This can be null in background processes
 if (currentContext == null) {
     return null;
 }
 var owinContext = currentContext.GetOwinContext();
```
`currentContext.GetOwinContext();` throws `System.InvalidOperationException: No owin.Environment item was found in the context.`
When I inspect the currentContext instance, Items.Count = 0.  

This seems to be happening when the request is a background process.

#### EDIT: More info
Looks like this is happening during the migration process for updating Orchard.Framework - error caused due to duplicates in the database, then trying to log those errors (and get the current user while doing that).

**Comment by Piedone** [comment]
So when does this piece of code run exactly?

**Comment by dcinzona** [comment]
IAuthenticationService GetAuthenticatedUser()
```c#
 public IUser GetAuthenticatedUser() {

            _signedInUser = CheckOwinContext();

            if (_signedInUser != null) {
                return _signedInUser;
            }
            else {
                //SignOut();
                return _signedInUser;
            }
        }

        private IUser CheckOwinContext() {
            var currentContext = _httpContextAccessor.Current();
            //This can be null in background processes
            if (currentContext == null) {
                return null;
            }

            if (currentContext.Items.Count == 0) {
                return null;
            }

            var owinContext = currentContext.GetOwinContext();
            if(owinContext == null) {
                return null;
            }
            var owinUser = owinContext.Authentication.User;
            if (owinUser == null || !owinUser.Identity.IsAuthenticated) {
                return null;
            }
            var userId = GetUserIdFromClaimsPrincipal(owinUser);
            var localUser = GetUserByUserId(userId);
            return localUser;
        }
```

**Comment by dcinzona** [comment]
A little more information: I was able to trigger Items.Count  == 0 by updating a content item and saving it, with auditing enabled.  The audit trail event might trigger this is anyone wants to try testing.

**Comment by jtkech** [comment]
Now, even in a background process and you use a _wca or a _hca... a fake `HttpContextBase` is returned. This allow some new capabilities but the fake `HttpContextBase` doesn't implement all properties.

So, sometimes all is ok, sometimes we need to implement a new propertie, but if it doesn't make sense you have to uses the `IsBackgroundContext()` extension that check if null or if a fake context.

    var currentContext = _httpContextAccessor.Current();
    if (currentContext.IsBackgroundContext()) {

When you use `HttpContext.Current` directly, there is another extension (but only in dev) that do the same with an `HttpContext` (not HttpContextBase).

    var context = HttpContext.Current;
    if (context.IsBackgroundHttpContext()) {

Best

**Comment by dcinzona** [comment]
@jtkech That also solves our issue.  I'll implement that solution and close this one out.  Thanks!
