### ISSUE TITLE
Orchard 1.10 Workflows using Timer with 'Send email' --> NOT sent

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#6445]
On a  1.10 downloaded from Github (Feb 2016) I setup a simple Contact form with 'DynamicForm' and a 'Workflow' to send an e-mail.
The e-mail is never sent, no error msg, Workflows shows '1 running' .... for ever!
The details:
- 'Form' (contact) --> Layout --> Form(untitled) --> Name: 'ContactForm'
- In Form(ContactForm) I drag 3 fields (subject, mytext, email)
- Workflows (ContactWF) with: 'Form Submitted' (on!) -> Timer(1min) -> 'Send Mail'
- Send Mail: fields populated with: {FormSubmission.Field:subject} (respectively [email][mytext])
- Submit: shows correctly my 'Show Notification' message.
  Issue: that message is never sent!
- checking 'Workflows': 'ContactWF' shows '1 running' --> forever!
  **However:** when removing the 'timer' in Workflows --> the message is sent correctly!
  PS: my admin --> settings --> email test message works fine!

Thanks for your time and hints, ed

**Comment by BenedekFarkas** [comment]
Do you have any errors in the log?

**Comment by jtkech** [comment]
As i remember, when using the timer activity, you need an existing content item. So, in your form settings you need to check the `Create Content` option and attach a type that you have created. This type needs the same fields and you have to bind your form fields to them. Then, in your email you have to use the tokens related to your content type fields (not the form fields).

Just tried it on a dev branch, it works, the email is sent after the timer activity.

But i found other drawbacks for the binding process. Sometimes, the selected content type to create can't be saved correctly. And when ok, the form fields was not bound... But it's another issue.

Best

**Comment by edikaufmann** [comment]
because I'm not mass-mailing I do not need the 'timer' (I guess). And, using  {FormSubmission.Field:subject} works flawlessly. So, somebody knowing more than me investigates on the 'timer' issue!?
And ,no, I didn't find any errors in the log.
anyway thanks for your time, ed

**Comment by dcinzona** [comment]
@edikaufmann what log level are you recording?  Errors only? Can you try switching it to WARN?

**Comment by edikaufmann** [comment]
For clarification: in my 1st msg 'Notification refers to the DynamicForm NOT a 'Notify' workflows element!
I do NOT use 'Notify? Only 'SubmitForm' connected to 'Send email'. And again this works fine.
PS: All I'm saying is: as soon as I use a 'Timer' element the msg is NOT sent.

**Comment by infofromca** [comment]
maybe related to #6240

**Comment by dcinzona** [comment]
I'm getting errors with this on production as well.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Orchard.Workflows.Services.WorkflowManager.ExecuteWorkflow(WorkflowContext workflowContext, ActivityRecord activityRecord, IDictionary`2 tokens)
   at Orchard.Workflows.Services.WorkflowManager.StartWorkflow(WorkflowContext workflowContext, ActivityRecord activityRecord, IDictionary`2 tokens)
   at Orchard.Workflows.Services.WorkflowManager.TriggerEvent(String name, IContent target, Func`1 tokensContext)
   at Orchard.Events.DelegateHelper.<>c__DisplayClass16_0`4.<BuildAction>b__0(Object target, Object[] p)
   at Orchard.Events.DefaultOrchardEventBus.TryInvokeMethod(IEventHandler eventHandler, Type interfaceType, String messageName, String interfaceName, String methodName, IDictionary`2 arguments, IEnumerable& returnValue)
   at Orchard.Events.DefaultOrchardEventBus.TryNotifyHandler(IEventHandler eventHandler, String messageName, String interfaceName, String methodName, IDictionary`2 eventData, IEnumerable& returnValue)
```

**Comment by jtkech** [comment]
As said above (just retried on last dev), the timer activity need a content item passed by the previous activity. This is not the case on form submission if you don't use the `CreateContent` option and maybe with other activities that don't pass a content item to the flow.

The issue happens in `TimerActivity.Sweep()` as described in this other issue #6240 by @neTp9c and notified by @infofromca. **I can do a simple PR to add a null check here.**

That said, for @edikaufmann, to send an email after a timer, the `CreateContent` option needs to be used with a selected content type with the same fields, and the form fields need to be bound to them. Then, in the email activity we have to use the tokens related to the created content item.

But in the last dev i was not able to bind form fields, **i will open another issue for this.**

@dcinzona in your trace i can see the WorkflowManger executing but not sure it's related to the timer activity.

Best.

**Comment by dcinzona** [comment]
I think we were getting this because Workflows has been split up to new features, one of which is Timers.  With that enabled, and the workflow email activity featured enabled, we are no longer seeing this error.

**Comment by BenedekFarkas** [comment]
It's mentioned in the release notes (I didn't find a reference to the Timer specifically, though):

### 1.7.1
- Orchard.Workflows:
    - New Custom Forms event activity
    -Decoupled specialized from the Workflows modules, and moved some activities to specific modules

### 1.7.2
Upgrading from Orchard 1.7.1:
- If you were using the Roles or Comments Workflow Activities you will need to enable the corresponding features: Comments Workflows Activities, Roles Workflows Activities.

Timer was moved to a separate feature in 1.8.1 (the change was made 3 weeks after 1.8 was released), but it's not mentioned in any of the corresponding release notes.

**Comment by dcinzona** [comment]
It's weird because everything was working fine for us in 1.9.2 but after updating to 1.10, we had to re-enable a bunch of workflow features.

**Comment by BenedekFarkas** [comment]
Yes, it seems inconsistent indeed...

**Comment by sebastienros** [comment]
Is enabling Orchard.Workflows.Timers and Orchard,Emails fixes the issue?

**Comment by jtkech** [comment]
@edikaufmann only about your original issue, not about the problem of not enabled features.

You can send an email after a timer activity by applying this PR #6452. But, because after a timer activity, you have to use the `CreateContent` option and bind your fields as described in my previous comments. The binding process can work by applying this PR #6477.

Best

**Comment by Xceno** [comment]
I still experience this issue. I've created a custom Event to trigger the workflow (nothing fancy), then comes the timer and then the sendmail task.

**Comment by sebastienros** [comment]
Thanks for the update and trying to find the issue.

**Comment by sebastienros** [comment]
If by any change you would have repro steps?

**Comment by Xceno** [comment]
I'll write a simple demo module / recipe and throw it on github later today

**Comment by Xceno** [comment]
I have created a very simple DemoModule here: https://github.com/Xceno/Orchard/tree/issue/6445/src/Orchard.Web/Modules/MyModule

You can just clone it and run the setup-recipe from the module.

* The MyModule provides a simple demo ContentPart, a custom activity to trigger a workflow and a custom token provider.
* If you run the demo recipe, you'll get 2 Workflow; one with a timer and one without.
* Simply publish a page with something filled into the "CustomProperty" text box.
* The first workflow will immediately send a mail with successfully resolved tokens. 
* The timer-workflow-task looses the custom token somewhere along the way.

**Remarks**
1. I could not reproduce the YSOD mentioned above though. That may have been a race condition from me hitting F5 like insane while trying to debug it the first time.
2. The Sendmail-Task in my original project will crash, because I resolve the receivers through a custom token. Therefore the receivers are null and the smtp channel crashes accordingly
