### ISSUE TITLE
MediaLibrary: User sub-library doesn't show recent items

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#6446]
When a user has Dashboard access with `ManageOwnMedia` permission (not `ManageMediaContent`), their media items are always placed under the `\Users\<username>` folder structure. When such a user goes to `/Admin/Orchard.MediaLibrary`, they should be able to see their recent media items, but the items are not displayed, even after clicking on "Recent".

The reason behind that is the following:
- Users with `ManageMediaContent` permission see all the media items, so when they see the recent items, that means that their root folder is the absolute root (`folderPath` is empty).
- Users with only `ManageOwnMedia` permission see only their own media items, so their root folder is the user media folder (`folderPath` is `Users\<username>`).
- The logic that determines whether recent items need to be displayed compares the current folder to empty string. That is always a match for media admins (since the root folder for them is empty string) when they open up the Media Library and/or click on "Recent", but never matches for users with `ManageOwnMedia` permission, since their root folder is not an empty string.

I've tested the following implementation locally and works exactly as it should (only small additions, no breaking changes):
- IMediaLibraryService extended with the `GetMediaContentItemsRecursive` and `GetMediaContentItemsCountRecursive` methods that do exactly the same as their non-recursive counterparts, but with `recursive` set to `true` when calling `BuildGetMediaContentItemsQuery` (btw that parameter was never used before, because the only time its value is `true`, it's never evaluated due to another condition check above it).
- `RecentMediaItems` in the `AdminController` uses the new recursive methods.
- The current root folder is passed on from the controller to the UI logic to be able correctly determine if the current folder is user's root folder or not (while not changing the behaviour for admins).

@sebastienros I suggest this to be added to 1.9.3/1.10.

**Comment by dcinzona** [comment]
I posted this here: https://github.com/OrchardCMS/Orchard/issues/6396

This is actually caused because hasFolderPath is set to true (since it's being passed in as an empty string in the view).  This line here: https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Admin/Index.cshtml#L99 should use string.isNullOrWhiteSpace (because on initial load, it's "" by default, not null).  In fact, it will never be null.
https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/AdminController.cs#L44
It defaults to "".

I've tested on my local and confirmed that changing the line
https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Admin/Index.cshtml#L99
to `hasFolderPath: @(!string.IsNullOrWhiteSpace(viewModel.FolderPath) ? "true" : "false"),` resolves the issue for me on 1.10

**Comment by BenedekFarkas** [comment]
I'd rather go with `IsNullOrEmpty`, but the reason behind the fix is correct - it does fix #6396, but not this one. That is because calling the API for recent items is based on the assumption that you need to load recent items when you are in the root (which is determined by checking `folderPath` against empty string). While that is true for users with access to the whole Media (`ManageMediaContent` permission), that is not correct for users restricted to their own Media folder (`ManageOwnMedia` permission) under `Users\<username>`.

**Comment by dcinzona** [comment]
Yup, you're right.

**Comment by BenedekFarkas** [comment]
:shipit: :)

**Comment by dcinzona** [comment]
I posted a comment on the commit:
@BenedekFarkas @sebastienros 
I have an issue now, with this latest change. My account is an administrator (and site admin). Prior to the change, I could see all media folders. Now I don't see any. I have the Manage Media role permission but not the Manage Own Media.
Is this as expected?
![screen shot 2016-02-24 at 6 44 09 am](https://cloud.githubusercontent.com/assets/52411/13284424/313f85a8-dac2-11e5-854e-83910885ae54.png)
![screen shot 2016-02-24 at 6 44 21 am](https://cloud.githubusercontent.com/assets/52411/13284428/34096416-dac2-11e5-97be-f87be2717bf1.png)

**Comment by dcinzona** [comment]
I'm testing this in our QA environment now. For some reason on Dev, I can't see any folders anymore... but on QA I still can, so going to test this update there.

**Comment by dcinzona** [comment]
I take it back, this is working as expected on QA.  Now to troubleshoot my dev environment!

**Comment by BenedekFarkas** [comment]
I think I found what's causing your issue, but that also occurs before the change I applied as well (just tested on 1.10 before my last commit): if you use the navigation in Media Library, items and folder structure are not reloaded until you refresh the page.

**Comment by dcinzona** [comment]
It's weird because I was refreshing, clearing my cache, trying in a private browsing session, restarting debug, etc.

**Comment by BenedekFarkas** [comment]
@sebastienros do you think it's an issue we should care about (see my previous comment)?

**Comment by dcinzona** [comment]
Is it only in 1.10?  The media library works in QA with your changes pushed out and in production without your changes pushed out... but on my local dev environment, I don't get the folder navigation list (even though the folders are there in Azure blob storage).

**Comment by BenedekFarkas** [comment]
The change is only 1.10 according to Sébastien's instructions: since the IMediaLibraryService interface changed (with two additions), it's a breaking change if you have an implementation for that. I'll check locally with Storage Emulator!

**Comment by dcinzona** [comment]
Oh nice! good idea.

**Comment by BenedekFarkas** [comment]
I did a test with a user that has `ManageMediaContent`, but not `ManageOwnContent` explicitly with Storage Emulator and it works for me.

**Comment by dcinzona** [comment]
Ok, that's good.  Hopefully that means it's only an issue with my dev environment and not the code.
