### ISSUE TITLE
When a Part's record contains no other property than its ContentItem Id, NH don't save it when attached to a content item

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6447]
So no way to query, seems a bug.

**Comment by sebastienros** [comment]
Might not be a bug in NH but our convention to detect records.
c.f. http://stackoverflow.com/questions/7840250/orchard-custom-module-model-being-picked-up-by-nhibernate-requiring-virtual/7856337#7856337

I don't recall which class does it, I'll let you look for it.

**Comment by CSurieux** [comment]
Haaa, Ok, dommage.
I was expecting to use it as a marker part as is, being able to Query on it.
But I had to add a useless dummy column to have something stored in its table...and be able to query
