### ISSUE TITLE
[Request] Support Git Patch for minor updates post release

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#6448]
It would be very cool (and significantly speed up merging source) if we had patch files that we could apply to our local to merge diffs between a pre-release and final version.
Thoughts?
Creating the patch:
`git format-patch master --stdout > bug_fixes_since_pre_release.patch`

Checking the patch
`git apply --stat bug_fixes_since_pre_release.patch`
`git apply --check bug_fixes_since_pre_release.patch`

Applying the patch
`git am --signoff < bug_fixes_since_pre_release.patch`

**Comment by sebastienros** [comment]
Suggestion for now is to use multiple remotes and pull Orchard repository then merge on your own branch.
