### ISSUE TITLE
Upgrade 192 to 110: Orchard.Indexing upgrade fails 

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#6457]
I'm running this on the Github version Orchard.Web.1.10.zip (Feb 22)

After the upgrade i.e. copying my App_Data, Media, etc I get the message 'Orchard.Indexing' needs to be upgraded'. When doing so I get below error:

"An error occured while updating the feature Orchard.Indexing: Error while running migration version 3 for Orchard.Indexing"

'Orchard_Framework_DataMigrationRecord' status:
The original 110 carries a  Version '4' 
My old (192), after the Orchard.sdf copy, goes back to Version '2'.
PS: The Migration.cs modules are definitely different.

I tried to do a new 'codegen datamigration Orchard.Indexing' without success!
How do I correctly handle this?
OR, am I to early to report such issues!?
thanks for your time and hints, ed

**Comment by edikaufmann** [comment]
just for curiosity; is the sequence in 'Migrations.cs' correct with:
create(): return 4;
UpdateFrom(): return 2;
UpdateFrom(): return 3;
UpdateFrom(): return 4;

**Comment by dcinzona** [comment]
This was fixed in a later PR.  Can you try from source?  @sebastienros were the zips updated?

**Comment by sebastienros** [comment]
Need to update the zip files.
