### ISSUE TITLE
Orchard 1.10 bug at upgrade migrations?

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard#6464]
Hi, 
I'm upgrading a multitenant site from Orchard 1.9.3 to Orchard 1.10 and I get an exception when FrameworkDataMigrations is executed on UpdateFrom3() step, because it is attempting to create an unique key exception for table ContentItemVersionRecord using ContentItemRecord_id field when in fact here is a lot of rows with this field repeated.

"The CREATE UNIQUE INDEX statement terminated because a duplicate key was found for the object name"

The point is it is normal, because ContentItemVersionRecord table has the different versionsof a content item. The one referenced by ContentItemRecord_id field. So, it is expected to have multiple records for the same ContentItemRecord_id. So, I suspect this is a bug. Am I wrong?

This is the code causing the exception:

`public int UpdateFrom3() {
            SchemaBuilder
                .AlterTable("ContentTypeRecord", table =>
                    table.AddUniqueConstraint("UC_CTR_Name", "Name"))
                .AlterTable("ContentItemVersionRecord", table =>
                    table.AddUniqueConstraint("UC_CIVR_CIRId_Number", "ContentItemRecord_id", "Number"))
                .AlterTable("CultureRecord", table =>
                    table.AddUniqueConstraint("UC_CR_Name", "Culture"));

            return 4;
        }`

I can remove that AlterTable line to make it work, but the question is what was really attempting to do that code?

**Comment by sfmskywalker** [comment]
It is trying to create a unique key constraint based on two columns: "ContentItemRecord_id" and "Number". The combination of these two should be unique. The fact that this migration is failing means the table has duplicate rows. I believe @dcinzona has a SQL script somewhere online that can help de-duplicate this table.

**Comment by jersiovic** [comment]
great thank you

**Comment by dcinzona** [comment]
```sql 
SELECT [Number], [ContentItemRecord_id], COUNT(*) FROM 
[Orchard_Framework_ContentItemVersionRecord] GROUP BY [Number], [ContentItemRecord_id] 
HAVING ( COUNT(*) > 1 )
```
http://docs.orchardproject.net/Documentation/Orchard-1-10.Release-Notes

**Comment by jersiovic** [comment]
Just in case it is useful for someone I have modified the code of  this migrations step to remove my previously duplicated records:

`public int UpdateFrom3() {
            var session = _transactionManager.GetSession();
            int result = 0;
            do {
                
                string prefix = _shellSettings.DataTablePrefix + "_" + Feature.Descriptor.Extension.Id.Replace(".", "_") + "_";
                using (var command = session.Connection.CreateCommand()) {
                    command.CommandText =
                        "DELETE FROM dbo." + prefix + "ContentItemVersionRecord " +
                        "WHERE id IN(SELECT min(id) id FROM dbo." + prefix + "ContentItemVersionRecord " +
                        "GROUP BY ContentItemRecord_id, Number " +
                        "HAVING count(*) > 1)";
                    session.Transaction.Enlist(command);
                    result = command.ExecuteNonQuery();
                }
            } while (result > 0);

            SchemaBuilder
                .AlterTable("ContentTypeRecord", table =>
                    table.AddUniqueConstraint("UC_CTR_Name", "Name"))
                .AlterTable("ContentItemVersionRecord", table =>
                    table.AddUniqueConstraint("UC_CIVR_CIRId_Number", "ContentItemRecord_id", "Number"))
                .AlterTable("CultureRecord", table =>
                    table.AddUniqueConstraint("UC_CR_Name", "Culture"));

            return 4;
        }`

**Comment by dcinzona** [comment]
Looks like a cool PR ;)

**Comment by sebastienros** [comment]
@jersiovic You need to learn how to format multi-line code, twice now I had to clean after you ;)

**Comment by sebastienros** [comment]
Don't make a PR out of it, this code is SQL Server specific. __AND__ you don't want to go in the business of deleting customer's data.

**Comment by sebastienros** [comment]
We should provide the query to detect the duplicates before the migration is done, and we can the query to remove duplicate, but let the users apply it by themselves, not during an automatic migration.

**Comment by dcinzona** [comment]
Ah true.  Good point, but also good to know for us "SQL Server" users

**Comment by jersiovic** [comment]
Sorry, there is also a nice Preview button to avoid spam you with my attempts. 
Lesson learned
