### ISSUE TITLE
Dev & 1.10: Dynamic form field binding issue

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#6470]
Just re-tried in the last dev branch and 1.10 release. It was working in a previous version but maybe here i'm doing something wrong.

Repro:

- Create a content type with a field of type text.
- Create a dynamic form with the `CreateContent` option and select the above content type.
- Insert a text form field and bind it to the text field of the above content type.
- Display the form on front end, input a text in the form field and submit.
- Edit the created content item in the dashboard, **there is no value**.

Note: Trying this, i could see again the other issue where, for most of the element editors, as soon as a checkbox is saved as checked, it can't be saved again as unchecked. Can be fixed for me with #6339.

Best

**Comment by sebastienros** [comment]
@sfmskywalker
