### ISSUE TITLE
Anonymous access to search

### ISSUE THREAD

**Issue by JRKelso** [OrchardCMS/Orchard#6473]
Currently anonymous users can use the Search module, which could potentially be an issue. It would be nice if you could allow or disallow anonymous users access to search.

**Comment by CSurieux** [comment]
Don't display its widget for non authenticated ?

**Comment by bleroy** [comment]
Yep, Christian is partly right: create a layer that only appears for authenticated users (rule "authenticated", as documented here: http://docs.orchardproject.net/Documentation/Managing-widgets) and put the widget in there. That won't fix the fact that the search results page will still be accessible for whoever has its URL. But I have to ask: why do you think it's a risk? Is it that you want search results to only contain documents that the current user is allowed to access?

**Comment by JRKelso** [comment]
We could hide the search but as you said as long as they know the URL for search they can still search. We aren't concerned with auth users accessing areas they're not able to access, more of information leak from search results to anonymous users. It's a minor concern, we implemented the fix on our branch, thought we would raise the issue here with our fix.

**Comment by bleroy** [comment]
OK, so this is fine to close, right?
