### ISSUE TITLE
Post about VS Dev Essentials on Website

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#6475]
I was thinking we should post a news item on the Orchard site about the vs dev essentials program:

## Learn Orchard with Pluralsight for Free

Thinking about learning Orchard? Microsoft have recently set up a new developer program called [Visual Studio Dev Essentials](https://www.visualstudio.com/products/visual-studio-dev-essentials-vs). It's free to join and comes with range of free tools, cloud services and training including a 3 month free subscription to Pluralsight which has two great video courses:

  * [Orchard Fundamentals](https://www.pluralsight.com/courses/orchard-fundamentals)
  * [Advanced Orchard](https://www.pluralsight.com/courses/adv-orchard)

The courses target Orchard v1.4 but almost everything is still applicable today (For example Contrib.Taxonomies is now a core module, ContentParts can now take advantage of infoset and some minor admin panel UI differences) but it is a great introduction to learning Orchard.

The Microsoft developer program also includes $300 to spend on Azure + more benefits.

**Comment by rtpHarry** [comment]
This still hasn't made it onto the website.

**Comment by Jetski5822** [comment]
@agriffard Who updates the main site these days?

**Comment by agriffard** [comment]
Not me. I never had the access to orchardproject.net. 
@bleroy @sebastienros  and @LombiqTechnologies

**Comment by Piedone** [comment]
If it's worded more as a resource and less as an ad  I see no issues with adding it. Maybe 1) have a blogpost about announcing it and 2) adding it to http://docs.orchardproject.net/Documentation/Orchard-TV?

**Comment by rtpHarry** [comment]
Yes @sebastienros told me to post it here as an issue after discussing it in a weekly podcast a while back. I just thought it was a good resource that should be highlighted for the community.

**Comment by rtpHarry** [comment]
I guess this isn't going to make it onto the website :) 

I will post it myself if I can be given an editor account on the website?

**Comment by Piedone** [comment]
I still have the above reservations.

**Comment by rtpHarry** [comment]
Ah, I didn't realise that you were requesting a rewrite before.

## Visual Studio Dev Essentials program has Orchard developer friendly resources

Microsoft are running a free program called [Visual Studio Dev Essentials](https://www.visualstudio.com/products/visual-studio-dev-essentials-vs). It has a range of useful and not so useful 'developer benefits' included in it. 

Two that I've found valuable are the 3 month free Pluralsight subscription and the free monthly Azure credits. There are a broad range of other resources included though and from the ones I've tried they are totally free-to-try, not "add your credit card and remember to cancel it before we charge you".

The free 3 month Pluralsight subscription gives you access to a ton of topics, but there are also two Orchard-specific video courses:

  * [Orchard Fundamentals](https://www.pluralsight.com/courses/orchard-fundamentals)
  * [Advanced Orchard](https://www.pluralsight.com/courses/adv-orchard)

The courses target Orchard v1.4 but almost everything is still applicable today (For example Contrib.Taxonomies is now a core module, ContentParts can now take advantage of infoset and some minor admin panel UI differences) but it is a great introduction to learning Orchard.

The Azure Developer Benefit includes $25 a month to spend on Azure for one year. If you want to spend more than that you can uncap the subscription and use it as a discounted starter package to get up and running with your website for the first year.

**Comment by Piedone** [comment]
I think that's good now. So do you think this is suitable to post as a blogpost on orchardproject.net? Because then I'll do that under your name.

**Comment by rtpHarry** [comment]
Yeah sounds good to me

**Comment by Piedone** [comment]
Thank you, done.
