### ISSUE TITLE
The OnRemoving Event filter has no way to stop a delete and the OnCreating to prevent a create

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6476]
I have a part built on 3 links to 3 different contentParts in contentItems.

C1 : A Record, B Record, C Record

I want to avoid any delete of A , B or C when they are used in a C1 item.
My intention was first to add an OnRemoving filter on them, just stopping the remove and Notifying the user. But I can't see any flag in the RemoveContext which could allow this.
The examples of OnRemoving in existing code just take care to remove all related item, which I don't want.
Could be nice to add this feature to the pre - events ?

Is there another way to avoid a remove ?

**Comment by CSurieux** [comment]
I throw an OrchardSecurityException because a classic exception does not stop the delete.
The database is safe but the UI strange, saying I have no right to access this url !!!!!

**Comment by sebastienros** [comment]
The usual pattern we apply in Orchard is to cancel the transaction. 
The semantic here is not to let you cancel the event, but just warn you it is about to be done, and the decision is made already. For instance to order other actions.
