### ISSUE TITLE
Why is IContentManagerSession always injected in as Func<IContentManagerSession>?

### ISSUE THREAD

**Issue by paynecrl97** [OrchardCMS/Orchard#6481]
Whenever `IContentManagerSession` is injected into a constructor, it is always injected in as `Func<IContentManagerSession>` (see `DefaultContentManager` and `SessionLocator`).

**Can anyone explain why this is?**

I can't see a reason to do this, and as far as I can tell, injecting in directly seems to work (unless there is an edge case that I have not thought about).

**Comment by sebastienros** [comment]
Without looking at the code I would say to lazy load it, so that it's created only if used. Might be for historical reasons that don't apply anymore, or not.

**Comment by paynecrl97** [comment]
Those were the only two reasons that I could think of too.

The lazy one doesn't make much sense, as it's a relatively cheap object to create, and why not just use `Lazy<>` instead?

The historical reasons is the interesting one, as I think this is much more likely, and begs the question- should it be changed?

**Comment by sebastienros** [comment]
Actually if it's a `Func` it's probably so that we can get new ones on demand, not for lazyness, but on the contrary to create many of them.
Probably for each Batch we need a new one.
