### ISSUE TITLE
Orchard 1.10; Gallery install fails 

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#6485]
Due to some issues with Gallery modules I tested with a freshly downloaded 1.10 from Github.
I added gallery feed as follows:
https://orchardgallery.azurewebsites.net/api/FeedService (changed it from the old one)
A) I wanted to download 'Contrib.GoogleAnalytics'. I have seen the successfully installed msg BUT I do Not see the Module in my list NOR does the Gallery now say 'Installed'! A 2nd install: nothing happens
B) then I tried to install 'Bing.Maps' from the gallery and get msg:
quote
Package installation failed: There was an error installing the requested package. 
This can happen if the server does not have write access to the '~/Modules' or '~/Themes' folder of the web site. If the site is running in shared hosted environment, adding write access to these folders sometimes needs to be done manually through the Hoster control panel. Once Themes and Modules have been installed, it is recommended to remove write access to these folders.
end quote
PS: I'm sure the 'write' access is ok!
PSPS: just copying Bing.Maps from a 1.9.2 results in issues described in #6359.

has something changed with the new gallery ?
thanks for your hints, ed

**Comment by agriffard** [comment]
The url is gallery.orchardproject.net/api/FeedService

**Comment by sebastienros** [comment]
Why do you have to add a specific gallery feed, the default one in 1.10 should already point to the new gallery correctly.

**Comment by edikaufmann** [comment]
I changed because the  'default' one gave me the very same results. I certainly will go back again. 
BUT as said the issue remains the same. Any help is appreciated, ed

**Comment by edikaufmann** [comment]
ooops, just realised and I tried 3-times!
I went via module --> gallery, searched with 'analytics' and clicked 'google analytics (author: sebastien) and got 'Theme.Classic' installed (see msg below):
quote
Successfully added 'Orchard.Theme.Classic 1.0' to D:\CMSites\OrgBing_110s\src\Orchard.Web\
The theme has been successfully installed. It can be enabled in the "Themes" page accessible from the menu.
end quote
something must be mixed up! Sorry for not looking more carefully before!

**Comment by sebastienros** [comment]
Can we close the issue ?

**Comment by edikaufmann** [comment]
I probably confused you guys. Therefore, I tried this morning again. AND AGAIN I want to download the 'Google Analytics - Version: 1.0' Module via the Gallery.
BUT instead I receive:
quote:
Successfully added 'Orchard.Theme.Classic 1.0' to D:\CMSites\OrgTest_110s\src\Orchard.Web\
The theme has been successfully installed. It can be enabled in the "Themes" page accessible from the menu..
end quote
AND that Theme, 'Orchard.Theme.Classic 1.0', is really installed!!! BUT I clearly clicked the 'Analytics' Module.
I wouldn't know what's wrong on my side; I leave it up to you guys whether to close or not and
wait for the official release.
But thanks again for all the effort you guys put into this wonderful project, ed
PS: the Gallery feed is back to: https://gallery.orchardproject.net/api/FeedService

**Comment by dcinzona** [comment]
This may actually be an issue with the gallery, not with Orchard.
I can confirm, the same thing is happening to me when I try to install a module directly into Orchard (on local dev).  Downloading downloads the correct nuget package.

**Comment by dcinzona** [comment]
Using Fiddler, this is the query that is being sent to the gallery: https://gallery.orchardproject.net/api/FeedService/Packages()?$filter=tolower(Id)%20eq%20%27orchard.module.contrib.googleanalytics%27&$orderby=Id

**Comment by edikaufmann** [comment]
I didn't even know that 'gallery' is not orchard related. For now I refrain from 'gallery' and download the Nuget version.
thanks, ed
