### ISSUE TITLE
lateast 1.10 select button dispeared

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6489]
days ago, it was there
![select](https://cloud.githubusercontent.com/assets/297675/13364676/230afbb0-dc9e-11e5-8647-d1366c7fb53e.png)

**Comment by sebastienros** [comment]
Probably a merging issue from 1.9.3 ...

**Comment by dcinzona** [comment]
The select button only appears when selecting a media item using TinyMCE or the media field.  When browsing the media library, there shouldn't be a select button, because there's no action to do on the item.  I think this is by design.
Can you post the steps to repro?

**Comment by infofromca** [comment]
day ago, it was there

On Mon, Feb 29, 2016 at 7:45 PM, Gustavo Tandeciarz <
notifications@github.com> wrote:

> The select button only appears when selecting a media item using TinyMCE
> or the media field. When browsing the media library, there shouldn't be a
> select button, because there's no action to do on the item. I think this is
> by design.
> Can you post the steps to repro?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OrchardCMS/Orchard/issues/6489#issuecomment-190471964>
> .
>



-- 
Thank you for your attention
Yours

GUANG ZHENG (Andy)

*140 Glen Springs Dr. • Toronto, ON • M1W 1X8 •*
* 647-667-7538 *
