### ISSUE TITLE
multi tenant --one of URL prefix and Host should be required

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6495]
obviously host field should be required to avoid my mistake at  #6434

**Comment by geertdoornbos** [comment]
Host field should not be required on the default tenant. It would make a fixed binding and prevent routes that are not specified in thee host field. Also prevents custom middleware routes that do not match the host field.

**Comment by dcinzona** [comment]
Host field should NOT be required.  I shouldn't have to specify a host, if I only want to use a URL prefix.  This way I can change the root host and have it blanket update my other tenants.  Like a CNAME vs. A Record in DNS.

**Comment by infofromca** [comment]
ok , close it

**Comment by infofromca** [comment]
so, i think it is better that:
one of URL prefix and Host should be required, agree?
reopen

**Comment by dcinzona** [comment]
One OR the other, sure.

On Feb 28, 2016, at 7:38 AM, andy <notifications@github.com<mailto:notifications@github.com>> wrote:


so, i think it is better that:
one of URL prefix and Host should be required, agree?
reopen

-

**Comment by geertdoornbos** [comment]
And ignore my comment?

Besides my comment, isn't it very obvious if a tenant route doesn't work, when there is no host or prefix filled in?

**Comment by dcinzona** [comment]
It is obvious, but if it's a requirement to have one or the other for the tenant to work, it should be an actual *requirement*

**Comment by geertdoornbos** [comment]
True, for the default tenant to work, it's not an actual requirement, right?

**Comment by dcinzona** [comment]
Correct, it's not required for the default tenant to work.  In fact, I think it's required that they be blank for the default tenant to work?

**Comment by geertdoornbos** [comment]
Not required to be blank. You can specify something to make it explicit. For instance, you can 'overrule' the domain binding at server level. For example if you want to block <name>.azurewebsites.net if you're hosting on azure.

**Comment by dcinzona** [comment]
True
