### ISSUE TITLE
2 times TextField in the dropdown when adding a field to a content

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6497]
Version Dev last today

**Comment by infofromca** [comment]
i can verify that.
i also got 2 times Media library picker field

**Comment by jtkech** [comment]
There is the regular `Orchard.Core.Common.Drivers.TextFieldDriver`. And just seen that a `TextFieldDriver` has been added in `Orchard.Fields` to enable tokenization for default values, see in the code. @LombiqTechnologies is better placed to fix this issue, maybe we only need to display distinct names.

**Comment by infofromca** [comment]
it is ok in 1.9.x

**Comment by infofromca** [comment]
i agree with "we only need to display distinct names"
because i also have custom field driver for Media library picker field, so duplicated Media library picker field
