### ISSUE TITLE
GetInstalledThemes is public in ThemeService but not in corresponding interface

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6499]
Is there a reason ?

**Comment by harmony7** [comment]
I always wondered that too and always modified my build to expose it from the interface. Somehow I had not submitted a pull request for that one...

**Comment by sebastienros** [comment]
Why would you need it if it's already available in the Extension Manager.
I see there is some weird code in it though. If it was done it would be breaking too.
