### ISSUE TITLE
Orchard 1.10: Could not find file '...\httpdocs\bin\roslyn\csc.exe'

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard#6502]
I have upgraded a preproduction server from 1.9.2 to 1.10 deploying folder stage generated with ClickToBuild.cmd.
When I run Orchard I receive the following exception:
Could not find file 'C:\Inetpub\vhosts\pedidosinternet.com\httpdocs\bin\roslyn\csc.exe'
Taking a look to that folder within the stage folder generated by the build I see that csc.exe and other exes are missing.
I solved it taking those files from src\Orchard.Web\bin\roslyn but I understand the desirable would be those exes were copied to the build folders when ClickToBuild.cmd is executed.

**Comment by sebastienros** [comment]
Crap, forgot to clean the build script apparently. We removed roslyn views compilation because it needed more work on the deployment side.

**Comment by sebastienros** [comment]
Where did you take this version from, and when did you?
I can't find csc anymore, like I correctly removed it.

**Comment by jersiovic** [comment]
I downloaded a zip from githhub (branch 1.10) on 23/02/2016
Last commit at this branch was https://github.com/OrchardCMS/Orchard/commit/cb06c7576c5b4ca6bec1aac273d0a671acdf94a3

**Comment by sebastienros** [comment]
Can you check the web.config files to ensure they don't contain anything like this:

```
    <!-- NOTE: These have no runtime effect; they are only here to make the editor accept C#6+ syntax. -->
    <system.codedom>
        <compilers>
            <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:6 /nowarn:1659;1699;1701" />
            <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:14 /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" />
        </compilers>
    </system.codedom>
```

**Comment by dcinzona** [comment]
So I just downloaded the 1.10 source zip and ran the build command.  It completed successfully for me.

**Comment by sebastienros** [comment]
It succeeds, and I also checked the web.config and they don't contain the `codedom` section. Please check your we.config files.

**Comment by jersiovic** [comment]
Yes Sebastien that was the problem I had those lines.

**Comment by MuhammadTayyeb** [comment]
Kindly Goto this directly Download and this folder to Bin then Build the code. its Work properly
http://s000.tinyupload.com/?file_id=65594696755593015145

**Comment by RoyiNamir** [comment]
I also faced this problem and downloading @MuhammadTayyeb 's files into the bin directory , helped it compile.  - BUT I have another question. Instead of copying them manually - is there any command that I can run to re-create those files in the BIN folder ? I tried many update-package , install-package , but none of them actually re-put those rosyln files in the BIN.
