### ISSUE TITLE
Media Library: multiple cloning of the same item "fails"

### ISSUE THREAD

**Issue by attilah** [OrchardCMS/Orchard#6512]
When cloning an item in media library, only the first copy is made, subsequent copy operations "silently failing". Probably has something to do with the name generation of the cloned items?

**Comment by Skrypt** [comment]
That's because the file does'nt get copied. It tries to copy the file with the same file-copy.ext over and over.

```
    var newFileName = Path.GetFileNameWithoutExtension(media.FileName) + " Copy" + Path.GetExtension(media.FileName);
                
    _mediaLibraryService.CopyFile(media.FolderPath, media.FileName, media.FolderPath, newFileName);
```

**Comment by Skrypt** [comment]
I suggest adding a clone function in the MediaLibraryService directly.

**Comment by Skrypt** [comment]
Will provide a PR for this soon.
