### ISSUE TITLE
[1.10] RazorViewEngineProvider doesn't return themes directory

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#6514]
Previously, the area locations were hard set to 
* ~/core
* ~/modules
* ~/themes

Now, it seems to be omitting the `~/themes` directory.  I'm trying to find out where this is happening now, but this seems to be a bug in Core

**Comment by sebastienros** [comment]
This is now configurable. Maybe the value is missing from the configuration. @qt1 made the _awesome_ change.

**Comment by dcinzona** [comment]
Shouldn't the defaults still match watch was there before? i.e. core, modules, and themes
Or have the defaults changed (this is what it seems like)

**Comment by sebastienros** [comment]
Totally

**Comment by dcinzona** [comment]
So I specified the web.config setting for modules
```xml
<add key="Modules" value="~/Themes"/>
```
but that didn't add it to the locations dictionary.  Still looking...

**Comment by dcinzona** [comment]
It's passing in the engine and the engine isn't finding the view.  So it is search the themes directory, but the view isn't being returned.  Investigating...

**Comment by dcinzona** [comment]
Found out why it isn't finding the view.  Searched locations:
```
~/Themes/NFLPA.Web.Theme/Views/NFLPA.Web.Theme/Patterns/Index.cshtml
~/Themes/NFLPA.Web.Theme/Views/Index.cshtml
```
I don't know why it's injecting the theme name into the first location.

**Comment by dcinzona** [comment]
The problem is here:
```
            var areaPartialViewLocationFormats = new[] {
                parameters.VirtualPath + "/Views/{2}/{1}/{0}.cshtml",
            };
```
the `{2}` param shouldn't exist

**Comment by dcinzona** [comment]
Removing that `{2}` resolves the issue from me

**Comment by qt1** [comment]
Was out of office for a few days. Sorry.
Themes and Modules behave a little differently when searching for views (themes should be hierarchical).

Therefor themes should be added with the Themes keyword and modules with the Modules, for example:

        <add key="Modules" value="~/Ibn_Modules, ~/Gallery_Modules" />
        <add key="Themes" value="~/Ibn_Themes" />

Please see if this solves the problem.
As far as I remember the {2} was there for a reason (to be compatible with existing code) - but I may be wrong as it was some time ago..

**Comment by dcinzona** [comment]
No problem, see my PR #6528 
I added another location for scanning - this solves the problem for me (instead of removing the {2} )
