### ISSUE TITLE
Theme Selector does not work

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6522]
Dev.

In my module I have a shape, shoppingCart.cshtml,  in the MyModule\Views\ folder.
If I duplicate it under the Default site theme, \Themes\MySiteTheme\Views\shoppincart.cshtml, this new version is selected rather than the one in the module.
(Nothing special in any placement file)

But if I fix the theme to another one by a theme selector, this theme owning a dedicated version of the same shape  in \Themes\OtherSiteTheme\Views\shoppincart.cshtml, this last version is not used and it is the version in the module which is called ?

This is already weird, but it is worse because the  layout.cshtml in the OtherSiteTheme is also not used, and neither the dedicated wrapper, document.cshtml.

When a selector changes the current theme we could expect that everything be similar to what occurs in the default theme site. This is clearly different laws that apply.

This is a bug in Dev and certainly in 1.10. May be related to #6514

**Comment by CSurieux** [comment]
The layout used is the one in Orchard.Core\Shapes\Views ????? badly broken

**Comment by CSurieux** [comment]
If I set the 'laternate' theme as Default Site theme everything works as expected.

**Comment by infofromca** [comment]
i also met it long time ago.
seems related to #5675

**Comment by CSurieux** [comment]
I have just tried many configs to have this working.
In the siteTheme for shopping.cshtml 
- under Views: OK
- under Views\MyModule: NOK
- under Views\MyModule\Views NOK
- under Views\MyModule\Mycontroller NOK
- under Views\MyController NOK
layout.cshtml works.

in the theme selected
No one of previous places works and the layout used is always
Layout.cshtml calles is always the one in orchard.Core.

In the actual situation this theme selector feature is just a marketing announcement.

**Comment by dcinzona** [comment]
Can you try my PR to see if it resolved your issue? https://github.com/OrchardCMS/Orchard/pull/6517

**Comment by CSurieux** [comment]
I will try it as soon as I have VS2015 repaired following the install of an update of GitHub for VS which broke the config (not the first time... no more HitHub for VS for me)

**Comment by CSurieux** [comment]
It was Webessentials. Broken by GitHub vsx.
So I tried your patch and no change: when the selector force a different theme than the Site Theme, this theme does not work as a norm

**Comment by CSurieux** [comment]
The pb seems to be in the fact that the resources in the 'forced theme' have not been scanned, they are not in the resource tables so they can't be solved.

**Comment by sebastienros** [comment]
> This Theme selector concept is weird or I don't understand its usage

Second option

**Comment by CSurieux** [comment]
Ok, then what is this thing  doing ?

**Comment by sebastienros** [comment]
For every request, Orchard is able to select which Theme to use among all the enabled ones. This way you could customize the rendering based on the url, the user, the time of the day, whatever. To do so there is a `IThemeSelector` interface that anyone can implement to provide such behaviors. Each implementation will analyze the current context and decide if it should provide a specific theme or if it doesn't apply. Each result gets a priority, for instance if you want a theme per user, and also have some rule per url, but the current requests matches both, then the priority of your results will disambiguate which theme to use. Selecting a theme will indeed define what template is used to render a specific shape as shapes can be defined or overrided in themes. There are usually two Theme Selector implementation that take action by default. The one that chooses the theme that is defined for the front-end in the settings, and another implementation with higher priority that will return `TheAdmin` when the request is for an admin controller.

**Comment by bleroy** [comment]
And to be clear, there is no magical theme selector in the system. The default one is implemented using the exact same hooks that anybody can use, and has no special priority.

**Comment by CSurieux** [comment]
here is what I did
`
    public class MyThemeSelector : IThemeSelector {
        private readonly IOrchardServices _orchardServices;

        public MyThemeSelector(IOrchardServices orchardServices) {
            _orchardServices = orchardServices;
        }
        public ThemeSelectorResult GetTheme(RequestContext context) {
            if (AdminFilter.IsApplied(context) || context.RouteData == null || context.RouteData.Values  == null ) {
                return null;
            }
            var rts = context.RouteData.Values;
            if ( rts.ContainsKey("controller") ) {
                var ctrl = rts["controller"].ToString().ToLower();
                var settings = _orchardServices.WorkContext.CurrentSite.As<MySettingsPart>();
                int priority = settings.TSPriority;
                if ( ctrl.Contains("shoppingcart") && settings.ShoppingCartTS && !string.IsNullOrEmpty(settings.ShoppingCartTheme))
                    return new ThemeSelectorResult { Priority = priority, ThemeName = settings.ShoppingCartTheme };
                if ( (ctrl.Contains("checkout") || ctrl.Contains("shipping")) && settings.CheckoutTS && !string.IsNullOrEmpty(settings.CheckoutTheme))
                    return new ThemeSelectorResult { Priority = priority, ThemeName = settings.CheckoutTheme };
            return null;
        }

    }`

So why when I activate it it does not behave as a normal theme ? Why the layout called is the one in Orchard.Core and not the ones in the Theme/View folder ? Why my alternate shapes in the theme view folder are not found and I go back to the shapes in the module ?

**Comment by sebastienros** [comment]
Can you put a breakpoint in the service that reolves all theme results and see which one it's using, and why?

**Comment by CSurieux** [comment]
I spent 2 days on this. I have put dozen of breakpoints building a kind of breakpoint factory. For sure my theme is selected. Please read the info here.
Ok. I gave up ... again. I will find anothere solution than using 2 different themes, I am late and must deliver.

**Comment by bleroy** [comment]
A simple experiment would be to select those same themes as the active theme, with the default theme selector, to check if the views get rendered as expected. Then, you can break into that default selector, and peek into the theme selector result, to check if the theme name and priority show exactly like what you've put in your settings.

As a side note, however, it seems a bit weird to select an entirely different theme when on the shopping cart or checkout. I'm sure you have your reasons, but it does seem like a few alternates could do the job much more simply.

**Comment by CSurieux** [comment]
When I select this 'alternate theme as the site theme, everything is ok. I already write it.
Ok tired of permanent lessons, you know.
Anyway thanks for trying something. I have to progress.

**Comment by bleroy** [comment]
Well, we're also all tired of getting yelled at for trying to help. Your feeling of entitlement is palpable.

You did not do what's after the "then" if I'm not mistaken, which is key to finding out what's going on. Since your theme selector is running, something has to be different in its results. Stepping out of the theme selector up into the logic that makes the actual decision might help as a next step, if looking at the results is not enough to figure it out.

**Comment by sebastienros** [comment]
Is your theme enabled? Not default but enabled. The difference is subtle in the UI.

**Comment by CSurieux** [comment]
Great day, this theme was not activated. Thanks @Sebastienros. 
The world was against my mind but reality was simply a small link under the theme on the theme menu. Classic.
What is the usage of this activated status? 
There should be an error when trying to install a 'non activated theme' as the current one.
This is never checked in theme manager.
`public ExtensionDescriptor GetRequestTheme(RequestContext requestContext) {
            var requestTheme = _themeSelectors
                .Select(x => x.GetTheme(requestContext))
                .Where(x => x != null)
                .OrderByDescending(x => x.Priority);

            if (requestTheme.Count() < 1)
                return null;

            foreach (var theme in requestTheme) {
                var t = _extensionManager.GetExtension(theme.ThemeName);
                if (t != null)
                    return t;
            }

            return _extensionManager.GetExtension("SafeMode");
        }`

**Comment by sebastienros** [comment]
Any feature that needs to be used has to be enabled. Themes can be enabled, and set as default, these are two different things. And like features can be not enabled, theme have the same possibility as they can contain custom logic, and be used by some tenants only. Because __most of the time__ it doesn't make sense to just enable them, the link is not prominent.

**Comment by bleroy** [comment]
Do we think there are reasonable cases where a theme selector selects a theme that is not enabled, and that is not an error? How bad would it be to push a warning when the theme that ends up being selected is not found?

**Comment by sebastienros** [comment]
Could be logged, WARNING ...

**Comment by bleroy** [comment]
Maybe we can do better than that and have a theme and view resolution diagnostics tool in Glimpse and/or designer tools.

**Comment by CSurieux** [comment]
Github is missing a status: closed by concept
