### ISSUE TITLE
Outputcache still checks cache even if a route is configured as not to cache

### ISSUE THREAD

**Issue by carlwoodhouse** [OrchardCMS/Orchard#6523]
Hi,

Noticed this yesterday,

The outputcachefilter doesn't check the route configs to see if a route is ignored during the `RequestIsCacheable` method (it does check the `IgnoredUrls `field from settings in this method), this means that it will get as far as looking for an item in cache. Once it comes to server the item it does check the configs in the `ResponseIsCacheable` method, realises its disabled in the config (cacheduration set to 0) and never serves the cache item.

This means if your using an external cache provider like redis you can end up doing a request to redis for no reason as far as i can tell?

**Comment by dcinzona** [comment]
Hm, that's interesting... can you try to do a PR or give some code flow details?

**Comment by carlwoodhouse** [comment]
Not gonna have time this sprint for a pr (unless i find an hour over the weekend), but might be able to get it on the next one ... anyway flow as follows

Configure some routes to be disables, eg ....
![routes](https://cloud.githubusercontent.com/assets/465424/13494653/8f271ef2-e13d-11e5-9a8a-f6824aee31b6.png)

Stick a break point in https://github.com/OrchardCMS/Orchard/blob/1.9.2/src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs line 83.

You'll see it sails past

`
            if (!RequestIsCacheable(filterContext))
                return;
`

and eventually hits
` var cacheItem = GetCacheItem(_cacheKey);` (line 112) - this will go and look for the item in your cacheprovider (so in the case of redis, do a request to redis)

Eventually in the `ResultExecuted` it then checks `ResponseIsCacheable` realises its not because of the config and doesn't serve it from cache.

Imo we should probably check the config in `RequestIsCacheable`

**Comment by dcinzona** [comment]
Interesting, I wonder if you need to set the route as not-cacheable somewhere else - for example, in the ignored URLs text area box?

**Comment by carlwoodhouse** [comment]
well it correctly checks the ignoredurls text box in RequestIsCacheable but imo it should also be doing the route checks (as those routes can be dynamic, these are the routes it pulls from your Routes.cs file).

**Comment by dcinzona** [comment]
```c#
 if (!RequestIsCacheable(filterContext) || !ResponseIsCacheable(filterContext)))
```
?

**Comment by dcinzona** [comment]
basically, if the response isn't cacheable or the request isn't cacheable, don't even try - because if the response isn't cacheable then the request would never return a cached item?

**Comment by dcinzona** [comment]
summoning the cache king @DanielStolt

**Comment by carlwoodhouse** [comment]
I dunno cos ResponseIsCachable already does some other things that are irrelavent at that point, but you could be right - it's either that or moving the route config check to RequestIsCacheable i think :)

**Comment by DanielStolt** [comment]
This makes sense to me - it should be optimized such that the route check is done in `RequestIsCacheable()`. I'll target this at `dev` and assign myself - feel free to submit a PR if you feel up to it and I'll review and bring it in.
