### ISSUE TITLE
Azure app service crashes when an exception is thrown inside a layout part

### ISSUE THREAD

**Issue by joshberry** [OrchardCMS/Orchard#6526]
For several days now, we've been troubleshooting repeated site restarts on an Orchard 1.9.2 instance we have installed on an Azure app service. The end result is users receiving a 502 error. Initially we thought that any exception thrown from Orchard was causing the restart, but after a lot of testing, we found that it is actually only exceptions thrown by something that is later rendered through the layout part. We happen to use layout parts extensively on the site so it's affecting almost every page.

We've been able to reproduce the issue on an out-of-the-box Orchard 1.9.2 instance setup on a fresh Azure app service and database. Here's the basic steps to repro:

1. Install Orchard on a fresh Azure app service and database
2. Create a cshtml file in the theme's view folder that does nothing but throw an ApplicationException.
3. Create a new Page content item and add a Shape element (located under snippets) to the layout part, specifying the view you created in step 2 as the Shape Name.
4. Repeatedly hit the page you created in step 3. The site will eventually restart and you'll receive a 502 error.

Unfortunately, there is very little information to go off of in the logs. The only thing we're getting is a partial log entry for the ApplicationException then nothing else until it restarts. The issue appears to apply to any exception raised during the layout part rendering. We initially discovered it when an exception was raised by a projection we had included in a page layout part.

We also cannot repro the issue locally or on any of our own servers. It only happens (as far as we're aware) when Orchard is installed on an Azure app service.

Has anyone else encountered this before? 

If you have suggestions on how to resolve or further troubleshoot the issue they would be greatly appreciated. Right now, it feels a little bit like we're sitting on a time bomb as an exception raised on a frequently accessed page on the site could essentially send it into a continuous restart cycle.

**Comment by joshberry** [comment]
Here's a link to the page we setup to repro: http://bwlorchardtest2.azurewebsites.net/testpage?error=true.

The code in the shape that throws the exception is simply:
```
@{
    if (Request.QueryString["error"] == "true") {
        throw new ApplicationException("Test exception...");
    }
}
```

**Comment by joshberry** [comment]
We've been troubleshooting the issue with Azure support and found another piece of information that may be helpful in diagnosing the issue.

Azure support asked us to install the [Crash Diagnoser Site Extensio](https://blogs.msdn.microsoft.com/asiatech/2015/12/28/use-crash-diagnoser-site-extension-to-capture-dump-for-intermittent-exception-issues-or-performance-issues-on-azure-web-app/)n and collect a dump file. When we installed the extension and started it, the restarts/502s stopped happening completely. However, when we went back and uninstalled it, they came right back. We were able to repeat this several times on multiple sites with the exact same results.

It appears that something happens when the Crash Diagnoser is first run that eliminates (or at least masks) the issue. We don't really have any understanding of why this would be - maybe something specific to the Azure app service pipeline. We've passed the info along to Azure support and are waiting for their response. I wanted to mention it here in case it helps point to the source of the problem.

**Comment by sebastienros** [comment]
Have you tried to setup the same repro on a new App Service Plan? Just to ensure it's not related to a specific machine.

**Comment by joshberry** [comment]
Yes. We've been able to repro on 3 separate service plans. One of them was even on a completely different Azure subscription.

**Comment by sebastienros** [comment]
What if you run an empty app with this code?

**Comment by joshberry** [comment]
I'm assuming you're talking about a blank asp.net app. I get an error page - just like I would expect.

**Comment by sebastienros** [comment]
Yeah, it was just to confirm is related to Orchard.

**Comment by dcinzona** [comment]
I added this line of code to a normal partial mvc view page and we got a normal error page as expected.  I wonder if the key component here is the Layout part.

**Comment by joshberry** [comment]
Yes @dcinzona  - the issue only occurs when an exception is thrown by something being rendered inside a layout part.

**Comment by infofromca** [comment]
not invisgate it, but maybe  a hint:
in our app, the normal catch on top can not catch the exception from async method in middleware.
ref  #6493
