### ISSUE TITLE
After checking Store Submission field and Create Content field in a dynamic form it cannot be changed

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard#6527]
The repro steps (I'm using Orchard 1.10 Latest Commit 6c93bf4d69f44de467cd71435e9153f34544e0c5 March 1st 2016, 10:02 pm):

1. Create a new tenant with a Default recipe
2. Create a new dynamic form.
3. Edit Form element
4. Set to true Store Submission field and Create Content field
5. Accept
6. Edit another time the Form
7. Set to false Store Submission field and Create Content field
8. Accept
9. Edit another time the Form
10. You will find Store Submission field and Create Content field have still a true value

**Comment by dcinzona** [comment]
Does this PR fix it? https://github.com/OrchardCMS/Orchard/commit/369096864611f9b4b60a1718020da62fe6c4d51b

**Comment by jtkech** [comment]
More details in this issue #6302, see last comments for a summary...
Thenyou could try this PR #6339 or maybe #6308 for a more global solution.

Best

**Comment by jersiovic** [comment]
@dcinzona No, it doesn't fix it.
In fact, I have observed problems with checkboxes happen in other places as @jkech  suggest. For example if you try to create a new Content Menu Item, when the content item browser is launched and you select the content item you want (using its checkbox) nothing is set to to the Content Item field of the Menu Item.
@jkech I will take a look to your PR to have a better understanding of the bug. But maybe it is most likely a solution without hidden inputs to be accepted to be merged to Core repo. I'm still a bit lost with this part of the code so don't know if I will come up with something without hidden inputs.
Cheers

**Comment by jersiovic** [comment]
Checking what System.Web.Mvc.Html.InputExtensions.CheckBox() in current mvc version returns. I see that it solves problem in the same way you propose @jtkech 

System.Web.Mvc.Html.InputExtensions.CheckBox(Html, "test", true) returns the following: 
```
<input checked="checked" id="CreateContent" name="CreateContent" type="checkbox" value="true" />
<input name="CreateContent" type="hidden" value="false" />
```

System.Web.Mvc.Html.InputExtensions.CheckBox(Html, "test", false) returns the following: 
```
<input id="CreateContent" name="CreateContent" type="checkbox" value="true" />
<input name="CreateContent" type="hidden" value="false" />
```

**Comment by jersiovic** [comment]
An alternate solution not based on javascript but providing a hidden input is the following:

EditorShapes.cs
```
...
        [Shape]
        public IHtmlString Input(HtmlHelper Html, dynamic Shape, dynamic Display, string Type, string Name, dynamic Value, bool? Checked) {
            var tag = (TagBuilder)_tagBuilderFactory.Create(Shape, "input");
            tag.MergeAttribute("type", Type, false);
            if (Name != null) {
                tag.MergeAttribute("name", Name, false);
            }
            if (Value != null) {
                Value = Value is string ? Value : Display(Value);
                tag.MergeAttribute("value", Convert.ToString(Value), false);
            }
            if (Checked.GetValueOrDefault()) {
                tag.MergeAttribute("checked", "checked");
            }
            //CODE ADDED FOR HIDDEN INPUT
            var result = tag.ToString(TagRenderMode.SelfClosing);

            if (Type == "checkbox") {
                var hiddenTag = (TagBuilder)_tagBuilderFactory.Create(Shape, "input");
                if (Name != null) {
                    hiddenTag.MergeAttribute("name", Name, false);
                }
                hiddenTag.MergeAttribute("type", "hidden", false);
                hiddenTag.MergeAttribute("value", "false", false);
                result = result + hiddenTag.ToString(TagRenderMode.SelfClosing);
            }
            return new HtmlString(result);
        }
...
```
And in FormsElementDriver.cs
```
private void UpdateElementProperty(dynamic formElementShape, ElementEditorContext context) {
            var name = (string)formElementShape.Name;
            if (name != null) {
                var value = context.ValueProvider.GetValue(context.Prefix + name);
                if (value != null) {
                    'ADDED CODE TO HANDLE BOTH VALUES THAT COME
                    if (formElementShape.Metadata.Type == "Checkbox" && value.AttemptedValue != null)
                        context.Element.Data[name] = value.AttemptedValue.Split(',')[0];
                    else
                        context.Element.Data[name] = value.AttemptedValue;
                }
            }
        }
```
this doesn't solves the problem I mentioned with the content items selector creating a Content Menu Item, but it looks we are going to face similar problem wherever we use checkboxes. So, I could send a PR with a similar solution for that one, if do you think this solution is acceptable.

**Comment by jtkech** [comment]
Wow, i will try it this night and indeed, if it solves the issue without jquery code, i'll be happy to close my 2 PRs related to this and let you do another one.

But just seen you update `FormsElementDriver.UpdateElementProperty()`. So, if we only focus on layout element editors, did you try #6339 where i only update the same method and without using any hidden input.

Best

**Comment by jtkech** [comment]
@jersiovic 

I could repro your issue with `Content Picker` when adding a `Content Menu Item`. Idem when adding an item in a list with the `Lists` module.

If it's the same issue, the 1st workaround is not to use the `Add Selected` button but one of the individual `Select` buttons. To see these buttons i needed to extend the picker window to the right.

The `Add Selected` has been added to select multiple items but then an array of items is returned. Code has been updated in some places but not in all places.

Some scripts need to be changed. If the returned data is an aray, for the content menu item we only need the 1st item, for the list we have to iterate through this array. I'll open an issue and do a PR.

Best.

**Comment by jersiovic** [comment]
Great findings @jtkech ;)
So, at this point you can modify your PRs with the prefered option by the committee. It is not needed I complicate things providing an alternate PR. Don't you think?

**Comment by jtkech** [comment]
Ok, for #6308 we will see, i think you're in the right direction but not the easiest one.
But about my above comment it's another issue not related to forms api checkboxes.
