### ISSUE TITLE
Updating to 1.10 requiers lengthy work with references

### ISSUE THREAD

**Issue by qt1** [OrchardCMS/Orchard#6529]
Change includes moving dependencies (from lib to packages) and changing version.
This requires going over existing modules and updating the references.

This little utility is intended to make this process a bit more automatic by scanning the versions in the projects and selecting the largest, than preparing a new project file.
At the moment this is experimental so you should do the merge by a diff toll between the "new" and existing csproj file.

[https://github.com/qt1/Orchard/blob/ibn_2016/src/util/reflist/reflist.py]( https://github.com/qt1/Orchard/blob/ibn_2016/src/util/reflist/reflist.py )

**Comment by dcinzona** [comment]
Neat!  I did it the hard way :(

**Comment by sebastienros** [comment]
Couldn't you do ut with Node or PS or C# !!!!
Still, I will add it to the release notes. thanks

**Comment by qt1** [comment]
Two notes:
1. Maturity (lack of)
Worked for me but not really tested so please try and suggest improvements..

2. Tool-chain
Tried to do this with both Node and Python. Personally I found Python to be way more productive and lighter. 

I didn't try PhotoShop but I am sure it would really look good with that. (you couldn't mean power shell)

Someday, when I will have time, I'll rewrite in C# as a VS extension..
