### ISSUE TITLE
Seems that Media.Actions.cshtml is missing a Script.Require("JQuery")

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6532]
It crashes orchard when you try to list any Media Item (document for me)

**Comment by CSurieux** [comment]
`@using Orchard.ContentManagement
@using Orchard.Core.Contents;
@using Orchard.Core.Contents.Settings
@{
    Script.Require("JQuery").AtFoot();
    ContentItem contentItem = Model.ContentItem;
    var draftable = contentItem.TypeDefinition.Settings.GetModel<ContentTypeSettings>().Draftable;
}

<div id="media-actions">
    @if (Authorizer.Authorize(Permissions.EditContent, contentItem)) {
        @Html.Link(T("Edit").Text, Url.ItemEditUrl(contentItem), new { @class = "button", id = "edit-media-link" })
    }
    @if (Authorizer.Authorize(Permissions.PublishContent, contentItem) && draftable) {        
        if (contentItem.HasPublished()) {
            @Html.AntiForgeryTokenValueOrchardLink(T("Unpublish").Text, Url.Action("Unpublish", "Admin", new { Area = "Contents", contentItem.Id }), new { @class = "button", itemprop = "UnsafeUrl" })
        }
        else {
            @Html.AntiForgeryTokenValueOrchardLink(T("Publish").Text, Url.Action("Publish", "Admin", new { Area = "Contents", contentItem.Id }), new { @class = "button", itemprop = "UnsafeUrl" })
        }
    }
</div>
@using (Script.Foot()) {
<script type="text/javascript">
    //<![CDATA[
    // update the returnUrl from javascript to get the main window's location
    $('#media-actions .button').each(function () {
        var self = $(this);
        var href = self.attr('href');
        var containsQueryString = href.indexOf("?") >= 0;
        var returnUrl = href + (containsQueryString ? "&" : "?") + "returnUrl=" + encodeURIComponent(window.location);
        self.attr('href', returnUrl);
    });
    //]]>
</script>
}
`

**Comment by dcinzona** [comment]
Did you add that `Script.Require("JQuery")" line to the view?  Because it's a lower-case `j`: `Script.Require("jQuery")` (and you'll need it at head not foot because the javascript code in the view is not being attached to the footer and would execute before the jQuery library is loaded)

https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Parts/Media.Actions.cshtml

**Comment by CSurieux** [comment]
Well 
1) It is now case insensitive
2) if you look at the code I have also added @using (Script.Foot())

**Comment by CSurieux** [comment]
Maybe   @using (Script.Foot()) is enough, I will check

**Comment by dcinzona** [comment]
It would have been easier to read if you formatted your code when you posted the issue.  Just sayin'

As for it being case sensitive "now", I think it's been case sensitive for some time... I don't think that's a new "feature".

It's three backticks to format code: ```

**Comment by CSurieux** [comment]
I used the 'three backtick', but the problem is it''s not a perfect system.
Concerning case insensitive/sensitive it could be a new bug.
1.10 is the most buggy version I have seen since I follow Orchard, v 1.5 I believe.

Anyway the bug exists, isn't it. Do you agree on this ????

**Comment by CSurieux** [comment]
And if you or your team find a better, well formatted and correctly formulated fix, I accept you make a PR.

**Comment by dcinzona** [comment]
So this file didn't change between 1.9.2 and 1.10.
What version of Orchard are you currently running? 

I actually have not come across this bug myself. What page are you accessing to load that partial view?  Can you provide steps to reproduce the error on a clean 1.10 install?

Here is the file in the 1.9.2 branch
https://github.com/OrchardCMS/Orchard/blob/1.9.2/src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Parts/Media.Actions.cshtml

**Comment by CSurieux** [comment]
If you engage for the PR, I could say that I created a dedicated contentItem, assembling parts, to contain Documents media, it is a listable content.
I created some of them with the medialib UI and when I list them in the content I get the js exception.
Have you succeeded reproducing ?

**Comment by sebastienros** [comment]
We have tried to display Media Items and it works on 1.10. Can you provide some repro steps, and confirm you are using the 1.10 branch?
