### ISSUE TITLE
There was an error installing the requested package.

### ISSUE THREAD

**Issue by geertdoornbos** [OrchardCMS/Orchard#6533]
Probably related to #6485 

Repro:

Fresh 1.10 setup
Install module http://gallery.orchardproject.net/Packages/Orchard.Module.SH.Robots

Error: 
"There was an error installing the requested package." + some text about folder permissions

Quick fix
Click 'download' instead of 'install' to get the module. Then install local module from /Admin/Modules

Cause:
The package cannot be found. PackageInstaller.cs, line 55

```
var package = packageRepository.FindPackage(packageId, packageVersion);
```

Result:

```
            if (package == null) {
                throw new ArgumentException(T("The specified package could not be found, id:{0} version:{1}", packageId, String.IsNullOrEmpty(version) ? T("No version").Text : version).Text);
            }
```

This throws an ArgumentException which will be caught as an Exception, giving the generic error message. Also the message localization is wrong; will never translate correctly.

Fix:

```
            if (package == null)
            {
                var message = String.Format(T("The specified package could not be found, id:{0} version:{1}").Text, packageId, String.IsNullOrEmpty(version) ? T("No version").Text : version);
                throw new OrchardException(new LocalizedString(message));
            }
```

Question remains why the package cannot be found, but can be downloaded from the NuGet feed.

**Comment by geertdoornbos** [comment]
Issue is fixed by in the [Gallery module](https://github.com/OrchardCMS/Orchard.Gallery/issues/19)

Calling client code should still be fixed. PR to which branch? dev, master, 1.9.x, 1.10?

**Comment by sebastienros** [comment]
The issue was on the server code, any client should work fine now. So it should work with any Orchard version.

**Comment by sebastienros** [comment]
Closing the issue for now unless you can repro it since I updated the gallery.

**Comment by geertdoornbos** [comment]
Sebastien, there still is an issue on the client side. The server side failed with package == null. The code looks like it's handling the error, but it doesn't.

**Comment by BenedekFarkas** [comment]
@sebastienros repro: Modify a package install URL under "/Packaging/Gallery/Modules" so that the package ID is invalid. Without change, the exception message will not be displayed as it's caught by `PackageManager.DoInstall()` and wrapped in an `OrchardException`. As suggested by the PR, throwing an `OrchardException` (instead of `ArgumentException`) will surface the original message, so the user will get a better understanding of what's happened.
