### ISSUE TITLE
Wrong package returns from package feed!

### ISSUE THREAD

**Issue by geertdoornbos** [OrchardCMS/Orchard#6539]
**I think the package feed needs serious attention.**

Repro: Fresh 1.10
Go to http://localhost:30321/OrchardLocal/Packaging/Gallery/Modules
Search 'analytics'
Click 'Install'

Package ID = "Orchard.Module.Contrib.GoogleAnalytics"

```
var package = packageRepository.FindPackage(packageId, packageVersion);
```

Package found is: "Orchard Classic Blog Theme"

> The theme has been successfully installed. It can be enabled in the "Themes" page accessible from the menu.

**Comment by dcinzona** [comment]
I posted the issue on the Orchard.Gallery module:

**Comment by sebastienros** [comment]
Fixes the gallery, please try to ensure it works as expected now.

**Comment by geertdoornbos** [comment]
It works as expected now.
