### ISSUE TITLE
Themes that are not under ~/Themes/ not working in 1.10

### ISSUE THREAD

**Issue by KANekT** [OrchardCMS/Orchard#6541]
If i copy in Orchard.Web\Themes - js and styles working
but if i use theme from Orchard.Web\InnoLine\Themes - is not working

> 

Example please ... i have add
 ```
<system.webServer>
    <staticContent>
      <clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="7.00:00:00" />
    </staticContent>

    <handlers accessPolicy="Script,Read">
      <!--
      iis7 - for any request to a file exists on disk, return it via native http module.
      accessPolicy 'Script' is to allow for a managed 404 page.
      -->
      <add name="StaticFile" path="*" verb="*" modules="StaticFileModule" preCondition="integratedMode" resourceType="File" requireAccess="Read" />
    </handlers>
  </system.webServer>
```

not working

**Comment by bleroy** [comment]
That's by design. Themes go under the themes folder. What are you trying to achieve?

**Comment by bleroy** [comment]
Do you mean that it doesn't look under the proper folder when your site is under a vdir?

**Comment by KANekT** [comment]
> That's by design. Themes go under the themes folder. What are you trying to achieve?

in new orchard 1.10 I can point any folder for the theme

**Comment by bleroy** [comment]
So you should probably give a little more information about what you tried.

**Comment by KANekT** [comment]
i have add key <add key="Themes" value="~/nnoLine/Themes" />

not working 
http://localhost:7001/InnoLine/Themes/InnoLine.StockMaster24/Styles/img/icons_seti.png

but http://localhost:7001/InnoLine/Themes/InnoLine.StockMaster24/Styles/styles.css
load correctly

**Comment by bleroy** [comment]
Please check the web.config files above that `/InnoLine/Themes/InnoLine.StockMaster24/Styles/img/` directory.

**Comment by KANekT** [comment]
> Please check the web.config files above that /InnoLine/Themes/InnoLine.StockMaster24/Styles/img/ directory.

i have webconfig in Main Folder - Styles

i must put werconfig in each sub folder ?

**Comment by bleroy** [comment]
It depends. What's in the `web.config`?

**Comment by KANekT** [comment]
/InnoLine/Themes/InnoLine.StockMaster24/Styles/

**Comment by bleroy** [comment]
Does it serve the file if you put it at the same level as the css file?

**Comment by urbanit** [comment]
You need to change  resourceType="File" to  resourceType="Either"

**Comment by pacomonfort** [comment]
You have to add to web.config of Orchard.web in <appSettings> a line like this:

        <add key="Themes" value="~/InnoLine/Themes"/>

**Comment by KANekT** [comment]
> You have to add to web.config of Orchard.web in appSettings a line like this:

    <add key="Themes" value="~/InnoLine/Themes"/>

Yes I do it

> You need to change addHandler like here:
<add name="StaticFileHandler" path="*" verb="*" modules="StaticFileModule,DirectoryListingModule" resourceType="Either" requireAccess="Read" />

Thanks - it is solved my problem!

**Comment by urbanit** [comment]
Happy, actually is not an Orchard issue...
