### ISSUE TITLE
Dynamic Layout need to save on each step on Edge

### ISSUE THREAD

**Issue by pacomonfort** [OrchardCMS/Orchard#6546]
Using brach 1.10 March 3rd 2016, 9:12 pm

When you add new element to layout, you need to save on each addition. If not, it is not possible to add another one. It happends using Edge, in chrome works fine.

**Comment by sebastienros** [comment]
Could repro, it's javascript issue with Edge when the popup editor is launched. I can't explain why however as I don't understand the code in `LayoutDesignerHost.js` at line 26.
