### ISSUE TITLE
Taxonomy terms index has incorrect sorting

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#6548]
This is in all new versions (although tested on Dev and 1.10, but I can't see any difference in the code going back to 1.9.2)

The indentation / sorting / grouping doesn't seem to function as expected on the Terms index page for a taxonomy.  In the screenshot below, you can see that the last term should be under the first term, but it is still displayed last, yet indented as it should be.

![screen shot 2016-03-08 at 9 40 18 am](https://cloud.githubusercontent.com/assets/52411/13604687/e9cfbaf8-e511-11e5-95f3-8c3a7d566cdf.png)

Repro steps:
  1. Create a new taxonomy and add some terms
    * Add a root term
    * Add another root term
    * Add a child of the second root term
    * Add another child of the child added in step 3
    * Add another root term
    * Finally add a final root term
  2. Move the final root term and make it a child of the first root term

You will see that the last term is now indented correctly, but still appears last on the list (instead of under the first root term).

**Comment by Skrypt** [comment]
I confirm this, I can repro.

**Comment by BenedekFarkas** [comment]
Repro'd and fixed (here's the result, also tested with another similar scenario):
![taxonomytermadminindexsorting](https://cloud.githubusercontent.com/assets/2797449/13754261/9dcf1b6c-ea16-11e5-8aa2-6fcdce76f408.png)

**Comment by dcinzona** [comment]
Just tested in QA as well. Solution is confirmed.
