### ISSUE TITLE
[new-admin-theme] Can't set field properties in new admin theme

### ISSUE THREAD

**Issue by dcinzona** [OrchardCMS/Orchard#6549]
When adding a field to a content type, you should be able to specify the properties of that field, but it looks like you can't in 1.10.  This seems to work fine in dev?

@Skrypt is investigating but the screenshot below is from our 1.10 QA environment

![screen shot 2016-03-08 at 11 11 22 am](https://cloud.githubusercontent.com/assets/52411/13607867/3c5cad86-e520-11e5-92b8-54b24a3e345f.png)

**Comment by sebastienros** [comment]
The screenshot you took is from a Part. It's expected that you can't define the properties at this level, only for each type that your part is attached to.
I tried locally and you can correctly edit the fields.

**Comment by dcinzona** [comment]
Yup, confirmed... I was going to close it but got side-tracked.

**Comment by Skrypt** [comment]
Actually this is a bug in the new admin theme branch. Should we file issues in @sfmskywalker fork or here ? Maybe we could just add labels in here to take care of that.

**Comment by sfmskywalker** [comment]
I would file issues related to the new admin theme on the fork.

**Comment by Skrypt** [comment]
makes sense
