### ISSUE TITLE
Modules don't work after installing from Gallery (from VS)

### ISSUE THREAD

**Issue by geertdoornbos** [OrchardCMS/Orchard#6553]
When using Visual Studio to build and run the source code, modules don't work after installing them from the gallery. Installing and enabling features does work, nothing after that. 

Repro:
- Get the source and open solution in Visual Studio
- Start and setup Orchard
- Go to 'Modules' -> 'Gallery'
- Install a module
- Acknowledge to enable feature

Result:
Message says in green: 'Module enabled'. Module doesn't do anything.

Resolution:
- Find the module's .csproj and add it to the solution
- Most likely: change .NET Framework for the module's project to '4.5.2' due to reference issues
- Rebuild the module's project
- Restart Orchard

Is this a bug? [Dynamic compilation](http://docs.orchardproject.net/Documentation/Orchard-module-loader-and-dynamic-compilation) should work, right?

At least, it should be clear what's going on; user/dev should be informed how to act.

**Comment by sebastienros** [comment]
The issue is that VS is ensuring the projects target the same framework as Orchard.Framework, so they will have to be changed locally in this case. I am adding some release notes.

**Comment by sebastienros** [comment]
Done: https://github.com/OrchardCMS/OrchardDoc/blob/master/Documentation/Orchard-1-10.Release-Notes.markdown
