### ISSUE TITLE
Localization of LogOn, Register, NotFound is impossible

### ISSUE THREAD

**Issue by pda-code** [OrchardCMS/Orchard#6556]
If you have 2 languages in orchard (`en-US` and another) the url
`Url.Action("LogOn", "Account", new {Area = "Orchard.Users"})`

always render the `LogOn.cshtml` shape and it is always in en-US culture.

You can overide it in a theme but if you print
`<p>@WorkContext.CurrentCulture</p>`

the culture is always '`en-US`'. 
**That way THERE IS NO WAY to grab the localized resource strings from a .po file**

Major issue. Need a workaround!!!!

**Comment by urbanit** [comment]
@Piedone @BenedekFarkas any ideas?

**Comment by BenedekFarkas** [comment]
I assume it's the default site culture, so you can change that from "en-US" to something else if you added other cultures. Have you tried the culture selectors in the `Orchard.Localization.CultureSelector`?

**Comment by TFleury** [comment]
Yes, it should work with `CultureSelector` enabled.
If you take a look at `Localization` module source, you will find ways to select `CurrentCulture` (from browser, with a cookie or a route param).

**Comment by TFleury** [comment]
@BenedekFarkas you win the race !

**Comment by BenedekFarkas** [comment]
Sorry, @TFleury! :)
I'll close this as it's not an issue. Please re-open if localization doesn't work in this cases with a CultureSelector.

**Comment by pda-code** [comment]
Do not close the issue!! Yet!!

You have 1 localized page lets say Home, one for en-US and one for el-GR.

You add the culture picker combo, you select a language and the page automatically changes from en-US and el-GR. Perfect!!!

When you are in the HOME el-GR page, the culture and cookies is already in el-GR!!!!
You have a header link on your site that points to 
Url.Action("LogOn", "Account", new {Area = "Orchard.Users"})`

WHEN YOU CLICK on the link although you already in el-GR culture, the site switches culture to en-US and present to you the LogOn.cshtml.

if you print `<p>@WorkContext.CurrentCulture</p>` inside LogOn.cshtml it is always tthe en-US.

Have you tried it?

**Comment by TFleury** [comment]
You just have to set a cookie :
```
document.cookie = "OrchardCurrentCulture-FrontEnd=el-GR"
```
Or customise the login link
```
Url.Action("LogOn", "Account", new {Area = "Orchard.Users", culture = "el-GR"}) 
```

It's not an issue, just a lack of documentation.

**Comment by urbanit** [comment]
So, culture can be set as a route param. Tip of the day! Thanx guys.

**Comment by pda-code** [comment]
Thanks!!!
