### ISSUE TITLE
1.10 many tenant page problem after a91b06f1b55c38ff78ee1d880db27b845e2f114a

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6560]
home page 
before
![home-b](https://cloud.githubusercontent.com/assets/297675/13647863/0c2cac94-e604-11e5-91cd-cbd87e103fa4.png)

after
![home-after](https://cloud.githubusercontent.com/assets/297675/13647868/1363d9ec-e604-11e5-98e4-b3bdb55670c3.png)

contact page
![contact-b](https://cloud.githubusercontent.com/assets/297675/13647882/20345840-e604-11e5-8c5f-6f522abdd8a2.png)

after
![contact-after](https://cloud.githubusercontent.com/assets/297675/13647888/27b53af8-e604-11e5-8724-442ae90e0bf8.png)
after i comment out 
 //parameters.VirtualPath + "/Views/{1}/{0}.cshtml",
everything is ok

**Comment by infofromca** [comment]
for contact page (after). 
i have jquery dialog on other place, but not on contact. i do not know why it shows dialog on contact,
**and also on almost all other pages**

**Comment by Piedone** [comment]
It seems that a different Razor template is used now instead of a template that was used before, the one where you include the jQuery dialog box. Can you tell what the path of the template is that gets loaded (the one that uses the dialog box)? Shape Tracing can help.

**Comment by infofromca** [comment]
i have a custom item/Display.cshtml on my theme.
before it did not effect, 
now it runs.
after i delete it, every thing is ok

**Comment by Piedone** [comment]
Yeah, so you actually had a bug but a bug in Orchard masked it :-).

**Comment by sebastienros** [comment]
Breaking changes ;) Why some bugs in .NET are not fixed because customers rely on that, even things from private reflection is considered breaking change ...

**Comment by infofromca** [comment]
the purpose i put my custom  item/Display.cshtml  was for no theme situation long time ago and it worked for theme and no theme pages.

anyway it is ok now.
===
but still one thing puzzled me , why my contact page of default site did not dialog.
 no time to investigate no theme and the default  situation.
