### ISSUE TITLE
it shows success msg even if failing to send out email 

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6561]
repro steps:
created dynamic form -contact as the guide which was good days ago in 1.10
2--if i fail to send out email , it shows -orange circle
![contact](https://cloud.githubusercontent.com/assets/297675/13653819/deb57c8c-e621-11e5-924c-58f464c962a0.png)

**Comment by dcinzona** [comment]
Does the contact message content type have the autoroute part attached?

**Comment by infofromca** [comment]
dynamic form fields on page plus workflow 
i think page has autoroute part attached
i have seen this issue for long time

**Comment by dcinzona** [comment]
When a user fills out the form, does it create a content item?  I think it must because it is sending out the email via the workflow / delayed send, is that correct?  I actually haven't used Dynamic forms yet, so I don't know for sure.  Maybe I should drop off this thread :P

**Comment by infofromca** [comment]
emails not getting sent    is because i did not the email server correctly.

**Comment by Skrypt** [comment]
If the email is queued it could take a while to get the warning message. The form post and the action of sending the email are 2 separate things.
