### ISSUE TITLE
HTML widgets display HTML code instead of content

### ISSUE THREAD

**Issue by Cambridgeport90** [OrchardCMS/Orchard#6563]
Hi all, Not sure whether I'm doing something wrong, or what, but I was intent on editing one of the default widgets for my web site, when I noticed that after inserting the HTML code (the widget is meant to display my latest Twitter entries), instead of displaying the entries, it displays simply the HTML code instead. I simply inserted the code of my Twitter widget I created from Twitter into the body of the Widget on Orchard, and ensured that all white space was gotten rid of before clicking publish. If you go to http://cambridgeport90.net, you'll see what I'm referring to under the heading called "latest Twitter". You'll see the code of my Twitter widget instead of the actual timeline. I unfortunately had to use the Twitter options because none of the modules on Orchard for Twitter have been updated in ages, so until I can update them, I'll have to use service-provided buttons and widgets.

**Comment by sfmskywalker** [comment]
Did you paste in the HTML into the WYSYWIG view, or the HTML view?

**Comment by Cambridgeport90** [comment]
Darn. Not sure. How do I tell?

**Comment by dcinzona** [comment]
Go to the widget editor and if you see code immediately, then it was probably the WYSIWYG view... switch to source mode and put in the HTML there.

**Comment by Cambridgeport90** [comment]
Thanks. Will do and then report back.
