### ISSUE TITLE
Taxonomy Menu Placement In AsideSecond Zone is not correct

### ISSUE THREAD

**Issue by ActivePHOENiX** [OrchardCMS/Orchard#6571]
I have tried to create a tag cloud for defined terms in a taxonomy and show it on the mentioned zone, while there are some widget on the AsideFirst the content on the page is pushed to the right and two aside zones are besides each other. This happened in 1.10 branch.
anyone happened to see this issue before?

**Comment by sebastienros** [comment]
Can you give some repro steps? It doesn't sound like an Orchard bug but a theme's one. Please try with the TheThemeMachine theme to reproduce the issue.

**Comment by sebastienros** [comment]
Please reopen when you provide the repro steps.
