### ISSUE TITLE
[1.10] Conent not listed in admin content list

### ISSUE THREAD

**Issue by qt1** [OrchardCMS/Orchard#6579]
After change to 1.10 my Event content item is created properly, admin edit and view work and it seems to be displayed and working fine in the front end. 
However is does not appear in the admin contents list.

I have created an unfiltered query and projection and my items are listed correctly there.

The item implements its own _ITitleAspect_ (may be this is related, I don't know).

**Comment by BenedekFarkas** [comment]
Can you please share a more precise content definition and if there's any related entries in the error log?

**Comment by sebastienros** [comment]
Is the content items marked as Listable in the content definition screen ?

**Comment by qt1** [comment]
This is the indeed the Listable. Thanks Sebastian.

I the listable was set in the production site but not in the migrations so when creating from scratch it was missing.

Sorry for the false alarm.
