### ISSUE TITLE
Adding fields to a type after a validation error puts the content definition in an ambiguous state

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#6588]
### Repro steps:
- Create a new content type, e.g. "TestContent".
- Add any number of content parts to it (or none at all).
- Add a content field (of any kind) to the type and enter some data for the field definition that causes a validation error (e.g. empty display name, empty technical name, invalid technical name due to special characters) and attempt to save it.
- Save the definition after resolving the validation errors.

Expected result: the field is added to the type.
Actual result: the field is not added to the type.
### Additional repro steps:
- This is the point where TestContent content part is created and persisted (`ContentPartDefinitionRecord`), but it isn't attached to the TestContent type (there is no `ContentTypePartDefinitionRecord` entry to connect the TestContent part to the TestContent type). This part is hidden and attachable but it isn't visible on the admin (/Admin/ContentTypes/ListParts) or when attaching parts to a type (/Admin/ContentTypes/AddPartsTo/TestContent).
- The `ContentFieldDefinitionRecord` and `ContentPartFieldDefinitionRecord` entries are also persisted.
- Try to add a field again and enter the same display name as the previous attempt.
- You'll notice that the autocomplete for the technical name suffixes the value with a number meaning that the original technical name is actually taken.
- When you successfully save the second field, none of them is displayed still.
- When you successfully a third attempt for adding a content field - this time without triggering any validation errors - they are still not displayed.
- Adding/removing a content part or modifying any other part of the content definition does not help.
### Technical information:
- Orchard 1.10 and 1.9.3 affected.
- There are no caching features enabled at all.
- Reproducible using both SQL CE and SQL Server.
- Cleaning out the App_Data folder (except for Settings.txt, so e.g. mappings.bin is deleted) does not resolve the issue.
- No log entires.
- No runtime exceptions.

I have actually tried this before, but didn't manage to get a proper repro. At that time I was still messing around with it and after some time the fields suddenly appeared, but I still don't have a clear idea as to what triggered them to become available.

If you create another type and add a field to it without any validation errors then it's all working great.

Creating a manual `ContentTypePartDefinitionRecord` to connect the TestContent part to the TestContent type and cleaning out App_Data is confirmed workaround.

**Comment by BenedekFarkas** [comment]
I've updated the issue description with additional information.

**Comment by sebastienros** [comment]
Can't you just update the issue with a PR ;)

**Comment by BenedekFarkas** [comment]
Will do, I think I have the solution! :)

**Comment by sebastienros** [comment]
Not a new issue, assigning to 1.9.x

**Comment by BenedekFarkas** [comment]
So my suggestion would be to create the "ghost" content part for a type when the type is created (e.g. creating the `MyType` content type would invoke the creation of `MyType` content part as well and also attach it).

Right now this part is only created when you attempt to add a field to the type, but if the first field like that has a validation error before saving, the part is not persisted (it's created, but the transaction is rolled back and the ContentDefinitionManager caches it before the rollback and that's why it's not created later even if you successfully save the field). It seems that this issue is actually very old indeed.

**Comment by BenedekFarkas** [comment]
Related/same issue: #6310.

**Comment by BenedekFarkas** [comment]
Fixed in #f46be479a3d3a68cd2bcc5e9704e3efbfdafa6f6.
