### ISSUE TITLE
Web Deploy should not copy all the asset folders and content

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6593]
And not the Media folder content (but it is a very old demand).
And I still don't understand why it send all the modules bin folders content with all its duplicated assemblies. May be I missed a manual cleaning before sending.

A last comment but not for Orchard but for VS: totally impossible to deploy using a VM created with the new portal, it only works with Classic VMs. 
For Web App (old AWS) it is Ok but we send the whole non ecological orchard content ...

**Comment by sebastienros** [comment]
Deploying from Visual Studio will take care of duplicated binaries -> solved
Deploying directly with Web Deploy will require you to explicitly ignore the Media folder -> solved
If you want to deploy a cleaned list of bin folders, you need to do a `build Precompiled` and web deploy the `artifact/precompiled` folder -> solved

**Comment by CSurieux** [comment]
I am using VS2015 and it send everything.

I also get a problem with access rights not applied on the default subfolder of media.

Azure VM (classic).

 

De : Sébastien Ros [mailto:notifications@github.com] 
Envoyé : jeudi 17 mars 2016 20:41
À : OrchardCMS/Orchard <Orchard@noreply.github.com>
Cc : CSurieux <christian.surieux@hotmail.fr>
Objet : Re: [Orchard] Web Deploy should not copy all the asset folders and content (#6593)

 

Deploying from Visual Studio will take care of duplicated binaries -> solved
Deploying directly with Web Deploy will require you to explicitly ignore the Media folder -> solved
If you want to deploy a cleaned list of bin folders, you need to do a build Precompiled and web deploy the artifact/precompiled folder -> solved

**Comment by sebastienros** [comment]
> I am using VS2015 and it send everything.

You mean all the binaries, right? Because the Media folder is sent on purpose.

**Comment by CSurieux** [comment]
Yes, in my own modules and in some orchard modules, all the bin content is sent. But ok for asset, it is not sent.

**Comment by CSurieux** [comment]
I double checked and the asset folders are sent with the less content.

**Comment by CSurieux** [comment]
I have a problem withe the Media library: impossible to create any folder on the deployed site, the ACL are not ok ? 
Where in the code is this applied ?
