### ISSUE TITLE
Localizations | Bug in dictionary harvester for themes.

### ISSUE THREAD

**Issue by jagraz** [OrchardCMS/Orchard#6600]
The code in DefaultLocalizedStringManager.cs harvests dictionary files for ALL themes on the system; regardless of whether or not the theme is enabled. This can cause issues with multitenant systems where localizations for one site will be visible on other sites in the tenant; or situations where sites are single tenant but themes folders are shared. 

Acceptance Critieria:

- Localizations from Theme A that is not enabled on a site are not visible when the site is running theme B.

**Comment by sebastienros** [comment]
What does this mean:
> localizations for one site will be visible on other sites in the tenant

Repro ?

**Comment by jagraz** [comment]
Repro Steps:

1) create 2 themes with localization dictionaries
2) prop them to the same Orchard installation
3) observe how all dictionary files get harvested and localizations from inactive themes bleed over into your active site.

I have a PR I'll try to get up this week.
