### ISSUE TITLE
Publishing blogpost using Word 2016(livewriter ?)  does not work

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6608]
Module XmlRpc enabled.
Using the Word Blog template which includes LiveWriter publishing features.
Selecting 'Other' as provider and trying with the http and https versions of the blog url. 
No Error message, Word simply says that the operation fails, it can't create the account and ... its help page does not exist, this seems to be an official position of MS concerning help.

**Comment by CSurieux** [comment]
I must add that with Live Writer 2012 it is Ok, images from local PC goes in Media Lib.
Dommage, I use Word so often and never LW, it would have been nice.
And Live Writer is not adapted to W10 + the high screen definition of my PC, so small menus....

**Comment by bleroy** [comment]
You might want to try Open Live Writer, which is the modern and open source version of Live Writer. It supports high DPI.

**Comment by CSurieux** [comment]
Interesting, thanks.
As a Net Foundation object, they could add Orchard in the list of proposed managed Blog Engines ....
Certainly the good replacement for Live Writer.
...But still not Word.

**Comment by bleroy** [comment]
The list is the list of supported publishing APIs, not the list of supported blogs. Orchard supports the Metaweblog API iirc so no need for a separate entry. Their UI could be less confusing about that...
As for Word, no, it's not Word, and some consider that a good thing ;). It's designed to edit HTML, and arguably produces better code, and exposes a more appropriate UI (source view, image properties, etc.)
Still, would be interesting to understand why Word fails.
