### ISSUE TITLE
Ability to enable HTTP Strict Transport Security

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/Orchard#6612]
In the SSL module you can configure the whole site to be strictly under SSL and redirect all non-HTTPS requests to their HTTPS counterparts (which is mostly what you'd like to do). This leaves a possible man-in-the-middle attack open for the initial unencrypted HTTP requests (as an attacker can serve a forged site to the user) so users won't even get to the HTTPS URL if they didn't already typed that into the browser bar.

While we can't do much (AFAIK) if this is the first time the client accesses the site if they already visited the HTTPS site once we can basically tell them to only use HTTPS in the future. This is what HTTP Strict Transport Security is about: by setting a header value browsers can be instructed never to even try HTTP (see: https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security).

We could add the feature to the SSL module to send this header (with a configurable expiration time and a checkbox to send the `preload` parameter).

**Comment by sebastienros** [comment]
Another article I like about it: http://www.troyhunt.com/2015/06/understanding-http-strict-transport.html

It doesn't hurt to have that. I don't think it should be enabled by default though.

**Comment by kkelecsendi** [comment]
I think we could create these settings in the SSL module as @Piedone said. After we tick the "Force SSL on all pages" the HSTS settings should appear. The "Expiration time" should be a textbox (with validation), and the "Preload" should be a checkbox.

I'm not sure about this, but the NWebsec.Owin package(https://docs.nwebsec.com/en/4.2/nwebsec/Configuring-hsts.html) seems to be good for the implementation.

Is this a good idea?

@sebastienros

**Comment by Piedone** [comment]
I'd be hesitant to add a NuGet package (that also has another 3rd party dependency) just to add a few HTTP headers. Also I'm not sure whether the below style of configuration works from an `IOwinMiddlewareProvider`.

```
public void Configuration(IAppBuilder app)
{
    app.UseHsts(options => options.MaxAge(days:30).IncludeSubdomains());
}
```
