### ISSUE TITLE
Taxonomy bug when none selected in the field properties.

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/Orchard#6621]
![image](https://cloud.githubusercontent.com/assets/3228637/13923595/b66ecc1c-ef57-11e5-8242-da4ed83651c6.png)

when clicking on the link "create some terms".
As you can see in the url taxonomyId=0 does'nt exist so this url should'nt be there.
We should display a message that tells us to go setup the taxonomy field instead of :
_There are no terms defined for taxonomy field yet._

**Comment by BenedekFarkas** [comment]
Yes and selecting a Taxonomy for a TaxonomyField should be required when saving a content definition (but that doesn't mitigate the issue you are reporting, since you can just go to the content item editor after adding the field, don't need to save the content definition).

**Comment by sebastienros** [comment]
I suggest to only render a warning message if there is no taxonomy associated.

**Comment by Skrypt** [comment]
I'm trying to reproduce with 1.10.x branch and dev branch everything seems to be OK.

![image](https://cloud.githubusercontent.com/assets/3228637/14517556/d97f6ba2-01dc-11e6-895f-67554e0b1cab.png)
