### ISSUE TITLE
ClickToBuild and Orchard.proj: add the ability to use a custom solution

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#6627]
`ClickToBuild` has `.\src\Orchard.sln` wired in for restoring the NuGet packages.
`Orchard.proj` has `$(SrcFolder)\Orchard.sln` wired in as the solution to build.

Adding the ability to run these using a custom solution (with the current one set as default) would be quite useful. In the case of `ClickToBuild` it's really easy, but I'm not sure yet how to do it for `Orchard.proj` (maybe adding `/p:Solution=".\src\CustomSolution.sln"` to the `msbuild` parameters and then using `$(Solution)` in `Orchard.proj`), will check.

On the other hand, if you have a custom solution you probably have a custom proj file as well, so it may not be necessary.

**Comment by sebastienros** [comment]
Feel free to add a parameter to define a custom solution.

**Comment by BenedekFarkas** [comment]
Adding `/m` switch to `MSBuild` for multi-threaded building (tested with i7-3770 that has 4 cores = 8 hyperthreads on the `Compile` build target):

- Vanilla Orchard 1.10 (85 projects): 40s -> 25s (-37.5%)
- DotNest 1.9 (155 projects): 1m 22s -> 34s (-58.5%)

Btw I just realised that the solution doesn't really matter for `Orchard.proj` - all the modules and themes will be processed (including the custom ones), even if you build using `Orchard.sln`.

**Comment by BenedekFarkas** [comment]
Is `/m` not added when calling `MSBuild` on purpose (CI?), @sebastienros?
