### ISSUE TITLE
Orchard 1.10 With PosgreSql

### ISSUE THREAD

**Issue by KANekT** [OrchardCMS/Orchard#6632]
In PosgreSql all name table and column in lower case

example in MSSQL in CamelCase

https://s.mail.ru/C1wZ/8cjmRDXPF

**Comment by oldrev** [comment]
Hello KANekT:

The short answer is: it is not a bug in Orchard, it is intended to work that way.

In PostgreSQL, when you trying to execute a table creating SQL without quoted identifiers like this:

`create table MyTable(Col1 integer, Col2 integer);`

You will actually get the following result:

`mytable(col1` integer, col2 integer)

And sadly, as an Orchard module there is no way to quote all these tables and columns automatically without breaking the compatibility with other DBs.

**Comment by KANekT** [comment]
older, ok...

**Comment by KANekT** [comment]
It does not interest me any more.
