### ISSUE TITLE
Dev and 1.10.x: AliasHolderUpdater Refresh() is called 2 times

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#6638]
Seen on dev and 1.10.x, maybe in other branches.

**AliasHolderUpdater.Refresh() is called 2 times when starting the app.**
One in `AliasHolderUpdater.cs` through `AliasUpdaterEvent IOrchardShellEvents.Activated()`, and one in `AliasHolderUpdaterTask.cs` through its `IOrchardShellEvents.Activated()`.

**In background tasks: at least on time, and 2 times if `Alias.Updater` feature is enabled.**
1st time through `AliasHolderUpdaterTask.Sweep()`, and, if `Alias.Updater` is enabled, a 2nd time in `AliasUpdaterBackgroundTask` through its `Sweep()` method.

**Possible fix**
I think we need only one when starting the app. No one in background tasks if `Alias.Updater` is not enabled, ond only one if the feature is enabled. This can be easily done by removing the `AliasHolderUpdaterTask` class.

I can do a PR if you agree.

Note: this may break those using this feature without having enabled it.

Best

**Comment by sebastienros** [comment]
I agree. Thanks.
