### ISSUE TITLE
Azure Media Storage don't recognizes its own URLs

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/Orchard#6639]
# Repro steps
- Enable Azure Media Storage
- Add StorageConnectionString
```
<add key="Orchard.Azure.Media.StorageConnectionString" value="BlobEndpoint=http://myaccount.blob.core.windows.net/;AccountName=myaccount;AccountKey=mykey"/>
```
Note that port is not defined in the BlobEndPoint URI
- Add a media to your storage...

# The issue
Now, look at your media's PublicUrl :
It should be :
```
http://myaccount.blob.core.windows.net/media/mysite/mydir/mymedia.ext
```
But it is :
```
http://myaccount.blob.core.windows.net:80/media/mysite/mydir/mymedia.ext
```
The only difference is that the port is defined. Not an issue, it just works... no, not really.

## Assume you want to open your media file
The way to do this is :
```
var storagePath = _storageProvider.GetStoragePath(mediaPart.MediaUrl);
var mediaFile = _storageProvider.GetFile(storagePath);
```
But `AzureBlobStorageProvider.GetStoragePath` checks if `MediaUrl` StartsWith our `BlobEndpoint.AbsoluteUri` (which doesn't contains port), so it fails.

## But it works for MediaProcessing
The reason it works, is that it can handle external medias. When it processes a media from Azure Media Storage, it's handled as an external media.
`ImageProfileManager` should reprocess files if the source is more recent than processed file, so it doesn't works for Azure Media Storage files.

**Comment by TFleury** [comment]
@Piedone, @BenedekFarkas I think you use Azure Media Storage, can you confirm the issue and have a look at my PR ?

**Comment by Piedone** [comment]
Yeah we use it but not with the default blob URL and with our own reverse proxy in front of Bob Storage so probably that's why we didn't see the issue.

Shouldn't instead the PublicUrl creation be changed not to add the port if it's the default for the protocol?

**Comment by TFleury** [comment]
It's what I've done in 8b66c9530f35df8d98c9de7463f127b087f5f10e

**Comment by Piedone** [comment]
So I guess this latter commit is everything needed to fix the problem then?

**Comment by TFleury** [comment]
Yes, the second commit is sufficient to fix the issue. The first is intended to produce cleaner URLs (and also fix the issue if you don't use PublicUrl).
The issue is double fixed :-)
