### ISSUE TITLE
Web distribution via Web Platform Installer fails with A 'script' named 'jQuery' could not be found.

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#6641]
When installing Orchard from the Web Platform Installer, the project is loaded with WebMatrix, launching the site via IIS Express. However, the site immediately fails with a YSOD stating that **A 'script' named 'jQuery' could not be found.**

![image](https://cloud.githubusercontent.com/assets/938393/13985072/ae09561a-f0fa-11e5-8e78-05cfe213a4de.png)

Someone else on CodePlex seems to be having additional issues with the web distribution provided by Web PI: https://orchard.codeplex.com/discussions/652818

**Comment by sebastienros** [comment]
I haven't updated WebPI yet. It must be 1.9.2

**Comment by sebastienros** [comment]
I will submit 1.10 to WebPI and Azure today.

**Comment by urbanit** [comment]
As of today -  06 Sep 2016, same error with creating new site from WebMatrix... Should we repoen issue? cc:/ @sebastienros @sfmskywalker

**Comment by sfmskywalker** [comment]
I experience the same. It fails the first time, then works after a restart of IIS Express or WebMatrix.
