### ISSUE TITLE
Orchard 1.10 and localization 

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#6643]
what in the world am I doing wrong?
just downloaded the official 1.10!

I want to install fr-FR.zip
- I downloaded both the source and the gallery.zip
- Module 'Vandelay Translation Manager' is enabled
- then I did in the command prompt:

cd CMSites\OrgMod_110w\bin
Orchard.exe
install translation d:\BaseWare\Other\Orchard\fr_source.zip (it is there!)

The 'Vandelay Industries 1.8' is installed and 'Vandelay Translation Manager' is enabled when I run the site.
 ... But How is it called when I just want to enable that feature? 
? do I need to do a 'feature enable Vandelay Translation Manager' at all ?
Thanks for advising me, ed

**Comment by Skrypt** [comment]
Do you have set your website default culture to fr-Fr ? It could be that simple. You are supposed to drop the .po files and it just works. Else, you can also enable the admin culture picker to see if it's installed in the right place. I would need to test the command shell if it does'nt work after that. The "Vandelay Translation Manager' is not needed to make this work. It's only a extra tool.

**Comment by edikaufmann** [comment]
well, I'm using Orchard since 1.3 and I always used above procedure!?
Yes I know one can install cultures manually per module  like : App_Data /localization/ fr-FR!
But the command prompt 'Install translation ...' always did it automatically per used module!
All the modules you mentioned are enabled.

**Comment by sebastienros** [comment]
@BenedekFarkas will follow up here as he understands what the problem is.

**Comment by BenedekFarkas** [comment]
That's right, you don't need to use Vandelay.TranslationManager anymore. I just realized that the simplified process is not described on the website, so I just added the "Applying translations" section to http://orchardproject.net/localization.
