### ISSUE TITLE
Codegen don't creates Themes/Modules in right Solution directory

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/Orchard#6644]
Branch master, version 1.10.0
When using codegen with `/IncludeInSolution:true` to create theme/module, it's created at the right place on file system, but it appears at the root of the solution in Visual Studio.

**Comment by CSurieux** [comment]
I experimented this in Dev branch also.
And the created subfolders is not optimal (no Controler, Drivers, Handlers but lot of assets often useless)+ the property file is marked as content.

**Comment by TFleury** [comment]
I identified the problem, a new section was appended to the end of the solution file :
```
GlobalSection(ExtensibilityGlobals) = postSolution
```
and project attachment records are created in it instead of in :
```
GlobalSection(NestedProjects) = preSolution
```
