### ISSUE TITLE
Orchard.Resources Assets missing minified files.

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6648]
Todays download of 1.10.web.zip fresh install try a new blog post and inspect =  shows missing jquery-ui.min.css from Orchard.Resources. 
As are all the minified versions of all files .js and .css.

**Comment by DanielStolt** [comment]
I can confirm that this particular file is missing from the ZIP package.

But as far as I can tell, no others are missing, so I'm not sure what you mean by your second paragraph.

@sebastienros I think you might need to look into this. That file exists in the master branch, but not in the ZIP file.

**Comment by Skrypt** [comment]
#6637 just got merged in today ?

**Comment by DanielStolt** [comment]
Ah, that must be it.

**Comment by DanielStolt** [comment]
I guess we need a `1.10.1` shipped, like, yesterday.

**Comment by sebastienros** [comment]
I confirm it's fixed in 1.10.x already, we talked about it yesterday and merged a PR
