### ISSUE TITLE
Orchard.Resources two different jquery statements.

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6649]
Orchard.Resources = Resource Manifest has jquery as jquery-2.1.4.js
`<Content Include="Assets\Js\jQuery\jquery-2.1.4.js" />`

Orchard.Resources = jQuery.cs has jquery as jquery.js

`manifest.DefineScript("jQuery").SetUrl("jquery.min.js", "jquery.js").SetVersion("2.1.4").SetCdn("//ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.4.min.js", "//ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.4.js", true);`

Actual jquery file is jquery-2.1.4.js and I added jquery-2.1.4.min.js

No .map files anywhere added jquery.min.map

**Comment by DanielStolt** [comment]
There's no incorrectness as far as I can see, looking at tip of `1.10.x`.

I think maybe you're confusing `Assets/` script files with `Scripts/` script files. Only the latter are referenced in resource manifests.

The source jQuery file is named `Assets/Js/jQuery/jquery-2.1.4.js` yes, but in `Assets.json` you can see that this is compiled to `Scripts/jquery.js` which is what the resource manifest references.

**Comment by donaldboulton** [comment]
Why the inconsistency it should be one or the other not jquery-2.1.4.js  and jquery.js. Why have them in both places? Some reason?

**Comment by DanielStolt** [comment]
The idea was to keep the source asset names **with** the version numbers so we can easily see which version we have and have them match the actual source where they come from, but to compile them into scripts/stylesheet files **without** version numbers so as to minimize ripple effect when updating the source assets.

In many cases we compile multiple source files into one target script/stylesheet file, so there is not a one-to-one mapping, so keeping the names matching is not possible.

**Comment by donaldboulton** [comment]
Ok Thanks?
