### ISSUE TITLE
Azure Media Services wrong Microsoft.Azure.KeyVault.Core.dll

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6650]
On clean installation of 1.10 from yesterdays download of the Orchard.web.zip get message of 

The assembly reference 'Microsoft.Azure.KeyVault.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL' could not be loaded for module 'Orchard.Azure.MediaServices'. 

The Microsoft.Azure.KeyVault.Core.dll is NOT in the bin folder
Do not use Azure and its saying. "You need to enable an message bus broker implementation like SQL Server Service Broker".
Nothing Azure is enabled??? 
Or should be on asp.net 4.5.2 IIS 8.5 non Azure

**Comment by sebastienros** [comment]
What's the reason for closing it?

**Comment by donaldboulton** [comment]
Not sure if it was a error or not; doing more research. Getting lots of issues with 1.10 production sites, most likely ftp or server issues. The Microsoft.Azure.KeyVault.Core.dll is in the bin, I was wondering why the error when I am not on Azure, no Azure Modules are enabled.

**Comment by sebastienros** [comment]
Yeah I can't repro here, I assume some of the modules is looking for this dll. If you run `asmspy` on your bin folder you will see which assembly requires it.
