### ISSUE TITLE
Disabling Orchard.Alias with Orchard.Layouts enabled causes DependencyResolutionException (1.10.x)

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#6654]
`LayoutPartHandler` injects `IAliasService`, but `Orchard.Alias` is not a dependency of `Orchard.Layouts`. I didn't add the dependency, because there may be a workaround to exclude it (there's only one method call in the whole module that needs `Orchard.Alias`) if it's possible to achieve the same using existing dependencies.
cc: @sfmskywalker

**Comment by KumarVikey** [comment]
i disable alias of modules in orchard .now i am getting dependency issue .is there any way to enable that alias once again.
