### ISSUE TITLE
User Creation date still 2016 years ago 

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6664]
User Creation date still 2016 years ago in 1.10 web.zip from last Thursday download.
Has user Creation date still at 2016 years ago.
Thought that was fixed?

**Comment by Skrypt** [comment]
I'm not sure about what you mean. Could you precise ?

**Comment by BenedekFarkas** [comment]
That's fixed on the `dev` branch in the commit 4ba75cc9db601baa5b448af9587fdaf0d64e2237 for the issue #6440.
