### ISSUE TITLE
How to 'rebase' 1.9.x code to 1.10.x

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6673]
Using Git Extension, I get an error.
Any documentation available adapted to Orchard SC choices in managing repos ?
Maybe rebase is not the option to use ?
Thanks

**Comment by Skrypt** [comment]
Here is some informations about 2 different approach you could use.
https://www.atlassian.com/git/tutorials/merging-vs-rebasing/summary

**Comment by CSurieux** [comment]
Just pull-merging the 1.10.x and renamed my local from 1.9.x to 1.10.x
