### ISSUE TITLE
Orchard.Resources: DateTimeEditor does not render.

### ISSUE THREAD

**Issue by armanforghani** [OrchardCMS/Orchard#6674]
I have a painful problem. 
The ```DateTimeEditor.cshtml``` template in ```Orchard.Resources``` module does not override the corresponding template in core common module. So i see simple textbox instead of date picker.

I upgraded from ```1.9.x``` to ```1.10.x```. Orchard.Resources was enabled by default but i disabled Orchard.jQuery manually. 

Any help will be welcomed.

**Comment by donaldboulton** [comment]
Most likely same as issue [#6648](https://github.com/OrchardCMS/Orchard/issues/6648)
View your source and see if you are getting jquery-ui.min.css as it was missing in 1.10 zip.

**Comment by armanforghani** [comment]
@donaldboulton, Thank you for your reply.
I am using full source code so unminified version should be sufficient.

**Comment by armanforghani** [comment]
@sfmskywalker Can you help me please? 
This problem is very strange. I found that some configuration (such as Dependencies) in manifest file of a custom module can cause the same problem even when module is disabled. I don't understand the reason.

**Comment by armanforghani** [comment]
@sfmskywalker, Please be aware that if i rename the ```DateTimeEditor.cshtml``` template in common module or add ```Dependencies: Common``` to manifest file of ```Orchard.Resources``` module, ```DateTimeEditor``` shape will be rendered by the template from ```Orchard.Resources``` and Date Picker will appear.

**Comment by thekaveman** [comment]
@armanforghani I just ran into a similar issue, and I think the problem is stemming from the `jQuery` resource definition, specifically, there is a typo in the script definition for `jQueryTimeEntry`

I believe #6637 fixes the issue.

**Comment by armanforghani** [comment]
@thekaveman Thank you so much for your notice but i think my problem is related to the View Engine of Orchard. 
Please note that in my case, view engine does not hit ```DateTimeEditor.cshtml``` template in ```Orchard.Resources``` at all.

**Comment by armanforghani** [comment]
@sfmskywalker , @LombiqTechnologies 

I think ```Common``` should be explicitly included in ```Orchard.Resources``` manifest as a dependency.
I do some debugging and i think it is needed.
View Engine locates templates based on enabled features in dependency order. The list of enabled features come from ```ExtensionManager.EnabledFeatures``` method and this method has a call to ```ExtensionManager.AvailableFeatures()``` method. The later one returns sorted list of all available features (whether active or non-active) and uses ```OrderByDependenciesAndPriorities``` extension method internally. So any custom module can change order of items in available features list even when not activated because ```OrderByDependenciesAndPriorities``` **sorts a collection of elements "by dependency order"**.
Any changes in order of item in available features results changes in order of enabled features. Thus, in some case view engine will pick template out from ```Common``` module instead of ```Orchard.Resources```.

If you are agree i can send a simple PR to fix this problem.

**Comment by armanforghani** [comment]
As a test, you can add an empty module with only one manifest file as the following:
```
Name: Custom Module
AntiForgery: enabled
Author: Arman Forghani
Website: http://orchardproject.net
Version: 1.10
OrchardVersion: 1.9
Description: A custom module related to issue #6674.
Features:
    Custom.Module:
        Name: Custom Module
        Description: A custom module related to issue #6674.
        Category: Custom
        Dependencies: Orchard.Resources
```

You don't need to enable this module. It will change the order of items in AvailableFeatures() list so ```DateTimeEditor``` shape will be rendered with a template from ```Common``` instead of ```Orchard.Resources```.

Of course, This small bug may have some other side effects.

**Comment by donaldboulton** [comment]
I usa getting jQuery issues and date time editor was just one. The fix above on Resources Module.txt fixed all jquery.js and jquery-ui.js issues
@[infofromca](https://github.com/OrchardCMS/Orchard/issues/6682)

**Comment by sebastienros** [comment]
Reopened as I reverted the fix for https://github.com/OrchardCMS/Orchard/issues/6692#issuecomment-204148221

**Comment by sebastienros** [comment]
I assume you could safely remove the template in Common for now. What is weird is that I can correctly see the template from Resources on a local instance, an nobody has ever reported what you are showing.

**Comment by armanforghani** [comment]
@sebastienroz, As i mentioned above you can see the template from Resources because you don't add any custom module which can change the order of enabled features. Default set of modules has correct order accidently! You can try my above test. Adding any module depended on Resources, MediaLibrary, ... can change order of enabled features and cause this issue.
What is your opinion about enabling Common feature by default?

**Comment by jtkech** [comment]
@armanforghani 

In `Orchard.Resources Module.txt`, just below `Description:` try to add `Priority: 1`. Then, if it works, test again if it's ok on a new setup.

Best.

**Comment by armanforghani** [comment]
I can confirm that setting of Priority field resolves this issue and has no side effect on new setup.
@sebastienros I sent a new PR for this issue.

**_Special thanks to_** @jtkech

**Comment by sebastienros** [comment]
Can you put 5 instead? As long as no other module is already using a Priority I think it's better as it give some margin for another one to fit in the middle ... just in case.

**Comment by armanforghani** [comment]
@sebastienros Yes, you are absolutely right. I sent a new pull request.
