### ISSUE TITLE
enabled shape tracing module got js error

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6678]
![tracing](https://cloud.githubusercontent.com/assets/297675/14128432/e7138c8e-f5ee-11e5-81b7-d19ca5ee3ab5.png)

**Comment by urbanit** [comment]
Are you using a CDN jQuery version on your layout? If so, it seems jQuery is loaded 2 times with different versions..

**Comment by sebastienros** [comment]
If this is the case then https://github.com/OrchardCMS/Orchard/issues/6252 could explain. Can you try with  the 1.10.x branch pleae?

**Comment by infofromca** [comment]
It is in local computer , so no CDN.
but maybe both Resource and Jquery are enabled, it happened when I use Script.Require("JQuery");
now i use Script.Require("Guang.NumbersRange") which depends on Script.Require("JQuery"),
it is ok, so close it
