### ISSUE TITLE
RequestTokens, Should not Chain Text?

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#6688]
Hi all,
RequestTokens, in QueryString and Form Token, should not Chain Text?
Is there any reason they should not be chained?
Thank you.

**Comment by Piedone** [comment]
Yes, they should. Would you like to submit a PR for this? You can see how chaining works e.g. in `ContentTokens` (see how Text is declared as a chain target for Body in `Evaluate()`).

**Comment by HermesSbicego-Laser** [comment]
Ok  I will try on a few days (I hope)

**Comment by HermesSbicego-Laser** [comment]
Hi @Piedone,  a little question on Tokens and Chain. 
I would like your advice on how to chain QueryString:* in a proper way
Let's suppose we have a query filtering by token: on TitlePart Contains {QueryString:filter.Limit:10} > it should filter contents where titlepart contains first 10 chars of filter querystring param

Now, In order to recognize correctly the token "filter" and not "filter.Limit:10" I have to change the token evaluation (Orchard.Tokens.Providers.RequestTokens > Evaluate) and use the "." as split char
but what happens if in querystring I have a "." char? e.g. {QueryString:filter.text.Limit:10}
Which is the proper way to proceed?

I think this could be a problem of all "parametric tokens" like {SomePlaceholderForToken:*}

**Comment by Piedone** [comment]
If I understand correctly what you're looking to achieve is chaining tokens on other tokens' parameters. Right? I don't think this is supported at all, nor was it considered before.

However you should be able to chain these tokens (after the modification proposed in this issue) still, i.e. something like `{QueryString:"filter".Limit:10}` or `{(QueryString:filter).Limit:10}`. I don't think either one of these will work currently but we might make them work. Thoughts, @sebastienros , especially in the light of Orchard 2?

**Comment by HermesSbicego-Laser** [comment]
I've seen it already used in TaxonomyTokens {Terms: *} for example. But it is a bit easier there because of the "*" have to be a number

**Comment by HermesSbicego-Laser** [comment]
I've submitted a PR, paying attention to preserve backward compatibility to previous syntax of RequestTokens "Form" and "QueryString". 
Any other suggestions are welcome

**Comment by HermesSbicego-Laser** [comment]
solved with #7356

**Comment by Hazzamanic** [comment]
This only works for QueryString, not for form. This is the chain command in `Orchard.Tokens.Providers.RequestTokens`: 

`.Chain(FilterChainParam, "Text", (token, request) => request.QueryString.Get(token))`

We need different chains for QueryString and Form (and Route?)

**Comment by HermesSbicego-Laser** [comment]
My bad your are right, it seems to work only for querystrings. IMO adding 2 new chains seems to be the right way to proceed.
