### ISSUE TITLE
Content Definition lists are alternated

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#6695]
At some point a css change has lead to this:

![image](https://cloud.githubusercontent.com/assets/1165805/14193635/5adb37e4-f75b-11e5-9a4f-e1ddabcfb429.png)

**Comment by CSurieux** [comment]
I like it

**Comment by Piedone** [comment]
This is intentional, see #2665.

**Comment by Skrypt** [comment]
Constructive comment here. Maybe the border should be set on the bottom without having padding. And the > could be replaced by a .png with transparency.

**Comment by sebastienros** [comment]
Orchard Future Version is our backlog, like, don't do that now ;)

**Comment by Piedone** [comment]
The Orchard Future is now (well, was last June).

@Skrypt yeah, the arrow gif could be transparent. Not sure what you mean by your second suggestion; could you paint it together quickly please?

**Comment by Skrypt** [comment]
Try this.

```
.manage-part h3, .manage-field h3 {
    /* border-bottom: 1px solid #EAEAEA; */
    display: relative;
    line-height: 1.4em;
    padding-bottom: 0;
    padding-top: 0;
}
.manage-part {
    margin-bottom: 1em;
    border-bottom: 1px solid #EAEAEA;
}

.manage-field .details, .manage-part .details {
    overflow: auto;
    margin-top: 20px;
}
```

![image](https://cloud.githubusercontent.com/assets/3228637/14300536/09a260e8-fb5f-11e5-9940-f67594356a5f.png)

**Comment by sebastienros** [comment]
But when you expand the section it's stil lugly

**Comment by Skrypt** [comment]
He said quick ...
