### ISSUE TITLE
Strange syntax in Lists.Projections.ListSortCriteria

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6710]
`public LocalizedString DisplaySortCriterion(dynamic context) {
            bool ascending = Boolean.Parse(Convert.ToString(context.State.Sort));
            return T(@ascending ? "Ordered by {0}, ascending" : "Ordered by {0}, descending", T("Position"));
        }
`

What is the usage of this @ before ascending ?
I found nothing about a c# @operator applied to boolean ? It is supposed to compile...

**Comment by bleroy** [comment]
Looks like a typo. There is no good reason to have a `@` there. Good catch.
