### ISSUE TITLE
Sign In Workflow Activity fails in Orchard 1.10.x

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard#6712]
I have a dynamic form for login that triggers a workflow that signs in the user using the Sign In Activity.
A literal copy of the login page described by IDeliverable in this post http://www.ideliverable.com/blog/customizing-user-registration-and-login-with-dynamic-forms-and-workflows
Problem happens if you login in your site then you stop Orchard site. 
After, you start another time Orchard and login through a dynamic form like the one described in the post. Then you see it fails authorizing the user.

The reason for this bug is when on the second login is this check always returns false because this expression ```userPart.LastLogoutUtc < userPart.LastLoginUtc``` is always false :
```
namespace Orchard.Users.Services {
    public class MembershipValidationService : IMembershipValidationService {

        public bool CanAuthenticateWithCookie(IUser user) {
            var userPart = user as UserPart;

            if (userPart == null) {
                return false;
            }

            // user has not been approved or is currently disabled
            if (userPart.RegistrationStatus != UserStatus.Approved) {
                return false;
            }

            // if the user has logged out, a cookie should not be accepted
            if (userPart.LastLogoutUtc.HasValue) {

                if (!userPart.LastLoginUtc.HasValue) {
                    return true;
                }
                //ALWAYS RETURNS FALSE
                return userPart.LastLogoutUtc < userPart.LastLoginUtc;
            }

            return true;
        }
    }
```
The reason for that is because SignInUserActivity only executes this instruction for login:
```
            _authenticationService.SignIn(user, createPersistentCookie);
```
When indeed it should be done this to store in the userPart the login datetime that will make authorization successful:
```
            _userEventHandler.LoggingIn(userNameOrEmail, password);
            _authenticationService.SignIn(user, createPersistentCookie);
            _userEventHandler.LoggedIn(user);  
```
However this is not enough due to a previous commit that improved performance using following var ```private bool _isNonOrchardUser;```  https://github.com/OrchardCMS/Orchard/commit/d0f8fcdcf7ac524f4e49d370bc4a7f70fa1df787
This var prevents recheck authorization cookie more than one time per request. Problem after previous fix is now SignIn Activity workflow changes the cookie after isNonOrchardUser has been set to true. All of that in the same request. So, the redirect done by the workflow after sigin is not authorized.
I have solved it setting isNonOrchardUser to false when a SignIn method is called successfully.

**Comment by sebastienros** [comment]
Isn't the solution to actually clear the `userPart.LastLogoutUtc` value when a user is logged in? Or is it only done from the triggered events?
