### ISSUE TITLE
CreateUserActivity only allow create users of Content Type User

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard#6714]
It is very easy to make CreateUserActivity able of creating any content type that contains an user part. This will make more powerful this Activity allowing easily to manage scenarios where users have different data associated (for example: buyers profile vs sellers provile).

By the way we can extend MemberShipService to support the creation of any type with an UserPart instead of only allow the users of the User type.

**Comment by sebastienros** [comment]
Please refer to comments in the PR
