### ISSUE TITLE
Recycle bin pager not working

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/Orchard#6732]
In RecycleBin.cs need to replace

query.SetFetchSize(pageSize);
to
query.SetMaxResults(pageSize);

For some reason SetFetchSize does'nt work at all. (NHibernate)

> setMaxResults is the same as LIMIT in SQL- you are setting the maximum number of rows you want returned. This is a very common use case of course. 

> setFetchSize is about optimization, which can change how Hibernate goes about sending the results to the caller (example: buffered, in different size chunks). **setFetchSize is NOT implemented by all database drivers**.

**Comment by sebastienros** [comment]
TODO: check nothing else is using `SetFetchSize`

**Comment by Skrypt** [comment]
This is the only occurence I've found.
