### ISSUE TITLE
Orchard 1.10: No loader found for extension "xy"! 

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#6739]
After upgrading my Site from 1.9.2 -> 1.10 my 'Bîng.Maps' widget doesn't show anymore.
In the debug.log I find messages like:
---
2016-04-09 08:51:52,685 [7] Orchard.Environment.Extensions.ExtensionLoaderCoordinator - (null) - WARN No loader found for extension "Bing.Maps"!
---
and for all downloaded modules from the gallery, in my case for:
"Contrib.GoogleAnalytics"!, "F2B.Orchard.Schedule"!, "FacebookSDK"!, "Orchard.Knockout"!, "Piedone.Facebook.Suite"!

what I'm possibly missing with my upgrade!?
thanks for your time and help, ed

**Comment by infofromca** [comment]
i guess your Bîng.Maps module should use f.net 4.5.32 version as orchard

**Comment by edikaufmann** [comment]
just found it. For whatever reason - in HostComponents.config - 
<Property Name_Disabled" Value was 'true' instead of 'false' 
thanks for your time spent, ed

`<Component Type="Orchard.Environment.Extensions.Loaders.DynamicExtensionLoader">
            <Properties>
                
                <Property Name="DisableMonitoring" Value="true"/>                
                
                <Property Name="Disabled" Value="false"/>    <----------- works with 'false' ----------------------
            </Properties>
        </Component>`

**Comment by edikaufmann** [comment]
well, I probably was a bit early! I.e. with above config it works on my local system (WebMatrix)  but NOT on the deployed ISP site!
thanks for any ideas, ed

**Comment by infofromca** [comment]
do not use WebMatrix.
use vs and source code, add custom module (project) , let it pass building

**Comment by edikaufmann** [comment]
on  my site both WebMatrix and VS2015 works fine

 when HostComponents.config -  <Property Name_Disabled Value="true"
     - I don't see eg widget Bing.Maps (which makes sense)
when HostComponents.config -  <Property Name_Disabled Value="false"
     - I get an error log saying Orchard.Layout not found
(in APP_data/dependebcies Orchard.Layout.dll is listed!; need to investigate more!)

**Comment by BenedekFarkas** [comment]
@edikaufmann is there a transform for this value in your HostComponents.Release.config?

If you do, it won't affect the runtime properties of your application if your build it in VS and run it locally.

**Comment by sebastienros** [comment]
- Change the project to target .NET 4.5.2
- Compile the project locally
- Ensure the /bin for this module is deployed on the server, and remove the .csproj from the server

**Comment by edikaufmann** [comment]
I understand what you mean. However, I'm struggling to create the Bing.Maps.dll in my VS2015 ..
After reading in orchar.net doc: Orchard module loader and dynamic compilation ...
... do I need to change the module.txt!?
embarrassing : what is the procedure?
thanks ed

**Comment by sfmskywalker** [comment]
Hi Ed, to create the Bing.Maps.dll you will need to add the Bing.Maps.csproj file to the solution in Visual Studio, then compile. No need to change the module.txt.

**Comment by edikaufmann** [comment]
I know that I'm not the smartest  ... BUT
- I installed the Bing.Maps .nupgk. It is installed and I see the Bing.maps.csproj.
- Then I run Vs2015
- nowhere can I find a 'Bing.maps.dll' whether when searching my project in the explorer NOR searching the entire project solution in VS2015!? 
what in the world I'm missing!?
Otherwise I, of course, see the DLLs in App_Data/ dependencies just NOT the Bing.Maps.dll
I'm confused on ......  obviously a low level'
thanks for your patience and help!, ed
PS: believe me I use Orchard since 1.3 ... never had such basic issues!

**Comment by sebastienros** [comment]
Skype me, or join our meeting which is in about two hours at http://orchardproject.net/meeting

**Comment by edikaufmann** [comment]
#sebastien #sfmskywalker,
upfront; all is ok again!
thanks to both for not loosing patience and keeping supporting me!. Of course it was lack of knowledge in general and not knowing the  x features of VisualStudio!
#sebastien: thanks for your skype offer  .. I might need it ... some when ....
ed
PS: for some reason I don't have the 'close' option

**Comment by sebastienros** [comment]
Great, you don't see Close because it was already closed.

**Comment by ngvanmy** [comment]
I have same error when enable custom module. It run on local IIS with remote database but when upload all site to remote host it can not run

**Comment by sebastienros** [comment]
@ngvanmy it's usually because your Module doesn't compile or is incorrectly deployed (missing dependencies).

How are you deploying it?

**Comment by ngvanmy** [comment]
I copy all file and folder in Module, include bin and packages folder, to Modules folder on Orchard site. My module using FreeSpire.xls dll, Epplus.dll. 
It can not run after deploying but a few hours after it run, maybe my hosting can not update imediately.
Thanks for your response.
