### ISSUE TITLE
Start background timer after PE tasks, PE tasks list init and isolation.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#6742]
**1st concern**

Because PE through ContextState now uses LogicalData (if no ambient HttpContext), data are carried among threads. This could be desired with async / await codes, or not with some concurent codes.

The data sharing begins on the 1st write and can be broken by writing a `new` object. You can do this in a desired parent thread and / or to isolate it from its parent. So, the Processing Engine would need a new `Initialize()` interface method that can be easily done by using `_entries.SetState(new List<Entry>())`.

**The use case**

On startup, each shell starts in a parallel thread where the following is done:

1. Activate the shell.
2. Where the background timer is activated.
3. Execute Processing Engine tasks.

So, if PE tasks are added in 1, because 2 is in the same thread, the PE tasks list will be seen in the shell background tasks. No problem because PE tasks are not evaluated in the background.

But i've seen a background task that uses `AddTask()`, even if useless here. So, if in 3 there is a quite long running job, a background task could add an entry in the PE list while it is evaluted in 3.

**Suggestion**

Create the `PE.Initialize()` method and call it in `BackgroundService` to isolate background tasks. And also on startup in the `Parallel.ForEach()` at the beginning (so for each shell).

**2nd concern and suggestion**

Maybe not good to start executing a background task while a job on startup is still running. Here, my suggestion is to activate the background timer only when the PE tasks ended? (Could solve the above).

Best.

**Comment by CSurieux** [comment]
Do you know https://github.com/StephenCleary/AsyncEx

**Comment by jtkech** [comment]
@CSurieux thanks a lot for the link, seems very interesting about lock mechanisms, i'll read it. But beyond to be able to run concurently, here the goals are:

Init data (by a 1st write) in the desired parent thread, not in a child one then not seen by its parent. E.g on startup, in the `Parallel.ForEach()`, in each shell execution thread, init PE at the beginning before evaluate it at the end. But here, most of the time there is no additional thread switching.

Deliberately isolate and then not share the same PE tasks list with background tasks, this by writting a new object at the beginning of background tasks. Note: Then, maybe here we could add PE tasks in the background in a separate list and evaluate it at the end.

Prevent background tasks to execute before some jobs are done on startup (e.g some important migrations).

Best.
