### ISSUE TITLE
AuditTrail and Azure.MediaServices should not reference deprecated TaskLease module

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#6749]
The AuditTrail and Azure Media Services should not reference the deprecated TaskLease module. Instead, the should rely on the new DistributedLockService provide by the Framework assembly.

**EDIT**
Turns out the two projects are only referencing the deprecated module, but are already using Distributed Lock Service. So all we need to do is get rid of those references.

**Comment by sebastienros** [comment]
Weird, I checked that recently ... 7e45c5a33929dca87413c458282696abe00587ba

**Comment by sfmskywalker** [comment]
I know, I was surprised because I have the same recollection.

**Comment by sebastienros** [comment]
What branch are you looking at ?

**Comment by sfmskywalker** [comment]
dev

**Comment by sebastienros** [comment]
I checked on github and can't find it.

**Comment by sfmskywalker** [comment]
Ok, let me check again.

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.AuditTrail/Module.txt

**Comment by sfmskywalker** [comment]
Oh wait, I didn;t mean the Module.txt module dependencies, but project references:

![image](https://cloud.githubusercontent.com/assets/938393/14468490/24db3fc0-00e0-11e6-9427-c7b317fe854a.png)

**Comment by sfmskywalker** [comment]
Which means all we need to do is get rid of the project references. I just looked at the code, and it is already using Distributed Lock Service. :)

**Comment by sebastienros** [comment]
Good catch, I am checking all other modules to see if there are hidden references to other deprecated modules.
