### ISSUE TITLE
Replace Media Item: Replacing an Image/OEmbed with new one

### ISSUE THREAD

**Issue by hannan-azam** [OrchardCMS/Orchard#6759]
I'm working on a project where the client has thousands of content items. Each page has media picker which references all the different type of media items Image/Document/Video/OEmbed.

There is no easy way to replace a media item in the Media Gallery. If we delete a media item, all the pages which reference the old media item keeps pointing to a deleted resource. The only method to get it working is to upload a new media item and then go to all those individual pages and update the media picker with the newly uploaded item.

Working with FileSystemStorage Provider it might be a little easy to manually go to Media folder and replace the file there with same name, but on Azure Blob Storage one doesn't have the liberty to do it easily. Also, with OEmbed items which are purely just the content items and doesn't have any physical resource associated it becomes a nightmare to achieve the goal.

**It would be very nice if we could change the Media Item upload mechanism a little. While uploading the resource, if the media item with same name exists, we present the user a checkbox to confirm if the user wants to replace the existing item or upload the item as a new resource**

Please advise what are your thoughts.

**Comment by CSurieux** [comment]
We should be able to create a new Version of a Media Item (image,video or ducument, etc) just by changing the attached file, so we should not have to go and change all the medialibrary picker fields  included in other content items.

**Comment by sebastienros** [comment]
I think there is already an issue for what Christian is suggesting, I agree. There was even a PR at some point from Jeff Holstmed (sorry for the typos in the name) but there were some issues with corner cases.
I think the idea is to provide another page to overwrite an existing file, that can be launched from the media edit page. Like "Change media content".

**Comment by hannan-azam** [comment]
@sebastienros @CSurieux  @sfmskywalker , finally it is here. Please take out sometime to review the code changes and let us know if you have some more ideas to make it better. We can also discuss this in detail may be in weekly Orchard call. Thanks.

https://github.com/OrchardCMS/Orchard/pull/7160
