### ISSUE TITLE
Imported taxonomies loose their owner and weight

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6760]
Last Dev version.

**Comment by sebastienros** [comment]
I didn't look at the Owner but the weight worked for me. Exported terms, deleted them, imported them, they kept the weight and order after import.

**Comment by CSurieux** [comment]
I did it 2 weeks ago, importing in a recipe. I just discovered there are no weight and owners for terms.

Envoyé à partir de mon sanyo phc 25
________________________________
De : Sébastien Ros<mailto:notifications@github.com>
Envoyé : ‎13/‎04/‎2016 19:35
À : OrchardCMS/Orchard<mailto:Orchard@noreply.github.com>
Cc : CSurieux<mailto:christian.surieux@hotmail.fr>
Objet : Re: [OrchardCMS/Orchard] Imported taxonomies loose their owner and weight (#6760)

I didn't look at the Owner but the weight worked for me. Exported terms, deleted them, imported them, they kept the weight and order after import.

---

**Comment by sebastienros** [comment]
Now I understand how to try to repro, it's actually importing a Term which doesn't these properties in the recipe, they could get removed. Will try that.
