### ISSUE TITLE
Orchard.Layouts AssemblyInfo.cs version 1.0.0.0 not 1.10

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6762]
Orchard.Layouts AssemblyInfo.cs version 1.0.0.0 not 1.10 in dev and 1.10
[AssemblyInfo.cs](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Layouts/Properties/AssemblyInfo.cs)

**Comment by BenedekFarkas** [comment]
Fixed in other modules as well.

**Comment by donaldboulton** [comment]
Nice thanks
