### ISSUE TITLE
Admin UI: ContentController allows creating content items with a random type name

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#6769]
Repro:
- Go to `/Admin/Contents/Create/asdasd` (assuming you don't actually have a content type with the name `asdasd`, but if you do, I salute you).
- You'll see an empty editor with only a `Save` button. Do **not** click it if you value your life. Just kidding, click the button. I double dare you. Come on, do it.
- A content item and a shadow (how dramatic!) content type will be created (`ContentTypeRecord`, `ContentItemRecord` with `ContentType_id` pointing to the type and `NULL` for `Data`, `ContentItemVersionRecord` with `NULL` for `Data`).

Additionally, you can try actually creating the type (`asdasd` in this case): you'll be able to do that and it's technical ID won't get a suffix, but the item previously created won't be showing up in the `Contents` menu, because it has no data.

**Comment by Skrypt** [comment]
I actually have a content item named asdasd. :P

**Comment by sebastienros** [comment]
TODO: Validate the content type actually exists on GET and POST actions

**Comment by rtpHarry** [comment]
@BenedekFarkas you found your own bug again two years later haha #4723
