### ISSUE TITLE
Can't access DistributedLockRecord table on setup + possible fix

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard#6783]
In `AutomaticDataMigrations.cs`, before, `_transactionManager.RequireNew()` was called after creating the schema of the `DistributedLockRecord` table. Apparently with `PostgreSQL` we need to do it before, see #6729. But, since this update, i get nhibernate exceptions on a new setup (sqlce).

This because we still need `_transactionManager.RequireNew()` after creating the schema, otherwise, when 1st trying to acquire a lock on setup, we can't access the `DistributedLockRecord` table.

Indeed, when doing this it works

            if (!distributedLockSchemaBuilder.SchemaExists()) {
                // Workaround to avoid some Transaction issue for PostgreSQL.
                _transactionManager.RequireNew(); // line added for PostgreSQL
                distributedLockSchemaBuilder.CreateSchema();
                _transactionManager.RequireNew(); // new line for my tests
            }

But here there are 2 `RequireNew()`. Let me know what we have to do.

Best.

**Comment by sebastienros** [comment]
I don't get this issues locally.

**Comment by jtkech** [comment]
Forgot to say on the dev branch.

**Comment by jtkech** [comment]
Re-tried, here the beginning of the exception

`2016-04-16 00:49:08,940 [11] Orchard.Recipes.Services.RecipeScheduler - Default - INFO All recipe steps executed; restarting shell.
2016-04-16 00:49:09,567 [11] Orchard.Tasks.Locking.Services.DistributedLockService - Default - ERROR An error occurred while trying to acquire lock 'DistributedLock:Default:Orchard.Data.Migration.AutomaticDataMigrations'.
NHibernate.Exceptions.GenericADOException: could not execute query
[ select distribute0_.Id as Id212_, distribute0_.Name as Name212_, distribute0_.MachineName as MachineN3_212_, distribute0_.CreatedUtc as CreatedUtc212_, distribute0_.ValidUntilUtc as ValidUnt5_212_ from Orchard_Framework_DistributedLockRecord distribute0_ where distribute0_.Name=@p0 ]`

**Comment by jtkech** [comment]
On the **dev** branch and on a **new setup**.

**Comment by DanielStolt** [comment]
I'm seeing the same, `dev` on new fresh installation, on SQL Server.

**Comment by sebastienros** [comment]
Action: revert the commit and reopen the issue. Only accept a patch that won't break SQL server.

**Comment by jtkech** [comment]
@sebastienros 

So, do i have something to do here?

**Comment by sebastienros** [comment]
No, I will revert the commit

**Comment by jtkech** [comment]
@sebastienros 

I think this commit is not reverted

**Comment by sebastienros** [comment]
I applied the fix on 1.10.x too
