### ISSUE TITLE
Cache Statistics wrong url

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6787]
Not a Admin url.
`/Orchard.OutputCache/Statistics`

Should it not be

`/Admin/Orchard.OutputCache/Statistics`

Also some other modules urls are the same way, NO `/Adimin/`
Will look around to see if I can find them and update this issue.

**Comment by sebastienros** [comment]
If it doesn't begin by admin then it's either it's not an `AdminController` and doesn't have the `[Admin]` attribute, which would be an issue, or that it has a custom route and then it's ok.

**Comment by sebastienros** [comment]
I checked and it has an `[Admin]` attribute so there is no issue with this controller or route, it's just different.

**Comment by donaldboulton** [comment]
Creates a issue for the fork [Feature Admin Theme Amaretti](https://github.com/sfmskywalker/Orchard)
Admin navigation does not understand `/Orchard.OutputCache/Statistics`
And why not be consistent.
`/Admin/Orchard.OutputCache/Statistics` gets at 404 error.
It is a Admin, "url" and should be, been like this for years and it should be corrected

**Comment by rtpHarry** [comment]
It is an issue, I have it open in #5905. Perhaps not a security issue but a usability one. The problem is that it blocks users from creating pages using those urls for public facing content. It seems like it is an oversight that they haven't been standardised.

**Comment by sebastienros** [comment]
So you mean the issue is that a user could create page with the same url, that is a valid concern. The other bug explains that more clearly.
