### ISSUE TITLE
Publish Now button not work in latest 1.10.x

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6788]
no error. just not react

**Comment by donaldboulton** [comment]
I cannot get 1.10 to publish as Orchard.Resources has a broken reference to `<add assembly="Orchard.Layouts" />` on line 35 of its web.config.
Looking for layouts version 1.0.0.0 which was the Assembly.info. The Module.txt for layouts is Version: 1.10.
Was fixed from issue [#6762](https://github.com/OrchardCMS/Orchard/issues/6762), but I still get the error in last nights 1.10 src download. I will try it again, maybe a build issue.
