### ISSUE TITLE
Sort Taxonomies Terms failed when parent not found in paginated view

### ISSUE THREAD

**Issue by pacomonfort** [OrchardCMS/Orchard#6795]
Orchard 1.10 on March 18th
If you add new Taxonomy with this terms

a;a
    b;b
        c;c
        c1;c1
        c2;c2
        c3;c3
        c4;c4
        c5;c5
        c6;c6
        c7;c7
        c8;c8
        c9;c9
        c10;c10
        c11;c11
    d;d

When you view the terms of that Taxonomy paginated to 10 , the second page fails.

The bug is in the compare method of TermPart.cs, in 

```
                if (!xFullPath.Equals(yFullPath, StringComparison.OrdinalIgnoreCase)) {
                    var xParent = _index[xFullPath]; <---- Here, when _index not contains xFullPath
                    var yParent = _index[yFullPath];

                    return Compare(xParent, yParent);
                }
```

**Comment by komodosoftware** [comment]
Is there a workaround for this prior to 1.10.2 being released? Or could the Taxonomies project from 1.10.2 be used in a 1.10.1 build as a direct replacement?

**Comment by Piedone** [comment]
Yes, you can simply put the module from 1.10.2 into an 1.10.1 solution.

**Comment by komodosoftware** [comment]
Thanks - ended up copying just the contents of the Index view from 1.10.2 to fix the problem, but I'll copy the entire module when I get chance...
