### ISSUE TITLE
Idea: Move Deprecated modules to a custom folder

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#6797]
Since 1.10, custom folders are supported to load extensions from. We could move the deprecated modules - the ones that are in the `Modules.Deprecated` solution folder - to an actual folder (alongside `Modules`) with the same name. What do you think?

**Comment by DanielStolt** [comment]
What's the advantage?

**Comment by BenedekFarkas** [comment]
The solution and file system folders would show the same structure.

**Comment by DanielStolt** [comment]
Ok. :)

Could it perhaps also make it easier to disable harvesting of the deprecated modules by removing that folder from the configured list of extension folders?

**Comment by sebastienros** [comment]
Having the same structure is not a good enough reason IMO. We could break things. 
We can't remove them completely as they are required by previous versions. Removing them, moving them to another folder, or not harvesting them would have the same effect.
I don't really want to change anything there right now, they don;t hurt anyone. And anyone can already remove any module that they don't want to deploy/load.

**Comment by BenedekFarkas** [comment]
Even if we would move them to a different folder on the file system, that would be a breaking change in terms of project references.
