### ISSUE TITLE
Add ReSharper support to the Razor view engine

### ISSUE THREAD

**Issue by mroskamp** [OrchardCMS/Orchard#6815]
ReSharper  is unable to resolve views when using Orchard, so we get numerous errors in R# that are really false positives. Someone from the R# team recommended a fix to allow the resolution of views.

Here's the R# recommendation, for reference: http://spermophilus2.rssing.com/browser.php?indx=3176698&item=47964

Here's the pull request: #6814

**Comment by GlobalHealthLtd** [comment]
I have applied this fix to the RazorViewEngineProvider.cs and rebuild Orchard.Framework, what else do I need to do as it still complains "Cannot resolve view ..." by ReShaper (2025.1.4) in VS 2022.

<img width="1698" height="574" alt="Image" src="https://github.com/user-attachments/assets/d184bb85-245f-40f7-8aa9-5193e0512641" />
