### ISSUE TITLE
Export-Import recipe breaks taxonomy elements

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard#6821]
Taxonomy element (dynamic forms) stores the TaxonomyId of the taxonomy you selected to render on it.
If you Export the complete site through a recipe using Impor/Export module, when you create a site from scratch using that recipe, it is very likely your Taxonomy Elements have a TaxonomyId invalid because on the new site the Taxonomy you referenced has now another Id.

If you do it a simple test it is easy you don't notice the problem, but as soon as you work in a bigger project you start to see yourself fixing one time and another time references to taxonomies in taxonomy elements. It looks that solution will be to use an alias instead of the taxonomyId for importing/exporting TaxonomyId field.

**Comment by jersiovic** [comment]
I've been trying to solve it, but I'm not sure what's best approach. 
Element models are serialized in LayoutPart.LayoutData and those are "rehydrated" when it is needed. So, export operation simply takes that LayoutData, so there is no opportunity to replace the id per an Alias at this point because the Taxonomy Element is serialized directly without any translation step.

The easiest solution I see is to add an extra field to the Taxonomy Element: string TaxonomyAlias that will be also serialized with its other properties. Next, I will override in TaxonomyElementDriver following methods: Exporting, Exported, Importing, and Imported. In Exporting method I will update the TaxonomyAlias property based on TaxonomyId. Finally, in Imported method I will update TaxonomyId using TaxonomyAlias to get its value.

Do you agree this is the best way to solve the issue?

**Comment by sfmskywalker** [comment]
Hi Sergio, elements have the opportunity to store additional information during the export phase to handle this scenario for example where it needs to store a content identity. If you look at the Projection element and its drive, you'll see how it works.

**Comment by jersiovic** [comment]
Ahh I see!  
Thank you Sipke :)
