### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by risogolo** [OrchardCMS/Orchard#6830]

**Comment by sebastienros** [comment]
Because it's a potential security issue we need to analyze, could you send a full repro and the potential impact you found at orchard@microsoft.com as explained on this page http://docs.orchardproject.net/Documentation/Security-Researcher-Acknowledgments.

Thanks

**Comment by sebastienros** [comment]
I removed the details from the post on purpose until we have validated it internally.

**Comment by risogolo** [comment]
Repro steps were sent

**Comment by risogolo** [comment]
Any news?
