### ISSUE TITLE
@Csurieux reports that this not watch

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/Orchard#6834]
> assets.json:
> 
> [
> {
> "inputs": [
> "Assets/Less/Lib/Bootstrap/bootstrap.less",
> "Assets/Less/Lib/FontAwesome/font-awesome.less"
> ],
> "output": "Styles/Lib.css",
> "watch": [ "Assets/Less/Lib/Bootstrap/variables.less" ]
> },
> {
> "inputs": [ "Assets/Less/Site.less" ],
> "output": "Styles/Site.css",
> "watch": [ "Assets/Less/common.less","Assets/Less/layout.less", "Assets/Less/bootswatch.less" , "Assets/Less/lib/bootstrap/variables.less" ]
> },
> 
> {
> "inputs": [ "Assets/Less/Home.less" ],
> "output": "Styles/Home.css",
> "watch": [ "Assets/Less/common.less", "Assets/Less/layout.less", "Assets/Less/bootswatch.less" , "Assets/Less/lib/bootstrap/variables.less" ]
> },
> 
> {
> "inputs": [ "Assets/Less/Blogs.less" ],
> "output": "Styles/Blogs.css",
> "watch": [ "Assets/Less/common.less","Assets/Less/layout.less", "Assets/Less/bootswatch.less", "Assets/Less/lib/bootstrap/variables.less" ]
> },
> 
> {
> "inputs": [ "Assets/Less/Logon.less" ],
> "output": "Styles/Logon.css",
> "watch": [ "Assets/Less/common.less","Assets/Less/layout.less", "Assets/Less/bootswatch.less", "Assets/Less/lib/bootstrap/variables.less" ]
> }
> ]
> 
> This does not watch ?

Continue discussion on this here please.

**Comment by Skrypt** [comment]
Get me repro steps in a clean issue other than this one. With a reference to this well known gulp problem.

**Comment by CSurieux** [comment]
Thanks but I alredy reported this 2 times and it has been closed....
https://github.com/OrchardCMS/Orchard/issues/6230
and
https://github.com/OrchardCMS/Orchard/issues/5849

**Comment by Skrypt** [comment]
I won't close this one untill you found a proper solution even if it is specific for yourself. Maybe there is something that we missed and I want to know what you found exactly.

**Comment by CSurieux** [comment]
Certainly 'you' are missing something.
But sorry I have so many urgencies, I can't spent more time on it. Thanks.

**Comment by Skrypt** [comment]
Ok then I'm closing this issue. But don't complain that I did. I was there to help you. Feel free to elaborate later on this issue here. Thanks.

**Comment by CSurieux** [comment]
Well you opened it and closed it. With my id. Why should I complain, I did nothing :)
On some subjects, as I was saying on the other thread, we need more than goodwill, even if goodwill is always welcome.
Reading carefully and giving time to time is often a good starting point.

**Comment by Skrypt** [comment]
I believe that you have the right to be opiniated. Though for understanding your issue with the gulp pipeline. I need more than just what you gave me. I need either repro steps or a detailed explanation of what you are doing exactly. Saying that it just does'nt watch would'nt give me enough cases to rewrite the entire gulp pipeline. And I believe that's not the point either.

I think you maybe need to refactor the way you implemented your LESS files or just use a custom solution. That's mainly why the gulp watch task is never starting by default. It is also there to be customized... that's the beauty of open source there. So, the problems are mainly due to the fact that you have a custom made theme wich does'nt suit the way the gulp pipeline works.

The first questions to ask ourselves then is : 

- do we want to support all custom made themes or we want to provide a strong base code for people to use ?
- What does happens when Wordpress gets breaking changes that breaks themes ?
- Does paid themes gets updated properly ?
- How long do they get supported ?

**Comment by CSurieux** [comment]
Ok, Ok. Thanks.
I have not a paid theme Bootswatch is open source and used by hundred people.
I have not implemented a special thing, all standard.
Thanks for your offer to help and your global efforts on Orchard.

**Comment by Skrypt** [comment]
But why then do you need to watch the Bootstrap variables.less file if you're not trying to customize the base theme without overriding it ? Having Bootswatch is about overriding those css class's.

![image](https://cloud.githubusercontent.com/assets/3228637/14828495/30c879da-0bb5-11e6-9f73-9ecf5d66b676.png)

What I'm trying to say here is that you maybe should watch the Bootswatch variable.less file instead of the Bootstrap variable.less file.

The Lib.css file already includes the Bootstrap variables.less file.

**Comment by CSurieux** [comment]
Look and try it it is here, many people use it
http://bootswatch.com/
-> Easy to Install
Simply download a CSS file and replace the one in Bootstrap. No messing around with hex values.
Well sorry but I have no more time.

**Comment by Skrypt** [comment]
I have plenty of time this week :smile: I will leave you the last words if you say that you don't have more time to fix your issue.

**Comment by CSurieux** [comment]
Sorry but I don't understand ? If you have plenty of time that's good for you.

I would not have reported if I had proofs it is my mistake.
Look my history of reported issues in codeplex and here. Few of them were not real orchard problems.
Don't let some guy fool your mind.

**Comment by Skrypt** [comment]
I will test your Asset.json file later on today and tell you what I found.

**Comment by Skrypt** [comment]
Tested and made it work. The gulp watch works as expected.

**Comment by CSurieux** [comment]
Perfect.

**Comment by Skrypt** [comment]
What is perfect ?
