### ISSUE TITLE
Publish later tasks on older content item versions still execute/are not removed when a newer version is published

### ISSUE THREAD

**Issue by andrewcartwright1** [OrchardCMS/Orchard#6840]
When using the audit trail part on a content item, if a content item is saved by pressing publish later, but then published and a newer version is also published (i.e version 2) when the publish later time is hit, the older version of the content item will be published.

Replication Steps: As an admin
- Enable the audit trail module and attach the part to a content item
- Create a content item and click ​_save_​
- With the same content item set a publish later date and click ​_publish later_​
- With the same content item click ​_publish now_​
- With the same content item click ​_save_​
- With the same content item click ​_publish now_​

Wait until the publish later time has passed and then check the audit trial and the front end site

Example:

![zappshot - 2016-04-26_04-31-21-pm](https://cloud.githubusercontent.com/assets/10059155/14824330/7fdc95f2-0bcd-11e6-9652-884e98c3ecdf.png)

**Comment by sebastienros** [comment]
Does it happen also when you are not using the audit trail part? Trying to understand if the issue is related to it or not.

**Comment by andrewcartwright1** [comment]
Yes, It also looks to be an issue without the part, audit trail below is from Orchard.AuditTrail

![zappshot - 2016-04-29_08-36-47-am](https://cloud.githubusercontent.com/assets/10059155/14910477/990bbf7a-0de5-11e6-9c2c-dd2af5260592.png)

**Comment by sebastienros** [comment]
Thanks, it will help us to replicate and fix the issue.

**Comment by gcsuk** [comment]
Is anyone working to fix this? If not, I will look into it

@sebastienros @sfmskywalker

**Comment by sfmskywalker** [comment]
All yours. Thanks!

**Comment by gcsuk** [comment]
@sfmskywalker PR open 😄
