### ISSUE TITLE
Element Bindings of Dynamic Forms breaks when you add a new field to the content type bound to the form

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard#6842]
If you have a dynamic form bound to a content type, and an element bound to one field in that type.
After you add a new field to the definition of one content part of that type most of the times when you review the bindings of the elements you see them broken. I mean the element is bound to a different field than the original.

I have observed it only happens if the new field I add to the content type has an alphabetical position previous to any of the existing fields in the part that is bound to an element in the form.

For example if initially we have this configuration:
Test Type:(TestPart: Field1)
Form Test  bound to Test Type with an Element bound to Field1

If I add another field that alphabetically is positioned at the end, everything works properly:
Test Type:(TestPart: Field1,Field2) 
Form Test  bound to Test Type with an Element bound to Field1

If I add another field that alphabetically is positioned before bounded Field, it breaks the binding:
Test Type:(TestPart: AnotherField,Field1,Field2) 
Form Test  bound to Test Type with an Element bound to AnotherField

I have solved this issue that was giving us a lot of headaches last weeks because bug was at rendering time of the BindingSettings of elements. Problem was that when you save an element after adding a field to a content type, you break the bindings of those elements cause viewmodel built by the view is wrong.

I send a PR just in a moment

**Comment by jersiovic** [comment]
Same thing could happen with new parts in the bound type, I also have fixed it.

**Comment by donaldboulton** [comment]
I have a Content type Tickets that has a message text area.
I created a form widget then associated it with Tickets Content Type, the bindings are to the Tickets fields. I save it go to a page with the Ticket Form and inspect element it has associate my Message text area with Orchard.Comments. Comment Message text area.
Fill in the form and submit it, I get a error over the comment form that I must fill in the Message Text area.
Other dynamic form errors.
Try to add a Url field to a dynamic form. When I try to save the form by save or publish, on creation it tells me that I need to fill in the URL field, "upon creation", either save or publish,. Even if I fill in the Url field same thing, so I cannot save the form.
