### ISSUE TITLE
gulpfile.js - migrate gulp-minify-css to gulp-clean-css

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#6844]
1.10.x

When you run `npm install` this message is shown:

    npm WARN deprecated gulp-minify-css@1.2.1: Please use gulp-clean-css

The gulpfile needs updating to migrate gulp-minify-css to gulp-clean-css.

**Comment by DanielStolt** [comment]
@rtpHarry In `dev` this has already been replaced by `gulp-cssnano`. I don't think we should change this for `1.10.x` unless we have to. Unless we start changing package versions (which we shouldn't) this will continue to work.

**Comment by rtpHarry** [comment]
ok thanks for the heads up I didn't realise it was already dealt with
