### ISSUE TITLE
Outputcache should always vary by scheme to prevent SSL bypass

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/Orchard#6850]
The Outputcache currently does not differentiate between the scheme (http/https) which will allow a visitor to bypass SSL on pages configured in to be served under https in SecureSocketsLayer module.

**Steps to reproduce issue 2:**

1. Enable OutputCache
2. Enable SecureSocketsLayer
3. Configure a convenient cache time to reproduce the issue, e.g. 600
4. Configure a secure URL, e.g. "~/contact-us"
5. Create a page with the autoroute "contact-us"
6. Important: **LOG OFF**

8. Navigate to the secure URL http://localhost:30321/contact-us
9. You should be redirected to https://localhost:44300/contact-us

11. LOG BACK IN
12. Confirm in Admin/Cache that /contact-us is now cached
13. Important: **LOG OFF**

15. Navigate to the INsecure URL http://localhost:30321/contact-us

**Expected result:** Redirect to Secure URL
**Actual result:** No redirect, serving cached INSecure URL

The reason for this, is that in the first request (step 8) OutputCache does not find the page in its cache therefore the filters are executed. The SSL filter returns a 302 redirecting the browser correctly to the secure URL (step 9), which is subsequently cached and rendered back to the browser.

On the second INSecure request (step 15), the OutputCache now finds the page in its cache, and immediately returns the cached version, however this is the Secure version (from step 9) now being served under http.

There are a few solutions, one of which is putting the SSL filter before the OutputCache, but that just adds more processing to every cached request. By far the simplest solution, possibly also the most hardened, is to add the scheme de facto to the cache key.

Will submit the PR right away.

**Comment by DanielStolt** [comment]
Good catch. I agree - look forward to your PR.

**Comment by anoordende** [comment]
Created PR #6851

Not the most exiting of PR's @DanielStolt but one that automagically does the trick :8ball:

**Comment by DanielStolt** [comment]
The simplest, cleanest and most surgical PRs are the best ones IMO! :)
