### ISSUE TITLE
Stability and Publish errors because of Layouts [assembly: AssemblyVersion("0.0.0.0")]

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6853]
Created [#6762](https://github.com/OrchardCMS/Orchard/issues/6762) which was corrected but on trying to publish the latest dev or 1.10x Dashboard says:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not load file or assembly 'Orchard.Layouts' or one of its dependencies. The system cannot find the file specified.	Orchard.Web	`C:\OrchardWeb\src\Orchard.Web\obj\Release\AspnetCompileMerge\Source\modules\orchard.dashboards\web.config`	
Line 35	
Which is `<add assembly="Orchard.Layouts" />`

If you view the reference in any Module referencing Orchard.Layouts it still version 0.0.0.0 not 1.10
Assembly info for Layouts is `[assembly: AssemblyVersion("1.10")]`
Delete =reference and add it again still version 0.0.0.0
What would I need to change to get this to Compile and publish off of latest source?
Made all the changes from [#6829](https://github.com/OrchardCMS/Orchard/pull/6829)
still the same error.
Versions now are correct 1.10 but the same publishing error???

**Comment by anoordende** [comment]
These references between modules are project based so the version will be in sync with whatever the version of the Orchard.Layouts.dll in the bin folder is. Have you tried running the PowerShell script .\CleanSolution.ps1 followed by a build of the solution? After applying the changes from #6829 that is definitely a good start.

**Comment by donaldboulton** [comment]
I run CleanSolution.ps1 after every publishing try. 
Someone try it, try to figure it out, its beyond me whats up.
It still will not publish, Iunless you remove Layouts and Dynamic forms and references to them, then it will, but without two essential modules.
If you ever noticed no Orchard package has been compiled and published, just Zipped up files and call it good. I got 1.10x several weeks  ago to publish then they merged dev and now it wont, Not sure what changed. Get it to publish compiled and see the performance difference and the size with most all files in, ".dll's", is much smaller than all the files, easier to ftp.
I cannot get Orchard to work on my server unless it is published = 3 years now working with Orchard just by ftping the Orchard.Web.zip or a built version it will not work.

**Comment by LivyChops** [comment]
@donaldboulton did you discover a solution or did later builds sort this (as I'm suffering from the same thing)? Thanks in advance, Liv

**Comment by sebastienros** [comment]
The assembly versions have been fixed in the latest release.
