### ISSUE TITLE
Orchard 110: import/export 

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#6854]
Exporting some CI out of 1.9.2 seems to work ok (always worked)! Importing this file into 1.10 seems to work also (at least no error msgs)! Export: with data and metadata.
BUT I cannot find these imported CIs in 1.10

Are there any known restrictions?
thanks for your time and help, ed

**Comment by Skrypt** [comment]
The import/export module got an upgrade. The only workaround I found is modifying the export.xml files to be able to do that. You could alternatively upgrade your database on a separate database and then export those Content Items with the new import/export module.

**Comment by edikaufmann** [comment]
thanks for your time. Well, modifying the .xml wasn't to big a task - all ok now
