### ISSUE TITLE
Add SASS support to Gulpfile.js

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/Orchard#6860]
The Gulpfile currently supports LESS, but it would be great to let our SASS users feel some Orchard love too (me for one). This could become increasingly important with the uptake of Bootstrap v4.

Will submit the PR.

**Comment by anoordende** [comment]
Created PR #6861

**Comment by sebastienros** [comment]
Good, I also had to do it on the Orchard2 repository https://github.com/OrchardCMS/Orchard2/blob/master/gulpfile.js

**Comment by anoordende** [comment]
@sebastienros in Orchard2 it seems that the _maxListeners warning is also fixed. Maybe worth adding that to the PR too?

**Comment by sebastienros** [comment]
Feel free. But you can also just keep this PR focused and create a new one in case it blocks it. Up to you.

**Comment by anoordende** [comment]
Agreed, I will leave this PR as is.
