### ISSUE TITLE
Transaction does not get canceled on exception in web api

### ISSUE THREAD

**Issue by kumards** [OrchardCMS/Orchard#6868]
Hi,

I found that when there is an exception in asp.net web api controller request, the db transaction does not get canceled, leaving partial changes persisted in the database. But the db transaction gets canceled with asp.net mvc controller on exception. I think, we will have to add an exception filter for web api controller request as well.

**Comment by kumards** [comment]
Fixed in #6833

**Comment by sebastienros** [comment]
Why did you close the issue?
