### ISSUE TITLE
Pb with last sass addition in gulpfile.js

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6871]
task Runner is broken with this error

Failed to run "C:\Jingwei\src\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
Error: Missing binding C:\Jingwei\src\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32-11\binding.node
Node Sass could not find a binding for your current environment: Windows 32-bit with Node 0.10.x
Found bindings for the following environments:
  - Windows 32-bit with Node 0.12.x
This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (C:\Jingwei\src\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:14:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Jingwei\src\node_modules\gulp-sass\index.js:187:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Failed to run "C:\Jingwei\src\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
Error: Missing binding C:\Jingwei\src\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32-11\binding.node
Node Sass could not find a binding for your current environment: Windows 32-bit with Node 0.10.x
Found bindings for the following environments:
  - Windows 32-bit with Node 0.12.x
This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (C:\Jingwei\src\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:14:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Jingwei\src\node_modules\gulp-sass\index.js:187:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

It appears I have Node 0.12 rather than Node 0.10 installed.
How to fix this ?

**Comment by CSurieux** [comment]
I removed the sass related lines in gulpfile.js as I don't need it actually....

**Comment by infofromca** [comment]
i got the same

**Comment by Skrypt** [comment]
This is a problem related to node-sass itself. You need to rebuild it for your specific OS.
Alternatively you can download the bindings directly here : https://github.com/sass/node-sass-binaries

**Comment by CSurieux** [comment]
Yes, I also can read VS error text and Google results, thanks. I don't think I will follow your reco, sorry. But thanks.

**Comment by Skrypt** [comment]
You can also do that, it will save me time from answering issues that are not related to Orchard. You are welcome :smile:

**Comment by CSurieux** [comment]
I don't agree with all this. Your answer was a no answer and I am not the only to report this.
If answering is copying Google results...poor Orchard....
But wait, I could also stop reporting pbs and let you discover all of them/.

**Comment by Skrypt** [comment]
Error: Missing binding C:\Jingwei\src\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32-11\binding.node

Can you read ?

**Comment by CSurieux** [comment]
Yes I can read and I have done all that is necessary but there is a bug.
Et stp, lâche-moi merci, pour qui te prends-tu ???

**Comment by Skrypt** [comment]
Où est le bug concernant Orchard ici ?
Voici où le problème doit être rapporté :
https://github.com/sass/node-sass/issues/1162
 Il est connu. Et les instructions sont claires.

**Comment by Jetski5822** [comment]
Seems like this is a node-sass issue reading through what @Skrypt mentioned... Can you try this to see if it fixes things?

```
npm rebuild node-sass
rm -rf node_modules
npm i
```

**Comment by Skrypt** [comment]
Here is some additional information for that bug.
Visual Studio uses it's own version of Node.js so if someone wants to use a manually installed version of Node.js or that wants to upgrade it, here is what you need to do. Since node-sass needs to have bindings to it libsass.dll we need to recompile it each time we change Node.js versions "could be for an upgrade or downgrade". Though it will not be necessarly the same version that the Task Runner uses in Visual Studio. So if we want to use the latest version of Node.js with Visual Studio you need to update it's tool settings like explained there : 

http://ryanhayes.net/synchronize-node-js-install-version-with-visual-studio-2015/

**Comment by sebastienros** [comment]
I faced the same issue on my machine.
