### ISSUE TITLE
Non steering comittee members should not have right to close issues

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard#6874]
Especially without reasons as for #6871

**Comment by Skrypt** [comment]
This has nothing to do about steering comittee @CSurieux. If you have a problem with me then it is a different problem. And I'm not the only one closing your issues because they lack respect of people in here. And don't expect me to not be arrogant if you are. Thanks.

I will leave this one open.

**Comment by CSurieux** [comment]
I have no problem with you.
You are a problem for Orchard. 
There is no continuing to discuss with you.

I will stop reporting errors because this project is going out of control.

**Comment by Skrypt** [comment]
Please file complaints against me here.

**Comment by DanielStolt** [comment]
@CSurieux yes please do us all a favor and stop participating in this project.

**Comment by CSurieux** [comment]
You are the instigator of all this.
I leave.
________________________________
De : Daniel Stolt<mailto:notifications@github.com>
Envoyé : ‎07/‎05/‎2016 19:12
À : OrchardCMS/Orchard<mailto:Orchard@noreply.github.com>
Cc : CSurieux<mailto:christian.surieux@hotmail.fr>; Mention<mailto:mention@noreply.github.com>
Objet : Re: [OrchardCMS/Orchard] Non steering comittee members should not have right to close issues (#6874)

@CSurieux yes please do us all a favor and stop participating in this project.

---

**Comment by bleroy** [comment]
To be clear, the steering committee has no particular bug-closing privileges. It's just there to decide the general direction of the project, to take care of mostly administrative tasks related to the project, and to approve new committers, who are then trusted to close bugs, integrate PRs, etc.

See http://orchardproject.net/governance for more details on roles in Orchard.

**Comment by Skrypt** [comment]
I want to add that I, as everyone else, can be wrong sometimes. And I do appreciate people that can tell me when I'm wrong. I don't hold the absolute thruth and I believe no one does. This is why, I think that respecting each others is the most important thing if we want to achieve better things. We don't have all the same experience with Orchard. We all learn new things about it every day.

I deliberately closed my eyes on the lack of respect that happened here to make sure this was not aimed to only one person. I tried to be polite and answered even passed those "insults". The reasons are that beyond his arrogance @CSurieux has contributed on some issues and had good points on some. Also at some point I thought that we would come to reason with him over time. We don't want to question his integrity ; but we think that he reached point of no return where anything that we would write to him would never be enough.

I don't mind arguing with someone as long as it stays positive for the project.

Thanks
