### ISSUE TITLE
Cannot get any third party modules to work with 1.10.1

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#6883]
Orchard is completely trashed none of you use Orchard so its now a joke. Ha Ha

**Comment by Skrypt** [comment]
Hey Donald what's up over there ? Did you try installing a module from a fresh installation of Orchard from the source files ?

**Comment by sebastienros** [comment]
I assume most modules don't handle 4.5.2 or Nuget packages.

**Comment by Skrypt** [comment]
We can still get most of them from github, codeplex. Upgrade them, then install them.

**Comment by donaldboulton** [comment]
That's Right! If you upgrade the modules, I can upgrade almost all but the point is mostly simple web.config errors of not including needed references are breaking 3rd party modules, even the ones built recently. If the below was included most of my argument would be null.
References to
1. System.Data.DataSetExtensions
2. System.Web.Entity
3. JetBrains.Annotations, developers like Resharper
Even
4. System.Transactions
5. System.Runtime

You have lost what a CMS is, that this should be able to be used by anyone, not just developers.
All that have responded to this in all do respect have forgotten what is it like for the lesser skilled to have to try to decipher the simple mistakes.

**Comment by Skrypt** [comment]
But this is a "problem" that is inherent to the fact that we have version changes of framework from time to time. If we take Wordpress for instance. If PHP version changes, Wordpress changes and modules that don't follow the version change of PHP will have the same problems. At some point those module will still work and use deprecated function without even knowing it. The version changing as opposed to Wordpress is more strict into a compiled code world. Though this forces module contributors to see and to need to asses those evolution changes wich makes it better in some way.

I understand your point about the fact that this is not as easy as with Wordpress or Drupal but this is the tech that limits us somehow. I believe that this won't be problem going forward with the new dotnet core and Orchard 2. Patience is a virtue Donald ;)

**Comment by Skrypt** [comment]
I've been thinking about this. I have some ideas for the Orchard Gallery that could fix this.

**Comment by Skrypt** [comment]
What Drupal does for this is that they manage their own git server wich contains every modules from every contributors. Wich makes them having the right to harvest those repositories to create packages ready to download for each versions of Drupal. They use Tags for that purpose. Though they don't have to deal with .csproj framework configuration changes. On that matter, the Orchard Gallery could automate those tasks through git or github api or else ... we would need to elaborate on that matter.

**Comment by donaldboulton** [comment]
One thing that got me going was the Gallery links to Modules and Themes have all changed so Me, Orchard Developers and Others have to go through all there past Blog Posts, Twitter......where ever of postings discussions what ever on Orchard and try to fix all the dead links Referencing Orchard Modules or Themes.
I know that is alot of rewrite rules or Aliases to fix it but something has to be done.
Moff.Social old and new links.
[Moff.Social old link: as http://gallery.orchardproject.net/List/Modules/Orchard.Module.Moff.Social](http://gallery.orchardproject.net/List/Modules/Orchard.Module.Moff.Social)
[Moff.Social new link as: http://gallery.orchardproject.net/Packages/Orchard.Module.Moff.Social](http://gallery.orchardproject.net/Packages/Orchard.Module.Moff.Social)

Back to the topic.
As of today the References to `System.Data.DataSetExtensions` is now not removed nor added in web.config
@sebastienros sebastienros Fixing dynamic compilation issues  6 days ago
[951962f ](https://github.com/OrchardCMS/Orchard/commit/951962f6d9cc6f1c03f42dd9a8ba2d37e9d84c44)

Orchard 1.10.1 still has 58 Core Modules with References to `System.Data.DataSetExtensions` in dev, 1.10.1 and 1.10x
`C:\inetpub\wwwroot\Orchard1.10.1\Modules\TinyMce\TinyMce.csproj(58): `   `<Reference Include="System.Data.DataSetExtensions" />`

I removed 1.10.1 web.config reference of `<remove assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" /> `
I did not add it again like usual. I did not get any Orchard Messages as errors or log errors, so core Modules even with the dead references do not need = `<add assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />`
 The core modules seem to work even with the dead reference but most 3rd party modules need it added
`<add assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />`
