### ISSUE TITLE
1.10.1 Error in Layout editor

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/Orchard#6886]
In new version (1.10.1) when i add an element (Like HTML element) in content editor i get this Error!

![image](https://cloud.githubusercontent.com/assets/13555275/15197416/98789db6-17e6-11e6-8044-8ed44cdfe217.png)

**Comment by sebastienros** [comment]
Disable browser link which must be added by Visual Studio

**Comment by asemandeveloper** [comment]
How do I add it to Visual Studio؟

**Comment by sebastienros** [comment]
Does this work? http://stackoverflow.com/questions/23101265/disable-browser-link-which-toolbar

**Comment by asemandeveloper** [comment]
Thanks
