### ISSUE TITLE
Use Localizer in Layouts

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/Orchard#6895]
In LayoutEditor.Template.Toolbox.cshtml
who we can use T("") for {{item.toolboxLabel}}

![image](https://cloud.githubusercontent.com/assets/13555275/15266136/bf64e530-19b0-11e6-9ed9-14fdfb8542fc.png)

**Comment by sebastienros** [comment]
This has to be solved by this issue: https://github.com/OrchardCMS/Orchard/issues/6750
