### ISSUE TITLE
1.10.1 and Vandelay.Industries 

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#6896]
after realising that in 1.10.1 issue #6380 is in the 'fix list' I setup my test site BUT still get error:
"The assembly reference 'System.Data.DataSetExtensions' could not be loaded for module 'Vandelay.Industries'."

I then , on May 9, downloaded from github the 'dev' version. With this version I don't get the error anymore BUT:
the Vandely.industries features (enabled!) won't work¨!
e.g NO: Vandelay Content Admin Menu and NO: Remote RSS

(in #6359 -->) #6380; sebastien suggested 
The issue is that at some point the MarkdownSharp dll was replaced by the source code (a single file) as we were not using nuget
and the package was not updated and not in sync with the source code. The solution is to reference the Markdown module from Vandalay.Industries. At the same time we will fix 1.10.x to include this library from Nuget as we are now using it.

Question: what tweaks need to be done now to make Vandelay.Industries working ?

thanks for your time and help, ed

**Comment by sebastienros** [comment]
Please open the issue on their repository.
