### ISSUE TITLE
Using ICacheManager in razor

### ISSUE THREAD

**Issue by armanforghani** [OrchardCMS/Orchard#6898]
Is there any way to use ICacheManager in a razor template?

I write this code as i used for other interfaces:
```
@using Orchard.Caching

@{
    ICacheManager cacheManager;
    if (WorkContext.TryResolve(out cacheManager)) {
        ...
    }
}
```
but i get the following error:
```
None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Orchard.Caching.DefaultCacheManager' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.Type component' of constructor 'Void .ctor(System.Type, Orchard.Caching.ICacheHolder)'.
```

I want to connect to an API using HttpClient inside of a razor view because i don't want to write a custom module for this simple task.
I should use caching because i allowed to a certain number of requests.

**Comment by Ermesx** [comment]
Can you use caching in controller or driver to get necessary data from external resources? 
I think it could be better choice for you and also you should use `ICacheService` instead of `ICacheManager` for business data. 

There is also another solution which you can consider - OutputCache which cache your "views" and don't touch controllers to render result.

**Comment by sebastienros** [comment]
That should definitely work, even though @Ermesx is right.

**Comment by armanforghani** [comment]
@Ermesx As i mentioned above i don't want to create a custom module for this task. I am looking for a way to do that using Orchard.Templates, Workflows, ....
I want to cache API results because i have a limitation for number of queries in a day. As i know OutputCache can be invalidated by hitting F5 or somethings else. Also I'm not sure it would work for authenticated users.

@sebastienros, Unfortunately it doesn't work in my test. I will repeat my test ASAP.

**Comment by sebastienros** [comment]
Based on your scenario, you should use `ICacheService` from the `Orchard.Caching` module instead.

**Comment by Ermesx** [comment]
Sorry @armanforghani just now I realized what exactly you mean. You don't want create any module for this functionality. :)

The question is what dependency scope has view from Orchard.Templatest during rendering. Maybe there is no registered all dependencies or namespaces?
Look here: https://github.com/OrchardCMS/Orchard/blob/dev/src%2FOrchard.Web%2FModules%2FOrchard.Templates%2FServices%2FRazor%2FRazorCompiler.cs#L25

**Comment by sebastienros** [comment]
ICacheManager is used to store settings locally only, not serialized, with better possibilities of invalidation. In your case you just need time based invalidation, and have an issue with ICacheManager. So use ICacheService which can distribute data if necessary, is only time based, and works in a View.

**Comment by armanforghani** [comment]
@Ermesx You are right. Thank you very much for your detailed explanation.

@sebastienros Thank you so much for your clear and helpful explanation. I thought you mean ```ICacheManager``` from ```Orchard.OutputCache```. I tested ```ICacheManager```. It works well.
