### ISSUE TITLE
vs2015  new  theme

### ISSUE THREAD

**Issue by zhonggedan** [OrchardCMS/Orchard#6901]
Orchard.exe

codegen theme MeiyinTheme /IncludeInSolution:true

Set Current

error：
Oops. Something went wrong ... sorry
An unhandled exception has occurred and the request was terminated. Please refresh the page. If the error persists, go back
未将对象引用设置到对象的实例。
System.NullReferenceException: 未将对象引用设置到对象的实例。 在 Orchard.Themes.Services.ThemeService.EnableThemeFeatures(String themeName) 在 Orchard.Themes.Controllers.AdminController.Activate(String themeId) 在 lambda_method(Closure , ControllerBase , Object[] ) 在 System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) 在 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) 在 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) 在 System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) 在 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) 在 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() 在 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) 在 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() 在 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() 在 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() 在 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
http://www.iflve.com/1.png

**Comment by zhonggedan** [comment]
git clone 的代码跟直接下载下来的有区别，刚刚
codegen theme MeiyinTheme /CreateProject:true /IncludeInSolution:true /BasedOn:TheThemeMachine
失败
codegen theme MeiyinTheme /IncludeInSolution:true /CreateProject:true 
也失败
要么就是set current的时候出错，要么就是 参数超出有效值范围,我痛定思痛之后决定使用git clone  结果一切OK，这一点叫人费解.不过问题圆满解决！

**Comment by oldrev** [comment]
首先，楼上的大哥，你用中文发开发组没人能看懂好伐。

其次，要解决问题要详细说一下“直接下载的代码”的版本和 git clone 出来的工作分支名称，这样才能定位问题代码。

There is no Chinese speaker in the core developing team, please describe your question in English.

**Comment by sebastienros** [comment]
Closing this one in favor of https://github.com/OrchardCMS/Orchard/issues/6904 which is in English
