### ISSUE TITLE
Relative Urls in Content should be stored using a 'rooted' URL (~/)

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#6903]
If you insert an image from the Media Library using the TinyMce editor, an `<img>` tag with a relative URL is inserted, for example:

`<img src="/OrchardLocal/Media/Default/Images/img-1.png" />`

The problem with this is that this URL breaks when the content is deployed to a production server for example where no virtual directory is used (/ instead of /OrchardLocal).

To solve for this, we could transform all relative URLS into "rooted" URLS when saving the content. For example:

**/OrchardLocal/Media/Default/Images/img-1.png**

would be transformed into:

**~/Media/Default/Images/img-1.png**

When loading the content into the editor, the transformation is reversed:

**~/Media/Default/Images/img-1.png**

would be transformed into:

**/OrchardLocal/Media/Default/Images/img-1.png**

This is so that **TinyMce** is able to actually display the image, and essentially have this functionality be equivalent with how the **Media Library Picker** field works.

### Tenants

The transformation needs to take into account multi-tenancy as well.
For example, on a local developer's machine, the Default tenant may be used while creating content, but the content could be deployed to a _non-Default_ tenant, e.g. _Tenant1_.

To accommodate for this, the transformation logic needs to take into account the current tenant name. This means that not only do we need to store the URLs in a generic format, but we also need an `IHtmlFilter` implementation that replaces the URLs at runtime, taking the current tenant name into account.

The following example could be a good format to store URLs:

**~/Media/{tenant}/Images/img-1.png**

The `{tenant}` placeholder would be replaced with the current tenant name at run-time, and of course the URL would be mapped using `UrlHelper.Content`.

Or perhaps an even simpler format would be:

`<img src="medialibrary#123" />`

That is easier to parse, and even works when the filename of the selected media item changes.
A disadvantage of this is that we now actually need to load the media item to get its URL.

Or perhaps there is a better way?

**Comment by sebastienros** [comment]
duplicate https://github.com/OrchardCMS/Orchard/issues/6786
