### ISSUE TITLE
strange behavior  in textField of dynamic form 

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#6910]
![text-field](https://cloud.githubusercontent.com/assets/297675/15446437/fe3efda2-1eee-11e6-884b-fb2dfa7e4c2e.png)

you can visit 
http://noagent.properties/login
to see it.
it is lack of **type=text**
this only happen in anonymous user for http://noagent.properties/login
after i login as admin, or run in localhost , it has **type=text**

**Comment by infofromca** [comment]
![admin-tf](https://cloud.githubusercontent.com/assets/297675/15471361/8cd1ffd0-20c3-11e6-9566-414a680692e4.png)
the above is for admin
-----------------
![local-tf](https://cloud.githubusercontent.com/assets/297675/15471379/a346aab8-20c3-11e6-8940-7dbc7eb89290.png)
this is for anonymous user at localhost
---------------------
I checked the code which seems ok.
the only diff is that the host provide .net 4.6
or the bug in TagBuilder?

**Comment by sebastienros** [comment]
Does it repro out of the box? I can't see it currently on the site you are pointing to.

**Comment by infofromca** [comment]
after i redeploy it.
the type="text" came out, so close it
