### ISSUE TITLE
Users should be able to use an "administrator" rule on layers

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/Orchard#6912]
A user can make a rule for layer using the authenticated token, why not let users add a administrator rule. Really any of the standard permissions should be available. I would like to have a toolbar for administrators to use on the front of the site.

**Comment by sfmskywalker** [comment]
Or perhaps a 'hasrole(roleName)' rule function. Doesn't such function already exist?

**Comment by roballred** [comment]
It seems like standardizing the way it is done hasrole or authenticated would be a good idea to cut down on confusion.

**Comment by rtpHarry** [comment]
no the layer rules are a bit limited, I've been encountering these limitations recently as well. There is only authenticated, url and contenttype at the moment.

**Comment by thekaveman** [comment]
Maybe instead of introducing `hasrole`, this could be accomplished by extending the existing `authenticated` function, e.g.

The current behavior
```
authenticated
```

or check for an authenticated user in a role
```
authenticated('roleName')

**Comment by thekaveman** [comment]
I guess I'll play devil's advocate and throw something out that conflicts with my previous comment...

`IsInRoleActivity` from `Orchard.Roles.Workflows` has semantics for a user than is *not authenticated* if the `Anonymous` role is defined. Layer rules checking roles should probably work the same for consistency.

**Comment by sebastienros** [comment]
Let's create a new layer rule, `role`.

**Comment by Piedone** [comment]
There's a module for that: https://bitbucket.org/Lombiq/pcg.rolelayer It actually providees a `role` layer rule. We could simply incorporate the provider (https://bitbucket.org/Lombiq/pcg.rolelayer/src/a8145715b5e40af14505a696eca1ca6bf6a163fe/RoleRuleProvider.cs?fileviewer=file-view-default) into Orchard.

**Comment by sfmskywalker** [comment]
Turns out this already exists in the form of the `RoleConditionProvider` in Orchard.Roles.

**Comment by roballred** [comment]
@sfmskywalker so we can create rules for layers based on this? what would a rule look like?

**Comment by sfmskywalker** [comment]
Totally. Example:

```
role( "Contributor", "Editor" )
```
