### ISSUE TITLE
Orchard.Layouts - Extend snippet manifest format with category & description

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#6913]
While finishing off implementing the snippet manifest parsing in #6872 I noticed a few other improvements that could be made.

1. Move the default / fallback snippet `ToolboxIcon` value into the `Snippet` class and pull it from there.

1. Add a `Category` field to the yaml manifest to allow the snippets to blend in to whatever category the author chooses.

1. Add a `Description` field to the yaml manifest to customize the existing hard coded description `String.Format("An element that renders the {0} shape.", shapeType)`

As they will extend the manifest further I thought I would get approval before I start. Also, which branch should I target?

**Comment by sfmskywalker** [comment]
I like it, please continue and target the dev branch.

**Comment by rtpHarry** [comment]
While I was working on it I noticed a bug in your code. Just giving you a heads up in case you use that library again in the future:

    var fieldsConfig = snippetConfig.Fields != null ? snippetConfig.Fields.Children : new dynamic[0];

This snuck through because the manifest always had `Fields` in (that's all it was being used for before) but its never null, it return `DynamicYaml` regardless. Instead I updated it to this:

    if(snippetManifest == null || snippetManifest.Fields.Count == 0) {
        return null;
    }

    var fieldsConfig = snippetManifest.Fields.Children;

**Comment by sfmskywalker** [comment]
Great catch, thanks
