### ISSUE TITLE
Superscripts and subscripts styling in Theme Machine

### ISSUE THREAD

**Issue by I3undy** [OrchardCMS/Orchard#6920]
Superscripts and subscripts rule-sets are missing from the Theme Machine's [Site.css](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Themes/TheThemeMachine/Styles/Site.css) 

There is a reset for those: 

```
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, font, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td {
    margin: 0;
    padding: 0;
    border: 0;
    outline: 0;
    font-weight: inherit;
    font-style: inherit;
    font-size: 100%;
    font-family: inherit;
    vertical-align: baseline;
}
```

After that the only formatting for those is this line: 
`sup, sub    { line-height: 0; }`

**Comment by sebastienros** [comment]
Sorry, I don't understand what the actual issue is, are we missing some css rule? How does it impact the themes right now?

**Comment by Piedone** [comment]
The issue is that text in `<sub>` and `<sup>` tags actually look like normal text.
