### ISSUE TITLE
Executing recipes shows success even recipe fails

### ISSUE THREAD

**Issue by kappas** [OrchardCMS/Orchard#6924]
Navigate to Admin UI/Modules/Recipes and click "execute" link

If recipe has any errors, there are no error messages showing. However logs show that it failed eg. some invalid step

If same recipe is run via Import, error message is showing.

Seems that when refactoring for recipe execution was made, execute recipe was not modified.

**Comment by rtpHarry** [comment]
Is this the same issue as #4207?

**Comment by kappas** [comment]
I think so
