### ISSUE TITLE
How prevent double entry of record in dynamic forms

### ISSUE THREAD

**Issue by Xtremrules** [OrchardCMS/Orchard#6927]
I will love to know how to use dynamic from in Orchard  to prevent double entry of record like submiting of more than  one phone number  per different users and generating a unique number for their from.
I have been having difficulty in activating code generation and hence creating modules in Orchard 1.10

**Comment by sfmskywalker** [comment]
Hi, Kindly ask questions on the forum. We use the issue tracker for bugs and feature suggestions. Thank you
