### ISSUE TITLE
Make MembershipService.ValidatePassword public

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#6930]
I have a requirement where the user is able to reset their password, but they are not allowed to use the last 3 passwords they used before.

To accomplish this, I am storing the hashed password, password salt and hash algorithm as a record in a table. When the user tries to change their password, I take the last 3 records and use the password salt and algorithm to compute the hashed password, which I compare to the stored hashed password of each record.

I could do this by duplicating the `ValidatePassword` method that lives in `MembershipService`, but if we made that method public, I could simply create an in-memory `UserPart` "spie" object and update its Password, PasswordSalt, etc. and pass that into the `ValidatePassword` method on each iteration, e.g.:

```C#
public bool IsUsedPassword(string userName, string password, int retention) {
    var changedPasswords = _passwordChangedRepository.Table.Where(x => x.ForUserName == userName).OrderByDescending(x => x.ChangedOn).Take(retention).ToList();
    var spie = _contentManager.New<UserPart>("User");
            
    return changedPasswords.Any(changedPassword =>
    {
        spie.Password = changedPassword.Password;
        spie.HashAlgorithm = changedPassword.HashAlgorithm;
        spie.PasswordFormat = changedPassword.PasswordFormat;
        spie.PasswordSalt = changedPassword.PasswordSalt;

        return _membershipService.ValidatePassword(spie, password);
    });
}
```

Making the method public and updating the `IMembershipService` interface will be a breaking change of course, but perhaps enabling this scenario is worth it? If so, then we could consider refactoring the `ValidatePassword` to accept individual parameters instead of a `UserPart` so I don't need to new up the "spie" UserPart.

**Comment by sebastienros** [comment]
Ok, so if I really want to use the same "last" password, I can just change it 3 times in a row then use it again ;)

**Comment by sfmskywalker** [comment]
Yep :) Not my requirement. Perhaps better would be to use a time span instead of a change count. But regardless of the business rule, my suggested change will enable it, right?

**Comment by sebastienros** [comment]
Why not an event instead of changing the interface?

**Comment by sfmskywalker** [comment]
I'm not sure I understand. How would an event enable me to access the `ValidatePassword` functionality?

**Comment by sebastienros** [comment]
New interface or existing one with an event handler, that this method calls to let other components validate the password.

**Comment by sfmskywalker** [comment]
Well yes, however it doesn't help to know when a password is being validated for a given user name; I need to be able to hash the new password with the salt, format and algorithm used for the previous password. How else can you tell if a given password was used previously?

Even if we have this event handler, it would only be triggered when calling `ValidateUser (userNameOrEmail, password)``

The event handler would then provide all the information I need to record, for sure (but I can already do that without the event handler). But when a new password is set, I don't want it to use a random salt; instead, I want to reuse the salt of the previously set passwords. Hence, I need to be able to access `ValidatePassword`.

Unless I totally missed your point.

**Comment by sebastienros** [comment]
You just need the hash of previous passwords, and create your own salt every time.

**Comment by sfmskywalker** [comment]
I see. So as a user sets a password, I hash it myself using my own salt and store it in the history. When a user changes their password, I know how to hash and salt it again to match against any existing ones. It's perfect.

So what I'll do is as you suggested: introduce an event handler interface and not change `IMembershipService`.

Thanks!

**Comment by marknoble** [comment]
I saw this topic come up in the Orchard Meeting and posted this in the chat.  Good to read regarding recommended best practices on passwords: http://research.microsoft.com/pubs/265143/Microsoft_Password_Guidance.pdf
