### ISSUE TITLE
MSBuild should be called with the "/m" switch

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#6936]
It allows running independent project builds in parallel by using more than one cores, thus speeding up the build if you have many projects in your solution (since we're talking about Orchard, it's always over 80).
We're building our solutions in TeamCity with "/m" added (and also locally, when testing the Web package build) and there's no drawback I'm aware of (and haven't found any possible problems on the interwebz), but the speedup is quite significant (20-50% depending on the number of cores/hyperthreads).

EDIT: As suggested by Sébastien, it should be added in `deploy.cmd` as well, not just `ClickToBuild.cmd`.

**Comment by sebastienros** [comment]
Please check the `deploy.cmd` file too

**Comment by BenedekFarkas** [comment]
I just realized that I was talking about `build.cmd` on the meeting today, but you're right, `deploy.cmd` also uses `MSBuild`, so we'll add it there as well.
