### ISSUE TITLE
CdnSupportsSsl + Use CDN doesn't affect protocol relative URLs

### ISSUE THREAD

**Issue by thekaveman** [OrchardCMS/Orchard#6941]
This is somewhat of a follow on to #6831 (and likewise targets `dev`)

We have, for example in [`Orchard.Resources/Bootstrap`](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Resources/Bootstrap.cs#L7) (changed spacing for readability here):

``` csharp
manifest
    .DefineStyle("Bootstrap")
    .SetUrl("bootstrap.min.css", "bootstrap.css")
    .SetVersion("3.3.5")
    .SetCdn(
        "//ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css",
        "//ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.css",
        true
    );
```

`cdnSupportsSsl` is given `true`, while the URLs are protocol relative (`//domain.com`).

When the **Use CDN** setting is checked, these resources will be served under the protocol relative URL, even though they are available under `https`. As @anoordende mentioned in the linked issue, and pretty widely accepted best-practice:

> If the CDN does support SSL, it is greatly encouraged to serve resources from the CDN under SSL, even if the [Orchard] site is not [served under SSL].

The quick fix is to make all the CDN URLs `https` for CDNs that support it.

A possibly better fix is to always use `https` whenever `cdnSupoprtsSsl` is `true`, regardless of the given URLs.

**Comment by sebastienros** [comment]
Where is the PR?

I assume anywhere we have `//` urls they should be converted explicitly to `https` ?

/cc @bleroy you confirm ?

**Comment by thekaveman** [comment]
I wasn't sure if you wanted the quick fix, or the possibly better fix?

**Comment by thekaveman** [comment]
Submitted a PR, my attempt at the possibly better fix. I targeted `dev` since the work by @anoordende was also merged into `dev` (but not yet `1.10.x`)

**Comment by sebastienros** [comment]
I am not really a fan of trying to alter the url provided by devs, I'd rather educate in using `https` directly in the manifest instead of `//`

**Comment by BenedekFarkas** [comment]
@sebastienros I agree with the changes in this PR. If understand correctly, the only implication of this change is that a resource URL that starts with "//" and CdnSupportsSsl = true will together enforce SSL for the resource. If you think the code and concept of the change is OK, then I'll test it + verify unit tests.

**Comment by sebastienros** [comment]
I think we should just follow what @anoordende suggested, to remove this option completely as the url itself is sufficient.
