### ISSUE TITLE
in my module, tinymce insert media not pop up

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/Orchard#6954]
n my orchard module,tinymce insert/Update Media not working.

I am using Orchard 1.10, and in my new module , my new type with a bodypart, in the tinymce, the insert Media not pop up. but i use "OrchardLocal/Admin/Contents/edit/12" the insert media button work fine, why? thank you

**Comment by ViRuSTriNiTy** [comment]
Bring up your browser developer console with F12 and look at the console tab. Do you see any errors?

**Comment by gorelshv** [comment]
I know this topic is closed but I'm facing a similar problem.
i have multible text areas with classes "html tinymce". Initializing them works fine and everything works except the Insert Media button. No errors in console, nothing.
EDIT: the button is there it's just that nothing happens.

Thanks.
