### ISSUE TITLE
Queries returning Draft Content Items and with more tokens availables for filters

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard#6960]
I'm executing queries from tokens with a Query token context (Query.List:<nameOfTheQuery> or Query.Count:<nomeOfTheQuery>) and from Activities in workflows that throw a signal per content item returned by a query.
Problem is I cannot use other tokens but Request ones from the query filters.
It would be interesting to a have the possibility of offer context tokens available in token and activity execution to make queries more flexible.
Furthermore in workflows it is interesting to have access to draft content items through queries. So it would be interest to have the opportunity of ask to projection manager to return draft content items.

**Comment by BenedekFarkas** [comment]
Implemented in #7923 and #8112.
