### ISSUE TITLE
Placement's path condition don't strips UrlPrefix (MultiTenancy)

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/Orchard#6962]
## Repro steps :
- Enable multitenancy and create a tenant with an UrlPrefix
- Apply a placement rule with a path condition on tenant's theme

```
<Placement>
  <Match Path="/">
    <Place Parts_Title="-"/>
  </Match>
</Placement>
```

=> TitlePart is displayed

```
<Placement>
  <Match Path="/my-tenant">
    <Place Parts_Title="-"/>
  </Match>
</Placement>
```

=> TitlePart is **not** displayed

**Comment by Piedone** [comment]
What happens if you use "~/"?

**Comment by TFleury** [comment]
Tilde don't change anything.

**Comment by HermesSbicego-Laser** [comment]
Any updates on this?
A side effect is that the feature "Orchard.Users.PasswordEditor" does not work if the tenant has a prefix.

**Comment by sebastienros** [comment]
I assume Path should not take the tenant into account. It should just be the url after the tenant prefix. And we could add a `Tenant` filter with the tenant name. Or have custom placement files per tenant.

**Comment by HermesSbicego-Laser** [comment]
Not sure to understand:

> I assume Path should not take the tenant into account

does it mean that the GetPath() should strip the tenant prefix?
ref: `Orchard\src\Orchard\ContentManagement\DefaultContentDisplay.cs - line 161`

the above private method is used also at line 108 in the `UpdateEditor` method
`var context = new UpdateEditorContext(itemShape, content, updater, groupInfoId, _shapeFactory, shapeTable, GetPath());`

I don't know if the change affects some other functionality, but the change would be easy...

> And we could add a Tenant filter with the tenant name. Or have custom placement files per tenant.

Is not that overkill for this issue? 
I mean,  I like your two ideas, but they can be developed later... Or perhaps I misunderstood the suggestion....

**Comment by sebastienros** [comment]
What about detecting ~/ then. If not used it would mean the absolute path of the request (applies to a single tenant), and if set it would mean the path without the tenant prefix (applies to all tenants).

I assume that wouldn't be breaking then.
