### ISSUE TITLE
Projection does not handle nullable DateTimeFields correctly

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [OrchardCMS/Orchard#6967]
Currently when no value is selected for a DateTimeField then `GetFilterPredicate()` determines `min` and `max` incorrectly as it expects a string formatted as `yyyy-MM-dd HH:mm:ss`.

The following change is needed to pass `min` and `max` as empty string (to avoid exception in `IHQLCriterion.FormatValue()`) or `0` when `asTicks` is `true`:

**Comment by sebastienros** [comment]
Can you provide some repro steps? I am not convinced of how it should impact the construction of the query with the Or and Ands. The rest of your code is fine.

**Comment by ViRuSTriNiTy** [comment]
This issue is basically a forerunner of issue #6979, the PR has been accepted already, so i close this as it's not relevant anymore. Btw: the Ors and Ands are there to leave existing code untouched, it just adds a new code path for handling the `value is null` case.
