### ISSUE TITLE
HqlRestrictions class converts to unsafe SQL DateTime format

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [OrchardCMS/Orchard#6973]
I have a `ValidityPart` with a property `ValidFromUtc` of type `System.DateTime?`. The related column in the DB (SQL Server 2008 R2, german settings) is created as `DATETIME`. I also have a projection witch results in a query that looks like this

    ...where validitypa2_.ValidFromUtc <= '2016-06-10 10:31:59' and ...

The issue here is that `2016-06-10 10:31:59` is a `ANSI SQL` format which is **not** language neutral. In my case the server expects `10.06.2016 10:31:59` and therefore the where condition does not work.

There are 2 options now. Either the DB column is changed to `DATETIME2` (language neutral) or `HqlRestrictions`  is changed so that it returns the `ISO 8601` format, in this case `2016-06-10T10:31:59`.

I did test both options and it works but i prefer not to change all my DB column types.

Should i submit a patch?

Reference (in german, didn't find any other reference): http://www.insidesql.org/blogs/frankkalis/2010/08/19/der-ultimative-guide-fuer-die-datetime-datentypen

**Comment by Piedone** [comment]
I'd go with the option that doesn't require DB column changes. Yes, please submit a PR, that would be awesome!
