### ISSUE TITLE
Allow extending content queries

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [OrchardCMS/Orchard#6978]
I want to extend the content queries executed by `DefaultContentManager` and `DefaultContentQuery` with a left join of my ValidityPart to return only "valid" content items.

In case of  `DefaultContentManager` i can inherit from it and override `Get(int aId, Orchard.ContentManagement.VersionOptions aOptions, Orchard.ContentManagement.QueryHints aHints)`, this works without a hassle.

But in the case of `DefaultContentQuery` i cannot inherit from it because the methods of interest `Slice()` and `Count()` are private as almost everything in this class. Last resort would be to implement IContentQuery myself but this is overkill and results in basically copying `DefaultContentQuery.cs`.

Therefore i added a protected `BeforeExecuteQuery`in `DefaultContentQuery.cs` to be able to extend the query before it is executed:

```
namespace Orchard.ContentManagement {
    public class DefaultContentQuery : IContentQuery {
        ...

        protected virtual void BeforeExecuteQuery(ICriteria contentItemVersionCriteria) {
        }

        private IEnumerable<ContentItem> Slice(int skip, int count) {
            ...

            BeforeExecuteQuery(criteria);

            return criteria....;
        }

        int Count() {
            ...

            BeforeExecuteQuery(criteria);

            return criteria...;
        }
    }
}
```

My `ContentQuery` class looks like this:

```
[Orchard.Environment.Extensions.OrchardSuppressDependency("Orchard.ContentManagement.DefaultContentQuery")]
public class ContentQuery : Orchard.ContentManagement.DefaultContentQuery
{ 
    protected override void BeforeExecuteQuery(NHibernate.ICriteria aContentItemVersionCriteria)
    {
        base.BeforeExecuteQuery(aContentItemVersionCriteria);

        // here comes my code to extend the query by adding additional criteria to aContentItemVersionCriteria
        }
    }
}
```

Do you consider this a valid approach and is it possible to include this change in a future Orchard release?

I also thought about using a handler pattern here as it is done almost everywhere in Orchard but this would required the need to resolve all available handlers each time a query is executed which might affect performance negatively.

**Comment by HermesSbicego-Laser** [comment]
Same needs here, @sebastienros  could you suggest a good approach and from where to begin?

**Comment by Xceno** [comment]
We needed the same last year, but I've ended up writing pure HQL for such scenarios which works for us. Imho, the least invasive change would be to make more methods `protected` or `public`, so at least we don't have to copy/paste whole classes when we want to surpress them.

We had a similar discussion about extending the ContentManager with [additional hooks here](https://github.com/OrchardCMS/Orchard/issues/5039) and this issue sounds the same.
Maybe we can work on a solution together?

**Comment by MatteoPiovanelli** [comment]
My favourite way would be to have the ability to inject behviour without suppressing or overriding stuff. Like a provider that lets me say "Everytime you are creating a ContentQuery, apply this `Where`". As @ViRuSTriNiTy mentioned, this pattern would likely have a negative effect on performances.

I'll have to dig into the code for this to think a feasible scenario.

**Comment by sebastienros** [comment]
I didn't expect this requirement at all. But as long as it doesn't hurt perf to add the extensibility then I don't see any issue. It's however very limiting as not all modules use the CM to get the data, so adding security at this level is very risky. You'd better add a Permission Handler that would filter the data to render instead.

Options:
- Make methods protected for easier customization
- Add even handler in some services to alter the query

**Comment by ViRuSTriNiTy** [comment]
@sebastienros The sole purpose of extending content queries (at least for me) is to add certain functionality to the basic content item handling in Orchard. I had the requirement to add validity to some content items to skip displaying content items based on timestamps, no security involved, see http://stackoverflow.com/a/38369053/3936440.

I also vote for the event handler pattern as this would allow to extend the queries in different modules based on the assumption that suppressing existing implementations with `OrchardSuppressDependency` won't work in connection with different modules.

**Comment by ViRuSTriNiTy** [comment]
@Xceno i don't think the [content manager hook issue](https://github.com/OrchardCMS/Orchard/issues/5039) is related to this issue as the content query doesn't provide any hooks yet.

**Comment by MatteoPiovanelli** [comment]
I agree with @ViRuSTriNiTy :
I strongly dislike suppressing dependencies. Extensibility points possible by dependecy injection are great, and I especially like the pattern used for handlers alowing to compose behaviours.

@sebastienros filtering post-queries (post-everything, really) does not look like the best option, in general. I fell like you may end up with having found N items, and only having to show M<N, messing things up if slicing and paging has happened already.
Now, if we are talking about extending things so that the filtering criteria can be inserted as things happen, that is different.

**Comment by GiuseppeMusso-Laser** [comment]
I posted a possible solution (PR #7711) without suppressing dependencies.

**Comment by sebastienros** [comment]
How to you decide which query you want to change dynamically?

**Comment by GiuseppeMusso-Laser** [comment]
Here is how I figure it out.
When I create a class implementing IGlobalCriteriaProvider, I can write method AddCriteria(ICriteria) to add joins and where conditions (Restrictions) to every query performed through DefaultContentQuery.

I meant interface IGlobalCriteriaProvider to add extra conditions to all queries according to, for instance:
- site settings
- current date
- current user
- back-end or front-end request (check on AdminFilter)

In my case I perform some validity check on one of my custom parts.
I add an outer join to my custom part record and a where condition on a particular field value.

If you want to change only some individual query I suppose you can call some method on parameter "criteria" (e.g. GetRootEntityTypeIfAvailable(), GetCriteriaByPath(string)) and perform some checks.

However this wasn't my main purpose.
