### ISSUE TITLE
Projection should support NULL and IS NOT NULL filters for DateTime? columns

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [OrchardCMS/Orchard#6979]
Currently there is no way to generate a `MyField IS NULL` or `MyField IS NOT NULL` query condition in Orchard.Projections.

Filter editor should be extended to allow a selection of `not null` and `is not null`.

**Comment by sfmskywalker** [comment]
Could you maybe provide a use case scenario where you want to use this condition?

**Comment by ViRuSTriNiTy** [comment]
@sfmskywalker I created a ValidityPart which provides 2 properties: `ValidFrom` and `ValidTill`. Both properties are declared as `System.DateTime?` to make these 2 values `optional` (related issue #6966). Due to the fact that these properties are optional and i want to have a list of *valid* content items i created a projection query with the following conditions:

> `ValidFrom` LessThanEquals Token `Date.Local.Format:<formatString>` (related token issue #6963) 
> and 
> `ValidTill` GreaterThanEquals Token `Date.Local.Format:<formatString>`
> 
> or
> 
> `ValidFrom` LessThanEquals Token `Date.Local.Format:<formatString>` 
> and 
> `ValidTill` IsNull
> 
> or
> 
> `ValidFrom` IsNull 
> and 
> `ValidTill` GreaterThanEquals Token `Date.Local.Format:<formatString>
> 
> or
> 
> `ValidFrom` IsNull 
> and 
> `ValidTill` IsNull

Hope this helps.

**Comment by Xceno** [comment]
I second this. It would be very useful for me too.

My scenario is a list of Events where you don't need to specify a fixed date.
Nonetheless I want to create a projection for certain events with a valid date in the future.

Does the PR linked above resolve the issue? If so, can you merge it into the 1.10.x branch?

**Comment by ViRuSTriNiTy** [comment]
@Xeno Yes, i think the PR solves your valid date issue.

**Comment by ViRuSTriNiTy** [comment]
PR accepted, issue closed.
