### ISSUE TITLE
Feature: Dynamically Media-process images with fixed size in HTML

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/Orchard#6986]
Images inserted in HTML through, e.g. any content with a Body can be resized through the editor. However, the full size image will still be served whereas it would be more efficient, especially on mobile clients, to serve a pre-sized image.

It is quite straightforward to dynamically cut these images to size using the MediaProcessing module in combination with IHtmlFilter. Of course, it needs to be a feature that can be turned on or off as desired.

The one requirement is that the height/width attributes are provided, which will be when resizing through the TinyMce editor. This also provides an excellent trick when you particularly don't want an image to be resized: omit the height or width.

As I've had this code live for a few years already, the PR is to follow shortly.

**Comment by Skrypt** [comment]
I agree that this need to be a feature that you can enable/disable mostly because now responsive design uses images that have width="100%" that stretch twith the window size. If we keep the full sized image for keeping image quality on wider screen it makes less files to manage and sometimes as much efficient size wise.

**Comment by anoordende** [comment]
You can still use 100% width and use this feature. Just set the height/width atts to the maximum size you'll need for any viewport, but upload just the full-res.

As mentioned, this is targeting IHTMLFilter implementors. If you are using or thinking about e.g. sliders then these are better implemented with fixed Image profiles.

A common usage scenario is:

- user uploads > 3000px 5Mb original
- inserts it into a body part
- drags handles to resize it to 120px

This is where this feature kicks in and creates a dynamic 120px profile.
________________________________

**Comment by Skrypt** [comment]
Yeah, but if your image is 120px and you need to display it in 100% width on a QHD screen you will only see big pixels :smile:

I understand your request and I think this is a good idea, though it needs to be a feature that works with any Wysiwyg editor out there. So, it must be post-processed if enabled. The only thing I'm worried about is the scope; per image, per editor, per body part, per ...

**Comment by anoordende** [comment]
Simple: Don't resize to 120px in the editor and you'll get the original size.

It will work with any editor, TinyMce included, because it doesn't operate at that level, it uses IHTMLFilter.

Important to note it also does not apply to images already the result of a profile.

Anyway, all good input. I'll submit the code shortly and you can check it out.
________________________________

**Comment by anoordende** [comment]
PR created: #6992

**Comment by sfmskywalker** [comment]
This seems like a useful feature, but I'm not sure it should be part of the core distribution, so I would like to ask other people's opinion on this as well. /cc @sebastienros @bleroy @pszmyd @DanielStolt @Jetski5822

We also discussed enhancing the media library picker to allow providing additional information, for example selecting one or more profiles associated with view port sizes to render multiple sources.

**Comment by sfmskywalker** [comment]
Maybe add support for `<picture>` element.

**Comment by jonvee** [comment]
+1 for picture and img srcset

**Comment by DanielStolt** [comment]
@sfmskywalker I recall we had a discussion about using in `IHtmlFilter` to stop embedding absolute media URLs in HTML/markdown content, and instead embed an encoded reference to a media item by ID, and have the filter resolve this reference relative to wherever the media library storage happens to reside for the current tenant. I vaguely remembered you opened an issue for this, but I can't seem to locate it.

It occurs to me that this request could be combined with that one, to solve both problems at once. If we stop embedding pre-resolved media URLs in content and instead embed media item references, those could also contain size/profile information, and we could use all existing logic in the media library picker field to process.

**Comment by anoordende** [comment]
Good point, I have always argued that the media URL should be embedded relative to /Media as a level of indirection. Though that has it's issues and your idea of using an encoded ID will work around those. In fact, where needed we use a custom implementation of the media module that does exactly that (but relative to /Media). MediaProcessing should also make the _profile URL's host-agnostic: an issue and PR I thought I had raised... but cannot find. Anyway, as long as it eliminates the need for:

```
UPDATE [prefix_Orchard_Framework_ContentItemVersionRecord]
SET [Data] = REPLACE([Data], 'src=&quot;/Media/TenantName/', 'src=&quot;https://my.blob.core.windows.net/media/TenantName/')
WHERE [Data] LIKE '%src=&quot;/Media/TenantName%'
```

And allows for domain moves with wildcard 301's to images and image profiles, together with the dynamic resizing, I think that that would complete the Use Case?

**Comment by DanielStolt** [comment]
a) Exactly - we do exactly that, but in the recipe during the deployment process.
b) I think it might be best to leave redirects out of scope.
c) Yes, this would be inherently supported just like for media library picker fields. The media storage implementation can support such configuration, like the Azure Blob Storage implementation does.
d) I think perhaps this too should be up to the media storage implementation, e.g. perhaps you want media requested via HTTPS from blob storage or from your CDN even if your site runs on HTTP. The media storage implementation can always choose to emit a scheme-relative URL (starting with double slash) to have the media requested using the same scheme as the current Orchard request. This should be the default behavior of the built-in implementation.
e) Yep.

Fair point about separating the responsibilities. On the other hand, MediaLibrary already depends on MediaProcessing and knows about it, so perhaps it's OK that MediaLibrary has the knowledge of how to embed a processing profile in the media reference and resolve this to a URL that invokes MediaProcessing to execute it?

**Comment by sebastienros** [comment]
Is the current PR the final answer or do we want to wait for more features like the ones discussed here?
As it's an optional feature I am not too worried by the perf impact, though there is some.

**Comment by anoordende** [comment]
I would like to include `picture` and `img srcset` first, then that will be a rounded PR.
