### ISSUE TITLE
Admin, Content list, bulk labels should not be displayed as lowercase and have consistent CSS classes

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [OrchardCMS/Orchard#6987]
Some labels displayed in the `/Admin/Contents/List` view use the `bulk-...` CSS class. These classes have `text-transform: lowercase` applied and therefore any capitalization defined in the related `.po` file does not work.

For example: view calls `T("Culture")` -> renders `Culture` -> browser displays `culture`

This might not be an issue in the english language but for instance in german language the word needs to be `Kultur` not `kultur`.

So i suggest to remove the text-transform rule.

Also, to be consistent the `Filter by` label should be rendered with CSS class `bulk-filter` instead of `bulk-order` (this might be a copy pasta error from the one that was working on the view).

**Comment by sfmskywalker** [comment]
Could you please elaborate on the "Kultur" vs "kultur" issue? For example, do the two words have a completely different meaning?

Regarding the second issue, we will fix that as part of the new admin theme.

**Comment by ViRuSTriNiTy** [comment]
@sfmskywalker It's an orthography issue. In german, the word `culture` is written as `Kultur` (which is a noun, nouns are written with a beginning uppercase character), not `kultur`(which would be a verb or adjective, both are written with a beginning lowercase character, also in this case the word doesn't exist).
