### ISSUE TITLE
Some features need to be upgraded: Orchard.Framework, Settings

### ISSUE THREAD

**Issue by leomarbucud** [OrchardCMS/Orchard#6995]
Hi, after updating Orchard 1.9.2 to 1.10.1, I'm having a hard time fixing this warning on admin page **Some features need to be upgraded: Orchard.Framework, Settings**. But when updating the **Settings** it brings error _Transaction not connected, or was disconnected_ . Is there anyone here encounter the error and warning?

**Comment by ViRuSTriNiTy** [comment]
Try to have a look at the logs (src\Orchard.Web\App_Data\Logs). What's in there?

**Comment by sfmskywalker** [comment]
Please have a look at the error logs as per ViRuSTriNiTy suggestion.

**Comment by leomarbucud** [comment]
I've found what causing the error. There is a duplicate entry on this table **Settings_ShellFeatureStateRecord** Orchard.Packaging and Orchard.packaging. I deleted Orchard.packaging (small letter) and successfully updated the settings.

But still I can't enable/disable Package Module properly. Sometimes it adds **Orchard.packaging** and sometimes **Orchard.Packaging**
