### ISSUE TITLE
Orchard admin : menu settings dropdown too long

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/Orchard#7010]
related to https://github.com/sfmskywalker/Orchard/issues/24

**Comment by Skrypt** [comment]
I suggest that we move some of those modules settings to the Modules --> Features list view.
We could add a gear icon on each feature that has settings.

**Comment by sfmskywalker** [comment]
I'm afraid that will make the settings less discoverable and too scattered. Instead I would just add the Settings menu back to the left hand menu. Also, we would have to implement a way to know what features provide what settings.

**Comment by Skrypt** [comment]
I agree that for now we should just put back the settings to the left hand menu. How about just a simple item menu "Settings" that would point to a settings list view page ?

**Comment by sfmskywalker** [comment]
You mean add just a single, simple menu item "Settings" to the left hand menu, without a sub menu? If so, I don't understand why, unless it causes the same issue as when the top level menu item expands with too many sub items?

**Comment by Skrypt** [comment]
I meant. A single menu item "Settings" to the top menu, without a sub menu. Then we do a listview of those setting pages. Of course if we absolutely want this menu items on top menu.

Though, to me it makes more sense to have a single menu item. The reason is that the number of sub-menu items in that list gets relativly long if we activate every Core modules. Then if someone has it's own custom modules with settings that might make it a long list of sub-menu items. Would'nt that make sense to have those settings in a list view page instead of adding menu items ? I'm seeing maybe bad UI design here in the use case of someone who would have 20 and more setting pages that would add to those sub-menu items.
