### ISSUE TITLE
Orchard admin : expandoControl is not a function error

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/Orchard#7013]
related to https://github.com/sfmskywalker/Orchard/issues/44 and
https://github.com/sfmskywalker/Orchard/issues/14

**Comment by Skrypt** [comment]
This bug also happens now when trying to create a page. Something has changed on the mechanism for the expando stuff when we changed the Content Type edit screen thinking we should leverage features from the amaretti theme as much as possible. We then need to make sure to apply the same changes everywhere.

**Comment by Skrypt** [comment]
Happens only when we activate the Audit Trail module in the Page create view.

**Comment by Skrypt** [comment]
I can reproduce this bug by adding an audit trail part to a content type. Need to test if it's just with the new admin theme or if it's there also in the dev branch.

**Comment by sfmskywalker** [comment]
Fixed in 9d41692ca3bfe9a0dcfa9323ce92bf7371c34e98
