### ISSUE TITLE
mce double toolbar

### ISSUE THREAD

**Issue by qt1** [OrchardCMS/Orchard#7022]
![mce-double-toolbar](https://cloud.githubusercontent.com/assets/7355327/16568324/8524db56-4231-11e6-868a-88ed36b985c0.jpg)

Recreating:
1. Define a new type - myType
2. Add Body part
3. Add a text field with Html flavor & save
4. Add new item
The mce editor displays two toolbars.

As far as I can tell this problem is new - all is OK in 1.10

**Comment by thekaveman** [comment]
I can confirm this is happening in latest `1.10.x`. Additionally, it looks like the toolbar is not only duplicated on the first editor, but it is actually *removed* from the second editor:

![image](https://cloud.githubusercontent.com/assets/1783439/16633924/6285b7f0-4380-11e6-8430-6350c6db6ecb.png)

**Comment by Piedone** [comment]
This is most possibly something we've done in a recent changeset for implementing the sticky toolbar, will investigate.
