### ISSUE TITLE
Creating a new default tenant with an SQL db and a table prefix entered fails with a Setup failed warning message

### ISSUE THREAD

**Issue by Hazzamanic** [OrchardCMS/Orchard#7031]
Full warning message: Setup failed: Transaction not connected, or was disconnected

I don't have time to dig into this right now, and it is hardly a priority, but if it is a restriction from Orchard that the default tenant should not have a prefix then a better error message should be displayed.

**Comment by Piedone** [comment]
Are you sure this is not an issue with your SQL server instance? Can you otherwise connect to it?

**Comment by tktredstar** [comment]
I have the exact same issue... My SQL Server instance (MSSQL 2014) seems to be running just fine. (I have no problems logging in with the created user) Any solutions?

**Comment by Piedone** [comment]
Can you share all the exception details, including stack trace? What is the timeout value for the connection?

**Comment by tktredstar** [comment]
Hi, 
after trying to install a new instance, everything goes well. 
As I remember correctly the error I got had something to do with a zombieing Nhibernate session towards my SQL Express 2014.
Bu no issues left for the moment

**Comment by chris904apps** [comment]
I think this is the same problem i'm having. I'm trying to setup orchard to use Sql Server.
Background:
I originally set up a site to use Sql Compact but i found that the site is too slow after deploying to my godaddy account. I covered the database but i didn't know how to set up Orchard to use Sql Server vs compact, so i tried created a new orchard site using Sql Server so i could  compare and make updates to my site.
Problem:
So when i entered in all the info for setting up the site and orchard went to cook up site, I received an error (I dont have it anymore). Then I downloaded the source to see if it was something i could trouble shoot. That's when i got the following error:
orchard session.transaction nhibernate.transactionexception -> message "transaction not connected, or was disconnected"  
This was in SessionLocator.cs -> DisposeSession() ; line 96 ..._session.Transaction.Commit();
I am using Sql Server 2014. 
I'm not knowledgeable about how to use nhibernate, so i'm not really sure how to troubleshoot this. I will continue to play with it but I'm guessing I should maybe check how sessions/transactions should be handled in Sql Server for Orchard (So far i don't see anything in Orchard Documentation stating any requirements for sql server.)

**Comment by chris904apps** [comment]
Additional note, tables are created in the database. also, when i reloaded the page i received the following message: "This tenant is currently initializing. Please try again later."

**Comment by mead3000** [comment]
I also got this error after getting the lastest dev branch.

Here is my stack trace

`[TransactionException: Transaction not connected, or was disconnected]
   NHibernate.Transaction.AdoTransaction.CheckNotZombied() +70
   NHibernate.Transaction.AdoTransaction.Commit() +258
   Orchard.Data.TransactionManager.DisposeSession() in C:\dev\Projects\Orchard\src\Orchard\Data\SessionLocator.cs:96
   Orchard.Data.TransactionManager.Dispose() in C:\dev\Projects\Orchard\src\Orchard\Data\SessionLocator.cs:86
   Autofac.Core.Disposer.Dispose(Boolean disposing) +81
   Autofac.Util.Disposable.Dispose() +36
   Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing) +65
   Autofac.Util.Disposable.Dispose() +36
   Autofac.Features.OwnedInstances.Owned`1.Dispose(Boolean disposing) +45
   Autofac.Util.Disposable.Dispose() +36
   Orchard.Environment.DefaultOrchardShell.Activate() in C:\dev\Projects\Orchard\src\Orchard\Environment\DefaultOrchardShell.cs:81
   Orchard.Environment.<>c__DisplayClass51_0.<ActivateShell>b__2() in C:\dev\Projects\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:373
   Orchard.Utility.NamedReaderWriterLock.RunWithWriteLock(String name, Action body) in C:\dev\Projects\Orchard\src\Orchard\Utility\NamedReaderWriterLock.cs:62
   Orchard.Environment.DefaultOrchardHost.ActivateShell(ShellSettings settings) in C:\dev\Projects\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:362
   Orchard.Environment.DefaultOrchardHost.StartUpdatedShells() in C:\dev\Projects\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:134
   Orchard.Environment.DefaultOrchardHost.EndRequest() in C:\dev\Projects\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:317
   Orchard.Environment.DefaultOrchardHost.Orchard.Environment.IOrchardHost.EndRequest() in C:\dev\Projects\Orchard\src\Orchard\Environment\DefaultOrchardHost.cs:97
   Orchard.Web.MvcApplication.HostEndRequest(HttpApplication application, IOrchardHost host) in C:\dev\Projects\Orchard\src\Orchard.Web\Global.asax.cs:42
   Orchard.WarmupStarter.Starter`1.OnEndRequest(HttpApplication application) in C:\dev\Projects\Orchard\src\Orchard.WarmupStarter\Starter.cs:75
   Orchard.Web.MvcApplication.Application_EndRequest() in C:\dev\Projects\Orchard\src\Orchard.Web\Global.asax.cs:33

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +87
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +101
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +21
   System.Web.Util.ArglessEventHandlerProxy.Callback(Object sender, EventArgs e) +56
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69`

**Comment by sebastienros** [comment]
I need a simple repro please

**Comment by hsimah** [comment]
I just ran into this.
I created an Orchard website with no table prefix.
I added a tenant with a table prefix, same SQL Server database (identical connection string to default site).
Error occurs as above. 

I am doing this in Azure via the Portal, so I don't have all the diagnostics available. I will attempt to reproduce at home on my development PC. Don't tell my boss I'm doing this at work ;)

**Comment by dronzel** [comment]
Hey guys.

I am sorry for my bad english.

I have the same error after trying to install the Orchard system localy. I think the error is in the file:

`Orchard/Data/Migration/AutomaticDataMigrations.cs`


 ```
       private void EnsureDistributedLockSchemaExists()
        {
            // Ensure the distributed lock record schema exists.
            var schemaBuilder = new SchemaBuilder(_dataMigrationInterpreter);
            var distributedLockSchemaBuilder = new DistributedLockSchemaBuilder(_shellSettings, schemaBuilder);
            if (!distributedLockSchemaBuilder.SchemaExists()) {

                // Workaround to avoid some Transaction issue for PostgreSQL.
                if (_shellSettings.DataProvider.Equals("PostgreSql", StringComparison.OrdinalIgnoreCase)) {
                    _transactionManager.RequireNew();
                    distributedLockSchemaBuilder.CreateSchema();
                    return;
                }

                distributedLockSchemaBuilder.CreateSchema();

                distributedLockSchemaBuilder.CreateSchema();
                _transactionManager.RequireNew();
            }
        }

```
Here is the double call for distributedLockSchemaBuilder.CreateSchema() method.
If i comment one from the calls, i can done the installation.

**Comment by sebastienros** [comment]
@dronzel good catch

**Comment by MoBattah** [comment]
Why was this closed?
