### ISSUE TITLE
Audit Trail: Unable to filter by Content type

### ISSUE THREAD

**Issue by andrewcartwright1** [OrchardCMS/Orchard#7033]
When using the audit trail module alongside the Audit Trail Content Definition Events to allow for filtering, if a content item is saved, published, deleted, created or imported they will not show up in the filtered audit trail when filtering by Content Type

Replication Steps: As an admin

Enable the Audit Trail module and the Audit Trail Content Definition Events module
Create a content item and click ​publish now​
With the same content item make some changes click ​publish now​
Navigate to the audit trail and attempt to filter by that content type

![zappshot - 2016-07-13_09-53-28-am](https://cloud.githubusercontent.com/assets/10059155/16797482/a951fcb6-48df-11e6-89f7-84565f585810.png)

![zappshot - 2016-07-13_09-54-00-am](https://cloud.githubusercontent.com/assets/10059155/16797497/bee99ce6-48df-11e6-95b1-2865c33a22b3.png)

**Comment by sfmskywalker** [comment]
I believe the Content Type filter behaves differently than one might expect, but I don't recall the details. Notice the little question mark? Can you please hover over it and capture the tooltip? Thanks

**Comment by andrewcartwright1** [comment]
"Applies to content type events only, not to content item events"

**Comment by sfmskywalker** [comment]
There you go: it does not filter by a content item's content type, but only events regarding content type changes, e.g. when a content type was created, modified or deleted.

I do realize this is a confusing UI, but we weren't able at the time to come up with a better solution. It has to do with the modularity of the system. Each audit trail provider has a say in what filtering controls they want to contribute. If both the content item provider as well as the content type provider contribute a content type filter, it would not be much better.

But that was a while ago. Anyone any clever suggestions?

**Comment by DanielStolt** [comment]
I still can't think of a better way. :)

**Comment by sfmskywalker** [comment]
Yeah me neither. :)
What if we did add another "Content Type" filter, but using slightly different labels?
For example, the Content Items Audit Trail Provider would use something like: "Content events by Content Type", while the Content Type Audit Trail Provider would use: "Content Type events by Content Type".

**Comment by DanielStolt** [comment]
That's not a bad idea! I'm not sure if this actually makes it more clear, but I had the thought that maybe it could be shortened to:

- Content of type:
- Changes to content type:

**Comment by Skrypt** [comment]
That's one of the views that I would really like seeing filters to be hidden in a side panel like this one : 
https://codyhouse.co/gem/content-filter/
