### ISSUE TITLE
If an exception is thrown in a view or htmlhelper, the response is still output cached.

### ISSUE THREAD

**Issue by carlwoodhouse** [OrchardCMS/Orchard#7034]
It seem's that at the moment if an exception is thrown in a view or html helper, the response is still captured by output caching and stored along with it's status code, meaning subsequent visits to a url throw the same error even if the issue is rectified.

This was spotted using Redis as the cache provider; but i imagine it's the issue whatever the provider.

It seems that the ResponseIsCachable tries to determine the status and not cache if its not 200 or a transformed redirect, BUT at this point the StatusCode is still 200.

The status could be rechecked after the output is captured before storing it, this seems to fix the issue - happy to provide a PR with this fix.

**Comment by carlwoodhouse** [comment]
PR: #7035

**Comment by DanielStolt** [comment]
Ah, yes I have witnessed this behavior as well, but I was too preoccupied at the time to get to the bottom of it. Good catch.
