### ISSUE TITLE
Many modules and themes fail when installing 

### ISSUE THREAD

**Issue by cirocorvino** [OrchardCMS/Orchard#7036]
With 1.10.1 version of Orchard many modules and themes fail when installing, about theme I tryed to install only TheThemeMachine and TTMResponsive.

**Comment by infofromca** [comment]
impposible, can you build ?

**Comment by cirocorvino** [comment]
Really I want avoid debugging on code... I experienced the issue directly
on deployable versione. .

I ve spent a lot of hours trying to install modules without success.. with
previous versions I haven't this problem.

I also tryed all workaround suggested in stackoverflow and in git issues
but none has solved the problem..
Il 19/Lug/2016 03:54, "andy" <notifications@github.com> ha scritto:

**Comment by carlwoodhouse** [comment]
This is most likely because 1.10.x had major breaking changes in terms of nuget and the lib folder.

I guess ideally if your running 1.10 the gallery should only show modules/themes updated for 1.10.x?

**Comment by chris904apps** [comment]
Is there a fix underway for this issue?? 
I'm having what i'm guessing is the the same problem. Here is the error message that I am getting with Orchard.  (Side question: Is there a way to downgrade the version of orchard I'm using? I updated to the 1.10.1 version which sounds like it is causing the problem so I'm hoping going back a version will fix my issues...)
`Oops. Something went wrong ... sorry


An unhandled exception has occurred and the request was terminated. Please refresh the page. If the error persists, go back

One or more errors occurred.

System.AggregateException: One or more errors occurred. ---> Orchard.OrchardException: Error while loading extension '{0}'. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Orchard.Layouts, Version=1.10.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes) at System.Reflection.RuntimeAssembly.GetExportedTypes() at Orchard.Environment.Extensions.Loaders.PrecompiledExtensionLoader.LoadWorker(ExtensionDescriptor descriptor) at Orchard.Environment.Extensions.ExtensionManager.BuildEntry(ExtensionDescriptor descriptor) at Orchard.Environment.Extensions.ExtensionManager.<>c__DisplayClass1c.<LoadFeature>b__16(AcquireContext`1 ctx) at Orchard.Caching.Cache`2.CreateEntry(TKey k, Func`2 acquire) at Orchard.Caching.Cache`2.<>c__DisplayClass2.<Get>b__0(TKey k) at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory) at Orchard.Caching.Cache`2.Get(TKey key, Func`2 acquire) at Orchard.Caching.CacheManagerExtensions.Get[TKey,TResult](ICacheManager cacheManager, TKey key, Boolean preventConcurrentCalls, Func`2 acquire) at Orchard.Environment.Extensions.ExtensionManager.LoadFeature(FeatureDescriptor featureDescriptor) --- End of inner exception stack trace --- at Orchard.Environment.Extensions.ExtensionManager.LoadFeature(FeatureDescriptor featureDescriptor) at Orchard.Caching.Cache`2.CreateEntry(TKey k, Func`2 acquire) at Orchard.Caching.Cache`2.<>c__DisplayClass2.<Get>b__0(TKey k) at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory) at Orchard.Caching.Cache`2.Get(TKey key, Func`2 acquire) at Orchard.Caching.CacheManagerExtensions.Get[TKey,TResult](ICacheManager cacheManager, TKey key, Boolean preventConcurrentCalls, Func`2 acquire) at Orchard.Environment.Extensions.ExtensionManager.<LoadFeatures>b__10(FeatureDescriptor descriptor) at Orchard.Caching.DefaultParallelCacheContext.TaskWithAcquireContext`1.Execute() at System.Linq.Parallel.ArrayMergeHelper`1.ToArrayElement(Int32 index) at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey) at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork() at System.Linq.Parallel.SpoolingTaskBase.Work() at System.Linq.Parallel.QueryTask.BaseWork(Object unused) at System.Threading.Tasks.Task.Execute() --- End of inner exception stack trace --- at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose) at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute() at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId) at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream) at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings) at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream) at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings) at System.Linq.Parallel.ForAllOperator`1.RunSynchronously() at System.Linq.Parallel.ArrayMergeHelper`1.Execute() at System.Linq.Parallel.QueryOperator`1.ExecuteAndGetResultsAsArray() at Orchard.Caching.DefaultParallelCacheContext.RunInParallel[T,TResult](IEnumerable`1 source, Func`2 selector) at Orchard.Environment.Extensions.ExtensionManager.LoadFeatures(IEnumerable`1 featureDescriptors) at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext() at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) at Orchard.Modules.Controllers.AdminController.FeaturesPOST(FeaturesBulkAction bulkAction, IList`1 featureIds, Nullable`1 force) at lambda_method(Closure , ControllerBase , Object[] ) at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() ---> (Inner Exception #0) Orchard.OrchardException: Error while loading extension '{0}'. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Orchard.Layouts, Version=1.10.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes) at System.Reflection.RuntimeAssembly.GetExportedTypes() at Orchard.Environment.Extensions.Loaders.PrecompiledExtensionLoader.LoadWorker(ExtensionDescriptor descriptor) at Orchard.Environment.Extensions.ExtensionManager.BuildEntry(ExtensionDescriptor descriptor) at Orchard.Environment.Extensions.ExtensionManager.<>c__DisplayClass1c.<LoadFeature>b__16(AcquireContext`1 ctx) at Orchard.Caching.Cache`2.CreateEntry(TKey k, Func`2 acquire) at Orchard.Caching.Cache`2.<>c__DisplayClass2.<Get>b__0(TKey k) at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory) at Orchard.Caching.Cache`2.Get(TKey key, Func`2 acquire) at Orchard.Caching.CacheManagerExtensions.Get[TKey,TResult](ICacheManager cacheManager, TKey key, Boolean preventConcurrentCalls, Func`2 acquire) at Orchard.Environment.Extensions.ExtensionManager.LoadFeature(FeatureDescriptor featureDescriptor) --- End of inner exception stack trace --- at Orchard.Environment.Extensions.ExtensionManager.LoadFeature(FeatureDescriptor featureDescriptor) at Orchard.Caching.Cache`2.CreateEntry(TKey k, Func`2 acquire) at Orchard.Caching.Cache`2.<>c__DisplayClass2.<Get>b__0(TKey k) at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory) at Orchard.Caching.Cache`2.Get(TKey key, Func`2 acquire) at Orchard.Caching.CacheManagerExtensions.Get[TKey,TResult](ICacheManager cacheManager, TKey key, Boolean preventConcurrentCalls, Func`2 acquire) at Orchard.Environment.Extensions.ExtensionManager.<LoadFeatures>b__10(FeatureDescriptor descriptor) at Orchard.Caching.DefaultParallelCacheContext.TaskWithAcquireContext`1.Execute() at System.Linq.Parallel.ArrayMergeHelper`1.ToArrayElement(Int32 index) at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey) at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork() at System.Linq.Parallel.SpoolingTaskBase.Work() at System.Linq.Parallel.QueryTask.BaseWork(Object unused) at System.Threading.Tasks.Task.Execute()<--- ---> (Inner Exception #1) Orchard.OrchardException: Error while loading extension '{0}'. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Orchard.Layouts, Version=1.10.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes) at System.Reflection.RuntimeAssembly.GetExportedTypes() at Orchard.Environment.Extensions.Loaders.PrecompiledExtensionLoader.LoadWorker(ExtensionDescriptor descriptor) at Orchard.Environment.Extensions.ExtensionManager.BuildEntry(ExtensionDescriptor descriptor) at Orchard.Environment.Extensions.ExtensionManager.<>c__DisplayClass1c.<LoadFeature>b__16(AcquireContext`1 ctx) at Orchard.Caching.Cache`2.CreateEntry(TKey k, Func`2 acquire) at Orchard.Caching.Cache`2.<>c__DisplayClass2.<Get>b__0(TKey k) at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory) at Orchard.Caching.Cache`2.Get(TKey key, Func`2 acquire) at Orchard.Caching.CacheManagerExtensions.Get[TKey,TResult](ICacheManager cacheManager, TKey key, Boolean preventConcurrentCalls, Func`2 acquire) at Orchard.Environment.Extensions.ExtensionManager.LoadFeature(FeatureDescriptor featureDescriptor) --- End of inner exception stack trace --- at Orchard.Environment.Extensions.ExtensionManager.LoadFeature(FeatureDescriptor featureDescriptor) at Orchard.Caching.Cache`2.CreateEntry(TKey k, Func`2 acquire) at Orchard.Caching.Cache`2.<>c__DisplayClass2.<Get>b__0(TKey k) at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory) at Orchard.Caching.Cache`2.Get(TKey key, Func`2 acquire) at Orchard.Caching.CacheManagerExtensions.Get[TKey,TResult](ICacheManager cacheManager, TKey key, Boolean preventConcurrentCalls, Func`2 acquire) at Orchard.Environment.Extensions.ExtensionManager.<LoadFeatures>b__10(FeatureDescriptor descriptor) at Orchard.Caching.DefaultParallelCacheContext.TaskWithAcquireContext`1.Execute() at System.Linq.Parallel.ArrayMergeHelper`1.ToArrayElement(Int32 index) at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey) at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork() at System.Linq.Parallel.SpoolingTaskBase.Work() at System.Linq.Parallel.QueryTask.BaseWork(Object unused) at System.Threading.Tasks.Task.Execute()<--- ---> (Inner Exception #2) Orchard.OrchardException: Error while loading extension '{0}'. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Orchard.Layouts, Version=1.10.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes) at System.Reflection.RuntimeAssembly.GetExportedTypes() at Orchard.Environment.Extensions.Loaders.PrecompiledExtensionLoader.LoadWorker(ExtensionDescriptor descriptor) at Orchard.Environment.Extensions.ExtensionManager.BuildEntry(ExtensionDescriptor descriptor) at Orchard.Environment.Extensions.ExtensionManager.<>c__DisplayClass1c.<LoadFeature>b__16(AcquireContext`1 ctx) at Orchard.Caching.Cache`2.CreateEntry(TKey k, Func`2 acquire) at Orchard.Caching.Cache`2.<>c__DisplayClass2.<Get>b__0(TKey k) at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory) at Orchard.Caching.Cache`2.Get(TKey key, Func`2 acquire) at Orchard.Caching.CacheManagerExtensions.Get[TKey,TResult](ICacheManager cacheManager, TKey key, Boolean preventConcurrentCalls, Func`2 acquire) at Orchard.Environment.Extensions.ExtensionManager.LoadFeature(FeatureDescriptor featureDescriptor) --- End of inner exception stack trace --- at Orchard.Environment.Extensions.ExtensionManager.LoadFeature(FeatureDescriptor featureDescriptor) at Orchard.Caching.Cache`2.CreateEntry(TKey k, Func`2 acquire) at Orchard.Caching.Cache`2.<>c__DisplayClass2.<Get>b__0(TKey k) at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory) at Orchard.Caching.Cache`2.Get(TKey key, Func`2 acquire) at Orchard.Caching.CacheManagerExtensions.Get[TKey,TResult](ICacheManager cacheManager, TKey key, Boolean preventConcurrentCalls, Func`2 acquire) at Orchard.Environment.Extensions.ExtensionManager.<LoadFeatures>b__10(FeatureDescriptor descriptor) at Orchard.Caching.DefaultParallelCacheContext.TaskWithAcquireContext`1.Execute() at System.Linq.Parallel.ArrayMergeHelper`1.ToArrayElement(Int32 index) at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey) at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork() at System.Linq.Parallel.SpoolingTaskBase.Work() at System.Linq.Parallel.QueryTask.BaseWork(Object unused) at System.Threading.Tasks.Task.Execute()<--- 
`

**Comment by sfmskywalker** [comment]
I don't know that we can fix this. It's really up to the module developers to keep their modules up to date. However, it would be helpful if the gallery would expose some kind of information regarding Orchard version compatibility.

**Comment by chris904apps** [comment]
@sfmskywalker think version compatibility info would be great. How could it be done?
Maybe if we had some meta info with the modules that displayed what version it of Orchard it was built against. I'm not sure but that maybe the simples way.
Or
can a service be ran on the modules every time a change a new version of Orchard is released to check for exceptions being thrown when installing the modules? (I don't know if this is truly possible considering the amount of modules available on Orchard)
Or
Can the author of modules be notified that an update has been made and have them test the installation of their module and other functionality (Maybe have a service they can run locally that will do general exception and other bug testing, and if passed will call to module gallery and update status) is still working against the new versions of Orchard and have them update some type of status on the gallery so that users know they have checked and validated (to the best of their ability) their module works with the new code base.
And/Or
Can a notification system be set up when we have issue like this so that the authors of the module are aware and a status indicator is added to the module in the gallery until it has been resolved.

I haven't tried building a module myself yet but is there any type of quality control process for modules? I.E. the module must build, your documentation on your module must explain how to use the module....
Maybe this needs to be looked at for improvements especially looking forward to Orchard 2 using Asp.Net Core.

**Comment by ifle** [comment]
The simply way is allows to users comfirm with which version a module was been tested.

**Comment by sebastienros** [comment]
Closing because it's a known breaking change in 1.10 and there is not much more to add to how much bad this is.
