### ISSUE TITLE
Displaying Multiple Rich Content Editors from a Custom Part (Not using Fields)

### ISSUE THREAD

**Issue by hannan-azam** [OrchardCMS/Orchard#7043]
I came across this requirement of displaying TinyMce Rich Content Editor through a Custom Part. After looking into the code i came to know that it can be done using the following but the Property Name in Part needs to be **"Text"**. Using this approach one can't display more than one editors.
```
@Display.Body_Editor(Text: Model.PrintHead, EditorFlavor: "html")
```

If we modify the Body-Html.Editor.cshtml of TineMce Module as given, it will keep working with current functionality as well as we can use it from Custom Parts to display multiple Rich Content Editors as:

```
    var propertyName = Model.PropertyName != null ? (string)Model.PropertyName : "Text";
```
```
    var autofocus = "@(Model.AutoFocus == true ? ViewData.TemplateInfo.GetFullHtmlFieldId(propertyName) : null)";
```
```
@Html.TextArea(propertyName, (string)Model.Text, 25, 80,
     new Dictionary<string,object> {
        {"class", "html tinymce"},
        {"data-mediapicker-uploadpath",Model.AddMediaPath},
        {"data-mediapicker-title",T("Insert/Update Media")},
        {"style", "width:100%"}
     })
```

We can now display the Rich content editor by passing appropriate PropertyName. It will keep working with all existing scenarios without breaking anything.
```
@Display.Body_Editor(PropertyName: "MyCustomProperty", Text: Model.PrintHead, EditorFlavor: "html")
```

**Comment by sebastienros** [comment]
Seems fine.
