### ISSUE TITLE
Export does not include multiple layouts?

### ISSUE THREAD

**Issue by remesq** [OrchardCMS/Orchard#7046]
I had a site on 1.9.2 that I exported to upgrade to a server on Azure with1.10.1. I selected "Layout" as one of the content types to include in the export file. I had a total of three layouts in the old site.

When I imported to the new server only one layout was imported. The pages that relied on the other two layouts in the new site still had the correct layouts - except that in the drop down only one layout shows.

I'm going to rebuild the layouts in 1.10.1, but just wondering if this is a known problem.

EDIT: Upon reflection, I notice that Layouts have a "Save" and "Publish Now" button. All the layouts in my 1.9.2 site say "Unpublish" - which means they were published and should have been included in my export (I selected published items).

**Comment by sebastienros** [comment]
I think it works in 1.10, feel free to reopen if you confirm it's still an issue.
