### ISSUE TITLE
Orchard.Layouts/Widgets [Feature request]: 

### ISSUE THREAD

**Issue by puggycode** [OrchardCMS/Orchard#7048]
To have the ability to provide a custom display type for a widget being rendered. In my case, a widget contained within a Layout-->Projection.Element, contained within another Layout-->Projection.Element.
Sipke suggested:
"This could be done as a simple property we would add to the widget elements, which would be quite easy to do."
That would be great to achieve via the Layouts designer, but the real power would stem from being able to create Queries that use a Layout with 'Custom display type' to effect widgets [and other elements?] contained within the resultant recursive layouts. I believe if no displayType is supplied, and/or, is not recognized, orchard by convention defaults to 'Detail', so this shouldn’t affect existing scenarios, only enhance Drivers that are coded to recognise the Custom DisplayType.
The above relates to: http://orchardpros.net/tickets/10775

**Comment by sebastienros** [comment]
What is the relationship between Queries and Widgets here? I don't understand the scenario. Are you querying widgets?

**Comment by sebastienros** [comment]
Is this PR fixing your isue: https://github.com/OrchardCMS/Orchard/pull/7074

**Comment by puggycode** [comment]
Yes, #7074 would immediately fix that issue - thanks @jtkech and @sebastienros
