### ISSUE TITLE
Orchard admin : modals

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/Orchard#7052]
As seen in the Amaretti theme. We can use the Bootstrap modals for different scenarios. Right now we replaced all the javascript confirm with the BS modals. We could also use it for displaying forms. So, the goal is to implement all the use cases displayed on this page :

https://foxythemes.net/preview/products/amaretti-v1.1.7/ui-modals.php

We then could also make the modal animations to be configurable in the Admin Theme or Orchard Settings. Right now the shape/view "ConfirmationDialog.cshtml" has been moved to the Orchard.Core project. Since those modals have a dependency on Bootstrap I think we should maybe move it back to the Admin Theme unless we want to make BS a dependency on Orchard.Core.

I suggest we keep the actual data-confirm attribute and add a data-modal attribute that would be used for displaying custom shapes/forms. Right now we only have the ability to change the text displayed on the content zone of those confirm modals. So the idea is to be able to provide a more generic shape for those who would want to customize their own modals. We could then discuss if we should keep the data-confirm implementation. Personnally I would keep it, just because it's simpler.

```
data-confirm="@T("Are you sure you want to delete this item?")"
data-modal="ClassOrIdName"
```

Another implementation would be to use a data-toggle attribute with a string parameter to define which type it is combined with a data-target attribute. It could be used to toggle modals, dropdowns.

```html
<button data-toggle="modal" data-target="#mod-success" type="button" class="btn btn-space btn-success"><i class="icon icon-left s7-check"></i>Success</button>
<div id="mod-success" tabindex="-1" role="dialog" style="" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button " data-dismiss="modal" aria-hidden="true" class="close"><i class="icon s7-close"></i></button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <div class="i-circle text-success"><i class="icon s7-check"></i></div>
                    <h4>Awesome!</h4>
                    <p>Changes has been saved successfully!</p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-default">Cancel</button>
                <button type="button" data-dismiss="modal" class="btn btn-success">Proceed</button>
            </div>
        </div>
    </div>
</div>
```

**Comment by sfmskywalker** [comment]
The reason the modal shape has been added to core is to prevent modules from having a dependency on the shapes provided by the new admin theme. Notice that Core itself does not use BS at all; the new admin theme overrides this shape and provides the necessary scripts and styles.

**Comment by Skrypt** [comment]
Maybe we should then move back the javascript function to the base.js Core file.

**Comment by Skrypt** [comment]
A little update on modals. Bootstrap modal already implements the use of it's modals by using the 
```
data-toggle="modal" data-target="#mod-success"
```
technique. So it should work straight out of the box.

http://getbootstrap.com/javascript/#modals

**Comment by Skrypt** [comment]
Here is what I did in Base.js for the fallback to javascript confirm()

```javascript
    $(function () {
        // Bootstrap modal confirmation.
        $("[data-confirm]").click(function (e) {
            var magicToken = $("input[name=__RequestVerificationToken]").first();
            if (!magicToken) { return; } // no sense in continuing if form POSTS will fail
            var _this = $(this);
            var hrefParts = _this.attr("href").split("?");
            var form = $("<form action=\"" + hrefParts[0] + "\" method=\"POST\" />");
            form.append(magicToken.clone());
            if (hrefParts.length > 1) {
                var queryParts = hrefParts[1].split("&");
                for (var i = 0; i < queryParts.length; i++) {
                    var queryPartKVP = queryParts[i].split("=");
                    //trusting hrefs in the page here
                    form.append($("<input type=\"hidden\" name=\"" + decodeURIComponent(queryPartKVP[0]) + "\" value=\"" + decodeURIComponent(queryPartKVP[1]) + "\" />"));
                }
            }
            form.css({ "position": "absolute", "left": "-9999em" });
            $("body").append(form);

            if (!confirm($(this).data("confirm"))) {
                return false;
            }

            form.submit();
            e.preventDefault();
        });

        // Bulk action confirmation.
        $("[data-bulk-action]").click(function (e) {
            var magicToken = $("input[name=__RequestVerificationToken]").first();
            if (!magicToken) { return; } // no sense in continuing if form POSTS will fail
            var _this = $(this);
            var hrefParts = _this.attr("href").split("?");
            var form = $("<form action=\"" + hrefParts[0] + "\" method=\"POST\" />");
            form.append(magicToken.clone());
            if (hrefParts.length > 1) {
                var queryParts = hrefParts[1].split("&");
                for (var i = 0; i < queryParts.length; i++) {
                    var queryPartKVP = queryParts[i].split("=");
                    //trusting hrefs in the page here
                    form.append($("<input type=\"hidden\" name=\"" + decodeURIComponent(queryPartKVP[0]) + "\" value=\"" + decodeURIComponent(queryPartKVP[1]) + "\" />"));
                }
            }
            form.css({ "position": "absolute", "left": "-9999em" });
            $("body").append(form);

            if (!confirm($(this).data("bulk-action-confirm"))) {
                return false;
            }

            form.submit();
            e.preventDefault();
        });

        // End Bulk edit bootstrap dropdown button actions
    });
```

In the new admin theme I added an event unbind on both attributes before binding it back and displaying the Bootstrap modals instead : 

```javascript
$("[data-confirm]").unbind('click');
... rest of what we did
$("[data-bulk-action]").unbind('click');
... rest if what we did
```

That way we don't need anything coming from the ConfirmationDialog shape in the Core project. We can override it inside our admin theme.

**Comment by sfmskywalker** [comment]
Actually the Modal shape in the Core project did not rely on any script, it was simply a non-functional shape intended to be overridden by the admin theme, so that core definitely does not have any BS dependencies.

I'm not sure what you did with base.js, but if that file is part of the Core project, then it seems wrong that the script mentions Bootstrap in the comments.

Am I correct in understanding that you implemented Modal behavior in Core so that it works even without the Admin theme? If so then that would be good just as long as it does not rely on anything BS. My thinking here was that the core shape would simply provide a very minimalistic implementation, meant to be overridden by the admin theme.

If you're of the same mind then it's all good.

**Comment by Skrypt** [comment]
Yes that's what I did. I just need to edit those comments because I'm not using anything Bootstrap in the Core base.js file.
