### ISSUE TITLE
Orchard admin : Tokens are not displayed

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard#7057]
Tokens are not displayed anymore.

Tested on /OrchardLocal/Admin/ContentTypes/Edit/Blog on Autoroute settings

Also added RSS part and the icon is displayed on the right, not in the textbox.

**Comment by Skrypt** [comment]
I'm guessing this is related with the expandoControl bug.

**Comment by Skrypt** [comment]
First thing I found is that by using Style.Require("jQueryUI") the pop-up box works. So it is a styling issue.
