### ISSUE TITLE
Orchard CMS - Body Part content of the page is missing/not loading

### ISSUE THREAD

**Issue by kamalhasan-k** [OrchardCMS/Orchard#7065]
We are using Orchard CMS1.7.2 and recently we are frequently getting the strange issue in production server i.e body part content of the page is not loading/missing and throwing error in the log as:

System.NullReferenceException: Object reference not set to an instance of an object. at System.Web.Mvc.ModelValidatorProviderCollection.<>c__DisplayClass7.<GetValidators>b__6(ModelValidatorProvider provider) at System.Linq.Enumerable.<SelectManyIterator>d__142.MoveNext() at System.Web.Mvc.ModelValidator.CompositeModelValidator.<Validate>d__1.MoveNext() at System.Web.Mvc.DefaultModelBinder.OnModelUpdated(ControllerContext controllerContext, ModelBindingContext bindingContext) at System.Web.Mvc.DefaultModelBinder.BindComplexModel(ControllerContext controllerContext, ModelBindingContext bindingContext) at Orchard.ContentManagement.MetaData.Models.SettingsDictionary.TryGetModel[T](String key) in c:\Users\xxxxxxx\Dev\rew\tfs\up2\source\Orchard\src\Orchard\ContentManagement\MetaData\Models\SettingsDictionary.cs:line 17 at Orchard.Core.Common.Drivers.BodyPartDriver.GetFlavor(BodyPart part) in c:\Users\xxxxxxx\Dev\rew\tfs\up2\source\Orchard\src\Orchard.Web\Core\Common\Drivers\BodyPartDriver.cs:line 86 at Orchard.Core.Common.Drivers.BodyPartDriver.<>c__DisplayClass7.<Display>b__4(String text, IHtmlFilter filter) in c:\Users\xxxxxxx\Dev\rew\tfs\up2\source\Orchard\src\Orchard.Web\Core\Common\Drivers\BodyPartDriver.cs:line 40 at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable1 source, TAccumulate seed, Func3 func) at Orchard.Core.Common.Drivers.BodyPartDriver.<>c__DisplayClass7.<Display>b__3() in c:\Users\xxxxxxx\Dev\rew\tfs\up2\source\Orchard\src\Orchard.Web\Core\Common\Drivers\BodyPartDriver.cs:line 40 at Orchard.ContentManagement.Drivers.ContentPartDriver1.<>c__DisplayClassf.<ContentShape>b__e(BuildShapeContext ctx) in c:\Users\xxxxxxx\Dev\rew\tfs\up2\source\Orchard\src\Orchard\ContentManagement\Drivers\ContentPartDriver.cs:line 130 at Orchard.ContentManagement.Drivers.Coordinators.ContentPartDriverCoordinator.<>c__DisplayClassa.<BuildDisplay>b__9(IContentPartDriver driver) in c:\Users\xxxxxxx\Dev\rew\tfs\up2\source\Orchard\src\Orchard\ContentManagement\Drivers\Coordinators\ContentPartDriverCoordinator.cs:line 49 at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable1 events, Action1 dispatch, ILogger logger) in c:\Users\xxxxxxx\Dev\rew\tfs\up2\source\Orchard\src\Orchard\InvokeExtensions.cs:line 17

This error will go off (addressed/fixed) and body part of the content page will be loaded normally after we restart the IIS- app pool of the server. This become major road block as user is not able to view page content of the published pages (defeating CMS purpose). We are not sure what is the root cause of the issue and is frustrating as it occurring frequently in production server.

Request you to share your thoughts/solutions.

Regards,
Kamal

**Comment by sebastienros** [comment]
After the discussion we had on Gitter, it seems that it could be related to the custom Body editor you are using.
