### ISSUE TITLE
Orchad CMS - Dead lock & Time out issues

### ISSUE THREAD

**Issue by kamalhasan-k** [OrchardCMS/Orchard#7066]
We are using Orchard CMS 1.7.2. we recently getting many dead locks, timeouts and assertion failure issue.

Below are my observations:
1.dead lock and time outs are mainly happening at the below query: select userrolesp0_.Id as Id26_, userrolesp0_.UserId as UserId26_, userrolesp0_.Role_id as Role3_26_ from Orchard_Roles_UserRolesPartRecord userrolesp0_ where userrolesp0_userrolesp0_.UserId=@p0

2.The Orchard_Roles_UserRolesPartRecord table is having index on USerId column even though no change in number of timeouts and dead locks

3.Along with this table, dead locks/timeouts/concurrency has been noticed on the following tables: Orchard_Framework_ContentItemRecord and Orchard_Framework_ContentItemVersionRecord (Note : These tables also having indexes)

4.N-hibernate is not able to fetch records when table having more than 1+ million records (in Orchard_Framework_ContentItemVersionRecord) and throwing assertion failure

Because of this, we are getting many complaints from client/end users saying that they are not able to use the site well.

We are not sure how to control/fix them as these are coming from orchard framework level. As of now, We are looking at database isolation level. Some of the orchard articles recommending to change the database isolation level to snapshot (but no concrete justification on this)

Please share your thoughts which are helpful for to us to resolve these issues at the earliest.

Regards, 
Kamal

**Comment by sebastienros** [comment]
To fix some potential dead locks I would suggest you upgrade to a more recent version which has many fixes regarding data access.
About loading 1 million records with NHibernate the only solution is to simply not do that. I can't imagine a scenario where you'd have to load 1 million content items in memory, or you probably need another solution.

**Comment by kamalhasan-k** [comment]
Thank for your suggestions.

The application has to fetch few records from table having 1+ million records.  At this point, most of the times, N-hibernate is throwing error as Assertion failure.

**Comment by sebastienros** [comment]
Please provide some repro steps, there is nothing we are aware of that could link to this issue. Also please check that you are not reading too many values, and you have correct indexes in your database.
