### ISSUE TITLE
Lost password confirmation message usability issue

### ISSUE THREAD

**Issue by kumards** [OrchardCMS/Orchard#7070]
In the current implementation, if a user tries to recover his/her password, after submitting the username/email id, the system presents "Check your e-mail for the confirmation link." message.

When a legitimate user(not a hacker) tries with incorrect/misspelled email id, the user is still presented with the same message and the user is end up waiting for the email to arrive. Actually the email is sent out only if the user is found in the system, not otherwise. 

I would assume that for a security reason, we dont want to say if the given user name/email id exist in the system; so that hacker does not try with various username/password to identify valid usernames/emailds in the system.

My recommendation is changing the user confirmation message to something on this line "If you are an existing user, we will immediately send you an email with a link to reset your password." so that the user at least knows s/he will get an email only if the give username/email id is valid. Otherwise we will have to tell the user that the given username/email id does not exist in the system. In the later case, we may have to validate if the user is a real person and not a robot or some other security measure.

**Comment by sebastienros** [comment]
1. We don't want to give any hint that a username or email is valid for the system, so we can't change the message based on that.
2. I assume anyone knows that making a typo in the username of email will make the feature useless. 

Do we have to be explicit about 2. ? I don't think we have to, but if we can find a better message let's propose something.

**Comment by kumards** [comment]
This is the message I propose.
From the shelve-set "If you are an existing user, we will send you an email with a link to reset your password."

This message does not reveal the users existence in the database. All it says you will receive an email if you keyed in the name right. I also found this kind of message being used in other sites.
