### ISSUE TITLE
Redis exception if configuration is missing

### ISSUE THREAD

**Issue by mdameer** [OrchardCMS/Orchard#7075]
I noticed that if the user enable the 'Redis Output Cache' for any reason (maybe by mistake), the site will go down until provided the appropriate configuration (valid connection string), I think this module should check for it's configuration and if it's not presented it must disable redis cache functionality without throwing an exception.

**Comment by carlwoodhouse** [comment]
i think there is an outstanding PR for this - https://github.com/OrchardCMS/Orchard/pull/6876

**Comment by mdameer** [comment]
Yes, you are right, this fix is not included in Orchard 1.10.1, maybe in future releases.

**Comment by Skrypt** [comment]
True, I fixed it.
