### ISSUE TITLE
TinyMCE javascript files not found when using chrome

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/Orchard#7082]
Ok, this seems like it is an environmental issue but I cannot prove it. Maybe someone can try to reproduce it. I downloaded and ran a stock out of the box install of orchard 1.10.1, after initial setup I went to edit the home page. In chrome I cannot bring up tinyMCE to edit items in the layout of the home page. When I open the same item using edge browser or IE, it works as expected. The console in chrome says the following to 404 statuses
Failed to load: http://localhost:30321/OrchardLocal/Modules/TinyMce/scripts/themes/advanced/theme.min.js
Failed to load: http://localhost:30321/OrchardLocal/Modules/TinyMce/scripts/plugins/inlinepopups/plugin.min.js

I have restarted my system to see if something was just goofed up but it still persisted. Here are the steps to reproduce.

1. Download, extract, open in visual studio. Run default recipe, with sql express.
https://github.com/OrchardCMS/Orchard/archive/1.10.1.zip

2. Once the site is setup go to edit the home page "Welcome to Orchard!"

3. Using internet explorer or edge browser, the editor will open
4. Using the latest version of chrome browser it will fail to let you edit the content of this page.

I am running windows 10 and visual studio 2015 with update 3

**Comment by sebastienros** [comment]
I downloaded the link and tried with Chrome, I can see the TinyMCE editor.

**Comment by dougauerbach** [comment]
Oddly enough, I'm seeing this behavior too, although the URLs are different.
It seems that certain plugins are being requested from the CDN, but the files do not exist, resulting in a 404 error from the CDN.

This is reproducible when using the Orchard Admin's content editor on any content item with a Body part, which happens to utilize the tinyMCE control.  (v.1.10.2.0)

These are the failing URLs in my environments.

- tinymce.min.js:2 GET https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.8.2/plugins/medialibrary/plugin.min.js 404 ()
- tinymce.min.js:2 GET https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.8.2/skins/orchardlightgray/content.min.css 404 ()
- tinymce.min.js:2 GET https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.8.2/skins/orchardlightgray/skin.min.css 404 ()
-
