### ISSUE TITLE
Update new admin theme with latest version of Orchard Admin (FoxyThemes)

### ISSUE THREAD

**Issue by sfmskywalker** [OrchardCMS/Orchard#7084]
Latest version can be downloaded from here: http://www.ideliverable.com/downloads/orchard-admin-v1.2.0.zip

**Comment by agriffard** [comment]
We have to keep the changes we made in the original files when we update them.
Let's try to list them.
There are the ones I remember so far:
- Add styles for checkboxes and radio
- Changes of the menu

**Comment by Skrypt** [comment]
Have'nt we used overrides for these ?
