### ISSUE TITLE
Can't add widget to certain culture  [Orchard v.1.10.0.0]

### ISSUE THREAD

**Issue by gabboman** [OrchardCMS/Orchard#7086]
I have the culture modules enabled, but I can't add a widget to a culture. This is my default layer:
![image](https://cloud.githubusercontent.com/assets/3456181/17735457/8a9f57d2-6482-11e6-8ae5-75daca912dc8.png)

And this is what happends when I select any culture:

![image](https://cloud.githubusercontent.com/assets/3456181/17735470/a56ed0f6-6482-11e6-8881-68a6ccf851e8.png)

I can't add  widgets to any culture neither:

![image](https://cloud.githubusercontent.com/assets/3456181/17735538/0b938516-6483-11e6-98be-980e11394ec7.png)

What I'm doing right now is  adding layers for every language, but  I feel like I am doing something wrong, there is a filter of languages in the widgets.
![image](https://cloud.githubusercontent.com/assets/3456181/17735507/dc74d744-6482-11e6-9c95-521e05c6e654.png)

Am I doing something wrong or is this a problem with orchard?

Thank you for your help

**Comment by sebastienros** [comment]
It's fixed in the dev branch as it requires a new feature for cloning content items.

**Comment by gabboman** [comment]
Also, I just discovered that I had to add a localization element to the widgets. Thanks for your help
