### ISSUE TITLE
Sort menu items in admin panel by name

### ISSUE THREAD

**Issue by VahidNaderi** [OrchardCMS/Orchard#7090]
IMO it would be much better if we sort the menu items by their names and create a quick access part for frequently used items.

**Comment by sebastienros** [comment]
Can't do that. Menu items might have different names in different languages, and we would also get weird items at the top and important ones at the bottom.

What could be done however, and I think it might already be the case, @sfmskywalker made a demo I think, is that typing some text filters the items in the menu.
