### ISSUE TITLE
New Feature: Auto cleanup of Audit Trail Event Record

### ISSUE THREAD

**Issue by hannan-azam** [OrchardCMS/Orchard#7098]
A few days ago i opened up a ticket regarding the crash issue of Audit Trail #7088
@pszmyd suggested that we should trim the audit trail record table and it did the trick. We implemented it as an admin setting where user can specify the number of days for which he wants to maintain records. Further a setting is available to turn this audit trail auto cleanup on/off. Once enabled a scheduler runs every 24 hours and cleanup the extra records available.

Can we make this part of the main Audit Trail Module. It might be useful for many other users.
CC: @sebastienros @pszmyd  @sfmskywalker

**Comment by sfmskywalker** [comment]
I believe we already have that feature, which you can enable and then configure from the audit trail settings. I believe the feature is called "Audit Trail Trimming".

**Comment by hannan-azam** [comment]
@sfmskywalker thanks for pointing. We totally missed the out of the box feature.
