### ISSUE TITLE
Media resizing in projection

### ISSUE THREAD

**Issue by bernardocaldas** [OrchardCMS/Orchard#7102]
I would like to display a grid of content items that include a picture. I created a layout and then a query to get the content items I needed. I then edited the property to rewrite results so as to customize the image that was displayed, something like 
`
 src={Content.Fields.PacotePart.Foto.Url}?w=150&h=150&mode=crop&scale=both  class="img-rounded img-responsive">`

However, this is not working. How can I use the Media Processing features in this case?

Thanks

**Comment by sebastienros** [comment]
The url token seems to be correct, and will get your a link to the actual original image. But the modifiers are not working on the link directly, they are processed on the server side using the specific Shape.

I can't find any token however to do that, so I filed a new issue. A work around is to create a layout based on a Shape, then create this shape template in your theme and use the ResizeMediaUrl shape to render the image.

**Comment by sebastienros** [comment]
Closing as there is a workaround and I filed an issue to create a new token for your purpose.
