### ISSUE TITLE
.site\www\App_Data\Dependencies' is denied.

### ISSUE THREAD

**Issue by tedslinkard** [OrchardCMS/Orchard#7106]
Trying to move an orchard site to a new .net host.  I keep getting this message.  any thoughts on why I would be getting it?  the dependencies folder is not in the compiled site.  do I need to move up the un-compiled version?
Access to the path '\\WDP\DFS\30\0\3\4\3023676430\user\sites\5495667.site\www\App_Data\Dependencies' is denied.

**Comment by sebastienros** [comment]
You need to configure your hosting environment to allow write access to the account running your IIS process. It's part of the documented deployment instructions.
