### ISSUE TITLE
Taxonomies in orchard CMS

### ISSUE THREAD

**Issue by NBalouchi** [OrchardCMS/Orchard#7107]
In orchard CMS I have a taxonomies menu.I have added a alias breadcrumb menu.When I chose a taxonomy menu,the alias is correct.(Home->product->adidas->shoes) but when I click one of shoes post,the url is changed to(Home->shoes1). How can I fixed it to (Home->product->adidas->shoes->shoes1)?

**Comment by sebastienros** [comment]
I assume that's the goal of this class: https://github.com/OrchardCMS/Orchard/blob/e01e1ada2d197248c7cb80c96f280790b95a039b/src/Orchard.Web/Modules/Orchard.Alias/Navigation/NavigationAliasProvider.cs

Does the shoe url look like /products/adidas/shoes/shoes1 ? If it did we could have the feature render the breadcrumb for each parent segment.

**Comment by NBalouchi** [comment]
I use this pattern in autoroute of blog post {Content.Fields.BlogPost.Category.TermPathSlug}/{Content.Slug}.and it shows only products/adidas.not show the full path.How can Generate the full path?

**Comment by bleroy** [comment]
Seems like the problem with `{Content.Fields.BlogPost.Category.TermPathSlug}` would be that the `Category` field is multi-valued. You'd have to pick the first one before you get to the term's slug.

**Comment by sebastienros** [comment]
What categories have you selected for this blog post.
If you have several ones, then the solution is to add another field call "Main Category" and you use it in the autoroute pattern. Setting it to "Shoes" will then render to path you want.
