### ISSUE TITLE
ActivatingFilter with ContentPart using NodaTime breaks testing.

### ISSUE THREAD

**Issue by Xceno** [OrchardCMS/Orchard#7112]
Like the title says, this behaviour does only occur while running UnitTests.

I have a part like this, using [NodaTimes Instant type](http://nodatime.org/1.3.x/userguide/core-types.html):

```C#
public class EventPart : ContentPart
	{
		public Instant? FromUtc
		{
			get { return RetrieveInstant(this.Retrieve(r => r.FromUtc)); }
			set { this.Store(s => s.FromUtc, StoreInstant(value)); }
		}

        private static Instant? RetrieveInstant(DateTime? val)
		{
			return val.HasValue ? Instant.FromDateTimeUtc(val.Value) : default(Instant?);
		}

		private static DateTime? StoreInstant(Instant? val)
		{
			return val.HasValue ? val.Value.ToDateTimeUtc() : default(DateTime?);
		}
	}
```
Now everytime I attach this part in my mocked EventPartHandler, this happens:

![nodatimetesting bug](https://cloud.githubusercontent.com/assets/1850967/18381274/ccc5f138-767b-11e6-9ec8-67dd9fcd15b3.png)

I haven't found any reason why this happens yet. No exception gets thrown either, so I hope someone here has an idea.
This only occurs when using the `Store` and `Retrieve` getter and setter.

**Comment by sebastienros** [comment]
Probably as we try to store it in the InfoSet. You might be better using an intermediate field serialized to string or double in your Store/Retrieve calls, and have a property that is not serialized do the conversion between the Noda time object and your serialized value.

**Comment by Xceno** [comment]
I've accidentaly edited away too much. I actually convert the `Instant` to a `DateTime.`
In the meantime I've found a weird resolution:

First I've declared an interface and implemented it

```C#
public interface IMyEvent
{
    Instant? FromUtc { get; }
}

public class EventPart : ContentPart<EventRecord>, IMyEvent
{
    public Instant? FromUtc
    {
        get { return RetrieveInstant(this.Retrieve(r => r.FromUtc)); }
        set { this.Store(s => s.FromUtc, StoreInstant(value)); }
    }

    private static Instant? RetrieveInstant(DateTime? val)
    {
        return val.HasValue ? Instant.FromDateTimeUtc(val.Value) : default(Instant?);
    }

    private static DateTime? StoreInstant(Instant? val)
    {
        return val.HasValue ? val.Value.ToDateTimeUtc() : default(DateTime?);
    }
}
```

Then I've declared a mock FakeEventPart which implements this interface and just returns `null` for all `Instant ` properties, the setter is empty.

Now comes the thing I don't quite understand:
I left my mocked `EventPartHandler` with the original line by mistake but suddenly the issue was gone.

`this.Filters.Add(new ActivatingFilter<EventPart>(Core.Statics.ContentTypeNames.Event));`

Turns out that I just need my `FakeEventPart` to linger somewhere without ever actually using it.
So you might close this issue if you wish, but I'd really like to know what's going on here.
