### ISSUE TITLE
Error when create List in Orchard CMS 1.10.1

### ISSUE THREAD

**Issue by JeKachan** [OrchardCMS/Orchard#7114]
Hi comrades! I have some trouble with create list in Orchard CMS, follow instruction http://docs.orchardproject.net/en/latest/Documentation/Creating-lists/ I get source code from github (https://github.com/OrchardCMS/Orchard/releases/tag/1.10.1) and run in VS. Then I create new Content Type - Book Review and set him Containeble part. Then I enabled List module, and go to create list page from side bar admin panel and create Book Review List with reference to Book Review Content Type. Then I try to create Book Review, and when I click save I see exception message. If i disable List module then exception is gone, but i cant crete the list. What is this error? How can I avoid it? Or how can I create list in Orcahrd?
Exception image: https://api.monosnap.com/rpc/file/download?id=EslujUdhOAhTF4tAdJrMq8zEKDj8MK

**Comment by rtpHarry** [comment]
I think Lists was just a stop-gap feature which has been replaced by Orchard.Taxonomies and Orchard.Projections.

I would start here for a more up to date way to handle lists of things in Orchard:

  - http://www.ideliverable.com/blog/ways-to-render-lists-of-things

I actually thought it had be deprecated but it seems not.

**Comment by sfmskywalker** [comment]
It's not at all a stop gap feature, and serves a different purpose than Projections and Taxonomies. It's true that it was deprecated at some point, but has been revived and revamped.

**Comment by rtpHarry** [comment]
Ah ok, my bad :)

**Comment by JeKachan** [comment]
@rtpHarry thanks for link!
@sfmskywalker if List "deprecated" now, what should i used as alternative? Orchard.Taxonomies and Orchard.Projections? Or should I use an more older version?

**Comment by sfmskywalker** [comment]
Orchard.Lists is *not* deprecated. It was deprecated at some point, but then we updated and improved the module, after which it was declared to be no longer deprecated. Obviously we need to fix the error that you're running into.

**Comment by sebastienros** [comment]
Clearly the documentation is about the older version of the module. I think there is no bug on this module, 

Can you try that:
- Create a Book review content type
- Add Containable part to it
- Enable the List Module, and create a new List called Book reviews, without any custom type.
- Select Book review as the type to contain.

It should work, if it doesn't please reopen this issue.

**Comment by sebastienros** [comment]
We even have functional tests for the feature: https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Specs/Lists.feature

**Comment by JeKachan** [comment]
@sebastienros I did as you said. Unfortunately the error is still displayed.
