### ISSUE TITLE
Orchard.Setup - Blog setup recipe has broken Pages feature + other issues

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7115]
The "blog" setup recipe contains a Page content type still but there is no BodyPart or LayoutPart:

![image](https://cloud.githubusercontent.com/assets/1038062/18453271/5e97e0dc-7936-11e6-852a-e222a00d75b9.png)

I think it should have Orchard.Layouts woven in to its recipe.

Personally I think it should also include Content Definitions (Orchard.ContentTypes) on as default as you are likely going to want to mess around with your BlogPost content type as a blog site.

It will also want the Tripel widgets removing from the commands step.

The `<Settings>` section should be reviewed as well. Are they now redundant or should they be on the default setup recipe as well?

**Comment by sebastienros** [comment]
It should have the LayoutPart, like the core recipe.
If Default has Content Definitions then lets add it too.
And remove the widgets, maybe add some blog related ones instead, Archives, Tags, Recent Blog Post.
Don't change the settings.

**Comment by rtpHarry** [comment]
Note for me: If ContentTypes is on then Orchard.Fields should be added to blog recipe as well. 

Review other list of features for common sense ones missing.

**Comment by rtpHarry** [comment]
I've fixed the recipe up. It looks pretty stupid but its got all the moving parts in place:

![image](https://cloud.githubusercontent.com/assets/1038062/18963052/317c069a-866b-11e6-95de-28ae4141c7bd.png)

I think fixing the rest of the problems are separate issues to this one though:

 - Add create blogpost command
 - Add "empty data" view to all three sidebar widgets

I'll raise them separately.
