### ISSUE TITLE
Media Library Picker Field not working in 1.10.1

### ISSUE THREAD

**Issue by GioviQ** [OrchardCMS/Orchard#7117]
I am updating tenants from 1.9 to 1.10.1 and media library picker field previously created are working and in admin I see
![risparmio dindini modifica il tipo di contenuto blog post](https://cloud.githubusercontent.com/assets/7103057/18490301/aa5441d4-7a01-11e6-8025-147333a9e7ad.png)

Then I created a new tenant from zero, but when I add media library picker fields they do not show and in admin section you see
![modifica il tipo di contenuto blog post quarella net](https://cloud.githubusercontent.com/assets/7103057/18490359/e41e1750-7a01-11e6-8a60-64f4f86fbf2f.png)
You can not expand the field, so something goes wrong, but the logs are empty.
What is going on?

**Comment by rtpHarry** [comment]
Its strange that there is an extra space after the name `(Media Library Picker Field )` in the second screenshot.

**Comment by GioviQ** [comment]
Thank you, I did not note that. I am going to investigate.

**Comment by GioviQ** [comment]
I fixed it!
In a migration of a custom module there was a typo: OfType("MediaLibraryPickerField ")
Then I remove the extra space in Settings_ContentFieldDefinitionRecord too.
