### ISSUE TITLE
Orchard.MediaLibrary - Web Search with Bing API needs attention before Dec 16 2016

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7118]
Just noticed on the [Bing API website](http://datamarket.azure.com/dataset/bing/search) this message:

> TO CONTINUE USAGE AFTER DECEMBER 15, 2016
> The Azure Marketplace "Bing Search" and "Bing Search Web Results Only" API offerings will end of life on December 15, 2016. New Cognitive Services Bing Search API is available for purchase through Azure.com. Upgrade is easy. For the migration guide click [Here](https://msdn.microsoft.com/en-US/library/mt707570.aspx).

It looks like the endpoint and various field names have been altered between v2 and v5.

**Comment by rtpHarry** [comment]
## Azure Cognitive Services
Looking at this new Azure version it seems there is no free tier any more:

![image](https://cloud.githubusercontent.com/assets/1038062/18495354/37056dde-7a15-11e6-864a-28d7b2353563.png)

## Pixabay
I was actually looking into the module because I had just realised Pixabay has a [free to use API](https://pixabay.com/api/docs/) for up to 5000 requests a day. 

These could potentially be a better future for this feature as the Bing Search API returns copyright protected images and I have seen clients get into trouble before for grabbing images straight out of Google/Bing image search and using them in commercial situations. 

All of the Pixabay images are released under Creative Commons CC0, which means free to use images.

**Comment by sebastienros** [comment]
Maybe think about removing the API altogether. And have it as an external module.

**Comment by rtpHarry** [comment]
Yeah thats why I was originally poking around in the code, to see if the media source was pluggable.

It's baked in at the moment so would need a small amount of re-architecturing but I think it is more of an extension point than a core feature.

**Comment by BenedekFarkas** [comment]
@I3undy is working on this.

**Comment by BenedekFarkas** [comment]
@sebastienros we've got some small adjustments in the works (we'll have a new PR for that) and we'll demo the feature in the meeting on the 16th.
