### ISSUE TITLE
Orchard.ContentTypes - Add / Edit Field Issues

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7131]
1. The fields are both being validated twice
 1. The fields UI doesn't have the required * on them
 1. There is no cancel button

![image](https://cloud.githubusercontent.com/assets/1038062/18609701/6f6f1b50-7d00-11e6-93f7-88dbea2cff74.png)

Same issues with Edit Field:

![image](https://cloud.githubusercontent.com/assets/1038062/18609708/bd194e16-7d00-11e6-9156-ca6566e94855.png)

**Comment by sebastienros** [comment]
We should have controller validation only, just for Localization purpose.
