### ISSUE TITLE
RecipeJournal Folder in media library (1.10.1)

### ISSUE THREAD

**Issue by GioviQ** [OrchardCMS/Orchard#7135]
Why do I see RecipeJournal folder in media library?
![www muscoli info admin orchard medialibrary folderpath immagini](https://cloud.githubusercontent.com/assets/7103057/18613283/d490458c-7d77-11e6-9764-d82ae4d13f6a.png)

**Comment by sebastienros** [comment]
It should be filtered.

**Comment by DanielStolt** [comment]
The recipe journal filter should not even exist on a 1.10.1 install, as the recipe journal was removed from Orchard. Is this site an upgrade from an earlier version, with the Media folder contents migrated?
