### ISSUE TITLE
Orchard Content Pages

### ISSUE THREAD

**Issue by thierholzer** [OrchardCMS/Orchard#7138]
I can't edit any of my content pages on any of my tenants...After walking through the error I get a null sessionstate in Orchard.Layouts ElementController. Any thoughts on what could be causing this?

I recently upgraded to 1.10 from 1.9

An unhandled exception has occurred and the request was terminated. Please refresh the page. If the error persists, go back
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object. at Orchard.Layouts.Controllers.ElementController.Edit(String session) at lambda_method(Closure , ControllerBase , Object[] ) at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

**Comment by sfmskywalker** [comment]
Looks like the Session expired, which is used to transfer data from and to the element editor dialog. Refreshing the page should fix it (make sure to save any changes first!).

**Comment by rtpHarry** [comment]
You might be pushing over the limit of memory and causing the appdomain to recycle. Are you on decent hosting or some budget package? 

I have one client where I have to do my editing locally and then publish the changes because i continually get logged out trying to make edits on the server.

**Comment by thierholzer** [comment]
Yea that might be it...I'm able to edit locally, so maybe that is my issue. I'll do some research into that. Thanks.
