### ISSUE TITLE
Missing ability to redirect to content item from Orchard.Users.

### ISSUE THREAD

**Issue by judgestone** [OrchardCMS/Orchard#7141]
Missing the ability to redirect back to an admin content item from Admin-User-Edit using redirectUrl in querystring.  
Orchard.Users module has an alternate for Content.Edit.cshtml shape (Content-User.Edit.cshtml) which does not included the following: 

`@if (!String.IsNullOrWhiteSpace(Request.QueryString["returnUrl"])) {
    @Html.Hidden("returnUrl", Request.QueryString["returnUrl"])
}`

**Comment by judgestone** [comment]
Is it viable to remove the Orchard.Users alternate 'Content-User.Edit.cshtml'?
Or should the above line be simply added to the 'Content-User.Edit.cshtml' alternate?

**Comment by rtpHarry** [comment]
Out of the two choices I think the line should be added. The alternate view has a different layout to its original, I'm not sure what it's for though as it is structurally quite similar.

However, this is just masking the real issue. As mentioned in #3447 the return url should be in the querystring. 

There are some helper methods around here somewhere that create these for you automatically I think. 

Something like this: https://github.com/OrchardCMS/OrchardDoc/issues/250

**Comment by judgestone** [comment]
Thanks rptHarry for the reply.  I agree that the second choice is less invasive and is more than likely the way to go.  When viewing the two different files there was very little difference and I wondered was this simple something that was left over from an older version of the system.  In which case removing the file altogether would be the way to go.

Regards providing the URL in the querystring, I am already doing this using the helper @Html.ItemEditLinkWithReturnUrl(T("Edit").Text, contentItem).  The issue is that without the hidden returnUrl html field the querystring is not carried over when saving the content item.
