### ISSUE TITLE
Orchard.Framework - Using GroupInfo() class generates urls with spaces in it

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7155]
The [GroupInfo](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/ContentManagement/GroupInfo.cs) class is used to represent a settings part in the menu.

If the settings part has a space in the name then the url does too:

    context.Metadata.EditorGroupInfo.Add(new GroupInfo(T("Audit Trail")));

Results in `/Admin/Settings/Audit Trail/` which works but isn't correct.

From my simple testing [.HtmlClassify()](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Utility/Extensions/StringExtensions.cs#L58) seems to create a better url. 

Is there a more appropriate helper method tucked away somewhere in Orchard? If not I will create a PR.

**Comment by sebastienros** [comment]
Question is whatever the encoding is, how will the route be matched back.

**Comment by rtpHarry** [comment]
I didn't understand this comment in the triage. Under the hood the class uses the `.ID` but just gets it from the supplied name, which can have spaces:

        public GroupInfo(LocalizedString name) {
            Id = name.TextHint;
            Name = name;
        }

In my shape tracing modification I do this to combat the space in the url:

            var groupInfo = new GroupInfo(T("Shape Tracing"));
            groupInfo.Id = "ShapeTracing";

And the url is just `/Admin/Settings/ShapeTracing`. However, to automate I'm suggesting:

        public GroupInfo(LocalizedString name) {
            Id = name.Text.HtmlClassify();
            Name = name;
        }

Which makes the Name "Shape Tracing" into `/Admin/Settings/shape-tracing`.

So all of the other admin urls will go lower case and dashes, etc, but they will be valid css class format so therefore valid urls. Nobody should be linking directly to the settings pages anyway, they should be using url helpers but even if they do any single words will still work as windows urls aren't case sensitive.

**Comment by rtpHarry** [comment]
## Side question - Whats the reason for this?
It seems that modules use two different ways to add their entries to the settings menu:

  1. Creating a `GroupInfo` class instance and registering it as part of a SettingsPartHandler in the GetItemMetadata() for example:

        protected override void GetItemMetadata(GetContentItemMetadataContext context) {
            if (context.ContentItem.ContentType != "Site")
                return;
            base.GetItemMetadata(context);
            context.Metadata.EditorGroupInfo.Add(new GroupInfo(T("Search")));
        }
  1. Using the AdminMenu.cs method:

        public void GetNavigation(NavigationBuilder builder) {
            builder.Add(T("Settings"),
                menu => menu.Add(T("Indexes"), "5", item => item.Action("Index", "Admin", new {area = "Orchard.Indexing"})
                        .Permission(StandardPermissions.SiteOwner)));
        }

The menu is technically being managed by the Orchard.Settings module with the GroupInfo mechanism but then other modules are pushing their way in with the AdminMenu.cs approach.

It seems the GroupInfo solution is redundant as you cannot add sub menus and localnav with it but AdminMenu you can.
