### ISSUE TITLE
How to make "AutoroutePart" settings in Migrations.cs

### ISSUE THREAD

**Issue by happydaily** [OrchardCMS/Orchard#7159]
I want to use Patterns: 
name:book/id
Pattern:book/{Content.Id}
in AutoroutePart,but I dont know how to do this in Migrations.cs

**Comment by sfmskywalker** [comment]
Hi happydaily, you reached our GitHub project where we use issues to track bugs and feature requests. Kindly use our forum at https://orchard.codeplex.com or http://orchardpros.net to ask questions.

Thanks
