### ISSUE TITLE
Feature - Orchard.DeveloperTools - Add toggle from front end

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7162]
When I'm developing a site sometimes I will want the shape tracer on and sometimes I will want to work on the css / html with a clean view.

Adding a button to activate and deactivate the shape tracer from its front end ui makes this process a lot quicker.

The idea behind the feature is to allow quick toggling while developing, you would still disable the module at the end of development as you normally would.

## New settings tab
In the editor there is a new tab which lets you deactivate the shape tracer:

![image](https://cloud.githubusercontent.com/assets/1038062/18933365/5330ffce-85cc-11e6-96d7-bad55674b76c.png)

The page reloads and the page no longer has all the wrappers cluttering up the html markup.

You can quickly re-activate it when you need it again by clicking the activate button in the front end:

![image](https://cloud.githubusercontent.com/assets/1038062/18933438/ad9b552c-85cc-11e6-9519-f95d8450a6f4.png)

## Admin panel settings
You can also edit the setting in the new Shape Tracing section of the settings panel:

![image](https://cloud.githubusercontent.com/assets/1038062/18933404/7b7a0de0-85cc-11e6-9b2d-967739d6a70b.png)

![image](https://cloud.githubusercontent.com/assets/1038062/18933410/831cf468-85cc-11e6-87ce-d923b8e2418a.png)

## Visual amendments
The toolbar along the top "toolbar" has been given additional height for modern displays:

![image](https://cloud.githubusercontent.com/assets/1038062/18933490/fbe00994-85cc-11e6-8794-1a2ecb9563e7.png)

A notifier has been added which lets you see at-a-glance if the system is currently active:

![image](https://cloud.githubusercontent.com/assets/1038062/18933508/0c80813e-85cd-11e6-9543-53a432ad3b9a.png)

![image](https://cloud.githubusercontent.com/assets/1038062/18933523/19ebf60a-85cd-11e6-9fcf-3be933064f96.png)

The menu toggle button has been remade in CSS, better supporting modern high pixel density displays:

![image](https://cloud.githubusercontent.com/assets/1038062/18933533/2302fbd0-85cd-11e6-809a-21e08034780b.png) ![image](https://cloud.githubusercontent.com/assets/1038062/18933543/2db4b35c-85cd-11e6-813c-62b4359c977b.png)

## Enhanced click zone

The entire top bar is now a click zone to toggle the panel up and down:

![image](https://cloud.githubusercontent.com/assets/1038062/18933587/71ac9eee-85cd-11e6-96ff-91a5f488195c.png)

## Automatic re-enable

Each time the module itself is enabled the active setting is also reset so that it turns on:

![image](https://cloud.githubusercontent.com/assets/1038062/18933606/88973312-85cd-11e6-8f4c-544c9a2a9e07.png)

Less confusion for users who disabled the module while the feature was deactivated as well.

## Further feature ideas
These are the remaining items on the todo list for future enhancements, I welcome any feedback:

  - Review - ShapeTracingFactory.cs - Created() - Is it expensive / being run still when deactivated?
  - Review security around allowing shape tracing enable from UI
  - Add layer rule / conditions support
  - Add option to enable shape tracer to be used against the admin panel theme
  - Apply assets.json gulp pipeline support
  - Does it need import / export now?

**Comment by carlwoodhouse** [comment]
neat :)
