### ISSUE TITLE
MediaLibraryPickerField Can't select multiple images

### ISSUE THREAD

**Issue by brookeRIT** [OrchardCMS/Orchard#7164]
Installed the MediaLibraryPickerField per http://docs.orchardproject.net/en/latest/Documentation/Creating-an-image-gallery/

Not able to select more than one image at a time with the control key.

**Comment by rtpHarry** [comment]
Are you sure you ticked the "allow multiple content items" and also then clicked save at the end?

![image](https://cloud.githubusercontent.com/assets/1038062/18935197/6aba871e-85d6-11e6-9e1e-9a9f0d61e6e8.png)

**Comment by brookeRIT** [comment]
Yes, that option is selected. I am able to add more than one image, but only one at a time.

The "Tip: Use ctrl + click to select multiple images at once" is not working for me. I am using a Mac.
