### ISSUE TITLE
Orchard.Tags.TagsCloud - TagsCloud widget should have a "no data" view

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7170]
The blog setup recipe creates a BlogArchives widget in the sidebar but it doesn't have any content.

New users to the platform could easily believe something has gone wrong with the setup.

![image](https://cloud.githubusercontent.com/assets/1038062/18965622/dfbe1aa4-8675-11e6-85a4-2a7b9d619845.png)

**Comment by sebastienros** [comment]
Just add a "There are no blog posts" or something like this. Steal wording from wordpress without giving any credits ;)

**Comment by rtpHarry** [comment]
![image](https://cloud.githubusercontent.com/assets/1038062/19094502/4e50fbec-8a88-11e6-9dbe-29982b46e9a7.png)
