### ISSUE TITLE
Orchard.Blogs - Blog meta data should be hidden by default

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7171]
This is a container type and I don't think anyone really cares when the blog was created within the site, its the blog posts they are there to see.

The only purpose it serves is that it is the first thing most people new to the platform want to hide so they learn what placements.info are.

![image](https://cloud.githubusercontent.com/assets/1038062/18965923/1890e392-8677-11e6-9a00-f48bdb1e3ca7.png)

**Comment by sebastienros** [comment]
Dev branch because breaking change

**Comment by rtpHarry** [comment]
![image](https://cloud.githubusercontent.com/assets/1038062/19092841/8a8af4a8-8a80-11e6-92e2-f8d9b80d0dac.png)
