### ISSUE TITLE
Feature - admin-theme - rtl - Header Column Texts Should be positioned right

### ISSUE THREAD

**Issue by hpanahloo** [OrchardCMS/Orchard#7174]
This issue appears on all the tables in admin-theme in cultures with rtl direction.
Like these pages:
- /OrchardLocal/Admin/ContentTypes
![issue1](https://cloud.githubusercontent.com/assets/12455980/19001577/a91cc9e8-8754-11e6-948f-99ab0a2d27dd.jpg)

- /OrchardLocal/Admin/ContentTypes/ListParts
- ...

**Comment by sebastienros** [comment]
Awesome, thanks!

**Comment by hpanahloo** [comment]
no problem :)

**Comment by Skrypt** [comment]
Fixed some of those

**Comment by Skrypt** [comment]
Fixed
