### ISSUE TITLE
Feature - admin-theme - rtl - In Navigation Edit Add buttons not positioned correctly

### ISSUE THREAD

**Issue by hpanahloo** [OrchardCMS/Orchard#7175]
This issue appears on Navigation Edit page in admin-theme in cultures with rtl direction.
![issue2](https://cloud.githubusercontent.com/assets/12455980/19002166/9aa2cf72-8757-11e6-82fe-87ecf9d2efe9.jpg)

**Comment by Skrypt** [comment]
fixed
