### ISSUE TITLE
Feature - admin-theme - rtl - Sidebar in workflow Edit Page has some positioning issues

### ISSUE THREAD

**Issue by hpanahloo** [OrchardCMS/Orchard#7177]
This issue appears on workflow edit page in admin-theme in cultures with rtl direction.
- /OrchardLocal/Admin/Workflows/Edit/1

Icons should be in right side. And also there is an extra space in sidebar that shouldnt be there.
![issue4](https://cloud.githubusercontent.com/assets/12455980/19003205/af0aed14-875c-11e6-9f74-a7d95e07d1d4.jpg)

**Comment by Skrypt** [comment]
fixed
