### ISSUE TITLE
Admin Theme - Modules - Module title looks like should be on same row

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7180]
Spacings are there but not floated onto same row:

![image](https://cloud.githubusercontent.com/assets/1038062/19006792/66033ca0-8759-11e6-85a3-c973fb5ea9ee.png)

![image](https://cloud.githubusercontent.com/assets/1038062/19006796/731e6e64-8759-11e6-8a9e-9c880e479b2d.png)

**Comment by rtpHarry** [comment]
Nice and cosy:
![image](https://cloud.githubusercontent.com/assets/1038062/19015338/8ca6c45c-87fa-11e6-9c2e-54d288c80c24.png)

**Comment by Skrypt** [comment]
Something broke it! It was on the same line when I did it. :)

**Comment by sfmskywalker** [comment]
Perhaps one of the robots broke it. ;)

**Comment by Skrypt** [comment]
Probably Bender ... he drinks too much
