### ISSUE TITLE
Orchard.Tags - Manage Tags Admin Page Not Alpha Sorted

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7192]
![image](https://cloud.githubusercontent.com/assets/1038062/19008690/e352cf44-8764-11e6-87e5-5ff0356395a6.png)

Not a big deal for a few but wouldn't be manageable with a big site.

New admin shown but valid for old admin as well.

**Comment by rtpHarry** [comment]
@Skrypt this isn't admin tag either

**Comment by Skrypt** [comment]
Are you planning making a lot of pull requests this week-end ?

**Comment by rtpHarry** [comment]
Yep haha, im going to bed now for a fresh start tomorrow to clear some of my backlog :)
