### ISSUE TITLE
Orchard.Taxonomies - Admin Theme - Empty taxonomies view needs full stop

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7193]
![image](https://cloud.githubusercontent.com/assets/1038062/19007163/61da55b2-875b-11e6-9477-9ba69f1a7f5c.png)

Minor typo, will need dev target.

**Comment by rtpHarry** [comment]
this isn't an admin one either, technically, just a typo in the actual module

**Comment by Skrypt** [comment]
I see the new admin theme and I presume it is 😉

**Comment by rtpHarry** [comment]
yeah haha well most of them were admin! :)

**Comment by rtpHarry** [comment]
actually this is only in the new admin, oops
