### ISSUE TITLE
Admin Theme - Delete Confirm Message Appears Twice

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7194]
At the end of admin layout.cshtml the old confirm is still in there because base.js uses it. 

  - Base.js should be upgraded to the new system (attribute based at top of admin layout.cshtml).

  - Old var confirm message should JS should be removed (from end of new admin theme layout.cshtml).

**Comment by Skrypt** [comment]
I'll look back at this one because I kept both for backward compatibility purpose. What happens if someone install an old module and that it needs to use the old confirm message box ?

**Comment by rtpHarry** [comment]
In theory it should still work. That variable was just the default message that was used if the module **didn't** supply any custom message.

As a module developer if you wanted to use the message box you would have set the UnsafeUrl attribute or something like that (not at my dev computer right now). Then I came along and noticed the message wasn't correct for some scenarios and Seb + myself implemented this solution.

The solution was to optionally check the UnsafeUrl tagged link for a `data-message="whatever you want to ask"` and use that message instead. If it didn't have that attribute it would pull the message in from that confirmdelete variable in the footer of the layout.cshtml.

**Comment by rtpHarry** [comment]
This is where that variable came into existence: https://github.com/OrchardCMS/Orchard/pull/5827

**Comment by Skrypt** [comment]
I was just worried that it would override what I did for backward compatibility. If it still work it's all good. 👍 😄
