### ISSUE TITLE
Admin Theme - Side Menu - Dead zone in menu

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7196]
If I don't move fast enough the hover menu disappears when im over the dark bit (scroll bar):

![image](https://cloud.githubusercontent.com/assets/1038062/19008958/2fc12b3a-8767-11e6-8f58-f8e5eff79da3.png)

In Chrome Version 53.0.2785.116 m (64-bit).

Not sure if the scroll bar is provided by the system or if its an element that. I think the solution could be to add a hover-off delay?

**Comment by sfmskywalker** [comment]
If you find a fix for this, please provide it here so we can communicate it back to FoxyThemes. Thanks!

**Comment by rtpHarry** [comment]
I was thinking of this script when I said about the hover-off delay. I haven't looked into the issue though I just wanted to note it while I remembered:

http://cherne.net/brian/resources/jquery.hoverIntent.html

**Comment by rtpHarry** [comment]
We are removing this menu so its no longer relevant.
