### ISSUE TITLE
Admin Theme - Media Library - Typos In Msgs

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7207]
![image](https://cloud.githubusercontent.com/assets/1038062/19015032/e099a7b6-87f3-11e6-9148-bff800e68ce1.png)

in `.\admin\index.cshtml`

remove spaces

also check - is the plural delete msg shown on single image delete?

**Comment by sebastienros** [comment]
I think we should keep the plural on `delete`

**Comment by Skrypt** [comment]
Not sure why but my comments on pull requests don't close issues.

**Comment by rtpHarry** [comment]
Nothing to worry about, its not personal to you. Github doesn't auto close them until they get merged into the main branch (dev in this repo)

**Comment by Skrypt** [comment]
Ah! That's why 😄
