### ISSUE TITLE
Update Json.NET

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#7213]
Only in dev as it might be a breaking change, and also add a binding redirect to prevent any conflict with other modules.

**Comment by dalenewman** [comment]
When creating custom modules, I run into problems using libraries that reference a different major version of Json.Net then Orchard (e.g. [NEST](https://www.nuget.org/packages/NEST/1.9.1) uses 9-10 while Orchard uses 7).

While updating Orchard's dependency helps temporarily, I wonder if there is another way to fix this?  Is it bad practice to include the Json.NET source in Orchard (in another name space) so it would not conflict with any other library's use of it?  Or, is there another option (e.g. designing an interface for JSON services and being able to change it in Orchard)?

Thanks for everything you do!

**Comment by sebastienros** [comment]
A single binding redirect with the version you want to force in the main web.config should fix all the conflicts.
