### ISSUE TITLE
Admin Theme - Feature Request - Show if part has no properties

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7214]
Every item has the `>` now to show a description for its part. In the old admin theme only parts that are configurable would have the chevron. 

Can we add a visual clue for when the part has nothing to configure? Perhaps just make the chevron bold on items with properties that can be configured.

![image](https://cloud.githubusercontent.com/assets/1038062/19016466/799b7d22-8812-11e6-9926-dc148fc44530.png)

**Comment by Skrypt** [comment]
fixed
