### ISSUE TITLE
Admin Theme - Edit ContentType - Add Field Not Working

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7215]
Form lets me add fields but UI is not displaying them:

![image](https://cloud.githubusercontent.com/assets/1038062/19016473/d08d4cc8-8812-11e6-8dae-fd69913e4977.png)

This is the blog type and I've added three fields (of varying types) to it.

**Comment by rtpHarry** [comment]
## Further investigation
If I add fields to the `Page` content type then it works ok.

If I go to edit the Content PART - BlogPart I can see all the fields I created inside that.

BlogPart exists normally and is a part on the Blog content type. New fields are added in a hidden part with the same name as the type normally aren't they? 

Is this a bug in Orchard? It only fails when trying to add fields to a type that already has a part with the same name eg: Blog type to BlogPart part.

**Comment by rtpHarry** [comment]
I checked, it's not a bug in the main Orchard, so something is being pointed wrong in the admin theme.

**Comment by Skrypt** [comment]
Strange I just tested it after merging latest changes on my side and the fields gets added properly.

**Comment by Skrypt** [comment]
Please provide me with repro's because I've not been able to reproduce this bug.

**Comment by Skrypt** [comment]
@rtpHarry Can we close this one ?

**Comment by rtpHarry** [comment]
Yes I don't know what was causing it, I guess it was something to do with switching between branches without resetting the database. It's not happening for me anymore.
