### ISSUE TITLE
non-breaking hyphen &#8209; in culture links

### ISSUE THREAD

**Issue by GioviQ** [OrchardCMS/Orchard#7222]
As you can see here 

![coevolution of sites and search engines quarella net](https://cloud.githubusercontent.com/assets/7103057/19019586/355b11ba-888d-11e6-9be2-18a0fbd4bc7a.png)
 
non-breaking hyphen is not used in culture links.

**Comment by sebastienros** [comment]
We are just rendering the string value of the culture, from the .NET framework. This can be solved with CSS.
