### ISSUE TITLE
Can containable item be contained by many content item?

### ISSUE THREAD

**Issue by li0803** [OrchardCMS/Orchard#7227]
Here is the sample requriement: I got many classes under Class content type and many students under Student content type. One student can book some of classes.

Here is what I done and the problem I am encountering: I set the Class content type is containable and Student content type has Container part. But one class only can be contained by one student. Once the same class is booked by many students. It only appear under the list of the student who is the last one to operate the book action.

Here is what I expect to: One class can be contained by many students.

Any clue to find the path?

Thanks

**Comment by sebastienros** [comment]
This can't be done with Containable, you should use Taxonomies instead. Classes is a taxonomy, each class is a Term, and you create a Taxonomy field in the Student type. You can also add custom fields to the Class terms.
