### ISSUE TITLE
Admin Theme: javascript error when mouse over on Queries menu

### ISSUE THREAD

**Issue by ifle** [OrchardCMS/Orchard#7229]
Mouse over on Query menu cause to following error : "Syntax error, unrecognized expression: unsupported pseudo: hover". Tested on IE11, latest Chrome

**Comment by sfmskywalker** [comment]
This was recently fixed. Perhaps you need to clear your browser cache?

**Comment by ifle** [comment]
You are right. On IE a clearing is fixed, but on Chrome it still occurred.

**Comment by ifle** [comment]
My mistake. You can close this is issue. I had not the latest version. With resent cheages this is error is not occurred.

**Comment by sfmskywalker** [comment]
No worries, glad to hear it's a non issue. Also, thanks a lot for your reporting the RTL issues!
