### ISSUE TITLE
Admin Theme - RTL : There is extra padding in the first local nav tab

### ISSUE THREAD

**Issue by ifle** [OrchardCMS/Orchard#7232]
![orchard-rtl-issue3](https://cloud.githubusercontent.com/assets/1140474/19064797/3790b44e-8a18-11e6-8a13-d8930a0495e6.jpg)

**Comment by sebastienros** [comment]
If it's decided to fix it on RTL, it should be the same on LTR.

**Comment by rtpHarry** [comment]
Yes it looks like this on ltr, so it does need fixing:

![image](https://cloud.githubusercontent.com/assets/1038062/19172742/58685802-8c1b-11e6-9732-84d3e345c334.png)

**Comment by Skrypt** [comment]
fixed
