### ISSUE TITLE
Admin Theme: Admin menu is clipped. The scroller is missing

### ISSUE THREAD

**Issue by ifle** [OrchardCMS/Orchard#7233]
![orchard-rtl-issue4](https://cloud.githubusercontent.com/assets/1140474/19064930/2dd7405c-8a19-11e6-9400-60023a3b841d.jpg)

**Comment by sfmskywalker** [comment]
Does this happen on all browsers?

**Comment by ifle** [comment]
I've checked on IE11 and Chrome

**Comment by Skrypt** [comment]
Could be a javascript error happening before calling the scrollbar javascript. This can happen when there is an error on the view since it won't render all the HTML on the page. Specially when we include javascript in the bottom of the views.

**Comment by Skrypt** [comment]
Please provide repro. I'm looking at it in Chrome, Edge and Firefox and it looks fine.

**Comment by sfmskywalker** [comment]
Perhaps a browser cache issue (either on the OP or on Jasmin)?

**Comment by ifle** [comment]
Sorry. This is not browser cache issue. I've rechecked again on chrome and still have scroll issues. 
![orchard-issue_scroll](https://cloud.githubusercontent.com/assets/1140474/19179822/cc589a4e-8c69-11e6-9186-5a897a1b21d6.jpg)

**Comment by Skrypt** [comment]
Can you give me the details about your OS and Chrome version ?

**Comment by ifle** [comment]
Chrome : Version 53.0.2785.143 m
OS : Windows 10 pro, 64

**Comment by rtpHarry** [comment]
if you hover your mouse over it and scroll your mouse wheel does the menu scroll? does the scrollbar appear then?

**Comment by ifle** [comment]
Yes, the does menu scroll, but the scrollbar does not appeared.

**Comment by ramiassi** [comment]
I'm using the laptop's touch pad. I need a scrollbar in the side menu to scroll down to the bottom items.

**Comment by rtpHarry** [comment]
@ramiassi yes that one is a known issue, it's on the master list to be resolved before the admin theme goes live

**Comment by ramiassi** [comment]
Thanks @rtpHarry

**Comment by Skrypt** [comment]
Actually I don't think we can fix this one if we intend to keep the nanoScroller plugin. It is by design like that. Do we want to have larger scrollbars ? I think the nanoScroller is used there for a reason. To make this look better. Then, if we need to have this working for a laptop keypad then I think the problem is that the keypad needs to have gesture enabled. Here an instruction example for a Dell laptop : 
https://www.youtube.com/watch?v=GaPOD_dTPmc
Then the keypad should be able to scroll the menu.

**Comment by Skrypt** [comment]
Tested on my Dell laptop. Keypad over the menu and after that 2 fingers on the keypad for scrolling up or down...

**Comment by Skrypt** [comment]
Please discuss about it on that thread for further development on the subject. #7262
