### ISSUE TITLE
On tenant restart, the cache entries are not refreshed

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#7240]
try to reproduce

/cc @hannan-azam

**Comment by hannan-azam** [comment]
@sebastienros i reproduced the error and found two issues with Output Cache. Following are the steps. 
Note: OutputCache and ImportExport should be enabled. Set Default Cache Duration to some longer period of time like one hour etc.

I am also attaching two Recipes. [Recipe1](https://github.com/OrchardCMS/Orchard/files/513883/Recipe1.txt) [Recipe2](https://github.com/OrchardCMS/Orchard/files/513884/Recipe2.txt)
Recipe1 imports a test page of type Page and a html widget in Default Layer.
Recipe2 modifies the content of html widget and appends a string "12345" in its content

**Issue 1: On Import of recipe UpdateShell restarts the tenant which expires the TagCache but the OutputCache doesn't expire**
1. Evict all cache in Output cache
2. Import the recipe "Recipe1". A new page will be imported with url **/test-page**
3. In anonymous mode request the page /test-page through browser to create a cache entry
4. Ensure that the widget content is displayed on page and that a cache entry is created in Output Cache.
5. Import the recipe "Recipe2". It will modify the widget content and append "12345" in its content
6. In anonymous mode again request the page /test-page It will still show the old widget content where as it should show the fresh content.
**Possible Solution:** Implement IShellDescriptorManagerEventHandler in Orchard.OutputCache. On Changed event, remove all cache for that specific tenant.


**Issue 2: Removing the item doesn't expire OutputCache**
1. Remove the item.
2. OutputCache entry is still visible in Admin utility
**Possible Solution:** Implement OnRemoved<IContent> and OnDestroyed<IContent> event and remove cache for that specific content.

**Comment by sebastienros** [comment]
I think I understand, the default cache provider uses `HttpContext.Cache` to store the entries, hence they are not released. This could be seen as a feature too, so probably the solution is to store the tags in the same medium.

For the second issue I filed a separate bug.
