### ISSUE TITLE
Admin Theme - web.config compilation targetFramework="4.5.1"

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7243]
Noticed this in the web.config for the new admin theme:

![image](https://cloud.githubusercontent.com/assets/1038062/19093568/87f0bbd0-8a83-11e6-89e1-49f3fc2562f3.png)

But the version numbers are out of date. 

Not sure if this is honored and could cause issues? Project is targeted at 4.5.2.

**Comment by sfmskywalker** [comment]
What are the current assembly version numbers for the various assemblies listed above? If there are newer versions, I think we should apply them.
