### ISSUE TITLE
Label for bad pull requests

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [OrchardCMS/Orchard#7250]
Hi there,

is it possible to create a label for bad pull requests? I think it would improve the overview of closed pull request. Currently i have a prefix `[Bad PR]` in the title of my pull requests to immediatelly see why it is a closed PR but this is a bit ugly imho.

So lonG

**Comment by sebastienros** [comment]
What is a "Bad PR" ?
It doesn't show up anymore if it's closed, you shouldn't see it.

**Comment by ViRuSTriNiTy** [comment]
A bad PR is a PR with merge issues for example (like https://github.com/OrchardCMS/Orchard/pull/6988)

When filtering the PR tab for "is:pr author:ViRuSTriNiTy is:closed" then all PRs would be displayed as "closed" and i have to click on each PR to see why it has been closed.

I was basically going through all my issues and PRs to see what's still pending and i got a bit confused with all the issue / pr numbers, comments and stuff. So i thought a Bad PR label would be a good idea.

**Comment by sebastienros** [comment]
Too much administrative work, that if not done consistently would be useless, for the little use people would have. Feel free to join us during a triage meeting to talk about it or see how we take handle the PRs.

**Comment by ViRuSTriNiTy** [comment]
Ok, i agree, too much administrative work, i will stick to the prefix then.
