### ISSUE TITLE
Orchard.Setup - Blog recipe doesn't create widgets correctly

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7251]
I thought #7169 and friends would be simple issues but they have caught me out.

My [blog recipe](https://github.com/OrchardCMS/Orchard/pull/7166) doesn't actually work as intended. I checked the admin after it had run and the UI showed the widgets (Archives, Recent) with the correct blog selected but this was just because that was the only value in the list. The actual `BlogId` on the part is `0` which means when posts are added it doesn't list them.

I can't see any way to pass a blog id in through the `widget create RecentBlogPosts` command.

I'm thinking instead I should catch the blog id being 0 and attempt to set a sensible default in `RecentBlogPostsPartHandler.cs` for example:

    using Orchard.Blogs.Models;
    using Orchard.Blogs.Services;
    using Orchard.ContentManagement.Handlers;
    using Orchard.Data;

    namespace Orchard.Blogs.Handlers {
        public class RecentBlogPostsPartHandler : ContentHandler {
            public RecentBlogPostsPartHandler(
                IRepository<RecentBlogPostsPartRecord> repository,
                BlogService blogService) {

                Filters.Add(StorageFilter.For(repository));
            
                OnCreated<RecentBlogPostsPart>((context, part) => {
                    // If the part.BlogId = 0 then assume its being created via a command (ui shouldn't allow it)
                    // the widget create command can't specify a blog id so we attempt to infer it here:                
                        // get list of blogs ordered by last modified date
                        // set Part.BlogId to the last modified blog
                });
            }
        }
    }

This should mean that in a recipe as long as the recent/archive parts are created after the blog they want to be assigned to they will be attached to that blog.

//cc @sebastienros before I code it, is this a good approach?

**Comment by sebastienros** [comment]
In this case this needs to be a custom command from the blogs module.

Related question: How do we pass the default widgets' text for the default recipe?

**Comment by rtpHarry** [comment]
## how text is passed to widgets
In answer to the related question, there is a `/Text` command param and in the code it puts it into a `BodyPart` if it exists:

            var text = String.Empty;
            if (widget.Has<BodyPart>()) {
                if (UseLoremIpsumText) {
                    text = T(LoremIpsum).Text;
                }
                else {
                    if (!String.IsNullOrEmpty(Text)) {
                        text = Text;
                    }
                }
                widget.As<BodyPart>().Text = text;
            }

From [WidgetCommands.cs](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Widgets/Commands/WidgetCommands.cs#L99).

## custom command
Creating a custom command would solve the issue but seems like an inelegant solution because it means that the `widget create` command will happily make widgets with invalid data.

## extending parameters
One option I would like to explore in discussion is making the widget command extensibile.

I initially suggested adding a json type block on the end of the command for custom elements, considered doing it with an args... style block but I think the elegant solution would be to make the command arguments extensible. 

Individual modules can register their support for extra args and would get passed and use a harvester and delegates and whatnot to manage it all.

Can you see drawbacks to this? 

  - how to handle modules duplicating extended args (priorities?)
  - how to provide a way for another recipe item, such as recentblogposts wanting to depend on the id of the blog (pass the collection of completedrecipestepcontext's in to the event?)

## too complicated solution?
Then we create a way for a widget to opt out of being able to be created via `widget create` which forces the developer to look for its custom command and stops invalid widgets being created.

**Comment by rtpHarry** [comment]
Also fixes #1659
