### ISSUE TITLE
Not able to display Image into 'ImagePreview' in MediaPicker when open the mediapicker through 'Insert/update media' from  Html( Class : mce-tinymce) Flavor control.

### ISSUE THREAD

**Issue by npateltronc** [OrchardCMS/Orchard#7252]
Hi,

I have content type 'Carousel Item' in admin site.The content contains control 'Html' Flavor type for Body.See screenshot '1.EditContent.jpg'.

When I am trying to  create 'Carousel Item' content, it render the HTML control on screen.See screenshot '2.EditContent.jpg'.After that I have click on "Insert/update media" as shown in screenshot. 

This will open the MediaPicker popup.In that  after browse the image I have clicked on button upload.But it is not showing me any message or it is not uploading any image.See screenshot '3.MediaPicker.jpg'.

Issue : It is not uploading any Image in media picker after following above steps.

Observation :  

- I have observe that when it is open the popup for media picker it is not passing the parameters in querystring.See screenshot '3.MediaPicker.jpg'.It is not passing parameter for querystring parameter "uploadpath".

Also in same page (screenshot '2.EditContent.jpg') I have another control for browse the image which  use the media picker. When I am click on that it will allow me to browse and save the image.I have check the querystring and it is passing value "Images" for querystring "uploadpath".

I am using Orchard 1.10 Version.

Request you to please assist on same ASAP.

![1 editcontent](https://cloud.githubusercontent.com/assets/22450040/19111554/cea670ac-8b1d-11e6-86a0-9e7515575605.jpg)
![2 editcontent](https://cloud.githubusercontent.com/assets/22450040/19111553/cea02774-8b1d-11e6-844d-4c5562af8ef0.jpg)
![3 mediapicker](https://cloud.githubusercontent.com/assets/22450040/19111555/ceab1576-8b1d-11e6-8986-7ab9a5710d22.jpg)

**Comment by sebastienros** [comment]
Media Picker is a deprecated module since 1993, please use Media Library Picker

**Comment by npateltronc** [comment]
Hi,

Can you please provide reference url for how to  implement the 'Media Library Picker'?

I have search for module but I am not getting any luck.

Regards,
Nayan Patel

**Comment by sfmskywalker** [comment]
The way you use the Media Library Picker is to attach it to a content part, like any other content field. If there is anything specific you'd like to know about the media library picker field, then please do ask your question on the forums such as CodePlex, StackOverflow or OrchardPros.
