### ISSUE TITLE
Is it possible to read data stored in part in HttpModule

### ISSUE THREAD

**Issue by hacko-bede** [OrchardCMS/Orchard#7253]
Hi Orchard team,

I want to access data stored in part and editable by the admin in HttpModule. I want to know is this possible? Should I open a connection from NHibernate to DB and read from there?

**Comment by sebastienros** [comment]
It should be doable, because the workcontext is available in one of the HttpContext.Items (look at the owin integration where it's set). Then from that you can resolve dependencies.

**Comment by hacko-bede** [comment]
Yea I used the Owin integration. Thanks for the response.
