### ISSUE TITLE
Orchard CMS should be multilanguage

### ISSUE THREAD

**Issue by GioviQ** [OrchardCMS/Orchard#7256]
I used for the first time localization module and now I understand that Orchard is not a multilanguage CMS. In the doc here http://docs.orchardproject.net/en/latest/Documentation/Orchard-TV/#building-a-multilanguage-website-structure the modules used are outdated.

In my site for example I used taxonomies to tag my pages and I have a mix of Italian and English content for the same taxonomy
![seo quarella net](https://cloud.githubusercontent.com/assets/7103057/19166370/81edcbe4-8c07-11e6-8f8f-4ccddfb286c3.png)

How do I solve this issue? Taxonomies do not support localization, isn't it? Is there a new tutorial to overcome all missing native multilanguage orchard features?

**Comment by sebastienros** [comment]
Issue with taxonomies, but there is a module for that.
It's here: https://github.com/urbanit/OrchardCMS.Localization-Extensions
Here is a video explaining how to use it: https://youtu.be/X5QWYlDqyoU?t=26m14s

Please reopen the issue if it doesn't solve it.

**Comment by GioviQ** [comment]
Thank you I'll try. Do I still need a culture picker and a culture layer how explained here http://docs.orchardproject.net/en/latest/Documentation/Orchard-TV/#building-a-multilanguage-website-structure 
I suppose?

**Comment by sebastienros** [comment]
I think so. Layer will be needed if you want to display specific widgets per culture.

**Comment by GioviQ** [comment]
@sebastienros is not in your plan to make orchard multilanguage by default?

**Comment by Skrypt** [comment]
A lot of different people have worked on this so far. I think that what you should be searching for is a short term solution more than a long term solution. I think that this is a good request for Orchard 2, but for Orchard 1.x pushing this forward would require some breaking changes. It's been discussed a lot on Orchard 2 github repo.

**Comment by sebastienros** [comment]
@GioviQ Maybe you should add your ideas and comments on https://github.com/OrchardCMS/Orchard2/issues/161
