### ISSUE TITLE
Navigation URLs displaying application root folder

### ISSUE THREAD

**Issue by juanfq** [OrchardCMS/Orchard#7257]
Background:
I'm using WinHost to run my Orchard 1.10.1 application. Orchard is loaded in a folder off of the root and the Orchard folder is defined as an application starting point. My domain (www.tennisden.com) is directed to the root but a rewrite rule in the root web.config sends the request to the Orchard subfolder.

Problem:
The navigation link urls which are determined in NavagationManager.GetUrl() are including the Orchard folder. An example is the home page so ~/ becomes www.tennisden.com/Orchard/ instead of just www.tennisden.com/.

Is there a setting that can make HttpContext.Request.ApplicationPath used in GetUrl() to recognize the Orchard folder as the root rather than the site root?

**Comment by sebastienros** [comment]
Can you ask this question on the forum to get more traction, or stackoverflow? Thanks.
