### ISSUE TITLE
Orchard.Core - Shape created with New.ShapeName confuses tabbededit groupby

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7258]
I opened [this question on stackoverflow](http://stackoverflow.com/questions/39896431/priority-of-shapes-that-are-added-to-a-zone-from-a-view) which has led to my investigation.

Basically if you do something like this snippet the priority "1" isn't honoured:

        var socialShape = New.BlogPost_SocialMediaShareLinks(ShareUrl: socialShareUrl, ShareTitle: socialShareTitle);
        Model.Meta.Add(socialShape, "1");

It turns out that what is happening normally shapes have a `Metadata.Tab = ""` but when you dynamically create one like `New.BlogPost_SocialMediaShareLinks()` you get `Metadata.Tab = null`.

The variety between "" and null makes the groupby accidentally trigger:

        [Shape]
        public void ContentZone(dynamic Display, dynamic Shape, TextWriter Output) {
            var unordered = ((IEnumerable<dynamic>)Shape).ToArray();
            var tabbed = unordered.GroupBy(x => (string)x.Metadata.Tab);

            if (tabbed.Count() > 1) {
                foreach (var tab in tabbed) {
                    var tabName = String.IsNullOrWhiteSpace(tab.Key) ? "Content" : tab.Key;
                    var tabBuilder = new TagBuilder("div");
                    tabBuilder.Attributes["id"] = "tab-" + tabName.HtmlClassify();
                    tabBuilder.Attributes["data-tab"] = tabName;
                    Output.Write(tabBuilder.ToString(TagRenderMode.StartTag));
                    foreach (var item in Order(tab))
                        Output.Write(Display(item));

                    Output.Write(tabBuilder.ToString(TagRenderMode.EndTag));
                }
            }
            else {
                foreach (var item in Order(unordered))
                    Output.Write(Display(item));
            }
        }

https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Core/Shapes/CoreShapes.cs#L283

If you look at the output then you have extra data-tab attributes and such on those shapes in the front end of the site.

The code was added in [this commit, adding tabbed editor in the admin panel](https://github.com/OrchardCMS/Orchard/commit/3c8e39a7c509791578491d22314d2160d2c483f8) but I think the actual problem is that `New` isn't setting the defaults on the dynamic shape.

I tried to follow it to the source but I got lost in the dynamic stuff so I'm turning it over to the wiser ones among us...

**Comment by sebastienros** [comment]
```
        var tabs = unordered.Select(x => (string)x.Metadata.Tab).Where(x => !String.IsNullOrEmtpy(x)).Distinct();
```
