### ISSUE TITLE
Admin Theme - Comments - Warning Notification Missing Icon

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/Orchard#7266]
Noticed on Admin / Settings / Comments that the warning notice doesn't have an icon:

![image](https://cloud.githubusercontent.com/assets/1038062/19213074/a9a126f6-8d59-11e6-8748-114839fabf67.png)

Investigate: are some modules using just the html and it now needs updating or just that one case?

**Comment by Skrypt** [comment]
fixed
