### ISSUE TITLE
GetRoles method implementation of IRoleService should not enumerate to concrete collection

### ISSUE THREAD

**Issue by pwdst** [OrchardCMS/Orchard#7278]
The [GetRoles method of IRoleService](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Roles/Services/IRoleService.cs) returns a generic IEnumerable collection of type RoleRecord.

     IEnumerable<RoleRecord> GetRoles();

The [implementation of this in RoleService.cs](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Roles/Services/RoleService.cs#L47) builds an enumerable of this type from a repository, then enumerates this to a collection before returning.

```
public IEnumerable<RoleRecord> GetRoles() {
            var roles = from role in _roleRepository.Table select role;
            return roles.ToList();
        }
```

This means developers cannot take advantage of SQL filtering or restricting columns as such filtering will be done against the concrete collection in server memory after the entire collection is enumerated. Furthermore this is opaque to the developer as the interface type is an enumerable, not generic ICollection or IList.

Using deferred execution would allow developers to write code like -

     _rolesServices.GetRoles().Where(r => r.Name.Equals("Administrator").Select(r => r.Id);

This can then take advantage of SQL optimisations to only query for the data that is actually required, restricting returned columns and using a where predicate.

**Comment by pwdst** [comment]
The example above is arbitrary and intentionally simple.

**Comment by pwdst** [comment]
Deferred and lazy execution reference https://blogs.msdn.microsoft.com/charlie/2007/12/10/linq-and-deferred-execution/

**Comment by sebastienros** [comment]
I could understand that users should call `ToList` if they want to prevent multiple enumerations, even if they thought these are not queries.
