### ISSUE TITLE
Admin Theme - IE Display Issues

### ISSUE THREAD

**Issue by jonvee** [OrchardCMS/Orchard#7279]
Since IE isn't getting any feature updates I'm wondering if the following has any negative side effects:
The following fixes Content Item summary in "Content" list
`.content-items .summary { 
    ...
    flex-basis: auto; // instead of 100%
    ...
}`

The following fixes Content Item summary head in Content Item Search list (popup)
`/*@media all and (max-width:767px)*/
.content-items .summary .properties .head {
    ...
    flex-basis: auto;
}
`
I'm not sure if this has any negative side effects though... If not I'll submit a PR.
The screenshots below represent the issues in IE 10 and 11:
![2016-10-10 1](https://cloud.githubusercontent.com/assets/2614801/19249784/11339e50-8eec-11e6-81d4-d6fa095699c1.png)
![2016-10-10](https://cloud.githubusercontent.com/assets/2614801/19249785/113a75d6-8eec-11e6-86cd-6cc12156afb3.png)

**Comment by Skrypt** [comment]
Best way to find out is doing a PR that we will be able to test 👍

**Comment by Skrypt** [comment]
Fixed by #7295
