### ISSUE TITLE
Orchard admin : LTR text in RTL context

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/Orchard#7282]
If you look at the menu, the text content should be : Infoset (1.8) but since we are in RTL it places the ending ) at the beginning of the text like this : (Infoset (1.8
The question is : should we set those text back in LTR by using CSS ?

```
direction: ltr;
unicode-bidi: bidi-override;
```

![image](https://cloud.githubusercontent.com/assets/3228637/19257189/9a8ebd48-8f3b-11e6-8ccd-da159ca66d9c.png)

**Comment by ramiassi** [comment]
I think not because the RTL theme will be used with rtl cultures only. I mean these texts often will be localized strings then they will be displayed correctly.

**Comment by Skrypt** [comment]
Maybe I should load also a translation to see the right result. I'll learn Arab. 😄

**Comment by Skrypt** [comment]
I see what you mean now : 

![image](https://cloud.githubusercontent.com/assets/3228637/19261451/467ac25a-8f5f-11e6-8dc0-bc292e06ae66.png)

**Comment by sfmskywalker** [comment]
The following proposed solution makes most sense to me:

![image](https://cloud.githubusercontent.com/assets/938393/23262587/922d1cca-f9db-11e6-826c-e57cf69969d6.png)

Source: http://wplang.org/never-use-flags-language-selection/
