### ISSUE TITLE
designer tool version 1.6 , Shape Tracing icon no show on home page

### ISSUE THREAD

**Issue by techmio** [OrchardCMS/Orchard#7284]
I checkout the code and  ran debug mode with vs2015 ,enabled designer Shape Tracing, but there was on  icon  show on home page. then I download the latest version from the url.
http://gallery.orchardproject.net/Packages/Orchard.Module.Orchard.DesignerTools/1.6

I enabled the Shape Tracing again, no show Shape Tracing icon on home page too.

There was no log information under the folder
Orchard.Web\App_Data\Logs

So I had no idea what was the root reason.
Any suggestion?

**Comment by rtpHarry** [comment]
## Wrong version
That version that you downloaded on the gallery is not correct. It's an old version.

I would recommend that you undo that to start off with. You can get the files by going to the main repo https://github.com/OrchardCMS/Orchard and then changing your branch to the version you're running and getting the code for that module.

## Is it your theme?
Look in the source code, is the markup there at the end of the file but just hidden by something in your theme perhaps?

## Are you meeting the requirements?
It will only display on the front end under certain conditions which are here:

  - https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.DesignerTools/Services/TemplatesFilter.cs#L39

**Comment by techmio** [comment]
Thanks for your reply.

It comes out that resources in folder of "Modules/Orchard.DesignerTools/" are  not available.

http://localhost/Modules/Orchard.DesignerTools/scripts/jquery.scrollTo-1.4.4.min.js Failed to load resource: the server responded with a status of 404 (Not Found)

But  other modules resource  are accessible like:
http://localhost/Modules/Orchard.DynamicForms/Scripts/Lib.js
http://localhost/Modules/Orchard.Workflows/Scripts/orchard-workflows.js


I checked that  "Modules/Orchard.DesignerTools/" folder permission include IIS_USER the same as " Modules/Orchard.DynamicForms"

I check those   web.xml in modules folders it seems no  permission configuration for resources.

I create a test.html  file in  a new "test" folder in "Modules"  , and the resource is not accessible
 http://localhost/Modules/test/test.html Failed to load resource: the server responded with a status of 404 (Not Found).

Why resources under the directory "Modules", some can be accessed, and some are not accessible even those folders security setting are the same.What's wrong?

**Comment by techmio** [comment]
Adding a new web.xml to the "Orchard.DesignerTools/scripts/" and allow static resources access resloved it..

**Comment by rtpHarry** [comment]
@techmio yes that's what I would have suggested next :) the styles folder will need one of those same web.config files as well. The confusing thing is how you got Orchard into that situation in the first place as those files should already have been included. I always clone a copy of the repo on GitHub so that I get all the files. There are some other releases like installing with Web PI or downloading .zip file releases - did you perhaps start out from one of these?
