### ISSUE TITLE
Admin Theme - RTL : Top button has full screen width

### ISSUE THREAD

**Issue by ifle** [OrchardCMS/Orchard#7285]
![orchard-rtl-issue20](https://cloud.githubusercontent.com/assets/1140474/19263360/a2a47860-8fa4-11e6-927b-bca8176e8e07.jpg)

**Comment by sfmskywalker** [comment]
It looks good from my end:

![image](https://cloud.githubusercontent.com/assets/938393/19792874/7dc979be-9c97-11e6-9a20-caaf5a9a7efd.png)

Can you please try again (making sure browser cache has been cleared)?
I'm closing it for now, but will reopen if we can reproduce the issue. Thanks!
