### ISSUE TITLE
Admin Theme - Culture picker does not show selected culture

### ISSUE THREAD

**Issue by ifle** [OrchardCMS/Orchard#7286]
![orchardl-issue20](https://cloud.githubusercontent.com/assets/1140474/19263453/17c445e4-8fa5-11e6-8a31-72a47bf8ad38.jpg)

**Comment by Skrypt** [comment]
Do you mean that it does'nt specify which culture is the current one ?

**Comment by ifle** [comment]
Yes, exactly

**Comment by Skrypt** [comment]
Yeah, we presumed that you will have translations installed but it could happen that you don't have any and would just like to see if you really have switched cultures.
