### ISSUE TITLE
Admin Theme -  Layout - RTL : The default direction in the html editor will be RTL

### ISSUE THREAD

**Issue by ifle** [OrchardCMS/Orchard#7290]
Add HTML editor will be configured to RTL direction by default
![orchard-rtl-issue23](https://cloud.githubusercontent.com/assets/1140474/19264328/f25168ec-8fa8-11e6-9485-dd59fa195296.jpg)

**Comment by sfmskywalker** [comment]
Is this an issue with just the new admin theme? if also an issue with the old admin, we should not file this under the new admin theme, but as a localization issue with TinyMCE.

**Comment by ifle** [comment]
The issue of new admin.

**Comment by sfmskywalker** [comment]
Can you please try again, or let me know how to reproduce the issue? When I try, it just works:

![image](https://cloud.githubusercontent.com/assets/938393/19790830/c5d3d6f4-9c89-11e6-896f-2e12162c18dc.png)

I'm closing it for now, but will reopen if we can repro. Thanks
