### ISSUE TITLE
RTL - Tokenize hint will be positioned left

### ISSUE THREAD

**Issue by ifle** [OrchardCMS/Orchard#7293]
![orchard-rtl-issue26](https://cloud.githubusercontent.com/assets/1140474/19265565/49bde312-8fae-11e6-803e-796fdab29d5d.jpg)

**Comment by ifle** [comment]
I still have this is issue. Tested both on IE11 and Chrome

**Comment by sfmskywalker** [comment]
Did you clear your browser cache?

**Comment by ifle** [comment]
I did not had the latest version. Thanks
