### ISSUE TITLE
Admin Theme - Tokenize popup does not works

### ISSUE THREAD

**Issue by ifle** [OrchardCMS/Orchard#7294]
Tokenized popup does not works

**Comment by Skrypt** [comment]
I'm surprised about that one. I changed the token picker. Do you remember on which view exactly ?

**Comment by ifle** [comment]
I'm not sure, I think this is filter screen of query. I added the body part to query filter.

**Comment by sfmskywalker** [comment]
I just tried, and it seems to work just fine. I did notice, however, that the token glyph is not updated to show a nice leaf icon, plus it is pulled all the way to the right. See snippets below:

![image](https://cloud.githubusercontent.com/assets/938393/19332849/03413414-90be-11e6-9c5e-91c7408e7545.png)

The following token glyph looks good:
![image](https://cloud.githubusercontent.com/assets/938393/19332871/2e6e8ec0-90be-11e6-8c23-ac6059c5f161.png)

I'll check out what's different and submit a fix.

**Comment by sfmskywalker** [comment]
I suspect this was work in progress, initiated by Jasmin.

In the case of the nice little leafs, Jasmin coded in the relevant HTML, whereas the text field in the Body Part Text filter i not updated with this HTML.

What should be done is update the script in Orchard.Tokens to generate the appropriate HTML. That way, all token popups will be the same.

**Comment by Skrypt** [comment]
You are right I forgot to change it everywhere.

**Comment by sfmskywalker** [comment]
No worries, I'm pushing an updated script shortly that will fix this everywhere.

**Comment by ifle** [comment]
Still several layout issues with tokenize popup. I don't know if I need to create new issues? 
1. When popup is open the position of footer is changed. 
2. The keyword hint is clipped.
3. Popup is not positioned correctly in RTL. Right corner of popup will be aligned to right corner of textbox

![image](https://cloud.githubusercontent.com/assets/1140474/19337598/462cc5e8-911f-11e6-9bf5-07b6108c917c.png)
