### ISSUE TITLE
MultiTenancy: mismatch between Add and Edit views

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [OrchardCMS/Orchard#7301]
When creating a new tenant, after selecting we want to use an existing SQL database, there is a textbox to input the connection string. The code for that, from Add.cshtml, is:

    @Html.EditorFor(svm => svm.DatabaseConnectionString)

After having the tenant, we may edit the connection string. In the view Edit.cshtml the code for the textbox is:

    @Html.TextBoxFor(svm => svm.DatabaseConnectionString)

I personally prefer the UI resulting from the code in Edit.cshtml, because the result is generally a wider textbox in which it's possible to see the whole connection string without scrolling.

**Comment by rtpHarry** [comment]
Yes you're right, it is likely to be a long string. I've made them both uniform and full width:

![image](https://cloud.githubusercontent.com/assets/1038062/19356885/39c95b7a-9167-11e6-8739-7c39f3b48b1d.png)

**Comment by MatteoPiovanelli-Laser** [comment]
cool. Thanks
