### ISSUE TITLE
RTL - Wrong position of label and icon in menu item in case when it is not a link

### ISSUE THREAD

**Issue by ifle** [OrchardCMS/Orchard#7313]
![image](https://cloud.githubusercontent.com/assets/1140474/19346916/9c84ae86-914e-11e6-9c11-782c2298bcfa.png)

**Comment by sfmskywalker** [comment]
I would suggest we close this one for now, since we intend on replacing the current admin theme with a new one.

**Comment by ifle** [comment]
Ok. I've closed it. Thanks
