### ISSUE TITLE
Using as Web App - please support dynamic roles

### ISSUE THREAD

**Issue by weedkiller** [OrchardCMS/Orchard#7328]
Hello, in the ver 1, for orchard membership system can you please provide support for aspIdentity V 2.2.1 with dynamic roles for membership

I am trying to implement a web app to track support tickets and would like to be able to create different roles based on the user vendor, customer, employee etc

thanks

**Comment by sebastienros** [comment]
What is preventing you from creating custom roles with the current version? 
Please provide some repro steps as this is a working feature already.
