### ISSUE TITLE
Can't get 1.10.1 to run from VS 2015 Community/IIS10

### ISSUE THREAD

**Issue by rebeccamarye** [OrchardCMS/Orchard#7331]
I'm aware of [1.10.1 redist will not install](https://github.com/OrchardCMS/Orchard/issues/6858) but I'm getting a different error. 

I downloaded and unpacked the zip, opened the solution in Visual Studio 2015 Community, and hit Ctrl+F5. Everything built without error, but the browser displays a 500.19 error. Apparently it's looking for the web.config in \\?\C:\Users\Rebecca\Documents\My Web Sites\Orchard.Web-Site\web.config. IIS has created that folder, but it's empty.

I tried manually copying the web.config files to that location from the project directory, but that doesn't appear to have had any effect. 

I'm a front-end developer. I can just about get the IIS Manager to run, but adding Mime types is about the extent of my expertise. Can anybody help me figure out what egregiously stupid thing I'm doing here?

Oh, I'm running Windows 10.

**Comment by Skrypt** [comment]
Look at the port that it's trying to use. Maybe you have different web services that are running on the same port. Else, I would strongly suggest using the source code.

**Comment by rebeccamarye** [comment]
Ah, that was it. I picked a random port number and it's working now. Thanks!

BTW, I am running the source.
