### ISSUE TITLE
1.10.x : User with blog permissions can't manage a blog

### ISSUE THREAD

**Issue by ifle** [OrchardCMS/Orchard#7340]
User with blogs pernissions can't manage a blog.The blog menu item is missing on admin menu

![image](https://cloud.githubusercontent.com/assets/1140474/19620117/731e3184-987e-11e6-8e97-3aa1e6a5b0f2.png)

**Comment by rtpHarry** [comment]
I haven't looked into this in detail but I think that https://github.com/OrchardCMS/Orchard/pull/6994 fixes this. It changes the BuildMenu to check `Permissions.MetaListOwnBlogs` and also makes some other permissions based improvements.

**Comment by ifle** [comment]
On which branch this is issue already fixed? I did not checked on the dev branch. For now the dev branch does not works with sql server. There is error during a setup.

**Comment by rtpHarry** [comment]
Its an active PR, it hasn't been accepted yet.
