### ISSUE TITLE
BUG: content item localization sometimes causes culture duplicates

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [OrchardCMS/Orchard#7348]
I have not been able to replicate this behaviour wih 100% repeatability, so I am not too sure of the actual steps.

After enabling the Localization feature, I tried creating translations of a content item.
In the "new" content, I get to choose the culture, and of course the one I am translating from is not available. SO I select a culture and hit "Publish Now".
Sometimes, and again, I am not sure under what conditions, the translation is marked as having the same culture as the original (see picture).

![image](https://cloud.githubusercontent.com/assets/19283945/19652614/bcd0200a-9a11-11e6-9bb1-7962efc1b925.png)

Again, I have not been able to replicate this behaviour reliably, so I could not isolate its cause yet.

**Comment by sebastienros** [comment]
We'll need either a repro or someone that can corroborate.

**Comment by sebastienros** [comment]
We'll close it in two weeks if there is no update.

**Comment by MatteoPiovanelli-Laser** [comment]
I was checking things again about this. I found the reason why this happens.

There are two places where I am clicking the "New Translation" link:

1. In the SummaryAdmin view (Views/Parts/Localization.ContentTranslations.SummaryAdmin.cshtml)
2. In the Editor view (Views/EditorTemplates/Parts/Localization.ContentTranslations.Edit.cshtml)

In the former, the `id` query string parameter to the `Translate` action is set to the Id of the ContentItem whose SummaryAdmin this is.
In the latter, that same parameter is computed as
```
var contentItemId = Model.MasterContentItem != null ? Model.MasterContentItem.Id : Model.ContentItem.Id;
```

This means we have now repro steps to have the "wrong" behaviour from this issue:

- Enable the Localization module.
- Start from an instance with at least 3 enabled cultures. For example, consider `en-US`, `fr-FR`, `it-IT`.
- Have a ContentType that has a LocalizationPage. For example, the ContentType `Page`.
- Create a `Page` and assign `en-US` to its culture. Call this `Page` EnPage.
- Create a new Translation of EnPage and assign `fr-FR` to its culture. Call this `Page` FrPage.
- From the list of content, start a new Translation clicking on the "New Translation" link from FrPage's SummaryAdmin view. Assign 'it-IT' to its culture. Call this `Page` ItPage.
- We can now see in the record that the MasterContentItem for ItPage is FrPage, rather than EnPage as it should be. That means that we can, starting from ItPage, create a new translation in the `en-US` culture; at the same time, starting from EnPage we can create a new translation in the `it-IT' culture.
