### ISSUE TITLE
Recipe not downloading packages from the new Orchard Gallery

### ISSUE THREAD

**Issue by mroskamp** [OrchardCMS/Orchard#7353]
I recently updated my DefaultPackageUpdater to point at the new Gallery (since the old one wasn't redirecting), but cooking my site with a recipe that includes a module from the gallery fails.

I've been debugging this and it seems that ModuleRecipeHandler (via `<Module packageId="module1" [repository="somerepo"] version="1.1" />`) checks if the module is already installed. This check thinks that the module is installed, even though the package hasn't been downloaded (it doesn't exist in `Orchard.Web\Modules`). But, since the handler thinks the module _is_ installed, then it skips the download, which causes `feature enable` to fail, since the module doesn't exist on disk.

If I remove the `ModuleAlreadyInstalled` check and run my recipe, then the site cooks properly.

I ran `feature list` both before and after cooking my recipe, and neither listed the modules I'm trying to include from the gallery.

**Comment by sebastienros** [comment]
We need a redirection from the old feed url to the new one.

**Comment by sebastienros** [comment]
What version are you using?

**Comment by mroskamp** [comment]
I'm on v1.9.2.

I manually set DefaultPackageUpdater  to point at the new feed URL and that's when the `ModuleAlreadyInstalled` check failed. Before changing the feed URL the install threw an exception before getting to the `ModuleAlreadyInstalled` check

**Comment by sebastienros** [comment]
This was an issue with the gallery. This should work now without any changes in your code.
