### ISSUE TITLE
Problem when reading SiteSettings from the Routes class

### ISSUE THREAD

**Issue by ThaerAlAjlouni** [OrchardCMS/Orchard#7362]
I am trying to read **SiteSettings** in the **Routes** class, because I need to optionally add a route depending on some setting values, but it will throw an error each time I try to do that because the **WorkContext** instance will be _null_. I knew that a similar issue ( #6991 ) has been resolved and I think the same fix can be applied here.

As you can see below (**DefaultOrchardShell** class) the OwinMiddlewares and Orchard's  Shell events are wrapped with a **WorkContextScope** while Routes are not:
![defaultorchardshell](https://cloud.githubusercontent.com/assets/22820843/19833814/2066b0ba-9e1e-11e6-90e1-eceb2e28452b.png)

**Comment by sebastienros** [comment]
I am afraid that in this case the _routeProviders and _httpRouteProviders instances should be resolved from the same work context.

**Comment by ThaerAlAjlouni** [comment]
So the fix will be extending the **scope** of the created work context to everything inside the **Activate** method, right?
