### ISSUE TITLE
Error when starting a new tenant with a name starting with the '3' character.

### ISSUE THREAD

**Issue by SzymonSel** [OrchardCMS/Orchard#7378]
`Orchard.Environment.DefaultOrchardHost - (null) - A tenant could not be started: 3aaaa Attempt number: 0 [(null)]
System.Xml.XmlException: Name cannot begin with the '3' character, hexadecimal value 0x33. Line 4, position 4.`

Should a fix, disallow tenant name begging with numbers or should we try to make this work?

**Comment by sebastienros** [comment]
This is a duplicate, and I think we fixed it recently, or at least triaged it.

**Comment by SzymonSel** [comment]
Well, at least 1.10.x still has this bug.

**Comment by SzymonSel** [comment]
#5343

**Comment by sebastienros** [comment]
I think there is already validation for tenant names. How did you create it?

**Comment by sebastienros** [comment]
Here is the validation to apply:

`@"^[a-zA-Z]\w*$"`

**Comment by SzymonSel** [comment]
The standard way, from the dashboard.
Looks like the regex is incomplete.

**Comment by SzymonSel** [comment]
Oh, and let's stick with the "+" in the regex
