### ISSUE TITLE
Display.Body_Editor not persisting Model data

### ISSUE THREAD

**Issue by Bobinns** [OrchardCMS/Orchard#7379]
I have the following Layout Element in my EditorTemplates View -

`@Display.Body_Editor(EditorFlavor: "html", Text: Model.Content, AutoFocus: true)`

The Model.Content propery is not persisted on POST update?

The data is saved, if I instead use  `@Html.TextAreaFor(m => m.Content)`

but I wish to use the Tinymce within my Editor?

Any thoughts would be appreciated.

**Comment by sebastienros** [comment]
I don't understand what you are trying to do, maybe it's specific to layouts, @sfmskywalker any idea?

**Comment by Bobinns** [comment]
sorry for tardy response...
From [this post](https://github.com/OrchardCMS/Orchard/issues/7043) I solved my problem by using the following code -
`@Display.Body_Editor(PropertyName: "Content", Text: Model.Content, EditorFlavor: "html")`
