### ISSUE TITLE
As suggested in #5533, ProjectionPartDriver shouldn't pass token dictionary to projectionManager.GetContentItems in order to use tokens within queries?

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#7385]
@sebastienros, we used proposed solution in #5533 till now, so, request.content is perfect if we have a request.content. but i cannot use it in other contests, like within widgets for example. Any idea on how to solve it? 
In general I think that having the ability to pass a token dictionary to projectionmanager methods which uses queries should be considered... 

Adding a parameters to those methods (as I suggested in #5533 ) could be a breaking change so we should consider an alternative approach: a new service?

Any idea/suggestion will be appreciated.
H

**Comment by sebastienros** [comment]
Continuing on the first issue
