### ISSUE TITLE
A 'script' named 'jQuery' could not be found.

### ISSUE THREAD

**Issue by subtata-emfluence** [OrchardCMS/Orchard#7392]
I have just installed Orchard via Web Platform installer 5.0 and it got installed fine. But when I launched the site via WebMatrix I am getting the following error.

`A 'script' named 'jQuery' could not be found.`

>Line 13:     <meta charset="utf-8" />
>Line 14:     <title>@Html.Title(title, siteName)</title> 
>Line 15:     @Display(Model.Head)
>Line 16:     <script>        (function (d) { d.className = "dyn" + d.className.substring(6, >d.className.length); })(document.documentElement);</script> 
>Line 17: </head>

**Comment by ActivePHOENiX** [comment]
Which version of orchard have you installed? Jquery module has been deprecated in the current version as 1.10.1 and all jquery refs has been moved to Orchard.Resources module instead along with other useful scripts, and if you chose the default recipe it should be enabled by default.
I think your version is old or you have another old 3rd party module that is old and depends on the above mentioned deprecated module. I hope this helps.

**Comment by subtata-emfluence** [comment]
I installed via Web PI 5 and it has only one Orchard CMS listed which has a release date of 5/18/2016. Please advise what I should do to get rid of this. This is the first time I am using Orchard. Thank you!

**Comment by subtata-emfluence** [comment]
No idea what happened. I tried to run the site just now using WebMatrix and its loaded!! Nothing was changed or updated. Hope things will work now for me.  Out of curiosity, why I got that error yesterday?

**Comment by npsniloo** [comment]
I AM running the latest version in iis and have the problem same as you

**Comment by npsniloo** [comment]
ok  i think it is solved now too
