### ISSUE TITLE
Enhancement: add cache settings part for content items

### ISSUE THREAD

**Issue by jardg** [OrchardCMS/Orchard#7393]
I think it would be great to create a new part that contains cache settings for content items. So we attach this part to the types we would like to specify diferent cache settings  instead of the general ones that we define on the OuputCache settings view, since these settings are being applied to all the content items 
What I'm thinking of is to check in the OutputCacheFilter the content item we are caching and see if we have the cache settings part attached. If this is the case get the settings from the part and set them on the cacheItem.

My case scenario in which this improvement would be useful is our company website where content can be created/modified in any moment by the customers or any other process so we need to update the cache acording to the general gracetime and cache duration defined on the settings view. The site also has an automatic process that gets data from an external source and is saved as a specific type and then displayed on different pages. The process of getting on cache one of these pages for the first time is expensive and can be annoying for the user that makes the first request. Since We already know that the data isn't getting updated for a long amount of time(talking about days) it would be great to have a way to customize different cache time for those items. 

If you think this feature could be useful I have been working on this and I could work on this issue and submit a pull request according with how you think this feature should be done.

Regards.

**Comment by sebastienros** [comment]
I could agree with the suggestion, but the issues you are describing is already solved, or should be. Whenever a content item is editing, even a widget, we invalidate any cache entry that used it.

**Comment by DanielStolt** [comment]
Somewhat related to things discussed in #5790.

**Comment by DanielStolt** [comment]
OK, so I decided to consolidate things into #7439. The infrastructure described there would be the underpinnings that make it possible to do what @jardg suggests here, among other things.
