### ISSUE TITLE
Orchard CMS - can it work with Oauth2 provider like IdentityServer3 or 4?

### ISSUE THREAD

**Issue by nigel-dewar** [OrchardCMS/Orchard#7403]
Hi I'm sorry I know this is not an issue, but I find github seems to be best way to get good answers.

I'm trying to figure out if I can use OAuth2 provider like IdentityServer with orchard CMS.

Essentially if orchard has the ability to authenticate using a Oauth JWT token, then this is what I need.

Has anyone done this, or is there a module to facilitate this kind of scenario?

Cheers

Nigel

**Comment by sfmskywalker** [comment]
I believe there will actually be a small demo tomorrow at the weekly meeting regarding an OpenId module that enables users to authenticate their session against the most popular OpenID providers. It has extensibility points so it would be easy to add your own provider to connect to IdentityServer for example. I don;t know if it will do what you need, but I'd say it's worth checking out. The source code will be made available. /cc @ThaerAlAjlouni

**Comment by nigel-dewar** [comment]
Thanks very much ill check it out


Sent from Samsung Mobile


-------- Original message --------
From: Sipke Schoorstra
Date:15/11/2016 13:27 (GMT+10:00)
To: OrchardCMS/Orchard
Cc: nigel-dewar , Author
Subject: Re: [OrchardCMS/Orchard] Orchard CMS - can it work with Oauth2 provider like IdentityServer3 or 4? (#7403)


I believe there will actually be a small demo tomorrow at the weekly meeting regarding an OpenId module that enables users to authenticate their session against the most popular OpenID providers. It has extensibility points so it would be easy to add your own provider to connect to IdentityServer for example. I don;t know if it will do what you need, but I'd say it's worth checking out. The source code will be made available. /cc @ThaerAlAjlouni<https://github.com/ThaerAlAjlouni>

-
