### ISSUE TITLE
Unable to use OrchardSuppressDependency for MediaLibraryService

### ISSUE THREAD

**Issue by greg84** [OrchardCMS/Orchard#7408]
I'm trying to create a new implementation of one of the methods in the MediaLibraryService in Orchard.MediaLibrary.

After several hours of fiddling around, I couldn't get it to work in my own module so I moved the class straight into the MediaLibrary module itself to try and rule out a problem with my module - it still didn't pick up the new implementation. Attaching a debugger I could see that it was still using the original service.

Could something be broken or am I just being an idiot?

```
    [OrchardSuppressDependency("Orchard.MediaLibrary.Services.MediaLibraryService")]
    public class MyCustomMediaLibraryService : MediaLibraryService, IMediaLibraryService
    {
        public MyCustomMediaLibraryService(
            IOrchardServices orchardServices,
            IMimeTypeProvider mimeTypeProvider,
            IStorageProvider storageProvider,
            IEnumerable<IMediaFactorySelector> mediaFactorySelectors)
            : base(orchardServices, mimeTypeProvider, storageProvider, mediaFactorySelectors)
        {
        }

        public new string UploadMediaFile(string folderPath, string fileName, Stream inputStream)
        {
            throw new Exception("It works!");
        }
    }
```

**Comment by carlwoodhouse** [comment]
I assume you cleared out your app_data after making the changes?

**Comment by sebastienros** [comment]
As you are already attaching the debugger, can you check when your class is found why the code doesn't actually replace the specified one?

Also, have you added a manifest dependency on Orchard.MediaLibrary to be sure the service is loaded first, then yours?

**Comment by greg84** [comment]
Another 2 hours on this and I finally managed to work out what was going on. There's nothing wrong with Orchard, it's a C# thing...

I'd inherited the Orchard implementation to save having to duplicate the whole thing, as I only wanted to change the behavior of one method. However, the `new` keyword causes the method to be available only when invoked directly against the derived class, not the base class. In this case, other methods in the base class also call `UploadMediaFile`. This is what was happening here, changing my code as below worked fine - I just had to add the method that was calling the one I actually wanted to modify, copying the existing implementation.

Thanks for your time, I'll close this issue now.

```
    [OrchardSuppressDependency("Orchard.MediaLibrary.Services.MediaLibraryService")]
    public class MyCustomMediaLibraryService : MediaLibraryService, IMediaLibraryService
    {
        public MyCustomMediaLibraryService(
            IOrchardServices orchardServices,
            IMimeTypeProvider mimeTypeProvider,
            IStorageProvider storageProvider,
            IEnumerable<IMediaFactorySelector> mediaFactorySelectors)
            : base(orchardServices, mimeTypeProvider, storageProvider, mediaFactorySelectors)
        {
        }

        public new MediaPart ImportMedia(Stream stream, string relativePath, string filename, string contentType) {
            var uniqueFilename = GetUniqueFilename(relativePath, filename);
            UploadMediaFile(relativePath, uniqueFilename, stream);
            return ImportMedia(relativePath, uniqueFilename, contentType);
        }

        public new string UploadMediaFile(string folderPath, string fileName, Stream inputStream)
        {
            throw new Exception("It works!");
        }
    }
```
