### ISSUE TITLE
Problem with permissions for taxonomies

### ISSUE THREAD

**Issue by MarcoViglione-Laser** [OrchardCMS/Orchard#7413]
I want to create a user able to manage only taxonomies and no other content, but if I disable content permissions and enable taxonomies permissions he's not able to manage them.

This is how I was able to find the issue:
1. Create a new user
2. Assign a single role to a new user (i.e. Editor)
3. In the settings for that role, uncheck everything under "Content Feature" and check Manage Taxonomies under "Orchard.Taxonomies Feature"
4. Log as the new user
5. Open the Edit page of a Taxonomy or Term

**Result**
![cannotedit](https://cloud.githubusercontent.com/assets/13333789/20427709/8f12f336-ad85-11e6-9cee-41b3e960cdbf.png)

Maybe this behavior happens because taxonomies and terms use the standard content controller instead of a dedicated controller like Blogs?

**Comment by sebastienros** [comment]
Update the ContentItemMetadata Editr route to go to the Taxonomy/Term controller.

Probably remove `_taxonomyService.ProcessPath(term);` from the controller as this doesn't to be necessary (the Content Controller currently doesn't do it)
