### ISSUE TITLE
OpenId Module

### ISSUE THREAD

**Issue by ThaerAlAjlouni** [OrchardCMS/Orchard#7419]
For your consediration, the **Orchard.OpenId** is a new module that enables your site to authenticate users using the **_OpenId connect protocol_**. Out of the box, this module provides five Open Id providers:

- Facebook
- Google
- Twitter
- Azure Active Directory 
- Active Directory Federation Services

Each of these providers is implemented as a separate **feature** so it can be _enabled/disabled_ individually.   
Each provider's **settings** can be easily managed via the admin's dashboard under the **Open Id** menu item under the Site settings menu. 

> The login of usual orchard users will not be affected, but the **LogOn** page shape will be overridden to show the enabled OpenId providers.

The module was built in a way to easily add custom Open Id providers by simply implementing **IOpenIdProvider**, and then it will automatically be discovered and registered at runtime.

**Comment by Piedone** [comment]
Wow, very nice! Why not demo on one of Tuesday's meetings?

**Comment by Piedone** [comment]
It was demoed but I wasn't there? :-)

**Comment by sebastienros** [comment]
Two weeks ago, awesome!

**Comment by Piedone** [comment]
I'm glad my suggestion was so good that @ThaerAlAjlouni has taken it two weeks in advance!

**Comment by armanforghani** [comment]
Wow, great work.

**Comment by ThaerAlAjlouni** [comment]
Merged to the dev branch #7420

**Comment by armanforghani** [comment]
When will this be available in 1.10.x or master branch?
