### ISSUE TITLE
how to add security for field and parts in orchard

### ISSUE THREAD

**Issue by YakoobHammouri** [OrchardCMS/Orchard#7426]
I need Display Some of the Parts or fields to Anonymous user and prevent from see other

**Comment by sebastienros** [comment]
By implementing a ShapeTableProvider, you should be able to provide custom Placement info, which would check the current user and assign "-" to hide specific shapes.
You can also assign some specific content based on that.

Or override the shape templates to check for the current user, that might be the simplest solution.
