### ISSUE TITLE
Autoroute is regenerated wrongly after editing a localized content

### ISSUE THREAD

**Issue by MarcoViglione-Laser** [OrchardCMS/Orchard#7430]
I added a LocalizationPart to a content type for which I modified the default autoroute pattern. I didn't check the option to use different patterns for different cultures because I wanted to use the same pattern for all cultures. When creating the content item the pattern was generated as I expected. Then I edited the content, I deleted the autoroute to force its regeneration, I saved and the result was different: the modified pattern was applied only to the contents with a culture corresponding to the site culture, but for the other cultures Orchard applied the {Content.Slug} pattern.

**Steps to reproduce the issue:**

1. Create a content type with an Autoroute Part and a Localization Part.
2. In the Autoroute Part settings check "Allow custom patterns", uncheck everything else and edit the default pattern into something different.
3. Create a content in a language different from the site language. The autoroute should be generated with the modified pattern.
4. Delete the autoroute from the content and save. The autoroute will be generated with the {Content.Slug} pattern.

As an alternative to steps 1 and 2 you can attach a Localization Part to a content type already defined like that, i.e. a Taxonomy Term or a Blog Post.

Looking at the `AutorouteService`, in the `GetDefaultPattern` method, this is intentional. Why such an approach was chosen? I think that a culture neutral pattern should be applied to all cultures, not only to the site culture.

**Comment by Skrypt** [comment]
Will look at it. Need to put back my head into it first.

**Comment by Skrypt** [comment]
So the problem here I think is that I hardcoded the {Content.Slug} pattern and we just need to make this using the default dynamic slug.

**Comment by MarcoViglione-Laser** [comment]
I did some tests and I found some other problems regarding the autoroute localization support:

1. The concept of culture neutral pattern is not present. Even if you don't check the "Use culture pattern(s)" option, the only editable pattern is saved with the current culture of the site.
2. When saving a content definition that contains an AutoroutePart it automatically generates a pattern (in the default {Content.Slug} format) for each language defined in the website settings that has no pattern associated. Those patterns are used by the GetDefaultPattern method even if the "Use culture pattern(s)" option is unchecked.
3. In the same scenario, if I modify the only editable pattern, only the pattern associated to the site culture is updated, while the other cultures still keep the {Content.Slug} pattern.
4. Some modules (i.e. Taxonomy) currently create in the Migration some patterns with null culture, but when the content definition is saved again they are migrated to the site culture.

The result is that if the "Use culture pattern(s)" option is unchecked the visible pattern is only applied to contents in the site culture, while all other contents use the {Content.Slug} pattern.

To solve this problem my suggestion is to:
1. Modify the GetDefaultPattern method in a way that uses the "Use culture pattern(s)" setting: if it's unchecked it searches first a pattern with culture null (for backward compatibility), then if it not exists it searches a pattern associated to the site culture. If neither exists it returns {Content.Slug}.
2. When the AutoroutePart settings are saved, if the "Use culture pattern(s)" setting is unchecked the updates to the only editable pattern are saved for all languages.

**Comment by Skrypt** [comment]
> The concept of culture neutral pattern is not present. Even if you don't check the "Use culture pattern(s)" option, the only editable pattern is saved with the current culture of the site.

True, this is problematic because if we want to change the default culture of the website after having created content items ; then the default pattern will become the one set on that culture. And it could never have been customized. We need to have a null culture default pattern in that case. And it's been hardcoded wrongly as {Content.Slug} as far as I can remember.

> Modify the GetDefaultPattern method in a way that uses the "Use culture pattern(s)" setting: if it's unchecked it searches first a pattern with culture null (for backward compatibility), _**then if it not exists it searches a pattern associated to the site culture**_. If neither exists it returns {Content.Slug}.

If we don't check "Use culture pattern" it should not try to get that localized pattern. It should just try to get the culture neutral pattern. We should instead set this culture neutral pattern to the current default pattern set in the default culture with a database migration.

> When the AutoroutePart settings are saved, if the "Use culture pattern(s)" setting is unchecked the updates to the only editable pattern are saved for all languages.

If we always use the culture neutral pattern then we don't need to overwrite those custom patterns that we could want to reuse later on.

**Comment by MarcoViglione-Laser** [comment]
Seems a good idea. I can work on it in the next couple of days.

**Comment by Skrypt** [comment]
I'm closing as it is dated from 2016 and I think this is fixed.
