### ISSUE TITLE
Element which is based on parameterized snippet dont render

### ISSUE THREAD

**Issue by Elmarill** [OrchardCMS/Orchard#7431]
I created parameterized snippet and then created element based on the snippet (enter values as parameters). Added the element on the page and published the page. Then i try to show the page and element don't render. I dig deeper a little bit in the code and find out - Model.Snippet is empty in the snippet template (Snippet.cshtml) but Model contents all values which I added as parameters. Is it bug? 

Do it in d8f423888a

**Comment by sebastienros** [comment]
@sfmskywalker
