### ISSUE TITLE
[Design] Menu management

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#7445]

**Comment by DanielStolt** [comment]
@sebastienros Maybe this issue should be in the O2 repo?

Anyway, I have worked on several projects where we have used the extensibility of menu items heavily. CSS is a common requirement, but we also commonly use it to:

- Add images or icons
- Add text fields to categorize menu items
- Render menu items as separate headings and body texts
- Add SEO elements to menu items

So the decision to keep this extensibility is quite important IMO.

**Comment by sebastienros** [comment]
Ouch, I am moving it to O2, can you copy your comment?
