### ISSUE TITLE
Encoding issue for taxonomies in the dynamic forms

### ISSUE THREAD

**Issue by mhodorogea** [OrchardCMS/Orchard#7451]
Hello,
I noticed that when we use the **taxonomies in the dynamic forms**, it doesn't respect the proper encoding.
In result we have the following : 
- Acuité : `Acuit&#233;`
- Algèbre : `Alg&#232;bre`
- Ambiguë : `Ambigu&#235;`
- Aperçu : `Aper&#231;u`

If you have any ideas about  how to solve this, please write it down ;)

**Comment by mhodorogea** [comment]
It seems that the error comes from `Orchard.DynamicForms.Drivers` the class : `TaxonomyElementDriver` and more precise the function :
`private IEnumerable<SelectListItem> GetTermOptions(Taxonomy element, string displayType, int? taxonomyId, IDictionary<string, object> tokenData)`

**Comment by sebastienros** [comment]
_dynamic forms_ I didn't see that ... @sfmskywalker

**Comment by mhodorogea** [comment]
Hello ! I just created a pull request to fix this issue.
https://github.com/OrchardCMS/Orchard/pull/7458

I modified two lines only :) 

What do you think about this correction? Thanks
@sebastienros
@sfmskywalker
