### ISSUE TITLE
Media Library: Replacing a media item in recent section

### ISSUE THREAD

**Issue by armanforghani** [OrchardCMS/Orchard#7452]
A user with ```ManageOwnMedia``` permission (without ```ManageMediaContent```) cannot replace a media listed in recent section of Media Library. (```Unauthorized``` error)
This is because when the user click on the Replace button in the recent section, an empty string will pass to the Import action method as folderPath and this causes Unauthorized error because the user has not ```ManageMediaContent``` permission.

```
if (!Services.Authorizer.Authorize(Permissions.ManageMediaContent) && !_mediaLibraryService.CanManageMediaFolder(folderPath)) {
    return new HttpUnauthorizedResult();
}
```

@hannan-azam, @sebastienros

**Comment by hannan-azam** [comment]
@armanforghani thanks for reporting the issue.
@sebastienros i reproduced the issue and also have a quick small fix which is not that big and not a breaking change. Can we also plan it for 1.10.x?

**Comment by sebastienros** [comment]
yes, target 1.10.x, this feature has been added there, right?
