### ISSUE TITLE
Installing themes and modules from the Orchard CLI

### ISSUE THREAD

**Issue by podelo** [OrchardCMS/Orchard#7453]
I performed a basic Orchard setup (Site name, database connection, etc.) and it works fine.

Now, I need to develop a script to automate the install of some custom themes and modules. Here is my .bat code, running from src/Orchard.web folder:

```
cd bin
orchard @../orchard_commands.txt
```

Here is my "orchard_commands.txt" file:

```
package install Orchard.Theme.Theme1 "path/to/Themes"
package install Orchard.Theme.Theme2 "path/to/Themes"
theme activate Theme1
theme activate Theme2 
package install Orchard.Module.EloquaLookup "path/to/Modules"
package install Orchard.Module.EncryptionLinks "path/to/Modules"
feature enable Orchard.ImportExport
feature enable Orchard.Localization
```

When I execute the .bat file, I run into the following issue:

**"The application domain in which the thread was running has been unloaded"**

When I perform the themes and modules installs using the Orchard dashboard, it works perfectly, but I m unable to do it from the CLI. Also, running every command separately works well too.

Any idea ?

Thanks

**Comment by ActivePHOENiX** [comment]
You need to use Recipes in order to achieve what you intended to do. Orchard way of automation is different than a Linux/Windows cmd Batch file queued jobs.
Have a look at pre-defined recipes available in orchard, you see their name in setup page dropdown and the file and its content is available with a recipe extension.
you will succeed to reach your goal by learning how to define and execute a recipe.

Best regards.

**Comment by podelo** [comment]
Thanks for this reply. Is this possible to run recipes from command line ? My goal is setup automation without having to configure stuff using Orchard's UI.

If it's possible, please provide me some help link because I was not able to find one in the documentation or somewhere else.

Thanks

**Comment by sebastienros** [comment]
Yes, look at these commands https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Recipes/Commands/RecipesCommands.cs

**Comment by podelo** [comment]
Thanks, I will investigate further next week on this.

**Comment by podelo** [comment]
I m unable to understand certain things. The "recipe" command is not available by default when using the orchard.exe CLI. I noticed that the link you sent me deals with some code in Orchard.Recipes module. So I have to install the Orchard.Recipes module first ? How can I use the "recipes execute" command next ? Please clarify things for me because I m unable to find any documentation on this topic.

Thanks a lot

**Comment by podelo** [comment]
Ok my bad. I finally understood the "recipes command".

Now, when I execute "recipes execute Orchard.Setup <recipeName>", it says "Recipe scheduled for execution successfully". Does it mean the recipe has been loaded or just scheduled ? If scheduled, how could I manage the execution of the recipe ?
