### ISSUE TITLE
Remove IProjectionManagerExtension

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#7455]
https://github.com/OrchardCMS/Orchard/pull/7417

**Comment by BenedekFarkas** [comment]
Shouldn't this target 1.10.x (1.10.4 release) instead? #7417 was merged into 1.10.x (and released in 1.10.3). Btw the change should be just that the extension's logic is moved to ProjectionManager, right?

**Comment by sebastienros** [comment]
If it's a breaking change it can't. Unless there is no obvious implementations, or there is a way to be non-breaking,

**Comment by BenedekFarkas** [comment]
Well, it can be theoretically breaking if someone has their own IProjectionManager implementation. Orchard is all about extensibility, but I find that very unlikely.
But anyway, we've got the PR for dev, I'd still consider that good enough. :)
