### ISSUE TITLE
Update Gulpfile.js to also add autoprefixes through cssnano

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/Orchard#7467]
The default for cssnano is to _only remove_ not required vendor prefixes, but it would be great if it also _added_ missing prefixes. This is especially important for themes including Bootstrap 4 SASS directly as BS4 no longer includes prefixes and relies on autoprefixer.

This is easily achieved by updating this line in Gulpfile.js:

`autoprefixer: { browsers: ["last 2 versions"] },`

to

`autoprefixer: { browsers: ["last 2 versions"], add: true },`

However, this does result in a disconnect between the minified and the unminified dev version, so perhaps we need to include gulp autoprefixer to achieve the same result in the devStream. Do we even care?

Unless we change the flow completely to first create the unminified dev version, then create the minified version based on it.

**Comment by DanielStolt** [comment]
I actually was not aware that the `add` parameter was needed - I thought the default behavior was to add as well as remove.

I think we should add the required parameter, and I definitely think we should do the same in non-minified and minified outputs, they should not risk behaving differently which they currently do. It's an oversight (probably on my part) that no prefixing is done in the non-minified outputs currently. I'll address this.
