### ISSUE TITLE
Enabling/Disabling Module Causes Infinite Loop Trying To Restart Tenants

### ISSUE THREAD

**Issue by coridn** [OrchardCMS/Orchard#7469]
We've ran into an issue where if we disable or enable a module, our web app will sit and spin forever, until an app pool restart.  I've been able to track down where the issue is happening, and am wondering if this approach for a fix is appropriate or not.

Issue is in StartUpdatedShells() in DefaultOrchardHost.cs
https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Environment/DefaultOrchardHost.cs#L128

Inside of here, once a module is disabled or enabled, the tenants is added to _tenantsToRestart.
The current code immediately removes the settings from _tenantsToRestart.  After ActivateShell is called with the settings, the settings object is then 'saved'.  This event is then triggered, and inside of 
https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Environment/DefaultOrchardHost.cs#L320
The settings are once again added to the _tenantsToRestart, causing us to be stuck inside of the loop in StartUpdatedShells()

Our fix at the moment for this is as follows:

```
    void StartUpdatedShells() 
    {
        while (_tenantsToRestart.GetState().Any())
        {
            lock (_syncLock)
            {
                if (!_tenantsToRestart.GetState().Any()) continue;
                var state = _tenantsToRestart.GetState();

                foreach (var shellSettingse in state)
                {
                    Logger.Debug("Updating shell: " + shellSettingse.Name);
                    ActivateShell(shellSettingse);
                }
                state.Clear();
            }
        }
    }
```

This gets us out of the infinite loop and finally allows the web app to finish executing the request.

Considering I'm not that familiar with Orchard, does this fix seem acceptable?

**Comment by sebastienros** [comment]
This looks good, I think you can remove this line `if (!_tenantsToRestart.GetState().Any()) continue;`

**Comment by coridn** [comment]
@sebastienros Thanks!  I'll work on forking and getting a pull request for the change.
