### ISSUE TITLE
When uninstall module in orchard the physical source files are also deleted. How can i overcome the issue any one help me

### ISSUE THREAD

**Issue by krishgop** [OrchardCMS/Orchard#7483]
When i Uninstall module in orchard the physical source files are also deleted. How can i overcome the issue? any one help me

**Comment by Skrypt** [comment]
It is by design I think ...

**Comment by krishgop** [comment]
thanks for the update.

how to re add the module again after i uninstall?

**Comment by Skrypt** [comment]
You can reinstall it from the Orchard Gallery or manually. If it was a custom module then you will need to check with the module programmer to get it back.

**Comment by ViRuSTriNiTy** [comment]
Just deactivate it instead of uninstalling...

**Comment by krishgop** [comment]
AM developing new Theme based on Gentelella html layout how to place url for CSS, script files.

here i have placed the following type 

<link href="~/Themes/Gentelella/Assets/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    

    
    <link href="~/Themes/Gentelella/Assets/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    
    <link href="~/Themes/Gentelella/Assets/nprogress/nprogress.css" rel="stylesheet">
    
    <link href="~/Themes/Gentelella/Assests/iCheck/skins/flat/green.css" rel="stylesheet">
    
    <link href="~/Themes/Gentelella/Assests/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    
    <link href="~/Themes/Gentelella/Assests/jqvmap/dist/jqvmap.min.css" rel="stylesheet" />
    
    <link href="~/Themes/Gentelella/Assests/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    
    <link href="~/Themes/Gentelella/Styles/custom.min.css" rel="stylesheet">
    <script type="text/javascript" src="@Href("~/Themes/Gentelella/Assests/Chart.js/dist/Chart.min.js")"></script>

    <script src="@Href("~/Themes/Gentelella/Assests/Chart.js/dist/Chart.min.js")"></script>

    <script src="@Href("~/Themes/Gentelella/Assests/gauge.js/dist/gauge.min.js")"></script>

    <script src="@Href("~/Themes/Gentelella/Assests/bootstrap-progressbar/bootstrap-progressbar.min.js")"></script>

    <script src="@Href("~/Themes/Gentelella/Assests/iCheck/icheck.min.js")"></script>

    <script src="@Href("~/Themes/Gentelella/Assests/skycons/skycons.js")"></script>

    <script src="@Href("~/Themes/Gentelella/Assests/Flot/jquery.flot.js")"></script>
    <script src="@Href("~/Themes/Gentelella/Assests/Flot/jquery.flot.pie.js")"></script>
    <script src="@Href("~/Themes/Gentelella/Assests/Flot/jquery.flot.time.js")"></script>
    <script src="@Href("~/Themes/Gentelella/Assests/Flot/jquery.flot.stack.js")"></script>
    <script src="@Href("~/Themes/Gentelella/Assests/Flot/jquery.flot.resize.js")"></script>

    <script src="@Href("~/Themes/Gentelella/Assests/flot.orderbars/js/jquery.flot.orderBars.js")"></script>
    <script src="@Href("~/Themes/Gentelella/Assests/flot-spline/js/jquery.flot.spline.min.js")"></script>
    <script src="@Href("~/Themes/Gentelella/Assests/flot.curvedlines/curvedLines.js")"></script>

    <script src="@Href("~/Themes/Gentelella/Assests/DateJS/build/date.js")"></script>

    <script src="@Href("~/Themes/Gentelella/Assests/jqvmap/dist/jquery.vmap.js")"></script>
    <script src="@Href("~/Themes/Gentelella/Assests/jqvmap/dist/maps/jquery.vmap.world.js")"></script>
    <script src="@Href("~/Themes/Gentelella/Assests/jqvmap/examples/js/jquery.vmap.sampledata.js")"></script>

    <script src="@Href("~/Themes/Gentelella/Assests/moment/min/moment.min.js")"></script>
    <script src="@Href("~/Themes/Gentelella/Assests/bootstrap-daterangepicker/daterangepicker.js")"></script>
    <script src="@Href("~/Themes/Gentelella/Scripts/custom.min.js")"></script>

**It getting page not found error**
