### ISSUE TITLE
css, script File not found error

### ISSUE THREAD

**Issue by krishgop** [OrchardCMS/Orchard#7487]
AM developing new Theme based on Gentelella html layout how to place url for CSS, script files.

here i have placed the following type

<link href="~/Themes/Gentelella/Assets/font-awesome/css/font-awesome.min.css" rel="stylesheet">

<link href="~/Themes/Gentelella/Assets/nprogress/nprogress.css" rel="stylesheet">

<link href="~/Themes/Gentelella/Assests/iCheck/skins/flat/green.css" rel="stylesheet">

<link href="~/Themes/Gentelella/Assests/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">

<link href="~/Themes/Gentelella/Assests/jqvmap/dist/jqvmap.min.css" rel="stylesheet" />

<link href="~/Themes/Gentelella/Assests/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

<link href="~/Themes/Gentelella/Styles/custom.min.css" rel="stylesheet">
<script type="text/javascript" src="@Href("~/Themes/Gentelella/Assests/Chart.js/dist/Chart.min.js")"></script>

<script src="@Href("~/Themes/Gentelella/Assests/Chart.js/dist/Chart.min.js")"></script>

<script src="@Href("~/Themes/Gentelella/Assests/gauge.js/dist/gauge.min.js")"></script>

<script src="@Href("~/Themes/Gentelella/Assests/bootstrap-progressbar/bootstrap-progressbar.min.js")"></script>

<script src="@Href("~/Themes/Gentelella/Assests/iCheck/icheck.min.js")"></script>

<script src="@Href("~/Themes/Gentelella/Assests/skycons/skycons.js")"></script>

<script src="@Href("~/Themes/Gentelella/Assests/Flot/jquery.flot.js")"></script>
<script src="@Href("~/Themes/Gentelella/Assests/Flot/jquery.flot.pie.js")"></script>
<script src="@Href("~/Themes/Gentelella/Assests/Flot/jquery.flot.time.js")"></script>
<script src="@Href("~/Themes/Gentelella/Assests/Flot/jquery.flot.stack.js")"></script>
<script src="@Href("~/Themes/Gentelella/Assests/Flot/jquery.flot.resize.js")"></script>

<script src="@Href("~/Themes/Gentelella/Assests/flot.orderbars/js/jquery.flot.orderBars.js")"></script>
<script src="@Href("~/Themes/Gentelella/Assests/flot-spline/js/jquery.flot.spline.min.js")"></script>
<script src="@Href("~/Themes/Gentelella/Assests/flot.curvedlines/curvedLines.js")"></script>

<script src="@Href("~/Themes/Gentelella/Assests/DateJS/build/date.js")"></script>

<script src="@Href("~/Themes/Gentelella/Assests/jqvmap/dist/jquery.vmap.js")"></script>
<script src="@Href("~/Themes/Gentelella/Assests/jqvmap/dist/maps/jquery.vmap.world.js")"></script>
<script src="@Href("~/Themes/Gentelella/Assests/jqvmap/examples/js/jquery.vmap.sampledata.js")"></script>

<script src="@Href("~/Themes/Gentelella/Assests/moment/min/moment.min.js")"></script>
<script src="@Href("~/Themes/Gentelella/Assests/bootstrap-daterangepicker/daterangepicker.js")"></script>
<script src="@Href("~/Themes/Gentelella/Scripts/custom.min.js")"></script>

**Comment by agriffard** [comment]
Assests or Assets ?

Also, have you added a web.config like this in your Scripts and Assets folders to handle the static files ?


```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <system.webServer>
        <staticContent>
            <clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="7.00:00:00" />
        </staticContent>
        <handlers accessPolicy="Script,Read">
            <!-- For any request to a file exists on disk, return it via native http module. AccessPolicy="Script" above is to allow for a managed 404 page. -->
            <add name="StaticFile" path="*" verb="*" modules="StaticFileModule" preCondition="integratedMode" resourceType="File" requireAccess="Read" />
        </handlers>
    </system.webServer>
</configuration>
```
