### ISSUE TITLE
Moving project from Wordpress to Orchard

### ISSUE THREAD

**Issue by danitoto** [OrchardCMS/Orchard#7490]
Hi guys! I´m moving a project from Wordpress to Orchard, but before doing it I need to know if Orchard supports these things from the go or if these have to be created from scratch:

1. **Template options (themes):** The current website uses a custom homepage and 6 different page templates (which are basically the same except the banner and a custom menu at the sidebar).
2. **Banner administration:** Currently I have a Wordpress plugin that handles the main banner and a small banner in the pages. I´m wondering If Orchard has some type of functionality where I could manage banners from the admin.
3. **More than one navigation menu:** Currently the website has one main nav and 6 other menus.

I know the best way to find out is to install and test, but I would like to know a little bit more before I proceed to install in a couple of days.

Thanks guys!

**Comment by sebastienros** [comment]
Yes, these are supported, feel free to hang out on the Gitter forum for some help.
