### ISSUE TITLE
Why ExtensionLoaderCoordinator.SortExtensionProbeEntries  return a list

### ISSUE THREAD

**Issue by LE88I5** [OrchardCMS/Orchard#7492]
ExtensionLoaderCoordinator.cs:

            return firstNonEmptyGroup
                .OrderByDescending(probe => GetVirtualPathDepedenciesModificationTimeUtc(virtualPathModficationDates, probe))
                .ThenBy(probe => probe.Loader.Order)
                .ToList();

why not:
return firstNonEmptyGroup
                .OrderByDescending(probe => GetVirtualPathDepedenciesModificationTimeUtc(virtualPathModficationDates, probe)).First()

can explain it to me? Thank you。

**Comment by sebastienros** [comment]
If your issue is that the name `firstNonEmptyGroup` doesn't convey the notion of a list of items, then maybe we should change it. Or is there another issue in the code?

**Comment by LE88I5** [comment]
@sebastienros  Thank you for your answer, there is no other issue, I just think it can returns the first loader.
