### ISSUE TITLE
System.ArgumentOutOfRangeException in Orchard.Packaging.Extensions.PackageExtensions.ExtensionId

### ISSUE THREAD

**Issue by TomaszKustra** [OrchardCMS/Orchard#7497]
If "packageId" is in other format then expected then it throws exception.

My fix:

 private static string ExtensionId(bool isTheme, string packageId)
        {
            if (isTheme && packageId.StartsWith(Services.PackagingSourceManager.GetExtensionPrefix(DefaultExtensionTypes.Theme)))
            {
                return packageId.Substring(Services.PackagingSourceManager.GetExtensionPrefix(DefaultExtensionTypes.Theme).Length);
            }
            else if (packageId.StartsWith(Services.PackagingSourceManager.GetExtensionPrefix(DefaultExtensionTypes.Module)))
            {
                return packageId.Substring(Services.PackagingSourceManager.GetExtensionPrefix(DefaultExtensionTypes.Module).Length);
            }
            else return packageId;

            //return isTheme ?
            //    packageId.Substring(Services.PackagingSourceManager.GetExtensionPrefix(DefaultExtensionTypes.Theme).Length) :
            //    packageId.Substring(Services.PackagingSourceManager.GetExtensionPrefix(DefaultExtensionTypes.Module).Length);

        }

**Comment by sebastienros** [comment]
Can you explain which scenario you are doing?

**Comment by TomaszKustra** [comment]
Simple search in gallery module for example with 'seo'.

**Comment by pszmyd** [comment]
Well, in this case you should also change the `IsTheme` extension method. 

Could you please give us your package name? We have a number of conventions in Orchard and following those is usually the best course of action, except you have a *really good* reason not to do so.

**Comment by TomaszKustra** [comment]
Orchard.Packaging.Extensions class PackageExtensions

![orchard1](https://cloud.githubusercontent.com/assets/4504375/21752728/43a3278c-d5de-11e6-93be-8965526023a1.PNG)

![orchard2](https://cloud.githubusercontent.com/assets/4504375/21752729/495b01d6-d5de-11e6-8b8c-929d7ff03b13.PNG)

![orchard3](https://cloud.githubusercontent.com/assets/4504375/21752730/4d08c624-d5de-11e6-8df2-657fb4083d4f.PNG)

**Comment by sebastienros** [comment]
I am pushing a fix as right now the search is almost completely broken but there might be some other issues when downloading themes this way.
