### ISSUE TITLE
Need a "Do Not Vary by Query String Parameters" cache setting

### ISSUE THREAD

**Issue by joshberry** [OrchardCMS/Orchard#7498]
It would be very useful to have a negative counterpart to the VaryByQueryStringParameters property for cache settings. In many cases, it's cumbersome (and error prone) to list all the query string parameter used on the site when you only want to keep a few of parameters from varying. The example we run into all the time is the Google AdWords gclid parameter. We never want to vary the cache on this since it's only used client-side by analytics.js.

I propose that we add a new field to the cache settings where you can list the query string parameters that you don't want to vary the cache on. It would look something like this...

![image](https://cloud.githubusercontent.com/assets/1396816/21615435/2377fad0-d1a3-11e6-9c63-dc12fec97f43.png)

We are already using this modification on several sites. If folks are interested, I'd be happy to submit it as a PR.

**Comment by DanielStolt** [comment]
I agree that this feature is needed, but the proposed UI is a bit confusing IMO as you would effectively always leave one of the fields empty (any other combination would be redundant).

It also doesn't address the scenario "don't vary by any query string parameters at all" which is also missing today. And btw the current UI where an empty field means unfiltered, and when you enter in a value it suddenly flips the semantic to additive, is also a bit illogical.

Instead I propose something like the following:

![image](https://cloud.githubusercontent.com/assets/3889090/21752263/73b82b60-d5d5-11e6-85b8-975986344299.png)

**Comment by joshberry** [comment]
I like your approach much better. I'll update and submit a PR.

**Comment by DanielStolt** [comment]
Look forward to reviewing it! Thanks @joshberry!

**Comment by joshberry** [comment]
Check it out: #7509. Let me know if you have any suggestions for improvement.

**Comment by DanielStolt** [comment]
Not much, wrote a couple of minor comments on the PR.
