### ISSUE TITLE
Contrib.GoogleAnalytics and 1.10.1

### ISSUE THREAD

**Issue by edikaufmann** [OrchardCMS/Orchard#7500]
... could not find a specific Forum, thanks for your time: 
in 1.10.1 I'm not able to run the Contrib.GoogleAnalytics anaymore.
When adding the module in WebMatrix all seems fine i.e. I see the Anlytics' tab. HOWEVER when running on the deployed site I don't see the 'Analytics' tab in 
the dashboard anymore.
I then tried to add Contrib.GoogleAnalytics to the solution (VS2015) but always get error seen below. I also changed  the target.Framework to 4.5.2 and 
experimented with the 'System.Web.Mvc' version --> no success! . 

any help and your time is appreciated, thanks, ed

Error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1705	Assembly 'Orchard.Framework' with identity 'Orchard.Framework, Version=1.10.1.0, Culture=neutral, 
PublicKeyToken=null' uses 'System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
which has a higher version than referenced assembly 'System.Web.Mvc' with identity 'System.Web.Mvc, 
Version=4.0.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	
Contrib.GoogleAnalytics	D:\CMSites\ORG_1101s\src\Orchard.Web\Modules\Contrib.GoogleAnalytics\

**Comment by ViRuSTriNiTy** [comment]
Open the `NuGet package manager console` (Tools -> NuGet Package Manager -> Package Manager Console), select `Contrib.GoogleAnalytics` from the `Default project:` drop down, type `Install-Package Microsoft.AspNet.Mvc`. This should update the MVC version to 5.2.3.

**Comment by edikaufmann** [comment]
thanks for your time. With your instruction I was able to add 'Contrib.googleAnalytics' to the vs2015 solution.
Then, the 'Build' ran without any errors! So far so good. 

However:
Now I cannot find the .dll file?! I would assume that the 'build' created a 'Contrib.GoogleAnalytics.dll' file.
I do this successfully for other 'projects' and, in turn, use that .dll on my deployed site!

what in the world do I miss here - thanks again for your time and help, ed

**Comment by Piedone** [comment]
This won't be too constructive but you can also use this module that does pretty much the same but is kept up-to-date: https://github.com/Lombiq/Orchard-Simple-Analytics/tree/dev But only if you need users to be able to edit the analytics script, otherwise just add it to the Document shape override for example.

**Comment by urbanit** [comment]
The original one for 1.10.x is here: [](https://github.com/urbanit/Urbanit.GoogleAnalytics) .Although, as @Piedone said, it is better if you add it in Document.cshtml.

**Comment by edikaufmann** [comment]
Is adding the '<script> google scripts</script>' into the head of Document.cshtml all I need to do ?
PS: I see the script in the head tag !

when reading the Doc it says: 
"Just add the analytics script under the site Settings. This script (wrapped into a script tag) will be injected into the head of your site. You can also configure whether to inject the script on the admin site or not."

- Do you mean with site Settings: dashboard / settings OR just the Document.cshtml (as I did!)?
- How do I configure this for the admin site?
- I have seen an EditorTemplate 'Parts.AnalyticsSettings.SiteSettings.cshtml'. But I never see this template?!?
- shouldn't I get a dashboard 'analytics tab' or something alike?

perhaps I don't see the forest for the trees ...
thanks for clarifying, ed

**Comment by Piedone** [comment]
It's on the admin under Settings, just among the default site settings, no other tab. You can also select to inject it on the admin there. `AnalyticsScriptInjectingFilter` injects the script, so there won't be a corresponding template.

**Comment by edikaufmann** [comment]
ok, thanks you guys
