### ISSUE TITLE
Content field value is always null after setting it and building it's editor

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/Orchard#7505]
It's a DefaultValue bug in all field drivers.

**Comment by BenedekFarkas** [comment]
@sebastienros we have the fix for this, which branch shall I target with a PR?

**Comment by sebastienros** [comment]
1.10.x., I will merge it  in 1.10.2
How do you want to fix it?

**Comment by BenedekFarkas** [comment]
@sebastienros here's the PR!
