### ISSUE TITLE
LastLoginUtc : 2017 years ago

### ISSUE THREAD

**Issue by abhishekluv** [OrchardCMS/Orchard#7506]
![](http://i.imgur.com/WWafxyu.png)
With a clean install of Orchard, LastLoginUtc is null. 
Where should we set it's value? In the SetupService or somewhere else.
```
var userData = user.As<UserPart>();
userData.LastLoginUtc = _clock.UtcNow;
```

**Comment by ViRuSTriNiTy** [comment]
same issue #7071

**Comment by abhishekluv** [comment]
Thanks @ViRuSTriNiTy

**Comment by Piedone** [comment]
Closing as duplicate.
