### ISSUE TITLE
Orchard.Specs: Host app installation misses the latest features

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#7527]
I'm not 100% sure if this intentional (since many of the newer features don't have SpecFlow tests): The `OrchardSiteFactory` has the basic bindings for SpecFlow tests to set up the host application, `GivenIHaveInstalledOrchard` is one of them. It creates a clean installation and defines which Core features, themes and modules should be used by the host application.

The list of Core features does not contain `Reports` and the Module list is missing the following: `Orchard.AuditTrail, Orchard.Azure.MediaServices, Orchard.CustomForms, Orchard.Dashboards, Orchard.DynamicForms, Orchard.Glimpse, Orchard.jQuery, Orchard.Media, Orchard.MediaPicker, Orchard.MessageBus, Orchard.OpenId, Orchard.Redis, Orchard.Rules, Orchard.TaskLease`.

**Comment by sebastienros** [comment]
they are not used so it doesn't matter.
