### ISSUE TITLE
Request.IsAuthenticated issue on LogOn in openid module

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#7529]
1-set up the site (using default recipe) to create admin account
2-enable openid modules inside dashboard
3- now stop debug visual studio
4-F5 again
5-go to http://localhost:30321/OrchardLocal/users/account/logon to logon as admin
6-it hits this code in openid module
`         [HttpGet]
public ActionResult LogOn() {
            if (Request.IsAuthenticated) {
                return Redirect(Url.Content("~/"));
            }
            return View(_openIdProviders);
        }`
7-it shows true of Request.IsAuthenticated (so, return to home page which you can not go further)
8-but the page UI shows:
Powered by Orchard © The Theme Machine 2017.Sign In
notice Sign In (It is not Sign Out and dashbord)

**Comment by infofromca** [comment]
Resolve method:
Follow the same method in Orchard.Users module

**Comment by sebastienros** [comment]
In the new OpenId module from the dev branch?

@ThaerAlAjlouni can you take a look (_no_ is a valid answer)

**Comment by infofromca** [comment]
yes

**Comment by ThaerAlAjlouni** [comment]
@sebastienros I will have a look at it in the next couple of days

**Comment by ThaerAlAjlouni** [comment]
I can't reproduce it locally, my current branch is @ hash: [30e669e83f6095f326a9bef96a5fa9a896e1509c](https://github.com/OrchardCMS/Orchard/commit/30e669e83f6095f326a9bef96a5fa9a896e1509c).

On my machine after the step 6 it shows the home page with the correct links as shown below:
![image](https://cloud.githubusercontent.com/assets/22820843/22399402/7355228e-e5a4-11e6-9e2e-3de046eca1e3.png)

**Comment by sebastienros** [comment]
@infofromca can you provide a better repro?
