### ISSUE TITLE
How/where are child theme files selected?

### ISSUE THREAD

**Issue by petermorlion** [OrchardCMS/Orchard#7531]
I've created a child theme, with its own css file. However, when I activate the theme, the parent theme's css is still used. I can't provide a lot more info, but I'm willing to debug it myself. The [docs](http://docs.orchardproject.net/en/latest/Documentation/Customizing-the-default-theme/) mention:

 > Orchard first looks to that theme to resolve files, and if not found, it will look to the parent (BaseTheme) to find the files instead (and so on... even your parent theme can have it's own parent).

Can anyone point me to where this happens do I can debug it? I've looked at ´ThemeAwareViewEngine´, but I can't see my css file being loaded in there anywhere.

**Comment by Devqon** [comment]
I think this depends on how the (css) file is included. Is it registered in a ResourceManifest or is it included like `Style.Include(".../myFile.css")`?

**Comment by petermorlion** [comment]
I'm using `Style.Include("site.min.css")` in my parent theme.

**Comment by sebastienros** [comment]
This should work.

Technically when a css is rendered, it's by using a specific shape type, and this way a theme can take over how it's rendered. This is why you couldn't find the code.
It's very improbable that this feature is broken as many sites depend on it.
We'll try to repro the issue.

**Comment by petermorlion** [comment]
Ok, then I'd propose to close this. Must be something I'm doing wrong. Maybe even some form of caching? I'll look into my code.
