### ISSUE TITLE
Framework: Pager doesn't respect MaxPageSize site setting if pageSize is 0 (1.10.1)

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#7541]
As far as I can tell, the addition of the `MaxPageSize` site setting was to prevent users from querying a lot of content items accidentally, when you are using the Pager (`Orchard.UI.Navigation.Pager`).

Let's consider the following settings:

- PageSize (Default number of items per page): 10
- MaxPageSize (Maximum number of items per page): 20
- MaxPagedCount (Last index of items in pages): 0

If you go to `Admin/Contents/List?pageSize=0&page=1` (which is the same as opening `Admin/Contents/List` and then selecting `All` for page size at the bottom of the page), all the content will be queried. In this case, only 20 content items should be queried (and the `All`, `50` and `100` options shouldn't be available in the page size selection list).

**Comment by sebastienros** [comment]
Yes, when PageSize is 0 it should actually use MaxPageSize if it's defined.
