### ISSUE TITLE
openid: lack of Sign In of openid

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#7542]
should we put 
 AuthenticationManager.SignIn(claimsIdentity);
inside public RedirectResult LogonCallback() method

**Comment by sebastienros** [comment]
Can you explain the issue with a little more details, I am not as familiar with this module.
/cc @ThaerAlAjlouni

**Comment by infofromca** [comment]
after successful  challenge , we should sign in on the opened level.
also we may consider assign something to user, like:
HttpContext.User = new DemoPrincipal	(AuthenticationManager.AuthenticationResponseGrant.Principal);

**Comment by ThaerAlAjlouni** [comment]
@infofromca What is the use case that needs such a call? I mean why do you see this needed?

**Comment by infofromca** [comment]
from logon (get)  =>challenge =>LogonCallback, I can not see the **SignIn** code, which I guess is related to this issue
https://github.com/OrchardCMS/Orchard/issues/7529
===

if the nticationManager.SignIn(claimsIdentity) is not suitable, then I think we should use something like:
 _authenticationService.SignIn(user, rememberMe);

**Comment by ThaerAlAjlouni** [comment]
But the user will be signed in, even if the function is not called. And a cookie will be set, and the logged in user info can be read by accessing the `WorkContext.CurrentUser` property or the `_httpContextAccessor.Current().GetOwinContext().Authentication.User` property.

So why do you see that calling the ` authenticationManager.SignIn` is necessary?
