### ISSUE TITLE
openid: wrong route for logon

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#7545]
can not call logon inside openid module, but only Orchard.Users module after enable google feature.

httpget and httppost

**Comment by infofromca** [comment]
this is because 
if (IsAnyProviderSettingsValid() == false)
                return Enumerable.Empty<RouteDescriptor>();
inside OpenId.cs
if you just enable facebbok, it  will hit return Enumerable.Empty<RouteDescriptor>();
after you add client id,secret, it will not hit openid.cs again.
only if you enable, disable any (other) feature again, it will get true of IsAnyProviderSettingsValid(), and make the openid router effective

**Comment by ThaerAlAjlouni** [comment]
Yes we need it, and that is because registering a route of invalid settings will cause more errors when a user tries to log in to a **OpenId** provider with invalid settings, what you need instead of enabling/disabling another feature is to restart your app after changing any **OpenId** settings.

**Comment by sebastienros** [comment]
If a restart is necessary after the settings have changed, then it would be nice to display a notification. Even better a sticky notification (admin banner) but it's a little harder, this is what we are doing for the OpenId module in Orchard Core (not the same module though).
