### ISSUE TITLE
Openid: disable, then enable google feature produce error

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard#7546]
![googledisable-enable](https://cloud.githubusercontent.com/assets/297675/22401123/7913bedc-e596-11e6-99fd-41462aa7e983.png)

**Comment by infofromca** [comment]
i found it
the seeting of LogonCallbackUrl should be  /Users/Account/LogonCallback

**Comment by sebastienros** [comment]
Is it documented somewhere?

**Comment by infofromca** [comment]
yes, on the setting page, the hint said using
~/Users/Account/LogonCallback

**Comment by ThaerAlAjlouni** [comment]
The **`Microsoft.Owin.PathString`** `struct` is not accepting the "~" character at the beginning of the string passed to its `constructor` which is causing the error. We need to remove it from the default values (in the ` Constants.General` class) which will reflect elsewhere in the solution.

**Comment by ThaerAlAjlouni** [comment]
@infofromca @sebastienros 
Shouldn't this be closed as the fix was merged?
