### ISSUE TITLE
ContentHandler.OnCreated<TPart> get called even when validation fails.

### ISSUE THREAD

**Issue by armanforghani** [OrchardCMS/Orchard#7548]
This may be related to #6534.

I have a customer part and want to fire an event when a new customer created. I decided to use ```ContentHandler``` events because there is no simple solution for that in ```Driver```.

But ```ContentHandler.OnCreated<TPart>``` get called even when validation fails in ```Driver``` and customer is not created.

**Comment by siyamandayubi** [comment]
It is better to use ContentHandler.OnPublished event. The Creation of the ContentItem is done in the Controller before calling the Drivers, and after that, in case of no validation error, the ContentItem will be published.

**Comment by carlwoodhouse** [comment]
or possibly onUpdated :)

**Comment by armanforghani** [comment]
@siyamandayubi Yes, but still this is a bug. Also note that you may want to create item as a draft.
@carlwoodhouse ```OnUpdated``` executes after every update not after creation.

**Comment by sebastienros** [comment]
Created doesn't mean that the content item has been validated correctly. What you need is either Published, or Versioned (draft).
It's not a bug, it's by design.

**Comment by armanforghani** [comment]
@sebastienros I disagree. Created should mean Created and the content item should not be created before validation. Also when validation has been failed the ```OnCreated``` event fired while there is no record in database (So this is not real creation). 
On the other hand a content item will be created once but it may be published or versioned several times. What is the event we can hook up into the real creation process?
Thank you for closing the issue!

**Comment by sebastienros** [comment]
Well yo can disagree with how it behaves, but it has been design to do what it is currently doing, so it's not a bug. And in this context, Created means the Content Item has been created, not that is has been updated, that it's valid, or even persisted. 

So yes, if the issue is "ContentHandler.OnCreated<TPart> get called even when validation fails." then I need to close it because this is exactly what it's supposed to do, and what it does, we even have unit tests to ensure it does it.

As explained what you need to use is either Published or Versioned.

**Comment by armanforghani** [comment]
As I mentioned above Published and Versioned are not suitable because I want to execute the code once the item created not anytime it is published.

**Comment by sebastienros** [comment]
Ok I see what you mean. Then you could use a test on the version number. And I also understand the confusion with the CreatedUtc.

**Comment by mehranrezaei** [comment]
This is a BUG!
@sebastienros 
You can't test on the version number because in that case the version number is also equal to 1 and you have no way to know if the content item was actually created or not.
This is a clearly incorrect design. And it creates problems in various situations.
