### ISSUE TITLE
Special characters can break infoset

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/Orchard#7560]
If you try to save a special character (know about [vertical tab](https://en.wikipedia.org/wiki/Control_character) but surely this is not the only one) to an infoset-backed but also record-stored content part then you can cause a YSOD only fixable by editing the DB. Such a character can mess up the infoset's XML, resulting in the below exception being thrown.

```
2017-02-07 04:33:07,785 [15] Orchard.ContentManagement.DefaultContentManager - (null) - ArgumentException thrown from IContentHandler by Orchard.ContentManagement.FieldStorage.InfosetStorage.InfosetHandler [(null)]
System.ArgumentException: '', hexadecimal value 0x0B, is an invalid character.
   at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(Int32 ch, Char* pDst, Boolean entitize)
   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.Linq.ElementWriter.WriteStartElement(XElement e)
   at System.Xml.Linq.ElementWriter.WriteElement(XElement e)
   at System.Xml.Linq.XElement.WriteTo(XmlWriter writer)
   at System.Xml.Linq.XNode.GetXmlString(SaveOptions o)
   at Orchard.ContentManagement.FieldStorage.InfosetStorage.Infoset.get_Data()
   at Orchard.ContentManagement.FieldStorage.InfosetStorage.InfosetHandler.Creating(CreateContentContext context)
   at Orchard.ContentManagement.DefaultContentManager.<>c__DisplayClass41_0.<Create>b__0(IContentHandler handler)
   at Orchard.InvokeExtensions.Invoke[TEvents](IEnumerable`1 events, Action`1 dispatch, ILogger logger)
```

The offending character will be saved to the record's field but it won't succeed getting into the infoset, thus this write operation will be retried forever, without success. I guess that if there's no record then just saving the item would fail.

We should probably do some encoding in `InfosetHelper.Store()`? Note that I experienced this with `TitlePart`, so maybe it's only affecting infoset values if they're stored in an attribute like in this case.

**Comment by BenedekFarkas** [comment]
The solution might be to sanitize all input in forms with regards to control characters (i.e. character code is less than 32), although some might be actually valid to store in the DB.

**Comment by sebastienros** [comment]
I doubt that an XmlDocument would not encode these chars automatically. Can you repro it from a console app?

**Comment by sebastienros** [comment]
Let's look at the XML specification and XDocument documentation to see what chars are not allowed.

Repro:

```
            XDocument doc = new XDocument();
            doc.Add(new XElement("foo", @"bar" + Char.ConvertFromUtf32(20) + /*Char.ConvertFromUtf32(0x0b) +*/ "bar"));
            Console.WriteLine(doc.ToString());
```

**Comment by sebastienros** [comment]
https://www.w3.org/TR/xml/#NT-Char states the allowed chars, to summarize, any char less than 0x20 is forbidden with the exception of 0x9, 0xA, and 0xD.

This SO answer explains how to read any document with invalid chars: http://stackoverflow.com/a/18020992/142772
Not sure if the same exists on serialization, or we'll need to sanitize once the infoset is read.

**Comment by carlwoodhouse** [comment]
Have also experienced this though i forget what the character was!

**Comment by sebastienros** [comment]
Or read the content using:

```
XDocument xDocument = null;
XmlReaderSettings xmlReaderSettings = new XmlReaderSettings { CheckCharacters = false };
using (XmlReader xmlReader = XmlReader.Create(filename, xmlReaderSettings))
{
    xmlReader.MoveToContent();
    xDocument = XDocument.Load(xmlReader);
}
```

**Comment by Piedone** [comment]
I've pushed a failing test into this branch: https://github.com/Lombiq/Orchard/commits/issue/ORCH-208 (see `InfosetFieldStorageProviderTests.ForbiddenXmlCharactersDontBreakInfoset`). However, on the fix I'd need some advises.

The issue is that you can save such invalid characters into an `XElement` and you can read it out if you read the attribute or the node's value directly but you'll see this exception if you do a `ToString()`. This is somewhat inconsistent IMO and there is no way to tell `ToString()` to ignore such errors.

I've thought about the following fixes:

- Go through `XmlReader` as Sebastien suggested above, but that sounds a bit heavy for me (we don't use `XmlReader` here otherwise, so we'd introduce it just for this).
- Custom `XElement.ToString()` implementation: we can write some tree-walking code to build the XML string by accessing the elements' and attributes' values, which, since this works, wouldn't fail.
- Using `XmlConvert.EncodeName()` when saving values and `XmlConvert.DecodeName()` when reading them. This would work I think perfectly but might break already saved values in existing installations if they look like encoded XML characters.
- Custom escaping logic: we could minimize the possibility of breaking existing data if we just escape the 29 control characters causing issues (escaping "\0" e.g. is simply "\\0").

What do you think? None of these seem too appealing to me...

**Comment by Piedone** [comment]
Also, there's more than one place where the Infoset XML is directly written, so whatever we do should affect all of these:

- `InfosetHelper`
- `InfosetPart`
- `InfosetStorageProvider`

**Comment by Piedone** [comment]
The approach we'll take as discussed during the meeting: Throw an exception when saving offending characters that'll explain which character is invalid and tell you not to use it. It also seems that the current behavior is a bug in `XDocument` since it either should encode the characters, or throw an exception as soon as you try to save it.
