### ISSUE TITLE
How to get  Count value of content items  in Taxonomy Item ?

### ISSUE THREAD

**Issue by jiangyo4** [OrchardCMS/Orchard#7573]
I  use Orchard 1.10.1. I have a ContentType( product) that has a taxonomy (book,toy,clothing.....).The Content Item (product) has a taxonomy item. Now,I want to display  statistics .  Example,(book:30pages  toy:20pages  clothing:50pages). But I can't find out how to do it. I tried to modify TaxonomyItemLink.cshtml 

@{
 var _taxonomyService = WorkContext.Resolve<Orchard.Taxonomies.Services.ITaxonomyService>();
 var NumberOfContentItems = _taxonomyService.GetContentItems(part).Count(); 

}
but  it doesn't work ,in addition, How to represent  the data(book:30pages  toy:20pages  clothing:50pages) by Histogram or Bar chart? Please help  me ,Thanks!

**Comment by MatteoPiovanelli-Laser** [comment]
Hi,

WHen you say it does't work, what do you mean exactly?

Did you try:
```
var NumberOfCI = _taxonomyService.GetContentItemsCount(yourTermPart);
```
The following may also work:
```
var NumberOfCI = yourTermPart.Count;
```

Now, If I remember correctly, the Count for a TermPart is updated asynchronously, so it may not be 100% correct at all times.

Concerning presentation, I am a bit out of my depth, but maybe jquerygrid.net may work for you.

**Comment by jiangyo4** [comment]
MatteoPiovanelli-Laser,
Thank  you for  reply! It's ok. I have yet another question to ask.Now,  The  data(book:30 toy:20   clothing:50 ) only  display  on  web page.I want to sort the data  by count  and  start/end  time .Example,count(descending)&start/end  time(2017.2.10/2017.2.11). finally(1.clothing:10  2.book:5  3.toy:2 ) .

Thank you very much in advance!

**Comment by MatteoPiovanelli-Laser** [comment]
Hi,

To order by count, just put the counts for each category in an IEnumerable, e.g. a List<int>, and sort that.
Regarding start/end time, I don't know enough about your ContentTypes and data structures to know what you are talking about.

Best,
Matteo

**Comment by sebastienros** [comment]
Please use the issue tracker for issues, questions can be addressed on the Gitter forum. Thanks.
