### ISSUE TITLE
Taxonomy  bug?

### ISSUE THREAD

**Issue by jiangyo4** [OrchardCMS/Orchard#7578]
Hi,
I use Orchard 1.10.1. I created a Content-Type called product（include 2 taxonomy).

The taxonomy  are  Category(book,toy,clothing.....)  and color(red,blue,black....).

When Filters   taxonomy term  in the dashboard,  
I  choose  Has Terms and  Category with  is one of（filters  Category,not color）.
but, The filters  display  all(Category,color)  Content Items.

why! please  help,Thanks.

**Comment by sebastienros** [comment]
Can you provide some detailed repro steps, or screenshots ?

**Comment by jiangyo4** [comment]
![1](https://cloud.githubusercontent.com/assets/1290737/23046410/37feb958-f4e4-11e6-8c14-32497b11a9f7.PNG)
![3](https://cloud.githubusercontent.com/assets/1290737/23046417/49c21784-f4e4-11e6-92c1-4692188739b1.PNG)
![4](https://cloud.githubusercontent.com/assets/1290737/23046427/552eb2a8-f4e4-11e6-8c92-bc1d1936b49f.PNG)

**Comment by jiangyo4** [comment]
Hi,sebastienros
I want to display statistics . Example,(book:30 toy:20 clothing:50)
when has a  taxonomy,the work is ok. It  display statistics  by Projection.
![11](https://cloud.githubusercontent.com/assets/1290737/23054980/0b3358a4-f51e-11e6-9f60-8a2d2cf50254.PNG)
![12](https://cloud.githubusercontent.com/assets/1290737/23055162/4810281e-f51f-11e6-9f4c-0de7cac8a132.PNG)

**Comment by sebastienros** [comment]
Closing this issue as there is no bug. Please go on the gitter forum to ask for support. Will be faster and easier.
