### ISSUE TITLE
Build errors of Orchard for latest zip source

### ISSUE THREAD

**Issue by lookatthebluemoon** [OrchardCMS/Orchard#7579]
Downloaded this version, unzipped it and then opened the solution file using VS2015 Enterprise [version 14.0.25431.01 Update 3]. When tried to build, getting lots of error related to dll error. Tried several times but still facing the same issues. Build error.

**Comment by sebastienros** [comment]
Where did you get the zip file from?

**Comment by lookatthebluemoon** [comment]
https://github.com/OrchardCMS/Orchard/releases/download/1.10/Orchard.Source.zip

From that location, I got the zip file

**Comment by urbanit** [comment]
Tried dev, 1.10.x & the 1.10 (as provided by the link) and all compiling without any errors.

**Comment by sebastienros** [comment]
Tried it too, just fine.

**Comment by lookatthebluemoon** [comment]
I solved that. I manually copied the packages folder form my colleague's laptop (whose Orchard was running). And then put that under src folder. I see it it had issues to download those packages. I just mentioned this because, if anybody have similar situation  he/she could solve this thing using the same step. Thanks
