### ISSUE TITLE
Consistency displaying login errors

### ISSUE THREAD

**Issue by jardg** [OrchardCMS/Orchard#7588]
This was issued in #1397 too.

I have to add to the issue refered that the same problem arises when users must verify their email address before being able to login. If this option is enabled and the user doesn't validate his e-mail because he didn't notice or the e-mail wasn't sent for any reason He may think that he can't login because of wrong username/email or password. This happens because the ValidateUser method in MembershipService returns null in the three cases where the user can't login.
```
           if ( user == null || ValidatePassword(user.As<UserPart>(), password) == false )
                return null;

            if ( user.EmailStatus != UserStatus.Approved )
                return null;

            if ( user.RegistrationStatus != UserStatus.Approved )
                return null;
```

Should this return an object with IUser and a error property or getting the error in the calling method somehow so the methods using this service could handle the validation with more accuracy?. I would be able to contribute myself with a pull request solving this issue if you let me know which could be the best way to solve this problem.

**Comment by sebastienros** [comment]
Ok. Like return some kind of `IdentityResult` that would describe the current static.
