### ISSUE TITLE
Orchard.Resources - jquery.calendars.min.js in Assets folder instead of being an Gulp artefact

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [OrchardCMS/Orchard#7599]
Hi there,

currently i'm reworking some modules to use the [client-side asset pipeline](http://docs.orchardproject.net/en/latest/Documentation/Processing-client-side-assets).

I came across the Orchard.Resources module whereas the `Assets` folder contains a `Js\Calendars\jquery.calendars.min.js`.
Isn't this file supposed to be a Gulp artefact?

With the current configuration a file `Scripts\Calendars\jquery.calendars.min.min.js` is generated.

I think this is a misconfiguration. Should i provide a PR?

**Comment by DanielStolt** [comment]
Yes looks like a misconfiguration - a PR would be great. We should not keep minified versions in Assets if it can be avoided (like in cases where the minified version is all we have).

**Comment by ViRuSTriNiTy** [comment]
Yeah, minified version removed in PR.

**Comment by sebastienros** [comment]
I'd prefer to have it fixed on dev instead. It's current not an issue to keep it and I don't want to take a risk that close to releasing 1.10.2
