### ISSUE TITLE
Sometimes the ISiteService.GetSiteSettings() doesn't reflect the changes after editing the sitesettings

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/Orchard#7603]
Repro (dev branch):
1. Add a new module.
2. Add a new sitesetting with a custom part with an InputField.
3. Save some data(foo) into that field.
4. You'll see it's in the db, something like
`<Data><TestSettingsPart><TestInputField>foo</TestInputField></TestSearchSettingsPart></Data>`
5. But when you retrieve (_siteService.GetSiteSettings().As<TestSettingsPart>().TestInputField.Value) it (in our case) from IndexingBackgroundTask.Sweep()), it will be null.
6. An exception (System.ArgumentOutOfRangeException in our case) will be shown in various places like /Admin/ContentTypes/Edit/Site and in /Admin/Indexing.
7. BUT if you restart the site, everything will be OK, no exceptions, no issue.

**Comment by Piedone** [comment]
It was actually a lifetimescope issue in the module in question that was hard to surface in its actual form, not an Orchard bug.
