### ISSUE TITLE
SQL Server connection string

### ISSUE THREAD

**Issue by jrmcdona** [OrchardCMS/Orchard#7604]
It has been a while since I set up my blog.  I am working on creating  new dev enviornment for it.

I cannot seem to find where the SQL server connection string is located in the solution?

I have a custom media folder in Azure table storage but I believe everything else (Users, etc.) are store in my SQL server in Azure.   Just cannot seem where to find the setting.

I want to deploy a new instance of the blog and make sure its hitting the dev sql server..

Thanks

**Comment by servabahmani** [comment]
You can find it in ~/App_Data/Sites/Default/SiteSettings.txt file.

**Comment by jrmcdona** [comment]
Actually, every time I deploy to Azure via web publish in the visual studio solution.  Settings.txt is replaced with what was there before.   

I am changing settings.txt in the solution, deleting it from App_Data on the server, then deploying.  Yet my SQL Server settings are not changed.

What is happening here?

Thanks

**Comment by sebastienros** [comment]
The answer you got is correct. 

>Yet my SQL Server settings are not changed.

What do you mean?
- the file gets recreated with the old content?
- or does the file gets correctly created but it seems to use another sql database instead?

**Comment by jrmcdona** [comment]
Looks like the file gets created just fine, but connection string isn't taking my update that I have in settings.txt source code.    Using web publish in Azure.   

Even if I FTP a new version, the connection string is not changing.

**Comment by sebastienros** [comment]
Now the issue is to find where this content is coming from.

> Even if I FTP a new version, the connection string is not changing.

Are you sure you are connecting to the correct website? If you FTP it, you can't have some other content in the file than the one you uploaded. Or you have something else that will recover it.

**Comment by jrmcdona** [comment]
Found the issue, was my bad here.  When I was viewing the filed via FTP, I was clicking view from the server and it was using local cached copy so it appeared to be nothing was changing.    I think I am good for now!

Thanks
