### ISSUE TITLE
CacheManagerExtensions.Get is not thread safe.

### ISSUE THREAD

**Issue by benys** [OrchardCMS/Orchard#7614]
In many places orchard use patern:
```
return _cacheManager.Get("AvailableFeatures", true, ctx =>
                //critical section
        }
```
or
```
           string key = string.Format("{0}-{1}-{2}", path, manifestName, extensionType);
            return _cacheManager.Get(key, true, ctx => {
                //is not critical section
            });`
```

First sample is safe because author use ['string-interning'](https://msdn.microsoft.com/en-us/library/system.string.intern%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) . Second sample is not thread safe. Same string values has different object references.

I would like create patch which wraps "dynamic" string keys with `string.Intern`, if you want.

**Option 1**:
I can add new Extension method with string - key
```
        public static TResult Get<TResult>(this ICacheManager cacheManager, string key, bool preventConcurrentCalls, Func<AcquireContext<string>, TResult> acquire)
        {
            if (preventConcurrentCalls)
            {
                lock (string.Intern(key))
                {
                    return cacheManager.Get(key, acquire);
                }
            }
            else
            {
                return cacheManager.Get(key, acquire);
            }
        }
    }
}
```

**Option 2**:
Wraps with string.Intern() in all places where strings are built. 

**Option 3**:
Should read [Locking on an interned string?](http://stackoverflow.com/questions/6983714/locking-on-an-interned-string)

**Comment by sebastienros** [comment]
I was about that we were already interning the string key, until I read the code and see that we are passing an object. Good catch!

I don't have a string preference about how it's done.
- Adding a new string overload is fine, but it's still prone to errors if the actual variable type is an object. I don't think it's the case anywhere in our code, but Murphy's laws are against us.
- Add a `String,Intern` in all the calls with a `string` will also work, but people won't think about it. It's already hard to grasp that the cache manager is not thread safe.
- Add the logic in the extension method with a static `ConcurrentDictionary<object, object>` of locks. 

I assume the last solution is the less intrusive one and will work in all cases.

Go for it!
