### ISSUE TITLE
Version 1.10.2 has incorrect version number

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/Orchard#7619]
I could be wrong but it looks like the branch tagged 1.10.2 needs the version number updated.
https://github.com/OrchardCMS/Orchard/blob/1.10.2/src/Orchard/Properties/AssemblyInfo.cs

**Comment by sebastienros** [comment]
You are right, this is part of the release process, it will come in time. And there is no tag, when there is a tag they will already be versionned and merged to master.

**Comment by roballred** [comment]
Sorry, I saw that and thought 1.10.2 was out. My bad. I should learn to read release notes first.
