### ISSUE TITLE
Permissions on public media items

### ISSUE THREAD

**Issue by GiuseppeMusso-Laser** [OrchardCMS/Orchard#7620]
Hi all.
I'm facing a problem related to media item permissions.
I have several contributors who can manage thier own media. Besides they can share some media with others contributors. I think shared media can be placed outside users folders.

In this scenario I need to assign them "Manage Own Media" but I don't want to assign "Manage Media" because I don't want them to be able to delete or edit media items outside their own folder.

I propose to create some new Media permissions, all implied by "Manage Media": 
- View Media: users can choose media outside their own folder in a Media Library Picker Field. This permission is implied by the following three permissions.
- Insert Media: users can import media outside their own folder.
- Edit Media: users can edit media outside their own folder.
- Delete Media: users can delete media outside their own folder.

In my scenario, I can grant contributors "Insert Media" and "View Media" so they can share some media items and make use of media items shared by others.

**Comment by sebastienros** [comment]
The only question we have is about the requirement of "View Media". Why would you want to prevent someone from selecting Media items when they are accessible from their urls.

Looks like a UI only reason, but I don't see how it can hurt to be able to select a Media.

**Comment by HermesSbicego-Laser** [comment]
We started from a scenario in which a user was able or to manage all medias or only his own media (in his own folder, and without the ability to View or Select medias owned by other users).
So, the choice to use a ViewMedia permission is to keep untouched scenarios built over that setting/behaviour.
That said, I think in some cases could be useful to prevent users to reference medias "of others", in order to keep owenrship of the "Published Content" strictly related in what is published within it (text and medias).

**Comment by urbanit** [comment]
We have used a internal module based on this [one ](http://gallery.orchardproject.net/Packages/Orchard.Module.CloudConstruct.SecureFileField/1.3 ) explained [here](https://www.cloudconstruct.com/blog/secure-file-field-for-orchard-cms) It is another approach, do not know if it fits.

**Comment by sebastienros** [comment]
Could we rename the View permission to Select Media instead? Just to prevent any confusion?

**Comment by GiuseppeMusso-Laser** [comment]
Sure! I'll post the fix soon.

**Comment by GiuseppeMusso-Laser** [comment]
Fix posted on PR #7622 .
