### ISSUE TITLE
[Orchard Azure deployment] Migration from the deprecated Azure app service : classic Task

### ISSUE THREAD

**Issue by deckbsd** [OrchardCMS/Orchard#7627]
Hello everybody,

Actually in our compagny we are using orchard as the web portal of it. This website is hosted on azure app service.

Microsoft noticed us that, the deploy azure app service : classic task is going to be deprecated. So we tried to migrate our
release definition with the new one ( Azure app service deploy v3 ). But we have some issues.

First , apparently something went wrong with the manifest.xml file. While deploying the app , the "setacl" declared into
this file cannot be applied. We had : 

Failed to deploy App Service.
Error Code: ERROR_USER_NOT_AUTHORIZED_FOR_CREATEAPP
Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295

If we remove the file from the lib/msdeploy folder, at first, the deploy was ok. But few times after we had a new error.

Failed to deploy web package to App Service.
Error: (3/28/2017 8:39:33 AM) An error occurred when the request was processed on the remote computer. Error: Source (iisApp) and destination (contentPath) are not compatible for the given operation. Error count: 1. 
Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295

At this point we didn t find the solution for this.

Did you already solve this task migration ? Somebody does have the solution for this?

Best regards,

**Comment by infofromca** [comment]
have you try to deploy by git? should avoid this issue

**Comment by deckbsd** [comment]
Hello :)

Actually, deploying the website by git is not an option. We are not in continuous deployment. We are using Visual studio online, and when we deploy we are using builds and releases, there are no git deployment tasks that we can use into release definition to deploy via git. We just want to migrate our azure deploy task.

**Comment by infofromca** [comment]
you do not need continuous deployment, only need normal git.
you do not need build and release , azure do that for you.
how?
sebastienros has  a article about it, also others

**Comment by sebastienros** [comment]
This one?
http://www.andrewconnell.com/blog/continous-delivery-of-orchardcms-to-azure-complete-with-dev-test-environments
