### ISSUE TITLE
Taxonomy LocalizationExtension, TryToLocalize change default value

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#7632]
In order to have a coherence between all the localization features of  fields (ContentPickerFiled/TaxonomyField), I suggest to assign the same default value of "TryToLocalize" settings of TaxonomyField ("dev" branch) as per the ContentPickerField (TryToLocalizeItems = true;)
If you agreee we can PR soon the little fix.

**Comment by sebastienros** [comment]
Dev branch?

**Comment by HermesSbicego-Laser** [comment]
Yes, dev branch

**Comment by HermesSbicego-Laser** [comment]
can be closed?
