### ISSUE TITLE
Dev: Add LangVersion to each csproj for C# 5 restriction

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#7640]
#7639 should be fixed first and the rest of the csproj files should be modified after 1.10.x/1.10.2 has been merged into dev.

**Comment by sebastienros** [comment]
I had to remove these from the tests projects in dev.

**Comment by BenedekFarkas** [comment]
I haven't found any issue having this in the test projects - should it be removed from the test projects on 1.10.x?

**Comment by sebastienros** [comment]
I have the issues in dev only. we are fine for now on 1.10.x, until someone complains.

**Comment by BenedekFarkas** [comment]
`Orchard.Glimpse` will be handled as part of #7638.
