### ISSUE TITLE
How to add HTML content to Model.Head

### ISSUE THREAD

**Issue by blachawk** [OrchardCMS/Orchard#7647]
I'm running Orchard 1.10 and all I'm trying to do is extend TheThemeMachine with a javascript test.

I noticed the `@Display(Model.Head)` in documents.cshtml.  So I took an initial step in creating my file called mTest.cshtml inside of TheThemeMachine/Views directory.  

I then referenced my new file within my layout.cshtml file like this...

` WorkContext.Layout.Head.Add(New.mTest(), "10");`

But when I render my page in the browser, I am getting an error that states:

`Orchard.OrchardException: Shape type mTest not found`

What else am I missing from completing this process?

**Comment by sebastienros** [comment]
If you actually created the file in TheThemeMachine AND you are actually changing the Layout file from this theme, then it should just work.

Please ask your questions on gitter. If you think there is a bug just provide the repro steps.
