### ISSUE TITLE
Text.LineEncode token won't necessarily use the client's newline style

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/Orchard#7649]
The Text.LineEncode token changes newline characters to HTML linebreaks, and replaces `Environment.NewLine` to do so. However while `Environment.NewLine` will return `\r\n` on Windows systems the line break characters actually saved to the DB (or submitted via a form, etc.) aren't necessarily Windows-style, thus line breaks aren't always added. Particularly it seems that a form submitted via Chrome on a Windows machine will use `\n` line endings.

One option would be to replace `\n\r` with `<br />`, then try `\n` and `\r` separately too.

**Comment by sebastienros** [comment]
Agreed with the suggestion. But not sure about the `\r` only, even though I usually do it I have never seen it used this way.

**Comment by Piedone** [comment]
`\r` alone can be used too, so I'd include it though supposedly it should be practically non-existent today on the web: https://en.wikipedia.org/wiki/Newline

**Comment by sebastienros** [comment]
Ok
