### ISSUE TITLE
Workflow -> Content Updated, not working for pages

### ISSUE THREAD

**Issue by blachawk** [OrchardCMS/Orchard#7654]
I'm on windows 10, using Orchard 1.10.1. 
My goal is to display a link in the notification bar of a page, after a page is saved.  Here are steps I've taken:

- Go to workflows
- Create new workflow definition
- Give it a name
- Drag "Content Updated" to the canvas
- Edit it's content types to select Page
- Drag a "Notify" to the canvas and connect it to "Content Updated"
- Go into Notify's setting to create a notification link with the following message: 
`<a href="{Content.DisplayUrl}">Preview</a>`
- Make sure my "Content Updated" box is turned on.
- Save my workflow,

With these steps taken, the CMS does not display my notification message when I save pages.

**Comment by blachawk** [comment]
Still stuck on this.  What am I missing from my steps to meet my notification goal?

**Comment by sebastienros** [comment]
Have you selected the Content Updated an marked it as Start activity?
Have you "Enabled" the workflow?

**Comment by blachawk** [comment]
Yes.  The "Content Created" and "Content Versioned" options under the workflow options work perfectly.  But "Content Updated" does not fire when I change the content on a page and click save.

**Comment by sebastienros** [comment]
I just looked at the code and it seems correct, I will try to repro

**Comment by blachawk** [comment]
I believe you are correct. it does work, No need to further check.  I think its a matter of selecting the "correct" content types...

Thanks!

**Comment by sebastienros** [comment]
I tried to repro before reading your comment and was about to suggest that, as I did the same mistake during the repro.
