### ISSUE TITLE
Pages load very slow 

### ISSUE THREAD

**Issue by justgfather** [OrchardCMS/Orchard#7661]
Our website runs very slowly ... we have over 450 content pages ... is this the reason why? or something else ? HELP ZOLTAN !!!!!!!!!!

**Comment by sebastienros** [comment]
Do you have the cache enabled?
Are you releasing a Precompiled build?
Where are you hosting your site?

Please use the forum for help, not the issue tracker.

**Comment by Piedone** [comment]
Well, I guess I'm late to this party :).
