### ISSUE TITLE
Visual Studio 2017 - Unit tests are not showing in Test Explorer

### ISSUE THREAD

**Issue by andrewliang** [OrchardCMS/Orchard#7664]
In Visual Studio 2017, unit tests are not showing in test explorer. Rebuilding the project and clicking on "Run All" as no effect.

This isn't an issue in Visual Studio 2015.

Thanks

![image](https://cloud.githubusercontent.com/assets/1163664/25046921/074915a2-2102-11e7-997a-9080caf43d86.png)

**Comment by sebastienros** [comment]
We probably need to update some tooling nuget package version. Can somebody check the ones used on ASP.NET Core MVC on the master branch?

**Comment by carlwoodhouse** [comment]
they dont seem to work in 2015 for me anymore either :|

**Comment by MatteoPiovanelli** [comment]
I stumbled upon this issue. I think it's been fixed, because I can see the tests in the Test Explorer in VS 2015.

**Comment by jayharris** [comment]
I also think this has been fixed. The tests appear in VS2017 (15.7.4) as well.

![screen shot 2018-07-28 at 11 28 06 am](https://user-images.githubusercontent.com/220808/43359594-702790de-9259-11e8-95f9-dbefafae4f72.png)

**Comment by sebastienros** [comment]
Please reopen if you can still repro
