### ISSUE TITLE
Resources failing to load after deployment

### ISSUE THREAD

**Issue by sdimech** [OrchardCMS/Orchard#7666]
I'm quite new to Orchard and could not find an issue similar to mine. Basically, I downloaded Orchard and developed a custom module. After deploying I noticed that css and js files in modules are not being loaded both in the front end and dashboard. This is resulting in badly rendered pages and unusable functionality. Please refer to screenshots below.

![image](https://cloud.githubusercontent.com/assets/27689881/25092225/fe78de16-238c-11e7-9fde-ba4d9474e083.png)

![image](https://cloud.githubusercontent.com/assets/27689881/25092293/5ac394b8-238d-11e7-80ab-dfec8482551d.png)

Any help would be greatly appreciated, I spent a lot of hours trying to fix this.

**Comment by sebastienros** [comment]
It's usually because the folder is missing a proper web.config that enables static file to be served. Look at the /Media folder and copy paste the web.config to your folder containing the files.

**Comment by sdimech** [comment]
I have already ready checked, and the web.config is present in the Styles and Scripts folder of every module. Any idea what may be causing this?

**Comment by sebastienros** [comment]
Sorry, I had not seen it's also for the files in existing modules.

Are you sure the files are actually deployed? Have you checked the server?

**Comment by sdimech** [comment]
I setup IIS  on my local PC and tested the website using the same files I deployed on the server and it is working fine. I granted full control to IIS_IUSRS on all folders on server and it's still the same. I cannot understand what's happening.

**Comment by sdimech** [comment]
I managed to fix the issue. After checking the IIS log files I noticed that the Urls where being rejected by UrlScan ISAPI filter. I removed the filter from IIS Manager and now it works perfectly!
