### ISSUE TITLE
changing placement issues

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/Orchard#7678]
I have tested this in a few version, and maybe my expectation are off. Here is what I am experiencing. Using 1.10.1 I added a text field to the blog post called excerpt. I only want to show this field on the summary, so I decided I can just do a placement to hide this field in the blog post detail view. When I start to play around with placements I find that I cannot make very many changes before it doesn't have any effect anymore. Sometimes I am unable to make any at all even if I close everything down and restart. For example, while trying to hide my excerpt field, I decide to change a known field like metadata on a blog post.
`<Match ContentType="BlogPost">
       <Match DisplayType="Detail">
      <Place Parts_Common_Metadata="-"/>
      <place Fields_Common_Text="-"/>
    </Match>
  </Match>`
I was successful one time but turning off the metadata but quickly any changes to the placement file had no effect on the site. My expected behavior is that I can make as many changes as needed to the placement file and it will reliably be reflected on the site. I chatted with @sebastienros about this on gitter and thought it was just an old version of orchard but I am having trouble on 1.10.1 and 1.10.2

**Comment by sebastienros** [comment]
Do you have custom settings for the FileSystemWatcher in the web.config ? I know some settings can be set to optimize the perf. But if you did nothing then it should just work.

**Comment by roballred** [comment]
@sebastienros no custom settings at all.

**Comment by roballred** [comment]
@sebastienros I would love to demo this issue to you so we can decide if it is a bug or my just doing dumb things. It would be really great to use placement.info as advertised.

**Comment by sebastienros** [comment]
Is this sufficient to repro the bug? 

```
<Match ContentType="BlogPost"> <Match DisplayType="Detail"> <Place Parts_Common_Metadata="-"/> <place Fields_Common_Text="-"/> </Match> </Match>
```

**Comment by roballred** [comment]
I have been trying to get this to work as a simple test, but it seems to fail to hide the content for the page.
```
<Match ContentType="Page">
    <place Parts_Common_Body="-"/>
</Match>
```
I am testing on 1.10.2

**Comment by sebastienros** [comment]
Pretty bad indeed.

**Comment by thekaveman** [comment]
Could it be that `PlacementFileParser` expects the element to be named `<Place>` (capitalized)?

```c#
private IEnumerable<PlacementNode> Accept(XElement element) {
    switch (element.Name.LocalName) {
        case "Placement":
            return AcceptMatch(element);
        case "Match":
            return AcceptMatch(element);
        case "Place":
            return AcceptPlace(element);
    }
    return Enumerable.Empty<PlacementNode>();
}
```

**Comment by roballred** [comment]
@thekaveman that did it for me! At least that simple example now works.

**Comment by roballred** [comment]
Here is a screen cap of the help doc and its syntax example.
![placementscreenshot](https://user-images.githubusercontent.com/549504/29084630-7c284eb8-7c21-11e7-8235-8c92d3879ae6.png)

**Comment by sebastienros** [comment]
I saw the case issue, but thought it was just typo when you commented ... 
We should fix the documentation. Not sure I want to change the code as it could activate some issues on existing sites.

**Comment by roballred** [comment]
@sebastienros I made the changes to the documentation, So if you think we shouldn't change the code to be case insensitive then we can close this issue.
