### ISSUE TITLE
Fix typo: `MediaLibrayServiceExtensions`

### ISSUE THREAD

**Issue by jean** [OrchardCMS/Orchard#7679]
https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.MediaLibrary/Services/IMediaLibraryService.cs#L146

**Comment by jean** [comment]
Suggested by @Xceno : 

> [R]ename it, leave the old one intact and call the new code from there, but mark it with an `ObsoleteAttribute`
So if someone uses it they have the chance to adapt before updating to `VNext`

If this sounds acceptable, I'll try to make it so.

**Comment by sebastienros** [comment]
That's a safe breaking change for the dev branch, and probably nobody is calling this extension method with the class name.
