### ISSUE TITLE
Issue with theme settings form in TheBootstrapMachine not rendering in 1.10.2

### ISSUE THREAD

**Issue by petedavis** [OrchardCMS/Orchard#7683]
Theme settings page works fine in 1.9.3 with https://github.com/OrchardCMS/TheBootstrapMachine

After updating to Orchard 1.10.2 and applying the pull request https://github.com/OrchardCMS/TheBootstrapMachine/pull/2

The Theme Settings page only has a save button, the form does not render.

I have tried to identify differences between this module and say Orchard.Comments and the main difference is that Orchard.Comments uses a Driver, where TheBootstrapMachine uses a TemplateFilterForPart<BootstrapSettingsPart>

1.9.3 Theme Settings page
![1.9.3 Theme Settings](https://cloud.githubusercontent.com/assets/164331/25701344/2d486140-310b-11e7-8786-9efeb3567e77.png)

1.10.2 Theme Settings page
![1.10.2 Theme Settings](https://cloud.githubusercontent.com/assets/164331/25702312/8dca21c6-310f-11e7-92b7-b64ef9fc5a77.png)

I have yet to test on 1.10 and 1.10.1

**Comment by petedavis** [comment]
Another observation is that the URL is different
1.10.2: http://localhost:30321/OrchardLocal/Admin/Settings/ThemeOptions
1.9.3:   http://localhost:30321/OrchardLocal/Admin/Settings/Theme%20Options

**Comment by sebastienros** [comment]
Looks like a fix we applied to group urls for settings, specifically for the audit trail. 
Hope we haven't broken anything.

6df57dd098c5f5813fc865f3e057cd359037d666

**Comment by MarcoViglione-Laser** [comment]
The fix was related to the issue #7371 I found.

**Comment by petedavis** [comment]
From the Theme perspective, removing the space from the GroupId fixes the issue

From:
`Filters.Add(new TemplateFilterForPart<BootstrapSettingsPart>("BootstrapSettings", "Parts/BootstrapSettings", "Theme Options"));`
To:
`Filters.Add(new TemplateFilterForPart<BootstrapSettingsPart>("BootstrapSettings", "Parts/BootstrapSettings", "ThemeOptions"));`

Is there an issue matching the route back to the groupId and the part to be rendered?

Given that the route in 1.10.2 is `/Admin/Settings/ThemeOptions` (Space removed) and the group id is set to `"Theme Options"`

**Comment by sebastienros** [comment]
The group is normalized so I assume we need to do it too in the Template Filter.

NB:
Uou mention 1.10.2 but this theme is not shipped with Orchard

**Comment by petedavis** [comment]
Sorry @sebastienros, I am just using that theme as a repeatable reference implementation to an issue upgrading from 1.9.3 to 1.10.2. 

The 1.10.2 reference to "ThemeOptions" is only reference to the generated URL from Orchard 1.10.2, and not the theme code itself.

**Comment by BenedekFarkas** [comment]
Fixed in 55485cb465203c7d440ac600169ede918efc8ad1, verified with TheBootstrapMachine.
