### ISSUE TITLE
Doublequote characters in extension manifest files

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#7684]
This just came up while updating the translation files on Crowdin to 1.10.2 (not sure why it happened just now): The feature description of the `DatabaseUpdate` feature in the `Orchard.Migrations` module is the following:
```
Commands for updating the database schema according to the definition of the "Record" classes in code.
```
The unescaped doublequote characters cause Crowdin to fail to parse the PO file. It's an easy fix of course, but it has some further implications as this string is displayed as is, so it would look like this on the Features page: `... \"Record\" ...`.
So the question is whether the convention should be to escape doublequotes in manifests, or don't use them at all?

**Comment by sebastienros** [comment]
I don't understand the issue. The .PO file should have escape sequences like this:

```
#: kstars_i18n.cpp:3591
msgid "The \"face\" on Mars"
msgstr "\"Lice\" na Marsu"
```

**Comment by BenedekFarkas** [comment]
Yes, but you wouldn't usually do that in a Module.txt or a Theme.txt, unless you know that it can cause problems, whereas in a C# code file not escaping a double quote gives you a build error.

**Comment by sebastienros** [comment]
I am not saying to encode it in the manifest, it should be encoded. Just in the .po file.

**Comment by BenedekFarkas** [comment]
Ah, I see. You're right - since we're using @bleroy's module (the `Translation Manager` feature in [Vandelay Industries](https://github.com/bleroy/vandelay)) to generate `PO` files, I'll raise an issue there and send a PR.
