### ISSUE TITLE
What Kind of Applications Can Be Written with OrchardCMS?

### ISSUE THREAD

**Issue by meatballcoder** [OrchardCMS/Orchard#7689]
Hi, I want to use Orchard CMS to create a specialized application for a school.  It would be like Moodle, so very specialized, no Internet website, all internal.  It would have a gradebook, student information system, etc.  I do not need a blog or a forum.  Is Orchard CMS a suitable choice for this?  Is that beyond what OrchardCMS is supposed to be used for?  Thanks.

**Comment by sebastienros** [comment]
Totally adapted. Even more if you want to create workspaces dynamically by creating new tenants on the fly. One thing you will want to look at is to use a single sign on solution if you want the same credentials to be used across site.

**Comment by meatballcoder** [comment]
Can you please tell me what "Totally adapted" means?  I'm sorry.

Edit:  Do you mean that my project is a good thing or bad thing for OrchardCMS?

**Comment by sebastienros** [comment]
Yes, that's good.
