### ISSUE TITLE
Publish button should be renamed to OK button on layout element editor

### ISSUE THREAD

**Issue by DaRosenberg** [OrchardCMS/Orchard#7697]
When I made "publish" the default label for non-versioned content items I also applied this change to the layout element editor dialog. However, in that context the button should be neither "publish" nor "save" since nothing is actually persisted until you also save the containing content item. A much better label for this button would be "OK" which would close the editor keeping the changes, while the existing "Cancel" button closes the editor and discards the changes.

**Comment by sebastienros** [comment]
Please update the specflow test accordingly if there is one.

**Comment by DaRosenberg** [comment]
Couldn't find any related/affected specflow test to update.
