### ISSUE TITLE
There‘s a problem with command codegen working in VS2015

### ISSUE THREAD

**Issue by F-gulugulu** [OrchardCMS/Orchard#7699]
the Orchard version is 1.10.2, while using command to create a module ,the console always return a OutOfRange Exception,but it does create everything for me except adding this project to orchard solution.

**Comment by lucyh-t** [comment]
I have the same issue when using codegen to create a theme in version 1.10.2 with Visual Studio 2017. The Theme folder structure is created and recognised in the Themes admin area, but the project is not added to the solution
Command:
codegen theme Gecko.TestTheme /CreateProject:true /IncludeInSolution:true /BasedOn:Lombiq.PrettyGoodBootstrapBaseTheme
Error:
Creating Theme Gecko.TestTheme

Error executing command "codegen theme Gecko.TestTheme"
--------------------------------------------------------------------------------

Specified argument was out of the range of valid values.
Parameter name: startIndex

Exception Details: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: startIndex

Stack Trace:

[ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: startIndex]
   at System.String.Insert(Int32 startIndex, String value)
   at Orchard.CodeGeneration.Commands.CodeGenerationCommands.AddToSolution(TextWriter output, String projectName, String projectGuid, String containingFolder, String solutionFolderGuid)
   at Orchard.CodeGeneration.Commands.CodeGenerationCommands.CreateThemeFromTemplates(TextWriter output, String themeName, String baseTheme, String projectGuid, Boolean includeInSolution)
   at Orchard.CodeGeneration.Commands.CodeGenerationCommands.IntegrateTheme(String themeName, String baseTheme)
   at Orchard.CodeGeneration.Commands.CodeGenerationCommands.CreateTheme(String themeName)

**Comment by RHowland** [comment]
This StackOverflow article has a work around to this problem which also occurred for me when trying to generate scaffolding for a new theme (I have not tested it yet for generating a new module): 
https://stackoverflow.com/questions/39804581/creating-new-theme-in-orchard-with-codegeneration-module
The workaround is to remove "\r" from line 434 in the CodeGenerationCommand.cs file: 
solutionText = solutionText.Insert(solutionText.LastIndexOf("EndProject\r\n"), projectReference);

**Comment by sebastienros** [comment]
In theory the EOL chars should be replaced by `\r\n` automatically when you clone the repository. Can you check if the template you have locally for the solution contains `\n` or `\r\n` ?

**Comment by sebastienros** [comment]
Actually it's in the Orchard.sln file.

**Comment by RHowland** [comment]
Hi Sebastion;

Thank you for the email about this problem. 

In Orchard versions 1.9.2, 1.10.1, and 1.10.2 I get the same error.  

I found a workaround at:
https://stackoverflow.com/questions/39804581/creating-new-theme-in-orchard-with-codegeneration-module

The 
Change line # 434 in the CodeGenerationCommands.cs file:
- remove "\r" this one line.

**Comment by RHowland** [comment]
Hi Sebastien;

(Sorry for mis-spelling your name in my last email message.)

You mentioned that there is an error in the .sln file.  

Is there a work-around or a fix for that error?

Thanks.  

Best Regards;
Rich Howland

**Comment by sebastienros** [comment]
I was asking you if you could ensure that your sln file contains `\r\n` and not just `\n`.

**Comment by RHowland** [comment]
In the Orchard.sln file for v1.10.1 and v1.10.2, (both of which were downloaded from Github as .zip files) there was no occurrence of either “\r\n” or “\n”.  

I hope that answers your question.

Thanks for your help.

**Comment by sebastienros** [comment]
"Downloaded from zip file", now that makes sense. We should change the codegen to also replace `\n` then.
