### ISSUE TITLE
How add Indexs in Migration.cs

### ISSUE THREAD

**Issue by KANekT** [OrchardCMS/Orchard#7703]
How add Index's (SiteIndex, SiteNoAutorizedIndex, etc.) in Migration.cs?

[link to image](https://cloud.mail.ru/public/4iyk/6KQnKc8oE)

**Comment by KANekT** [comment]
in Migration.cs
                       `             ContentDefinitionManager.AlterPartDefinition(_creatimeGymCase, cfg => cfg
                .WithField("ShortDescription",
                    f => f.OfType("TextField"
                        .WithSetting("TextFieldSettingsEventsViewModel.Settings.Flavor", "Textarea")
                        .WithSetting("FieldIndexing.Included", "true")
                )
            );
`

is set Default Flavor - where my error ?

**Comment by sebastienros** [comment]
Please ask question on the forums (gitter, stackoverflow).

I think `TextFieldSettingsEventsViewModel` shouldn't be there.
