### ISSUE TITLE
Orchard.OutputCache vital error

### ISSUE THREAD

**Issue by ziic** [OrchardCMS/Orchard#7704]
Hello.
I have enabled feature Orchard.OutputCache. I've upgraded site to Orchard 1.10.2 and now have trouble with it.
When I try to open any page without cache (CTRL + F5), I get the NullReference Exception.
Call stack:
[NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.]
   Orchard.OutputCache.Services.DefaultTagCache.Tag(String tag, String[] keys) +235
   Orchard.OutputCache.Filters.<>c__DisplayClass29_0.<OnResultExecuted>b__1(Byte[] output) +1437
   Orchard.OutputCache.Filters.CaptureStream.OnCaptured() +71
   Orchard.OutputCache.Filters.CaptureStream.Flush() +115
   System.Web.HttpWriter.FilterIntegrated(Boolean finalFiltering, IIS7WorkerRequest wr) +9762749
   System.Web.HttpResponse.FilterOutput() +104
   System.Web.CallFilterExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +58
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

I've done some research and found out that  when the site starts DefaultTagCache gets null when requests workContext and thus doesn't create _dictionary that later is used (in Tag method in my case). 
```C#
public DefaultTagCache(IWorkContextAccessor workContextAccessor, ShellSettings shellSettings) {
            var key = shellSettings.Name + ":TagCache";
            var workContext = workContextAccessor.GetContext();

            if ( workContext != null ) {
                _dictionary = workContext.HttpContext.Cache.Get(key) as ConcurrentDictionary<string, HashSet<string>>;

                if ( _dictionary == null ) {
                    _dictionary = new ConcurrentDictionary<string, HashSet<string>>(StringComparer.OrdinalIgnoreCase);
                    workContext.HttpContext.Cache.Add(key, _dictionary, null, Cache.NoAbsoluteExpiration, Cache.NoSlidingExpiration, CacheItemPriority.Normal, null);
                }
            }
        }
```
![orcharderroroutputcache](https://cloud.githubusercontent.com/assets/14326251/26279212/2ecc6d4c-3db6-11e7-9075-a1de75177c84.png)

**Update:**
Also I found out that GetRoutes method in my module uses _taxonomyService.GetTerms to construct some routes and this triggers initialization of DefaultTagCache (and get null on this stage).
If I do not touch _taxonomyService then all wokrs correctly: creation of DefaultTagCache is not triggered on this step (constucted later, after routes are created).

**Comment by sebastienros** [comment]
Could someone create simple repro steps?

**Comment by sebastienros** [comment]
If we just need a null check, let's add it.

**Comment by BenedekFarkas** [comment]
@I3undy's observation is that the internal dictionary is only conditionally initialized, so it's possible that when trying to access it later it's still null. My suggestion would be to add a method that can be called later to make sure that it's set up correctly (similar to the `EnsureInitialized` method in `Orchard.Azure.Services.FileSystems.AzureFileSystem`):

- Initializing the dictionary itself should happen in the ctor with or without WorkContext being available. ITagCache is an ISingletonDependency, so putting it later in the cache is not a problem.
- Add a private method (e.g. `EnsureCached`) that checks if WorkContext is available and then puts the dictionary in the cache.
- `EnsureCached` is called in the beginning of the public methods (Tag, GetTaggedItems, RemoveTag).

@sebastienros what do you think?

**Comment by sebastienros** [comment]
I agree, the initialization of the dictionary needs to be triggered outside of the ctor, using an `EnsureInitialized` method.
