### ISSUE TITLE
Why Custom Forms have been marked as obsolete?

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#7714]
We are trying to find a way to insert a form in the front-end, capable to create a new content or edit an existing one (for example a Content Type "Help Desk ticket", TitlePart, TaxonomyField, our Custom "MapPart," MediaLibraryPickerField and so on); we don't want to grant access to admin panel for this type of thing. 
This issue is similar to this one #6163 and it can extend what described there.

By now we tried two different approaches:
1.  Using **Custom forms** seems to be a nice solution for us, because in a while we are capable to achieve the result; _BUT_ this module is marked as Deprecated: Why? Any security reason?
2. Using **Dynamic Forms**, is _NOT_ yet a way  because we have to build all the form from zero, AND not all parts/fields are bindable (my custom part for example is not as per MediaLibraryPickerField). 

By the way It could be interesting for us to have, in the "forms" group of dynamic forms, the ability to drag and drop a new element Content"; when the element Content is dropped into the layout, all the content will be editable in the front-end, using editors of all parts and fields.

The form element settings of the layout could be modified like this
![dyamicform - form settings](https://cloud.githubusercontent.com/assets/13333709/26453955/da26c3f6-4165-11e7-919c-67c6a4d69b58.png)

So when an ID is resolved by the token, the form will be filled with data of the content and the content will be updated on submission; otherwise the form will be blank and a new content will be created during form submission.

It could be an idea? Someone has already something implemented?
Thank you for answers

**Comment by sebastienros** [comment]
We deprecated it because Dyanmic forms is more suitable. It's fields editors are target the front end, whereas the Custom Form ones are targeting the admin. In the end it's easier to create your own forms than having something configurable that doesn't render correct inputs.
