### ISSUE TITLE
LocalizationPart is in Page even when Localization Module is not enabled

### ISSUE THREAD

**Issue by MatteoPiovanelli** [OrchardCMS/Orchard#7721]
THis should be easy to fix.

The Default recipe adds LocalizationPart to Page, even though it does not enable the Localization Module.
Might be worth spending a little bit double-checking the recipes, and deciding whther it makes sene to change the migration in the localization module to add a LocalizationPart to Page when the feature is enabled (I think that would not be correct).

**Comment by sebastienros** [comment]
Ok

**Comment by sebastienros** [comment]
Reading this issue again. What exactly is the problem with it?

**Comment by MatteoPiovanelli** [comment]
In the Default recipe we are adding the LocalizationPart to Page. However:
 - The Localization feature is not enabled, so that part does nothing
 - There is no definition for the part. It's just there if you go in the ContentDefinition for Page, but the part does not really exist and cannot even be removed.
