### ISSUE TITLE
: sharing violation: System.Data.SqlServerCe.SqlCeException

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#7722]
environment: 1.10.2, using ONLY SQLce: Orchard.sdf

Thanks for your time ...
when logging in I get out of 5 trials 2 times subject error.
on the (user) screen I get a 404 /application error. However the Log always says (see also attached file 'orchard-error-2017.05.31.txt'):

NHibernate.TransactionException: Begin failed with SQL exception ---> System.Data.SqlServerCe.SqlCeException: There is a file sharing violation. A different process might be using the file. 
[ \\WAGNER\wwwrootamenfr$\cdbdcbee4.hostnd\htdocs\www\App_Data\Sites\Default\Orchard.sdf ]

- where can I find out who is violating!?
- Is this something I can influence by setting certain parameters in Orchard ?
- my Cache settings: Output Cache, SysCache, Database Output Cache, File Sytem Output Cache

I'm out of ideas
any help is appreciated, ed

**Comment by sebastienros** [comment]
How/Where do you host this site? How many instances?

**Comment by ghost** [comment]
the site is hosted on AMEN (france www.meounes.com). It is only one site i.e. no sub domains if that's what you mean with 'instances'! 
Only one Editor, one Admin is defined.
I'm happy to provide addl info ...
thanks for your prompt reply, ed

PS: forgot to attach the log ; did it now!
[orchard-error-2017.05.31.txt](https://github.com/OrchardCMS/Orchard/files/1045960/orchard-error-2017.05.31.txt)

**Comment by sebastienros** [comment]
Maybe two different servers handled the database before and after the site restarted, and the previous was not really stopped before the second one started. Just an hypothesis.

**Comment by ghost** [comment]
thanks, will contact AMEN again. 
Will also confront AMEN re FTP (FileZilla): when I try to download the DB 'Orchard.sdf' -  sometimes it works; mostly it fails also with FileZilla error:
"550 The process cannot access the file because it is being used by another process. "

 OTHER files are handled correctly!
Merci, ed

**Comment by ghost** [comment]
FYI; so far I do not have secured test results with below suggestion.
However, AMEN suggested to ad in the Web.config the <security policy .. as follows:

 <securityPolicy>
           <trustLevel name="Full" policyFile="internal"/>
</securityPolicy>

! the <trust level ... below was and is still included:
        <trust level="Full" originUrl="" />
PS: I do not yet know what this means ... need to make myself smart first.
In case you have some hints  ... I appreciate it
thanks for your time, ed

**Comment by ghost** [comment]
further investigations show that the newest Orchard 1.10.2 has an issue with the old AMEN platform!
AMEN suggested to migrate to their newer platform.
Therefore I'm closing this ticket for now.
Thank you again for your time and help, ed

**Comment by ghost** [comment]
in the meantime the site runs on the new platform, BUT, unfortunately I have the very same issue. I even transferred
the site onto another ISP (Winhost): same issue.

I start to think of going back to 1.10.1

Attached again the error log
 
any help is appreciated, ed
[SQLceLog.txt](https://github.com/OrchardCMS/Orchard/files/1093741/SQLceLog.txt)

**Comment by ghost** [comment]
with some further testing I found:
when closing access to the Site by just closing the Browser (cross) and try immediately to login again I mostly get the 404 error (log NHibernate... issue).
After some time OR after a new Windows login it works again.

Questions
- could it be that just killing the Browser does NOT clean up ALL!?
- also I de-activated all cache modules
? are in this context any modules/parameters which could help ?

thanks for your guys time, ed

**Comment by sebastienros** [comment]
I would suggest to use Sql Server, you definitely have different processes accessing the same file, and SqlCe doesn't support that.

**Comment by ghost** [comment]
thank you again. Didn't know that SQLce is not supporting that. And, It is probably about time anyway to do that step.
Is there a documented procedure on how to convert a 'orchard.sdf' DB onto a SQL server!? I guess I'm not the first one to do this?
Perhaps you have some hints re such a documentation (afterwards I close this issue).
thanks for your time, eda

**Comment by sebastienros** [comment]
I know there is a tool in webmatrix to convert.
Then you just need to change the settings.txt file to point to the new database
and you hoster should already support Sql for free I assume

**Comment by carlwoodhouse** [comment]
http://erikej.blogspot.co.uk/2012/02/migrating-databases-between-sql-server.html

**Comment by ghost** [comment]
Merci beaucoup !

**Comment by agriffard** [comment]
Can we add some display templates or settings to the media Field to render them easily as img instead of having to create an alternate in the theme?

Will we be able to replace the 'header image url' TextField in the blog recipe by a MediaField?

**Comment by ghost** [comment]
firstly, thanks to all for their advice! Finally, after changing from SQLce to SQL Server .... so far all seems to work!
As a conclusion: I will NOT anymore use SQLce; isn't there perhaps a documentation change needed? Because it is a very annoying error - because it is not 'stable'!?
thanks again and close it after your(s) conclusion, ed

**Comment by carlwoodhouse** [comment]
Perhaps; sqlce is really meant for development/really low traffic stuff -
perhaps the documentation could highlight that
