### ISSUE TITLE
Headless CMS

### ISSUE THREAD

**Issue by tomakali** [OrchardCMS/Orchard#7735]
Orchard should go "headless" "decoupled"

https://hackernoon.com/headless-vs-decoupled-cms-architecture-e240838fbc99
https://pantheon.io/decoupled-cms

**Comment by sebastienros** [comment]
It's doable as a module. I have done that a few years ago. The module would disable the UI unless you try to go in the admin. And it would also expose some apis to query the content.

Note that the decoupled approach is used in Orchard Core.

**Comment by carlwoodhouse** [comment]
Thats pretty cool :)

**Comment by sebastienros** [comment]
Done in Orchard Core

**Comment by deltoss** [comment]
So if this is done, how do we achieve it with Orchard Core?

**Comment by tomakali** [comment]
can orchard run on AWS lambda?
