### ISSUE TITLE
Date/Time Format Translation BUG ", " ","

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/Orchard#7738]
“/”应用程序中的服务器错误。

索引超出了数组界限。

说明: 执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。 

异常详细信息: System.IndexOutOfRangeException: 索引超出了数组界限。

源错误: 

行 1:  <div class="published">@Display.PublishedState(createdDateTimeUtc: Model.ContentPart.CreatedUtc, publisheddateTimeUtc: Model.ContentPart.PublishedUtc)</div>

源文件: f:\WEB\Orchard.dev\Core\Common\Views\Parts.Common.Metadata.cshtml    行: 1 

堆栈跟踪: 

[IndexOutOfRangeException: 索引超出了数组界限。]
   Orchard.Localization.Services.DefaultDateFormatter.GetDateFormatValues(DateParts parts, Calendar calendar, Int32& twoDigitYear, String& monthName, String& monthNameShort, String& monthNameGenitive, String& monthNameShortGenitive, String& dayName, String& dayNameShort, String& eraName, String& eraNameShort) +764
   Orchard.Localization.Services.DefaultDateFormatter.FormatDateTime(DateTimeParts parts, String format) +573
   Orchard.Localization.Services.DefaultDateLocalizationServices.ConvertToLocalizedString(Nullable`1 date, String format, DateLocalizationOptions options) +387
   Orchard.Localization.Services.DefaultDateLocalizationServices.ConvertToLocalizedString(DateTime date, String format, DateLocalizationOptions options) +68
   Orchard.Core.Shapes.DateTimeShapes.DateTime(DateTime DateTimeUtc, LocalizedString CustomFormat) +110

[Exception: TargetInvocationException DateTime]
   Orchard.DisplayManagement.Descriptors.ShapeAttributeStrategy.ShapeAttributeBindingStrategy.PerformInvoke(DisplayContext displayContext, MethodInfo methodInfo, Object serviceInstance) +475
   Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context) +108
   Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context) +1123
   Orchard.DisplayManagement.Implementation.DisplayHelper.Invoke(String name, INamedEnumerable`1 parameters) +65
   Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result) +79
   CallSite.Target(Closure , CallSite , Object , DateTime ) +237
   Orchard.Core.Common.Shapes.PublishedState(Object Display, DateTime createdDateTimeUtc, Nullable`1 publisheddateTimeUtc) +496

[Exception: TargetInvocationException PublishedState]
   Orchard.DisplayManagement.Descriptors.ShapeAttributeStrategy.ShapeAttributeBindingStrategy.PerformInvoke(DisplayContext displayContext, MethodInfo methodInfo, Object serviceInstance) +475
   Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context) +108
   Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context) +1123
   Orchard.DisplayManagement.Implementation.DisplayHelper.Invoke(String name, INamedEnumerable`1 parameters) +65
   Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result) +79
   CallSite.Target(Closure , CallSite , Object , Object , Object ) +346
   ASP._Page_Core_Common_Views_Parts_Common_Metadata_cshtml.Execute() in f:\WEB\Orchard.dev\Core\Common\Views\Parts.Common.Metadata.cshtml:1
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +252
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +148
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +122
   System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData) +136
   Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.Render(ShapeDescriptor shapeDescriptor, DisplayContext displayContext, HarvestShapeInfo harvestShapeInfo, HarvestShapeHit harvestShapeHit) +244
   Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.<>c__DisplayClass20_7.<Discover>b__14(DisplayContext displayContext) +61
   Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context) +108
   Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context) +1123
   Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvoke(InvokeBinder binder, Object[] args, Object& result) +72
   CallSite.Target(Closure , CallSite , Object , Object ) +268
   Orchard.Core.Shapes.CoreShapes.ContentZone(Object Display, Object Shape, TextWriter Output) +1979

[Exception: TargetInvocationException ContentZone]
   Orchard.DisplayManagement.Descriptors.ShapeAttributeStrategy.ShapeAttributeBindingStrategy.PerformInvoke(DisplayContext displayContext, MethodInfo methodInfo, Object serviceInstance) +475
   Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context) +108
   Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context) +1123
   Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvoke(InvokeBinder binder, Object[] args, Object& result) +72
   CallSite.Target(Closure , CallSite , Object , Object ) +268
   ASP._Page_Core_Contents_Views_Content_cshtml.Execute() in f:\WEB\Orchard.dev\Core\Contents\Views\Content.cshtml:19
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +252
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +148
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +122
   System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData) +136
   Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy.Render(ShapeDescriptor shapeDescriptor, DisplayContext displayContext, HarvestShapeInfo harvestShapeInfo, HarvestShapeHit harvestShapeHit) +244
   Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.<>c__DisplayClass20_7.<Discover>b__14(DisplayContext displayContext) +61
   Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Process(ShapeBinding shapeBinding, IShape shape, DisplayContext context) +108
   Orchard.DisplayManagement.Implementation.DefaultDisplayManager.Execute(DisplayContext context) +1123
   Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvoke(InvokeBinder binder, Object[] args, Object& result) +72
   CallSite.Target(Closure , CallSite , Object , Object ) +268
   ASP._Page_Core_Shapes_Views_ShapeResult_Display_cshtml.Execute() in f:\WEB\Orchard.dev\Core\Shapes\Views\ShapeResult\Display.cshtml:1
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +252
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +148
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +122
   Orchard.Mvc.ViewEngines.ThemeAwareness.<>c__DisplayClass9_0.<FindView>b__0(ViewContext viewContext, TextWriter writer, IViewDataContainer viewDataContainer) +255
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +375
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +88
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +831
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +81
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +185
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +52
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +43
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) +77
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Orchard.Mvc.Routes.<<ProcessRequestAsync>b__0>d.MoveNext() +429
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Orchard.Owin.<<UseOrchard>b__0_0>d.MoveNext() +322
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Orchard.SecureSocketsLayer.Services.<<GetOwinMiddlewares>b__6_1>d.MoveNext() +470
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Orchard.Mvc.Routes.<ProcessRequestAsync>d__5.MoveNext() +576
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +64
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +607
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +134

版本信息: Microsoft .NET Framework 版本:4.0.30319; ASP.NET 版本:4.7.2046.0

**Comment by pgy866** [comment]
https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Localization/Providers/LocalizationDateTimeFormatProvider.cs#L56


 trim
![image](https://user-images.githubusercontent.com/28694676/27415958-eef0c498-573c-11e7-8b98-00851abdae71.png)


![image](https://user-images.githubusercontent.com/28694676/27415941-beb2bb88-573c-11e7-9e85-e2a468bb0a30.png)

**Comment by ViRuSTriNiTy** [comment]
...so you think in an english issue tracker someone can read chinese?

**Comment by pgy866** [comment]
https://crowdin.net/translate/orchard-cms/325/enus-zhcn


。。 All right! I'll revise the translation document.

**Comment by sebastienros** [comment]
Are you pointing a translation issue or a bug?

**Comment by ViRuSTriNiTy** [comment]
I think the issue here is that the english version of the text is seperated with " ," whereas in chinese "," is needed. Therefore the split by " ," won't work.

**Comment by pgy866** [comment]
![4](https://user-images.githubusercontent.com/28694676/27479794-eda20514-5847-11e7-9d44-594c054a795f.gif)

**Comment by sebastienros** [comment]
Maybe we should escape double commas first, then split by commas.

**Comment by sebastienros** [comment]
The split is done on `", "` which is fucking stupid (I have to replace Linus here) from moronic devs!!!
It should be on both `','` and `' '` with a RemoveEmptyEntries. Or maybe split by comma then trim the result in case a month has a space in it.
Do not change the string itself or it would break the existing translations.

**Comment by sebastienros** [comment]
c.f. https://www.newyorker.com/science/elements/after-years-of-abusive-e-mails-the-creator-of-linux-steps-aside

**Comment by BenedekFarkas** [comment]
Fixed in 3644d868ec72643030ea16cc99c2ddb89c0b3bdf according to ~~Linus~~Sébastien's suggestion. ;)
