### ISSUE TITLE
YesSQL and Orchard 1

### ISSUE THREAD

**Issue by ActivePHOENiX** [OrchardCMS/Orchard#7745]
I would like to know , Is there any chance of future releases of O1 using this database or , it is going to be only Orchard Core that is benefiting from it?
Is there any future plan for YesSql to be use in core modules of Orchard1? any official provider is going to be released?

Thanks in advance

**Comment by pszmyd** [comment]
Chance is close to zero imho - there is so much code that relies on NH making it extremely hard to switch without introducing **major** breaking changes. To answer the second part - official most likely not but I'll be releasing a module that brings YesSql to O1 in the upcoming weeks.
