### ISSUE TITLE
Conflict with Layout part and Content picker field on same content type

### ISSUE THREAD

**Issue by risiepit** [OrchardCMS/Orchard#7750]
I created a new content type, with a content picker field and a layout part. 

When trying to create a new content item in this new content type, The content picker field is visible however the first thing I noticed is that the Layout part is not visible in the create view and the following error is logged. 

**See pdf of error log:**
[orchard-error-2017.06.29.pdf](https://github.com/OrchardCMS/Orchard/files/1111641/orchard-error-2017.06.29.pdf)

When I proceed with saving this new content item, the Layout part seems to load in the edit view and no error is logged at this point. However when I select an existing layout and save the content item an error is logged, see below

[orchard-error-2017.06.29-after-save.pdf](https://github.com/OrchardCMS/Orchard/files/1111657/orchard-error-2017.06.29-after-save.pdf)

A quick fix will be appreciated.

_NOTE: This was tested with version 1.9, with a clean installation._

**Comment by sfmskywalker** [comment]
Can you try on a clean 1.10 installation, just to see if it's been fixed there since?

**Comment by risiepit** [comment]
I have just tested it in 1.10.2, the problem does not seem to exist in the new version. I guess I will have to upgrade. Thanks
