### ISSUE TITLE
Admin Menu css files are broken with 404 error

### ISSUE THREAD

**Issue by ActivePHOENiX** [OrchardCMS/Orchard#7754]
From commit #6e05649c51bd066a45fba04c9ce356e9147386ab onwards titled "Fixing specflow tests" by Sebastien, css files for admin menu icons give 404 response code, as glimpse and openId modules are added to the code-base by this commit but the diffs from github shows only changed to Feature files of specflow.

this is what I experienced and maybe I should have done setup for gulp as I know it has been changed a bit.
anybody else have this issue?

**Comment by BenedekFarkas** [comment]
Isn't this a duplicate of #7932?

**Comment by BenedekFarkas** [comment]
Fixed with #8199.
