### ISSUE TITLE
jQuery confusion

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#7757]
I'm confused (on a low level ...)!
when trying to apply the attached 'tooltip.txt' jQuery sample in Orchard 1.10.2
the tooltip appears BUT, after 5s, it disappears automatically. I'd like to have it as long as 'mouseover'.
In a 'HTML Layout' I use (Orchard 1.10.2):
`<p><a title="Hooray!" class="test" href="#" data-placement="top" data-toggle="tooltip">Top tooltip</p>`

[ToolTip.txt](https://github.com/OrchardCMS/Orchard/files/1126787/ToolTip.txt): in this sample the 'tooltip' stays as long as the mouse is over it! 
Questions:
- I would have thought to set different parameters in the appropriate 'alternate view'!?
- where do I see which parameters/variables are used?
PS: In 'Orchard.Resources' I read "Depreciated in 1.10 for e.g. jQueryUI !?! .............

I know I probably need a crash course ...
Thanks for your time and help, ed

**Comment by sebastienros** [comment]
Maybe try to ask this on gitter, you should have some answers. It's not really a bug in Orchard.

**Comment by ghost** [comment]
thanks Sebastien,
never thought this to be an Orchard bug - its more my deficit
Thanks for the gitter advise
