### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/Orchard#7758]
I checked on Crowdin and I found Orchard CMS localized 50% fro Persian but I don't see any Persian word in orchard CMS?
if it's not important for you please say that to not try translate for our language.
when I  choose fa-IR just change to RTL and Persian calendar will be enable.

**Comment by sebastienros** [comment]
The source code only contains english. All the persian words (and other languages) are on the crowding site only. Then downloaded for each installation by the developer.
