### ISSUE TITLE
ContentType and ContentPart names should be sanitized upon creation

### ISSUE THREAD

**Issue by Xceno** [OrchardCMS/Orchard#7770]
It's currently possible to create ContentParts with trailing whitespace via the Dashboard.
Such ContentParts cannot be edited again, following the link will result in a 404 (e.g. _/Admin/ContentTypes/EditPart/PartWithTrailingSpace%20_)

The `Orchard.ContentType` AdminController already [sanitizes part-name](https://github.com/OrchardCMS/Orchard/blob/1.10.x/src/Orchard.Web/Modules/Orchard.ContentTypes/Controllers/AdminController.cs#L385) (*suggestion.ToSafeName()*). The same needs to be done in [*CreatePartPOST*](https://github.com/OrchardCMS/Orchard/blob/1.10.x/src/Orchard.Web/Modules/Orchard.ContentTypes/Controllers/AdminController.cs#L389).

**Comment by BenedekFarkas** [comment]
Fixed in c8f5fd731ea79f62d8fd32957970071013a806fc.
