### ISSUE TITLE
Import/export doesn't handle identically-named fields across parts

### ISSUE THREAD

**Issue by jean** [OrchardCMS/Orchard#7773]
For [this XML](https://github.com/OrchardCMS/Orchard/files/1138438/export.xml.txt), if I create an item with values for all fields, only the last set of values is exported. I.e. if I export both content and definition, this is what I get:

```xml
  <ContentDefinition>
    <Types>
      <DetailContact ...>
        <AdditionalApplicationsContactPart />
        <AdditionalApprenticeshipProgramContactPart />
        <AdditionalBidsContactPart />
        ...
      </DetailContact>
    </Types>
    <Parts>
      <AdditionalApplicationsContactPart ...>
        <FirstName.TextField DisplayName="First Name" TextFieldSettings.Required="False" />
        ...
      </AdditionalApplicationsContactPart>
      <AdditionalApprenticeshipProgramContactPart ...>
        <FirstName.TextField DisplayName="First Name" TextFieldSettings.Required="False" />
        ...
      </AdditionalApprenticeshipProgramContactPart>
      <AdditionalBidsContactPart ...>
        <FirstName.TextField DisplayName="First Name" TextFieldSettings.Required="False" />
        ...
      </AdditionalBidsContactPart>
      ...
    </Parts>
  </ContentDefinition>
  <Content>
    <DetailContact Id="/alias=test-detail" Status="Published">
      <TextField.FirstName Text="First 3" />
      ...
    </DetailContact>
  </Content>
```

The issue in the above is that the item has fields with three different "first name" values, and only the last is exported. As far as I can see, it works fine in Orchard (editing, viewing).

From @Xceno : 

> I think the problem is right here. `ContentFields` should probably be prefixed with the partname
>
```C#
// Orchard.ContentManagement.Handlers.ExportContentHandler.cs
public XElement Element(string elementName) {
            var element = Data.Element(elementName);
            if (element == null) {
                element = new XElement(elementName);
                Data.Add(element);
            }
            return element;
        }
```
ref: [slack](https://gitter.im/OrchardCMS/Orchard?at=5964c928bf7e6af22cc891c9)

> I've created a blank site with your exact configuration (`DetailContact` with 3 Parts, each having a `FirstName` field). I can confirm the export issue and it's indeed a problem with the fieldname. So `ExportContentHandler.Element(myFieldName)` will always return the existing field in the context and `SetAttributeValue()` overrides it.
>
> A version attribute in the XML could be used for a fallback but I'd rather not introduce a "legacy import/export api".
> I think it should be sufficient enough to check if the currently imported field has a prefix equal to a `ContentPart` name and otherwise proceed the old, "buggy" way.
> Though I haven't tried that out yet.
> The generated XML will look like this btw:
>
```xml
<DetailContact Id="/Identifier=63638ee501024f26a1d2c30da524cdac" Status="Published">
      <AdditionalApplicationsContactPart.TextField.FirstName Text="first value" />
      <AdditionalApprenticeshipProgramContactPart.TextField.FirstName Text="second value" />
      <AdditionalBidsContactPart.TextField.FirstName Text="third value" />
      <CommonPart Owner="/User.UserName=admin" CreatedUtc="2017-07-11T14:30:28.3681873Z" PublishedUtc="2017-07-11T14:30:28.4651858Z" ModifiedUtc="2017-07-11T14:30:28.4581861Z" />
      <IdentityPart Identifier="63638ee501024f26a1d2c30da524cdac" />
    </DetailContact>
```
ref: [slack](https://gitter.im/OrchardCMS/Orchard?at=5964e567bc46472974db6fac)

**Comment by jean** [comment]
@chanond-w :eyes:

**Comment by Xceno** [comment]
Thanks for creating this Issue!
I'll leave a comment later with some more details I've found out while testing yesterday.

**Comment by Xceno** [comment]
Here comes the update:
After testing it out I found that my first assumption was correct. The [ExportContentContext](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/ContentManagement/Handlers/ExportContentContext.cs#L17) will return existing entries with the same name. So exporting multiple fields with the same name is impossible -> Last one wins. Prefixing fields with the part name seems to solve the issue.

I tried out a quick fix with [TextFields](https://github.com/OrchardCMS/Orchard/blob/1.10.x/src/Orchard.Web/Core/Common/Drivers/TextFieldDriver.cs#L87) by introducing these methods:

```
private static string GetExportPrefix(TextField field, ContentPart part) {
    return part.PartDefinition.Name + "." + GetFieldName(field);
}

private static string GetFieldName(TextField field) {
    return field.FieldDefinition.Name + "." + field.Name;
}
```

and updating the **Import** and **Export** methods like this:

```
protected override void Importing(ContentPart part, TextField field, ImportContentContext context) {
    var importedText =
        context.Attribute(GetExportPrefix(field, part), "Text")
         ?? context.Attribute(GetFieldName(field), "Text"); // Try again with the legacy field name, to keep it backwards compatible.

    if (importedText != null) {
        field.Value = importedText;
    }
}

protected override void Exporting(ContentPart part, TextField field, ExportContentContext context) {
    context.Element(GetExportPrefix(field, part)).SetAttributeValue("Text", field.Value);
}
```

The resulting XML:

```
<MyContentItem Id="/Identifier=63638ee501024f26a1d2c30da524cdac" Status="Published">
      <!--This is what were talking about -->
      <FirstPart.TextField.FirstName  Text="first value" />
      <SecondPart.TextField.FirstName Text="second value" />
      <ThirdPart.TextField.FirstName  Text="third value" />

      <CommonPart Owner="/User.UserName=admin" CreatedUtc="2017-07-11T14:30:28.3681873Z" PublishedUtc="2017-07-11T14:56:41.3204657Z" ModifiedUtc="2017-07-11T14:30:28.4581861Z" />
      <IdentityPart Identifier="63638ee501024f26a1d2c30da524cdac" />
</MyContentItem>
```

Importing this new XML works as expected.
So the remaining question is: *what should we do with old exports?*

In the approach above I just fall back to the old, buggy behavior, which will override all fields with the value of the first XML-Entry. If this approach is good enough, we either need to implement it for every single field in orchard, or find a way to throw it into the *ContentFieldDriver* base class.

All opinions are highly appreciated :)

**Comment by jean** [comment]
> In the approach above I just fall back to the old, buggy behavior, which will override all fields with the value of the first XML-Entry. 

One fix would be to **warn** if we see that we have clashing fields:

> This import has ambiguous fields: `TextField.FirstName` will be imported to `FirstPart.TextField.FirstName`, `SecondPart.TextField.FirstName`, and `SecondPart.TextField.FirstName`.
> To fix this, edit the input XML to change elements like 
> `<TextField DisplayName="First Name" ... />` to 
>  `<FirstName.TextField DisplayName="First Name" ... />`

Corner cases: 

- if the Orchard instance has only `TextField.FirstName` on the contenttype, no problem.
- if the Orchard instance has only one `TextField.FirstName` on a part, no problem.
- if the Orchard instance has `TextField.FirstName` on the contenttype **and** on one or more part(s), import to the field on the item and output a warning (_"imported to `TextField.FirstName` on `ContentType`, not to `FirstPart.TextField.FirstName` [, `SecondPart.TextField.FirstName`, ...]"_). 

> find a way to throw it into the `ContentFieldDriver` base class.

That sounds much nicer than implementing it for every existing field and remembering to implement it for every new custom field.

**Comment by Xceno** [comment]
+1 for the warnings, that seems like a really nice idea 👍
