### ISSUE TITLE
record Specify table name

### ISSUE THREAD

**Issue by yangjiale** [OrchardCMS/Orchard#7775]
my module name is Regeister,
IRepository<UserPartRecord> repository
_repository.Table -- this is error,
could not execute query
table 'Regeister_UserPartRecord' don't exist,
how to specify record to db table Name

**Comment by yangjiale** [comment]
Like tablename attribute
[Table('Orchard_Users_UserPartRecord')]
public class xxx
or
[TableName('Orchard_Users_UserPartRecord')]
public class xxx

**Comment by sebastienros** [comment]
You create a Migration class that creates the table for you. The name is defined by convention and can't be customized.
