### ISSUE TITLE
Gallery is broken - new module/theme cannot be installed

### ISSUE THREAD

**Issue by atiq-cs** [OrchardCMS/Orchard#7776]
Screenshot attached:
<img width="968" alt="orchard-1 10 2" src="https://user-images.githubusercontent.com/7858031/28244946-c9310f5e-69ae-11e7-86ff-32779a075f8c.png">

This is showed when we try to access Modules or Themes etc. I have tried a number of times. I did a fresh reinstall on Azure and got the same problem. Any hint/idea please how to fix this? Thanks.

**Comment by atiq-cs** [comment]
Seems to be okay now.
<img width="968" alt="fftsys_modules_gallery" src="https://user-images.githubusercontent.com/7858031/28503222-6ac08aa8-6fb7-11e7-85bf-dd403b121370.png">

**Comment by sebastienros** [comment]
Couldn't get my emails for some time, and it was the SSL certificate that expired. I renewed it and it fixed the issue.
