### ISSUE TITLE
Changes that broke Blog Editor also broke the NGM.Forum Forum editor

### ISSUE THREAD

**Issue by cyberjaxx** [OrchardCMS/Orchard#7778]
Changes that broke Blog editor also broke the NGM.Forum Forum editor.
NGM.Forum\Controllers\ForumAdminController.cs line 127
        [InternalFormValueRequired("submit.Save")]

> Corrected expected form value for Blog.Publish action. Fixes #7698.

**Comment by cyberjaxx** [comment]
Breaking changes are related to #6388.

**Comment by sebastienros** [comment]
Is there a way to file the bug on the forum's project?
