### ISSUE TITLE
You can't organise editors into tabs using Edit Placement 

### ISSUE THREAD

**Issue by Hazzamanic** [OrchardCMS/Orchard#7791]
From version 1.9 (or 10?) you can move editors into tabs using #tab_name in your module's Placement file. However, you can't control this from the admin area using Edit Placement. That screen should be revamped to allow tabs to be created and editors moved between them

**Comment by HermesSbicego-Laser** [comment]
@Hazzamanic @sebastienros Is it possible to have this feature mergeable in 1.10.x? I have tried to merge it by myself but it seems like if the fix was branched from dev and not from 1.10.2; am I right?
