### ISSUE TITLE
Some shape's placement cannot be overridden in the Edit Placement feature

### ISSUE THREAD

**Issue by Hazzamanic** [OrchardCMS/Orchard#7794]
It is caused by shape type keys in the shape table descriptors have differing cases to the name specified by Content Shape. For example the owner edit shape is stored as a placement setting on the content type as: Parts_Common_Owner_Edit but the corresponding shape in the descriptor dictionary is all lowercase: parts_common_owner_edit. So when it tries to find the shape type key to register a placement override it cant. This comes from Orchard.ContentTypes.Services.ContentTypePlacementStrategy

**Comment by sebastienros** [comment]
Should we do a case insensitive search instead?

**Comment by Hazzamanic** [comment]
I guess so, but being a dictionary I think we'd need to change the dictionary to have a case insensitive key comparer?

**Comment by Hazzamanic** [comment]
Fixed in https://github.com/OrchardCMS/Orchard/pull/7904
