### ISSUE TITLE
.NET Runtime version 4.0.30319.0 - The profiler was loaded successfully

### ISSUE THREAD

**Issue by MuraliAele** [OrchardCMS/Orchard#7800]
<System>
<Provider Name=".NET Runtime"/>
<EventID>1022</EventID>
<Level>0</Level>
<Task>0</Task>
<Keywords>Keywords</Keywords>
<TimeCreated SystemTime="2017-07-31T00:56:24Z"/>
<EventRecordID>-1089492812</EventRecordID>
<Channel>Application</Channel>
<Computer>RD00155D2AA144</Computer>
<Security/>
</System>
<EventData>
<Data>
.NET Runtime version 4.0.30319.0 - The profiler was loaded successfully. Profiler CLSID: '{324F817A-7420-4E6D-B3C1-143FBED6D855}'. Process ID (decimal): 5544. Message ID: [0x2507].
</Data>
</EventData>

**Comment by sebastienros** [comment]
What is the issue here?
