### ISSUE TITLE
add Mello.ImageGallery

### ISSUE THREAD

**Issue by Number30** [OrchardCMS/Orchard#7804]
I got this error while adding Mello.ImageGallery 
The assembly reference 'System.Drawing' could not be loaded for module 'Mello.ImageGallery'. 

There are generally a few ways to solve this issue: 
1. Install any dependent module. 
2. Remove the assembly reference from the project file if it's not needed. 
3. Ensure the assembly reference is present in the 'bin' directory of the module. 
4. Ensure the assembly reference is present in the 'bin' directory of the application. 
5. Specify the strong name of the assembly (name, version, culture, publickey) if the assembly is present in the GAC.

how could I resolve it ? 
thanks for any help

**Comment by ViRuSTriNiTy** [comment]
This module is not compatible with the current Orchard release. I've tested this module like 3 days ago and you need to fix several things. As far as i remember these were the steps:

1) remove the lib folder
2) remove all references that are pointing to the lib folder
3) go to project settings and set the .net framework from 4.5.1 to 4.5.2
4) compile and fix error by error by adding the appropriate packages via nuget package manager

Also you should use the GitHub fork as it has already some issues fixed: https://github.com/kissstudio/orchardimagegallery

Beware that this module has some serious bugs in it, for example don't give a gallery a name with spaces.

**Comment by Piedone** [comment]
Closing because it's not an Orchard bug, but feel free to continue the discussion.
