### ISSUE TITLE
MvcModule.HttpContextBaseFactory() causes exception when BaseUrl setting is not set

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [OrchardCMS/Orchard#7811]
Hi there,

the `baseUrl` variable that is passed to the `HttpContextPlaceholder` constructor is defined as

    var baseUrl = new Func<string>(() => 
        siteService.GetSiteSettings().BaseUrl
        ?? "http://localhost" /* When Setup is running from the command line, no BaseUrl exists yet. */);

whereas `siteService.GetSiteSettings().BaseUrl` might return an empty string (because nothing is entered in the admin settings page) which in return causes some exceptions when the empty base url is used later on (e.g. to create a `System.Uri` object).

I've changed the code to

    var baseUrl = new Func<string>(() => {
        var s = siteService.GetSiteSettings().BaseUrl;

        if (string.IsNullOrEmpty(s))
            return "http://localhost"; /* When Setup is running from the command line, no BaseUrl exists yet. */
        else
            return s;
    });

and no exception is logged anymore.

Should i provide a PR?

**Comment by sebastienros** [comment]
Yep, 

```
// When Setup is running from the command line, no BaseUrl exists yet.
return string.IsNullOrEmpty(s) ? "http://localhost" : s; 
```
