### ISSUE TITLE
Updates Newtonsoft.Json to 10.0.3

### ISSUE THREAD

**Issue by armanforghani** [OrchardCMS/Orchard#7814]
The current version of Newtonsoft.Json (7.0.1) is outdated. I suggest for updating to latest version 10.0.3.
I have several problems with third-party components that need newer version.

**Comment by Piedone** [comment]
I agree. As a temporary workaround you can add the new version in a module for example and then set an assembly redirect in the root Web.config.

**Comment by Jetski5822** [comment]
+1
