### ISSUE TITLE
Unable to save creation date of content (Orchard v.1.10.1.0)

### ISSUE THREAD

**Issue by GioviQ** [OrchardCMS/Orchard#7822]
![modifica blog post muscoli info](https://user-images.githubusercontent.com/7103057/29497780-801468a0-85ee-11e7-85f4-82e812eff57d.png)
In Orchard v.1.10.1.0 localized in Italian I cannot change the creation date of a blog post as shown in figure above with a warning about invalid date.

**Comment by BenedekFarkas** [comment]
I couldn't repro this with 1.10.1 (a629ce0f4b02179399249c44915e0f6317d748b1), neither with the latest 1.10.x commit. @GioviQ can you please check again on the latest 1.10.x commit?

@HermesSbicego-Laser have you or the other Laser guys seen this kind of error recently?

**Comment by HermesSbicego-Laser** [comment]
No, as far as I know never seen before but I will check deeper on monday.

**Comment by sebastienros** [comment]
Almost sure it works, and that we have a specflow test for it.
