### ISSUE TITLE
Comments total at /Admin/Blogs is always 0

### ISSUE THREAD

**Issue by robertwray** [OrchardCMS/Orchard#7838]
This issue can be seen by either:
- Clicking on "Blog" in the /Admin menu (for an Orchard instance where there is more than one blog)
- Navigating directly to /Admin/Blogs (for an Orchard instance where there's only one blog which results in clicking on "Blog" in the /Admin menu taking you to the posts view for that blog)

The text under the name of the blog will look something like this:

> 0 comments |   Last modified: 7 days ago |  By robertwray

The issue is that, irrespective of the number of comments actually present against individual blog posts, the totaliser will always state "0 comments". I *think* this is due to the fact that `CommentsContainerPartDriver` (from Orchard.Comments) asks the commentService for the number of comments associated with the ContentItem for the *blog*, which is *0*, rather than asking for the number of comments associated with the blog posts associated with the blog.

Unfortunately I'm too new to the Orchard codebase and how it all hangs together to work out how this could be fixed, other than by simply removing the field that indicates the number of comments against the blog.

**Comment by Hazzamanic** [comment]
Weirdly, the comments module attaches the comments container part onto the blog content type in it's migrations. I assume someone meant to attach it to the blog post, not that it has any business doing that. So basically it is a mistake, the comments container part (which displays the number of comments), should not be attached to the blog content type and be displayed at all

**Comment by robertwray** [comment]
I can see the utility in having the aggregate number of comments (specifically the number that are pending) for a given blog visible at the blog level, rather than at a post level, so perhaps there was an intention to provide that, albeit one that didn't work?

Is it feasible to have a solution in Orchard that allows something that contains items (e.g. a blog, or a list?) which have comments associated with its distinct member items to report back aggregate totals, without writing the mother of kludges to achieve that?

**Comment by Hazzamanic** [comment]
Actually, I was wrong and you were right. It looks like the part being attached is named to be attached to the container i.e. the blog. But yeah it just totally fails to implement that functionality. It also returns the same shape name as that which is used for the CommentsPart count. And the container part is not attachable. Overall, a big fail. 

I too have a site with many blogs and this functionality would actually be pretty cool so I just chucked together a quick module for it. Some of the blogs have quite a lot of posts and querying for the comment counts was a bit of a performance hog so I am storing aggregates. The module is here: https://github.com/Hazzamanic/Hazza.Blogging. The module hides the broken container comments. To use enable the feature 'Blog Comment Count' and attach the ContainerCommentsCountPart to your Blog type. The counts will update when a comment is added to any blog post in that blog (or updating the status of a comment in the comment admin area). 

I'm not sure if it is worth integrating this into core or removing the broken attempt and letting people use their own solution/this extension. 

Note: If you cant install a module or just want to add the functionality to the comments module in place, you can find the queries here: https://github.com/Hazzamanic/Hazza.Blogging/blob/master/Services/ContainerCommentProcessor.cs#L40 and chuck them into the driver Orchard.Comments.Drivers.CommentsContainerPartDriver and replace the funcs to calculate the comment counts with those queries.

**Comment by Hazzamanic** [comment]
@sebastienros do you want me to add this to core? or just remove the broken views from core and let people use a module to do this?

@robertwray I added the blog comment overview to the blog management page too, which is a pretty nice way to see comment overviews for your blog. That was a lot of blog

**Comment by jchenga** [comment]
Pull request created: #7847

**Comment by Hazzamanic** [comment]
Haha good catch, I totally didn't even see that the comments contain that property! Much simpler

**Comment by sebastienros** [comment]
The PR sounds good, I commented on it as it's a breaking change.

**Comment by jchenga** [comment]
Pull request created: #7853. The change is based on dev branch as requested.
