### ISSUE TITLE
Local development gitignore

### ISSUE THREAD

**Issue by nathansizemore** [OrchardCMS/Orchard#7839]
I'm waiting to do local development against a remote db. Cloned the repo, setup initial site. `git status` returns nothing to check in. What files/directories do I need to enable in the gitignore to ensure anything done in local dev gets picked up by source control?

**Comment by robertwray** [comment]
There's an "Orchard specific" section in gitignore. 

From memory, the only thing you *really* need from a configuration perspective is the content under src\Orchard.Web\App_Data\Sites as this (specifically the "Settings.txt" file under the folder for the tenant, e.g. *src\Orchard.Web\App_Data\Sites\Default\Settings.txt* for the default tenant) is what tells Orchard where to look to for the database and what's configured.
