### ISSUE TITLE
Localization does not work

### ISSUE THREAD

**Issue by armanforghani** [OrchardCMS/Orchard#7840]
I updated my source with branch 1.10.x. All translations stop working.

I think [this commit](https://github.com/OrchardCMS/Orchard/commit/eff20785aaba35089e394916d51503578668be73) causes the problem.

**Comment by MatteoPiovanelli** [comment]
what have you been localizing? What issues are you seeing?
We are doing localization for a website these days, and it's not been giving trouble.

**Comment by gcsuk** [comment]
If you revert that commit's change does it all start working again?

**Comment by andrewcartwright1** [comment]
Could you please share a sample of your localization file?

**Comment by armanforghani** [comment]
Sorry for my delay. I was busy.
@gcsuk Yes. i replaced previous version (```dbb5668d```). It works correctly.
@andrewcartwright1 I am using standard format based on documentation. Here you can see an example.

```
#. "Name"
#: "~/Core/Dashboard/Module.txt"
msgctx "~/Core/Dashboard/Module.txt"
msgid "Dashboard"
msgstr "پیشخوان"

#. "Author"
#: "~/Core/Dashboard/Module.txt"
msgctx "~/Core/Dashboard/Module.txt"
msgid "The Orchard Team"
msgstr "تیم ارچارد"

#. "Website"
#: "~/Core/Dashboard/Module.txt"
msgctx "~/Core/Dashboard/Module.txt"
msgid "http://orchardproject.net"
msgstr "http://orchardproject.net"
```

**Comment by andrewcartwright1** [comment]
Theres a typo with your msgctx its supposed to be: msgctxt - Can you correct this and retest?

With the old implementation your msgctxt is being skipped over.
This implementation is more strict then the last one 😃

**Comment by armanforghani** [comment]
@andrewcartwright1 Thank you for the notice. I fixed it. Everything is OK.
