### ISSUE TITLE
Create default sort for content fields??

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/Orchard#7842]
What is the default sort when creating content content in custom content?

 I am now building the order is "
《序号Number (Numeric Field) 
                     ↓
员工工号Worker Number (Text Field)
                     ↓
​姓名Name (Text Field)
                     ↓
性别Gender (Enumeration Field)
                     ↓
部门Sector (Text Field)
                     ↓
职位Job (Text Field)
" Why is the default not sorted up and down in order?? 
(PS:  It seems to be anti-human practice??)

![qq 20170909184626](https://user-images.githubusercontent.com/28694676/30239442-5ddc1fa2-958f-11e7-81d7-3f4fd8dc8a6c.png)

**Comment by pgy866** [comment]
I am sorry，Sorry, maybe I do not know enough about the use of OrchardCMS

**Comment by sebastienros** [comment]
Use Placement.info to reorder the fields in the front end, but usually devs write their own template directly. You can also use Query projections.
