### ISSUE TITLE
upgrade Bing.Maps Module to Bingmaps V8

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#7844]
I'm a happy user of Bing.Maps since quite some time but found that the version available isn't compatible with todays BingMaps V8! V6 is NOT supported anymore!
Below script is out of date since quite some time:
Script.Include("http://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=6.2");

With some changes in both BingMap.cshtml modules in ... 
Views/EditorTemplates/Parts (some keywords like road, aerial etc have changed!)
Views/Parts (scripts have changed)
... I can now use Bing.Maps with BingMaps Version8.

Perhaps Bertrand (as the owner) can update the Bing.Maps.nuGet package.

Attached the 'Views.zip' folder. As I'm not a BingMaps specialist one probably could streamline the .cshtml files even more!

I'm pretty sure some others would appreciate a updated Bing.Maps Module!
ed

Name: Bing.Maps
AntiForgery: enabled
Author: Bertrand Le Roy
Website: http://weblogs.asp.net/bleroy
Version: 1.7.0
OrchardVersion: 0.5.0
Description: Bing Maps part and widget
Features:
    Bing.Maps:
        Description: Bing Maps part and widget
        Category: Geolocation
[Views.zip](https://github.com/OrchardCMS/Orchard/files/1292003/Views.zip)

**Comment by sebastienros** [comment]
If the module doesn't get updated, you should just release a new one with the changes.
