### ISSUE TITLE
Add Container、containable widget, if you don't add a title widget, manage edits to an error

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/Orchard#7857]
Add Container、containable widget, if you don't add a title widget, manage edits to an error

**Comment by sebastienros** [comment]
Please provide repro steps.

**Comment by pgy866** [comment]
1.New Content Types
2.​Add  Containable Parts
3.Add this content type content post or save error
4..It's normal to join the Title Parts。
![6](https://user-images.githubusercontent.com/28694676/30742588-5d9333b8-9fcc-11e7-8e8b-026a67bdd9ad.gif)

**Comment by sebastienros** [comment]
To rephrase, looks like a Containable type without a title cannot be edited/displayed, because the breadcrumb logic looks for it.

**Comment by pgy866** [comment]
Yes, must be added Title Title can, very sorry, my English is very bad。

**Comment by sebastienros** [comment]
TitlePart is mandatory for widgets, by design.
