### ISSUE TITLE
Taxonomy Field no longer displays all possible values

### ISSUE THREAD

**Issue by Jabberrwocky** [OrchardCMS/Orchard#7862]
I recently upgraded a client's Orchard CMS installation from 1.9.x to 1.10.2. Everything went smoothly. However, we are missing some functionality that was previously available.

Before, to select a topic (Taxonomy Field), I would click in the Topics field and a box with all available topics would appear. I would then click on the desired topic. To add more topics, I just had to repeat.

Now, however, clicking on the field does nothing. A cursor appears in the box, but no topic window appears...

...until I start typing. But here’s the catch. If I type an ‘a’ only topic names that contain an ‘a’ are shown. Any topic that does not contain an ‘a’ is not shown.

If I know the topic I want, no problem. I simply start typing it, and the topics list will filter itself accordingly and I just need to click the topic to add. Repeat as needed.

The problem with this is that if I don’t know the topic the I want, there’s no way to easily know what topics are available. And if I wasn’t aware that the list was filtered based on the letter I typed, I might assume that a certain topic wasn’t entered into our system.

Is it possible to go back to the old way the Taxonomy Field was set up?

Thanks.

**Comment by thekaveman** [comment]
It sounds like the Autocomplete option has been enabled - you can check in the *Content Definition* section of the Admin, by looking at your Type and expanding the settings for the Part that contains your Taxonomy Field. 

Here's an example from one of my Parts that has a topics Taxonomy Field:

![image](https://user-images.githubusercontent.com/1783439/30676909-7ded91c0-9e3d-11e7-9012-18391fce5eb0.png)

**Comment by ViRuSTriNiTy** [comment]
@thekaveman Nope, disabling autocomplete completely removes the input field and replaces it with a radio selection. I have just analyzed the issue and i'm going to provide a PR.

**Comment by Jabberrwocky** [comment]
Thank you, @ViRuSTriNiTy.

**Comment by Jabberrwocky** [comment]
Is it safe to close this now?
