### ISSUE TITLE
 Evil out of date = user-scalable=no

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#7869]
user-scalable=no was for older browsers and kills zoom on phones and tablets.
As in this tag`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0**, user-scalable=no**">`
    Do your own google search or see below
See[ ](https://codepen.io/absolutholz/post/user-scalable-no-evil-or-slightly-not-evi)https://codepen.io/absolutholz/post/user-scalable-no-evil-or-slightly-not-evil 
or
[https://ux.stackexchange.com/questions/80487/revisiting-user-scalable-no](https://ux.stackexchange.com/questions/80487/revisiting-user-scalable-no)

**Comment by Jetski5822** [comment]
@donaldboulton How come you closed?
