### ISSUE TITLE
In Orchard 1.XX is marked so much,Is not going to be abandoned?

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/Orchard#7872]
In Orchard 1.XX is marked so much,
But only 1%
Is not going to be abandoned?
Did all the teams revolve around OrchardCore?

*****It is very honored to be an Orchard user, but I am not a programmer, so a lot of wrong problems, I can not repair, I hope the team do not give up, very grateful to all the dedication!*******

![image](https://user-images.githubusercontent.com/28694676/31044929-9cac8028-a60b-11e7-9175-7612fd29556a.png)

**Comment by sfmskywalker** [comment]
Many people and companies are heavily invested in Orchard 1, so I wouldn't worry about it being abandoned anytime soon.

**Comment by AryanShadowhunter** [comment]
Based on Orchard's core changes on GitHub and continuous builds in Orchard's TeamCity page (https://teamcity.jetbrains.com/project.html?projectId=Orchard&tab=projectOverview) I think it is actively developing.

**Comment by sebastienros** [comment]
The percentage doesn't represent anything. We just tag 1.10.x to mark an issue that can be done any time without doing any breaking change.
