### ISSUE TITLE
Orchard.Workflows requires styles that not exists

### ISSUE THREAD

**Issue by MarcoViglione-Laser** [OrchardCMS/Orchard#7873]
In the ResourceManifest.cs file of the Orchard.Workflows module there is a foreach that creates a DefineStyle for each existing activity, searching their corresponding css in the Orchard.Workflows/Styles folder.
If that file does not exist there will be a missing reference error in the page where we edit a workflow.

The procedure should check if the file exists before adding the requirement and add it only if there already is a css with the corresponding name. Maybe it should also search in the styles folder of the module where the activity is defined.

**Comment by sebastienros** [comment]
This is how it has been designed, but we have found better ways to add dynamic css in the meantime. For instance by just having a specific shape add the dependency on the <link> resource. Maybe a way to go. To be more specific, we call an alternate or a shape type for each activity, and this one will include or not some resources.

**Comment by MarcoViglione-Laser** [comment]
Any news about a fix?

**Comment by sebastienros** [comment]
There is a PR here: https://github.com/OrchardCMS/Orchard/pull/8009/files

can anyone test it?

**Comment by sebastienros** [comment]
Can anyone who is concerned by this issue try the PR https://github.com/OrchardCMS/Orchard/pull/8009
