### ISSUE TITLE
Replace Image is not updating last modified and by properties

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/Orchard#7874]
The replace image has been a big deal with a lot of ours users, but we have found that it doesn't update the Last modified time and by in the properties view. see attached screen cap. I uploaded a file, waited 4 minutes, then uploaded another and the properties I highlighted didn't change.

![lastmodifiedproperties](https://user-images.githubusercontent.com/549504/31136787-020cf38a-a81e-11e7-93b2-dd607d1dfcf8.png)

**Comment by roballred** [comment]
Did this not get added to 1.10.3? @sebastienros @Piedone

**Comment by Piedone** [comment]
Not, unfortunately. The PR was merged into dev, i.e. the upcoming 1.11 version's branch.
