### ISSUE TITLE
PLEASE HELP : [Orchard 1.10.2] Ajax "Post" fails when logged in

### ISSUE THREAD

**Issue by Vahradrim** [OrchardCMS/Orchard#7881]
Hello everyone !
I am very depressed on this one..

**My problem :**
When I log in (through the native Orchard form, with the user "admin") all Ajax callbacks in "POST" fail, I get a Javascript Popup with the message : "Object not set to a reference of an object"
It perfectly WORKS when NOT connected, and totally works with the "GET" method (when logged in or not, "GET" method always works).
The MVC methods called are both decorated with [HttpPost] and [HttpGet]
The breakpoints are reached except in "POST" when logged in (Javascript error 500 with popup message "Object not set to a reference of an object").

**My installation :**
Orchard 1.10.2
I created a tenant called "NEC" and I log in to it. (With the correct URL)
No module activated on this tenant except the one I use to display 2 buttons (One Ajax postback in "GET" the other one in "POST").
The user ("admin" I'm connecting with) has the role "Administrator" (with all privileges possible)

I struggle on this one for a week now, so if someone can help me that would be great
Thanks to all

**Comment by sfmskywalker** [comment]
Are you including the antiforgery token when making the POST request?

**Comment by sfmskywalker** [comment]
See also: https://stackoverflow.com/questions/9029402/orchard-cms-ajax-anti-forgery-token-when-logged-in/9039504#9039504

**Comment by Vahradrim** [comment]
First, thank you very much for your answer.
Unfortunately it still doesn't work even with this test :

> function CallbackTestPost()
    {
        $.ajax({
            type: "post",
            dataType: "",
            url: '@Url.Action("TestCallbackPost", "Test")',
            data:
            {
                __RequestVerificationToken: '@Html.AntiForgeryTokenValueOrchard()'
            },
            success: function (response) { alert(response.responseText); },
            error: function () { alert("Error on callback Post"); }
        });
    }

The request fails the same way : "Object not set to a reference of an object".

What am I missing ?

**Comment by sfmskywalker** [comment]
Can you execute the request with debugger attached, but making sure that the debugger breaks on ALL exception types listed in the "Common Language Runtime Exceptions" category? I.e.:

![image](https://user-images.githubusercontent.com/938393/31442472-da49c7ea-ae96-11e7-81cb-f4ce533ef26b.png)

Make sure it is checked as in my screenshot.
Now when the error occurs, the debugger should break exactly where the NRE is thrown, which should help you identify the issue. Interesting information to know is: what class and method throws the exception? Make sure to do this with a full source Orchard solution.

**Comment by Vahradrim** [comment]
Yes it's done, I have a full source Orchard, however (in my package at least) there is no Orchard.Framework.dll source (no .pdb found) and the error occurs inside it :
No symbol loaded
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\f277b3c9\b868d4e8\assembly\dl3\59fed778\00329985_89bfd201\Orchard.Framework.dll

That's why I'm in the dark, maybe my package is not complete (in source code files) ?

**Comment by sfmskywalker** [comment]
Then there may be something wrong with your package. When you download (or clone) the full source code, you will have source code for Orchard.Framework. I would double check that (simply see if you have the source files of the Orchard.Framework.csproj class library). If you do, try doing a rebuild. And perhaps clean out your Temporary ASP.NET files while you're at it.

**Comment by Vahradrim** [comment]
Thank you for your help, I will try to reinstall everything with the full source code, this way I might be able to raise the exception exacty where the error occurs.

Have a great day :)
