### ISSUE TITLE
Tenant reset does not delete all tables

### ISSUE THREAD

**Issue by MarcoViglione-Laser** [OrchardCMS/Orchard#7885]
If I reset a tenant through the multitenancy page it only deletes the database tables created by the currently enabled modules.
If I enabled a module and then disabled it, the tables it created will not be deleted by a reset and will remain inside the database.
This can be a problem, because if I try to enable again those modules after doing another setup of the resetted tenant I receive an error, caused by the fact that the migrations try to create again some tables that already exist.

**Comment by sebastienros** [comment]
It's new to me that table are deleted. I thought it was only handled by each module if they implement `Uninstall()`

**Comment by mdameer** [comment]
@sebastienros, I checked the current implementation and found that it trying to get the table names to be dropped through NHibernate 'ClassMappings' object, which will contains only mappings for enabled modules record classes, so we need to find another way to bring all table names with support for all database engines which supported by Orchard.

**Comment by sebastienros** [comment]
Or implement the Uninstsall methods so that when a module is uninstalled it correctly removes the tables and indices it created. Then the remaining tables would be all registered already, and the remaining module could just also delete their own tables.

**Comment by HermesSbicego-Laser** [comment]
I think there is a difference between uninstalling a module and resetting a tenant. If I uninstall a module I don't want to drop the tables too, beacause **I will loose all datas** of the uninstalled module and **of the modules depending from it too**!!!; So I think it's a bad idea to drop tables implementing the Uninstall method. 
Different are the needs when I want to reset a tenant, because I want to drop all the tables, for both installed and uninstalled modules.
@sebastienros @mdameer what do you think?

**Comment by sebastienros** [comment]
But we'd need to remember that a module was once installed to be able to delete the tables. But I could agree with you, and then only on reset we would look at the migrations and detect which ones need to be uninstalled, not using the enabled modules, but actually what migrations were executed. Doable.

**Comment by mdameer** [comment]
@HermesSbicego-Laser, I'm totally agree with you, so I suggest to find a solution to load the database metadata, then dropping all tables will be very simple,  I'm trying to find a way to implement this solution, but the main problem is that we are dealing with different database types.

@sebastienros, regarding the uninstalling mechanism, I think it should be a user choice to delete or keep the tables which was created by the module, what do you think?

**Comment by sfmskywalker** [comment]
@mdameer If you're looking to drop all tables, look no further: I already wrote it for you ;) https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.ImportExport/Services/DatabaseManager.cs

**Comment by mdameer** [comment]
@sfmskywalker, it's so nice to hear from you again, I think the code you shared will have the same impact, as long as it depends on Nhibernate class mappings to load the database schema, can you please take a look at my suggested solution in PR #8031 and give me your feedback.

**Comment by sfmskywalker** [comment]
I see. My code does indeed depend on NHibernate class mappings. And since the "reset tenant" functionality relies on this, that feature is potentially broken if someone disables a feature that created a table.

I looked at your PR, and it looks good to me.

**Comment by sfmskywalker** [comment]
And yes, it's great to hear again from you too :)
