### ISSUE TITLE
How to Multi-Lingual and multi-culture ?

### ISSUE THREAD

**Issue by joshi062** [OrchardCMS/Orchard#7895]
Hi All,

We are about to using Orchard CMS 1.10.2 for our new site. As per the requirement we have to work  with Multi-Lingual and multi-culture. For example if we publishing some content from, US in US English (en_US) and French - Canada(fr-ca) languages and it should be publish as per the respective country time zone.Is any built-in culture module having this same or similar functionality available with CMS ? If it is possible then how can we implement or need to develop custom functionality for the same.Thank You.

**Comment by pgy866** [comment]
@joshi062

http://docs.orchardproject.net/en/latest/Documentation/Builtin-Features/#orchardlocalization

Out of the box can be used

**Comment by sebastienros** [comment]
You will find many video on youtube showing what you can do. And yes, you can with Orchard.
