### ISSUE TITLE
Fields are not indexed if content is not published

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#7903]
At the present a field is indexed only when a content is published. The module which is responsible of indexing fields, is the projections module via FieldIndexPartHandler.OnPublishing. Now I understand why the index is populated only on publishing because we normally use it in queries/projections in the front-end of a site. But if I would like to use it in back-end? 
I've this use case:
2 Content Types Event (Event 1 published, Event 2 unpblished, Event 3 unpblished) and Edition (Spring 2017 published, Summer 2017 unpublished): Event has a Content Picker Field referencing an Edition (Event 1 > Spring 2017, Event 2,3 > Summer 2017).
What I would like to achieve is that when I publish the Edition "Summer 2017" I want to publish Event 2 and 3 too; but I cannot search for those events because the index is not yet there to be searched for and searching the field into infoset is not doable due to perfomance issues when contents are a lot.
The idea is to make the index tables (StringFieldIndexRecord and so on) "versionable" relating them to ContentItemVersionRecord table; in alternative we could index published and latest version.
Is there another way to achieve my goal?

**Comment by sebastienros** [comment]
Have you tried the option that lets you index drafts in the content type settings?

**Comment by HermesSbicego-Laser** [comment]
If you mean the dropdown list that permit to choose to index between published and latest version it is not useful for us - if I remember well, is for fulltext indexing and lucene...

**Comment by sebastienros** [comment]
My bad, you're right

**Comment by HermesSbicego-Laser** [comment]
So, any idea/solution?
1. Make fieldindexpart versionable? I see perf problems with lot of records or fields
2. Indexing latest and published only? How?
3. Any other idea?
No one has the same needs?
Ty for sharing ideas. ..

**Comment by sebastienros** [comment]
Maybe add a column with the latest value. And a filter could have an option to use the latest value (which would be either the published or the draft if there is any).
That should be easy to implement and not impact perf. The defaults should be Published for filters, or this would be a breaking change.

**Comment by HermesSbicego-Laser** [comment]
Ok, I like the solution. we will work on it.

**Comment by HermesSbicego-Laser** [comment]
I'm working on this new feature:
1. I created the new table columns via migration: I noticed that columns "PropertyName" and "Value" of the tables StringFieldIndexRecord, IntegerFieldIndexRecord, DecimalFieldIndexRecord, DoubleFieldIndexRecord are not indexed (SQL Index); I think they should be indexed (because they are in the where/order by clause) so i will index them, as well as for the new column LatestValue
2. Save/publish the content store values in the appropriate fields via handler
These two changes are enough for our purpose because they give us a way to query the LatestValue via HqlQuery or IRepository.

That said, I liked the idea to add a filter for queries, but things are more complicated and we have some extra work here:
3. ProjectionManager query only the PublishedVersion of a content https://github.com/OrchardCMS/Orchard/blob/cd9bccef964f03e02c5318f2a33376984367a9be/src/Orchard.Web/Modules/Orchard.Projections/Services/ProjectionManager.cs#L205, so we should add the ability to query also the LatestVersion of a content (default will remain the published one).
4. Then, to query the Value or the LatestValue of a field should not be an option to choose field by field in the query UI, because the choice is implied by the previous choice (published/latest)

I will create a second issue so I can PR points 1 and 2. And in the meantime I will work on points 3 and 4.
@sebastienros?

**Comment by HermesSbicego-Laser** [comment]
I am searching for an example to add index via migration... And I don't like what I see...
@sebastienros, Is it possible that SQL Indexes are missing within all the tables? From what I see only the PK is set. I Think at least the most used one should be there.
- TitlePartRecord.Title 
- CommonPartRecord.ModifiedUtc, CreatedUtc, PublishedUtc, ModificedBy.

This could be the cause of slowness in showing lists? Am I wrong?

**Comment by sebastienros** [comment]
Some indices are already create in migrations. Not everything as it usually depends on what usage you are doing of the db. It should be a case by case, unless it's something that all site have to do and then we add the index. Here is an example: https://github.com/OrchardCMS/Orchard/blob/6720b71cf3474a9a7b8a8cc9a99d58b1e733acfa/src/Orchard/ContentManagement/DataMigrations/FrameworkDataMigration.cs#L56

Not sure we should add indices on the field tables by default, not all sites do queries on these. But you can definitely add some based on your stats.

**Comment by HermesSbicego-Laser** [comment]
In the light of #7923, could be closed?
