### ISSUE TITLE
The Alias UI links for sites using UrlPrefix are broken

### ISSUE THREAD

**Issue by Hazzamanic** [OrchardCMS/Orchard#7919]
The UrlPrefix is manually added to the alias and root urls  but the helper methods do that automatically so the links are broken

**Comment by sebastienros** [comment]
Can you provide a repro? And do you know which commits broke this? Also, 1.10.x or dev ?

**Comment by Hazzamanic** [comment]
Sorry, for the delay, and terrible issue description...

I think it is both 1.10.x and dev. Repro is to create a tenant using a UrlPrefix, enabling Alias UI and trying to click on any links in either Managed or Unmanaged, they don't work.

 I reckon the commit that broke it was very old, when Href was made tenant aware and the tenant prefix was never stripped from the Alias UI views which add it manually. There is also another problem where this commit: https://github.com/OrchardCMS/Orchard/commit/9c2ea8067094d9ed02f50bcd372bf445ff2e81ee#diff-3806ff11c9d923fac04777c83296a19e reverted this fix: https://github.com/OrchardCMS/Orchard/commit/a4894930f054fa9521fb4ea98594dd60fea72152 to using Href with a tenantprefix as it strips out the leading slash. Explained in more detail in this issue https://github.com/OrchardCMS/Orchard/issues/4540 This means Href is actually pretty broken if you use a UrlPrefix

**Comment by Hazzamanic** [comment]
I made a pull request to fix the original issue. I have also fixed the Href method, reverting what the commit I mentioned above broke. Did you want them as two separate PRs?
