### ISSUE TITLE
ReferencedExtensionLoader loads dynamically compiled extensions that are referenced instead of DynamicExtensionsLoader

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#7924]
This is currently breaking Dynamic Compilation on `dev` (but not on `1.10.x`, which I can't explain). So extensions that aren't referenced (i.e. they are leaves of the dependency tree) are loaded correctly with DynamicExtensionsLoader.

**Comment by BenedekFarkas** [comment]
@sebastienros 

So after a bit more digging, it all comes down to `Orchard.Web` having a reference to `Orchard.Glimpse` (without that, the decorators that allow measurements related to Orchard features are not working). Besides the projects that are referenced by `Orchard.Web`, the following projects cannot be loaded dynamically due to being part of the reference tree that start with `Orchard.Glimpse`:
`Alias, Autoroute, Caching, Conditions, ContentTypes, Forms, Glimpse, Layouts, Localization, MediaLibrary, Packaging, Projections, Scripting, Themes, Tokens, Users, Widgets, Workflows`

This kind of bothers me, but it's something we can live with - Dynamic Compilation is OK for other projects (as long as they aren't added to that reference tree), even if they reference one of those projects.

On the other hand, Glimpse will always be loaded when the application starts, no matter what (e.g. `/Glimpse.axd` is accessible even when the feature is disabled), so it's most of the time unnecessary. We also found that it can interfere with other components (Entity Framework in that case).
Do you have any idea for alternative way to integrate Glimpse without making it basically mandatory?

**Comment by sebastienros** [comment]
No idea, I am too rusty in O1.

**Comment by BenedekFarkas** [comment]
OK, so the conclusion is that an project that is part of the reference tree which starts with Orchard.Web can't be Dynamically Loaded. This doesn't really matter for custom modules, because they won't be part of that tree of references, so this doesn't block 1.11.
