### ISSUE TITLE
When viewing Blog as an admin, there is a "Publish" and "Save Comment" button that does the same thing

### ISSUE THREAD

**Issue by DForant** [OrchardCMS/Orchard#7927]

**Comment by sebastienros** [comment]
I didn't know there was a "save comment" in a Blog. Have you changed anything or does it repro with the default recipe?

**Comment by DForant** [comment]
It was with the built in recipe. But even if i changed themes it was there
as well. When I have the chance to get in front of my computer i will take
a screen shot and send it

**Comment by BenedekFarkas** [comment]
@sebastienros, I changed the milestone to dev, because it's caused by a change (332a2676dddf0a08458d287f48d0feaa1bd82eea) on that branch.
