### ISSUE TITLE
Orchard 1.10.2 Web Config Newtonsoft.json added twice

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#7931]
Lines 199 and 233 duplicate of below assembly      which is 7.0.1 according to packages config     not 7.0.0
 <dependentAssembly>
                <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
                <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
            </dependentAssembly>

**Comment by sebastienros** [comment]
The fix can be copied to 1.10.x
