### ISSUE TITLE
Invalid object name '[Prefix]_Locations_LocationsPartRecord'. Statement(s) could not be prepared.

### ISSUE THREAD

**Issue by kcastro18** [OrchardCMS/Orchard#7933]
I'm new with orchard. I am trying to create a module by following the instructions on the documentation but I get stuck on the second part of the tutorial (http://docs.orchardproject.net/en/latest/Documentation/Getting-Started-with-Modules-Part-2/). 

![image](https://user-images.githubusercontent.com/15161975/34678641-5c47f200-f459-11e7-80e0-30cd6a2be030.png)

I get this error when I try to configure the widget from the Dashboard UI.

Please help.

**Comment by sebastienros** [comment]
Do you have a migration that creates the `LocationsPartRecord` table?

Do you have an idea why the statement is being prepared? Is that some configuration you defined in the connection string?

**Comment by kcastro18** [comment]
Yes I have a migration that creates the LocationsPartRecord table but it seems like it's not creating the table, hence, the error.

I have no idea why the statement is being prepared.

**Comment by sebastienros** [comment]
Can you share you code that creates this table?

**Comment by kcastro18** [comment]
I'm sorry but I don't have it anymore. I just downloaded a new copy of Orchard and started creating a new module from there and I didn't have problem creating table from migrations.

**Comment by sfmskywalker** [comment]
@sebastienros fixed it very recently :)
