### ISSUE TITLE
Problem with PostgreSQL

### ISSUE THREAD

**Issue by LegendORC** [OrchardCMS/Orchard#7942]
Hello,

I have some problem with `PostgreSQL` when i try to enable `Vandelay Meta` module.
There is no problem when i'm using `SqlCE`.

the error message is `ERROR: 42601: syntax error at or near "text"`

I have looked at this.
Look like the `Orchard` has generated sql command like this :

```
ALTER TABLE vandelay_industries_metarecord ALTER COLUMN description text
```

This is work on `SqlCE` but not `PostgreSQL`.
for `PostgreSQL` should be like this :

```
ALTER TABLE vandelay_industries_metarecord ALTER COLUMN description TYPE text
```

Thank you.

**Comment by sebastienros** [comment]
if `TYPE` needs to be injected then we need a new class like this one: https://github.com/OrchardCMS/Orchard/blob/e37eae4bcd4d88a8eec60999a3572d6f4f57ffe4/src/Orchard/Data/Migration/Interpreters/MySqlCommandInterpreter.cs

We might need to only override one method.
