### ISSUE TITLE
1503 Errors

### ISSUE THREAD

**Issue by IrishChieftain** [OrchardCMS/Orchard#7948]
Just downloaded Orchard, opened it in VS 2015 and tried to build the solution. Received 1503 errors!!
Your documentation would take a year to read. I usually complain about lack of documentation but this is something new.
Has to be the most over-engineered project I have ever come across. Moving on and trying to find something simple that works out of the box.

**Comment by sfmskywalker** [comment]
Did you try and open the solution from the web package (Orchard.Web.1.10.zip), or the source code package? Only the latter is intended to be built - the former is pre-compiled and will not build.

In any case, I hope you find a decent CMS that does work for you. Thanks for the feedback.

**Comment by IrishChieftain** [comment]
I wanted to get familiar with the code, which is why I downloaded the src version. Many references broken so I'm sure many of the errors were circular in nature. Took a look at MiniBlog (non Core version) but while simple, it's basically non-functional and I'm concerned about it being supported now that they have a Core version.

I'll give the compiled version a shot. Maybe you can look into the compile issues with the src version?

Also, looking through the documentation I see that different DB options are available. Is there also an XML option?

**Comment by sfmskywalker** [comment]
I'll have a look for sure, although I don't have VS2015 installed (I'm on VS2017). Meanwhile, did you check whether the nuget packages were restored successfully? VS should do this automatically, but I've seen this fail in VS2015.

Orchard uses NHibernate under the covers, so it potentially supports anything that NHibernate does. I don't think it supports XML as a datasource.

**Comment by IrishChieftain** [comment]
Thanks!
