### ISSUE TITLE
Adding module which control other modules behaviors 

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#7949]
i just got involved in orchard .
is it possible to  control a module from another module ? 
example of a modules which call an external API and display content .
say we have a number of modules with the same type (calling API and displaying data) . 
i want something just like the enabled button on the admin page . this is a bit different , i want my module to be called each time one of those modules was called and do  something . its like a middleware between the modules and the framework

**Comment by sfmskywalker** [comment]
>  i want my module to be called each time one of those modules was called and do some something

Can you be more specific with what you mean by "each time one of those modules was called"?
A module can expose services you can call and events that you can react to.
There are also framework events related to the shell to which your module can respond.

**Comment by ghost** [comment]
Hi thank you for your answer. 
what i meant by is , some users shouldn't use some of those modules, i can do that using the permissions on orchard but i'm getting the permissions of the current user from an external API so what i want more specifically is  whenever a user logged in and tried to use a module , the module i want to create will be **called first**  then if the permissions which is received from the external API is granted the module will pass through .

**Comment by ghost** [comment]
> There are also framework events related to the shell to which your module can respond.

this might be what i'm looking for , can you give an example or a doc about it please ?

**Comment by sfmskywalker** [comment]
Sure, checkout these event interfaces you can implement:

- https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Environment/IFeatureEventHandler.cs
- https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Environment/IWorkContextEvents.cs
- https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Environment/IOrchardShellEvents.cs

**Comment by sfmskywalker** [comment]
Perhaps the permissions checking event handlers are more interesting:

- https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard/Security/IAuthorizationServiceEventHandler.cs

**Comment by sfmskywalker** [comment]
The tricky part will be determining whether a user is "using a module". First of all, you would need to define what that means, specifically. Perhaps it could be as simple as the user accessing any controller exposed by a module. Your module would have to have a middleware or action filter that intercepts HTTP requests that provide you with that information. If you use an action filter, the route will contain the "area" which, if exists, contains the name of the module (Orchard modules are more or less MVC areas).

**Comment by ghost** [comment]
Thank you again for your reply . 
that's exactly what i was wondering , more specifically wondering is it possible to use a module without a controller exposed ? , since the module i want to create has no relation with the content displayed to the user or the admin . its a module which will have some logic .

**Comment by sfmskywalker** [comment]
You can "use a module" without it exposing a controller if that module for example exposes a service (e.g. `IUserService`). But in that case it's hard, if even possible, to intercept any and all calls made to any service exposed by any module in a generic fashion. Modules call services exposed from other modules directly by resolving them from the DI container. There is no intermediary mechanism into which you could hook.

**Comment by ghost** [comment]
> But in that case it's hard, if even possible

its not possible to wrap all services which i want to check in an interface say "IExposedService" and then make the service(module) looks only for IExposedServices ?

**Comment by sfmskywalker** [comment]
Not really, since that would require us as well as any other module developer out there to make sure they implement `IExposedService`. However, pretty much all services do implement `IDependency` as a means to automatically register the service with Autofac. Maybe Autofac provides a way to intercept service registration so that you can somehow decorate the service being registered. That decorator would then intercept any and all calls.

**Comment by sfmskywalker** [comment]
E.g. http://autofaccn.readthedocs.io/en/latest/advanced/interceptors.html

**Comment by ghost** [comment]
Thank You !
