### ISSUE TITLE
Azure always on, not using azure

### ISSUE THREAD

**Issue by donaldboulton** [OrchardCMS/Orchard#7952]
Been having hell with dynamic form and any form in my sites for a while since 1.10.0
Just now finding out why because you cannot turn off azure services. on local installs and on live servers dependencies are on azure and HtmlAgilityPack.dll is the fault. never turn on azure anything and get this in all install as dependencies.
`  <Dependency>
    <ModuleName>Orchard.Azure.MediaServices</ModuleName>
    <VirtualPath>~/Modules/Orchard.Azure.MediaServices/bin/Orchard.Azure.MediaServices.dll</VirtualPath>
    <LoaderName>PrecompiledExtensionLoader</LoaderName>
    <References>
      <Reference>
        <Name>HtmlAgilityPack</Name>
        <LoaderName>PrecompiledExtensionLoader</LoaderName>
        <VirtualPath>~/Modules/Orchard.Azure.MediaServices/bin/HtmlAgilityPack.dll</VirtualPath>
      </Reference>
      <Reference>
        <Name>Microsoft.Azure.KeyVault.Core</Name>
        <LoaderName>PrecompiledExtensionLoader</LoaderName>
        <VirtualPath>~/Modules/Orchard.Azure/bin/Microsoft.Azure.KeyVault.Core.dll</VirtualPath>
      </Reference>
      <Reference>`
I use a hosting company that has a installer or by ftp because azure is running rewriting over some .dll's cannot be done as they are running and these .dll's are only in azure and not needed if you are not needing azure.
Cannot ftp over these .dlls nor can the hosting companies installer because they should not be running. Especially in a no Azure environment.
How can I keep Orchard from automatically turning on Azure????????

**Comment by sebastienros** [comment]
I can read words, but no sentence makes any sense here, and I really don't understand what your issue is.
Would you mind rephrasing the issue?

Or does anyone else understand this issue?

**Comment by donaldboulton** [comment]
Azure always on HtmlAgilityPack.dll  always running in a none Azure environment.
