### ISSUE TITLE
Orchard Gallery FeedService reports Web App is Stopped

### ISSUE THREAD

**Issue by gbelmont22** [OrchardCMS/Orchard#7955]
Unless this has changed, the latest URL for the Orchard Gallery Feed Service should be:

https://orchardgallery.azurewebsites.net/api/FeedService

Attempting to browse the Gallery from within Orchard fails.  Visiting the URL directly reports: Error 403 - This web app is stopped.

I suspect the WebApp in Azure needs to be restarted.

**Comment by sebastienros** [comment]
I stopped the app since I migrated to a different subscription. Can you use
gallery.orchardproject.net which is the official URL? Was the other URL
predefined with your setup? Then which version are you using?

**Comment by gbelmont22** [comment]
Thank you.  I was indeed using the wrong URL.  My feed URL was out of date, and I found the URL I was using in a post on Slashdot.  Apparently, that post wasn't accurate.

I am now using:  https://gallery.orchardproject.net/api/FeedService   which appears to work fine.

Thanks again!
