### ISSUE TITLE
Condition for user approved

### ISSUE THREAD

**Issue by MatteoPiovanelli** [OrchardCMS/Orchard#7956]
https://github.com/OrchardCMS/Orchard/blob/aa969534a8b936acc15934882552b1e4606fffdc/src/Orchard.Web/Modules/Orchard.Users/Services/MembershipService.cs#L99

I think that is missing 
`&& user.EmailStatus == UserStatus.Approved`

Note also that in the `ValidateUser` method down the same class both conditions are checked to declare a user valid.

Am I missing something?

**Comment by sebastienros** [comment]
Only if there is no option that email validation is mandatory. I don't remember.

**Comment by MatteoPiovanelli** [comment]
Email validation has its own setting separate from user moderation.
A few lines above my proposed change:
```
if ( registrationSettings != null ) {
    user.RegistrationStatus = registrationSettings.UsersAreModerated ? UserStatus.Pending : UserStatus.Approved;
    user.EmailStatus = registrationSettings.UsersMustValidateEmail ? UserStatus.Pending : UserStatus.Approved;
}
```

I understand that may be we want to keep the concept of "Approved" user separate from "Valid" user, since there is a separate `ConfirmedEmail` event. Given that, I am not sure it is correct to implement the change I propose here.
