### ISSUE TITLE
Anyone know where ProcessFullWeight is or how to access it?

### ISSUE THREAD

**Issue by WhittenMike807** [OrchardCMS/Orchard#7961]
I have inharited this project, and i'm not sure how to access:
_taxonomyService.ProcessFullWeight(term, parent);

I'm pretty sure it's part of the Orchard.Taxonomy.dll, but it says it's not a method.

Any thoughts?

**Comment by Hazzamanic** [comment]
Hey, 

This method was added in commit https://github.com/OrchardCMS/Orchard/commit/fca9bb41af894d530308760689143aaae7da55bb, and is part of the dev branch and can be found on [line 384](https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.Taxonomies/Services/TaxonomyService.cs#L384) of the TaxonomyService.

This kind of question is usually better asked on [Stackoverflow](https://stackoverflow.com/tags/orchardcms) or the Orchard gitter channel. You'll get more prompt replies over there
