### ISSUE TITLE
Injecting Menu to the Navigation shape

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#7962]
as i couldn't find any results on the documentation provided . 
is there any way to inject menu items to the navigation ? 

I have module which contains some services i want once the modules is activated to inject some menus dynamically to the navigation And assigned it to a specific Content Item. 

any help is appreciated .

**Comment by MatteoPiovanelli** [comment]
Assuming you are talking about navigation in the back office, the most straightforward way to it I think is through `INavigationProvider` implementations. I just opened a module at random (it's Orchard.Taxonomies) and found one.

I am not sure what you mean when you say "assigned it to a specific Content Item".

I think the "Show on a Menu" flag you see in the editor of some content items (e.g. in Page content items), and that is the view of their MenuPart is to show a link to those items in Front end menus.
