### ISSUE TITLE
Get content Item by UserId

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#7964]
Is there any way to get a content Item by UserId instead of Content Id ? 
`context.Content = _ContentManager.Get(0);`
I'm making a web project where the Administrators will be able to create a content item for specific new user . so i want that the user sees only the content specified by the administrator . 

the way i'm going is : 
-The administrator set the owner of the content item to the targeted user . 
-using `IAuthorizationServiceEventHandler`  i specify the content using the current userId 

is there anyway to get the content by userId ? or is there any other good way to go ?

**Comment by Hazzamanic** [comment]
If you want to get all content items with a specific owner you can do:

```
var userId = ...; //
_contentManager.Query(VersionOptions.Published)
  .Where<CommonPartRecord>(cr => cr.OwnerId == userId)
  .List();
```


This kind of question is usually better asked on [Stackoverflow](https://stackoverflow.com/tags/orchardcms) or the Orchard gitter channel. You'll get more prompt replies there.

**Comment by ghost** [comment]
@Hazzamanic  the content i want to render which include Navigation etc ..  (which is retrieved by userId) how can i set it as the default one to render dynamically ?
