### ISSUE TITLE
Running PHP under Orchard

### ISSUE THREAD

**Issue by LegendORC** [OrchardCMS/Orchard#7966]
Hello,

I have a question about "How can i run PHP under the Orchard folder ?"
I created a site and test PHP script like `<?php phpinfo(); ?>` and it's work.
But when i created PHP file in `Orchard` folder. it's not found.
in the `web.config` file i added
`<add name="FastCgi" path="*.php" verb="*" modules="FastCgiModule" scriptProcessor="C:\Program Files (x86)\PHP\v5.3\php-cgi.exe" resourceType="Either" requireAccess="Read" preCondition="integratedMode" />`
and doesn't help.

Actually, I can run a static file under `Orchard` with `web.config`

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <httpRedirect enabled="false" />
    <validation validateIntegratedModeConfiguration="false" />
    <handlers>
      <clear />
	  <add name="StaticFile" path="*" verb="*" modules="StaticFileModule" resourceType="Either" />
	</handlers>
  </system.webServer>
</configuration>
```

Do you have any idea ?

Thank you

**Comment by ghost** [comment]
did you tried creating a route for it ?
