### ISSUE TITLE
Orchard Dependecy Iservice<T> 

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#7968]
I'm implementing an interface `IService<T> : IDependency` to a class `Service<T> : IService<T> Where T : class, new()`

but this for some reason stops orchard and throws the following exception : 

`The type 'Service`1[T]' is not assignable to service 'IService`1'.`

any help ? 

thanks

**Comment by sfmskywalker** [comment]
I don't see anything wrong. As a test, are you at least able to instantiate a new `Service<T>` manually (e.g. from a controller) and assign it to another variable typed as `IService<T>`?

**Comment by ghost** [comment]
@sfmskywalker  yes . i don't understand when i move the generic type from the class level to the method level : 

```
 public Interface IService : IDependency
 {
  T Execute<T>();
 }
```
it works .

**Comment by sfmskywalker** [comment]
Perhaps service registration via `IDependency` doesn't support generics. Have a look at how `IRepository<T>` is registered, and mimic that approach.
