### ISSUE TITLE
The assembly reference 'ClaySharp' could not be loaded for module 'Orchard.DesignerTools'. 

### ISSUE THREAD

**Issue by donavanmarais** [OrchardCMS/Orchard#7969]
Fresh install of Orchard v.1.10.0.0.
Installed Designer Tools and activated Shape Tracing.
Error is encountered:

The assembly reference 'ClaySharp' could not be loaded for module 'Orchard.DesignerTools'. 

There are generally a few ways to solve this issue: 
1. Install any dependent module. 
2. Remove the assembly reference from the project file if it's not needed. 
3. Ensure the assembly reference is present in the 'bin' directory of the module. 
4. Ensure the assembly reference is present in the 'bin' directory of the application. 
5. Specify the strong name of the assembly (name, version, culture, publickey) if the assembly is present in the GAC.

**Comment by sebastienros** [comment]
This is a good one, we have removed this assembly and any reference to it 4 years ago. If you find any reference to it, even a string that would prove that we didn't completely get rid of it.

**Comment by sebastienros** [comment]
I did a quick search on Github and nothing appears when I search for `ClaySharp`. Can you check for old files on your side? Maybe you are using an old DesignerTools version. Or are you actually taking it from the gallery? (which you should not in this case)

**Comment by donavanmarais** [comment]
I did a search and wasn't able to find any reference to ClaySharp
