### ISSUE TITLE
Display Templates for Elements . 

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#7974]
what i couldn't find . is how can i change the template responsible for Displaying Element in the front ? 
which in default under (Elements/myelement.cshtml) . 

Scenario : say i have different element templates (myelement_1.cshtml, myelement_2.cshtml) .I want the adminisitrator to choose which template should be used to render the element on the Editor Element Shape : 

```
protected override EditorResult OnBuildEditor(AccountElement element, ElementEditorContext context)
        {
            return base.OnBuildEditor(element, context);
        }
```
any help ? 

thanks!

**Comment by sfmskywalker** [comment]
Do you mean that the administrator should be able to select which element template to use for rendering on the front-end?

**Comment by ghost** [comment]
Exactly
