### ISSUE TITLE
Activating Theme Dynamically 

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#7975]
We have a multi-tenancy Orchard application . 
when selecting a themes  for a tenant , we'd like to activate a default one automatically . 
is it possible to activate an Orchard theme  dynamically ? 

thanks

**Comment by ghost** [comment]
was too slow to discover about `ISiteThemeService` service :)

**Comment by ghost** [comment]
When activating the template i got almost no styles on it ? 

is this a bug or i'm missing something ?

**Comment by sebastienros** [comment]
You are missing something.

Please provide more information about what you want to achieve and how you are currently doing it. You can also try the gitter forum for help before filing an issue.
