### ISSUE TITLE
Orchard Repository from another DB (EDITED) 

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#7986]
I have another DB separated from the `OrchardDB` , how can i use orchard repositories using that DB ?

**Comment by ghost** [comment]
what i wanted more specifically is make orchard work with two Nhibernate configurations . the standard one which orchard works with . and my custom configuration (with my db and my mappings ...) .

is it possible to make it work within the same Orchard data , without having to work with another nhibernate instance (if even possible )

**Comment by sebastienros** [comment]
Not that I know of.
