### ISSUE TITLE
Working with Orchard Dynamic Forms

### ISSUE THREAD

**Issue by muniran** [OrchardCMS/Orchard#7997]
Hi,

We are working with Orchard CMS 1.10.2 version.
While using Dynamic forms we are unable to find out how to use Media Selector for Image.

Could someone help us regarding the same.

**Comment by sfmskywalker** [comment]
Unfortunately there's no media picker element. Media Picker is designed for use from the back-end only. This means you will have to implement a media picker yourself. This would involve a custom module that has a custom controller to present a media picker (either copied from Orchard or created by you from scratch), and a custom element that renders a picker button (which then launches the custom media picker).
