### ISSUE TITLE
Fetch Data from Table

### ISSUE THREAD

**Issue by stelmar** [OrchardCMS/Orchard#8001]
Hello,

I am new to orchard. We have created a table in orchard database and need to bind the data to a dropdown. 

How can i work around with this?

**Comment by ghost** [comment]
did you create the table using Orchard Migrations ?

**Comment by stelmar** [comment]
No. I directly created the table

**Comment by ghost** [comment]
You should take a look at [Data Access](http://docs.orchardproject.net/en/latest/Documentation/Understanding-data-access/)

**Comment by stelmar** [comment]
Thanks for the reply. I looked at the URL you provided and created the table using data migration. Added data in the table. Now I want to bind the table data to drop down. Can you help me with this?

**Comment by sebastienros** [comment]
Closing as this question is not related to Orchard  but to general programming in MVC.
