### ISSUE TITLE
Create Table with Byte[] Property 

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#8002]
I'm trying to create a model which contains a byte[] property to save a file bytes . 

```
public class FileModel 
{
 public Virtual int Id { get; set; }
 public Virtual Byte[] fileBytes { get; set; }
}
```
using Migration : 

```
        public int Create()
        {
            this.SchemaBuilder.CreateTable(typeof(FileModel).Name, (Builder) =>
            {
                Builder.Column<int>("Id", c => c.Identity().PrimaryKey());
                Builder.Column<byte[]>("fileBytes");
            });

            return 1;
        }
```

but this does not seems to be working it throws invalid Db type 

any help ?

**Comment by mdameer** [comment]
I think you can define the byte array column as `Builder.Column("fileBytes", DbType.Binary)`, please refer to this [link](https://www.tutorialspoint.com/nhibernate/nhibernate_data_types_mapping.htm) for more information about "NHibernate - Data Types Mapping"

**Comment by sebastienros** [comment]
thanks @mdameer , we should probably handle it directly in the `SchemaBuilder` code like we do for other types.

**Comment by mdameer** [comment]
You are right @sebastienros, so we can handle it with adding new condition to `SchemaUtils.ToDbType` method like following:
```csharp
if(type == typeof(Guid))
    dbType = DbType.Guid;
else if (type == typeof(byte[]))
    dbType = DbType.Binary;
```
If you agree with this solution, I can make the PR for it.

**Comment by sebastienros** [comment]
I agree, plus some unit test obviously
