### ISSUE TITLE
User logout affects all clients

### ISSUE THREAD

**Issue by MatteoPiovanelli** [OrchardCMS/Orchard#8003]
https://github.com/OrchardCMS/Orchard/blob/1.10.x/src/Orchard.Web/Modules/Orchard.Users/Services/MembershipValidationService.cs

The `CanAuthenticateWithCookie(IUser user)` method of the service linked above is used in `FormsAuthenticationService` to validate the user from the authentication cookie received in the current request being processed.

The code there is such that the following happens:

 - Open two different browsers to the same tenant. The browsers must not share cookies.
 - Be logged in in both browsers.
 - Logout from one browser.
 - The user is not "logged out" from the other browser as well.

This happens for any client, not just browsers, and I reckon that's a rather jarring UX.

While I think there should be a way for a user to "invalidate" all their outstanding authentication cookies, I don't think this should be how it's done.

I would like to hear what everyone thinks about this, and reach a consenus on how this should be done.

**Comment by sebastienros** [comment]
I don't understand what is the issue you are trying to solve. 

> The user is not "logged out" from the other browser as well.

Do you actually expect that it logs out by itself on the client without any user interaction? Do we agree that the next request won't be authenticated, with the current code?

**Comment by MatteoPiovanelli** [comment]
I agree. The issue I see is exactly that the next call by that user will not be authenticated, no matter what client it is coming from

**Comment by MatteoPiovanelli** [comment]
Just realised there was a typo in my original post that changed the meaning completely.

> The user is not "logged out"

should actually be

> The user is now "logged out"

**Comment by sebastienros** [comment]
Ok, so isn't it you who implemented this feature? I think I remember there was a PR to add this behavior.

**Comment by MatteoPiovanelli** [comment]
No. This service has been there for a while. My pr was to add custom information to invalidate the auth cookie.

**Comment by sebastienros** [comment]
I would recommend to use a hostenvironment parameter to disable this feature.
