### ISSUE TITLE
Add Excel Export functionality to DynamicForms

### ISSUE THREAD

**Issue by TFleury** [OrchardCMS/Orchard#8012]
Dynamic Forms lacks a submissions export feature.

I achieved it locally with OpenXml and it exports submissions in an xlsx spreadsheet.
[here is the diff](https://github.com/Codinlab/Orchard/commit/fbe7f75d744d5241925ae656fd19cd0e9d18c346)

Is the community interested by a PR for that ?

**Comment by sebastienros** [comment]
Go for it.

**Comment by pgy866** [comment]
Thank you very much. Can add import excel data at the same time? I once submitted in orchard core! But the core version does not have this plan!
非常感谢，可以同时实现excel数据导入吗？我曾在orchard core中提交！但core版本没有此相计划！

**Comment by TFleury** [comment]
I don't see any use case of importing submissions from an external source, and importing is much more complicated then exporting.
It could be ported to Orchard Core when DynamicForm will be ready.

**Comment by sfmskywalker** [comment]
I actually do see a use case for importing from an eternal source, but perhaps the Recipes feature is good enough. You would have to generate a recipe from an Excel file of course. Not sure if that part should be part of the core distribution. At the same time, if Excel export is supported, why not also import? I think they should either both be part of it, or none.

**Comment by pgy866** [comment]
I'm sorry, I don't program, I'm the user. Thank you very much for sharing. EXCEL dynamic forms are a very good thing if they are everywhere. Try to use simple OA system such as contact form, customer profile information, etc. , very good, expecting

`非常抱歉，我并不会编程，我是使用者，非常感谢所有共享，EXCEL 动态表单若能到处是一个非常好的东西，在尝试用于简单的OA系统中比如联系表单、客户资料信息、等，非常好，期待`

**Comment by HengzheLi** [comment]
@pgy866   https://github.com/salween/ToolsConvert   这是一个orchard xml和csv格式互转的工具  你可以试试看能不能满足你的要求

This is a tool for inter-transforming between xml and csv. You can hava a try if it meet your requirement.

**Comment by pgy866** [comment]
@li0803 
非常感谢您！发现这么美好的一个开箱即用的工具！可以我的一些需求！

Thank you very much! Discover such a wonderful tool out of the box! Can some of my needs!

**Comment by pgy866** [comment]
@TFleury
@TFleury If, for development functions, it is recommended to generate an EXCEL fixed template corresponding to the imported ORCHARD through a dynamic form and then import the data. PS: I don't know how to program. I don't know whether it can be implemented. I just saw it on other projects.
`如果，开发功能，建议：通过动态表单生成一个对应导入ORCHARD的EXCEL固定模板，然后在导入数据。PS: 并不会编程的我，不知道是否可以实现，只是在其它项目看到过，是这种方式实现`

**Comment by BenedekFarkas** [comment]
Fixed by #8012.
