### ISSUE TITLE
How to work with the UserTask Activity in workflows ?

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#8015]
can someone please explain how to work with the UserTask Activity in Orchard ?

**Comment by sebastienros** [comment]
There are some videos online from previous Orchard Harvest conferences.

The idea is that such a task will let you add custom buttons to the Edit screens, that the user can click to advance the workflow. Like "Approve". You can also generate links in emails that will have the same effect.

**Comment by ghost** [comment]
@sebastienros thanks for your reply ! .
can you give a link to a conference which discuss how to generate links with that effects actions ?

**Comment by sebastienros** [comment]
No idea, start with that: https://www.youtube.com/results?search_query=orchard+workflow

@sfmskywalker any idea?

**Comment by sfmskywalker** [comment]
No idea, but I'll record a quick screencast.

**Comment by sfmskywalker** [comment]
* User Task Activity in action: https://www.youtube.com/watch?v=iioKQkXUwXA
* Signal activity, Send Email activity and TriggerUrl token in action: https://www.youtube.com/watch?v=M57Dp0O3ttI
