### ISSUE TITLE
Why non English character can not be used as taxonomy name

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/Orchard#8017]
I created a taxonomy using a Chinese word. But when CreateTermContentType for this taxonomy, the name of it will be ToSafeName(). 

```
public string GenerateTermTypeName(string taxonomyName) {
            var name = taxonomyName.ToSafeName() + "Term";
            int i = 2;
            while (_contentDefinitionManager.GetTypeDefinition(name) != null) {
                name = taxonomyName.ToSafeName() + i++;
            }

            return name;
        }
```

After this operation, the non English character and non digital character will be removed, then the name become empty. This will causes #7893. 

However, the taxonomy can be created successfully as well as the Term content type for this taxonomy. The only problem is that when create a new term for the Term content type, the edit page is empty.

repro step:
1: Create a taxonomy with non English character and non digital character.
2: Create a new term for this taxonomy
3: Editing page is empty.

**Comment by sebastienros** [comment]
Because they are used for technical names. You can use any character in the display name.
