### ISSUE TITLE
Change culture code to respective culture name

### ISSUE THREAD

**Issue by stelmar** [OrchardCMS/Orchard#8023]
Hello Team,

In the localization part instead culture code(en-US or es-ES), we want to display culture name(English (United States)) as displayed in the attached screenshot.
![screenshot_culture](https://user-images.githubusercontent.com/36508171/38684380-353fb3ea-3e8d-11e8-86b5-480119893102.png)

Please let us know how to achieve the same.

**Comment by sebastienros** [comment]
Do you know which template is creating the drop down? If it's a shape you could just copy it in your module and customize it. If it's not a shape then it should be one.

**Comment by BenedekFarkas** [comment]
The AdminCultureSelector in the Localization module indeed shows the culture code (I just changed that to show the display name in b03d83473fbcb75f97cea195c8bb699d34bee7d0), but the TheAdmin theme overrides that shape and displays the cultures' display names.
