### ISSUE TITLE
Can PR #6839 re-submit to apply #6838

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/Orchard#8026]
Hi @sfmskywalker,

Seems that PR #6839 was closed before it was merged. Can this PR re-submit as I am using it in my project and it looks working well? If you are busing on other work. I may submit it from my side. 

Thanks

**Comment by sfmskywalker** [comment]
Yeah you're right, not sure how that happened but I reopened the PR.

**Comment by sfmskywalker** [comment]
Actually, reading the thread on the referenced issue, it turns out we decided this PR wasn't necessary. However feel free to make your case as to why you think it is necessary after all here: #6839
