### ISSUE TITLE
unknow loop in RolesBasedAuthorizationService.cs

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/Orchard#8027]
in line 46, there is a loop line:
`for (var adjustmentLimiter = 0; adjustmentLimiter != 3; ++adjustmentLimiter) {`
But the variable **adjustmentLimiter** never been used in this loop. And seems that it does the same thing in very loop.

Can someone provide some clues about the mysterious number **3** and why it does the same thing for 3 times?

**Comment by sebastienros** [comment]
It's calling some authorization handlers that can change the permission to check. If the permission to check is changed too many times (3 times) then we stop as it could mean there is an issue in the logic.
