### ISSUE TITLE
Non-creatable contents are actually still creatable

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#8030]
Despite their setting (creatable is set to false), non-creatable contents are wrongly still creatable.
From what I can see, I found 4 cases:
1. Accessing directly the `Create Action`
2. Accessing directly the `Clone Action`
3. Filtering in the `SummaryAdmin` for a non-creatable content the create button still permit to create that `ContentType`
4. In the SummaryAdmin the `Clone ActionLInk` is there and permit to clone the content.

I think this is an inconrrect behaviour: a non-creatable content should neither be creatable nor clonable.
The only doubt is for translations: should we permit to translate a non-creatable content? I think yes, because it is a translation not a real new creation...

**Comment by sebastienros** [comment]
This is just to hide it from the New menu section.

**Comment by HermesSbicego-Laser** [comment]
Yes, you are right, by now is the only effect and that is the point. But my suggestion was to have a coherent option (I would like not a different one, since a setting exists) even if more restrictive.

**Comment by sebastienros** [comment]
You can use permissions, as they are also checked before rendering the links to create items. We do that with content permission. Have you tried to remove the permission from a role, that should work?

**Comment by HermesSbicego-Laser** [comment]
That was an option we considered but there is no a "create content" permission.
I see three ways to achieve the feature.
1. To use the "creatable" settings in order to hide create button in contents list and hide clone link in summaryadmin, as well in the "new" menu. We can keep routes actives (as is, without any check against the setting) for backward compliance.
2. Add a new permission for each securable content named "create new content". And check over that permission where we need it.
3. Both.

I think these can be 2 useful features in some business context...

We can start working suddenly on point 1, if you agree. Then point 2, later.

**Comment by sebastienros** [comment]
The effect of Creatable should not be changed.

Instead you should ensure that the ways to create items, as states in your first comment, should be secured by ensure the permissions are correctly enforced.

**Comment by HermesSbicego-Laser** [comment]
Although I cannot imagine why the effect of Creatable should not be changed, we will work on a solution providing a new permission `Create new content`: we will provide that permission for all securable contents, as per the `edit content` permission. If a role has the `Create new content` permission will also have the `edit own` permission too, otherwise after the first save the user will see an Unauthorized exception.

**Comment by sebastienros** [comment]
Ok for a new Create permission
