### ISSUE TITLE
Override Module Elements

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#8032]
I'm trying to override some Elements from DynamicForms Module .

But still orchard don't pick up My Elements from the theme on /Views/Elements Folder 

any help ?

**Comment by sfmskywalker** [comment]
Can you show us what you did exactly?

**Comment by ghost** [comment]
@sfmskywalker lets take the example of `Forms.cshtml` on `DynamicForms/Views/Elements/Forms.cshtml`
i tried to make the same route on my theme/Elements/Forms.cshtml 

but Orchard didn't pick it up .

**Comment by sfmskywalker** [comment]
I tried and it just works. Perhaps you can do a short screencast and show us exactly what you're doing?

**Comment by ghost** [comment]
I don't know but it worked after a clean rebuild
