### ISSUE TITLE
Assigning a LocalizedString to an HTML attribute could cause rendering issues

### ISSUE THREAD

**Issue by Jarre10** [OrchardCMS/Orchard#8033]
An example in Razor would be:
`<input class="btn btn-primary full-width" type="submit" value='@T("Register")'/>`
Translating Register in French would yield S'enregistrer.
Once the page gets rendered, you'll see a submit button with just an 'S' in the button text.
The HTML that ultimately got rendered on the page is:
`<input class="btn btn-primary full-width" type="submit" value="S" 'enregistrer'="">`

I noticed some of the code in Orchard does this, a few examples being in Orchard.Users\Views\Admin\Index.cshtml:
`                    @if (entry.User.RegistrationStatus == UserStatus.Approved && entry.User.EmailStatus == UserStatus.Approved) { 
                    <img class="icon" src="@Href("~/Modules/Orchard.Users/Content/Admin/images/online.gif") " alt="@T("Approved") " title="@T("User is approved") " /> 
                    } else { 
                    <img class="icon" src="@Href("~/Modules/Orchard.Users/Content/Admin/images/offline.gif") " alt="@T("Moderated") " title="@if (entry.User.EmailStatus == UserStatus.Approved) { @T("User is moderated") } else { @T("E-mail validation is pending") }" />
                    } `

If you do a regex search on "=("|')@T" you can find more spots. 

The reason there's no HTML encoding in these cases is likely due to the fact that, ultimately, a IHtmlString is what is getting rendered.
https://msdn.microsoft.com/en-us/library/system.web.ihtmlstring(v=vs.110).aspx
"Represents an HTML-encoded string that should not be encoded again."

**Comment by Skrypt** [comment]
Not `value='@T("Register")' ` but `value="@T("Register")"`. That's a HTML integration error. HTML parameter values should never be encapsulated with 'something'.

**Comment by Jarre10** [comment]
Ah. Thanks for that catch!
