### ISSUE TITLE
OnUpdating<TPart>not firing

### ISSUE THREAD

**Issue by mehranrezaei** [OrchardCMS/Orchard#8035]
I have a ContentPart with a ContentPartHandler. I defined OnUpdating event handler for this part.
Now when I get this part for a content item in code using ContentManager and modify it, OnUpdating event handler does not execute. It runs when I modify part in driver.

Is this by design or I am wrong?
How I can make content part events firing when I update part from code?

**Comment by MatteoPiovanelli** [comment]
Hi, this is by design. Those events are fired as part of a "chain" of events. See in Orchard.Core.Contents.Controllers.AdminController. You would be looking for the EditPOST method.

To replicate firing all the events, I think you should be calling ContentManager.UpdateEditor(), but that requires you to pass an IUpdateModel instance.

**Comment by armanforghani** [comment]
@mehranrezaei As @MatteoPiovanelli-Laser mentioned above you should call ```UpdateEditor``` method to fire  those events. You can implement ```IUpdateModel``` interface in your controller and pass the controller instance itself as an updater.
I recommend to follow all references of ```UpdateEditor``` in source code to find its usages.

**Comment by mehranrezaei** [comment]
@MatteoPiovanelli-Laser
@armanforghani 
Thanks all you guys.

**Comment by mehranrezaei** [comment]
@MatteoPiovanelli-Laser
@armanforghani

I have a new problem. Please help.

I defined a simple internal field in my content part as the following:
```internal decimal PreviousPrice;```

I set this field in OnLoaded event handler:
```
    OnLoaded<CustomPart>((context, part) => {
        part.PreviousPrice = part.Price;
    });
```

The problem is the part has not this value when it passed in EditorPost method of its driver.
Why the different instance of content part has been passed to the driver method?
I don't understand.

**Comment by MatteoPiovanelli** [comment]
Looking through `DefaultContentManager.Get(int, VersionOptions, QueryHints)`  you'll find that the `Loaded` handlers are only invoked in some conditions. My guess is that when you are going through the POST Editor method the item is being returned from session, so it does not go through those events.
