### ISSUE TITLE
Prevent versioning for non-draftable items

### ISSUE THREAD

**Issue by armanforghani** [OrchardCMS/Orchard#8036]
I created a new content type that is not draftable.
But when i edit its content item using the default content management UI (```Admin/Contents/Edit/ID```) a new version of item will be created for each edition.
 
I think this is because of the following line in ```EditPOST``` method of ```Orchard.Core.Contents.Controllers.AdminController```.

```var contentItem = _contentManager.Get(id, VersionOptions.DraftRequired);```

Why this method requires draft version for a non-draftable item?

**Comment by sebastienros** [comment]
Not draftable means there is no draft, just a published version, but historical version are still kept.
We added a different option in Orchard Core to handle this independently. You could port the code back to O1 if you need it?

**Comment by armanforghani** [comment]
@sebastienros Thank you for your reply. I will check the new option in Orchard Core.
