### ISSUE TITLE
Query could not filter content items based on contentpicker field

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/Orchard#8037]
1. Append a contentpicker field file to a contenttype, set the 
2. Create a contentitem of this type and assigne a content to that contentpicker field. let's say the id of content assigned to contentpicker is 10
3. Create a query and use the contentpicker field filter as the query filters. And set the filter value is 10
4. Preview this query. The query returned no results. It should return the content item which of contentpicker field's ids value is 10

**Comment by li0803** [comment]
seems like that the QueryElement used query's id as foreign reference in exported recipe:
```
"elements": [
                        {
                          "typeName": "Orchard.DynamicForms.Elements.Query",
                          "data": "FormBindingContentType=BankEntity&InputName=BankName&OptionLabel=&QueryId=78&TextExpression=%7bContent.DisplayText%7d&ValueExpression=%7bContent.Id%7d&DefaultValue=&InputType=SelectList&Required=false&CustomValidationMessage=&ShowValidationMessage=false&Name=&Alternate=",
                          "exportableData": "",
                          "index": 0,
                          "elements": [],
                          "isTemplated": false,
                          "htmlId": "",
                          "htmlClass": "",
                          "htmlStyle": "",
                          "rule": ""
                        }
                      ],
```

According to the usage of IdentityPart, I think it may use Identity instead of the DB id's value.
