### ISSUE TITLE
Asynchronicity for Orchard v.1

### ISSUE THREAD

**Issue by ActivePHOENiX** [OrchardCMS/Orchard#8043]
As we know Orchard Core operations and requests are mostly designed in async mode, my question is,  is there any possibility to port that kind of achievement to O1 or custom modules themselves should implement the async/await model internally rather than having Orchard core modules support the approach?

**Comment by sebastienros** [comment]
That would be a huge breaking change and would not provide all the expected benefits. At that point people would be better off moving to Orchard Core if performance is the main reason.

**Comment by ActivePHOENiX** [comment]
@sebastienros  Yes exactly I was thinking about performance, thank you for the response and direction, our team would plan to migrate to Orchard Core as soon as possible. Hats off to you.
