### ISSUE TITLE
YesSql support for Orchard v.1

### ISSUE THREAD

**Issue by ActivePHOENiX** [OrchardCMS/Orchard#8044]
Is there any plan to port YesSql feature and capability to orchard v.1? If we want to get rid of CommonRecord altogether what would you suggest about the right way to do it .
We have reached to a conclusion that join queries accrued by CommonRecord can degrade the query performance and not adding reference to CommonRecord while defining the table in migration class can help , as CommonRecord is part of the core, what would be the risk of removing it and taking the Orchard.Core approach distributing its properties among module models themselves ? although it would be repetitive BTW.

**Comment by ghost** [comment]
the common part should always exist in the content types cause it gives informations about the type such as the versionning informations and owner etc ... unless you have a way to implements those informations which is not recommended cause orchard always look for the "commonpart" so even if you managed to implements those informations somewhere you ll have to change orchard to look for the something you added .

**Comment by sebastienros** [comment]
I did the conversion 5 years ago, and it was able to go through Setup, but at that point it would be less effort to migrate to OrchardCore than migrating an app on Orchard1 to this new model if that was implemented. So I don't think anyone should even try to do it.

**Comment by ActivePHOENiX** [comment]
@sebastienros Thank you for your direction and leadership, now I need to change and correct my point of view.
