### ISSUE TITLE
Orchard Search Doesnt show any results ,

### ISSUE THREAD

**Issue by rezarouf** [OrchardCMS/Orchard#8063]
I have turned on Lucene,Indexing,Search. Created Index,Added page to Index,set search parameters but still it only shows the Word SEARCH on the results screen
![image](https://user-images.githubusercontent.com/39696836/40610634-d6d5edc4-6290-11e8-94fe-031f539008ac.png)
![image](https://user-images.githubusercontent.com/39696836/40610649-e3a638d8-6290-11e8-93d1-90227ba6f20f.png)
any idea or help is appreciated. thank you!

**Comment by sebastienros** [comment]
You need to configure which content types are indexed, then ensure that the index is up to date.
