### ISSUE TITLE
Email Validation pattern fails

### ISSUE THREAD

**Issue by Vaclav-Volek** [OrchardCMS/Orchard#8066]
Hi,
in Orchard.DynamicForms.ValidationRules.EmailAddress is validation pattern:
`Pattern = @"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$";`

Validation of email fails for domains that have more than 4 characters after dot. This limitation is little bit crazy. It fails for example for domains: xxx.network, xxx.academy, xxx.accountants, .....

Could you please fixit. 

Thank you very much :)

**Comment by sebastienros** [comment]
At the time we wrote it there were not such domains, but now it's totally valid, correct.

Have you thought about creating a PR and updating the unit tests, that would expedite the process.

**Comment by sebastienros** [comment]
Quick notes:
- This pattern is used in many places, so we need to search for it everywhere.
- This is the official TLD list: http://data.iana.org/TLD/tlds-alpha-by-domain.txt, the longest is 24 chars right now but the specification states it can be up to 63 chars, so we need to change the regexp to 

"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
