### ISSUE TITLE
Cannot Hide custom modules from dashboard admin panel

### ISSUE THREAD

**Issue by rezarouf** [OrchardCMS/Orchard#8072]
i have several roles, each role has some access, eg : superadmin can see all the modules , but HR can see only some modules ,so hiding of default modules is possible ,by giving permissions but custom modules is not getting hidden even if i set "manage" permission as disabled.
any help is appreciated 

@sebastienros 
@Piedone

**Comment by Piedone** [comment]
I'm not sure I understand, where exactly do you want those modules to get hidden? Their permissions under a role screen? Under Features? Else?

**Comment by rezarouf** [comment]
@Piedone thank you for replying , by hiding i meant hiding from the dashboard (that is the admin panel )
![image](https://user-images.githubusercontent.com/39696836/41535482-1c5d6116-7320-11e8-9a9a-16426d53a447.png) 
like you see here in the image , my custom modules are FileManager , Useful links,News etc i want to restrict certain admins from using them,so i want to hide them..its easily possible in default modules by just disabling their permission to access it .. i wanted to know why disabling permission is not hiding custom modules
Thankyou

**Comment by Piedone** [comment]
For this you need define your custom permissions and use them in your navigation providers. For an example see https://github.com/Lombiq/Orchard-Training-Demo-Module.

**Comment by rezarouf** [comment]
Thankyou for your help ,ill look at it right away!

**Comment by rezarouf** [comment]
Thanks The logic was to add the permission to access or not in Admin Menu Page,

**Comment by Piedone** [comment]
Great then!
