### ISSUE TITLE
Background task fired only once 

### ISSUE THREAD

**Issue by ghost** [OrchardCMS/Orchard#8074]
the background task is supposed to run every minute . but if a task did not complete yet the background task is never hit again . 

example: 

```
  public class MyBackgroundTask : IBackgroundTask
    {
        public void Sweep()
        {
            while (true)
            {
            }
        }
    }
```

each call of the sweep() Method should be in a separate thread unrelated to the previous execution .
but instead orchard always waits for the previous Sweep() to end .

**Comment by ghost** [comment]
does this have anything to do with the dependency injection scope ?

**Comment by sebastienros** [comment]
By design, we don't re-enter a background task that is already running, or this could cause issues if there is a bug in the modules, with an unlimited number of threads created and eventually put the site down.

**Comment by ghost** [comment]
@sebastienros  this indeed is a good design to go with, orchard will not re-enter the background task that's already running but will eventually wait for the thread to be available again? if so does orchard waits another minute or re-enter it immediately ?
