### ISSUE TITLE
Designer Tools Won't Work

### ISSUE THREAD

**Issue by a1Sandor** [OrchardCMS/Orchard#8076]
I have downloaded the designer tools from the external orchard gallery website. I installed it.
I am getting this error

> The assembly reference 'ClaySharp' could not be loaded for module 'Orchard.DesignerTools'. 

There are generally a few ways to solve this issue: 
1. Install any dependent module. 
2. Remove the assembly reference from the project file if it's not needed. 
3. Ensure the assembly reference is present in the 'bin' directory of the module. 
4. Ensure the assembly reference is present in the 'bin' directory of the application. 
5. Specify the strong name of the assembly (name, version, culture, publickey) if the assembly is present in the GAC.

I need to enable URL alternates but it wont work.
Any help is highly appreciated.

**Comment by sebastienros** [comment]
This module is deprecated, the designer tools are already shipped with Orchard.

**Comment by rjamesnw** [comment]
For those, like me, who followed old instructions (using Web Deploy) and installed the tools (and messed up the included module after uninstalling it), just simply download the .ZIP release, extract the `Modules\Orchard.DesignerTools` module and copy back to your website. ;) You're welcome.
