### ISSUE TITLE
FileNotFoundException occurs when viewing error log

### ISSUE THREAD

**Issue by jonbarthol** [OrchardCMS/Orchard#8097]
If an orchard-error log file does not yet exist and I switch the type from "Debug" to "Error" a System.IO.FileNotFoundException occurs:

![debug_log](https://user-images.githubusercontent.com/18033870/43862361-7542a6fe-9b27-11e8-87ba-0275ff89bef9.png)

Change "Type" to error:
![change_to_error](https://user-images.githubusercontent.com/18033870/43862664-497af66a-9b28-11e8-95ee-5b4267ca6a77.png)

Error occurs:
![debug_error](https://user-images.githubusercontent.com/18033870/43862677-50128b14-9b28-11e8-930f-8ff75a84f2a9.png)

**Comment by sebastienros** [comment]
Is that coming from an external module of something in this repos?

**Comment by jonbarthol** [comment]
Ah yes. My apologies. This is from the external Devq.ErrorLog module. Closing this issue.
