### ISSUE TITLE
Making the Contents Controller more general extending it with Some Contente Metadata permissions

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#8098]
Working on that fix #8092  I realize that we could abstract a bit more the logic for permissions in order to consent developers to use the same Contents/Edit controller/view instead of cloining it. As per Metadata.EditorRouteValues we could add to new propoerties to metadata with the permissions to check over Display/Edit/Delete/Publish actions and so on. So we could use the Contents Controller without copying/pasting the Controller Actions and Views. 
@sebastienros What about the suggestion?

**Comment by sebastienros** [comment]
I don't think that is necessary. Usually you will need to adapt the actions specifically to your items, and this is why you wan't to create custom ones, or you would just use the default ContentItem ones.
