### ISSUE TITLE
Upgrade from 1.7.1 to the latest

### ISSUE THREAD

**Issue by yaporyvaev** [OrchardCMS/Orchard#8102]
Hello !

We have an orchard 1.7.1 version. It's neccessary to upgrade to the latest version. The instruction says that first of all we should upgrade to 1.7.2 then 1.8.2 then 1.9.0 then to the latest, is it right ? Or it would be better for us to create new project with latest version of Orchard CMS and migrate our modules manually ? 

If it is neccessary to upgrade gradually, where can we find 1.7.2 version of Orchard ? We cant find that on github, the oldest version is 1.7.3. Is it possible to upgrade from 1.7.1 to 1.7.3 ? 

Thanks !

**Comment by sebastienros** [comment]
You need to do major version migrations one by one, using the latest of each major version.
So latest for 1.8, then 1.9 and finally 1.10. 

It "might" work by trying only the latest major, but there are many reasons it can fail too.
