### ISSUE TITLE
ProjectionManager can return duplicate results when using multiple filter groups

### ISSUE THREAD

**Issue by jimasp** [OrchardCMS/Orchard#8108]
There is a bug in ProjectionManager relating to filter groups.
This applies to filter groups which produce duplicate results and you are using paging.

To further explain, with easy steps to reproduce:

Imagine a scenario where you have say 20 blog posts.
You want to create a projection with a pager that shows _6 blog posts per page_.

When setting up your Query, you want to have 2 filter groups for your blogs i.e. an OR scenario, these filters are not exclusive (i.e. internally they may produce duplicate results).
For example, one filter may say blogs that have a tag of "news" or blogs that have a tag of "cabbages". So a blog tagged with both would be in both sets.

For the sake of simplicity and testing though, let's just set up your filter groups so they are guaranteed to produce 100% duplicates, eg:
ContentType="BlogPost" OR ContentType="BlogPost"

You will find that on the second page of the projection you get zero results. You will also find you get the wrong number of pages (double) in the pager.

Now let's look at the code in ProjectionManager.GetContentItems():

```
// aggregate the result for each group query
foreach (var contentQuery in GetContentQueries(queryRecord, queryRecord.SortCriteria.OrderBy(sc => sc.Position), tokens)) {
    contentItems.AddRange(contentQuery.Slice(skip, count));  
}
```

as we have a page size of 6, this would return 12 content items (6 from each group)
note the Slice being applied.
a little further down in the code we have:

```
var ids = contentItems.Select(c => c.Id).ToArray();
var groupQuery = _contentManager.HqlQuery().Where(alias => alias.Named("ci"), x => x.InG("Id", ids));
```

this returns 6 content items as in fact they are all duplicates.

following on from that, we have:

`return groupQuery.Slice(skip, count);`

Now, that would work fine on the first page, as skip will be 0, and count will be 6.

But on the second page of the pager, you will have skip of 6 and count of 6.

Which gives you 0 results.

I'm guessing this should be changed to:
`return groupQuery.Slice(0, count);`

Duplicate results inside the group filters will also cause the pager number of pages to be wrong due to the TotalItemCount being incorrect. This is effectively set via ProjectionManager.GetCount():
```
// aggregate the result for each group query
return GetContentQueries(queryRecord, Enumerable.Empty<SortCriterionRecord>(), tokens)
    .Sum(contentQuery => contentQuery.Count());
```
So this needs to be changed to something more like this:
```
return GetContentQueries(queryRecord, Enumerable.Empty<SortCriterionRecord>(), tokens)
    .SelectMany(contentQuery => contentQuery.List().Select(x => x.Id)).Distinct().Count();
```

Lazy, untested PR attached with these changes purely for clarity.

**Comment by sebastienros** [comment]
This is by design, as soon as you use groups you can't page without having duplicate items issues.
Your changes would load everything in memory, and then page which would have a huge impact on perf.

**Comment by jimasp** [comment]
i don't get it.
how would my changes load everything into memory? 
to be clear my code changes are as follows:

1. change this line:
`return groupQuery.Slice(skip, count);`  (returns 0 records in scenario)
to this:
`return groupQuery.Slice(0, count);`  (returns 6 records)
2. ideally, change this line:
`var contentItemsCount = _projectionManager.GetCount(query.Id, part) - part.Record.Skip;` (slow)
to this:
`var contentItemsCount = contentItems.Count() - part.Record.Skip;` (fast)

i don't see how those changes would load anything in memory that isn't already?

**Comment by jimasp** [comment]
I didn't get what you meant at first, but pretty sure you mean this change:

`return GetContentQueries(queryRecord, Enumerable.Empty<SortCriterionRecord>(), tokens)
    .SelectMany(contentQuery => contentQuery.List().Select(x => x.Id)).Distinct().Count();`

That's really why i stated
> something more like this

i.e. because i was hinting that i wasn't sure what the best solution was without delving further into the query functionality so was asking for input. (thanks).

i've put a more performant solution in the PR below. i realise you're unlikely to accept it, but it might help someone else who wants to do an Or group with paging, and/or someone can point out if it they see a problem with this approach in a non-official repo.

https://github.com/OrchardCMS/Orchard/pull/8114/files

**Comment by BenedekFarkas** [comment]
This looks promising, but making sure that it's not a performance compromise is very important. As a workaround, have you tried setting up the filter groups to be mutually exclusive? It might not always be possible, though.

Even if it's a performance hit (which might be acceptable to an extent), we can try to set it up in a way that the distinct check only happens if there are multiple groups. Probably most Projection Queries have only one filter group, so in those cases this would not affect anything.

**Comment by jimasp** [comment]
>filter groups to be mutually exclusive

thanks, i actually tried that first, but it didn't pass all our test scenarios.

> we can try to set it up in a way that the distinct check only happens if there are multiple groups. 

good idea, i've quickly stuck that in (untested), see the latest commit to the PR.

**Comment by sebastienros** [comment]
Sorry, I missed this code `contentQuery.List()`

**Comment by jimasp** [comment]
I ran a very quick + basic test.

I created a query based with Content Type "Any" as a filter.
I also created a Group query with Content Type "Any" OR Content Type "Any".

I then put a StopWatch start in ProjectionPartDriver like so:
```
  var metaData = Services.ContentManager.GetItemMetadata(part.ContentItem);
  Stopwatch stopwatch = new Stopwatch();
  stopwatch.Start();
```

And added Logger code to output the Elapsed.TotalMilliSeconds:
```
if (part.Record.DisplayPager) {
    var contentItemsCount = _projectionManager.GetCount(query.Id, part) - part.Record.Skip;
    contentItemsCount = Math.Max(0, contentItemsCount);
    pagerShape.TotalItemCount(contentItemsCount);
}
Logger.Debug("ProjectionDriver Elapsed:" + stopwatch.Elapsed.TotalMilliseconds);
```

Such that both _projectionManager.GetContentItems() and _projectionManager.GetCount(query.Id, part) are contained in the timer.

I disabled SysCache, and linked up a projection page with a pager to the test, with the setting for "Maximum number of items which can be queried at once" set to unlimited, and 10 items per page.

I loaded up an unrelated page in the site to start up Orchard and removed all scheduled tasks so unrelated db operations did not interfere with the test.
Then I loaded up the Projection Page 20 times with Ctrl+F5. 

Tests run with 18365 (published) content items in the database:

With PR changes:
With Group: mean average - 120ms      (range: 115 - 127ms)
Without Group: mean average - 97ms    (range:  95 - 132ms)

Without PR changes:
With Group: mean average - 105ms      (range:  98 - 148ms)
Without Group: mean average - 85ms    (range:  81 - 90ms)

These times are from a debug build running on a fast dev PC.

**Comment by BenedekFarkas** [comment]
@jimasp I'm so sorry for coming back to this so late.
This problem came up in one of our client projects, so I applied the changes from your PR and it's working great! I added some suggestions to you PR, I think it's good to go with those!
