### ISSUE TITLE
v1.10.2 - Release pipeline in VSTS (now Azure DevOps) not deploy new modules bin folder

### ISSUE THREAD

**Issue by fbardet** [OrchardCMS/Orchard#8117]
Hello,

My solution contains a custom module called MyModule (created by the command codegen module MyModule).
In VSTS, my release pipeline uses the IIS Deployment group job with the IIS Web App Deploy task.
The target package to deploy is $(System.DefaultWorkingDirectory)/_master/drop/Orchard.Web.zip.
On my server agent, the file C:\vstsagent\A4\_work\r2\a\_master\drop\MyModule.zip contains a bin folder.
But after the deploy, the folder C:\inetpub\wwwroot\MySite\Modules\MyModule do not contains the bin folder.
For all the default modules (Lucene, Orchard.Alias, Upgrade...), it's ok.
What's missing to deploy correctly the custom modules in VSTS ?

Best regards,
Frédéric

**Comment by CraigLittlewood** [comment]
Hello Frédéric

We are having the same issue.  Did you find a solution?

Regards
Craig

**Comment by fbardet** [comment]
Hello Craig,

My solution is to use task (powershell task or Unzip file task) to unzip the custom module package 
(ex : Expand-Archive -Path $(System.DefaultWorkingDirectory)/_master/drop/MyModule.zip -DestinationPath $(TempDirectory)\MyModule) 
and copy the files in the custom module bin folder
(ex : Copy-Item -Path $(TempDirectory)\Imagence.MyModule\Content\D_C\a\1\s\src\Orchard.Web\Modules\MyModule\obj\Release\Package\PackageTmp\bin -Destination $(SiteRootDirectory)\Modules\MyModule\bin –Recurse -force).

Best regards,
Frédéric

**Comment by deanmarcussen** [comment]
I came across this doing an Orchard Devops deployment yesterday.

The trick to getting a good zip file to start with, including all the custom module bin folders, is to 
- Build the `Orchard.proj` in the root of the repo, not the `Orchard.Web.csproj`
- Use the `/t:Precompiled` option
- The publish artifact path should then be set to `Build/PreCompiled`
- You can then `Zip-Deploy` that artifact
