### ISSUE TITLE
how we can get media files from remote server to Orchard media module

### ISSUE THREAD

**Issue by OrchardWeb** [OrchardCMS/Orchard#8122]
I'm new to Orchard CMS. I was trying to figured out the way to get the Media files from my remote drive into Orchard Media module(On Orchard Dashboard).

**Comment by sebastienros** [comment]
If you put the files in the same folder on the server, there is a custom "Upgrade" module that can be used to import all the local files as Media items.

**Comment by OrchardWeb** [comment]
That means I have to download the Upgrade module,Is it correct?

**Comment by OrchardWeb** [comment]
If suppose I have a bunch of Media file in my server,I want those files available on my Orchard UI(In Media Module)then only my development team will be able to use,I don't want to upload one by one.For that i created one button in media module beside the create folder button.I wrote one method in foldercontroller.cs,and I created one view also to display on in Media module.Some how I got the images but I was not able to use those Images in my content items.I was not able click on those images.(Usually if you upload image through the computer you can edit the name,delete,clone..)
