### ISSUE TITLE
Content data and themes data is not migrating from one Database to another database?

### ISSUE THREAD

**Issue by OrchardWeb** [OrchardCMS/Orchard#8123]
Hi All,

I'm new to Orchard CMS. My question is I changed my database of Orchard project and I copied whole data from Old one to New database.But,I figured out that I didn't get the content data and Themes data from old Database to new Database.Is it possible to happens like that.

Thanks in Advance

**Comment by sebastienros** [comment]
You mean the templates?

**Comment by OrchardWeb** [comment]
Yeah,I created one theme in my localhost with one database.I tried to hosted into my IIS server with new database,(I migrated data all data from old DB to new DB).The Template I got,I was trying to login with my credentials,It shows PAGE NOT FOUND.
