### ISSUE TITLE
Fix default value of NumericField

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard#8124]
@apiradeemaii 14 days ago  • 
This comment is test about Default value should be proposed on creation.
But when I go to "Admin/ContentTypes/Edit/Event" and look at Numeric Field. It has no text box of Default value for input data.

  @protoncm
protoncm 13 days ago  • 
 Contributor
@sebastienros I think Default value was removed by accident after you merged 1.10.x branch to dev ? see commit line: c8a4def#diff-cd6b21ce02651cd47807bad80bef7189L53

**Comment by BenedekFarkas** [comment]
@ifjmacila is working on this.
