### ISSUE TITLE
How we get the themes from Local Host to Server?

### ISSUE THREAD

**Issue by OrchardWeb** [OrchardCMS/Orchard#8129]
I developed one theme in Local host and trying to put in server(Install from Computer option in Themes Module on Orchard UI).Somehow I'm getting error while I'm trying to put the new theme as set as current theme or Enable theme[Please check the below path for Reference].Can you please help me out what are the possibilities and where should I have to do the changes.
(https://user-images.githubusercontent.com/43148914/46822800-a9361280-cd49-11e8-9785-35af59d5791d.png)

**Comment by OrchardWeb** [comment]
Is there anyone to help me out from this issue?

**Comment by sebastienros** [comment]
You should look at the logs.

Also deploying Orchard is quite well documented, have you looked at it?

**Comment by OrchardWeb** [comment]
No I didn't see yet.Can you please share the document link,I will review it.

Thanks in Advance.

**Comment by sebastienros** [comment]
http://docs.orchardproject.net/en/latest/search.html?q=deploy
