### ISSUE TITLE
Blind SQL Injection

### ISSUE THREAD

**Issue by jerhhh** [OrchardCMS/Orchard#8130]
Nexpose has detected Blind SQL Injection vulnerability.

Updated: Removing screenshot for security reasons

**Comment by Piedone** [comment]
What is the issue exactly, what is happening? Is there a YSOD or something worse?

**Comment by sebastienros** [comment]
Please send any security concern to me directly at sebastien.ros@microsoft.com

This message doesn't prove there is any issue but I prefer to confirm offline with you directly. Thanks.
