### ISSUE TITLE
Gallery, widget, and Lucene error (all one related issue?)

### ISSUE THREAD

**Issue by nutullah** [OrchardCMS/Orchard#8132]
I am running into three issues, that all may or may not be related.

First, the gallery page does not show any modules or themes. After reviewing other issues, I realized that my gallery feed link is empty. I tried to add the gallery link, but received the following error ("The url of the feed or its content is not valid."):
![image](https://user-images.githubusercontent.com/20462294/47401676-ec0fc700-d707-11e8-971e-b744e30f4816.png)

Second, I am also issues with widgets. Whenever I try to save a new widget, I receive the following runtime error ("Cannot perform runtime binding on a null reference"):
![image](https://user-images.githubusercontent.com/20462294/47401813-64768800-d708-11e8-90c3-6ecce4c8c478.png)

Third, when I build the root project for the website on visual studio, I receive the following error:
Severity Code Description Project File Line Suppression State
Error The type or namespace name 'Lucene' could not be found (are you missing a using directive or an assembly reference?) c:\Users\nkisa\AppData\Local\Temp\Temporary ASP.NET Files\root\12a3c9a5\acde505f\App_Web_1xekvbnv.0.cs 35 

The website is also very slow, but it is up and running. Again, I'm not sure if these are related, but they all started happening at the same time. Please let me know if you know how to resolve/how to start resolving any or all of these issues.

Thank you!

**Comment by sebastienros** [comment]
The https cert was out of date, can you try again?

**Comment by nutullah** [comment]
It is working. Thank you so much for your help
