### ISSUE TITLE
The Custom Properties part not found in Content Parts list

### ISSUE THREAD

**Issue by Estar1** [OrchardCMS/Orchard#8134]
I created an Employee content type and added a containable part to it - but I can't find the 'Custom Properties' part to add to it. This is needed to automatically add the Custom 1, Custom 2 and Custom 3 fields that its required by the Widget container filter

Any ideas please?

**Comment by BenedekFarkas** [comment]
Is your custom content part attachable (it's a checkbox in the content part's settings)?

**Comment by BenedekFarkas** [comment]
@Estar1 please reopen or follow-up on [Gitter](https://gitter.im/OrchardCMS/Orchard) if this question is still relevant.
