### ISSUE TITLE
Deleting media all profiles of the media are persistent

### ISSUE THREAD

**Issue by LorenzoFrediani-Laser** [OrchardCMS/Orchard#8156]
When contentitem media file is deleted, the  media file is deleted from filesystem but the files generated and stored on  _Profiles folder  are not deleted and they can be displayed by direct url.

**Comment by BenedekFarkas** [comment]
@LorenzoFrediani-Laser FYI I tested this, works nicely and I added support for the same thing when using Azure Blob Storage.
