### ISSUE TITLE
Upgrade to jQuery 3.3.1 and jQuery UI 1.12.1

### ISSUE THREAD

**Issue by niranjankala** [OrchardCMS/Orchard#8161]
I run into a problem with old version of jQuery that tends to fail lots jQuery widgets. So i have to manually upgrade the version of jQuery in the Orchard CMS release build. It would be better to have updated version  of these libraries.

**Comment by niranjankala** [comment]
Hi @sebastienros,

I would like to contribute about this upgrade of jQuery libraries. How can i start contribute?? What is the process to get start. I would be better to have discussion to let me know about the process if possible...

Thanks,
Niranjan

**Comment by sebastienros** [comment]
Create a PR that updates the version.

**Comment by niranjankala** [comment]
Merged [PR-8183](https://github.com/OrchardCMS/Orchard/pull/8183) related to this issue.
