### ISSUE TITLE
have a exception on second setup later

### ISSUE THREAD

**Issue by kiventwang** [OrchardCMS/Orchard#8164]
when I run the program setup page write the information later（I choice the software as service ）the program correct run。the I delete the app_data folder start the second setup，I choice the blog in this time,but the program throw an exception  "An unhandled exception was thrown by the application.
System.ArgumentNullException: The folder 'wwwroot' that contains the web-servable application content files is missing. Please add this folder to the application root to allow caching.
Parameter name: WebRootPath"

**Comment by sebastienros** [comment]
Looks like an issue for https://github.com/OrchardCMS/OrchardCore, please file a new one on the other repository.

**Comment by gtmoraisomd** [comment]
I just created the wwwroot folder there and it was fine, apparently an issue with the ImageSharp and the Agency template.
