### ISSUE TITLE
Registration challenge e-mail won't work if only authenticated users can access the frontend

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/Orchard#8166]
If you revoke the AccessFrontend permission from anonymous users then the whole registration challenge e-mail mechanism breaks:

1. After submitting the registration form you'll get an Access Denied because AccountController/ChallengeEmailSent is inaccessible.
2. Opening the link received in the challenge e-mail will again give you an Access Denied because the ChallengeEmail action is inaccessible too. Same would later happen with ChallengeEmailSuccess and ChallengeEmailFail too.

RegistrationPending has a similar issue. So all but the LogOff action needs `[AlwaysAccessible]` it seems.

The fix is trivial, I'm opening this only because I may be missing something obvious. So should we just add `[AlwaysAccessible]` everywhere mentioned?

**Comment by BenedekFarkas** [comment]
@sebastienros if you agree that it's OK from a security perspective, then I'll fix it for 1.10.3.

**Comment by sebastienros** [comment]
GTG

**Comment by BenedekFarkas** [comment]
@sebastienros pre-release (tag and package) updated.
