### ISSUE TITLE
How to use logger in Orchard customer module?

### ISSUE THREAD

**Issue by happydaily** [OrchardCMS/Orchard#8168]
I want to use logger for customer module,I add  public ILogger Logger { get; set; } and  Logger = NullLogger.Instance  and Logger.Warning("Erssss") like orchard.framwork, but customer module don't log  error ,by breakpoints,I find Logger still is Orchard.Logging.NullLogger,how can I get  an instance of CastleLogger?

**Comment by ViRuSTriNiTy** [comment]
The correct logger instance is injected, see https://stackoverflow.com/questions/9225040. Where does the log call takes place? Any chance that you have it in the constructor or a place where the logger instance is not injected yet?

**Comment by happydaily** [comment]
> The correct logger instance is injected, see https://stackoverflow.com/questions/9225040. Where does the log call takes place? Any chance that you have it in the constructor or a place where the logger instance is not injected yet?

How to injected castlelogger property in customer module ?

**Comment by ViRuSTriNiTy** [comment]
> > The correct logger instance is injected, see https://stackoverflow.com/questions/9225040. Where does the log call takes place? Any chance that you have it in the constructor or a place where the logger instance is not injected yet?
> 
> How to injected castlelogger property in customer module ?

Did you read the stackoverflow answer posted by @pszmyd (Piotr)? The logger instance is injected by the Autofac module, you don't need to inject it yourself. You could set a breakpoint in the Autofac module to analyse why your module is skipped or something.

**Comment by sebastienros** [comment]
Here is an example:
https://github.com/OrchardCMS/Orchard/blob/5b5eda6ae36dc2d7906599882165ef1e985cdc8c/src/Orchard.Web/Modules/Orchard.Glimpse/Services/DefaultGlimpseService.cs#L24

You only need to declare a custom `ILogger` property, initialize it with a `NullLogger` and at runtime it will get the correct instance.

**Comment by happydaily** [comment]
> Here is an example:
> [Orchard/src/Orchard.Web/Modules/Orchard.Glimpse/Services/DefaultGlimpseService.cs](https://github.com/OrchardCMS/Orchard/blob/5b5eda6ae36dc2d7906599882165ef1e985cdc8c/src/Orchard.Web/Modules/Orchard.Glimpse/Services/DefaultGlimpseService.cs#L24)
> 
> Line 24 in [5b5eda6](/OrchardCMS/Orchard/commit/5b5eda6ae36dc2d7906599882165ef1e985cdc8c)
> 
>  public ILogger Logger { get; set; } 
> You only need to declare a custom `ILogger` property, initialize it with a `NullLogger` and at runtime it will get the correct instance.

I try to use log in orchard.setup module,setupcontroller.cs,at line 163,when error occured, Logger didn't worked?
