### ISSUE TITLE
Page title field uses Chinese garbled

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/Orchard#8172]
Orchard Version: 1.10.3
MySQL:5.7

![image](https://user-images.githubusercontent.com/3222379/54805193-25e1fb00-4cb1-11e9-8108-fb36ad1b1cbf.png)

Chinese Culture is alread added to setting and set to the default.
How can  I resolve the problem ? 
Thanks!

**Comment by sebastienros** [comment]
Can you explain the issue? With repro steps?

**Comment by RockNHawk** [comment]
> Can you explain the issue? With repro steps?

Hi, Thank you for taking the time to reply to me.

- I deploy a new Orchard instance (I have tried Orchard 1.10.3 release and 1.10.x branch from source code fresh install without any third-party module or customize)
- Create a new Page content
- the Page title fill in chinese character, such as “你好世界”
- also put some chinese character in Layout and Body part
![image](https://user-images.githubusercontent.com/3222379/55203792-a8197480-5207-11e9-87fa-866bf8a36de2.png)

- click "Save"

the content saved, but the title, route url and body becomes to "????",  but the chinese character in Layout is correct.
![image](https://user-images.githubusercontent.com/3222379/55203798-b071af80-5207-11e9-8ee9-1e23406e9545.png)

**Comment by RockNHawk** [comment]
I have tried https://dotnest.com , haven't this issue.
So, any one know how https://dotnest.com solved this problem ?

**Comment by HermesSbicego-Laser** [comment]
Tryed on our test env and everything works as expected, with no issue. Could be a mysql db misconfiguration?

**Comment by RockNHawk** [comment]
> misconfiguration

Ah,, may be MySQL connection string should add `;charset=utf8;` parameter, let me have a try....
Thank you for your advice !

**Comment by RockNHawk** [comment]
@HermesSbicego-Laser Add `;charset=utf8;` parameter to connection string solved my problem , Thank you!

I think Orchard should add`;charset=utf8;` parameter to  connection string template in Setup page.

**Comment by RockNHawk** [comment]
Orchard MySQL 中文乱码。

 Orchard MySQL 텍스트가 왜곡되었습니다.

 Orchard MySQL text garbled.

Orchard MySQL Text verstümmelt

Orchard MySQL 文字化け

(Add this comment to make it easier for others to search)
