### ISSUE TITLE
Unable to access files in App_data

### ISSUE THREAD

**Issue by cmsilv** [OrchardCMS/Orchard#8179]
Upgraded from Orchard 1.10.0 to 1.10.3 and was testing changes.

Tried launching the site and received this error
 
```
Orchard.Web\App_Data\Sites\Default\Settings.txt' is denied. 
ASP.NET is not authorized to access the requested resource. Consider granting access rights to the resource to the ASP.NET request identity. ASP.NET has a base process identity (typically {MACHINE}\ASPNET on IIS 5 or Network Service on IIS 6 and IIS 7, and the configured application pool identity on IIS 7.5) that is used if the application is not impersonating. If the application is impersonating via <identity impersonate="true"/>, the identity will be the anonymous user (typically IUSR_MACHINENAME) or the authenticated request user. 

To grant ASP.NET access to a file, right-click the file in File Explorer, choose "Properties" and select the Security tab. Click "Add" to add the appropriate user or group. Highlight the ASP.NET account, and check the boxes for the desired access
```

I noticed that in 1.10.3 changes have been made to Orchard/FileSystems/AppData/AppDataFolder.CreateFile to create the file in a temp location and then move it to the App_Data folder  instead of just creating the file in App_Data directly. Per this [article](https://stackoverflow.com/questions/2929918/file-move-does-not-inherit-permissions-from-target-directory) when files are moved they do not inherit the file access permissions of the target directory. (which is why I believe I am seeing the change in behavior) modifying the code as follows fixed the issue. Note the section at the bottom.
```
private static void WriteAllTextWithTempFileAndMove(string path, string content) {
            // generate a temp file
            var tempPath = Path.GetTempFileName();

            // write the data to a temp file
            using (var tempFile = File.Create(tempPath, 4096, FileOptions.WriteThrough)) {
                using (var writer = new StreamWriter(tempFile)) {
                    writer.Write(content);
                }
            }

            // move to destination
            // will throw exception if destination exists
            File.Move(tempPath, path);

            // when files are moved they do not inherit permissions from the target directory, added this block of code so that they will
            System.Security.AccessControl.FileSecurity fileSecurity = File.GetAccessControl(path);
            fileSecurity.SetAccessRuleProtection(false, false);
            File.SetAccessControl(path, fileSecurity);
        }
```

I am not sure if this is actually a base issue or just an issue with how I am deploying the site.

**Comment by sebastienros** [comment]
Can you provide a PR?

And I assume they don't inherit the rights form the original folder either?

**Comment by cmsilv** [comment]
The file does have some access permissions. My guess is it inherits these from the original folder and then keeps them through the move operation even though the inheritance to the original folder is severed. Just a guess though.

Will provide a pull request shortly.

**Comment by cmsilv** [comment]
#8180
