### ISSUE TITLE
CommonPart(Version)Record query performance problems

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#8196]
There are no indexes on CommonPart(Version)Record columns, which can cause performance issues and query timeout with a couple thousand content items in common scenarios, such as simply displaying the content list at "/Admin/Contents/List". This listing can order items by Created/Modified/Published date, so at least those columns should have an index.

**Comment by sebastienros** [comment]
Good point

**Comment by BenedekFarkas** [comment]
Fixed in #8210
