### ISSUE TITLE
Culture Picker: 

### ISSUE THREAD

**Issue by zorankalicanin** [OrchardCMS/Orchard#8200]
Hi All,

is it possible to create only one culture picker per theme?
Right now whenever I create some widget, with added Localization part, new culture picker is created also. As a result there is to many pickers.
As solution i create an alternate per picker and delete html content of the alternate.
I am wondering is there some more elegant solution.

Thanks in advance
Zoran Kalicanin

**Comment by sebastienros** [comment]
Can you show a screenshot and some repro steps? 

> I create some widget

It's not obvious what "create" means in this context.

**Comment by zorankalicanin** [comment]
**Home Page: there are two culture pickers**
![1  HomePage](https://user-images.githubusercontent.com/8599750/57910176-e97fe500-7884-11e9-98f2-304edeb4be37.PNG)


**In Dashboard, in the Widget page are added three html widgets. They are culture specific**
![2  AdminWidgets](https://user-images.githubusercontent.com/8599750/57909378-f13e8a00-7882-11e9-927f-d67e97e5c498.PNG)


**To HtmlWidget is added Localisation part**
![3  EditContentType_HtmlWidget](https://user-images.githubusercontent.com/8599750/57909380-f3a0e400-7882-11e9-881c-fcf9c1e568ac.PNG)


![4  EditHtmlWidget](https://user-images.githubusercontent.com/8599750/57909382-f56aa780-7882-11e9-9a01-da5f939cf707.PNG)


**Enabled Features: Localization and CulturePicker** 
![5  EnabledFeatures_ContentLocalization](https://user-images.githubusercontent.com/8599750/57909384-f7346b00-7882-11e9-8630-9633a8d0cf3d.PNG)


![6  EnabledFeatures_CulturePicker](https://user-images.githubusercontent.com/8599750/57909387-f996c500-7882-11e9-9ee1-02e2858a5f75.PNG)

**Comment by zorankalicanin** [comment]
Issue is solved. 
At the end I installed Culture Switch module.
There was needed only to fix changing culture on home page.

In the UserCultureController.cs, in the ChangeCulture method i used custom SetCultureCookie instead of SaveCultureCookie private method.

private void SaveCultureCookie(string cultureName)
{
   HttpContextBase httpContext = Services.WorkContext.HttpContext;
   HttpRequestBase request = httpContext.Request;

   var cultureCookie = new HttpCookie(CookieCultureSelector.CultureCookieName);
   cultureCookie.Values.Add(CookieCultureSelector.CurrentCultureFieldName, cultureName);
   cultureCookie.Expires = DateTime.Now.AddYears(1);

   //setting up domain for cookie allows to share it to sub-domains as well
   //if non-default port is used, we consider it as a testing environment
   //without sub-domains
   if (request.Url != null && request.Url.IsDefaultPort) {
       // '.' prefix means, that cookie will be shared to sub-domains
       cultureCookie.Domain = "." + request.Url.Host;
   }

   httpContext.Response.Cookies.Add(cultureCookie);
}

private void SetCultureCookie(string culture) 
{
     _cultureStorageProvider.SetCulture(culture);
}
