### ISSUE TITLE
Taxonomies and Terms

### ISSUE THREAD

**Issue by MatteoPiovanelli** [OrchardCMS/Orchard#8209]
Some issues I am seeing in terms and taxonomies on the dev branch (pasting here from gitter):

I was checking stuff related to optimizations, specifically wrt Terms and Taxonomies. I noticed that in the dev branch TermPart has a FullWeight property, introduced in #7709 .
Using that property as it is now in dev reverses the ordering of terms in a taxonomy when compared to the situation in the 1.10.x branch. In 1.10.x terms (on the same level) are ordered by decreasing weight. In dev they are ordered by increasing weight.
Additionally, in the code from dev TermPart.Name is not used in ordering terms, while it is being used as a "backup" criterion in 1.10.x when two terms have identical paths and weights.
Both these differences may be somewhat breaking in terms of experience for our users.

used to be htat terms were sorted in memory, based on decreasing weight and then alphabetical order of title
in dev a string is built and stored in the db to "map" the tree structure
it only uses weight, and doing a sql's orderby there results in an increasing weight order

and I have issues with the Post Editor in the TermPartDriver
it's doing TryUpdateModel, then doing further updates no matter what the result.
if it sets that to null, a method later in the update will throw an exception, because it will use that string as a paramenter for a string.IndexOf
```
string parentOldFullWeight = termPart.FullWeight == null ? termPart.FullWeight : "";
```
parentOldFullWeight will be null if termPart.FullWeight is null, empty otherwise

with the driver as it is:
Starting from
parent.FullWeight = 000009.13/
​child.FullWeight = 000009.13/000007.158/

Update parent.

Now you have:
parent.FullWeight = 000009./
​child.FullWeight = 000009./000009.13/000007.158/

I'll try to tackle all that, as well as a few refactorings and optimizations.

**Comment by MatteoPiovanelli** [comment]
Currently testing this:
https://github.com/LaserSrl/Orchard/tree/fix/8209_TAxonomiesTerms

**Comment by sebastienros** [comment]
thanks for looking into it

**Comment by MatteoPiovanelli** [comment]
A pr should be coming soon.
Note that we have been testing this on our environments, that are a sort of hybrid between 1.10.x an dev.
