### ISSUE TITLE
Validate ReCaptcha in custom controller and implementation redundant 

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/Orchard#8211]
If i add a `ReCaptcha Element` to a dynamic form in the layout editor and submit to a custom controller, the `ReCaptcha Field` is not required an the form could be submitted without solving/checking the captcha.
How can i use the `OnValidate` from the `DynamicForms Module` in my module?

Also, the implementation is redundant in the `AntiSpam Module` and in the `DynamicForms Module`.

**Comment by Flarescape** [comment]
If someone has the same problem, i've found the solution to the custom controller problem.
Just implement this code from the dynamic forms controller at the beginning of your custom controller.
This uses all validators (also the recaptcha validator) and prevents a further processing of the submit.

```
            var layoutPart = _layoutManager.GetLayout(contentId);
            var form = _formService.FindForm(layoutPart, formName);
            var urlReferrer = Request.UrlReferrer != null ? Request.UrlReferrer.LocalPath : "~/";

            if (form == null)
            {
                Logger.Warning("The specified form \"{0}\" could not be found.", formName);
                _notifier.Warning(T("The specified form \"{0}\" could not be found."));
                return Redirect(urlReferrer);
            }

            var values = _formService.SubmitForm(layoutPart, form, ValueProvider, ModelState, this);
            this.TransferFormSubmission(form, values);

            if (!ModelState.IsValid)
            {
                // We need a way to inform the output cache filter to not cache the upcoming request.
                var epoch = new DateTime(2014, DateTimeKind.Utc).Ticks;
                var refresh = _clock.UtcNow.Ticks - epoch;
                return Redirect(urlReferrer + "?__r=" + refresh);
            }
```

**Comment by sebastienros** [comment]
Will close because you found a solution.
