### ISSUE TITLE
Performace issue on localized Taxonomies and Terms

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#8221]
src/Orchard.Web/Modules/Orchard.Taxonomies/Handlers/LocalizedTaxonomyPartHandler.cs
The code between lines 53/70 is inefficient with lots of terms.

**Comment by MatteoPiovanelli** [comment]
Notes regarding this:

line 47: we get the Ids of taxonomies from the respective content items
line 50: for each taxonomy id, we fetch the contentitem again, and then its culture

line 51: we get the ids of terms by fetching the termparts
line 54: for each term it, we fetch the termpart again

line 55: we call _taxonomyExtensionsService.GetParentTerm. That takes the container item for the term, and using its id fetches the same item again.

Should be easy to fix, I think
