### ISSUE TITLE
Problem with versioning in style include

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/Orchard#8231]
We used to be able to do the following:

Style.Include("site.css?version=4.1.5");

The versioning is now causing a error and is not able to find the resource. 
(with the exception "System.ArgumentException: Illegal characters in path.")
Not present in 1.10.2 but is in 1.10.3

**Comment by Piedone** [comment]
Maybe related to https://github.com/OrchardCMS/Orchard/commit/514e4fa0d79486603382d8058c03a0a3cb9c12d3.

**Comment by Piedone** [comment]
Are you sure you didn't check this on a dev commit?

**Comment by BenedekFarkas** [comment]
Updated milestone to dev as it turned out that it's not an issue on 1.10.x.
