### ISSUE TITLE
How notifier are delivered to the front end and displayed?

### ISSUE THREAD

**Issue by happydaily** [OrchardCMS/Orchard#8237]
I have added message in Orchard.Notifier,
`_notifier.Add(NotifyType.Error, T("An Exception has occured,error message:{0}", filterContext.Exception.Message)); `
I want to display this message to front page by custom,What should I do?

**Comment by sebastienros** [comment]
There is a Filter (NotifyFilter) that will be executed on each request and inject a custom shape in the current Layout, in the Messages zone. Then each theme can pick all the shapes from this zone and render them. The values are cleared on each request.
