### ISSUE TITLE
Media Library delete folder could delete media from neighbor folders.

### ISSUE THREAD

**Issue by AndreyLuzinov** [OrchardCMS/Orchard#8239]
https://github.com/OrchardCMS/Orchard/blob/89c562c50216498ecf3b0a87d7ca8832005b4cdf/src/Orchard.Web/Modules/Orchard.MediaLibrary/Services/MediaLibraryService.cs#L98

Example:
1. You have 2 folders: Folder1 and Folder11
2. Delete folder Folder1.
3. Files from Folder11 will also be removed because you cannot search sub-folders with StartsWith function.

**Comment by AndreyLuzinov** [comment]
This issue related to DeleteFolder and RenameFolder methods.

**Comment by sebastienros** [comment]
Nasty one, it needs to be fixed ASAP
