### ISSUE TITLE
MediaUrl for OEmbed

### ISSUE THREAD

**Issue by MatteoPiovanelli** [OrchardCMS/Orchard#8242]
We noticed that unlike other Media Types, when a MediaPart is an OEmbedPart (we checked this for youtube and vimeo videos) its MediaUrl property is null.

Would there be any issue in populating that?

It could easily be done in the MediaPartHandler like this:
```
OnLoaded<MediaPart>((context, part) => {
    if (!String.IsNullOrEmpty(part.FileName)) {
        part._publicUrl.Loader(() => _mediaLibraryService.GetMediaPublicUrl(part.FolderPath, part.FileName));
    } else {
        var oe = part.As<OEmbedPart>();
        if (oe!=null) {
            part._publicUrl.Loader(() => oe.Source);
        }
    }
});
```

**Comment by sebastienros** [comment]
I don't see any issue with that.

**Comment by MatteoPiovanelli** [comment]
I will test this a bit in the next few days an make a PR
