### ISSUE TITLE
Content Picker - Culture filter lost after changing page

### ISSUE THREAD

**Issue by MarcoViglione-Laser** [OrchardCMS/Orchard#8243]
When selecting a content item to add to a Content Picker, if the localization feature is enabled there's the option to filter content items by culture.
If there are enough content items to activate the pager, unlike the other filters the culture filter is lost after changing page.
I'll make soon a pull request to address this problem.

**Comment by BenedekFarkas** [comment]
@MarcoViglione-Laser @sebastienros so #8244 completely fixes this issue?
