### ISSUE TITLE
Content Picker - Selected items lost after changing page

### ISSUE THREAD

**Issue by MarcoViglione-Laser** [OrchardCMS/Orchard#8247]
If a Content Picker shows multiple pages of content items, selecting items in a page and then moving to another page now causes the selections of the previous page to be lost. Clicking "Add selected" will only add the items selected in the current page.
I rewrote the script SelectableContentTab.js to allow for items selected in other pages to be memorized and added when the "Add selected" button is clicked.

**Comment by BenedekFarkas** [comment]
@MarcoViglione-Laser @sebastienros so #8248 completely fixes this issue?
