### ISSUE TITLE
returnurl parameter problem

### ISSUE THREAD

**Issue by LorenzoFrediani-Laser** [OrchardCMS/Orchard#8258]
in many views this line of code is present (es: Core\Contents\Views\Content.SummaryAdmin.cshtml)
 var returnUrl = ViewContext.RequestContext.HttpContext.Request.ToUrlString();

why don't use relative url?
  var returnUrl=ViewContext.RequestContext.HttpContext.Request.RawUrl;
  
this will prevent error on a scenario of load-balancer redirecting https requests to http

**Comment by sebastienros** [comment]
Would that work with prefixed tenants?

**Comment by LorenzoFrediani-Laser** [comment]
Yes, i have tested it
