### ISSUE TITLE
locked out

### ISSUE THREAD

**Issue by thesecuritycompany** [OrchardCMS/Orchard#8279]
Hello, 

I've recently joined a company who need to update their Orchard content. Unfortunately the old developers who set it up have gone. 

I've tried following various guides online that suggest changing a field in the users table to "Clear" to remove the hashing. I've then changed the password to something like "Password#123" to try an gain access but to no avail. 

I'm wondering if these guides are old. Do you have a mechanism to reset passwords in the newer version of Orchard? Or can I inject a user in to the DB?

**Comment by sebastienros** [comment]
You need to change it in the contentitemversion table too, it has the whole data in xml.

**Comment by TheDevelolper** [comment]
Sorry but that's very little to go on... Where is Content Item Version? I don't see a table with that name? 

I found Orchard_Framework_ContentItemVersionRecord

but it has rows and rows of data. I have no idea what I'm supposed to be looking for to change the password?

**Comment by TheDevelolper** [comment]
I finally managed to find what I was looking for. 

You need to find the record in the above table with the same ID as the user ID. It will have some XML metadata associated with that user. For some reason, all the info in the table is represented as XML. 

I copied the data out into vscode and edited it. I then updated the record and it worked.
