### ISSUE TITLE
OrchardProject.net ssl certificate is expired.

### ISSUE THREAD

**Issue by niemyjski** [OrchardCMS/Orchard#8307]
OrchardProject.net ssl certificate is expired.

**Comment by sebastienros** [comment]
Thanks for reporting it, have I broken the Let's Encrypt bot :(

**Comment by sebastienros** [comment]
Status: Found the reason, the automatic redirection to orchardcore.net broke the auto ssl cert renewal as it can't request the acme file anymore (due to the redirection). Now update these rules so that it still works.
