### ISSUE TITLE
Missing some dll files in orchard source

### ISSUE THREAD

**Issue by hoomanhooshyar** [OrchardCMS/Orchard#8314]
Hello everyone
newly when I run Orchard solution in visual studio, it has some errors like this one:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'D:\Software\Programming\Orchard\Develope\Orchard-1.10.3\src\Orchard.Web\Modules\Orchard.ContentTypes\bin\Orchard.ContentTypes.dll' could not be found	Orchard.Autoroute	D:\Software\Programming\Orchard\Develope\Orchard-1.10.3\src\Orchard.Web\Modules\Orchard.Autoroute\CSC	1	Active

but why?
I have downloaded source code from orchardproject.net but it seems some dll files is missing.
How could I fix this error?
Thanks a lot in advance

**Comment by sebastienros** [comment]
Did you clone the repository or downloaded the zip files in the releases tab?

**Comment by hoomanhooshyar** [comment]
I have downkoaded zip file


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Sébastien Ros <notifications@github.com> Date: 1/30/20  23:34  (GMT+03:30) To: OrchardCMS/Orchard <Orchard@noreply.github.com> Cc: hoomanhooshyar <hooman.hooshyari@gmail.com>, Author <author@noreply.github.com> Subject: Re: [OrchardCMS/Orchard] Missing some dll files in orchard source (#8314) 
Did you clone the repository or downloaded the zip files in the releases tab?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OrchardCMS/Orchard/issues/8314?email_source=notifications\u0026email_token=ALNOBDUAFJGTKR2O4Y667VTRAMXE7A5CNFSM4KLVE2FKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKMLFTQ#issuecomment-580432590",
"url": "https://github.com/OrchardCMS/Orchard/issues/8314?email_source=notifications\u0026email_token=ALNOBDUAFJGTKR2O4Y667VTRAMXE7A5CNFSM4KLVE2FKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKMLFTQ#issuecomment-580432590",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sebastienros** [comment]
Did you download it from this page? https://github.com/OrchardCMS/Orchard/releases

When unzipped there is a Build.cmd file you need to execute.

**Comment by hoomanhooshyar** [comment]
> Did you download it from this page? https://github.com/OrchardCMS/Orchard/releases
> 
> When unzipped there is a Build.cmd file you need to execute.

Yes, I have worked on it and I have done that. It works well, 
Thanks a lot
