### ISSUE TITLE
Bug?? Admin Workflow page

### ISSUE THREAD

**Issue by kyahyan** [OrchardCMS/Orchard#8316]
Can't Scroll up ![Screen Shot 2020-02-03 at 6 30 53 PM](https://user-images.githubusercontent.com/23460968/73645987-6a9d3780-46b3-11ea-9e81-964135ce51ef.png)

**Comment by sebastienros** [comment]
What browser and version are you using?
Are there simple steps to reproduce the issue?

**Comment by kyahyan** [comment]
Googgle Chrome, Version 79.0.3945.130 (Official Build) (64-bit). i thing it's Latest Version.
i wrong put html body in Notify Task Message  then i save it. that's what happen, can't scroll up

**Comment by kyahyan** [comment]
When i use split Screen then when you save it. auto Crop Workflow | Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

@sebastienros

**Comment by sebastienros** [comment]
Create the issue in Orchard Core repository if this is what you are using.
