### ISSUE TITLE
Can't Save Password in SMPT Config

### ISSUE THREAD

**Issue by kyahyan** [OrchardCMS/Orchard#8320]
![Screen Shot 2020-02-07 at 11 43 26 PM](https://user-images.githubusercontent.com/23460968/74043120-c9401980-4a03-11ea-9cf8-c6a3d5cdd3f3.png)

**Comment by agriffard** [comment]
It is not displayed when you are refreshing the page but don't worry, the password is saved.

Try the 'Test Settings' button and you will see if it works.

**Comment by domonkosgabor** [comment]
I think this is related to Orchard Core.
