### ISSUE TITLE
Can I modify Web.config of Orchard.Web project?

### ISSUE THREAD

**Issue by endrihacker** [OrchardCMS/Orchard#8330]
I don't have any previous experience with Orchard CMS and I am required to implement some changes to an existing Module.
What I need to do is to use a soap web service in that module. I noticed that adding a service reference to my module project didn't and to solve it I moved bindings and endpoint to Web.config or Orchard.Web project.
Is this the right way to do it? Am I allowed to modify that web.config file?
Is any point I'm missing that I am not able to use those binding and endpoint from the web.config of my module?

**Comment by sebastienros** [comment]
Yes it's totally valid to update it. What you can also do is a web.config transform file in case you don't want to change it directly, as it might be updated overtime in our repos.
