### ISSUE TITLE
GraphiQL unresponsive

### ISSUE THREAD

**Issue by siaochuenchong** [OrchardCMS/Orchard#8341]
Hi guys, 

After enabling GraphQL in the feature tab, the page is unresponsive when I click GraphiQL in the Configuration area. Can anyone solve this issue? Thanks for your help!
![image](https://user-images.githubusercontent.com/57893076/78208034-ebbb5400-74d5-11ea-80ee-c4d085b4c5f3.png)

**Comment by sebastienros** [comment]
OrchardCore issue
