### ISSUE TITLE
Can someone explain the dev branch

### ISSUE THREAD

**Issue by imranazad** [OrchardCMS/Orchard#8342]
Can someone please explain the `dev` branch? I noticed there's additional branches such as `master` `1.10.x`, `1.10.2` what exactly is the strategy here? When do changes in `dev` get merged into master? And what exactly is master, where are the changes being merged from? How does this differ from branches such as  `1.10.x`, `1.10.2`.  I couldn't find any explanation in the read me.

**Comment by sebastienros** [comment]
Dev target the next "major" release, including breaking changes if any. Currently 1.11.
1.10.x target the next "minor" release, and no breaking changes are allowed. It can also contain new features if not breaking.
1.10.2 and other previous releases have their own tag/branch in case we need to apply security fixed retroactively.

**Comment by imranazad** [comment]
@sebastienros That's great thank you.
