### ISSUE TITLE
Is it okay to directly linking theme's script in a module?

### ISSUE THREAD

**Issue by lbcsy** [OrchardCMS/Orchard#8347]
Can I do following in a view? The first Include is pointing to a script in a theme

`@{
    Layout.Title = T("Edit Tenant").ToString();
    Script.Require("jQuery").AtFoot();
    Script.Require("ShapesBase").AtFoot();
    Script.Include(Url.Content("~/Themes/TheAdmin/Scripts/admin.js")).AtFoot();
    Script.Include("multi-tenancy.admin.js").AtFoot();
}`

Above pattern has been repeated in several Orchard modules such as MultiTenancy, doesn't above create a dependency from a module to a theme?

**Comment by sebastienros** [comment]
It creates a dependency to TheAdmin theme, in admin views, so that's acceptable.

**Comment by lbcsy** [comment]
Thanks, that means we don't switch theme for admin view.
