### ISSUE TITLE
Default Values for ContentPickerFields

### ISSUE THREAD

**Issue by MatteoPiovanelli** [OrchardCMS/Orchard#8350]
Use Case 1:
When a User creates a content of Type MyType, a ContentPickerField for the new content should be set to contain the same content that is already selected in another ContentPicker in the User.

Use Case 2:
When a user creates a content of Type MyType, a ContentPickerField for the new content should be set to contain some content, based on a value passed through querystring.

So, ContentPickerField should have an additional setting to work as DefaultValue, that may be set in the ContentDefinition to some token like {User.Content.User.Fields.MyCPF} or {Request.QueryString:myval}.

I already have some code for this I can propose.

**Comment by sebastienros** [comment]
The use cases surprise me but the solution is acceptable.

**Comment by MatteoPiovanelli** [comment]
Those are actually pretty common requirements we see for some not-quite-a-cms installations. We finally caved in rather than try weird workarounds. A similar thing should really be available for all ContentFields, I think. But I am closing this issue since you merged the PR in. Thank you.
