### ISSUE TITLE
support hierarchy of tenants

### ISSUE THREAD

**Issue by MatteoPiovanelli** [OrchardCMS/Orchard#8386]
Orchard as is doesn't support the following scenario:

Have an Orchard Multitenancy at www.mymultitenancy.com
Create a tenant Foo that you want to respond to www.foo.com
Create a tenant Bart that you want to respond to www.foo.com/bar

The way "redirection" is handled among the shells, a call to www.foo.com/bar is intercepted by Foo, while we want it to be intercepted by Bar. The same goes for www.foo.com/bar/*.

To make that possible, we propose to mark Foo with a boolean IsBaseHost that gives it a "lower priority" when trying to figure out what tenant should handle a request.
This can be handled in a way that breaks nothing, since that bool would default to false when no corresponding setting is found for a tenant, meaning that tenant would, after introducing the changes we propose, still behave exactly like before.

This would allow from a single Orchard Install to have more than one "base", each with potentially several "sub-tenants".

A PR is coming soon.

Care will have to be taken when using this setting:
In the example above, tenant Foo at www.foo.com cannot have its own content whose alias is 'bar', because the tenant Bar would respond to requests for it. This is the opposite of what happens currently.

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore/Shell/RunningShellTable.cs

**Comment by MatteoPiovanelli** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/54f9334aec344eb4fd387ea0db6d1a9a86aedee6/test/OrchardCore.Tests/Shell/RunningShellTableTests.cs#L126

@sebastienros 
This is the test you pointed out to me yesterday. I've run the same test for Orchard, and it passes. However, in Orchard, if you do `table.Add(settingsG)` before `table.Add(settingsA)` the test fails: this is the condition we were seeing in the case of our application.
I think it should still work in OCore, thanks to how `_shellsByHostAndPrefix` is built. Since `ImmutableDictionary` does not seem to be available in .NET 4.5.2 (the current framework version for Orchard.Framework), I'll figure out a work around. It may be enough to keep values in `_shellsByHost` sorted so that the shells with a RequestUrlPrefix are tested first.
