### ISSUE TITLE
Should lock be deleted from dictionary when DeleteDistributedLockRecord is called?

### ISSUE THREAD

**Issue by imranazad** [OrchardCMS/Orchard#8391]
Should the lock be deleted from the the dictionary when DeleteDistributedLockRecord is called?

https://github.com/OrchardCMS/Orchard/blob/1.10.3/src/Orchard/Tasks/Locking/Services/DistributedLockService.cs#L180

I don't understand why you'd want to keep a deleted lock in the dictionary? Currently the issue we're having is when task acquires a lock for say five minutes and then finishes it calls the DeleteDistributedLockRecord and then when a task runs again within the time the lock has been acquired it won't recreate the record in the database and as a result an exception is thrown:

https://github.com/OrchardCMS/Orchard/blob/1.10.3/src/Orchard/Tasks/Locking/Services/DistributedLockService.cs#L185

@DaRosenberg @sebastienros @jtkech any thoughts?

**Comment by jtkech** [comment]
Not so easy for me to remember the details ;)

But looks like you're right, seems that a lock is added once in the dico and then never removed even there is no more related record ...

Maybe remove the lock from the dico [before this line](https://github.com/OrchardCMS/Orchard/blob/1.10.3/src/Orchard/Tasks/Locking/Services/DistributedLockService.cs#L107)

Would you suggest a PR for this?

**Comment by imranazad** [comment]
@jtkech Thanks for getting back to me. Of course I'll create a PR.

**Comment by imranazad** [comment]
Will keep the issue opened once the PR has been approved and merged.

**Comment by imranazad** [comment]
@jtkech I can confirm your suggestion on the line works a treat! Thank you! As promised here is the PR: https://github.com/OrchardCMS/Orchard/pull/8394

So to recap since Orchard uses software locks to ensure the same task doesn't run simultaneously from two different servers.

When a task runs it creates a software lock and adds a record in the Orchard_Framework_DistributedLockRecorD table and in a dictionary so the lock doesn't have to be reacquired. The problem was that it wasn't deleting it from the dictionary so that meant when the same task ran again it would pick up the lock because it's already been acquired. Once the task had finished it attempted to delete the lock from the database but it was already deleted so that's why it was throwing the exception: https://github.com/OrchardCMS/Orchard/blob/1.10.3/src/Orchard/Tasks/Locking/Services/DistributedLockService.cs#L185. 

With the fix once the task is disposed the new line deletes the lock from the dictionary.

Can you please do the honours of a code review? :-)

Also just thinking about the impact of this change? Since we're just deleting an item in the dictionary and we've not touched any of the other logic I can't imagine this having any major impact. Of course the most obvious thing would be to make sure the tasks are running and completing and that the locks are being deleted from the database. Just wondered if you could think of anything else we might need to test?

Many Thanks

**Comment by imranazad** [comment]
Also @jtkech Would I be right in thinking with the current version of Orchard with the bug since the lock gets deleted from the database and not the dictionary it's possible that the same task would continue to run on say machine A whilst on machine B a new lock would be created for the same task and that would also run defeating the purpose of the distributed lock feature.

**Comment by jtkech** [comment]
@imranazad exactly, i will approve your PR
