### ISSUE TITLE
LogOn.cshtml: Html.CheckBox() throws exception if ModelState contains non-convertable value

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#8392]
When some malicious user try to programmatically logon to a tenant or simply it modifies the value of "rememberMe" input checkbox with 1/-1 we log an error.
The error is: 
System.InvalidOperationException: The parameter conversion from type 'System.String' to type 'System.Boolean' failed. See the inner exception for more information. ---> System.FormatException: 1 is not valid for Boolean.

It seems to be a MVC problem as shown there https://github.com/aspnet/AspNetWebStack/issues/233
For the moment (waiting for a low level MVC fix) in order to prevent spamming our logs I will remove the value from ModelState in the controller before the view is rendered if ModelState has errors. 
See related PR.

**Comment by sebastienros** [comment]
That's unfortunate. But will we do that any time some malicious payload can throw an exception?

**Comment by sebastienros** [comment]
A valid solution would be to find ways to disable logging for specific controllers, if this is what the problem is.

**Comment by HermesSbicego-Laser** [comment]
> That's unfortunate. But will we do that any time some malicious payload can throw an exception?

Not everytime for sure. But in this particular case we should, I think. Because we could have hundreds of log items (and we have for real) for this issue and I think that we should try to keep logs as clean as possible. The PR #8393 is the only way I found to prevent logging this kind of error.

> A valid solution would be to find ways to disable logging for specific controllers, if this is what the problem is.

The exception throws in the View when `Html.Checkbox()` automatically tries to bind the `Request`, not in the controller. I don't know a way to achieve what you are suggesting, by the way I don't think that it could be a good idea: we really want to disable logging for some specific controller, in this case the AccountController?

Please take a look to #8393, I think it's the best way to proceed in this particular case:
- because the LogOn Action takes explicit parameters and not a model, so we can't validate the model neither the parameter (the rememeberMe parameter value is `false`, the `ModelState["rememberMe"]` is in error)
- because rewriting the LogOn Action converting parameters in a Model is breaking and involves a lot of changes in themes/views alternates
