### ISSUE TITLE
Update content of a shape on the page

### ISSUE THREAD

**Issue by asemandeveloper** [OrchardCMS/Orchard#8401]
I have three shapes on my page. In the first shape, I show the user's profile.
In the second shape, I have several options to choose from. I want to change the content of the third form by selecting each option without changing or update the content of the first and second shapes.
what should I do?
Can I use Ajax? How?

**Comment by MatteoPiovanelli** [comment]
You could use ajax, sure. Include the js for it in one of the shapes. Have a controller whose actions you'd use to query what's in the third shape.

Depending on your specific needs, you may also just have all contents that you may show in the third form already loaded, and hide/show them based on the selected options.
