### ISSUE TITLE
Is the dev branch considered stable?

### ISSUE THREAD

**Issue by imranazad** [OrchardCMS/Orchard#8405]
Which branch should I use for production? Master or Dev? Is dev considered stable?

**Comment by huideaki** [comment]
I would like to know too, There hasnt been a release in over a year and theres is quite alot of change in dev that would help us. Is it stable enough to run Dev in a production environment ?

**Comment by sebastienros** [comment]
Yes, dev is stable now. We could start releasing 1.11. @BenedekFarkas is too busy

**Comment by BenedekFarkas** [comment]
Yes, I am unfortunately, but still lurking around here in the shadows! :)
Orchard 1.11 would be great and we actually need it too for a number of projects - I'd love to do something about that, so we'll see!
