### ISSUE TITLE
How to do DB Caching on Azure Appservice?

### ISSUE THREAD

**Issue by byhub** [OrchardCMS/Orchard#8408]
hi there, 

for orchard 1.10.3 on azure appservice, I believe azure redis cache is the only option. To use it, we need to enable Redis Cache and Redis Output Cache orchard features. How about database level caching? Considering there are many redundant db calls, it is well worth to use this functionality. How do we do it? I see "Microsoft Azure Database Cache" feature but I think it is a no more offered service by azure. How do you guys handle db caching in your production (for legacy orchard users)

Thx in advance!

**Comment by sebastienros** [comment]
No need to db cache if you have output cache enabled. That's the best perf improvement you can get, and db cache can just introduce caching issues, with stale inproc data. Then if you are using a single instance, you don't need Redis, just the default output cache feature. Use Redis with Output Cache only if you are using multiple instances.
