### ISSUE TITLE
NHibernate exception isn't handled.

### ISSUE THREAD

**Issue by vic-yes** [OrchardCMS/Orchard#8409]
I add some WCF services, and normally, If code during that request aborts the current transaction, error with code 99999999 will be returned and status is 400, but I found if I insert invalid data into DB, an error with Html format will be returned when the current transaction commits at the end of the request, and the status is 500, seems Orchard doesn't handle this exception. how can I handle it and return a 99999999 error?
![image](https://user-images.githubusercontent.com/11804807/91810683-e6b72800-ec60-11ea-8026-5b54b0483a48.png)
![image](https://user-images.githubusercontent.com/11804807/91810851-2ed64a80-ec61-11ea-89aa-5befda952991.png)

**Comment by sebastienros** [comment]
Looks like the error is intercepted by MVC and returns an HTML message.

**Comment by vic-yes** [comment]
@sebastienros , thank you for reply, it seems to be so, I thought Orchard should handle all of the exceptions in the **ExceptionHandler** class, but not. Do you know how to make the **ExceptionHandler** handle the exceptions caused by transaction commits automatically?

**Comment by sebastienros** [comment]
Not even sure we are responsible for this page. You can try to check if any cshtml file is currently rendering the error (Error.cshtml for instance). If that's the case then there should be a way to ignore it.
