### ISSUE TITLE
关于内容部分的简体中文和繁体中文的互换

### ISSUE THREAD

**Issue by OlziiNaran** [OrchardCMS/Orchard#8429]
我想做一个文本内容部分的简体中文和繁体中文的互换模块。需求是当站点的语言设置为简体中文时，需要将用户添加的繁体中文的文本内容转换为简体中文的文本内容，存入数据库中，并保留原始内容。请问，我应该如何开发这个模块？我主要不是很明白解决方案中的OrchardCore、OrchardCore.Module、OrchardCore.Module.CMS之间的依赖关系！？目前的思路步骤如下：
1、在OrchardCore中建立一个工程叫OrchardCore.Chinese.Abstractions，主要完成简体中文和繁体中文的特征；
2、在OrchardCore.Modules中创建OrchardCore.Chinese.Coding，并引用OrchardCore.Chinese.Abstractions，实现具体特征，并完成简体中文和繁体中文的互转方法，并实现转换的配置项；
3、OrchardCore.Modules.Cms什么都不做；
请老师们分析一下，我这样做对吗？
这里所指内容部分为：Title、Content、Text Field、Menu等，针对系统维护人员和内容维护人员录入的文本内容！
**Please help translate to english, thank you**

**Comment by Skrypt** [comment]
Translation from Google Translate : 

I want to make an interchange module between simplified Chinese and traditional Chinese for text content. The requirement is that when the language of the site is set to simplified Chinese, the text content of traditional Chinese added by the user needs to be converted into text content of simplified Chinese, stored in the database, and the original content is retained. Excuse me, how should I develop this module? I mainly don't understand the dependency between OrchardCore, OrchardCore.Module, OrchardCore.Module.CMS in the solution! ? The current thinking steps are as follows:
1. Create a project called OrchardCore.Chinese.Abstractions in OrchardCore, which mainly completes the features of simplified Chinese and traditional Chinese;
2. Create OrchardCore.Chinese.Coding in OrchardCore.Modules and reference OrchardCore.Chinese.Abstractions to realize specific features, complete the conversion method between simplified Chinese and traditional Chinese, and realize the configuration items for conversion;
3. OrchardCore.Modules.Cms does nothing;
Ask the teachers to analyze, am I doing this right?
The content referred to here is: Title, Content, Text Field, Menu, etc., for the text content entered by system maintenance personnel and content maintenance personnel!

Please help translate to english, thank you

**Comment by sebastienros** [comment]
I am sure someone will help translate this
