### ISSUE TITLE
Media Files Not Restricting File Types for Content Folder

### ISSUE THREAD

**Issue by burninatorsec** [OrchardCMS/Orchard#8434]
Hello, I was conducting a security assessment for a client who was using OrchardCMS. When using /Admin/Media/Add, the file types are restricted. However when OrchardCMS is used in combination with the TinyMCE html editor, and a file is uploaded that way, this bypasses the validation.  Is this expected behavior? Are the file type restrictions only to restrict what’s uploaded through the Orchard file upload widgets or is it to restrict file types uploaded to the media folder (no matter the source)? Thanks for your help.

![image](https://user-images.githubusercontent.com/68610637/100624898-ef67da80-32f1-11eb-89be-2b93a384aee3.png)
![image](https://user-images.githubusercontent.com/68610637/100624962-00185080-32f2-11eb-9b5f-8fd8e4b9113c.png)
![image](https://user-images.githubusercontent.com/68610637/100625012-0a3a4f00-32f2-11eb-8682-385de6670cf9.png)
![image](https://user-images.githubusercontent.com/68610637/100625031-10c8c680-32f2-11eb-932b-2041b7d43f5d.png)

**Comment by burninatorsec** [comment]
Also, is this related to https://github.com/OrchardCMS/Orchard/issues/1885? Thanks

**Comment by sebastienros** [comment]
@MatteoPiovanelli-Laser can you check on the latest version? (1.x branch)

**Comment by burninatorsec** [comment]
I should also mention my version is v.1.8.1.0.

**Comment by MatteoPiovanelli** [comment]
I just checked. It looks to be working fine in 1.10.x.
The setting appears to be different from the screenshot: I have to input allowed file extensions separated by commas (e.g. ".txt, .png"...).
![image](https://user-images.githubusercontent.com/19283945/101174469-359ba180-3644-11eb-9836-f3eaa231c4e4.png)

Then from a tinymce editor, hitting "import media" will cause me to go through the "normal" steps to import a media, that go through that same validation.
![image](https://user-images.githubusercontent.com/19283945/101174632-74315c00-3644-11eb-9b35-b3ceece9a47b.png)

![image](https://user-images.githubusercontent.com/19283945/101174701-84e1d200-3644-11eb-93cf-aabdb3278ac8.png)

![image](https://user-images.githubusercontent.com/19283945/101174742-91fec100-3644-11eb-9566-47e0b54a9621.png)

**Comment by burninatorsec** [comment]
To clarify, in my version, the settings will function correctly - even without commas between the allowed file types settings field - when using the uploader functionality in other areas of the site (such as Add Media, in the screenshot below). However, the problem is that it allows the dangerous file when uploading through MCE's editor. Here is it properly erroring in Add Media with the settings as I have them:

![image](https://user-images.githubusercontent.com/68610637/101294502-afb75c00-37e5-11eb-8bc4-9745a66e15f5.png)

But, just to be certain, I repeated my test with commas in the allowed file types list:

![image](https://user-images.githubusercontent.com/68610637/101294729-741d9180-37e7-11eb-84e8-fee3143f34b1.png)
![image](https://user-images.githubusercontent.com/68610637/101294742-88fa2500-37e7-11eb-8141-6092d7de5e6a.png)
![image](https://user-images.githubusercontent.com/68610637/101294750-91eaf680-37e7-11eb-9fd8-2b83ebb2a1c2.png)
![image](https://user-images.githubusercontent.com/68610637/101294758-9b745e80-37e7-11eb-8ab1-ac6556c8927f.png)
![image](https://user-images.githubusercontent.com/68610637/101294764-a4653000-37e7-11eb-9ffb-9cc44fbb9589.png)

Also - I have a previously unknown XSS vulnerability for Orchard CMS as well (I couldn't find a CVE for it, anyway). I would like to share information about this... is Github the right place for this or is there a separate security email?

Thank you for your help.

**Comment by sebastienros** [comment]
Please send the xss by email to sebastien.ros@microsoft.com

**Comment by sebastienros** [comment]
I confirmed that this issue has already been fixed in version 1.10.0.
