### ISSUE TITLE
dev branch does not build in VS2017

### ISSUE THREAD

**Issue by MatteoPiovanelli** [OrchardCMS/Orchard#8441]
https://github.com/OrchardCMS/Orchard/blob/0cadd5a916f080e0b1b6a9fa8f37cc51e94e1d3a/src/Orchard.Web/Modules/Orchard.Email/Services/SmtpMessageChannel.cs#L131

Visual Studio 2017 doesn't support c#8 features out of the box.
By cloning the dev branch, vs2017 is unable to build the solution. 

I think that the line I linked is the only place where we have those right now. It's work from @aaronamm , if I am not mistaken.

**Comment by sebastienros** [comment]
Feel free to remove these new c# features. Unless @BenedekFarkas added more in some razor files. I know it was a discussion we had.

**Comment by MatteoPiovanelli** [comment]
in #8458 we fixed this to allow the solution to build in VS 2017
