### ISSUE TITLE
Orchard is not working with swagger, wrong routes definition. 

### ISSUE THREAD

**Issue by witold-oles-s4d** [OrchardCMS/Orchard#8442]
I cannot make the orchard cms run with swagger because it seems that orchard does not follow swagger route policies in asp.net core 3.0.

I got following exception:

`The request matched multiple endpoints. Matches: \r\n\r\nOrchardCore.Contents.Controllers.AdminController.List (OrchardCore.Contents)\r\nOrchardCore.Email.Controllers.AdminController.Index (OrchardCore.Email)\r\nOrchardCore.Apis.GraphQL.Controllers.AdminController.Index (OrchardCore.Apis.GraphQL)\r\nOrchardCore.Sitemaps.Controllers.AdminController.Edit (OrchardCore.Sitemaps)\r\nOrchardCore.Contents.Controllers.AdminController.Edit `
it comes from:

`Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)\r\n   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)\r\n   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)\r\n   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)\r\n`

**Comment by MatteoPiovanelli** [comment]
From the namespaces, I would think this is an issue for https://github.com/OrchardCMS/OrchardCore . Am I correct?
Please close this issue in that case.
