### ISSUE TITLE
Nuget libraries update

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#8445]
As natural consequence of upgrading to framework 4.8 (see #8444 and #8007) we think that it's possible to upgrade libraries too to their Latest/Stable version.
The list of libraries taken from Nuget is:
- MVC/Razor
- Newtonsoft
- NHibernate (@sebastienros, it's not that simple, some interfaces have changed, we have not idea what the impact could be.)
- Autofac.* (@sebastienros, it's not that simple, some interfaces and even also some constructor have changed, we have not idea how to proceed. Any help would be appreciated https://autofaccn.readthedocs.io/en/latest/whats-new/upgradingfrom5to6.html)
- Castle.Core
- DotNetZip
- HtmlAgilityPack
- ImageResizer
- Log4Net
- Markdig.Signed
- WindowsAzure.*
- System.IdentityModel.Tokens.Jwt
- NUnit
- Microsoft.CodeDom.Providers.DotNetCompilerPlatform
- Microsoft.AspNet.WebApi.*
- Microsoft.Owin
- YamlDotNet
- StackExchange.Redis

Any help will be appreciated. Who is interested to help in order to speed up a PR, could ping us here.

Working on this at https://github.com/LaserSrl/Orchard/tree/feature/8445_LibrariesUpdate

**Comment by sebastienros** [comment]
MVC, Razor since that should be simple
YamlDoNet for security reasons

If it doesn't provide any useful benefit, then don't update. Can just cause harm otherwise.

**Comment by HermesSbicego-Laser** [comment]
I went a little further, and It seems to work fine for now (see branch above).
If you agree, I will try to upgrade libraries that do not generate compilation errors, leaving those "breaking" untouched.
Next I can try to upgrade "breaking" libraries in a separate branch, hoping someone could partecipate and help. 
I think that, even if it will be challenging, we should try to stay as updated as possibile.
What do you think about?

Libraries updated to latest version
MVC
Razor
WebPages
Newtonsoft
Microsoft.AspNet.WebApi.*
ImageResizer
Log4Net
SharpZipLib
Markdig.Signed
YamlDotNet (Code has been changed: see Consume method)
Microsoft.Owin*
