### ISSUE TITLE
Error in LocalizationPart validation

### ISSUE THREAD

**Issue by ElenaRepository** [OrchardCMS/Orchard#8463]
Hi,

We realised that the validation of LocalizationPart had some problems under the tests made to replicate the error

-	 Create a content that has LocalizationPart and add an obligatory part
-	 Add to your tenant other languages, such as Italian and French

During the creation of the content

-	 Select a language other than the language of default, we assume to select Italian
![image](https://user-images.githubusercontent.com/50620495/114190649-d29c7d00-994b-11eb-93fb-3c6d7c457dc2.png)

-	 After publishing the required value, the selected value within the dropdown remains unchanged.
![image](https://user-images.githubusercontent.com/50620495/114190766-f495ff80-994b-11eb-92b3-0e14a5989be2.png)

The same thing happens when new translation is being created

**Comment by HermesSbicego-Laser** [comment]
closed via #8464
