### ISSUE TITLE
Cached pages don't work with forms and their RequestVerificationToken when navigation is authenticated

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#8469]
Because OutputCache stores the RequestVerificationToken for authenticated users also, cached pages fails to POST data.

**Comment by sebastienros** [comment]
I remember how we had decided to handle XSRF tokens, by actually not caching any page that generates one. Then anything with forms would not be cached. The solution we have was to issue forms using ajax such that we could still cache most of the page.

I don't know what it's not applied anymore, but that might be a better solution? If it's possible to see that the outgoing cookie is set. Can you confirm the logic? And that it still works with comment forms?

**Comment by HermesSbicego-Laser** [comment]
fixed via #8470
