### ISSUE TITLE
Flag “Exclude children” for Taxonomies

### ISSUE THREAD

**Issue by ElenaRepository** [OrchardCMS/Orchard#8480]
Hi,

We found a problem with the management of the Has Term filter in the query, with the steps below to check the error.

After creating a taxonomy and attaching it to a content, we select 2 child terms, one which has other child terms within it

![image](https://user-images.githubusercontent.com/50620495/120204738-70fcde80-c229-11eb-829b-d2cd4bd6aa73.png)

Let us create the query by selecting ‘Is all of’ and the two terms we have previously selected, without selecting relatives.

![image](https://user-images.githubusercontent.com/50620495/120204787-7ce8a080-c229-11eb-9d9b-8a16b71b017b.png)

The query will answer with ‘no outcome’, this because currently all the selected terms and their children are taken, so in this case the filter will search the items which contain "child a" "a 1" "child b"

Adding a flag as “Automatically excludes children terms in filtering”, that with default to false continues to work as it does now, instead of true, it filters only for selected terms and not for children.

**Comment by HermesSbicego-Laser** [comment]
closed via #8481
