### ISSUE TITLE
`Shape type 'MyCustomPart' not found` exception

### ISSUE THREAD

**Issue by dafergu2** [OrchardCMS/Orchard#8485]
If you create a custom part in a module but do not create a `MyCustomPart.cshtml` file, a `Shape type'MyCustomPart` not found` exception will be thrown when it is added to a content type without a custom display shape template.

Steps to reproduce:

1) Create a new module
2) Add a custom part
3) Add a custom display driver (may be optional)
4) Do not add a display shape template
5) Add a custom edit shape template (may be optional)
6) Add the part to the standard liquid content type (I also opened and saved the content item in the admin editor)
7) Navigate to a page that has a liquid content item on it (in my case, the liquid content item was in a flow part on a liquid page).

The reason I didn't add a display shape template is because I didn't need to render the part during a normal display.  It is similar to the Seo part in that it collects metadata and doesn't necessarily need to display content.  In my case, I have a custom `FlowPart.cshtml` that looks for the part and adjusts its rendering accordingly.  Thus, I never needed a display shape template.

If the part is never actually rendered, then there is no error.  Since the liquid content item will try to render all the display shape templates by default (and I hadn't overridden the liquid widget display shape template), the liquid widget threw the exception and my test widget did not.

My workaround/fix is to create an empty `MyCustomPart.cshtml` file in my module Views folder.

My question is, should the exception be thrown or should the part be rendered using a default display shape template just as if I had created the part in the Admin UX.

**Comment by MatteoPiovanelli** [comment]
Is this issue about Orchard or Orchard Core?
Correct me if I'm wrong, but I am thinking the latter, since you are talking about Display drivers and Liquid.

**Comment by dafergu2** [comment]
@MatteoPiovanelli-Laser @sebastienros Yes, my apologies, I didn't realize I was in the wrong repository when creating the issue.
