### ISSUE TITLE
Projection part default value

### ISSUE THREAD

**Issue by ElenaRepository** [OrchardCMS/Orchard#8489]
It is often the case that we need all projections of a some type to have common settings. 
In order to ease this operation, we have decided to add a setting to the projectionPart that allows us to overcome this difficulty.
In the setting, it would be useful to have not only the default query, which is already evaluated during the creation phase, but also the "static" parts such as 
- Items to display 
- Offset 
- Maximun items 
- Suffix 
- Show pager

in order to have a good starting situation for content creation. It would also be useful for these values to be able to choose to have them edited or not.
It might also be useful to have a filter which, in the case of a lot of queries, allows only those queries appropriate to the type of content to be selected.
Finally, this setting will definitely require import-export management.

**Comment by MatteoPiovanelli** [comment]
I'm closing this because the corresponding PR has been merged
