### ISSUE TITLE
HtmlDecode missing

### ISSUE THREAD

**Issue by AndreaPiovanelli** [OrchardCMS/Orchard#8500]
https://github.com/OrchardCMS/Orchard/blob/4e69612d90175d28249a7051d938a9e25e826344/src/Orchard.Web/Modules/Orchard.Tokens/Providers/TextTokens.cs#L24
HtmlDecode token needed in case I need to tokenize a field containing html code (e.g. TextField with flavour = Html).

**Comment by MatteoPiovanelli** [comment]
I'm closing this because the corresponding PR was merged
