### ISSUE TITLE
SSL redirect should be permanent

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#8502]
The Orchard.SecureSocketsLayer module redirects http calls to https with a 302 temporary redirect.
Search engines consider both pages http ones (as they are temporary redirected) and https also, so they result as duplicated pages, as well SEO Site Audit tools mark them as errors (because duplicated).

**Comment by sebastienros** [comment]
This should being a setting, because when developing it could be an issue since it's hard to remove permanent redirections.

**Comment by HermesSbicego-Laser** [comment]
We agree. The setting is in #8503

**Comment by MatteoPiovanelli** [comment]
I'm closing this because the PR was merged.
