### ISSUE TITLE
Published content is not synced with all app service instances

### ISSUE THREAD

**Issue by sivakumar715** [OrchardCMS/Orchard#8504]
we have developed a site using orchard CMS and deployed in azure app service with 2 instances by pointing to a single database. 
Trying to publish a new content item from admin (https://demo-host/Admin/Contents/Edit/609) and new content is accessible only from one instance.

Instance1 - new content is loaded properly (https://demo-host/registration/test-article4-08092021)
Instance2 - giving 404 error

suggest us if anyone faced similar content sync issue with Orchard CMS.

**Comment by LorenzoFrediani-Laser** [comment]
i think you must enable feature "Alias Updater" , the page will be available after task execution (the default run time is every minute)

**Comment by sivakumar715** [comment]
thanks @LorenzoFrediani-Laser . It's working fine now after enable the feature "Alias Updater".

**Comment by oryza-ivt** [comment]
Hi, currently I have almost the same setup : 2 web instance which point to single database but in on premise environment (VM).
I am facing the same issue, and after enable "Alias Updater" module, it looks like it solved. But, I don't know the exact timing of it, sometimes it takes about 1 min, sometimes way longer, sometimes require to first access the page on origin instance (usually for new content), Is there any other configuration / feature / module that affect this feature? (orchard cache, or message bus or something else)
