### ISSUE TITLE
Generic "edit content wrapper" permission at front end

### ISSUE THREAD

**Issue by ElenaRepository** [OrchardCMS/Orchard#8506]
We thought of adding a specific permission to improve the performance logic.
Since the specific search is very costly, we can add a generic check on the new role.
Only after checking if the user has associated the generic role then we check the specific role for the content.

**Comment by sebastienros** [comment]
I am not in favor of custom permission for this one, because there might be conflicts with the Edit permission. And the suggested PR breaks the current behavior.

> Since the specific search is very costly

Can you explain?

**Comment by ElenaRepository** [comment]
Given our needs, we decided to close the issue and implement the functionality in one of our modules.
