### ISSUE TITLE
ProjectionPart QueryLayoutRecord edit link not working properly

### ISSUE THREAD

**Issue by AndreaPiovanelli** [OrchardCMS/Orchard#8514]
I was applying a patch to MenuWidgets to have the same edit link for menus, when I noticed the link doesn't work properly: when you change the selected value in the select list containing the queries, the edit link isn't updated with the id of the new selected query.
The file I'm talking about is "Modules\Orchard.Projections\Views\EditorTemplates\Parts\ProjectionPart.cshtml".
I'm patching the issue and opening a PR in the next days.
Meanwhile, I'm planning the same behaviour (edit link to "...Navigation/menuId=x") for "Core\Navigation\Views\EditorTemplates\Parts.MenuWidget.Edit.cshtml".

**Comment by HermesSbicego-Laser** [comment]
Closed via #8515
