### ISSUE TITLE
Extend Users and  Roles capabilities and settings

### ISSUE THREAD

**Issue by HermesSbicego-Laser** [OrchardCMS/Orchard#8516]
Starting from dev, we will work on adding these capabilities to Orchard.Users and Orchard.Roles Module:
1. Set a User to forcely change its own password at next LogOn;
2. Prevent reuse of last n password on password change; 
3. Suspend accounts that didn't logon within last n days;
3.1. the SiteOwner will never be suspended;
3.2. a flag over specific Users will prevent suspension for them;
4. Resend a confirmation e-mail if an "email unconfirmed" user try to re-register;
5. Have a dynamic permission to Assign roles : taking the idea from "Assign Role - {0}" implementation of OrchardCore https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore/OrchardCore.Roles.Core/CommonPermissions.cs

**Comment by sebastienros** [comment]
> Resend a confirmation e-mail if an "email unconfirmed" user try to re-register

Should do some rate limiting for this one.

**Comment by MatteoPiovanelli** [comment]
> Have a dynamic permission to Assign roles : taking the idea from "Assign Role - {0}" implementation of OrchardCore

Working on that now.
Accessing a User's Edit view requires the ManageUsers Permission. The "Assign Role - {0}" permission naturally wouldn't imply that, so I would add a specific view for that functionality. Accessing that would require a way to inject a link to that action in the table of users:
![image](https://user-images.githubusercontent.com/19283945/150520646-a87238ac-1dca-4c45-84c1-2d4a0042b957.png)

**Comment by MatteoPiovanelli** [comment]
I think we merged everything proposed relating to this issue, so I'll close it.
