### ISSUE TITLE
LayoutWidget widget children are not saved properly

### ISSUE THREAD

**Issue by AndreaPiovanelli** [OrchardCMS/Orchard#8533]
After creating a LayoutWidget and adding a Widget inside the layout, when saving the LayoutWidget its children didn't have their container set properly. This causes a warning in the "Widgets" page at backoffice, as the child widgets were considered orphans (if it's a new layout, the container doesn't exist yet when saving its children).

**Comment by MatteoPiovanelli** [comment]
fixed by #8534
