### ISSUE TITLE
Impossible to replace "missing" media because DeleteFile throws a exception

### ISSUE THREAD

**Issue by AndreaPiovanelli** [OrchardCMS/Orchard#8554]
https://github.com/OrchardCMS/Orchard/blob/ffb56e684ce39ef65387793730d3c6d5ecfcf3ed/src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/ClientStorageController.cs

When trying to replace a "broken" media file (Action Replace in ClientStorageController), if the file has been deleted from filesystem, the process stops because a exception is thrown (by FileSystemStorageProvider.DeleteFile(string)), so the media can't be replaced.

**Comment by Skrypt** [comment]
Could you share an error log example as a reference?

**Comment by AndreaPiovanelli** [comment]
> Could you share an error log example as a reference?

The error status (the one displayed to the user when uploading the replacement file) is the following:

> File Foto\image.jpg does not exist

The error log is:

> 2022-04-08 09:04:31,656 [43] Orchard.MediaLibrary.Controllers.ClientStorageController - TenantName - Unexpected exception when uploading a media. [BaseHttpUrl/Orchard.MediaLibrary/ClientStorage/Replace]
> System.ArgumentException: File Foto\image.jpg does not exist
>    at Orchard.FileSystems.Media.FileSystemStorageProvider.DeleteFile(String path) in OrchardRoot\src\Orchard\FileSystems\Media\FileSystemStorageProvider.cs:line 254
>    at Orchard.MediaLibrary.Services.MediaLibraryService.DeleteFile(String folderPath, String fileName)
>    at Orchard.MediaLibrary.Controllers.ClientStorageController.Replace(Int32 replaceId, String type)

The file Foto\image.jpg is the original file, the one missing from filesystem. If you import a new media with the same file name, the "old" media (the broken one) works again properly (and you have two identical media files displayed, because both reference the same file in the filesystem). This is a sort of workaround to the issue, because afterwards you may delete the new media getting the old one to work again.

**Comment by AndreaPiovanelli** [comment]
Closing the issue because PR #8555 has been successfully merged.
