### ISSUE TITLE
Issue with queries in Orchard v.1.10.3.0

### ISSUE THREAD

**Issue by johnmangam** [OrchardCMS/Orchard#8564]
Hi,

We have an issue with these queries that get hanged on our sql server that come from this Orchard 1.10.3 app:

Query:
```
(@p0 int)SELECT scheduledt0_.Id as Id18_0_, scheduledt0_.TaskType as TaskType18_0_, scheduledt0_.ScheduledUtc as Schedule3_18_0_, scheduledt0_.ContentItemVersionRecord_id as ContentI4_18_0_ FROM Scheduling_ScheduledTaskRecord scheduledt0_ WHERE scheduledt0_.Id=@p0
```

```
(@p0 int)select aliasrecor0_.Id as Id17_, aliasrecor0_.Path as Path17_, aliasrecor0_.RouteValues as RouteVal3_17_, aliasrecor0_.Source as Source17_, aliasrecor0_.IsManaged as IsManaged17_, aliasrecor0_.Action_id as Action6_17_ from Orchard_Alias_AliasRecord aliasrecor0_ where aliasrecor0_.Id>@p0 order by aliasrecor0_.Id asc
```

We don't even get to see a log entry for this issue. Any idea how we could resolve this?

Thank you.

**Comment by sebastienros** [comment]
Is this always with these exact queries or randomly others?
If these are just these ones, try to run them in SQL directly and see how the query plan can be optimized. It might just be that you need to add an index in the db to make them faster depending on the size of the tables.

**Comment by johnmangam** [comment]
Thanks a lot, @sebastienros 

In fact, it's not a performance tuning issue. The query is not actually doing anything - there is no read, write or CPU activity. It looks like a session the application stops using, but does not close.

Could you shed some light on this issue, please?

**Comment by sebastienros** [comment]
> get hanged on our sql server

It's hanged, what does it mean for you? My understanding of "hanged on our sql server" is that sql server can't finalize it. You seem to say it's not the issue.
