### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by x7-7** [OrchardCMS/Orchard#8604]
Do you have an email to report security vulnerabilities?

**Comment by sebastienros** [comment]
Please use this file: https://github.com/OrchardCMS/OrchardCore/blob/main/SECURITY.md

**Comment by sebastienros** [comment]
@MatteoPiovanelli-Laser Would you mind joining a triage meeting so we can talk about this issue?

**Comment by MatteoPiovanelli** [comment]
@sebastienros sorry, I wasn't online last night.
If whatever the issue was about is still a thing, could you send an email to me and @HermesSbicego-Laser ?
