### ISSUE TITLE
Setting CurentCulture when entering the page based on localized 'Page' Content Type

### ISSUE THREAD

**Issue by Vaclav-Volek** [OrchardCMS/Orchard#8615]
If you have a multi-language website, some translations are done through LocalizationPart and some through .po files or layers depending on the culturecode rule. What is the best way to set CurentCulture and FrontEnd cookies if I access a web page directly from the internet using a link that leads to a 'Page' ContentType with LocalizationPart? If the culture of this ContentItem doesn't match the CurrentCulture, I get a **mix of different languages on the page**.

For example, I have an cs-CZ and en-US multi-language website with a default site culture of cs-CZ. Let's take the example that I access a page based on 'Page' Content Type with LocalizationPart that has created two language versions (en-CZ and en-US). If I access the Czech version of this page and I don't have set FrontEnd cookies to en-US, the localization works as it should be because the Czech version is set as defalut.

However, if I access the Czech version and have cookies set to en-US, or access the English version of the page without set up FrontEnd cookies to en-US, I get a mix of Czech and English text on the generated web page. Some of the text is generated using .po files and layers depending on the culturecode rule. Another is based on LocalizationPart.

_For example, I create an English version (/contacts) and a Czech version (/kontakty) of the page. The default site culture of the website is cs-CZ. Petr will share '/contacts' on Twitter. Hans will click on this shared link and he get to the '/contacts' page, where only the BodyPart and TitlePart of this ContentItem will be in English but everything else will be in Czech._

I solved this by creating an OnGetDisplayShape event in the LocalizationPartHandler.

```
OnGetDisplayShape<LocalizationPart>((context, part) => CheckCurrentCulture( part));
```

 Here, for the 'Page' ContentType, I test if WorkContext.CurrentCulture is equal to LocalizationPart.Culture and if I am not in Admin site. If they don't equal, I set WorkContext.CurrentCulture to localizationPart.Culture.

```
if ( _services.WorkContext.CurrentCulture != localizationPart.As<ILocalizableAspect>().Culture)
  {
     _services.WorkContext.CurrentCulture = localizationPart.As<ILocalizableAspect>().Culture;
  }
```

And I set the FrontEnd cookies as needed.

So far, this solution works. For example, when someone from outside comes to the English version of 'Page', it automatically sets the cookies and CurrentCulture to en-US and shows all .po translations in English. And it show layers with en-US culturecode  rule.

Is there any way to solve this better? Thanks

**Comment by MatteoPiovanelli** [comment]
See here:
https://github.com/OrchardCMS/Orchard/blob/ca86ec98316f6fa3a3b561cf83eae98b14988dae/src/Orchard/Localization/Services/CurrentCultureWorkContext.cs#L29

CurrentCulture is based on implementations of ICultureSelector.

What we did here:
https://github.com/LaserSrl/Laser.Orchard.Platform/blob/3b09e6924e88cb8036bc1cac0889d8973006b03b/src/Modules/Laser.Orchard.CulturePicker/Services/ContentCultureSelector.cs#L32
Was implement our own with an high enough property, so that the currently displayed content would be the one "dictating" the culture for the various elements (layers and such) being displayed. That's in one of our modules, tested on our fork of Orchard, so it may take some work to make it work on 1.10.x.

**Comment by Vaclav-Volek** [comment]
Thank you, this is a very good solution.

The disadvantage is that I have to get the ContentItem on the route /contents/item/display/{id} from the database one more extra time. Just to find out the language version, if it has one.
So my first thoughts were how to avoid this.

But this is a very good solution, so I will do it in a similar way. 
Thank you

**Comment by MatteoPiovanelli** [comment]
That query is actually cached for you behind the scenes by Orchard, so it shouldn't hit the db again.
