### ISSUE TITLE
For accessing JS or CSS or ico, the error: The page cannot be displayed because an internal server error has occurred.

### ISSUE THREAD

**Issue by johnmangam** [OrchardCMS/Orchard#8618]
The Orchard CMS page loads but not the CSS / JS / ico files.

When I try to access them I get the error: The page cannot be displayed because an internal server error has occurred.

**Comment by MatteoPiovanelli** [comment]
Hello,

We'll need more details than this, if possible.

Are you having this issue on the backend or the frontend?
Is any theme active?
What version of Orchard are you using?

Last I checked, both dev and 1.10.x worked out of the box, so any more details you could provide on this error would be helpful

**Comment by johnmangam** [comment]
Hi @MatteoPiovanelli-Laser 

Instead of the default c:\ on the IIS, I have configured the website for a website folder on D drive. The website loads well. 

Issues on the frontend. The application loads but js, css, ico, png do not get loaded. 

When I try to access them, I get the error: The page cannot be displayed because an internal server error has occurred.

The current theme is: **Terra**

The version of Orchard CMS is **Orchard v.1.9.2.0**

Running on **IIS version 10.0.20348.1**

**Part of web.config:**

`<system.web>
<authentication mode="Forms">
            <forms loginUrl="~/Users/Account/AccessDenied" timeout="2880"/>
        </authentication>
        <customErrors mode="Off"/>
        <pages>
            <namespaces>
                <add namespace="System.Collections.Generic"/>
                <add namespace="System.Linq"/>
                <add namespace="System.Web.Mvc"/>
                <add namespace="System.Web.Mvc.Ajax"/>
                <add namespace="System.Web.Mvc.Html"/>
                <add namespace="System.Web.Routing"/>
                <add namespace="System.Web.WebPages"/>
                <add namespace="Orchard.Mvc.Html"/>
            </namespaces>
        </pages>
    </system.web>    
    <system.webServer>
        
        <validation validateIntegratedModeConfiguration="false"/>
        <modules runAllManagedModulesForAllRequests="false">
            <remove name="OutputCache"/>
            <remove name="WarmupHttpModule"/>
            <add name="WarmupHttpModule" type="Orchard.WarmupStarter.WarmupHttpModule, Orchard.WarmupStarter, Version=1.9.2, Culture=neutral"/>
        </modules>
        <handlers accessPolicy="Script">
            
            <clear/>
            
            <add name="NotFound" path="*" verb="*" type="System.Web.HttpNotFoundHandler" preCondition="integratedMode" requireAccess="Script"/>
            
            <remove name="ExtensionlessUrlHandler-ISAPI-4.0_32bit"/>
            <remove name="ExtensionlessUrlHandler-ISAPI-4.0_64bit"/>
            <remove name="ExtensionlessUrlHandler-Integrated-4.0"/>
            <add name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness32" responseBufferLimit="0"/>
            <add name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness64" responseBufferLimit="0"/>
            <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0"/>
        </handlers>
        
    <httpErrors errorMode="Detailed" existingResponse="PassThrough"/> 
        <security>
            <requestFiltering>
                
                <requestLimits maxAllowedContentLength="67108864"/>
            </requestFiltering>
        </security>
		<staticContent>
			<remove fileExtension=".woff" />
			<mimeMap fileExtension=".woff" mimeType="application/font-woff" />
			<remove fileExtension=".js" />
			<mimeMap fileExtension=".js" mimeType="text/javascript" />
			<remove fileExtension=".svg" />
			<mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
			<mimeMap fileExtension=".mp4" mimeType="video/mp4" />
		</staticContent>
    </system.webServer>`

Thank you.

**Comment by MatteoPiovanelli** [comment]
Two configurations that sometimes tripped things up on some servers I've seen:
 - MimeType configurations on IIS
 - Setting permissions for the application pool user on the folders under Orchard.Web.

Your specific setup (having the site in a folder under D:) is not an issue at all, and it's actually how I usually have things configured.

**Comment by johnmangam** [comment]
That's very helpful @MatteoPiovanelli-Laser 

Thank you so much.
