### ISSUE TITLE
Retry the connection with SQL Server where framework is stored

### ISSUE THREAD

**Issue by johnmangam** [OrchardCMS/Orchard#8619]
Hi,

The Orchard app that lost connection to its framework SQL Server doesn't seem to reconnect once failed. 

Could be a bug in the Orchard CMS 1.9.2 ?

Once it  has a connectivity issue with the SQL server, it gives 404 error. Only after I restart the app in the IIS it starts working.

Thank you.

**Comment by sebastienros** [comment]
SQL Server connections string can have "retry connections" arguments, maybe you could try that if the connection with your server is spotty.

**Comment by HermesSbicego-Laser** [comment]
We faced the same problem some time ago in one of our deploy. 
What I suggest is:
1. Ensure that the DBServer is live when the tenant attempt to start and tries to acquire the connection to the Database; 
2. Increase in the `Orchard.Web\Config\HostComponents.config` the number of retries when a tenant can't be loaded
```
<Component Type="Orchard.Environment.DefaultOrchardHost">
        <Properties>
          <!-- The number of retries when a tenant can't be loaded -->
          <Property Name="Retries" Value="1"/>
          <Property Name="DelayRetries" Value="true"/>
        </Properties>
</Component>

```
