### ISSUE TITLE
Create an new release

### ISSUE THREAD

**Issue by mwentz** [OrchardCMS/Orchard#8634]
I propose the creation of a new release. It's been two and a half years since the last release, and unfortunately with the last release the code is running on .NET 4.5.2 which is [no longer supported](https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/). 

Let me know how I can help!

Edit: removed a bunch of incorrect information per @sebastienros. See his comment below for what the release(s) should be.

**Comment by sebastienros** [comment]
> from the subset above

__1.10.x__ branch is the base for 1.10.4 release
__dev__ is the base for 1.11 release

These are two distinct releases. We can start releasing 1.10.4, then merge it to dev and release 1.11.

**Comment by mwentz** [comment]
Is there a release checklist for O1 like [this one for Orchard Core](https://docs.orchardcore.net/en/latest/docs/topics/publishing-releases/)?

**Comment by mwentz** [comment]
I'm trying to figure out how the 1.10.X and dev branches relate to the [1.10.4 Milestone](https://github.com/OrchardCMS/Orchard/milestone/39?closed=1). Many of the issues in the 1.10.4 milestone have commits into the dev branch, not the 1.10.X branch.

If the 1.10.X branch is seen as stable, I think it makes sense to choose a point in the 1.10.X branch, apply the 1.10.4 tag there and create a release. I think that would then mean that a number of the issues in the 1.10.4 milestone would then be moved to the dev milestone. Once that's done, all the issues in the 1.10.X branch related to the 1.10.4 release can be changed to the 1.10.4 milestone.

One commit that I'm seeing in the dev branch that looks like it might want to be part of a 1.10.4 release is 0a82721968232b07354edcaac63a9ccea02220c6. I don't use ClickToBuild so I don't know how critical that change is.

**Comment by sebastienros** [comment]
All the issues assigned to 1.10.x and closed can be assigned to 1.10.4.
If an 1.10.x issue is closed but fixed in the dev branch then it should be assigned to dev.

The 1.10.x branch should be merged into dev to ensure all the fixes in 1.10.4 are reflected in dev.

**Comment by BenedekFarkas** [comment]
We'll release 1.10.4 soon, from the 1.10.x branch, then merge that into dev and work towards releasing 1.11.
