### ISSUE TITLE
Migrate CI builds from TeamCity to GitHub Actions

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#8683]
CI builds are currently executed by [the public TeamCity server](https://teamcity.jetbrains.com/project/Orchard) provided by JetBrains for free for OSS. Let's move everything to GitHub Actions for better integration (with GH) and maintainability, potentially also adding PR builds.

Current builds are structured as follows (each of them restore NuGet packages and then call a specific target on Orchard.proj):
1. Main builds
    1. Continuous build - Major version: dev branch on every commit, "Build" target.
    2. Continuous build - Major version: 1.10.x branch on every commit, "Build" target.
    3. Nightly build - Major version: dev branch at midnight, "Spec" target.
    4. Nightly build - Major version: 1.10.x branch at midnight, "Spec" target.
    5. Release: master branch on every commit, "Build" target, zip packages (Source and Web distribution) published as artifact.
2. Major version (dev branch at midnight):
    1. Build and SpecFlow Tests: "Compile" target, then calling NUnit on `*.Specs.*.dll`.
    2. Build and Unit Tests: "Compile" target, then calling NUnit on `*.Tests.*.dll`.
3. Minor version: Same as the previous, but 1.10.x branch.

**Comment by BenedekFarkas** [comment]
There are a few dozen unit tests that are failing to initialize due to breaking changes as well as a dozen or so that are failing the assertion, so I'm working on those too.

**Comment by BenedekFarkas** [comment]
I've paused the whole project in TC for now, because missing tooling causes all the builds to fail.

**Comment by sebastienros** [comment]
> I've paused the whole project in TC for now

May as well delete it, it just doesn't work and we'll never use it again

**Comment by BenedekFarkas** [comment]
Sure, we don't need it anymore when the GitHub Actions migration is complete. I'm just keeping it as a backup for now - it would be better to have something to compare the results with, but we probably won't be able to get it working again.

**Comment by BenedekFarkas** [comment]
Fixed as part of #8686 and #8684, see this comment: https://github.com/OrchardCMS/Orchard/issues/8686#issuecomment-1985507899
