### ISSUE TITLE
Upgrade Orchard.Email from using SmtpClient

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard#8691]
As stated on [`System.Net.Mail.SmtpClient`'s official documentation page](https://learn.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netframework-4.8#remarks):

> We don't recommend that you use the SmtpClient class for new development because SmtpClient doesn't support many modern protocols. Use [MailKit](https://github.com/jstedfast/MailKit) or other libraries instead. For more information, see [SmtpClient shouldn't be used](https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md) on GitHub.

For example, SendGrid deprecates support for TLS 1.0 and 1.1 on the 5th of June.

**Comment by dministro** [comment]
I'm starting to work on this.

**Comment by BenedekFarkas** [comment]
Great!
