### ISSUE TITLE
Back LocalizationPart's LazyFields with Infoset

### ISSUE THREAD

**Issue by MatteoPiovanelli** [OrchardCMS/Orchard#8692]
The `LazyField`s in `LocalizationPart` are "backed" by information in the `LocalizationPartRecord`. In the `Loader` and `Setter` for those `LazyField`s we are currently referring directly to properties of the Record.
https://github.com/OrchardCMS/Orchard/blob/610b3c4f53ce9a4bdbe26a5a095bd606bfabc811/src/Orchard.Web/Modules/Orchard.Localization/Handlers/LocalizationPartHandler.cs#L32
As a consequence, whenever there is a `ContentItem` that has a `LocalizationPart` and we need to access one of those properties, a query has to be performed. This happens often when displaying multi-language websites that rely on localized content and widgets: we easily end up having 10+ queries for that to visualize a simple page.

It seems trivial to use `Store`/`Retrieve` methods in the `Loader` and `Setter` for those `LazyField`s. 
I have a PR coming soon for this. I've tested it a little, and it seems to work for all cases I've put it through, but localization is a complex topic so I'm not yet 100% sure I've covered all corner cases.

**Comment by MatteoPiovanelli** [comment]
For example, I worry about import/export scenarios

**Comment by sebastienros** [comment]
I don't recall any reason it's not in the infoset.

**Comment by sebastienros** [comment]
Maybe run the specflow tests (based on Benedek's changes)

**Comment by MatteoPiovanelli** [comment]
Leaving this open for the results of the tests

**Comment by MatteoPiovanelli** [comment]
Specflows seem fine.
To be fair, I'm not sure they involve localization.
I'm closing this issue anyway.
