### ISSUE TITLE
Adding scale parameter to ResizeMediaUrl function

### ISSUE THREAD

**Issue by dbertolin** [OrchardCMS/Orchard#8712]
https://github.com/OrchardCMS/Orchard/blob/274b4416ec2a9dd6794207ffd7868cf7f706f866/src/Orchard.Web/Modules/Orchard.MediaProcessing/Shapes/MediaShapes.cs#L31

In certain cases we got messed images from ResizeMediaUrl call: images were grainy when resized
We need to add scaling as an optional parameters to ResizeMediaUrl  function.

**Comment by HermesSbicego-Laser** [comment]
fixed via #8713
