### ISSUE TITLE
Password encryption in settings.txt file

### ISSUE THREAD

**Issue by areghunandanan** [OrchardCMS/Orchard#8731]
Hi,

We are using version 1.8.1 of Orchard, and our connection string is in the Settings.txt file as plaintext. We now have a requirement to encrypt this connection string. Are there any subsequent versions of Orchard that supports this?

Also, we could not find version 1.8.1 source code in github. Could you please provide the link?

Thanks,
Anish

**Comment by sebastienros** [comment]
You can create a custom implementation of `IShellSettingsManager` like this one: https://github.com/OrchardCMS/Orchard/blob/4043df7a0d158dfc70cea65480b61fbd8191bbb3/src/Orchard/Environment/Configuration/ShellSettingsManager.cs

The during load/save events you can use a private key to do the encryption.

There are tags for each release: https://github.com/OrchardCMS/Orchard/tree/1.8.1

![image](https://github.com/OrchardCMS/Orchard/assets/1165805/7d333e94-d8ce-4bdb-afc9-7aaafc5be376)

**Comment by BenedekFarkas** [comment]
@areghunandanan please let us know if you've got something regarding connection string encryption, I'll close this for now.
